[quote.epigraph, , Heb. 7:25]
____
Therefore He is also able to save to the uttermost
those who come to God through Him.
____

== Forward

Robert Barclay (1648–1690) was a Scottish Quaker,
and one of the most eminent writers among the early Society of Friends.
His [.book-title]#Apology for the True Christian Divinity# was first published in 1675,
and came to be considered the definitive exposition and
defense of Quaker principles for the next 200 years.

Barclay was born into opulence and educated in
some of the finest schools of the time,
where his natural genius gained the admiration of both teachers and peers.
In addition to English, he was early a master of the Greek, Hebrew, French,
and Latin languages,
and so excelled in his studies that his uncle
(the Rector of the Scotts College at Paris)
offered to make him his heir.
But at seventeen years of age, upon entering a meeting of the people called Quakers,
Robert Barclay said, "`I felt a secret power among them which touched my heart.`"
And as he continued with them,
he "`came to receive and bear witness of the Truth,`" not being convinced, he said,
"`by strength of argument, or by a particular discussion of each doctrine,
but by being secretly reached by Life.
And as I gave way to it, I found the evil weakening in me and the good raised up,
and so I became thus knit and united to this people,
hungering more and more after the increase of the Power and
Life of Christ whereby I might feel myself perfectly redeemed.`

The [.book-title]#Apology for the True Christian Divinity# (from which this book is
taken) was first written in Latin when Barclay was only 27 years old,
and afterwards translated by himself into English.
In the preface to the original edition we find the following remarks:

[quote]
____
"`Perhaps my method of writing may seem not only different, but even contrary,
to that which is commonly used by the men called theologians,
with which I am not concerned;
for I confess myself to be not only no imitator and admirer of the schoolmen,
but an opposer and despiser of those by whose labor I judge
the Christian religion to be so far from being bettered,
that it is rather destroyed.
Nor have I sought to accommodate my work to itching ears,
who desire to comprehend in their head the sublime notions of Truth,
rather than to embrace it in their heart.
For what I have written comes more from my heart than from my head;
from what I have heard with the ears of my soul and seen with my inward eyes,
and my hands have handled of the Word of Life.
What has been inwardly manifested to me of the things of God, that do I declare;
not so much minding the eloquence and excellency of speech,
as desiring to demonstrate the efficacy and operation of Truth.
And if I err sometimes in the former, it is no great matter;
for I act not here the grammarian or the orator, but the Christian;
and therefore in this I have followed the certain rule of the Divine Light,
and of the Holy Scriptures.
Indeed, what I have written is written not to feed the wisdom, knowledge,
and vain pride of this world, but rather to starve and oppose it.`"

"`Unto you these following propositions are offered;
and if they be read and considered in the fear of the Lord, you may perceive that simple,
naked truth which man, by his wisdom, has rendered so obscure and mysterious.
Alas, man has burdened the world with great and voluminous treatises and commentaries,
and rendered truth a hundredfold more dark and intricate than it is in itself.
All of man`'s school learning, which takes up most of a lifetime to learn,
brings not a bit nearer to God,
nor makes any man less wicked or more righteous than he was.
Therefore God has laid aside the wise and the learned and the disputers of this world,
and has chosen a few despicable and unlearned instruments (as he did fishermen of old),
to publish his pure and naked Truth,
and to free it from the mists and fogs wherewith the clergy has clouded it.
And among many others whom God has chosen to make known
these things--seeing I also have received,
in measure, grace to be a dispenser of the same Gospel--it seemed good unto me,
according to my duty, to offer unto you the following propositions.
Though they are short, yet they are weighty,
comprehending much and declaring what the true ground of knowledge is,
even that knowledge which leads to Life Eternal.
To this Life I bear witness,
and leave my testimony to the Light of Christ in all your consciences.
Farewell.`"

[.signed-section-signature]
Robert Barclay

[.signed-section-context-close]
Ury, Scotland, 25th of 9th Month, 1675
____

The following pages contain five of the original
fifteen propositions from Barclay`'s [.book-title]#Apology,#
treating upon the fall, redemption, justification, and perfection of man.
Because the great majority of modern readers find the
original language and style of Barclay unmanageable,
and because many are unfamiliar with the theological debates and
common criticisms against the Quakers at the time of his writing,
I have felt it appropriate to somewhat modernize, edit,
and annotate these five propositions.
I understand and respect the opinion of those
who oppose the editing of early Quaker writings,
saying rightly that these were native English speakers,
and knew well how to speak for themselves.
Even so,
I have found very few today who have been able or willing to wade through
the original publications (a task I nevertheless highly recommend^
footnote:[The unabridged and unedited version of Barclay`'s
[.book-title]#Apology# is available through Quaker Heritage Press.
www.qhpress.org]),
and I doubt very much that ancient Friends would have desired their style or
vocabulary to be a stumbling block in the way of the modern reader.
This version is not for the historian, the purist, or the theologian,
but for the present day seeker of Truth, and I can say, without any misgivings,
that my only aim in re-publishing Barclay is the
glory of Truth and the good of immortal souls.

[.signed-section-signature]
Jason Henderson

[.signed-section-context-close]
February 2017
