== Chapter IThe Condition of Man in the Fall

We come now to examine the state and condition of man
as he stands in the fall--what his capacity and power is,
and how far he is able, of himself, to advance in relation to the things of God.
Truly, a thorough understanding of this subject is of great use and service,
because from the ignorance and altercations that have surrounded it,
there have arisen great and dangerous errors, both on the one hand and the other.
Some have exalted the light of nature, or the faculties of the natural man,
as being capable (by man's own will, light,
and power) to follow what is good and make real progress towards heaven.
Others, however, have run to the other extreme,
not only confessing (rightly) that men are incapable of themselves to do good,
and prone to evil; but also suggesting that infants still in their mother's womb,
before committing any actual transgression,
are contaminated with a true guilt whereby they deserve eternal death.
Indeed,
many have not been afraid to affirm that poor infants are
eternally damned and must forever endure the torments of hell.
But the God of Truth, having now again revealed His Truth by His own Spirit,
has taught us to avoid both of these extremes.

In this chapter, I therefore propose to show,
first--the condition of man in the fall,
and how far incapable he is in meddling with the things of God;
and second--that God does not impute evil to man until he actually joins with it.

=== The Nature and Extent of Man's Fall

As to the first,
it is not my desire to dive into the various notions and conjectures which
many have asserted concerning the condition of Adam before the fall.
All agree in this: that by transgression he came to a very great loss,
not only in the things which related to the outward man,
but in regard to that true fellowship and communion he had enjoyed with God.
This loss was signified unto him in the command,
"`For in the day that you eat of it you shall surely die.`"^
footnote:[Genesis 2:17]
This death could not have been an outward death, or the dissolution of the outward man,
for Adam's body did not die till many hundreds of years after.
So the death spoken of must necessarily relate to the
immediate loss of spiritual life and communion with God.

The consequence of this fall is also expressed in these words:
"`So He drove out the man; and He placed cherubim at the east of the Garden of Eden,
and a flaming sword which turned every way, to guard the way to the tree of life.`"^
footnote:[Genesis 3:24]
Now whatever literal or outward signification this might have had,
we may also safely ascribe to this paradise a spiritual meaning,
and rightly understand it as that spiritual communion and
fellowship which the saints obtain with God by Jesus Christ.
Only to Christ do these cherubim give way,
and to as many as enter by the One who calls Himself the Door.
So then, though we do not ascribe any part of Adam's guilt to men,
until they make it theirs by similar acts of disobedience;
yet we cannot believe that the descendants of Adam have any good thing in their nature,
as belonging to it;
for he from whom they derive their nature had
nothing good in himself to pass along to them.

If then we may affirm that Adam did not retain in his
nature (as belonging to it) any will or light capable of
giving him knowledge or experience in spiritual things,
then neither can his posterity.
So then, whatsoever real good^
footnote:[Editor's Note: Not things judged to be good by the fallen, dark,
and selfish perspective of the creature, but that which is truly good,
as coming from the Source of goodness Himself, and aiming towards His eternal purpose.]
any man does, proceeds not from his nature as a man, or as a son of Adam,
but from the Seed of God in him,
from a new visitation of life given to bring him out of this natural condition.
But though this gift or Seed be in man, it is not of him,
and this the Lord plainly declared; for when speaking of fallen man,
He testified "`that every imagination of the thoughts
of his heart was only evil continually.`"^
footnote:[Genesis 6:5]
These words are very clear and comprehensive.
Observe the emphasis of them: First,
He says "`every imagination of the thoughts of his heart;`" so
that this allows no exception in any thoughts of man's heart.
Secondly,
"`is only evil continually;`" it does not say 'partially evil continually,' nor '
entirely evil at some times;' but it is both only evil and continually evil!
This certainly excludes any good as belonging to man's heart naturally:
for that which is only evil, and always evil,
cannot of its own nature produce any good thing.
The Lord expressed the same thing again a little after, saying,
"`The imagination of man's heart is evil from his youth,`" again inferring
how natural and inherent evil is to every son and daughter of Adam.
So then, if man's thoughts are always and only evil, and that from his youth,
it is certain and undeniable that the thoughts of man are
altogether useless and ineffectual to him in the things of God.

Furthermore, this appears clearly from that saying of the prophet Jeremiah,
"`The heart is deceitful above all things, and desperately wicked.`"^
footnote:[Jeremiah 17:9]
For who can seriously imagine that a heart such as this has any power of itself,
or is in any way fit, to lead a man to righteousness,
seeing that its own nature is directly the opposite?
This is as contrary to reason, and is as impossible in nature,
as to suggest that a stone, of its own nature and ability, should fly upwards.

The apostle Paul treats the condition of men in the fall at large,
taking various descriptions from the Old Testament: "`There is none righteous,
no not one.
There is none that understands; there is none that seeks after God.
They have all turned aside, they have together become unprofitable.
There is none that does good, no not one.
Their throat is an open tomb; with their tongues they have practiced deceit;
the poison of asps is under their lips, whose mouths are full of cursing and bitterness.
Their feet are swift to shed blood; destruction and misery are in their ways,
and the way of peace they have not known.
There is no fear of God before their eyes.`"^
footnote:[Romans 3:10-18]
What more could be said?
Paul seems to be particularly careful that no good be ascribed to the natural man,
showing how he is polluted in all his ways, void of righteousness, understanding,
and the knowledge of God, out of the right way, and entirely unprofitable.
And if this be the condition of the natural man as he stands in the fall,
he is most certainly unfit to take one right step toward heaven.

Objection:
If it be suggested that this text of the apostle does
not speak of the condition of all men in general,
but only of some particulars, I answer:

Answer: The text clearly speaks to the contrary in the foregoing verse,
where the apostle applies these things to himself (in
his natural condition) and to all Jews and Gentiles,
saying: "`What then?
Are we better than they?
Not at all.
For we have previously charged both Jews and Gentiles, that they are all under sin,
as it is written:`" and so he goes on, showing that he speaks of mankind in general.

Objection:
If they object that the same apostle says in the foregoing chapter
that the Gentiles "`do by nature the things contained in the Law,`"^
footnote:[Romans 2:14]
and so consequently do by nature that which is good and acceptable in the sight of God,
I answer:

Answer: The word "`nature`" here cannot be understood of man's own nature,
which is corrupt and fallen,
but of that spiritual nature which proceeds from the Seed of God in
man as he receives a visitation of God's love and is quickened by it.
This clearly appears by the following words, where Paul says,
"`These not having the law`" (i.e., the written law) "`are a law unto themselves,
who show the work of the law written in their hearts.`"
Thus whatever good deeds appear are the effect of God's law written in their hearts.
And seeing that Scripture plainly declares the writing of the
law in the heart to be part of the New Covenant dispensation,
this can be no consequence or part of man's fallen nature.

Moreover,
if the "`nature`" here mentioned could be understood of man's own nature,
then the apostle would unavoidably contradict himself,
since he elsewhere positively declares,
that "`the natural man does not receive the things of the Spirit of God,
for they are foolishness to him; nor can he know them.`"^
footnote:[1 Corinthians 2:14]
Now I hope all will confess that the Law of God is among the things of God,
especially as it is written in the heart.
And the apostle, in the 7th chapter of the same epistle, says that "`the Law is holy,
just, and good;`" and that "`the Law is spiritual, but I am carnal.`"
Now in what respect is he carnal, except as he stands unregenerate in the fall?
We see then that the apostle makes a clear
distinction between the Law which is spiritual,
and the nature of man which is carnal and sinful.
Thus, even as Christ says that "`grapes cannot be expected from thorns,
nor figs from thistles,`" so neither can the law (which is spiritual, holy,
and just) be fulfilled by a nature that is corrupt, fallen, and unregenerate.

From all of this we conclude (and with good reason),
that the "`nature`" here spoken of (Rom. 2:14) by which some
Gentiles are said to have done things contained in the Law,
is not the common and fallen nature of man,
but the spiritual nature that arises from the righteous and
spiritual law written on the heart by the finger of God.

=== Guilt Imputed to Transgressors

I come now to discuss the other part, namely,
that this evil and corrupt seed is not imputed
to infants until they actually join with it.
For as Paul relates in Ephesians 2, they "`are by nature children of wrath,
who walk according to the prince of the power of the air,
the spirit that now works in the children of disobedience.`"
Here the apostle gives their evil walking as the reason of their being children of wrath.
And this is in keeping to the whole strain of the Gospel,
where no man is ever threatened or judged for the iniquity he has not actually committed.
But in the case of those who continue in iniquity,
and so do approve the sins of their fathers,
God will visit the iniquity of the fathers upon the children.

But alas, as has been stated,
many among Protestants and Catholics are not ashamed to declare openly that infants,
even in their mother's wombs,
are contaminated with true guilt whereby they deserve eternal death.
Now, is it not strange that men should entertain an opinion so absurd in itself,
and so cruel and contrary to both God's mercy and justice,
and concerning which the Scripture is altogether silent?
Is it not manifest that man has invented this opinion out of self-love,
and from that bitter root from which all errors do spring?
For most Protestants who hold this opinion think that they and their
children rest securely in the absolute decree of God's election;
and since they deem themselves incapable of missing salvation,
they have no great difficulty in assigning all others, both old and young, to hell.
For seeing that self-love (which is always apt to believe whatever it
desires) fills them with a hope that their part is secure,
they are not too concerned how this may leave their neighbors,
which happen to be the far greater part of mankind.

The Catholics, on the other hand,
use this opinion as an artful means to increase esteem for their church,
and reverence for its sacraments,
seeing they pretend that Adam's guilt is only
washed away by their form of infant baptism.
These, perhaps, appear a little more merciful,
in that they do not send unbaptized children to hell,
but rather to limbo--concerning which concept the Scriptures are also entirely silent.

Such ideas are not only absent from Scripture,
but contrary to the express tenor of it.
The apostle plainly says, "`Where there is no law there is no transgression,`"^
footnote:[Romans 4:15]
and again, "`But sin is not imputed, where there is no law.`"^
footnote:[Romans 5:13]
Now clearly to infants there can be no law,
seeing they are utterly incapable of receiving and comprehending it.
The law cannot reach to any but those who have, in some measure, less or more,
the exercise of their understanding.
But those who are under a physical impossibility of either hearing, knowing,
or understanding any law--where the impossibility is
not brought upon them by any act of their own,
but is according to the very order of nature appointed by God--to such there is no law.

Furthermore, what can be more certain than the word of God to Ezekiel,
"`The soul that sins, it shall die.
The son shall not bear the guilt of the father,
nor the father bear the guilt of the son`"^
footnote:[Ezekiel 18:20]
The prophet here first shows the true cause of man's eternal death,
which is his own sinning.
Then, as if he purposed expressly to shut out such an opinion, he assures us,
"`The son shall not bear the iniquity of the father, etc.`"
From which I thus argue: If the son does not bear the guilt of his father,
or of his immediate parents, far less shall he bear the guilt of Adam.

Having thus far shown how absurd this opinion is,
I shall briefly examine the reasons that some contend for it.

Objection: First, they insist that Adam was the head of a corporate race,
and therefore all men sinned in him, as being still in his loins.
And for this they allege Romans 5:12, where the apostle says, "`Therefore,
just as through one man sin entered the world, and death through sin,
and thus death spread to all men, because all sinned.`"

Answer: To this I answer: That Adam is the head of a corporate race is not denied by us,
nor that through him there is a seed of sin propagated to all men,
which in its own nature is sinful, and inclines men to iniquity.
Nevertheless, it does not follow from this that infants,
who do not willingly join with this seed, are accounted guilty.
And as for these words of Paul in his letter to the Romans,
the reason for the guilt is there plainly stated, "`because all sinned.`"
But that infants cannot be counted among these guilty
ones is plainly shown in the following verse:
"`But sin is not imputed where there is no law.`"

Objection: Their second objection is from Ps. 51:5, "`Behold,
I was brought forth in iniquity, and in sin my mother conceived me.`"
Hence, they say, it appears that infants are guilty even from their conception.

Answer: How they infer this conclusion, for my part, I do not see.
The iniquity and sin here appear to be far more
ascribable to the parents than to the child.
David says, "`In sin my mother conceived me;`" he does not say,
"`My mother conceived me a sinner.`"
But even if the sin here mentioned should be ascribed to the child,
we confess freely that a seed or nature of sin is transmitted to all men from Adam,
in which seed all are given occasion to sin,
and this is the origin of all evil actions and thoughts in men's hearts.
But, again,
we insist (according to plain Scripture) that this evil is imputed or credited to none,
until by actually sinning, they willingly join with it.

Objection: Thirdly, they object,
that "`the wages of sin is death;`" and seeing
that children are subject to diseases and death,
they must therefore be guilty of sin.

Answer:
We confess that death and disease are a consequence of the fall and of Adam's sin;
but that this necessarily infers a guilt in all that experience them, we deny.
For though the whole outward creation suffered a decay by Adam's fall,
according to which it is said in Job that "`the
heavens are not clean in the sight of God;`"^
footnote:[Job 15:15]
yet it does not follow that the herbs, the earth, and the trees are thereby sinners.

Objection: Lastly, some are so foolish as to object that,
if Adam's sin is not imputed to those who actually have not sinned,
then it would follow that all infants are saved.

Answer: We are willing that this conclusion be the consequence of our doctrine,
rather than accept the unavoidable consequence of theirs, namely,
that countless infants eternally perish, not for any sin of their own,
but only for Adam's iniquity.
Here we are willing to let the controversy stop,
commending all to the illuminated understanding of the Christian reader.

