== Chapter II. A Universal Offer of Redemption

Having considered man`'s fallen, lost, corrupt, and degenerate state,
we must now inquire how, and by what means,
he may come to be freed from this miserable and depraved condition.

=== Absolute Reprobation--A Doctrine of Devils

We must begin by striking at the doctrine of __absolute
predestination and reprobation__,
whereby many are not afraid to assert that God, by an eternal and immutable decree,
has predestinated to eternal damnation the far greater part of mankind,
without any regard to their disobedience or sin,
but only for the demonstration of the glory of His justice.
These miserable souls, they say, are appointed to walk in their own wicked ways,
to the end that God`'s justice may at last lay hold upon them.
Not only has He withheld the preaching of the Gospel and the
knowledge of Christ from many parts of the world,
but even in those places where the gospel is preached,
and salvation by Christ is offered, He justly condemns for disobedience great multitudes,
from whom He has withheld the grace by which they could have been saved.
This, it is said, is because He has, by a secret will unknown to all men,
foreordained and decreed (without any respect to
disobedience or sin) that many shall not obey,
and that the offer of the Gospel shall never prove effectual for their salvation,
but only serve to occasion their greater condemnation.

Now, with respect to this horrible and blasphemous doctrine,
our view is the same with many others, who have both wisely and learnedly,
according to Scripture, reason, and antiquity, refuted it.
And seeing that so much has already been written
against this doctrine that very little can be added,
I shall be brief in this respect.
However, because it stands in opposition to my way, I cannot let it altogether pass.

First, we may safely call this doctrine a novelty,
seeing that for the first four hundred years after Christ there is no mention made of it.
For as it is contrary to the Scripture`'s testimony, and to the tenor of the Gospel,
so all the ancient writers, teachers,
and doctors of the church pass it over with profound silence.
The first foundations of it were laid in the later writings of Augustine, who,
in his warring against Pelagius,
let fall some expressions which some have unhappily picked up,
to the establishing of this error.
Afterwards this doctrine was promoted by Dominicus, a friar, and the monks of his order;
and at last unhappily taken up by John Calvin (otherwise a man
in some respects to be commended),
to the great staining of his reputation, and the defamation of Protestant Christianity.
And though it was confirmed by the decrees of the Synod of Dort,
it has since lost ground,
and is being discredited by most men of learning and piety in all Protestant churches.
However, we do not quarrel with it because of the silence of the ancients,
the scarcity of its asserters, or the learnedness of its opposers,
but because we believe it to have no real foundation in
the writings or sayings of Christ and the apostles,
and find it highly injurious to God himself, to Jesus Christ our Mediator and Redeemer,
and to the power, virtue, nobility, and excellency of His blessed Gospel,
and lastly to all mankind.

First, it is highly injurious to God, because it makes Him the author of sin,
which of all things is most contrary to His nature.
I confess the asserters of this principle deny this consequence;
but their denial is pure illusion,
seeing that it so naturally follows from their doctrine.
For if God has decreed that certain reprobated people shall perish,
without any respect to their evil deeds, but only of His own pleasure;
and if He has also decreed this long before they had a being,
or any capacity to do good or evil, so that they must walk in their wicked ways,
by which they are led to condemnation; who then, I ask,
is the first author and cause of this but God, who so willed and decreed it?
This is the most natural, and indeed the only consequence that can exist.
And although many of the preachers of this doctrine have sought out various, strange,
strained, and intricate distinctions to defend their opinion,
and to avoid this horrid consequence,
yet some of the most eminent of them have been so plain in the matter,
that they have put it beyond all doubt.
I shall instance a few among many of these:

[quote]
____
The following are John Calvin`'s expressions: "`By the ordination and will of God,
Adam fell.
God would have man to fall.`"^
footnote:[Calvin in cap. 3. Gen.]
"`Man is blinded by the will and commandment of God.`"^
footnote:[Id. 1 Inst. c. 18. s. 1.]
"`We refer the cause of our hardening to God.`"^
footnote:[Id. lib. de praed.]
"`The highest or remote cause of hardening is the will of God.`"^
footnote:[Idem, lib. de provid.]
"`It follows that the hidden counsel of God is the cause of hardening.`"^
footnote:[Id. 3 Inst., cap. 23. s. 1.]
____

[quote]
____
Theodor Beza writes: "`God has predestined not only unto damnation,
but also unto the causes of it, whomsoever He saw fit.`"^
footnote:[Beza, lib. de praed.]
"`The decree of God cannot be excluded from the causes of corruption.`"^
footnote:[Id. de praed. ad art. 1.]
____

[quote]
____
"`It is certain,`" says Jerome Zanchi,
"`that God is the first cause of hard-heartedness.`"^
footnote:[Zanchi, de excaecat. q. 5.]
"`Reprobates are held so fast under God`'s almighty
decree that they cannot help but sin and perish.`"^
footnote:[Idem, lib. 5 de nat. Dei cap. 2. de praed.]
____

[quote]
____
"`It is the opinion,`" says David Pareus, "`of our doctors,
that God did inevitably decree the temptation and fall of man.
The creature sins indeed necessarily, by the most just judgment of God.
Our men do most rightly affirm that the fall of man was necessary and inevitable,
because of God`'s decree.`"^
footnote:[Pareus, lib. 3. de amiss. gratiae. c. 2. ibid., c. 1.]
____

[quote]
____
"`God,`" says Ulrich Zwingli, "`moves the robber to kill.
He kills, God forcing him thereunto.
But you will say, he is forced to sin; I confess truly that he is forced.`"^
footnote:[Zwingli, lib. de Prov. 100:5.]
____

[quote]
____
"`Reprobate persons,`" says Piscator, "`are absolutely ordained to this twofold end,
to undergo everlasting punishment, and necessarily to sin; and therefore to sin,
that they may be justly punished.`"^
footnote:[Resp. ad Vorst. part 1, p. 120.]
____

Such sayings do plainly and evidently make God the author of sin.
Some have sought to evade this necessary consequence
with the assertion that men sin __willingly__;
but this does not help them at all, since man`'s willingness and propensity to evil is,
according to their own judgment,
necessarily imposed upon him by the will and decree of God.
This shift is just as if I should take a child who is incapable of resisting me,
and throw it down from a great precipice.
The weight of the child`'s body indeed makes it go readily down,
and the violence of the fall does immediately kill it.
Now then, I ask you,
though the child goes down willingly because of the weight of its body,
and not by any immediate stroke of my hand (who am perhaps at a great distance away
when he is killed)--am I or the child the proper cause of its death?
Therefore, let any man of reason judge,
if the above citations not only make God the immediate author of sin,
but also more unjust than the most unjust of men.

Secondly,
this doctrine is injurious to God because it makes Him delight in the death of sinners,
yes, and to desire many to die in their sins, contrary to many scriptures, such as:
"`'`As I live,`' says the Lord God, '`I have no pleasure in the death of the wicked,
but that the wicked turn from his way and live.
Turn, turn from your evil ways!
For why should you die, O house of Israel?`'`"^
footnote:[Ezekiel 33:11]
And, "`For this is good and acceptable in the sight of God our Savior,
who desires all men to be saved and to come to the knowledge of the truth.`"^
footnote:[1 Timothy 2:4]
And, "`The Lord is not slack concerning His promise, as some count slackness,
but is long-suffering toward us,
not willing that any should perish but that all should come to repentance.`"^
footnote:[2 Peter 3:9]
But if God has created men that He might show forth His justice and power in them,
as these men affirm,
and for the effecting of this He has not only withheld from them the means of doing good,
but also predestined the evil that they might fall into it--
certainly He must necessarily delight in their death,
and will them to die, seeing He does nothing against His own will.

Thirdly, it is highly injurious to Christ our mediator,
and to the efficacy and excellency of His Gospel;
for it renders His mediation ineffectual--as if He had not by
His sufferings thoroughly broken down the middle wall,
nor yet removed the wrath of God,
nor purchased the love of God towards all mankind--if it was indeed foreordained
that His death would be of no service to the far greater part of mankind.

Fourthly, it makes the preaching of the Gospel a mere mockery and illusion,
if indeed many of those to whom it is preached are, by an irrevocable decree,
excluded from benefitting by it.
It makes the preaching of faith and repentance wholly useless,
along with all of the Gospel promises and warnings.
For, to what purpose are these,
if all is dependent upon a former decree by which a chosen man cannot fail
to be saved at the appointed time (though it be at the last hour of his life)
and a reprobate man cannot fail to be damned,
though he seek and wait upon the Lord with diligence?

Fifthly, it is injurious to the coming of Christ and His propitiatory sacrifice,
which the Scripture affirms to have been the fruit of God`'s love to the world,
and transacted for the sins and salvation of all men.
For, if the coming of Christ was foreordained to save very few,
and also served to harden and augment the condemnation of the
far greater number of men who do not believe in it (they not
being able to believe in it by foreordination),
then the cross rather serves as a testimony of God`'s wrath to the world,
and as an act of indignation towards the majority of mankind.

Sixthly, this doctrine is highly injurious to mankind,
for it renders them in a far worse condition than the devils in hell.
For devils once stood in their proper domain, and had the capacity so to remain;
these then suffer for their own rebellion and guilt.
But, according to this doctrine,
many millions of men are forever tormented for Adam`'s sin, of which they know nothing,
and for which they bear no responsibility.
Indeed, this renders them worse than the beasts of the field,
of whom their master requires no more than they are able to perform.
And when a beast is killed, death to them is the end of their sorrow;
but those chosen for damnation are forever tormented
for not doing that which they were never able to do.
Yes, this puts man into a far worse condition than Pharaoh put the Israelites;
for though he withheld straw from them,
yet by much labor and pain there was a possibility of obtaining it.
But this doctrine makes God withhold all means of salvation,
so that man can by no means attain it!

=== Christ`'s Death For All Men

Having thus briefly removed this false doctrine which stood in my way,
I come to the matter of our proposition, which is, "`That God, out of His infinite love,
who delights not in the death of a sinner but that all should live and be saved,
has sent His only begotten Son into the world,
that whosoever believes in Him might be saved.`"
The truth of this statement, being almost entirely in the express words of Scripture,
will not require much proving.
And because our assertion here is in common with
many others who have both earnestly and soundly,
according to the Scripture, pleaded for God`'s offer of universal redemption,^
footnote:[Editor`'s Note:
There have been many misunderstandings and false conclusions derived from
the Quakers use of the term "`universal`" in reference to redemption.
This word was used by Friends to establish an intentional contrast with the
prevalent idea that God offers the saving knowledge of Christ to only a small,
predestined few.
The Quakers rejected the idea of individual predestination and a "`limited
atonement,`" insisting that Christ died for all men,
and that an offer of redemption extends towards all the sons of Adam.
It is this gracious, inward invitation that is universal.
When received, followed, and obeyed,
the light of Christ becomes the life and salvation of the soul.
When rejected, the same light becomes man`'s eternal condemnation.
See John 3:19-21. Early Quakers were not at all proponents of universalism,
or universal reconciliation.]
I shall be brief until I come to those assertions which
are more singularly and peculiarly ours.

This truth of Christ`'s dying for all men is of itself
so evident from the Scripture testimony that there is scarce
found any other article of the Christian faith so frequently,
so plainly, and so positively asserted.
It is that which makes the preaching of Christ to be truly termed the Gospel,
or an announcement of glad tidings to all.
Thus the angel declared the birth and coming of Christ to the shepherds, saying,
"`Behold, I bring you good tidings of great joy, which shall be __to all people__;`"^
footnote:[Luke 2:10]
notice he says not to a few people.
Now if this coming of Christ had not brought a possibility of salvation to all,
this announcement should rather have been accounted bad
tidings of great sorrow to most people;
nor would the angel have had reason to sing,
"`Peace on earth and good will towards men`"^
footnote:[Luke 2:14]
if the greatest part of mankind had been necessarily
shut out from receiving any benefit by it.
And why would Christ have sent out His disciples
to "`preach the Gospel to every creature?`"^
footnote:[Mark 16:15]
Indeed, He commanded them to preach repentance, remission of sin,
and salvation to every son and daughter of mankind,
warning every man and exhorting every man, as Paul did in Col. 1:28.

Now, how could these ministers of Christ have preached the Gospel to every man,
"`in much assurance,`"^
footnote:[1 Thessalonians 1:5]
if salvation by that Gospel was not possible to all?
What if some had asked them, "`Has Christ died for me?`"
To this, those who deny the universal death of Christ can answer nothing,
and only run in a circle.
But "`the feet of those that bring the glad tidings of
the Gospel of peace`" are said to be "`beautiful,`"^
footnote:[Isaiah 52:7, Romans 10:15]
for they preach a common salvation, repentance unto all,
the offering of a door of mercy and hope to all through
Jesus Christ "`who gave himself a ransom for all.`"^
footnote:[1 Timothy 2:6]
Yes, the Gospel invites all;
and certainly Christ did not intend to deceive and delude the
greater part of mankind when He invited and cried out,
saying,
"`Come unto Me all you that labor and are heavy laden and I will give you rest.`"^
footnote:[Matthew 11:28]
If all then ought to seek after Him, and to look for salvation by Him,
He must necessarily have made salvation possible to all.
Certainly it would be mere mockery to bid men seek what is impossible to obtain.
And those who deny that by the death of Christ salvation is made possible to all men,
do most blasphemously make God mock the world;
for they admit that God has given His servants a
commission to preach the Gospel of salvation unto all,
and yet they maintain He has previously decreed it impossible for most to receive it.

But seeing that Christ, after He arose and perfected the work of our redemption,
gave a commission to preach repentance, remission of sins, and salvation to all,
it is manifest that He indeed died for all.
For He that has commissioned His servants thus to preach is a God of Truth,
and not a mocker of poor mankind,
nor does He require of any man that which is simply impossible for him to do.

Moreover, if we regard the testimony of the Scripture in this matter,
there is not one scripture that I know of that
plainly affirms Christ did not die for all,
though there are many that positively and expressly assert He did, such as:
"`Therefore I exhort first of all that supplications, prayers, intercessions,
and giving of thanks be made for all men... For this is
good and acceptable in the sight of God our Savior,
who desires all men to be saved and to come to the knowledge
of the truth... who gave Himself a ransom for all,
to be testified in due time.`"^
footnote:[1 Timothy 2:1,3-4, 6]
Nothing could more plainly confirm what we have asserted;
for first the apostle here recommends them to "`pray for all men,`" and then,
as though seeking to prevent any objections as to the will of God in this regard,
tells them that "`it is good and acceptable in the sight of God,
who desires all men to be saved.`"
He then manifests the reason for His willingness that all men should be saved,
in these words: "`Who gave himself a ransom for all.`"
It is as if he said, '`Since Christ died for all,
and since He gave himself a ransom for all, He therefore desires all men to be saved.`'
And Christ Himself shows God`'s love to the world in these words,
"`God so loved the world that He gave His only begotten Son,
that whosoever believes in Him should not perish but have everlasting life.`"^
footnote:[John 3:16]
This word "`whosoever`" is an indefinite term, from which no man is excluded.

The same is very positively affirmed in these words, "`But we see Jesus,
who was made a little lower than the angels,
for the suffering of death crowned with glory and honor that He, by the grace of God,
should taste death for every man.`"^
footnote:[Hebrews 2:9]
Clearly,
if He "`tasted death for every man`" then there
is no man for whom He did not taste death,
nor is there any who may not become a sharer in the benefit of it;
for He came not "`to condemn the world but that the world might be saved through Him.`"^
footnote:[John 3:17]
"`He came not to judge the world but to save the world.`"^
footnote:[John 12:47]
But according to the doctrine of our adversaries, He came not with the intention to save,
but rather to judge and condemn the greater part of the world,
contrary to His own express testimony.

And as the apostle Paul (in the words above cited) does
positively assert that God desires the salvation of all,
so the apostle Peter asserts the same thing negatively--
that God "`is not willing that any should perish.`"
He writes, "`The Lord is not slack concerning His promise, as some count slackness,
but is long-suffering toward us,
not willing that any should perish but that all should come to repentance.`"^
footnote:[2 Peter 3:9]
This corresponds with the words of Ezekiel: "`'`As I live,`' says the Lord God,
'`I have no pleasure in the death of the wicked,
but that the wicked turn from his way and live.`'`"^
footnote:[Ezekiel 33:11]
Therefore, if it is safe to place our trust in God,
we cannot believe He intends to deceive us by
all of these clear expressions from His servants.
And if His manifest will for our salvation has not taken effect,
the blame must be on our part, as shall afterwards be shown.

Besides these things,
how should we understand the multitudes of earnest invitations, serious accusations,
and regretful lamentations that fill the pages of holy Scripture?
Such as, "`Why should you die, O house of Israel!`"^
footnote:[Ezekiel 18:31,33:11]
"`Why will you not come unto Me, that you might have life?`"^
footnote:[John 5:40]
"`I have waited to be gracious unto you;`"^
footnote:[Isaiah 30:18]
"`I have sought to gather you;`"^
footnote:[Matthew 23:37]
"`I have knocked at the door of your hearts;`"^
footnote:[Revelation 3:20]
"`Is not your destruction of yourselves?`"^
footnote:[Jeremiah 2:17, etc.]
"`I have called all the day long.`"^
footnote:[Isaiah 65:2]
If those who are so invited by the Lord are really under no capacity of being saved,
then we must suppose God to be like the author of a romance or comedy,
who amuses Himself by raising the affections and passions of men,
sometimes leading them into hope and sometimes into despair,
while all along having predetermined what the conclusion will be.

Moreover, this doctrine is abundantly confirmed by the words of the apostle John:
"`And if anyone sins, we have an Advocate with the Father, Jesus Christ the righteous.
And He Himself is the propitiation for our sins,
and not for ours only but also for the whole world.`"^
footnote:[1 John 2:1-2]
The way by which our adversaries seek to avoid this
plain testimony is most foolish and ridiculous:
suggesting that the "`world`" here refers only to the world __of believers__.
To support this, they have nothing but their own assertion; for let them show me,
if they can,
in all the Scripture where "`the whole world`" is taken to mean believers only.
I can show them where it many times means the contrary.^
footnote:[Barclay`'s Note: Such as, "`The world knows Me not.`"
"`The world receives Me not.`"
"`I am not of this world.`"
Besides all these scriptures: Ps. 17:14; Isa. 13:11; Matt. 18:7;
John 7:7-8:26, 12:19, 14:17, 15:18-19, 17:14, and 18:20; 1 Cor. 1:2,21:12, and 6:2;
Gal. 6:14; James 1:27; 2 Pet. 2:20; 1 John 2:15-3:1, and 4:4-5,
and many more.]

Furthermore, the apostle, in this very place,
makes a distinction between the world and the saints,
saying "`And not for ours only but for the sins of the whole world.`"
What does the apostle mean by "`ours`" here?
Is he not plainly speaking of the sins of believers?
And is not "`the whole world`" necessarily then
a reference to those outside of the church,
for whom Christ also died, and to whom the gospel invitation is extended?
But we need no better interpreter for the apostle than himself,
for he uses the very same expression in the fifth chapter of the same epistle, saying,
"`We know that we are of God, and the whole world lies in wickedness.`"^
footnote:[1 John 5:19]
Seeing then that the apostle John tells us plainly that Christ not only died
for the saints and members of the church of God to whom he wrote,
but also for the whole world, let us then hold it for a certain and undoubted truth,
despite the squabbles of those who oppose.

The same might also be proved from many more Scripture testimonies,
if it were needful.
And indeed, all the Fathers of the church (so-called), for the first four centuries,
preached this doctrine.
These boldly held forth the Gospel of Christ and the efficacy of His death,
inviting and entreating the heathen to come and be partakers of the benefits of it.
They did not tell them that God had predestinated any of them to damnation,
or had made salvation impossible to them by withholding
the power and grace necessary to believe;
but rather declared that a door had been opened for all
mankind to come and be saved through Jesus Christ.

Seeing then that this doctrine of the universality of Christ`'s death is so
certain and agreeable to the Scripture`'s testimony and to Christian antiquity,
it may be wondered how so many (some of whom have been esteemed not only learned,
but also pious) have been capable of falling into so gross and strange an error?
There are indeed a few difficult texts which the
unrenewed mind may easily twist and misconstrue,
but the principle cause arises from a general misunderstanding of the way or method
by which the virtue and efficacy of Christ`'s death is offered to all men.
Here men have stumbled, and resorted to various theological inventions.
Not understanding this way, some have departed from clear Scripture testimony,
and (as we have seen) limited Christ`'s atonement to a predestined few.
Others have erred in the other direction,
affirming that those who have never heard the outward
proclamation of Christ are not obliged to believe in Him,
or that all are saved regardless of faith in, and obedience to the gospel.
