== Chapter III. The Seed, Light, and Grace of God.

Even as the darkness of the great apostasy did
not come upon the Christian world all at once,
but rather by several degrees, one thing making way for another,
until that thick and gross veil came to be overspread (with which the
nations were so blindly covered from the seventh and eighth,
until the sixteenth century);
and even as the darkness of night does not come upon the outward creation all at once,
but by degrees, according as the sun declines in the horizon;
so neither did the full and clear light and knowledge of the glorious
dispensation of the Gospel of Christ reappear in the world all at once.
Indeed,
the work of the first witnesses in the reformation was more to
testify against and uncover the abuses of the apostasy,
than to establish the Truth in purity.
He that comes to build a new city,
must first remove the old rubbish before he can see to lay a new foundation;
and he that comes to a house that is greatly polluted and full of dirt,
will first sweep away and remove the filth before
setting up his own good and new furniture.
The light at dawn is sufficient to dispel the darkness,
and to make us see the things that are most conspicuous;
but a clear discovering and discerning of things,
so as to make certain and perfect observations,
is reserved for the arising of the sun and its shining in full brightness.

Now, from certain experience we can boldly affirm,
that many an unhappy and hurtful mistake among the Protestants has
arisen from a failure to wait for the further rising of this sun;
and thus they have built with and among much old Catholic
rubbish before the foundation was thoroughly purged.
But now, in this our age,
the Lord God has seen fit to communicate and make known again a more full, evident,
and perfect knowledge of His everlasting Truth and evangelical
dispensation (notwithstanding various testimonies to it have
been borne by noted persons in several ages,
as shall hereafter be seen.) And in order to magnify the glory of His grace,
and preclude all cause for boasting,
He has raised up a few despicable and uneducated men, for the most part tradesmen,
to be the messengers of it.
By this Gospel, all the above-mentioned scruples, doubts, hesitations,
and objections are easily and evidently answered,
and the justice as well as mercy of God, according to their divine and heavenly harmony,
are exhibited, established, and confirmed.
It is according to this certain Light and Gospel,
as the knowledge thereof has been manifested to
us by the revelation of Jesus Christ in us,
fortified by our own sensible experience,
and sealed by the testimony of the Spirit in our hearts, that we can confidently affirm,
and clearly declare, according to the testimony of the holy Scriptures,
the following points:

[.numbered]
I+++.+++ That God, who out of His infinite love sent His Son, the Lord Jesus Christ,
into the world to taste death for every man,
has given to every man--whether Jew or Gentile, Turk or Scythian, Indian or Barbarian,
of whatsoever nation, country, or place--a certain day or time of visitation,
during which it is possible for them to be saved,
and to partake of the fruit of Christ`'s death.

[.numbered]
II+++.+++ That for this end God has communicated and given
unto every man a measure of the Light of His own Son,
a measure of grace, or a measure of the Spirit,
which the Scripture expresses by several names:
as sometimes "`the seed of the kingdom;`"^
footnote:[Matthew 13:18-19]
the "`Light that makes all things manifest;`"^
footnote:[Ephesians 5:13]
the "`Word of God;`"^
footnote:[Romans 10:17]
or "`manifestation of the Spirit given to profit withal;`"^
footnote:[1 Corinthians 12:7]
"`a talent, or mina`"^
footnote:[Matthew 25:15, Luke 19:11]
"`a little leaven;`"^
footnote:[Matthew 13:33]
"`the Gospel preached in every creature.`"^
footnote:[Colossians 1:23, Literal Translation "`εν παση τη  κτισει`"]

[.numbered]
III+++.+++ That God, in and by this Light and Seed, invites, calls, exhorts,
and strives with every man in order to save him.
As this is received, and not resisted,
it is able to work the salvation of all--even those who are
ignorant of the historical death and sufferings of Christ,
and of Adam`'s fall--by bringing them to a sense of their own misery,
to be sharers in the sufferings of Christ inwardly,
and by making them partakers of His Resurrection, in becoming holy, pure, and righteous,
and recovered out of their sins.
By this same Light and Seed,
salvation is worked in those who do have the outward and historical knowledge of Christ,
opening their understanding rightly to use and
apply the things described in the Scriptures,
and to receive the saving benefit of them.
Nevertheless, this gift of grace may be resisted and rejected in both,
in which then God is said to be resisted^
footnote:[See Acts 7:51; Hebrews 2:3; Galatians 2:21, etc.]
and pressed down,^
footnote:[See Amos 2:13]
and Christ to be again crucified, and put to open shame in and among men;^
footnote:[Hebrews 6:6]
and to those who thus resist and refuse Him, He becomes their condemnation.^
footnote:[John 3:19]

Now then, according to this doctrine: __First__:
The mercy of God is excellently exhibited,
in that none are necessarily shut out from salvation; and His justice is demonstrated,
in that He condemns none but those to whom He truly made an offer of salvation,
having affording them the means sufficient for it.

__Secondly__: This doctrine, if well considered,
will be found to be the foundation of true Christianity, salvation, and real assurance.

__Thirdly__:
It agrees and fits with the whole tenor of the Gospel promises and threats,
and with the nature of the ministry of Christ, according to which, the Gospel, salvation,
repentance are commanded to be preached to every creature, without respect of nations,
kindred, families, or tongues.

__Fourthly__: It magnifies and commends the merits and death of Christ,
in that it not only accounts them sufficient to save all,
but declares them to be brought so near to all men as to
thereby put them into the real capacity of salvation.

__Fifthly__: It exalts the grace of God above all,
as the source of all that is truly good--from the least and smallest motions of good,
to the whole conversion and salvation of the soul.

__Sixthly__: It contradicts, overturns, and disables,
the false doctrine of those who exalt the light of man`'s nature,
and the strength of man`'s will,
in that it wholly excludes the natural man from
having any place or portion in his own salvation,
by any acting, moving, or working of his own, until he be first quickened, raised up,
and moved by God`'s Spirit.

__Seventhly__:
Even as it makes the whole of man`'s salvation solely and completely to depend upon God,
so it also makes man`'s condemnation wholly and in every respect to be of himself.
For the man who refuses and resists the gift of
God that wrestles and strives with his heart,
is forced at length to acknowledge the just judgment of
God in afterwards rejecting and forsaking him.

__Eighthly__: It takes away all ground of despair,
and gives every man a ground of hope and a certain assurance that they can be saved.
However, it feeds nobody in a false security,
for none are certain how soon their day may expire.
It is therefore a constant incitement and provocation,
and a lively encouragement to every man, to forsake evil and turn to that which is good.

__Ninthly__: It wonderfully commends the Christian religion among unbelievers,
manifesting its truth to all,
in that this doctrine is confirmed and established by the experience of all men.
For there was never yet a man found in any place of the earth,
however barbarous and wild, who has not acknowledged that at some time or other,
less or more,
he has found something in his heart reproving him for some evil things that he has done.
This inward witness is the same in all--both
threatening a certain horror as man continues in evil,
and also promising and communicating a certain peace and
sweetness as grace is given way to and not resisted.

__Tenthly__: It wonderfully shows the excellent wisdom of God,
by which He has made the means of salvation so universal and comprehensive.
He is therefore not bound to make use of outward miracles, the ministry of angels,
or other unusual means, seeing that, according to this most true doctrine,
the Gospel reaches all, of whatsoever condition, age, or nation.

__Eleventhly__: It is really and effectively (though perhaps not in so many words,
yet by deeds) established and confirmed by all the preachers
and promoters of Christianity in all the world.
For although in their judgment they may oppose this doctrine,
they nevertheless preach to every individual that they may be saved,
entreating and desiring them to believe in Christ, who has died for them,
telling them Jesus Christ calls and wills them to believe and be saved,
and that if they refuse, they shall therefore be condemned,
and that their condemnation is of themselves.
Indeed, such is the evidence and virtue of Truth, that it constrains its adversaries,
even against their wills, to plead for it.

=== Further Considerations upon the Above Propositions

[.numbered]
I+++.+++ First, by this day and time of visitation which, we say, God gives unto all,
during which they may be saved,
we do not mean the whole course of every man`'s life--though to
some it may be extended even to the very hour of death,
as we see in the example of the thief converted upon the cross.
Rather,
we understand this time of visitation as a season of the Spirit`'s
striving with man for the salvation of his soul (to some shorter,
and to others longer, according as the Lord in His wisdom sees fit),
which more than sufficiently exonerates God of every man`'s condemnation.
Moreover, it is evidently possible for men to outlive this day or time of visitation,
after which there is no possibility of salvation to them.
These God justly allows to be hardened as the due punishment for their unbelief,
and at times even raises them up as instruments of wrath,
and makes them a scourge one against another.^
footnote:[Barclay`'s Note:
To men in this condition may be fitly applied those Scriptures which are
often wrongly used to prove that God incites men necessarily to sin.]

This doctrine is clearly expressed by the apostle in Romans 1,
from verse 17 to the end, but especially verse 28,
"`And even as they did not like to retain God in their knowledge,
God gave them over to a debased mind, to do those things which are not fitting.`"
And that many may outlive this day of God`'s gracious visitation unto them,
is shown by the example of Esau, who had the birthright once,
and certainly could have kept it; but afterwards, when he wanted to inherit the blessing,
he was rejected.^
footnote:[Hebrews 12:16-17]
This appears also by Christ`'s weeping over Jerusalem, saying, "`If you had known,
even you, especially in this your day, the things that make for your peace!
But now they are hidden from your eyes.`"^
footnote:[Luke 19:42]
This plainly demonstrates there was a time when they might have known these things,
which time now was removed from them, though they were yet alive.

[.numbered]
II+++.+++ Secondly, we say that there is a Seed, or measure of grace, a Word of God, or Light,
by which every man is enlightened (having been given a measure of it),
which strives with them in order to save them, and which may,
by the stubbornness and wickedness of man`'s will, be quenched, bruised, wounded,
pressed down, slain and crucified.
Now, we do not understand this to be the proper essence and nature of God,
strictly taken, which is not divisible into parts and measures, but is a most pure,
simple being, void of all composition or division;
and in this sense He cannot be resisted, hurt, wounded, crucified,
or slain by all the efforts and strength of men.
But we understand this Seed to be a spiritual, heavenly,
and invisible emanation in which God (as Father,
Son and Spirit) dwells--a measure of whose divine and glorious life is sown in all men,
and which, of its own nature, draws, invites, and inclines to God.
And this we call the spiritual flesh and blood of Christ, which came down from heaven,
upon which all the saints do feed, and are thereby nourished to eternal life.
And as every unrighteous thought or action is witnessed
against and reproved by this Light and Seed,
so, by such wicked actions it is said to be wounded, crucified, or slain,
and so draws back or flees from them.

Now, because this Seed is never separated from God, but wherever it is,
God and Christ are as wrapped up therein, in this respect we say that,
when the Seed is resisted, then God is resisted; and where it is borne down,
God is said to be pressed, as a cart under sheaves,^
footnote:[Amos 2:13]
and Christ is said to be slain and crucified in men.^
footnote:[Hebrews 6:6]
And on the contrary, as this Seed is received in the heart,
and allowed to bring forth its natural and proper effect,
Christ comes to be formed and raised.
The Scripture makes frequent mention of this, calling it "`the new man,`"^
footnote:[Ephesians 4:24; Colossians 3:10]
"`Christ formed within,`"^
footnote:[Galatians 4:19]
or "`Christ within, the hope of glory.`"^
footnote:[Colossians 1:27]
And this is that Christ within of whom we so often speak and declare, preaching Him,
and exhorting people to believe in the Light, and obey it,
that they may come to know Christ in them to deliver them from all sin.

But by preaching this Light or Seed within,
we do not at all intend either to equal ourselves to the Lord Jesus Christ,
who was born of the virgin Mary,
and in whom all the fullness of the Godhead dwelt bodily,
nor to destroy the reality of His present existence.
For, though we affirm that Christ dwells in us, His presence in us is in measure,
through the mediation of His Seed.
But in that holy Man, the Lord Jesus Christ, the eternal Word (which was with God,
and was God) dwelt in fullness and without mediation.
He then is as the head, and we are as the members; He is the vine,
and we are the branches.

[.numbered]
III+++.+++ Thirdly, we understand this Seed, Light, or Grace to be a real spiritual substance,
which the soul of man is capable to feel and apprehend, and from which a real, spiritual,
inward birth in believers arises, which is called in Scripture the new creature,
or the new man in the heart.
This seems strange to carnally minded men because they are not acquainted with it,
but we know it, and are sensible of it, by true and certain experience.
Indeed it is impossible for a man in his natural wisdom
to comprehend it until he comes to feel it in himself,
and then he finds that holding it as a mere notion does but little avail him.
Yet, though men deny it, we are able to make it appear to be true,
and to show that our faith concerning it is not without solid ground.
For it is in and by this inward and substantial Seed in our hearts,
as it comes to receive nourishment, and to have a birth in us,
that we come to have those spiritual senses
raised by which we are made capable of tasting,
smelling, seeing, and handling the things of God.
For a man cannot reach unto these things by his natural spirit and senses,
as is above declared.

[.numbered]
IV+++.+++ Fourthly, by insisting upon these things, we do not hereby intend, in any way,
to lessen or derogate from the atonement and sacrifice of Jesus Christ;
but on the contrary, we do magnify and exalt it.
For as we believe all things which are recorded
in the holy Scriptures concerning the birth,
life, miracles, sufferings, resurrection and ascension of Christ,
so we also do believe that it is the duty of everyone to whom
these truths have been declared to believe the same.
Indeed,
we look upon it as damnable unbelief __not__ to believe
whenever these things have been rightly presented.
For the holy Seed that is sown in man, when minded,
does lead and incline every heart to believe the
truths of Scripture as they are made known.
For though it does not reveal in every heart the
outward and historical knowledge of Christ,
yet it always assents to it whenever it is declared.

And as we firmly believe it was necessary that Christ should come,
so that by His death and sufferings He might
offer up Himself a sacrifice to God for our sins,
who Himself "`bore our sins in His own body on the tree;`"^
footnote:[1 Peter 2:24]
so we believe that the remission of sins, which any partake of, is only in,
and by virtue of, that most satisfactory sacrifice, and not by any other way;
for it is "`through one Man`'s righteous act that the
free gift has come upon all to justification.`"^
footnote:[Romans 5:18]

We moreover affirm,
that even as all men partake of the fruit of Adam`'s fall by reason of
that evil seed which through him is communicated unto them,
making them prone and inclined unto evil,
even though millions are ignorant of Adam`'s fall,
never having heard of his eating the forbidden fruit--so also,
many may come to feel the influence of this holy and divine Seed and Light,
and be turned from evil to good by it,
though they know nothing of Christ`'s coming in the flesh,
through whose obedience and sufferings this gift is purchased for them.
And, as we affirm it to be absolutely needful that those do
believe the history of Christ`'s outward appearance,
to whom it pleased God to bring the knowledge of it; so we do freely confess,
that even the outward knowledge is very comforting to such as are subject to,
and led by the inward Seed and Light.
For, not only does hearing of Christ`'s love and sufferings tend to humble them,
but they are thereby also strengthened in their faith,
and encouraged to follow that excellent pattern which He has left us,
"`who suffered for us,`" as says the apostle Peter,
"`leaving us an example that we should follow his steps.`"^
footnote:[1 Peter 2:21]
Indeed,
many times we are greatly edified and refreshed with the
gracious sayings which have proceeded from His mouth.
The history then is truly profitable and comforting when known together with the mystery,
and never without it.
But the mystery may be profitable without the
explicit and outward knowledge of the history.

[.numbered]
V+++.+++ But fifthly, this brings us to another question,
namely--whether Christ is therefore in all men?
We have said before that a divine, spiritual,
and supernatural Light has been given to all men;
that God and Christ dwell in it and are never separated from it; and also that,
as this is received and yielded to in the heart,
Christ comes to be formed and brought forth.
But we are far from ever having said that Christ is received by all men,
and much less formed in all men; for that is a great attainment,
for which the apostle travailed that it might be brought forth in the Galatians.
Neither is Christ in all men by way of union, or indeed, to speak strictly,
by way of dwelling or inhabiting; because this inhabiting implies a union,
or the manner in which Christ resides in the saints.
As it is written "`I will __dwell__ in them, and __walk__ in them.`"^
footnote:[2 Corinthians 6:16]

However, in a more general sense, seeing that Christ never is, nor can be,
separate from that holy pure Seed and Light which testifies in all men,
it may thus be said that He is in all.
As observed previously,
it is in this sense the Scripture says God is pressed
down as a cart under sheaves (Amos 2:13),
and that Christ is crucified in the ungodly (Hebrews 6{^
}6)--though to speak properly and strictly,
neither can God be pressed down, nor Christ, as God, be crucified.
But in this respect, we can direct all men to seek Christ within,
who lies crucified in them by their sins and iniquities,
that they may "`look upon Him whom they have pierced,`"^
footnote:[Zechariah 12:10]
and repent.
Then, He who now lies slain and buried in them (so to speak), may come to be raised,
and have dominion in their hearts over all.
In this way also the apostle Paul preached to the Corinthians and Galatians
concerning "`Christ crucified in them,`" (__en humin__ as the Greek has it.)^
footnote:["`For I determined not to know anything in
you except Jesus Christ and Him crucified.`"
1 Corinthians 2:2; "`O foolish Galatians!
Who has bewitched you that you should not obey the truth,
before whose eyes Jesus Christ was clearly portrayed in you as crucified.`"
Galatians 3:1]
This Jesus Christ was that which the apostle desired to know in them,
and make known unto them,
that they might come to be sensible how they had been resisting and crucifying Christ,
and that so they might repent and be saved.
And because Christ is called "`the true Light, that enlightens every man,`"^
footnote:[John 1:9]
"`the Light of the world,`"^
footnote:[John 8:12]
this Light is therefore taken to be Christ, who truly is the fountain of all light,
and has His dwelling in it forever.
Thus the Light of Christ is sometimes called Christ, i.e., that in which Christ is,
and from which He is never separated.

[.numbered]
VI+++.+++ Sixthly, it will clearly appear by what is above said,
that we do not understand this divine Seed or Light to be any part of man`'s nature,
nor to be any relic of any good which Adam lost by his fall;
for we know it to be a distinct and separate thing from
a man`'s soul and all the faculties of it.
Yet such is the malice of our adversaries, that they do not cease to reproach us,
as if we preached up a natural light, or the light of man`'s natural conscience.
But we certainly know that the Light of which we speak is not only distinct,
but of a different nature from the soul of man,
and all of its operations and capacities.

We do not deny that man, as he is a rational creature,
has reason as a natural faculty of his soul,
by which he can discern things that are rational.
Indeed, this is a property natural and essential to him,
by which he can know and learn many arts and sciences,
beyond what any other animal can do by mere animal faculties.
Nor do we deny that man, by this rational principle,
may apprehend in his brain and his notions, a knowledge of God and spiritual things;
yet this not being the right organ for true spiritual knowledge,
it cannot profit him towards salvation, but often rather hinders him.
And truly,
the great cause of the apostasy has been that man has sought to comprehend
the things of God in and by this natural and rational principle,
and to build up a religion in it,
neglecting and overlooking the Light and Seed of God in the heart.
Thus has Antichrist, "`exalted himself`" in every man,
"`taking his seat in the temple of God, displaying himself as being God.`"^
footnote:[2 Thessalonians 2:4]
For men being "`the temple of the Holy Spirit,`"^
footnote:[1 Corinthians 3:16]
as the apostle says, whenever the natural reason sets itself up there,
above the Seed and Light of God,
to reign and rule as a prince in spiritual things (while the
holy Seed is wounded and bruised),
there is Antichrist in every man, or something exalted above and against Christ.

Nevertheless,
we do not hereby suggest that man has received his reason to no purpose,
or that it is of no service to him: not at all.
For we look upon reason as fit to order and rule man in natural things.
And even as God gave two great lights to rule the outward world, the sun and moon,
the greater light to rule the day, and the lesser light to rule the night;
so He has given man the Light of His Son, a spiritual divine Light,
to rule him in things spiritual, and the lesser light of reason,
to rule him in things natural.
And even as the moon borrows her light from the sun, so ought men,
if they would be rightly and comfortably ordered in natural things,
to have their reason enlightened by this divine and pure Light.
For we confess that, in those that obey and follow this true Light,
their enlightened reason may be useful to man even in spiritual things,
so long as it is still subservient and subject to the other;
even as the biological life in man, when regulated and ordered by his reason,
helps him in going about things that are rational.

We do further rightly distinguish the Light of
Christ from man`'s natural conscience;
for conscience, being that in man which arises from the natural faculties of man`'s soul,
may be defiled and corrupted.
The apostle Paul, speaking of the impure, expressly says,
"`Even their mind and conscience is defiled.`"^
footnote:[Titus 1:15]
However, this Light can never be corrupted or defiled,
nor did it ever consent to evil or wickedness in any;
for it is expressly said that it "`makes all things manifest that are reprovable,`"^
footnote:[Ephesians 5:13]
and so is a faithful witness for God against every unrighteousness in man.

Now conscience, to define it truly, comes from the Latin __conscire__,
and is that knowledge which arises in man`'s heart from what agrees with,
or is contrary to, anything believed by him,
whereby he becomes conscious to himself that he transgresses
by doing something he is persuaded he ought not to do.
So then, when the mind has been blinded or defiled with a wrong belief,
there arises a conscience from that belief, which troubles him when he goes against it.
For example, when a Muslim,
who has possessed himself with a false belief that it is unlawful for him to taste wine,
acts against his belief and drinks, his conscience smites him for it;
but if he keeps many concubines, his conscience does not trouble him,
because his judgment is already defiled with a false
opinion that it is lawful for him to do the one,
and unlawful to do the other.
However, if the Light of Jesus Christ in him were minded, it would reprove him,
not only for committing fornication,
but would also inform him (as he became further
obedient to it) that Muhammad is an impostor,
just as Socrates, in his day, was informed by it of the falsity of the heathens`' gods.

Likewise, if a Roman Catholic were to eat meat during Lent,
or not be sufficiently diligent in the adoration of saints and images,
his conscience would smite him for it,
because his judgment is already blinded with a false belief concerning these things.
However, the Light of Christ never consented to any of those abominations.
So then, man`'s natural conscience is sufficiently distinguished from it;
for conscience follows the judgment; it does not inform it.
But this Light, as it is received and obeyed, removes the blindness of false judgment,
opens the understanding, and rectifies both the judgment and conscience.
Thus we confess that conscience is an excellent thing,
wherever it is rightly informed and enlightened from above.
Indeed, some of us have fitly compared it to a lantern,
and the Light of Christ to the candle within.
A lantern is useful when a candle burns and shines brightly within it,
but otherwise it is of no use.
It is therefore to the Light of Christ __in the conscience__,
and not to man`'s natural conscience, that we continually commend men.
This is their certain guide unto life eternal.

Lastly, this Light, Seed, etc.,
is seen to be no power or natural faculty of man`'s mind, because a healthy man can,
when he pleases, stir up, move, and exercise the faculties of his soul; indeed,
he is master of them, and except there be some natural cause or impediment in the way,
he can use them at his pleasure.
But this Light and Seed of God in man cannot be moved and stirred up when man pleases;
rather it moves, blows, and strives with man as the Lord sees fit.
For though there be a possibility of salvation extended
to every man during the day of his visitation,
yet man cannot, at any time when he pleases, or whenever he has a sense of his misery,
stir up that Light and Grace so as to procure for himself real tenderness of heart.
Instead, he must wait for it, as it comes upon all at certain times and seasons,
working powerfully upon the soul, mightily tendering and breaking it.
At such a time, if a man does not resist it, but receives and follows it,
he comes to know salvation by it.
Even as the pool of Bethesda did not cure all,
but only those who waited for the stirring of the waters, so God, at certain times,
moves in love to mankind by His Seed in their heart,
setting their sins in order before them, seriously inviting them to repentance,
and offering them remission of sins and salvation; which, if a man accepts,
he may be saved.

Now, there is no man alive, and I am confident there never shall be, who,
if they will deal faithfully and honestly with their own hearts,
will not be forced to acknowledge that they have been sensible of this in some measure,
less or more;
which is a thing that man cannot bring upon himself with all his pains and industry.
This then, O man and woman, is the day of God`'s gracious visitation to your soul,
and you shall be happy forever if you resist it not.
This is the day of the Lord, which, as Christ says, is like the lightning,
which shines from the east unto the west, and like the wind or spirit,
which blows upon the heart, and no man knows where it comes from, or where it goes.

=== The Seed`'s Operation in the Heart

[.numbered]
VII+++.+++ Seventhly,
this leads me to speak concerning the manner of this
Seed or Light`'s operation in the hearts of all men,
which will show even more clearly how we vastly differ from
all those who exalt a natural power or light in man,
and how our principle leads, above all others,
to attribute our whole salvation to the mere power, Spirit, and grace of God.

Some have presented us with the following question:
If two men have equal and sufficient Light and Grace, and the one is saved by it,
and the other not, is not then the will of man the true cause of the one`'s salvation,
beyond the other?
To this question we answer: that as the Grace and Light in all is sufficient to save all,
and of its own nature would save all, so it strives and wrestles with all to save them.
He that resists its striving is the cause of his own condemnation;
he that does not resist, finds it to become his salvation.
So then, in the one that is saved, the working is of the grace, and not of the man,
and this is in his yielding and passiveness, rather than his acting.
However, afterwards, as a man is wrought upon by the grace,
there is a will raised in him by which he comes to be a coworker with the grace;
for as Augustine has said, "`He that made us without us, will not save us without us.`"

Thus, the first step is not by man`'s working,
but by his __not__ working contrary to the Light and Grace of God.
And during these seasons of every man`'s visitation, though man is wholly unable,
of himself, to work with the grace,
nor to move one step out of his natural condition until grace lays hold upon him,
yet it is possible for him to be passive and not resist it,
or to be stubborn and resist it.
So we say, the grace of God works in and upon man`'s nature, which,
though of itself wholly corrupt and defiled, and prone to evil, yet,
is capable to be wrought upon by the grace of God--even as iron,
though a hard and cold metal of itself,
may be warmed and softened by the heat of the fire, and wax melted by the sun.
And, as iron or wax,
when removed from the fire or sun returns to its
former condition of coldness and hardness,
so man`'s heart, as it resists or retreats from the grace of God,
returns to its former condition again.
I have often had the manner of God`'s working towards the salvation of
all men illustrated to my mind by one or two clear analogies,
which I shall here add, for the information of others.

The first is of a man greatly diseased,
to whom I compare man in his fallen and natural condition.
Now, some suppose that God, the great physician,
offers medicine to this poor man only after he has done all in his power,
by any skill or knowledge of his own, to secure his own health.
These are those that say, if a man improve his reason or natural faculties,
then God will see fit to supply grace.
Others say that God comes and makes an offer of a remedy to the sick man,
but leaves it to the liberty of the man`'s will either to receive it or reject it.
But we say, that He, even the Lord, this great physician,
comes and pours the remedy into the sick man`'s mouth and lays him in his bed, so that,
if the sick man be but passive, it will necessarily work the cure.
But if he is stubborn and troublesome,
and insists upon rising up and going forth into the cold,
and eating such foods as are hurtful to him while the medicine should operate; then,
though of its nature the medicine tends to cure him,
yet it will prove destructive to him in the end.
So then, in this example,
the man who perishes would certainly be the cause of his own death;
and the man who is cured would owe his health wholly to the physician,
and not to any deed of his own.

The second example is of several men lying in a dark pit together,
where all their senses are so stupefied that
they are scarcely sensible of their own misery.
To this I compare man in his natural, corrupt, and fallen condition.
Again, we do not understand that God looks down and,
upon seeing one doing all in his power to deliver himself,
decides that such a one deserves to be assisted.
Nor do we suppose that a deliverer comes to the top of the pit, puts down a ladder,
and expects them to ascend in their own strength, understanding, and will.
Instead, we believe that the deliverer comes at certain times,
and fully discovers and informs the men of the great misery and hazard they
are in if they continue in that horrid and unhealthy place.
Indeed, this deliverer forces them to a certain sense of their misery,
(for even the wickedest of men are at times made
sensible of their misery by God`'s visitation),
and not only so, but at times lays hold upon them, and gives them a pull,
in order to lift them out of their misery--which if they do not resist, will save them;
only they may resist it.

These two examples, in some measure, do illustrate the matter,
showing that the grace of God reaches all,
though its effect differs according to the object it meets with.
For this grace is a ministration of mercy and love in all those that do not reject it,
but receive it (John 1:12);
but the same is a ministration of wrath and
condemnation in those that do reject it (John 3:19);
even as the sun, by one act or operation, melts and softens wax,
but dries and hardens clay.
The nature of the sun is to cherish the creation,
and therefore the living are refreshed by it,
and the flowers send forth a good savor as it shines upon them,
and the fruits of the trees are ripened.
However, with a dead carcass, a thing without life,
the same rays of the sun will cause it to stink, and putrefy it.
So then, every man, during the day of his visitation,
is shined upon by the sun of righteousness, and capable of being influenced by it,
so as to send forth good fruit, and a good savor, and to be melted by it.
But when a man has rejected the light, and has sinned out his day,
then the same sun hardens him, as it does the clay,
and makes his wickedness more to appear and putrefy, and send forth an evil savor.
