== Chapter IV. The Proof of Our Position

Having then clearly and evidently stated the issues
and given our mind and judgment in these matters,
so it will make our proof both the easier and the shorter.

=== A Day or Time of Visitation

The first thing to be proved is that God has
given to every man a day or time of visitation,
wherein it is possible for him to be saved.
If we can prove that there is a day and time given in which some might have been saved,
who actually perished, the matter is done.
But this clearly appears by the many regrets and complaints
expressed by the Spirit of God throughout all the Scriptures,
even to those that did perish;
blaming them for having not accepted or received
God`'s visitation and offer of mercy to them.

In this way the Lord did express Himself in the beginning to Cain,
saying "`Why are you angry?
And why has your countenance fallen?
If you do well, will you not be accepted?
And if you do not do well, sin lies at the door.`"^
footnote:[Genesis 4:6-7]
This was said to Cain before he slew his brother Abel,
when the evil seed had begun to tempt him and work in his heart.
Here we see how God gave a warning to Cain in season,
in the day of His visitation towards him,
offering him acceptance and remission if he did well;
for this question "`Will you not be accepted?`"
implies the affirmative, "`You will be accepted, if you do well.`"
So then, if we can trust God Almighty, the fountain of all Truth and equity,
then it was possible for a time even for Cain to be accepted.
For surely God would not have proposed the doing of good as a condition,
if He had not also given to Cain sufficient power whereby he was enabled to do it.

This the Lord also shows in giving a day of visitation to the old world:
"`And the Lord said,
'`My Spirit shall not always strive in man;`'`"
(for so it ought to be translated).^
footnote:[Genesis 6:3,
// lint-disable invalid-characters
בָ אָ דָ ם --i.e. "`in man`"]
This manifestly implies that His Spirit __did__ strive with man,
and __does__ strive with him for a season,
which season expires when God ceases to strive with them in order to save them.
And it is during this day of visitation given to all
men that God is said to "`wait to be gracious,`"^
footnote:[Isaiah 30:18]
and to be "`long-suffering`"^
footnote:[Exodus 34:6; Numbers 14:18; Psalms 86:15; Jeremiah 15:15, etc.]
towards His creation.
The apostle Peter says expressly that the "`long-suffering of
God waited in the days of Noah for those of the old world,`"^
footnote:[1 Peter 3:20]
which being compared with Gen. 6:3, before mentioned,
does sufficiently support our proposition.
And that none may object that this long-suffering or
striving of the Lord was not in order to save them,
the same apostle expressly says that "`the long-suffering
of God is to be accounted salvation;`"^
footnote:[2 Peter 3:15]
for, as he affirms a little before (vs. 9),
"`God is not willing that any should perish.`"

In the following verse, Peter further refers to the writings of Paul,
showing this to have been the universal doctrine of the church.
And it is observable what he adds upon this occasion,
how there are some things in Paul`'s epistles which are hard to understand,
which the unstable and unlearned twist to their own destruction,
most likely insinuating Paul`'s expressions from Romans 9. Many indeed,
who are unlearned in spiritual things,
have made Paul`'s words contradict the truth of God`'s long-suffering
towards all and His will that not any should perish,
but all be saved.
If only these had given more heed to Peter`'s warning!

But the place in Paul`'s writings which
Peter seems here most particularly to hint at,
does much contribute also to clear up the matter.
For Paul writes: "`Or do you despise the riches of His goodness, forbearance,
and longsuffering, not knowing that the goodness of God leads you to repentance?`"^
footnote:[Romans 2:4]
Here he speaks to the unregenerate and to the wicked,
who in the following verse he says "`are treasuring up wrath unto the day of wrath.`"
But to such as these he commends the riches of the forbearance and long-suffering of God,
showing that the tendency of God`'s goodness leads men to repentance.
How could it necessarily tend to lead them to repentance,
and how could it be called riches or goodness to them,
if there were not a time wherein they might repent and
come to be sharers of the riches offered by it?

From all which I thus argue:
If God pleads with the wicked from the possibility of their being accepted;
if God`'s Spirit strives in them for a season in order to save them,
though they afterwards perish; if He waits to be gracious to them;
if He is long-suffering towards them,
and this long-suffering (while it endures) is unto salvation,
during which time God does not will them to perish,
but exhibits to them the riches of His goodness and forbearance in
order to lead them to repentance--then I conclude,
there is a day of visitation given to men wherein they may be saved, if they repent.

Moreover, the same appears from the prophet Isaiah, where it is said:
"`What more could have been done to My vineyard that I have not done?`"
For in the second verse he says: "`He dug it up and cleared out its stones,
and planted it with the choicest vine.
He built a tower in its midst, etc.`"
And yet, when "`He expected it to bring forth good grapes,
it brought forth wild grapes.`"^
footnote:[Isaiah 5:2]
Therefore he calls the inhabitants of Jerusalem and the
men of Judah to judge between Him and His vineyard,
saying; "`What more could have been done to My vineyard that I have not done in it?`"
This parable was applied to many in Israel who
refused God`'s mercy in the days of the kings,
and the same example was used by Christ (Matt. 21:33; Mark 12:1;
Luke 20:9). Here Jesus shows that a vineyard was planted,
and that all things necessary were given to the workers
in order to gather fruit to repay their master.
The master many times waited to be merciful to them, sending servants after servants,
and passing by their many offenses,
before determining at last to destroy and cast them out.
Now then, this parable could not have been spoken with reference to the saints,
or to those who repent and are saved; for it says expressly, "`He will destroy them.`"
Nor is it reasonable to suggest that these men were not in a capacity to have done good,
for the Lord`'s expectation was plain,
and indeed He says through the prophet "`What more could I have done?`"
So then,
it is more than manifest by this parable (repeated in three gospels)
that Christ holds forth His long-suffering towards men,
even in their wickedness, for a time, affording them a true means of salvation;
and that those who nevertheless resist, do so to their own condemnation.
See also the following parallel scriptures: Prov. 1:24-26; Jer. 18:9-10;
Matt. 18:32-34; Acts 13:46.

Lastly,
that there is a day of visitation given to the wicked wherein they might have been saved,
and which, having expired, they are shut out from salvation,
appears evidently by Christ`'s lamentation over Jerusalem,
expressed in three separate places (Matt. 23:37; Luke 13:34; and 19:41-42):
"`Now as He drew near, He saw the city and wept over it, saying, '`If you had known,
even you, especially in this your day, the things that make for your peace!
But now they are hidden from your eyes.`'`" And "`O Jerusalem, Jerusalem,
the one who kills the prophets and stones those who are sent to her!
How often I wanted to gather your children together,
as a hen gathers her brood under her wings, but you were not willing!`"
What could more evidently prove our doctrine?
For first,
He insinuates that there __was__ a day wherein the inhabitants of
Jerusalem might have known those things that belonged to their peace.
And secondly, He manifests that during that day He was willing to have gathered them,
even as a hen gathers her chicks.
This illustration shows plainly that the offer of
salvation made to them was not in vain on His part,
but was as real,
and with as great cheerfulness and willingness as a hen gathers her chicks.
Indeed, even as a hen shows love and care towards her brood,
such is the care of Christ to gather lost men and women,
to redeem them out of their corrupt and degenerate state.
Then thirdly, it is seen how, because they refused,
the things belonging to their peace were hidden from their eyes.
And why were they hidden?
Because they would not allow Him to gather them;
they would not see those things that were good for them
in the season of God`'s love towards them.
And therefore, that day having expired, they could not see them;
and so God permitted them to be hardened in unbelief.

So it is __after__ real offers of mercy and salvation are rejected,
that men`'s hearts are hardened, and not before.
Thus that saying is verified, "`Whoever has, to him more will be given;
but whoever does not have, even what he has will be taken away from him.`"^
footnote:[Mark 4:25]
This may seem a riddle, yet it is easily solved according to this doctrine.
He has not, because he has lost the season of using what he had,
and so it is now to him as nothing.
For Christ uses this expression (Matt. 25:26) upon the
occasion of taking the one talent from the slothful servant,
and giving it to him that was diligent--which
talent was in no way insufficient of itself,
but was of the same nature as those given to the others.
Therefore the Lord had reason to expect the profit of it proportionably,
as well as from the rest.

So I say, it is after the rejecting of this day of visitation,
that the judgment of hardness is inflicted upon men and women,
even as Christ pronounced it upon the Jews (quoting from Isaiah 6:9,
of which all four evangelists make mention: Matt. 13:14; Mark 4:12; Luke 8:10;
John 12:40). And the apostle Paul,
after he had offered the Gospel of salvation to the Jews at Rome,
makes mention of the same, saying,
"`The Holy Spirit spoke rightly through Isaiah the prophet to our fathers,
'`Go to this people and say: "`Hearing you will hear, and shall not understand;
and seeing you will see, and not perceive; for the hearts of this people have grown dull.
Their ears are hard of hearing, and their eyes they have closed,
lest they should see with their eyes and hear with their ears,
lest they should understand with their hearts and turn, so that I should heal them.`'`"^
footnote:[Acts 28:24-27]
So it again appears that God desired them to see, but having closed their eyes,
they are therefore justly hardened.

Of this matter Cyril of Alexandria speaks well,
in answering the following objection: "`But some may say,
if Christ has come into the world that those who see may be blinded,
then their blindness is not to be imputed unto them; but rather to Christ,
who is the cause of their blindness.
But such as these speak irrationally, who are not afraid to call God the author of evil.
For as the natural sun is carried upon our horizon that
it may communicate the gift of its clearness unto all,
and make its light shine upon all, yet if anyone close his eyelids,
or willingly turn himself from the sun, refusing the benefit of its light,
he lacks its illumination, and remains in darkness.
This, no doubt, is through no defect of the sun, but through his own fault.
In the same way, Christ, the true Sun, came to enlighten those that sat in darkness,
and in the region of the shadow of death,
that He might communicate unto all the gift of knowledge and grace,
and illuminate the inward eyes of all by His own spiritual splendor.
But many reject the gift of this heavenly Light freely given to them,
having closed the eyes of their minds,
lest so excellent an illumination of the eternal Light should shine unto them.
It is not then through defect of the true Sun that they are blinded,
but only through their own iniquity and hardness; for, as the wise man has said,
'`their wickedness has blinded them.`'`"^
footnote:[John, lib. 6, cap. 21.]

From all which I argue:
If there was a day wherein the obstinate Jews might
have known the things that belonged to their peace,
which, because they rejected them, were hid from their eyes;
and if there was a time wherein Christ would have gathered some who,
because they refused, could not be gathered; then those who might have been saved,
do actually perish, because they have slighted the day of God`'s visitation towards them.

=== A Measure of Saving Light and Grace Given to Man

That which must next be proved is the way by which God seeks
to work salvation in man during the day of his visitation,
which is through a measure of saving, sufficient,
and supernatural Light and Grace given to every man.
This I shall prove, by God`'s assistance,
with several plain and clear testimonies of the Scripture.

First, from John 1:9:
"`That was the true Light which gives light to every man coming into the world.`"
This scripture does so clearly favor us,
that it is called by some "`the Quakers`' text`"--for it so plainly demonstrates our
position that there is scarcely need for either interpretation or deduction.
Indeed,
this verse is itself something of a conclusion which follows two previous assertions,
namely, that "`In Him was life,
and the life was the light of men,`" and "`The Light shines in the darkness,
and the darkness did not comprehend it.`"

Let us first observe that this apostle calls Christ the "`Light of
men,`" and gives this to us as one of His chief properties.
And the same apostle says elsewhere that it is as we walk with
Him in that Light (which He communicates to us),
that we come to have fellowship and communion with Him.^
footnote:[1 John 1:7]
Secondly, we are told that "`this Light shines in darkness,
though the darkness did not comprehend it.`"
And thirdly,
that this is the "`true Light which gives light to every man coming into the world.`"
Here the apostle, being directed by God`'s Spirit,
has carefully avoided that notion of our adversaries,
who would restrict this Light to a certain number of individuals.
For, where it says "`every man,`" there is clearly no man excluded.
And should they be so obstinate (as sometimes they are) as to
say that this "`every man`" is only every one of the elect,
then the following words,
"`every man coming into the world,`" does invalidate their objection.
Therefore,
it is here plainly asserted that no man comes into the
world whom Christ has not enlightened in some measure,
and in whose dark heart this Light does not shine.
Though the darkness does not comprehend it, still it shines there,
and its nature is such as would dispel the darkness,
whenever men do not shut their eyes upon it.
Indeed,
the purpose for which this Light is given is expressed in verse 7--"`that all men,
through it +++[+++that is, through the Light], might believe.`"^
footnote:[Barclay`'s Note:
__di`' autou__ (through it) does very well agree with photos (the Light),
as being the nearest antecedent;
though many translators have made it relate to
John (to make it suit with their own doctrine),
as if all men in the world were to believe through John.
But all could not believe through John,
because all men could not know of John`'s testimony;
whereas every man being enlightened by this Light may through it come to believe.
John shined not in the darkness; but this Light shines in the darkness, so that,
having dispelled the darkness, it may produce and beget faith.
And it is by walking in this Light that we have this communion and fellowship,
not by walking in John, which is nonsense.
So that this relative __di`' autou__ must necessarily refer to the Light (__photos__),
of which John bears witness, so that through that Light,
with which Christ has enlightened every man, all men might come to believe.]

Seeing then that this Light is the Light of Jesus Christ,
and is said to be the Light through which men come to believe,
I think it need not be doubted that it is a supernatural, saving, and sufficient^
footnote:[Editor`'s Note: i.e. sufficient for the salvation of the soul.
Some adversaries of early Friends,
while admitting that the Light of Christ is given in measure to every man,
insisted that this is a measure or endowment __insufficient__ to save the soul.
These argued that there is a __common grace__ (or illumination) by
which all men possess moral discernment between good and evil,
and then a separate and __saving grace__, which is bestowed upon Christians only.]
Light.
If it were not supernatural, it could not properly be called the Light of Jesus.
And surely the Light which enlightens man cannot be any
of the natural gifts or faculties of his soul,
because it is said to "`shine in the darkness,`"^
footnote:[2 Corinthians 4:6]
and cannot be comprehended by it.
Now this "`darkness`" is no other than man`'s natural condition and state,
in which natural state he can easily comprehend, and does comprehend,
those things which are common to him as man.
But that man in his natural condition is called darkness, see Ephesians 5:8:
"`For you were once darkness, but now you are light in the Lord.`"
and several other places, such as Acts 26:18, Colossians 1:13,
and 1 Thessalonians 5:5,
where the condition of man in his natural state is termed "`darkness.`"
Therefore, I say,
this Light that shines in darkness cannot be any
natural property or faculty of man`'s soul,
but must be the supernatural gift and grace of Jesus Christ.

And that this Light is sufficient and saving is apparent in
that it was given "`that all men through it may believe.`"
Moreover, we are told that, by walking in it, we enjoy fellowship with the saints,
and "`the blood of Jesus Christ cleanses us from all sins.`"^
footnote:[1 John 1:7]
And that which we are commanded to believe in,
in order "`to become the children of Light,`" must certainly be a supernatural,
sufficient, and saving principle; for Christ has said, "`While you have the Light,
believe in the Light, that you may become the children of the Light.`"^
footnote:[John 12:36]

Some object that by "`Light`" here,
the disciples were meant to understand Christ`'s __outward__ person,
in which He desired them to believe.
Now, we do not deny that they ought to have believed in Christ`'s outward appearance,
acknowledging Him to be the Messiah who was to come.
But how this could be the intent of Christ`'s words in this place I do not see.
For the words "`while you have the Light,`" and those of the previous verse,
"`Walk while you have the Light lest darkness come upon you,`" clearly imply that,
when that Light in which they were to believe was removed,
then they should lose the capacity or season of believing.
This could not be understood of Christ`'s outward appearance,
since many did savingly believe in Him (as do all Christians at this day)
when His bodily presence or outward man was far removed from them.
So that this Light in which they were commanded to believe must be that inward,
spiritual Light, that shines in their hearts for a season,
even during the day of man`'s visitation.
While this Light continues to call, invite and exhort,
men are said to have it and may believe in it; but when men refuse to believe in it,
and reject it, then it ceases to be a Light to show them the way,
and leaves the sense of their unfaithfulness as a sting in their conscience,
which is a terror and darkness unto them and in which they cannot know where to go.
Therefore, to such rebellious ones as these,
the "`day of the Lord`" is said to be "`darkness and not light.`"^
footnote:[Amos 5:18]

So then, it appears that,
though many do not receive the Light (as the darkness does not comprehend it),
nevertheless this saving Light shines in all that it might save them.
Concerning this, Cyril of Alexandria has spoken well:

[quote]
____
"`With great diligence and watchfulness,`" he says "`does the
apostle John endeavor to anticipate and prevent the vain thoughts of men.
He had just now called the Son the true Light,
by whom he affirmed that every man coming into the world was enlightened; yes,
and that He was in the world and the world was made by Him.
One might then object, '`If the Word of God is the Light,
and if this Light enlightens the hearts of men and suggests
unto them piety and a true understanding of things,
and if He was always in the world and was the creator or builder of the world,
then why was He so long unknown unto the world?`'
It might seem to follow that, because He was unknown to the world,
the world was therefore not enlightened by Him, nor was He totally Light.
But let not man accuse the Word of God and His eternal Light,
but rather his own weakness: for the Son enlightens,
but the creature rejects the grace that is given to it and abuses the
clearness of understanding granted it by which it might have known God.
Like the prodigal, man has turned his sight to the creation, neglecting to go forward,
and through laziness and negligence has buried God`'s illumination and despised His grace.
And it was in order to avoid this very thing that the
Thessalonians were commanded by Paul to watch and be sober.

Therefore,
the fault must be imputed to the wickedness of those who are illuminated,
and not to the Light; for though the sun rises upon all,
yet he that is blind receives no benefit by it.
None can accuse the brightness of the sun,
but will ascribe the cause of not seeing to the blindness;
and such is the case with the only begotten Son of God,
for He is the true Light and sends forth His brightness upon all.
But the god of this world, as Paul says,
has blinded the minds of those that do not believe (2 Cor. 4:4),
lest the Light of the Gospel shine unto them.

We say then, that darkness is come upon men,
not because they are altogether deprived of Light,
but because man is dulled by an evil habit and become worse,
and has made the measure of grace in some respect to languish.
By these words, then, the world is accused as ungrateful and insensible,
not knowing its Author, nor bringing forth the good fruit of their illumination.
So it seems it may now be truly said of all,
what was of old said by the prophet of the Jews "`I
expected it to have brought forth good grapes,
but it brought forth wild grapes.`"
____

From this it appears Cyril believed that a saving illumination is given unto all,
and that it is of the same kind with that grace of which Paul makes mention to Timothy,
saying, "`Neglect not the grace that is in you.`"

Now, that this saving Light and Seed, or a measure of it, is given to all,
Christ tells us expressly in the parable of the sower (Matt. 13:18; Mark 4,
and Luke 8:11). He says that the "`seed`" which is sown in
those several sorts of grounds is the "`Word of the Kingdom,`"
which the apostle calls the "`Word of faith,`"^
footnote:[Romans 10:8]
or the "`implanted Word which is able to save the soul;`"^
footnote:[James 1:21 -- "`__ho logos emphutos__`"]--which
words imply that it is of a saving nature,
and that in good soil it bears fruit abundantly.

Let us then observe that this Seed of the Kingdom--this saving, supernatural,
and sufficient Word--was really sown in the stony ground, the thorny ground,
and by the wayside, where it did not profit but became useless as to these grounds.
This was, I say, the very same Seed that was sown in the good ground.
It is then (according as Christ Himself interprets the parable) the fear of persecution,
the deceitfulness of riches, the cares of the world, and desires for other things,
which hinder this Seed from growing in the hearts of many.
It is not a lack of sufficiency in its own nature,
for it is the same that grows up and prospers in the hearts of those who receive it.
So then, it is manifest that though all are not saved by it,
yet there is a seed of salvation planted and sown in the hearts of all by God,
which seed would grow up and redeem the soul if it were not choked and hindered.

Concerning this parable, Victor of Antioch (on the fourth chapter of Mark) says,
"`Our Lord Christ has liberally sown the divine Seed of the
Word and offered it to all without respect of persons.
As he that sows distinguishes not between ground and ground,
but simply casts the seed without distinction,
so our Savior has offered the food of the divine Word to all,
although He was not ignorant what would become of many.
Indeed, He behaved Himself in such a way as He might justly say,
'`What should I have done that I have not done?`'`"

To this corresponds the parable of the talents (Matthew 25),
where he that had two talents was accepted as well as he that had five,
because the talents were used to the master`'s profit.
And he that had one talent might have done the same,
for his talent was of the same nature with the rest,
and was equally capable of bringing forth a proportionable increase.
So then,
though there is not an equal proportion of grace given to all--to some five talents,
to some two talents,
and to some but one--yet there is given to all that which is sufficient,
and no more is required than according to that which is given:
"`For unto whomsoever much is given, from him shall much be required.`"^
footnote:[Luke 12:48]
He that had the two talents and returned four was equally acceptable
to the master as he who had five talents and returned ten.
So the man who received one talent would likewise have been accepted in returning two;
for no doubt one was capable of producing two, even as the two produced four,
and the five produced ten.

Furthermore, this saving, spiritual Light __is__ the Gospel,
which the apostle expressly says is preached "`in every creature under
heaven;`" even that very "`Gospel whereof Paul was made a minister.`"^
footnote:[Colossians 1:23, Literal Translation
// lint-disable invalid-characters
"`εν παση τη  κτισει`" i.e. "`in every creature`"]
For the Gospel is not a mere declaration of good things,
but rather "`the power of God unto salvation, to all those that believe.`"^
footnote:[Romans 1:16]
Though the outward declaration of the Gospel be taken sometimes for the Gospel,
yet this is but figuratively and by a metonymy.^
footnote:[A metonymy is a figure of speech in which a thing or concept is referred
to by the name of something else closely associated with that thing or concept.
For example "`the crown`" is used to refer to the power of a king;
or "`the sword`" is used to refer to military force.]
For to speak properly,
the Gospel is the inward power and life which
preaches glad tidings in the hearts of all men,
offering salvation unto them, and seeking to redeem them from their iniquities.
It is therefore said to be preached "`in every creature
under heaven,`" though there are many thousands of men
and women to whom the outward gospel was never preached.

Therefore the apostle Paul (in Romans 1),
where he says "`the Gospel is the power of God unto salvation,`" adds
that "`therein is revealed the righteousness of God from faith to
faith;`" and also the "`wrath of God against such as suppress the
Truth of God in unrighteousness.`"^
footnote:[Romans 1:17-18]
And it is for this reason that Paul, in the following verse,
says "`because that which may be known of God is manifest in them;
for God has shown it to them.`"^
footnote:[Romans 1:19]
So then, that which may be known of God is made known by the Gospel,
which was manifest in them.
For those of whom the apostle here speaks had no outward gospel preached to them,
so that it was by the inward manifestation of the knowledge of God in
them (which is indeed the Gospel preached in man) that "`the
righteousness of God is revealed from faith to faith`"--that is,
it reveals to the soul that which is just, good, and righteous,
and as the soul receives it and believes,
righteousness comes more and more to be revealed from one degree of faith to another.
For though, as the following verse says, the outward creation declares the power of God,
yet that which may be known of Him is manifest within,
by which inward manifestation we are made capable to see and
discern the Eternal Power and Godhead in the outward creation.
So, were it not for this inward Light and Grace,
we could no more understand the invisible things of God by the outward visible creation,
than a blind man can see and discern the variety of shapes and colors,
or judge the beauty of the outward creation.
Therefore Paul first says,
"`That which may be known of God is manifest in them,`" and in
and by __that__ they may read and understand the power and Godhead
in those things that are outward and visible.
Though some might insist that the outward creation does, of itself,
without any supernatural or saving Light in the heart,
declare to the natural man that there is a God; yet, I say,
what would such a knowledge avail if it did not also
communicate to me the will and nature of God,
and how I might do what is acceptable to Him?
For the outward creation,
though it may beget a persuasion that there is some eternal
power or virtue by which the world has had its beginning;
yet it does not inform me what is just, holy, and righteous,
or how I shall be delivered from my temptations
and evil affections and come unto righteousness.
Indeed, this must be from some inward manifestation in my heart.
But these Gentiles, of whom the apostle here speaks,
knew to distinguish between good and evil by that inward law
and manifestation of the knowledge of God in them,
as is demonstrated in the following chapter of Romans.

The prophet Micah, speaking of man in general, declares this: "`He has shown you,
O man, what is good.
And what does the Lord require of you, but to do justly, to love mercy,
and to walk humbly with your God?`"^
footnote:[Amos 6:8]
Notice,
he does not speak of God`'s requirement till he has first
assured them that God has shown unto them what is good.
Now, it is because this is shown unto all men and is manifest in them,
that the apostle can say "`the wrath of God is revealed against them
in that they suppress the Truth in unrighteousness;`" that is,
they suppress the measure of Truth, the Light, the Seed, the Grace in them,
for they "`hide their talent in the earth,`" or in the
earthly and unrighteous part in their hearts,
and do not allow it to bring forth fruit.
Instead, their measure or Seed is choked with the sensual cares of this life,
the fears of reproach, and the deceitfulness of riches,
as is manifest by the above-mentioned parables.

But the apostle Paul opens and illustrates this matter yet more in Romans 10,
where he declares that the Word which he preached "`is not far off,
but near in the heart and in the mouth;`" (now the Word
which he preached and the Gospel which he preached,
and of which he was a minster, is one and the same).
He then sets up the common objection of our adversaries in the 14th and 15th verses:
"`How shall they believe in Him of whom they have not heard?
And how shall they hear without a preacher?`"
And this he answers in the 18th verse, saying, "`But, I say, have they not heard?
Yes indeed, '`Their sound has gone out to all the earth,
and their words to the ends of the world;`'`"^
footnote:[Romans 10:18, quoting from Psalms 19:4]
insinuating that this divine Preacher has sounded in the ears and hearts of all men.
For, with regard to the outward apostles this saying was not true, neither then,
nor for many hundred years after.
Indeed,
for all we know there may still be nations and kingdoms who
have never heard of Christ or his apostles outwardly.

This inward and powerful Word of God is yet
more fully described in the epistle to the Hebrews:
"`For the Word of God is living and powerful, and sharper than any two-edged sword,
piercing even to the division of soul and spirit, and of joints and marrow,
and is a discerner of the thoughts and intents of the heart.`"^
footnote:[Hebrews 4:12]
The virtues of this spiritual Word are here enumerated--it is living and powerful,
and is a searcher and trier of the hearts of all.
No man`'s heart is exempt from it, for the apostle says,
"`There is no creature hidden from His sight,
but all things are naked and open to the eyes of Him to whom we must give account.`"
Though this ultimately and mediately refers to God,
yet it nearly and immediately relates to His Word or Light, which, seeing all,
is plainly in the hearts of all.

This Word then is that faithful witness
and messenger of God that bears witness for God,
and for His righteousness in the hearts of all men.
For the Lord "`has not left man without a witness,`"^
footnote:[Acts 14:17]
and He is said to be "`given for a witness to the people.`"^
footnote:[Isaiah 55:4]
And as this Word bears witness for God, so it is not placed in men only to condemn them;
for He who is given for a witness, says the prophet,
is also "`given for a leader and commander.`"^
footnote:[Isaiah 55:4]
The Light is given that all through it may believe,^
footnote:[John 1:7]
"`for faith comes by hearing, and hearing by the Word of God,`"^
footnote:[Romans 10:17]
which is placed in man`'s heart, both to be a witness for God,
and to be a means to bring man to God, through faith and repentance.
So this Word is said to be powerful, able to divide between the soul and the spirit.
It is like a two-edged sword,
that it may cut off iniquity and separate between the precious and the vile.
And because man`'s heart is naturally cold and hard, like iron,
therefore God has placed this Word in him, which is said to be "`like a fire,
and like a hammer.`"^
footnote:[Jeremiah 23:29]
And even as by the heat of the fire, the iron (being naturally cold) is warmed,
and by the strength of the hammer it is softened
and framed according to the mind of the worker;
so the cold and hard heart of man is,
by the virtue and power of this Word of God near and in the heart,
warmed and softened (when not resisted) in order
to receive a heavenly impression and image.

The greater part of the church fathers have spoken at
length concerning this Word,
Seed, Light, and saving Voice, which calls unto salvation, and is able to save.

Clement of Alexandria says, "`The divine Word has cried, calling all,
knowing well those that will not obey.
And yet, because it is in our power either to obey or not to obey,
that none may claim the pretext of ignorance,
it has made a righteous call and requires only that which is
according to the ability and strength of everyone.`"^
footnote:[lib. 2, Stromat.]
The same author, in his Warning to the Gentiles,
says "`That heavenly ambassador of the Lord--the grace
of God that brings salvation--has appeared unto all.
This is the new song, coming, and manifestation of the Word which now shows itself in us,
which was in the beginning and was first of all.`"
And again, "`Hear, therefore, you that are afar off; hear, you who are near;
the Word is hid from none, the Light is common to all and shines to all.
There is no darkness in the Word, so let us hasten to salvation, to the new birth,
that we, being many, may be gathered unto the one true love.`"

Justin Martyr, in his first apology, says, "`that the Word which was and is,
is in all; even that very same Word which, through the prophets,
foretold things to come.`"

=== Salvation by the Inward Working of Grace and Light in the Heart

The third proposition which needs to be proved has two parts: __First__,
that it is only by this Light, Seed, or Grace that God works the salvation of men,
causing them to partake of the benefit of Christ`'s death,
and the salvation purchased by Him; and __second__,
that by the working and operation of this same Grace and Light, many have been,
and some may be saved, to whom the Gospel has never been outwardly preached,
and who (because of inescapable circumstances) are
utterly ignorant of the outward history of Christ.

Having already proved that Christ has died for all,
that there is a day of visitation given to all
men during which salvation is possible unto them,
and that God has actually given a measure of saving Grace and Light unto all,
preached the Gospel to and in them, and placed the Word of faith in their hearts,
the matter of this proposition may seem already to be proved.
Yet, for the further satisfaction of all who desire
to know the Truth and hold it as it is in Jesus,
I shall attempt to prove this from two or three clear Scripture testimonies,
and to remove the most common objections usually brought against it.

[.numbered-group]
====

[.numbered]
I+++.+++ As to the first, because it is already granted by most,
I shall try to prove it in just a few words.
First from the words of Christ to Nicodemus, "`Most assuredly, I say to you,
unless one is born again, he cannot see the kingdom of God.`"^
footnote:[John 3:3]
Now this birth does not come by the outward preaching of the Gospel,
or by a historical faith in Christ; for many have this, and firmly believe it,
and yet are not one bit renewed.
Indeed, the apostle Paul,
in his commendation of the necessity and excellence of
this "`new creation,`" goes so far as to lay aside,
in a certain respect, the outward knowledge of Christ,
or the knowledge of Him after the flesh.
He says, "`Therefore, from now on, we regard no one according to the flesh.
Even though we have known Christ according to the flesh,
yet now we know Him thus no longer.
Therefore, if anyone is in Christ, he is a new creation; old things have passed away;
behold, all things have become new.`"^
footnote:[2 Corinthians 5:16-17]
Here it clearly appears that Paul makes the knowledge
of Christ after the flesh to be the mere rudiments,
so to speak, which spiritual children learn, and which afterwards,
when they have further progressed, are of less use to them,
having come to possess the very substance to which the first precepts pointed.
Now as all comparisons have their limitations,
I shall not affirm this one to hold in every respect; but I believe it will hold in this:
that even as those who go no further than the
rudiments are never to be accounted learned,
so too those who go no further than the outward knowledge of
Christ are not to inherit the kingdom of heaven.
Yet those who come to know this new birth,
to be in Christ indeed, to be a new creature,
to have "`old things pass away and all things become new,`"
these may safely say with the apostle,
"`Though we have known Christ according to the flesh,
yet now we know Him thus no longer.`"

====

Now this new creature proceeds from the
work of Christ`'s Light and Grace in the heart.
It is begotten by that Word that is sharp and piercing (of which we have spoken),
the implanted Word that is able to save the soul.
Christ has purchased for us this holy Seed, that by it a birth might be brought forth;
and this the apostle Paul calls "`the manifestation of
the Spirit given to every one to profit withal.`"^
footnote:[1 Corinthians 12:7]

The apostle Peter also ascribes this birth to the same Seed and Word of God,
saying, "`Having been born again, not of corruptible seed but incorruptible,
through the Word of God which lives and abides forever.`"^
footnote:[1 Peter 1:23]
Though this Seed be small in its appearance,
so that Christ compares it to a "`grain of mustard seed,
which is the least of all seeds,`"^
footnote:[Matthew 13:31-32]
and though it be hid in the earthly part of man`'s heart,
yet therein is life and salvation towards the sons of men wrapped up,
which comes to be revealed as they give way to it.
And in this Seed in the hearts of all men is the Kingdom of God,
as in a capacity to be known and exhibited according as it receives depth,
and is nourished, and not choked.
So it is that Christ said the Kingdom of God was in the very Pharisees^
footnote:[Luke 17:20-21]
who did oppose and resist Him,
and were justly accounted as serpents and a generation of vipers.
Now the Kingdom of God could be in these men in no other way but as in a Seed,
even as the thirty-fold and hundred-fold increase was
wrapped up in the small seed that lay on the path,
and did not spring forth for lack of nourishment.
And just as the whole body of a great tree is
wrapped up potentially in the seed of the tree,
and so is brought forth in due season;
and as the capacity of a man or a woman is not
only in a child but even in the very embryo,
even so, the Kingdom of Jesus Christ, yes Jesus Christ himself--"`Christ within,
who is the hope of glory,`" who becomes wisdom, righteousness,
sanctification and redemption--is sown into every man`'s heart,
in that little incorruptible Seed,
ready to be brought forth as it is cherished and "`received in the love of it.`"^
footnote:[2 Thessalonians 2:10]
For no men can be said to be worse than those rebellious and unbelieving Pharisees;
and yet this Kingdom was as a seed within them,
and they were directed to look for it there.
So, it is neither "`lo here`" nor "`lo there,`" in this or the other observation,
that the kingdom is known,
but only as this Seed of God in the heart is minded and cherished.
And certainly, it is because this Light, Seed,
and Grace that appears in the heart of man is so little regarded and so much overlooked,
that so few know Christ brought forth and formed in them.

The Calvinists look upon grace as an irresistible power and therefore
neglect and despise this eternal Seed of the Kingdom in their hearts,
deeming it a low, insufficient, and useless thing as to their salvation.
On the other hand, the Catholics, Arminians,
and Socinians seek to set up their natural power and will,
and with one consent deny that this little Seed, this small appearance of the Light,
could be that supernatural and saving grace of God given to every man to save him.
Consequently, upon them is verified that saying of the Lord Jesus Christ,
"`This is the condemnation of the world, that Light is come into the world,
but men love darkness rather than Light;`" and the reason is added,
"`because their deeds are evil.`"
All confess they feel this condemnation for evil,
but they will not allow it to be of the virtue of grace.
Some call it reason; others a natural conscience;
still others call it a relic of God`'s image that remained in Adam.
Thus Christ,
even as He met with opposition from all kinds of professors in His outward appearance,
does now meet with the same in His inward appearance.
It was the lowness of His outward man that made many despise Him, saying,
"`Is not this the son of the carpenter?
Are not His brethren and sisters among us?
Is this not a Galilean?
And did ever a prophet come out of Galilee?`"
And other similar reasonings.
For they expected an outward deliverer who, as a prince,
should deliver them with great ease from their outward enemies,
and not such a Messiah as should be crucified shamefully and, as it were,
lead them into many sorrows, troubles, and afflictions.

Even so now, the lowness of Christ`'s inward appearance makes the crafty Jesuits,
the rational Socinians, and the learned Arminians overlook Him,
desiring instead something upon which they can exercise their subtlety, reason,
and learning, and also use the liberty of their own wills.
And the secure Calvinists, they would have a Christ to save them without any trouble,
to destroy all their outward enemies for them and do nothing or little within,
while they meanwhile live securely and at ease in their sins.
But when all of this is well examined the cause is plain:
it is "`because their deeds are evil`" that with one consent
they reject this Light--for it checks and reproves even the
wisest and most learned of them in secret.
Indeed, all of their logic cannot silence it,
nor can the most secure among them stop its voice from crying and reproving
them within for all their confidence in the outward knowledge of Christ.
For as we have demonstrated, in a day or time it strives and wrestles with all;
and it is the unmortified nature, the first nature, the old Adam,
yet alive in the wisest and most learned,
in the most zealous for the outward knowledge of Christ, that denies this, despises it,
and shuts it out to their own condemnation.
These then fall under the description:
"`For everyone practicing evil hates the light and does not come to the light,
lest his deeds should be exposed.`"^
footnote:[John 3:20]
Therefore, it can now be said from true and certain experience,
even as it was said of old, "`The stone which the builders rejected,
has become the chief cornerstone.`"^
footnote:[Psalms 118:22; Matthew 21:42; Mark 12:10; Luke 20:17; Acts 4:11]

Glory to God forever, who has arisen again to plead with the nations,
and therefore has sent us forth to preach this
everlasting Gospel unto all--Christ near to all,
the Light in all, the Seed sown in the hearts of all,
that men may come and apply themselves to it.
And we rejoice that we have been made to lay down our wisdom and
learning (such of us as have had some of it) and our carnal reasoning,
to learn of Jesus and sit down at His feet in our hearts and hear Him,
who there makes all things manifest and reproves all things by His Light.^
footnote:[Ephesians 5:13]
For many are wise and learned in notions, in the letter of the Scripture,
as the Pharisees were, and can speak much of Christ and plead strongly against infidels,
Turks, and Jews, and perhaps against some heresies,
who in the meantime are crucifying Christ in the
small appearance of His Seed in their hearts.
Oh it would be far better to be stripped and naked of all,
and account it all as dross and dung, and become a fool for Christ`'s sake!
Then they would know Him to teach them in their hearts;
they would witness Him raised there, feel the virtue of His cross there,
and say with the apostle,
"`God forbid that I should boast except in the cross of our Lord Jesus Christ,
by whom the world has been crucified to me, and I to the world.`"^
footnote:[Galatians 6:14]
This is better than to write thousands of commentaries
and to preach a multitude of sermons.

And truly,
it is because of the operation of this cross in our hearts
that we have denied our own wisdom and wills in many things,
and have forsaken the vain worships, fashions, and customs of this world.
For these several centuries the world has been full of a dry, fruitless,
and barren knowledge of Christ, feeding upon the husk and neglecting the kernel,
following after the shadow but strangers to the substance.
The devil cares not how much of this lifeless knowledge abounds,
provided he can still possess the heart and rule in the will,
crucifying the appearance of Christ there,
and so keep the Seed of the Kingdom from taking root.
Indeed, he has led them abroad, saying,
"`lo here`" and "`lo there,`" and has made them wrestle in a false zeal,
so often one against another, contending for this or that outward observation,
seeking Christ in this and the other external thing, such as bread and wine.
Some say it is this way; some say it is another; some say He is in Scriptures and books,
some in societies and pilgrimages and merits.
And still some, confiding in an external and barren faith,
think all is well if they do but firmly believe that He died for their sins--past,
present, and to come--while in the meantime Christ lies crucified and slain within them,
and is daily resisted and opposed in His appearance in their hearts.

It is from a sense of this blindness and ignorance that is come over Christendom,
that we are led and moved of the Lord so constantly and frequently to call all,
invite all, request all to turn to the Light in them,
to believe in and mind the Light of Christ in them.
And in the name, power,
and authority of the Lord--not in school arguments and lofty
distinctions--we do charge and direct them to lay aside their wisdom,
to come down out of that proud, airy, brain-knowledge,
to stop their mouth (however eloquent it may appear to the worldly ear),
to be silent and sit down as in the dust,
and to mind the Light of Christ in their own consciences.
If He were thus minded, they would find Him to be a sharp,
two-edged sword in their hearts,
and as a fire and a hammer that would knock against and burn up all that carnal,
gathered, natural stuff,
and make even the stoutest of them tremble and become "`Quakers`" indeed.
Alas, those who will not come to feel this now,
and to kiss the Son while their day lasts, but instead harden their hearts,
will certainly be made to feel the Truth when it is too late.
Therefore, as the apostle says, "`Examine yourselves as to whether you are in the faith.
Test yourselves.
Do you not know yourselves,
that Jesus Christ is in you?--unless indeed you are disqualified.`"^
footnote:[2 Corinthians 3:5]

=== The Work of Grace in Those Who Have Not Heard

[.numbered-group]
====

[.numbered]
II+++.+++ Secondly, that which remains now to be proved is,
that by the operation of this Light and Seed, some have been (and may yet be) saved,
to whom the Gospel is not outwardly preached, nor the history of Christ outwardly known.
To make this easier, we have already shown how Christ has died for all men,
and given unto all a measure of saving Light and Grace,
so that the Gospel is preached to them,
and in them (though not necessarily in any outward way),
leaving all men in a possibility of salvation.

====

In addition to those arguments which have already been
used to prove that all men have a measure of saving grace,
I shall now add another: namely, that excellent saying of the apostle Paul to Titus,
"`For the grace of God that brings salvation has appeared to all men, teaching us that,
denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in the present age.`"^
footnote:[Titus 2:11]
Nothing could be more clear than this statement,
for it comprehends both parts of the controversy.
First, it plainly asserts this to be no natural principle or light, but rather,
"`the grace of God that brings salvation.`"
Secondly, it says that this has appeared not to a few, but rather to all men.
Moreover, the fruit of this grace declares just how powerful it is,
seeing that it comprehends the whole duty of man.
It teaches us first to forsake evil, to deny ungodliness and worldly lusts;
and then it teaches our duty in all things: First, to live soberly,
which comprehends temperance, chastity, meekness,
and the things that relate to one`'s self.
Secondly, to live righteously, which comprehends equity, justice, and honesty,
and those things which relate to our neighbors.
And lastly, to live godly, which comprehends piety, faithfulness, and devotion,
which are the duties relating to God.
So then there is nothing required of man, or needful to man,
which this grace does not teach.

Though this might suffice, yet to put it further beyond all question,
I shall instance another saying of the same apostle: "`Therefore,
as through one man`'s offense judgment came to all men, resulting in condemnation,
even so through one Man`'s righteous act the free gift came to all men,
resulting in justification of life.`"^
footnote:[Romans 5:18]
From this it can be plainly seen that,
even as all men have received a loss from Adam which leads to condemnation,
so too all men have received a gift from Christ, which leads to justification.
And if this gift of Christ be received and obeyed, then all men,
even those who lack the outward knowledge of Christ, may be saved;^
footnote:[Editor`'s Note: To this,
the following Scripture might be added as further proof:
"`Judas (not Iscariot) said to Him, '`Lord,
how is it that You will manifest Yourself to us, and not to the world?`'
Jesus answered and said to him, '`If anyone loves Me,
he will keep My word +++[+++i.e. the implanted Word, Grace, Light+++]+++;
and My Father will love him,
and We will come to him and make Our home with him.`'`" (John 14:22-23)]
for Christ was given as a "`Light to enlighten the Gentiles,
that You should be My salvation to the ends of the earth.`"^
footnote:[Isaiah 49:6, See also Isaiah 42:6,60:3; Luke 2:32; Acts 13:47]

[.discourse-part]
Objection: The most common objection to this doctrine is taken from the words of Peter,
"`There is no other name under heaven given among men by which we must be saved.`"
Thus the heathen, not knowing this name, cannot be saved.

[.discourse-part]
Answer: Though they do not know His name outwardly,
yet they may know the name Jesus (which signifies Savior) inwardly,
by feeling the virtue and power of it to free them from sin and iniquity in their hearts.
I confess there is no other name by which any can be saved;
but salvation lies not in a literal and outward knowledge,
but in an experiential knowledge.
Those that have the literal knowledge are not saved by it without a real,
experiential knowing of Jesus.
Yet those that have the real, inward knowledge may be saved without the external name,
as the arguments hereafter will more fully show.
For if the outward knowledge of Christ were necessary
before men could receive any benefit from Him,
then (by the rule of contraries) it would follow that men could
receive no hurt except by the outward knowledge of Adam`'s fall.
But experience proves otherwise;
for how many millions have been injured by Adam`'s fall that
know nothing of there ever being such a man in the world,
or of his eating the forbidden fruit?
Why then may not some be saved by the gift and grace of Christ in them,
making them righteous and holy,
though they know not distinctly how that gift was purchased for them by the
death and sufferings of Jesus who was crucified at Jerusalem--especially in
cases where God Himself has made the outward knowledge impossible to them?
Many are killed by poison infused into their food,
though they know neither what the poison was, nor who infused it.
Likewise, many are cured of their diseases by good remedies,
though they know not how the medicine is prepared, what the ingredients are,
nor oftentimes who made it.
The like may also hold in spiritual things, as we shall hereafter show.

Now,
even our adversaries readily confess that many infants and mentally
disabled persons are saved without the outward knowledge of Christ.
Here they break their general rule,
and cannot allege that it is because such are free from sin,
seeing they also affirm that all infants, because of Adam`'s sin,
deserve eternal condemnation, as being really guilty in the sight of God.
And with mentally disabled people,
experience shows us that they are subject to many common iniquities as well as other men.

[.discourse-part]
Objection: If it be said, that these children are the children of believing parents:

[.discourse-part]
Answer: What then?
None of them dare say that parents transmit grace to their children.
And do they not all affirm that the children of
believing parents are guilty of original sin,
and deserve death as well as others?

[.discourse-part]
Objection:
And if they should further allege that these children
are within the bosom of the visible church,
and are partakers of the sacraments:

[.discourse-part]
Answer: All of this gives no certainty of salvation;
for (as all Protestants confess) these sacraments do not
confer grace independently of the faith of the recipient.
And will they not also acknowledge that there are many
others in the bosom of the visible church,
who are clearly no members of it?

But if our opposers are willing to extend this charity
towards infants and mentally disabled persons,
so that these are judged capable of salvation because they are
under a simple impossibility of knowing the means of salvation,
what reason can be alleged why the like charity should
not be extended to such as __are__ capable of knowing,
yet have never heard the outward and historical gospel?
Is not a man in China, or in India,
as much to be excused for not knowing a thing which he never heard of,
as the disabled person who cannot hear, or the infant who cannot understand?

But the truth of our doctrine manifestly appears by that saying of Peter in Acts,
"`Of a truth I perceive that God is no respecter of persons.
But in every nation, he that fears Him and works righteousness, is accepted of Him.`"^
footnote:[Acts 10:34-35]
Peter was before liable to that mistake which the rest of the
Jews were in--judging that all were unclean except themselves,
and that no man could be saved,
except as they were converted to their religion and circumcised.
But God showed Peter otherwise in a vision,
teaching him to call nothing common or unclean which God had cleansed.
And therefore, seeing that God had regarded the prayers of Cornelius,
who was a stranger to the outward law, and to Jesus Christ,
Peter found that God had accepted him.
And as Cornelius is said to have feared God before he had this outward knowledge,
therefore Peter concludes that everyone, in every nation, without respect of persons,
who fears God and by Him works righteousness, is accepted of Him.
Now we have already proved that to every man a measure of
grace is given whereby he may live godly and righteously.
Thus we see that by this grace Cornelius did so, and was accepted,
and that his prayers came up for a memorial before God,
even before he had this outward knowledge.

Also, was not Job "`a perfect and upright man, that feared God,
and shunned evil?`"^
footnote:[Job 1:1]
Who taught Job these things?
How did he know of Adam`'s fall?^
footnote:[Job 31:33]
And from what Scripture did he gain that excellent knowledge
and faith by which he knew that his Redeemer lived?
Most believe him to have lived before Moses,
so must it not have been an inward grace in the
heart that taught Job to shun evil and fear God?
Notice how he reproved the wickedness of men (chapter
24). And after he recounted their wickedness,
does he not condemn them for "`rebelling against
the Light,`" and for "`not knowing its way,
or abiding in the paths?`"^
footnote:[Job 24:13]
It appears then that Job believed men had a Light,
and that because they rebelled against it, they therefore knew not its ways,
nor abode in its paths.
And also Job`'s friends, though in some things they erred,
yet who taught them all the excellent sayings and knowledge which they had?
Did not God give it to them in order to save them?
Who taught Elihu that "`There is a spirit in man,
and the breath of the Almighty gives him understanding.`"^
footnote:[Job 32:8]
Or that, "`The Spirit of God has made me, and the breath of the Almighty gives me life?`"^
footnote:[Job 33:4]
And did not the Lord at last accept a sacrifice for them?^
footnote:[Job 42:8]
Who dares then say that they are damned?

But the apostle puts this controversy out of doubt, for,
if we may believe his plain assertion,
he tells us that some Gentiles indeed "`did the things contained in the law.`"^
footnote:[Romans 2:14]
From all of which I argue as follows:

[.syllogism]
* In every nation, he that fears God and works righteousness is accepted.
* But some of the heathen did fear God, and wrought righteousness by Him.
* Therefore they were accepted.

Can there be anything more clear?
And this appears even more plain by another verse,
taken out of the same chapter (v. 13). The words are,
"`The doers of the Law shall be justified.`"
From which I thus argue, from plain Scripture:

[.syllogism]
* The doers of the Law shall be justified.
* But some of the Gentiles did the things contained in the Law, showing that the work of the Law was written in their hearts.footnote:[Romans 2:15]
* Therefore these were justified.

Paul, through that whole chapter,
labors as if he were contending now with our adversaries,
in order to confirm this doctrine.
He says, "`Tribulation and anguish on every soul of man who does evil,
of the Jew first and also of the Gentile; but glory, honor,
and peace to everyone who works what is good, to the Jew first and also to the Greek.
For there is no partiality with God.`"^
footnote:[Romans 2:9-11]
Here the apostle clearly approves Peter`'s words to Cornelius (before mentioned),
showing that both they that have an outward law and they that have none,
when they do good^
footnote:[Editor`'s Note:
By "`doing good`" Barclay does not refer to the so-called good works of fallen man,
but to the good which results from receiving and
yielding to the inward manifestations of the Grace,
Light,
or Seed of God (as previously explained) by which the soul is
brought out of sin and corruption and made a new creation.]
shall be justified.
So then, unless we think Paul did not mean what he clearly spoke,
we may safely conclude that such Gentiles as these were justified,
and did partake of that "`honor, glory, and peace,
which comes upon every one that does good.`"^
footnote:[Romans 2:10]
And so we see that,
even as the presence of the outward knowledge of Christ cannot save without the inward,
neither can the lack of outward knowledge condemn those who have the inward.
And in these scriptures it appears that many who have lacked the outward,
have indeed come to a knowledge of the gospel inwardly,
by virtue of the work of that Grace and Light given to every man.
By the operation of this grace, received and heeded,
these Gentiles forsook iniquity and grew in true
righteousness and holiness (as was proved above).
Though they knew not the history of Adam`'s fall,
yet they were sensible in themselves of the loss that came by it,
feeling their inclination to sin, and the power of the "`body of sin`"^
footnote:[Romans 6:6]
working in them.
And likewise, though they knew not the outward coming of Christ,
yet they were sensible of that inward power and salvation which came by Him,
both before and since His appearance in the flesh.

Lastly,
I question whether those who insist upon the outward knowledge of
Christ for salvation can prove that all the patriarchs and fathers
before Moses had any distinct knowledge either of Adam or Christ.
For seeing how Moses most certainly wrote of Adam by revelation,
it is doubtful whether the patriarchs before him knew anything
of the history of the tree of the knowledge of good and evil,
or of Adam`'s eating the forbidden fruit; and far less of the Christ,
that He should be born of a virgin, crucified, raised, etc.

=== A Few Examples Among Ancient Writers

Thus we see that it is the inward work,
and not the outward history and Scripture, that gives true knowledge,
and by this inward Light many of the Gentile
philosophers were sensible of the loss received by Adam,
though they did not know the outward history.
Hence Plato asserted that, "`Man`'s soul was fallen into a dark cave,
where it only conversed with shadows.`"
Pythagoras says, "`Man wanders in this world as a stranger,
banished from the presence of God.`"
And Plotinus compares "`man`'s soul, fallen from God, to a cinder, or dead coal,
from which the fire is extinguished.`"
Some of them said that "`the wings of the soul were clipped or fallen off,
so that they could not flee unto God.`"
These,
and many more expressions might be gathered out of their writings to
show that they were not without a sense of their loss,
and the great fall of man from the presence of God.

These also had a knowledge and discovery of Jesus Christ inwardly,
as a remedy in them, to deliver them from that evil seed,
and the evil inclinations of their own hearts, though not using these specific names.
Some called Him a Holy Spirit, as Seneca, who said,
"`There is a Holy Spirit in us that treats us as we treat Him.`"^
footnote:[Epist. 41]
Cicero calls it an "`innate light, constant and eternal, calling unto duty by commanding,
and deterring from deceit by forbidding.`"^
footnote:[De Republica, cited by Lactantius (6 Instit.)]
He further adds that this light "`cannot be abrogated, nor can any be freed from it,
neither by senate nor people; for it is one, eternal, and the same always to all nations,
so that there is not one at Rome and another at Athens.
Whosoever does not obey it must seek to flee from himself,
and in this he is greatly tormented, though he should escape all other punishment.`"
Plotinus also calls Him Light,
saying that "`as the sun cannot be known but by its own light,
so God cannot be known but by His own Light.
And as the eye cannot see the sun but by receiving its image,
neither can man know God but by receiving His image.
Thus it behooves man to come to purity of heart before he can know God.`"
He elsewhere calls Him "`Wisdom,`" a name frequently
given Him in Scripture--see Prov. 1:20 to the end;
and Prov. 8:9-34, where Wisdom is said to cry, entreat,
and invite all to come unto her and learn of her.
And what is this Wisdom but Christ?
Accordingly,
those among the heathen who came to forsake evil and cleave to
righteousness were called "`philosophers,`" that is,
lovers of wisdom.
They knew this wisdom was near to them,
and that "`the best knowledge of God and divine mysteries came
by the inspiration of the wisdom of God.`"

Much more of this kind might be instanced,
by which it appears that some of these men knew Christ,
and by His working in them were brought from unrighteousness to righteousness,
and to love that power by which they felt themselves redeemed.
Thus, as the apostle says,
"`These showed the work of the law written in their hearts,`"
and "`did the things contained in the law,`" and so were no
doubt justified and saved by the power of Christ in them.
And as this was the judgment of the apostle,
so it was also the belief of the primitive Christians.
Hence Justin Martyr did not hesitate to call Socrates a Christian,
saying that "`all such as lived according to the divine Word in them,
which was in all men, were Christians, such as Socrates and Heraclitus,
and others among the Greeks.`"

Augustine says,
"`I do not think that the Jews dare affirm that
none belonged to God but the Israelites.`"^
footnote:[City of God, lib. 18, cap. 47]
And referring to these words, Ludovicus Vives says, "`Thus the Gentiles,
not having a law, were a law unto themselves;
and the light of so living is the gift of God, and proceeds from the Son,
of whom it is written that He enlightens every man that comes into the world.`"

=== Conclusion

Seeing then it is by this inward Gift, Grace, and Light,
that both those who have the Gospel preached to
them come to have Jesus brought forth in them,
and to have the saving and sanctified use of all
outward helps and advantages (i.e. Scriptures,
teaching, etc.); and also, by this same Light, that God calls, invites,
and strives with all, in a day of visitation,
desiring the salvation of even those to whom He
has withheld the outward knowledge of the gospel;
we therefore,
having experienced the inward and powerful work of this Light
in our hearts--even Jesus Christ revealed in us--cannot cease
to proclaim the Day of the Lord that has arisen within us,
crying out with the woman of Samaria;
"`Come and see One that has told me all that ever I have done!
Is not this the Christ?`"
This we do that others may come and experience the same thing in themselves,
and may know that the little thing which reproves them in their
hearts (however much they may have despised and neglected it),
is nothing less than the Gospel preached in them--"`Christ,
the wisdom and power of God,`" being in and by His Seed seeking to save their souls.

Of this Light therefore Augustine speaks in his Confessions: "`In the beginning,
O God, You made the heavens and the earth, in Your Word, in Your Son, in Your virtue,
in Your wisdom, wonderfully saying, and wonderfully doing.
Who shall comprehend it?
Who shall declare it?
What is that which shines in unto me, and smites my heart without hurt,
at which I both tremble, and am inflamed?
I tremble, in so far as I am unlike unto it;
and I am inflamed in so far as I am made like unto it?
It is Wisdom, which shines in unto me and dispels my cloud, which had again covered me,
after I was departed from that darkness and heap of my punishments.`"^
footnote:[lib. 11, cap. 9]
And again he says, "`It is too late that I have loved You, O Beauty so old and so new;
late have I loved You.
And behold You were within, and I was without, and there I was seeking You!
You did call, You did cry, You did break my deafness, You glanced, You did shine,
You chased away my darkness.`"^
footnote:[lib. x., cap. 27]

Of this our countryman, George Buchanan, also speaks as follows:
"`Truly I understand no other thing at present,
than that Light which is divinely infused into our souls.
For when God formed man, He not only gave him eyes for his body,
by which he might shun those things that are hurtful to him,
and follow those things that are profitable, but He has also set before his mind,
as it were, a certain Light,
by which he may discern things that are vile from things that are honest.
Some call this power nature, others the law of nature; I truly judge it to be divine,
and am persuaded that nature and wisdom never say different things.
Moreover, in this God has given us a summary of the law,
which in few words comprehends the whole, namely:
that we should love Him from our hearts, and our neighbors as ourselves.
And all the books of the Holy Scriptures which pertain to the forming of conduct,
contain no more than a further explanation of this one law.`"^
footnote:[De Jure Regni apud Scotos]

This is that universal, evangelical Light, Grace,
or Word in and by which the salvation of Christ is exhibited to all men,
both Jew and Gentile, Scythian and Barbarian, of whatsoever country or kindred he may be.
And therefore God has raised up unto Himself, in this our age,
faithful witnesses and evangelists to preach again His everlasting Gospel,
and to direct all--from the lofty professors of Christianity,
who boast of the Law and the Scriptures and their outward knowledge of Christ,
to the infidels and heathens that know Him not that way--that
they may all come to mind the Light in them,
and know Christ in them, whom James calls "`the Just One +++[+++__ton Dikaion__],
whom they have so long killed;`"^
footnote:[James 5:6]
that these may give up their sins, iniquities, false faith, professions,
and outward righteousness, to be crucified by the power of His cross in them,
and so know Christ within to be the "`hope of glory,`"
and may come to walk in His Light and be saved,
who is that "`true Light which gives light to every man coming into the world.`"
