== Chapter V. Concerning Justification

The doctrine of justification comes next in order after discussing
the extent of Christ`'s death and the grace thereby communicated.
Many are the disputes among those called Christians concerning justification; but surely,
if all were truly minding that power which justifies,
there would be less noise about the various notions and opinions.
I shall briefly review the controversy as it stands among others,
and as I have often seriously observed it;
and then state the controversy as it relates to us, opening our sense and judgment of it.
Lastly, I will prove it (if the Lord permits) by some Scripture testimonies,
and the certain experience of all who ever were truly justified.

That the doctrine of justification has been
greatly corrupted by the church of Rome is not,
I suppose, denied by any Protestant Christian, for it manifestly appears,
and is openly taught among Catholics, that they obtain remission of sins,
and justification by the merits of Christ,
as these are applied to them in the use of the sacraments of the church,
and are dispensed in the performance of various ceremonies, pilgrimages, indulgences,
prayers, penances, and other performances,
even though there be no inward renewing of the mind,
or knowing of Christ inwardly formed;
so that their justification comes from something outside of them,
and not from Someone within them.
These are said to be forgiven and made righteous by virtue of the sacrament itself,
and by the authority of a priest who pronounces them absolved.
Truly, Luther had great reason to oppose them on this matter,
and if he had not run himself into another extreme (of which
we will speak hereafter) his work would have stood the better.
For in this, as in most other things,
he is more to be commended for what he pulled down of
Babylon than for what he built of his own.

The Protestants say that "`they obtain remission of sins,
and stand justified in the sight of God by virtue of the merits and sufferings of Christ,
not by any infusing of His righteousness into them, but by the pardoning of their sins,
and by accounting and accepting their persons as righteous;
not for anything wrought in them, or done by them,
but by imputing the obedience and satisfaction of Christ unto them by faith;
which faith they have not of themselves, it is the gift of God.`"^
footnote:[So says the Westminster Confession of Faith, chap. 11, sect. 1.]

So then,
we see that the justification of both Catholics and
Protestants is not placed in any inward renewing of the mind,
or by virtue of any spiritual birth or formation of Christ within them,
but only by a bare application of His death and sufferings outwardly performed for them.
The one lays hold of a faith given to them, and hopes to be justified by it alone;
the other expects to make the death of Christ effectual unto
them by the performance of some outward prayers and ceremonies.
I admit, however (being unwilling to wrong any),
that some better things have been said as to the necessity of inward holiness,
both by some modern Catholics and modern Protestants,
who have come near to the Truth (as will hereafter appear,
by some citations from their writings).

=== Our Position

As to our position on this matter: First,
we renounce the idea of there being any natural power or ability in
ourselves to bring us out of our lost and fallen condition and first nature;
and confess that, as of ourselves, we are able to do nothing that is good.
We further say that we are entirely unable to procure
remission of sins or justification by any act of our own so as
to merit it or draw it as a debt from God due unto us.
Instead, we acknowledge all to be of and from His love,
which is the origin and fundamental cause of our acceptance.

Secondly, God manifested this love towards us in the sending of His beloved Son,
the Lord Jesus Christ, into the world,
who gave Himself for us as an offering and a sacrifice to God,
for a sweet-smelling savor, making peace through the blood of His cross,
that He might reconcile us unto Himself.
This One, by the Eternal Spirit, offered Himself without spot unto God,
and suffered for our sins, the just for the unjust, that He might bring us unto God.

Thirdly then,
forasmuch as all men (who have come to a man`'s state) have sinned--
the Man Jesus only excepted--therefore all have need of this Savior,
to remove the wrath of God from them, due to their offenses.
In this respect,
He is truly said to have "`borne the iniquities of us all in His body on the tree,`"^
footnote:[1 Peter 2:24]
and is therefore the only Mediator, having qualified the wrath of God towards us,
so that our former sins stand not in our way, being,
by virtue of His most satisfactory sacrifice, removed and pardoned.
And indeed, remission of sins is not to be expected, sought,
or obtained in any other way, or by any works or sacrifice whatsoever (though,
as has been said formerly,
some may come to partake of this remission that are ignorant of the history).

So then Christ, by His death and sufferings, reconciles us to God,
even while we are enemies--that is, He offers reconciliation unto the world,
we are put into a capacity of being reconciled,
God is willing to forgive us our iniquities and to accept us,
as is well expressed by the apostle: "`God was in Christ,
reconciling the world unto Himself, not imputing their trespasses to them,
and has put in us the Word of reconciliation.`"^
footnote:[2 Corinthians 5:19 Literal Translation.
Editor`'s Note:
Most modern translations read "`has committed to
us the word or message of reconciliation.`"
But the Greek reads "`placing in us the word of reconciliation`" --
// lint-disable invalid-character
θέμενος ἐν ἡμῖν τὸν λόγον τῆς καταλλαγῆς]
And therefore the apostle, in the very next verses,
entreats them "`in Christ`'s stead to be reconciled to God;`" intimating,
that the wrath of God has been removed by the obedience of Christ Jesus,
and now God is willing to be reconciled unto them,
and is ready to remit the sins that are past, if they repent.

We therefore consider our redemption in a two-fold respect or state,
both of which in their own nature are perfect,
though in their application to us the one cannot be without respect to the other,
as will be seen.

The first then,
is the redemption performed and accomplished by
Christ __for us__ in His crucified body without us.
The other is the redemption wrought by Christ __within us__,
which is no less properly called and accounted a redemption than the former.
The first is that whereby man, as he stands in the fall,
is put into a capacity of salvation, and has conveyed unto him a measure of that power,
virtue, spirit, life, and grace that was in Christ Jesus--which, as the free gift of God,
is able to overcome and root out the evil seed
with which we are naturally leavened in the fall.
The second is that whereby we experience and know this
pure and perfect redemption in ourselves,
purifying, cleansing, and redeeming us from the power of corruption,
and bringing us into unity, favor, and friendship with God.^
footnote:[Editor`'s Note: See also Ephesians chapter 1, where Paul first writes (vs. 7),
"`In Him __we have redemption__ through His blood, the forgiveness of sins,
according to the riches of His grace;`" and then (vs. 14)
declares the Holy Spirit to be the "`guarantee of our
inheritance __until the redemption__ of the purchased possession.`"]

By the first of these two, we, who were lost in Adam,
plunged into the bitter and corrupt seed, unable, of ourselves to do any good thing,
but naturally joined and united to evil, forward and prone to all iniquity,
servants and slaves of the power and spirit of darkness, are, notwithstanding all this,
so far reconciled to God by the death of His Son, even while enemies,
that we are put into a capacity of salvation,
having the glad tidings of the Gospel of peace offered unto us,
that God is reconciled unto us in Christ, and so calls and invites us to Himself.
It is in this respect that we understand the following scriptures:
"`He put to death the enmity in Himself;`"^
footnote:[Ephesians 2:14-15]
"`He loved us first,`"^
footnote:[1 John 4:19]
"`Seeing us in our blood, He said unto us, Live;`"^
footnote:[Ezekiel 16:6]
"`He Himself bore our sins in His own body on the tree;`"^
footnote:[1 Peter 2:24]
and "`Christ also suffered once for sins, the just for the unjust;`"^
footnote:[1 Peter 3:18]
etc.

By the second, we experience this capacity brought into act,
whereby receiving and not resisting the purchase of His death (namely, the Light, Spirit,
and Grace of Christ revealed in us), we witness and possess a real,
true and inward redemption from the power and prevalence of sin,
and so come to be truly and really redeemed, justified, and made righteous,
and to an experiential union and friendship with God.
Thus He "`gave Himself for us,
that He might redeem us from all iniquity and
purify for Himself His own special people;`"^
footnote:[Titus 2:14]
and thus we "`know Him and the power of His resurrection,
and the fellowship of His sufferings, being conformed to His death.`"^
footnote:[Philippians 3:10]
This last follows the first in order, and is a consequence of it, proceeding from it,
as an effect proceeds from its cause.
So then,
even as none can enjoy the last without the first
having been established (such being the will of God);
so also none can truly partake of the first, except as he experiences the last.
Thus to us, they are both causes of our justification.

Now, by justification we do not understand merely the production of good works,
even those works wrought by the Spirit of Christ;
for these (as Protestants rightly affirm) are more an effect of justification,
than the cause of it.
Instead, we understanding this justification to be the formation of Christ in us,
Christ born and brought forth in us, from which good works naturally proceed,
even as fruit from a fruitful tree.
It is this inward birth in us, bringing forth righteousness and holiness in us,
that does justify us, which,
having removed and done away the contrary nature and
spirit that did bear rule and bring condemnation,
is now in dominion over all in our hearts.
Those then, that come to know Christ thus formed in them,
do enjoy Him wholly and undividedly, who is "`the Lord our righteousness.`"^
footnote:[Jeremiah 23:6]
This is what it means to be clothed with Christ, and to have put Him on,
and such as these God truly accounts to be righteous and just.

This is far from the doctrine of Catholics,
for the formal cause of justification is not the works (they being but an effect of it),
but rather an inward birth, Jesus Christ brought forth in the heart,
who is the well-beloved, whom the Father cannot but accept,
together with all those who are thus sprinkled
with the blood of Jesus and truly washed with it.
And by this (i.e. Christ inwardly put on) also comes
the communication of the goods of Christ unto us,
"`by which we come to be made partakers of the divine nature,`"^
footnote:[2 Peter 1:4]
as Peter says, and are made one with Him, as the branches with the vine,
and so have a title and right to what He has done and suffered for us.
In this way His obedience becomes ours, His righteousness ours,
His death and sufferings ours.
And by this nearness we often come to have a sense of His sufferings,
and do suffer with His Seed that yet lies pressed and
crucified in the hearts of the ungodly.
So we travail with it, and for its redemption,
and for the repentance of those souls that are yet
crucifying the Lord of Glory--even as the apostle Paul,
who by his sufferings is said to "`fill up that which
is behind of the afflictions of Christ for His body,
which is the church,`"^
footnote:[Colossians 1:24]
though this be a mystery sealed up from all the wise
men that are yet ignorant of this Seed in themselves,
and oppose it.

Finally,
though we place remission of sins in the righteousness and obedience
of Christ performed by Him in the flesh (as the procuring cause),
and we hold ourselves truly justified by Christ Jesus formed and brought forth in us;
yet we cannot (as some Protestants have unwarily done) exclude works from justification.
For though, to speak properly, we are not justified __by__ them,
yet are we justified __in__ them, and so they are necessary.
The denying of this is not only contrary to Scripture`'s testimony,
but has brought a great scandal to the Protestant religion,
opened the mouths of accusers,
and made many to feel falsely secure in a justification without good works.
Moreover, though it is not safe to say good works are meritorious,
yet the Scriptures plainly show that they are rewarded,
so that many of those called Church Fathers have not been afraid to use the
word "`merit`" in a qualified sense (though not as the Catholics do).
However, not only do most Protestants deny them to be necessary,
but they are sometimes not ashamed to call them hurtful,
often saying that the best works, even of the saints, are defiled and polluted.
Now, though we judge this to be true of the best works performed __by man__,
endeavoring a conformity to the outward law by his own strength, and in his own will,
yet we believe that such works as naturally proceed from this spiritual birth,
and from the formation of Christ in us, are pure and holy,
even as the root from which they come is pure.
For this reason God accepts them, justifies us in them, and rewards us for them,
of His own free grace.

=== The Proof of Our Position

The state of the controversy being thus described,
these following positions must now be proved:

[.numbered]
__First:__ that the obedience, sufferings,
and death of Christ is that by which the soul obtains remission of sins,
and is the procuring cause of that grace by whose
inward workings Christ comes to be formed inwardly,
and the soul made conformable to Him, and so made just and justified.
And therefore,
it is with respect to this capacity and the offer of
grace that God is said to be "`reconciled`" to us--
though not in the sense that He is actually united to,
or does actually account anyone just or justified, while they remain in their sins,
continuing impure and unjust.

[.numbered]
__Secondly:__ that it is by this inward birth of Christ in man that we are made just,
and therefore so accounted by God.
So then, to speak plainly,
it is not till Christ be brought forth in us
that we are truly justified in the sight of God;
for the term justification is used, both more properly and more frequently in Scripture,
according to its proper meaning,
which is "`to make one just,`" and not merely to repute one so.

[.numbered]
__Thirdly:__ that since good works naturally flow from this birth (as heat from a fire),
they are therefore an absolute necessity to justification--not as the cause thereof,
but as that in which we are justified, and without which we cannot be justified.
And though these good works are not meritorious, nor draw any debt upon God,
yet He cannot but accept and reward them,
for it is contrary to His nature to deny His own,
especially since these may be perfect in their kind,
as proceeding from a pure and holy birth and root.
It is therefore false and contrary to the Truth to suggest that the holiest
works of the saints are defiled and sinful in the sight of God;
for the good works which flow from the spiritual birth are not the
works of the law which the apostle excluded from justification.

As to the first position, I first prove it from Romans 3:25:
"`Whom God has set forth to be a propitiation through faith in His blood,
to declare His righteousness for the remission of sins that are past,
through the forbearance of God.`"
Here the apostle holds forth the extent and efficacy of Christ`'s death,
showing that by it, and by faith in it, remission of sins that are past is obtained;
and that in this the forbearance of God is exercised towards mankind.
So that though men, for the sins they daily commit, deserve eternal death, yet,
by virtue of that most satisfactory sacrifice of Christ Jesus,
the grace and seed of God moves in love towards them during
the day of their visitation to redeem man out of evil.

Secondly, if God were perfectly reconciled with men,
and did esteem them just while they are actually unjust and continue in their sins,
then He would have no controversy with them.
But why is it then, throughout the whole of Scripture,
that He so often complains and reasons with
those who our opponents claim to be justified,
telling them "`that their iniquities have made a
separation between them and their God.`"^
footnote:[Isaiah 59:2]
For where there is a perfect and full reconciliation there is no separation.
But to suggest that men may be fully reconciled to God even while they continue in
their sins necessarily implies that sin makes not the least separation from God,
and that man is justified __in his sins__.
And from this would follow the most abominable consequence,
that good works and great sins are alike in the sight of God,
seeing that neither one serves to justify,
nor to break reconciliation with God--which doctrine
opens a door to false security and every lewd practice.

Thirdly, this would make void the whole practical doctrine of the Gospel,
and make entirely unnecessary such things as faith, repentance, obedience,
and the other conditions which are required to be performed^
footnote:[Editor`'s Note:
These are performed in the grace that flows to us in the covenant,
as is previously mentioned.]
on our part.
And certainly,
these conditions are of a nature that they cannot be performed at one time only,
but are to be done all of one`'s lifetime.
But if we are already perfectly reconciled and
justified before these conditions are performed,
then they cannot be said to be needful,
which is contrary to the express testimony of Scripture acknowledged by all Christians.
For we read: "`Without faith it is impossible to please God.`"^
footnote:[Hebrews 11:6]
And, "`For if you live according to the flesh you will die;
but if by the Spirit you put to death the deeds of the body, you will live.`"^
footnote:[Romans 8:13]
And to those who were converted, the Lord said,
"`I will remove your candlestick from you, unless you repent,`"^
footnote:[Revelation 2:5]
and Paul exclaimed, "`You ran well.
Who has hindered you from obeying the truth?`"^
footnote:[Galatians 5:7]
Were I to mention all the Scriptures that positively and evidently prove this,
I might transcribe much of all the doctrinal part of the Bible.
For Christ said "`It is finished,`"^
footnote:[John 19:30]
and indeed did finish His work more than sixteen hundred years ago,
offering His body a sacrifice for sin, opening a door of mercy to all,
and communicating a measure of His grace by which all may see their sins,
be able to repent, and thus experience redemption, reconciliation,
and justification inwardly wrought by Him now.
But if in saying "`It is finished,`" He is understood
to have so perfected and finished the redemption of man,
and fully reconciled all that will be saved (either before they believe, as some say,
or after they confess to the truth of the history of Christ, or are sprinkled with water,
etc.), even though they continue in their sins,
then the whole doctrinal part of the Bible is useless and of no profit.
In vain were the apostles sent forth to preach the gospel;
in vain does Scripture warn us not to drift away, nor nullify the grace of God,
nor lose our first love,
nor allow our hearts to be hardened and so come short of our rest, etc.,
and in vain do all Christian preachers bestow their labor, spend their lungs,
and give forth writings, only to do that which is already perfectly done without them.

But lastly,
this doctrine also makes void the present intercession of Christ for men.
For what shall become of that great article of faith by which we affirm,
"`That He sits at the right hand of God daily making intercession for us?`"^
footnote:[Romans 8:34]
And for what end does "`the Spirit Himself make intercession
for us with groanings which cannot be uttered?`"^
footnote:[Romans 8:26-27]
For to make intercession for those who are not in a possibility of salvation is absurd.
And to pray for those that are already reconciled, and perfectly justified,
is to no purpose.
Truly, I see no real solving of this, except by acknowledging the truth of the matter,
namely: that Christ by His death removed the wrath of God,
so far as to obtain remission of sins for as many as receive
the Grace and Light that He communicates unto them,
and has purchased for them by His blood.
As they believe in this, they come to know remission of sins past,
and power to save them from the dominion of sin, for "`to as many as receive Him,
He gives power to become the sons of God.`"^
footnote:[John 1:12 KJV]
These also know His power to wipe away any present sin
into which they may fall by unwatchfulness or weakness,
if, applying themselves to this grace, they truly repent.
So then, none are sons, none are justified, none are reconciled,
until they receive Christ in that little Seed in their hearts;
and thus life eternal is offered to those, "`who by patient continuance in well-doing,
seek for glory, honor, and immortality.`"^
footnote:[Romans 2:7]
For, according to the prophet, "`If the righteous man turns away from his righteousness,
his righteousness shall be remembered no more.`"^
footnote:[Ezekiel 18:24]
Accordingly, none remain sons of God, nor are justified in the sight of God,
unless they patiently continue in righteousness and well-doing.
And therefore Christ lives always to make intercession
during the day of every man`'s visitation,
that they may be converted.
And when they are in some measure grown up in the life,
He makes intercession that they may continue, and go on, and not faint,
nor go back again.
Much more might be said to confirm this truth;
but I go on to take notice of the common objections against it.

=== Objections and Responses

[.discourse-part]
Objection:
The first and chief objection is drawn from that
saying of the apostle (before mentioned):
"`God has reconciled us to himself by Jesus Christ:
God was in Christ reconciling the world unto himself,
not imputing their trespasses unto them.`"^
footnote:[2 Corinthians 5:18-19]
From here it is inferred that Christ fully perfected
the work of reconciliation while He was on earth.

[.discourse-part]
Answer: If by "`reconciliation`" is understood the removing of wrath,
and the purchase of that Grace by which we may
come to be fully reconciled and united to God,
then we agree to it.
But that this verse speaks of no more than this appears from the verse itself;
for when the apostle speaks in the perfect tense, saying,
"`He has reconciled us,`" he speaks of himself and the saints, who,
having received the Grace of God purchased by Christ,
were through faith in Him actually reconciled.
But with regard to others,
he speaks of the "`Word of reconciliation`" which was "`put in them;`"^
footnote:[2 Corinthians 5:19 Literal Translation.
Editor`'s Note:
Most modern translations read "`has committed to
us the word or message of reconciliation.`"
But the Greek reads "`placing in us the word of reconciliation`" --
// lint-disable invalid-character
θέμενος ἐν ἡμῖν τὸν λόγον τῆς καταλλαγῆς]
and in the following verse says, "`Now then, we are ambassadors for Christ,
as though God were pleading through us: we implore you on Christ`'s behalf,
be reconciled to God.`"^
footnote:[2 Corinthians 5:20]
Now if their reconciliation had already been perfectly accomplished,
what need would there be for any entreating them to be reconciled?
Ambassadors are not sent after peace is already perfected and reconciliation made,
but to entreat for reconciliation.

[.discourse-part]
Objection: Secondly, they object (from v. 21 of the same chapter),
"`For He made Him who knew no sin to be sin for us,
that we might become the righteousness of God in Him.`"
From this they argue, that as our sin is imputed to Christ, who had no sin;
so Christ`'s righteousness is imputed to us, without our actually being righteous.

[.discourse-part]
Answer: But this interpretation is easily rejected; for the apostle himself,
in multiple instances, demonstrates that we are to be made __really__ righteous by Christ,
and not merely imputed or considered righteous.
Indeed, this appears by what follows in verses 14-16 of the following chapter,
where he argues largely against any supposed agreement between light and darkness,
or righteousness and unrighteousness.
But if men are to be reckoned engrafted in Christ, and real members of Him,
merely by an external imputative righteousness,
while they themselves continue in unrighteousness,
would this not imply a fellowship between righteousness and unrighteousness?
And truly,
it should be considered strange how many have made this "`imputed
righteousness`" so fundamental an article of their faith,
though it is so contrary to the whole strain of the Gospel.
For Christ did not, in any of His sermons and gracious speeches,
ever desire His hearers to rely upon such a thing,
but instead always pointed them to true sanctification,
to the cleaning of the inside and outside of the cup,
and to good works that glorify the Father, saying, "`You shall be perfect,
just as your Father in heaven is perfect.`"^
footnote:[Matthew 5:48]

=== True Justification--Christ Formed Within

I come then to the second thing proposed by me, which is,
that it is by this inward birth, or Christ formed within,
that we are formally (so to speak) justified in the sight of God.
I suppose I have said enough already to demonstrate how much
we acknowledge the death and sufferings of Christ as that
offering by which satisfaction is made to the justice of God,
remission of sins is obtained, and the Grace and Seed are purchased,
from which this birth proceeds.
The thing which remains to be proved is,
that by Christ Jesus formed in us we are justified, or __truly made just__.
Let it be noted that I here use the term "`justification`" in this sense.

First then, I prove this by that Scripture of the apostle Paul,
1 Corinthians 6:11: "`And such were some of you.
But you were washed, but you were sanctified,
but you were justified in the name of the Lord Jesus and by the Spirit of our God.`"
The word "`justified`" here must necessarily signify a being made really just,
and not being merely imputed such;
or else "`sanctified`" and "`washed`" might also be considered a mere imputation,
which overturns the whole intent of the context.
For in the preceding verses,
the apostle warns his readers "`not to be deceived,`" for "`the unrighteous cannot
inherit the kingdom of God;`" and after specifying several sorts of wickedness,
concludes by saying "`such were some of you`" but you are so no longer.
Thus having been washed and sanctified, so they were truly justified.
For my part, I neither see anything, nor have ever heard or read anything,
that could suggest the word "`justified`" in this place to be understood in
any other way than in its own proper and genuine meaning of __being made just__.

Now this word "`justify,`" which is derived from the noun "`justice,`" or
the adjective "`just,`" does beyond all question signify a making just,
for it is nothing other than a composition of the verb __facio__, and the adjective __justus__,
which is __justifico__, or __I make just__.
Likewise, the word justified is from __justus__ and __fio__, meaning __I become just__.
So it is with other verbs of this kind,
like __santifico__ which is from __sanctus__ (holy) and __facio__, meaning __I make holy__.
In each case it is understood that the subject is really and truly
endued with that virtue and quality from which the verb is derived.
For as none are said to be sanctified who are not really holy;
so neither can any truly be said to be justified, while they actually remain unjust.

However, this verb "`justify`" has, in a metaphorical and figurative way,
been used in a legal sense,
as when a man really guilty of a crime is freed from the punishment of his sin,
he is said to be justified, that is, put in the place as if he were just.
But is it not strange that men should be so superficial in a matter
of so great importance as to build the stress of their acceptance
with God upon a mere borrowed and metaphorical meaning of this word,
to the excluding (or at least esteeming unnecessary)
that holiness without which Scripture expressly says,
"`No man shall ever see God?`"^
footnote:[Hebrews 12:14]
Indeed,
would it not be a great mistake to content ourselves with an
imaginary justification while God requires a real one?
And let it be considered that in all the letters to the Romans, Corinthians, Galatians,
and elsewhere, where the apostle handles this theme,
the word may be taken in its own proper signification without any absurdity.
For instance, in his epistles to the Romans and Galatians,
Paul asserts that "`a man cannot be justified by the law of Moses,
nor by the works of the law.`"^
footnote:[Romans 3:28; Galatians 2:16-3:11]
There is no absurdity or danger in understanding
it here according to its own proper meaning,
namely, that a man cannot be made just by the law of Moses,
especially seeing how this so well agrees with that saying of the same apostle,
That "`the law makes nothing perfect.`"^
footnote:[Hebrews 7:19]
Also where it is said, "`We are justified by faith,`"^
footnote:[Romans 3:28; Galatians 3:24]
it may be very well understood of being made just,
seeing it is also said that "`faith purifies the heart;`"^
footnote:[Acts 15:9]
and no doubt the pure in heart are just, and "`the just live by faith.`"^
footnote:[Habakkuk 2:4; Romans 1:17; Galatians 3:11; Hebrews 10:38]
Again, where it is said, "`We are justified by grace,`"^
footnote:[Romans 3:24; Titus 3:7]
or "`We are justified by Christ,`"^
footnote:[Galatians 2:17]
or "`We are justified by the Spirit;`"^
footnote:[1 Corinthians 6:11]
it is in no way absurd to understand it as being made just,
seeing that by His Spirit and grace He does indeed make men just.
But to understand it universally the other way, as a mere legal acceptance,
would infer great absurdities, as might be proved at large,
but because I judged it would be acknowledged, I forbear at present, for brevity`'s sake.

But further,
in the most weighty places where this word "`justify`" is used in Scripture,
our adversaries must acknowledge it to be understood as making just,
and not as a bare legal acceptance.
This we have seen in 1 Corinthians 6:11, "`But you were washed,
but you were sanctified, but you were justified.`"
But also in Titus 3:5-7--"`According to His mercy He saved us,
through the washing of regeneration and renewing of the Holy Spirit,
whom He poured out on us abundantly through Jesus Christ our
Savior, that having been justified by His grace we should
become heirs according to the hope of eternal life.`"
And also in that excellent saying of the apostle (Romans 8:30), "`Whom He called,
these He also justified; and whom He justified, these He also glorified.`"
This is commonly called the "`golden chain,`" and is acknowledged by
all to comprehend the method and order of salvation.
But if "`justified`" were not here understood in its proper
signification--of actually being made just--then a true change from
wickedness to holiness would be wholly excluded from this chain.
But surely (as most do acknowledge), the apostle, in this abbreviated account,
uses the word "`justified`" to comprehend all that comes between calling and glorifying,
insinuating that being made really righteous is the
means by which we pass from calling to glorification.

Indeed many Church Fathers and famous Protestants do acknowledge the same:
"`I take,`" says Beza, "`the name of justification generally,
as comprehending whatsoever we acquire from Christ, whether by imputation,
or by the efficacy of the Spirit in sanctifying us.
So likewise should the word justification be taken in Romans 8:30.`"^
footnote:[In cap. 3. ad Tit. ver. 7.]
Melanchthon says, "`That to be justified by faith,
signifies in Scripture not only to be pronounced just, but also,
from unrighteous to be made righteous.`"^
footnote:[In Apol. Confess. Aug.]
Also, some chief Protestants, though not so clearly, have hinted at our doctrine,
whereby we ascribe unto the death of Christ remission of sins,
and the work of justification unto the grace of the Spirit acquired by His death.
Martin Borrhaus, explaining Romans 4:25 where it says, "`Who was given for our sins,
and rose again for our justification,`" says:
"`There are two things here beheld in Christ,
which are necessary to our justification;--the one is His death;
the other is His arising from the dead.
By His death, the sins of this world were expiated.
By His rising from the dead, it pleased the same goodness of God to give the Holy Spirit,
whereby both the Gospel is believed,
and the righteousness which was lost by the fault of the first Adam, is restored.`"^
footnote:[In Gen. cap. 15. ad verb. Cred dit Abraham Deo+++.+++, p. 161.]
And afterwards he says, "`The apostle expresses both parts in these words,
'`Who was given for our sins, and rose again for our justification.`'
In His death is beheld the satisfaction for sin;
in His resurrection is beheld the gift of the Holy Spirit,
by which our justification is perfected.`"^
footnote:[lib. 3. Reg. cap. 9. ver. 4., p. 681.]
And William Forbes, bishop of Edinburgh, says,
"`Whensoever the Scripture makes mention of the justification before God,
it appears that the word justify necessarily signifies not only to pronounce just,
in a legal sense, but also really and inherently to make just;
for God justifies differently than earthly judges.
Indeed, both the Scriptures and the Fathers do affirm,
that in the justification of a sinner, their sins are not only remitted, forgiven,
covered, and not imputed, but also taken away, blotted out, cleansed, washed, purged,
and very far removed from us, as appears from many places of the holy Scriptures.`"^
footnote:[In considerat. modest. de Just. lib. 2. Sect. 8.]

=== The Revelation of Jesus Christ in the Soul

Having then sufficiently shown that by "`justification`" we
should understand a really being made righteous,
I now do boldly affirm (not only from a notional knowledge, but from a real, inward,
experiential feeling of the thing), that the immediate, nearest,
or formal cause of a man`'s justification in the sight of God,
is the revelation of Jesus Christ in the soul, changing, altering, and renewing the mind.
It is by Him (the Author of this inward work), thus revealed and formed within,
that we are truly justified and accepted in the sight of God.
For it is as we are covered and clothed with Him
in whom the Father is always well pleased,
that we may draw near to God, and stand with confidence before His throne,
being purged by the blood of Jesus inwardly poured into our souls,
and clothed with His life and righteousness therein revealed.
And this is that order and method of salvation held forth by
the apostle in that divine saying (Romans 5:10):
"`For if, when we were enemies, we were reconciled to God by the death of His Son,
much more being reconciled, we shall be saved by His life.`"
Here the apostle first holds forth reconciliation wrought by the
death of Christ (wherein God is near to receive and redeem man),
and then man`'s salvation and real justification wrought by the life of Jesus.
Now this life is an inward, spiritual thing revealed in the soul,
whereby the soul is renewed and brought forth out of
death (where it naturally has been by the fall),
and so quickened and made alive unto God.

Of this saving life the apostles speak frequently,
commending all disciples to the inward working of its power.
Paul, upon taking leave of the Ephesians, says, "`So now, brethren,
I commend you to God and to the Word of His grace,
which is able to build you up and give you an
inheritance among all those who are sanctified.`"^
footnote:[Acts 20:32]
And in his letter to the same,
he speaks of "`the exceeding greatness of His power toward us who believe.`"
James directs his readers to "`the implanted word, which is able to save your souls.`"^
footnote:[James 1:21]
Elsewhere, Paul writes, "`Even when we were dead in trespasses,
He made us alive together with Christ (by grace you have been saved),
and raised us up together.`"^
footnote:[Ephesians 2:5-6]
Now, this "`making alive`" and "`raising together`"
doubtless speaks of the inward work of renovation;
therefore the apostle here mentions their being saved by grace,
which is the inward virtue and power of Christ in the soul.
Of this the apostle also speaks in 2 Corinthians 4:10:
"`That the life also of Jesus might be made manifest in our body;`" and verse 11:
"`That the life of Jesus also might be made manifest in our mortal flesh.`"
And it is by this inward life of Jesus Christ revealed
and formed (as before observed) that "`we are saved.`"

Furthermore, the truth of our being justified by this revelation of Jesus Christ,
and the new creation brought forth in us,
does evidently appear from that excellent saying of the apostle in Titus 3:5:
"`According to His mercy He saved us,
through the washing of regeneration and renewing of the Holy Spirit,
whom He poured out on us abundantly through Jesus Christ our Savior,
that having been justified by His grace we should
become heirs according to the hope of eternal life.`"
So then, that which saves us is evidently also that which justifies us,
these words being more or less synonymous in this respect.
Here the apostle clearly ascribes the immediate cause
of justification to this inward work of regeneration,
which is Jesus Christ revealed and formed in the soul;
for this washing of regeneration is no doubt that inward power and virtue
whereby the soul is cleansed and clothed with the righteousness of Christ,
so as to be made fit to appear before God.

This doctrine is also manifest from 2 Corinthians 13:
5--"`Examine yourselves as to whether you are in the faith.
Test yourselves.
Do you not know yourselves,
that Jesus Christ is in you?--unless indeed you are reprobates.`"
First,
it appears here how earnest the apostle was that they should know Christ to be in them,
for he presses this exhortation upon them three times.
Secondly,
he makes the cause of reprobation (or of non-justification)
the lack of Christ thus revealed and known in the soul.
Thus it necessarily follows, that wherever Christ is inwardly known,
there the persons subjected to Him are approved and justified.
Nothing could be more plain than this; for if we must know Christ in us,
except we be reprobates (or unjustified persons),
then those who __do__ know Him in them are __not__ reprobates,
and consequently justified persons.
For this reason, the same apostle says: "`My little children,
for whom I travail in birth again until Christ be formed in you,`"^
footnote:[Galatians 4:19]
also using this language--"`Christ within, the hope of glory.`"^
footnote:[Colossians 1:27-28]

Now, in insisting upon this inward work,
we are far from denying that the origin and fundamental cause of our justification
is the love of God manifested in the appearance of Jesus Christ in the flesh,
who by His life, death, sufferings and obedience, made a way for our reconciliation,
becoming a sacrifice for the remission of sins that are past.
Yet, "`through one Man`'s righteous act the free gift came to all men,`"^
footnote:[Romans 5:18]
for He purchased unto us His Seed and Grace from which this inward birth arises,
and in which Jesus Christ is inwardly received, formed, and brought forth in us,
in His own pure and holy image of righteousness.
By this alone our souls live unto God, and are clothed with Him, and have put Him on,
even as the Scripture speaks (Eph. 4:23-24;
Gal. 3:27). We stand justified and saved in and by Him,
and by His Spirit and grace (Rom. 3:24; 1 Cor. 6:11;
Tit. 3:7). Hereby we are made partakers of the fullness of His merits, and indeed,
His cleansing blood is near to wash away every sin and weakness,
and to heal all our backslidings as often as we turn towards
Him by unfeigned repentance to become renewed by His Spirit.

Therefore,
those who find Christ thus raised and ruling in them have a true
ground of hope to believe that they are justified by His blood.
But let not any deceive themselves,
so as to encourage themselves in a vain hope or confidence
that by the death and sufferings of Christ they are justified,
even while "`sin lies at their door,`"^
footnote:[Genesis 4:7]
iniquity prevails,
and they remain yet unrenewed and unregenerate--lest it be said unto them at last,
"`I never knew you; depart from Me.`"^
footnote:[Matthew 7:23]
Let that saying of Christ be remembered, "`Not everyone who says to Me, '`Lord,
Lord,`' shall enter the kingdom of heaven,
but he who does the will of My Father in heaven.`"^
footnote:[Matthew 7:21]
And with this consider those excellent sayings of the beloved disciple:
"`Little children, let no one deceive you.
He who practices righteousness is righteous, just as He is righteous.
He who sins is of the devil.`"^
footnote:[1 John 3:7-8]
And "`if our heart condemns us, God is greater than our heart, and knows all things.`"^
footnote:[1 John 3:20]

Many famous Protestants bear witness to this
justification by Christ inwardly revealed and formed in man.
Martin Borrhaus says, "`The form of our justification is the divine righteousness itself,
by which we are made just and good.
This is Jesus Christ,
who is called '`our righteousness,`' partly from the forgiveness of sins,
and partly from the renewing and the restoring of that
integrity which was lost by the fault of the first Adam,
so that the new and heavenly Adam is put on by us, of which the apostle says,
'`You have put on Christ.`'`"^
footnote:[In Gen.
pag. 181]
Zwingli also, says, "`The sanctification of the Spirit is true justification,
which alone suffices to justify.`"^
footnote:[In his epistle to the princes of Germany, as cited by Himelius, c. vii., p. 60,]
Estius, commenting upon 1 Cor. 6:11, says,
"`Lest Christian righteousness should be thought to consist in the washing alone,
that is, in the remission of sins, Paul adds the other degree or part,
'`but you are sanctified;`' that is, you have attained to purity,
so that you are now truly holy before God.
Lastly, expressing the sum of the benefit received in one word,
which includes both the parts, the apostle adds,
'`but you are justified in the name of the Lord Jesus
Christ and by the Spirit of our God.`'`" And lastly,
Richard Baxter, the famous English preacher, says,
"`Some ignorant wretches gnash their teeth at this doctrine,
as if it were flat Roman Catholicism,
not understanding the nature of the righteousness of the new covenant;
which is all out of Christ in ourselves,
though wrought by the power of the Spirit of Christ in us.`"^
footnote:[In his book called Aphorisms of Justification, p. 80]

=== The Necessity of Good Works

The third thing to be considered is concerning good works, which,
as we have said, do naturally flow from this spiritual birth, as heat from a fire,
and are therefore an absolute necessity to justification--not as the cause thereof,
but as that in which we are justified, and without which we cannot be justified.

I suppose enough has already been said to clear us from any
charges of being similar to the Roman Catholics in this matter.
But if it be asked, whether we affirm that a man is justified by works?
I answer--I hope none will take offense if in this
matter we use the plain language of the Holy Scripture,
which expressly says: (James 2:24) "`You see then that a man is justified by works,
and not by faith only.`"
I need not offer to prove the truth of this saying,
since what is said in this chapter by the apostle is sufficient to
convince any man that will but read and believe it.
I shall only derive this one argument:

[.discourse-part]
__Argument:__ If no man can be justified without faith,
and no faith can be living or suitable to justification without works,
then works are necessary to justification.

[.small-break]
'''

This truth is so apparent and evident in the Scriptures that,
for the proof of it, we might transcribe most of the precepts of the Gospel.
I shall instance a few which so clearly assert the thing in question
that they need no commentary nor further demonstration,
and then answer the common objections made against this.
HebRev. 12:14, "`Without holiness no man shall see God;`" Matthew 7:21,
"`Not every one that says unto Me, Lord, Lord, shall enter into the kingdom of heaven,
but he that does the will of my Father who is in heaven;`" John 13:17,
"`If you know these things, happy are you if you do them;`" 1 Corinthians 7:19,
"`Circumcision is nothing, and uncircumcision is nothing,
but the keeping of the commandments of God;`" Rev. 22:14,
"`Blessed are they that do His commandments,
that they may have right to the tree of life and
through the gates may enter into the city;`" Indeed,
many more might be given as examples, from all of which I argue:

[.discourse-part]
__Argument:__ If only those who do the will of the Father can enter the kingdom of heaven;
if only those who do the sayings of Christ are accounted the wise and happy builders;
if no outward observations avail, but only the keeping of the commandments;
and if only those who do His commandments have right to the Tree of Life,
and an entrance through the gates of the city;
then works are absolutely necessary to salvation and justification.

[.discourse-part]
Objection:
But they object that works are not necessary to justification
because of the saying of Christ in Luke 17:10:
"`When you have done all those things which you are commanded, say,
'`We are unprofitable servants,`'`" etc.

[.discourse-part]
Answer: As to God we are indeed unprofitable, for He needs nothing,
and we can add nothing to Him.
But as to ourselves we are not unprofitable,
else it might be said that it is not profitable for a man to keep God`'s commandments,
which is most absurd and would contradict Christ`'s doctrine throughout the Scriptures.
Does not Christ pronounce those men "`good and
faithful servants`" who improved their talents?^
footnote:[Matthew 25:14-30]
Was not their doing so profitable unto them?
It is said of the one that hid his talent and did not improve it,
"`Cast the unprofitable servant into the outer darkness.`"
If failing to improve the talent made this man unprofitable,
then improving their talents indeed made the others profitable,
especially seeing how Christ said of them, "`Well done, good and faithful servant,
you have been faithful over a few things, I will make you ruler over many things;
enter into the joy of your Lord.`"^
footnote:[Matthew 25:23]

[.discourse-part]
Objection: Secondly, they object from those sayings of the apostle Paul,
where he excludes the deeds of the law from justification: such as Romans 3:20,
"`Therefore by the deeds of the Law no flesh
will be justified in His sight,`" and verse 28,
"`Therefore we conclude that a man is justified
by faith apart from the deeds of the Law.`"

[.discourse-part]
Answer: In answer to this objection, I say,
there is a great difference between the works of the Law,
and the works of grace or of the Gospel.
The first are excluded, the second are not, but are necessary.
The first are those which are performed in man`'s own will and by his strength,
in a conformity to the outward law and letter,
and therefore are man`'s own imperfect works,
or the works of the Law which makes nothing perfect.^
footnote:[Hebrews 7:19]
And to this kind belong all the ceremonies, purifications, washings,
and traditions of the Jews.
The second are the works of the Spirit of Grace in the heart,
wrought in conformity to the inward and spiritual law.
These works are not wrought in man`'s will, nor by his power and ability,
but in and by the power and Spirit of Christ in us,
and therefore are pure and perfect according to their kind.
Indeed, these may be called Christ`'s works,
for He is the immediate author and worker of them.^
footnote:[See Hebrews 13:20-21; Philippians 1:11-2:13]
Such works we absolutely affirm to be necessary to justification,
so that a man cannot be justified without them;
for all faith without them is dead and useless, as says the apostle James.

Now,
that this distinction between works of the Law and works of grace is to be admitted,
and that the apostle excludes the first from justification but not the second,
clearly appears when we consider the context of these assertions.
For in both his letter to the Romans and to the
Galatians where he speaks to this purpose,
we find that many of the Gentiles (who were not of the seed of Abraham
according to the flesh) had been converted to the Christian faith,
and come to believe in Him.
Yet some among the Jewish converts to the faith sought to subject the
believing Gentiles to the legal ceremonies and observations of the Law,
insisting that these were necessary to their justification.
This gave the apostle Paul occasion at length to show the use and tendency of the Law,
and of its works,
and to distinguish them from the faith of Christ and the righteousness thereof,
showing that the former had ceased and become ineffectual, but the latter remained,
and was necessary.
And the kind of works excluded by the apostle is evident by
the whole strain of his epistle to the Galatians.
For in the fourth chapter,
he reproves them for returning to the observation of days and times,^
footnote:[Galatians 4:10-11]
and in the fifth and sixth he shows them the folly of
adhering to the ceremony of circumcision,
saying: "`For in Christ Jesus neither circumcision nor uncircumcision avails anything,
but faith working through love;`"^
footnote:[Galatians 5:6]
and "`For in Christ Jesus neither circumcision nor uncircumcision avails anything,
but a new creation.`"^
footnote:[Galatians 6:15]
Now circumcision is a word which is often used
to comprehend the whole of the old covenant,
with its ceremonial and legal performances.
These, Paul says, are excluded, and by them no man is justified;
but faith working through love, but the new creature, __this__ is that which avails,
and indeed is necessary.
Now, that the apostle in no way intends to exclude the good
works of the new creature appears in this same place,
for he tells them plainly: "`Do not be deceived, God is not mocked;
for whatever a man sows, that he will also reap.
For he who sows to his flesh will of the flesh reap corruption,
but he who sows to the Spirit will of the Spirit reap everlasting life.
And let us not grow weary while doing good,
for in due season we shall reap if we do not lose heart.`"^
footnote:[Galatians 6:7-9]
Does it not clearly appear by this how necessary these good works are--not
the outward ceremonies and traditions of the Law,
but the fruits of the Spirit mentioned a little before (4:22),
by which Spirit Paul desired them all to be led,
and in which he would have them all walk.
The former are "`works of righteousness that __we__ have done,`" wrought in our first,
fallen nature, by our own strength, in legal performances.
The latter are the fruits of "`the washing of regeneration,
and the renewing of the Holy Spirit.`"^
footnote:[See Titus 3:5]

[.discourse-part]
Objection: But these works of the Spirit may also be called ours,
because they are wrought in us, and also by us many times as instruments.

[.discourse-part]
Answer: Even so, the two kinds of works differ widely from each other.
In the first we are yet alive in our own natural state, unrenewed, working of ourselves,
seeking to save ourselves by imitating and endeavoring
a conformity to the outward letter of the Law,
and so wrestling and striving in the carnal mind that is enmity to God,
and in the cursed will, which is not yet subdued.
But in the second we are "`crucified with Christ,`"^
footnote:[Galatians 2:20]
having become "`dead with Him,`"^
footnote:[Romans 6:3]
being partakers "`of the fellowship of His sufferings,`"
and made "`conformable to His death.`"^
footnote:[Philippians 3:10]
Here our first man, our "`old man with all his deeds`"^
footnote:[Colossians 3:9]
(both the openly wicked and the seemingly righteous),
are all buried and nailed to the cross of Christ,
and so it is no more we but Christ alive in us--the Worker living in us.
So then, though it be us in a sense,
yet it is according to that sense of the apostle in Galatians 2:20,
"`I have been crucified with Christ; it is no longer I who live,
but Christ lives in me;`" or, "`I labored more abundantly than they all, yet not I,
but the grace of God which was with me.`"^
footnote:[1 Corinthians 15:10]
These works are most certainly to be ascribed to
the Spirit of Christ and the grace of God in us,
as being immediately done, enabled, or led by Him.
And this manner of speech is not at all strained, but was familiar to the apostles,
as often appears in Scripture: such as Galatians 2:8:
"`For He who worked effectively in Peter for the apostleship to the
circumcised also worked effectively in me toward the Gentiles;`" or,
"`For it is God who works in you both to will and to do for His good pleasure,`"^
footnote:[Philippians 2:13]
etc.

[.discourse-part]
Objection: Some object that no works, not even the works of Christ in us,
can have place in justification, because nothing that is impure can be useful in it;
and all the works wrought in us are impure.
To prove this they allege that saying of the prophet Isaiah:
"`All our righteousness is as a filthy rag;`"^
footnote:[Isaiah 64:6]
adding this reason, that, seeing we are impure, so our works must be also;
for even the works of God, as performed by us, receive a tincture of impurity,
even as clean water passing through an unclean pipe is defiled.

[.discourse-part]
Answer: That no impure works are useful to justification is confessed;
but that all works wrought in the saints are impure is denied.
And to answer this objection,
the above-mentioned distinction between the two sorts of works will also serve us here.
For we confess that the first sort of works are impure;
but not the second--because the first sort is wrought by man in the unrenewed state,
but the other is wrought by the Spirit and grace of God.
And as for that place in Isaiah, it must relate to the first sort; for though he says,
"`All __our__ righteousness is as a filthy rag,`" yet this does
not comprehend the righteousness of Christ wrought in us,
but only that which we work of and by ourselves.
For were it otherwise,
then it would follow that we should throw away
all holiness and righteousness as a filthy rag,^
footnote:[Lit.
"`a menstrual garment`"]
even the fruits of the Spirit, mentioned in Galatians 5. But to the contrary,
some of the works of the saints are said to have been a
"`sweet savor in the nostrils of the Lord;`"^
footnote:[Philippians 4:18; 2 Corinthians 2:15]
and an "`ornament of great price in the sight of God;`"^
footnote:[1 Peter 3:4]
which are said to "`prevail with Him,`" and to be "`acceptable to Him;`"^
footnote:[See Romans 12:1-2, 14:18; Philippians 4:18; 1 Timothy 2:3,5:4;
1 Peter 2:2,5:30.]
which filthy rags cannot be (as many well-known Protestants have acknowledged).

As to the other part of this objection--that seeing
the best of men are still impure and imperfect,
therefore their works must be so--this involves a great assumption, one which we deny,
as will be discussed at length in the next proposition.
Yet even in the case of a man not thoroughly perfect in all respects,
this will not preclude all good or perfect works (according to their
kind) from being brought forth in him by the Spirit of Christ;
neither does the example of water going through an unclean pipe hit the mark;
because though water may be tinctured with uncleanness, yet the Spirit of God cannot,
whom we assert to be the immediate Author of those works that avail in justification.
Consequently, we say that Jesus Christ`'s works in His children are pure and perfect,
and that He works in and through that pure thing
of His own forming and creating in them.

Moreover, if our adversaries`' supposition held true,
then it would follow that the very miracles and works of the apostles,
which Christ wrought in them, and which they wrought in and by the Power, Spirit,
and Grace of Christ, were also impure and imperfect.
And indeed,
would not also the writing of the Holy Scriptures (which our adversaries
seem so much to magnify) of necessity be impure and imperfect,
as coming through impure and imperfect vessels?

But lastly,
because it seems fit here to say something of the merit and reward of works,
I shall add something in this place of our sense and belief concerning that matter.
We are far from thinking or believing that man merits anything by his works from God,
for indeed all is of free grace,
and therefore we have always denied the Catholic notion of __meritum ex condigno__.^
footnote:[Editor`'s Note:
__Meritum ex condigno__, is the Roman Catholic doctrine
stating that there is an intrinsic worth in works,
which God, if He does according to justice, cannot but reward with eternal life.]
Nevertheless we cannot help but acknowledge, that God,
out of His infinite goodness with which He has loved mankind,
after He communicates to him His holy Grace and Spirit, does, according to His own will,
recompense and reward the good works of His children.
And therefore, a merit of reward,
in the sense that the Scriptures plainly and positively assert it, we may not deny.
For the same Greek word __axion__,
which signifies "`merit,`" is found in those places where the
translators express it "`worth,`" or "`worthy,`" (as in Matt. 3:8;
1 Thess. 2:12; 2 Thess. 1:11-5)

Those who are called the Fathers of the church
frequently used the word "`merit`" in this way,
and many Protestants have shown themselves not
opposed to this word in the sense that we use it.
The Apology for the Augustan confession, art.
20, has these words: "`We agree that works are truly meritorious,
not of the remission of sins or justification;
but they are meritorious of other rewards both natural and spiritual,
which are indeed both in this life and after this life.`"
G+++.+++ Voss, in his theological thesis concerning the merits of good works, says;
"`We have not gone as far as to condemn the word '`merit`' altogether,
as being that which both many of the ancients use,
and also the reformed churches have used in their confessions.
Now, that God judges and accepts men according to their works is beyond doubt to
any who will seriously read and consider the following scriptures:
Matt. 16:27; Rom. 2:6-7,10; 2 Cor. 5:10; James 1:25; Heb. 10:36;
1 Pet. 1:17; Rev. 22:12.`"

=== Conclusion

To conclude this theme, let none be so bold as to mock God,
supposing themselves justified and accepted in the
sight of God by virtue of Christ`'s death and sufferings,
while they remain unsanctified and unjustified in their own hearts,
and polluted in their sins--lest their hope prove to be that of the hypocrite,
which perishes.^
footnote:[Job 8:13]
And on the other hand, let none foolishly imagine that they can, by their own works,
or by the performance of any ceremonies or traditions, or by the giving of money,
or by afflicting their bodies in will worship and voluntary humility,
or foolishly striving to conform themselves to the outward letter of the law,
flatter themselves that they merit anything before God, or draw a debt upon Him.
Indeed,
let no one think that men have power to make
such things effectual to their justification,
lest they be found foolish boasters and strangers to Christ and His righteousness.
But blessed forever are they who have truly had
a sense of their own unworthiness and sinfulness,
who have seen all their own endeavors and performances to be fruitless and vain.
Yes, blessed are they who have beheld their own emptiness,
and the worthlessness of their vain hopes, faith, and confidence,
while being inwardly pricked, pursued,
and condemned by God`'s holy witness in their hearts.
For these, having surrendered themselves to this inward witness,
and allowed His grace to work in them,
have become changed and renewed in the spirit of their minds, passed from death to life,
and come to know Jesus arisen in them, working both the will and the deed.
These have indeed "`put on the Lord Jesus Christ,`"^
footnote:[Romans 13:14]
and are clothed with Him, and partake of His righteousness and nature,
and so can draw near to the Lord with boldness,
knowing their acceptance in and by Him in whom the Father is well pleased.
