== Chapter VI. Concerning Perfection

Since we have placed justification in the experience of Jesus Christ revealed,
formed,
and brought forth in the heart--there working His works of righteousness and
bringing forth the fruits of the Spirit--the question that now confronts us
is how far He may prevail in us while we are in this life?
Or how far may we prevail over our souls`' enemies, in and by His strength?

Those that plead for a justification wholly without them,
merely by an imputed righteousness,
denying the necessity of being clothed with real and inward righteousness,
do consequently affirm that it is "`impossible`" for a man, even "`the best of men,
to be free of sin in this life, which,`" they say, "`no man ever was.`"
On the contrary, they insist that none can, "`neither of himself,
nor by any grace received in this life +++[+++O,
wicked saying against the power of God`'s Grace!], keep the commandments of God perfectly,
but that every man does break the commandments in thought, word and deed.`"^
footnote:[These are the words of the Westminster larger Catechism.]
From this they also affirm (as was observed before),
that the very best actions of the saints, even their prayers and worship,
are impure and polluted.

Now, we freely acknowledge this to be true of the natural, fallen man,
in his first state, whatever his profession or pretense may be,
so long as he is unconverted and unregenerate.
However, we do believe that, to those in whom Christ comes to be formed,
and the new man brought forth and born of the incorruptible seed,
as that birth (and the man in union with it) naturally does the will of God,
so it is possible to keep to it in such a way as not to
be found daily transgressors of the law of God.
And for the more clear stating of the controversy, let the following be considered:

First, that we do not place this possibility in man`'s own will and capacity,
as he is a man, the son of fallen Adam, or as he is in his natural state,
however wise or knowing,
or however much he is endued with a notional and literal knowledge of Christ,
thereby endeavoring a conformity to the letter of the outward law.

Secondly, we attribute this wholly to man as he is born again,
renewed in his mind, raised by Christ, knowing Christ alive, reigning and ruling in him,
guiding and leading him by His Spirit,
and revealing in him the law of the Spirit of
life--which not only manifests and reproves sin,
but also gives power to come out of it.

Thirdly,
by this we do not intend such a perfection as does not allow for a daily growth,
and so do not mean we are to be as pure, holy,
and perfect as God in His divine attributes of wisdom, knowledge and purity.
Rather, we speak of a perfection proportionable and answerable to man`'s measure,
whereby we are kept from transgressing the law of God
and enabled to answer what He requires of us.
Even as a little gold is perfect gold in its kind, as well as a great mass,
and as a child has a perfect body as well as a man, though it daily grows more and more.
Thus Christ is said (Luke 2:52) to have "`increased in wisdom and stature,
and in favor with God and man,`" though before that time He had never sinned,
and was no doubt perfect, in a true and proper sense.

Fourthly,
though a man may witness this for a season (and therefore all ought to press after it),
nevertheless, those who have attained it in measure, may,
by the wiles and temptations of the enemy, fall into iniquity, and lose it sometimes,
if they are not watchful, and do not diligently attend to that Seed of God in the heart.
And we do not doubt but that many good and holy men
have had some ebbings and flowings of this kind,
for though every sin weakens a man in his spiritual condition,
yet it does not necessarily destroy him altogether,
or render him incapable of rising again.

Lastly, though I affirm that after a man has arrived to such a sinless condition,
he may yet fall and sin again,
I will nevertheless not deny but there may be a state attainable in this life,
in which to do righteousness may become so natural to the regenerate soul,
that in the stability of this condition they cannot sin.
Others may perhaps speak more certainly of this state, if they have arrived to it.
With respect to myself, I shall speak modestly,
as acknowledging myself not to have arrived at it.
However, I dare not deny that there is such a state,
for it seems so clearly to be asserted by the apostle in the following words,
"`Whoever has been born of God does not sin, for His seed remains in him;
and he cannot sin, because he has been born of God.`"^
footnote:[1 John 3:9]

Having then stated the controversy,
I shall proceed first to show the absurdity of that
doctrine that pleads for sin for term of life,
even in the saints.
Secondly,
I will prove our doctrine of perfection from
many clear testimonies of the holy Scriptures.
And lastly, I will answer the arguments and objections of our opposers.

=== The Folly of Contending for Sin

First then,
the doctrine which states that saints can never be free from sinning in this life,
is inconsistent with the wisdom of God and with His glorious power and majesty,
"`who is of purer eyes than to behold evil, and cannot look upon wickedness;`"^
footnote:[Habakkuk 1:13]
for He who purposed in Himself to gather a people to worship Him in Spirit and truth,
and to witness for Him on the earth, is doubtless able to sanctify and purify them.
God has no delight in iniquity, but abhors transgression,
and though He regards man in transgression so far as to
pity him and afford him a means to come out of it,
yet He has no delight in man as he remains in that state.
For if men must always be joined to sin,
then God should always be at a distance from them, as it is written (Isa. 59:2),
"`Your iniquities have separated you from your God,
and your sins have hidden His face from you.`"
Indeed, it is expressly written,
that there is "`no communion between light and darkness.`"^
footnote:[2 Cor. 6:14]
Now God is Light, and every sin is darkness in measure.
So then, what greater stain could be cast upon God`'s wisdom,
than to suggest He lacks a means whereby His
children might perfectly serve and worship Him;
or that He has not provided a way whereby they might cease to serve the devil?
For "`he that sins is the servant of sin,`"^
footnote:[John 8:34; Romans 6:16]
and every sin is an act of service and obedience to the devil.
So then, if the saints must continue to sin daily, in thought, word and deed,
and if their very service to God is mixed with sin (as our opposers insist),
then surely they serve the devil as much or more than they serve the Lord!

Now, who would not be accounted a foolish master among men who,
being willing and able to provide a way whereby his
children and servants might serve him entirely,
yet refused to do so,
and instead allowed his servants to more fully and faithfully serve his avowed enemy?
What then should we think of a doctrine that would
infer this folly upon the omnipotent and only wise God?

Secondly, this doctrine is inconsistent with the justice of God.
For since God requires purity from His children,
and frequently commands them to abstain from every iniquity (as shall hereafter be seen);
and since "`His wrath is revealed against all ungodliness and unrighteousness of men,`"^
footnote:[Romans 1:18]
it must necessarily follow that He has given men the capacity to answer His will,
or else He requires more than He has given power to perform.
This, indeed, would be to openly declare Him unjust,
and to say with the slothful servant, "`You are a hard master!`"
We have previously spoken of the injustice that our opposers ascribe to God,
in alleging that He damns the wicked without ever
having afforded them the means of being saved.
But this is a charge even more irrational and inconsistent--to suggest that God
will not afford His own elect (whom they confess He loves) the means to please Him.

What can follow from so strange a doctrine?
This imperfection in the saints either proceeds from God, or it is from themselves.
If it proceeds from them,
it must be because they fall short in making use of the power
given to them--the grace whereby they are made capable to obey.
But if it is not of themselves, then the imperfection must be of God,
who has not seen fit to grant sufficient grace to answer His own requirement.
And again, what is this but to attribute to God the height of injustice,
to make Him require His children to forsake sin
even while withholding the means to do so!
Surely this makes God more unrighteous than the wicked
men of whom Christ spoke in His sermon on the mount;
for even they, when "`their children ask for bread, will not give them a stone,
or when they ask for fish, will not give them a serpent.`"^
footnote:[Matthew 7:9-11]
And though our adversaries confess that all
ought to seek God for power to redeem from sin,
yet they believe and teach that none should ever expect to receive such power.
Is this not to make God as unjust to His children as Pharaoh was to the Israelites,
in requiring brick and not giving them straw?
But blessed be God,
He does not so deal with those that truly trust in Him and wait upon Him,
as these men vainly imagine.
For the faithful ones indeed find His grace to be sufficient for them,
and they know how to overcome the evil one by the gift of His power and Spirit.

Thirdly,
this evil doctrine is highly injurious to Jesus Christ and
greatly derogates from the power and virtue of His sacrifice,
rendering His coming and ministry ineffectual.
For one of the principal reasons for Christ`'s coming in the flesh was the removal of sin,
and the gathering of a righteous generation to serve the Lord in purity of mind,
and to walk before Him in fear.
It is He who "`brought in everlasting righteousness,`"^
footnote:[Daniel 9:24]
and that gospel perfection which the Law could not effect.^
footnote:[See Colossians 1:28; Hebrews 7:19-9:9, 10:1]
Hence He is said to have "`given Himself for us,
that He might redeem us from every lawless deed
and purify for Himself His own special people,
zealous for good works.`"^
footnote:[Titus 2:14]
These words of the apostle are certainly spoken
with regard to the saints while still upon earth.
But contrary to this,
our opponents affirm that we are never truly redeemed from all iniquity,
and so they make Christ`'s "`giving of Himself for us`" void and ineffectual,
denying that He really "`purifies for himself a special people.`"
But, I ask,
how can a people be zealous for good works when they are daily committing evil ones?
And how are they a purified people who still live in impurity, and sin continually?
It is expressly written that, "`For this purpose the Son of God was manifested,
that He might destroy the works of the devil,`"^
footnote:[1 John 3:8]
and, "`You know that He was manifested to take away our sins.`"^
footnote:[1 John 3:5]
But these men make this purpose of no effect,
for they will not believe that the Son of God
destroys the works of the devil in this world,
nor that Christ was manifest to take away our sins,
seeing they plead a necessity of always living in them.
And lest any should twist this Scripture as if
it were spoken only of removing the __guilt__ of sin,
the apostle (as though seeking purposely to avoid such an objection) immediately adds,
"`Whosoever abides in Him does not sin;`" and "`Let no one deceive you.
He who practices righteousness is righteous, just as He is righteous.
He who sins is of the devil.`"^
footnote:[1 John 3:6-8]

Now, if Christ was manifest to take away sin,
how strangely do these men overturn the doctrine of
Christ by denying that sin is ever taken away here?
Oh consider how injurious this is to the efficacy and power of Christ`'s appearance?
Did not Christ come to gather a people out of sin into righteousness,
out from the kingdom of Satan into the kingdom of the dear Son of God?
And do not they who are gathered by Him become His servants, His children, His brethren,
and His friends?
Indeed, it is said of them "`as He was, so are they in this world`"^
footnote:[1 John 4:17]--holy, pure, and undefiled.
And does not Christ still watch over them, stand by them, pray for them,
preserve them by His Power and Spirit, walk in them and dwell among them,
even as the devil, on the other hand, does among the reprobate ones?
Why would the servants of Christ be less able to serve their
Master than the servants of the devil serve theirs?
Or is Christ unwilling to have His servants thoroughly pure (a gross blasphemy,
contrary to many scriptures)?
Or is Christ not able by His power to preserve and enable His
children to serve Him (which is no less blasphemous to affirm)?
But certainly, if the saints sin daily in thought, word, and deed, as these men assert,
then they serve the devil daily, and continue subject to his power,
and so he prevails more in them than Christ,
and keeps them in bondage even contrary to Christ`'s will.
But how greatly does this contradict the end of Christ`'s
coming as it is expressed by the apostle:
"`Even as Christ also loved the church and gave Himself for her,
that He might sanctify and cleanse her with the washing of water by the word,
that He might present her to Himself a glorious church,
not having spot or wrinkle or any such thing,
but that she should be holy and without blemish.`"^
footnote:[Ephesians 5:25-27]
Now, if Christ has really accomplished the thing for which He came,
then the members of His body are not always to be sinning in thought, word, and deed.
Otherwise, there is no difference between being sanctified and unsanctified,
clean and unclean, holy and unholy, being daily blemished with sin,
and being without blemish.

Fourthly, this doctrine renders the work of the ministry,
the preaching of the Word, the writing of the Scriptures,
and the prayers of holy men altogether useless and ineffectual.
As to the first (Eph. 4:11-13),
pastors and teachers are said to be "`given for the perfection of the saints,`" etc.,
"`till we all come in the unity of the faith and of the knowledge of the Son of God,
unto a perfect man, unto the measure of the stature of the fullness of Christ.`"
Now, if there is a necessity of sinning daily, and in all things,
then there can be no perfection.
Moreover, these ministers,
who assure us that we need never expect to be delivered from sin,
do they not render their own work needless?
For what need is there for preaching against sin, if sin can never be forsaken?
And with regard to the Scriptures, our adversaries highly exalt them in their words,
often extolling their usefulness and perfection.
Indeed,
the apostle tells us (2 Tim. 3:17) that the "`Scriptures are profitable for doctrine,
for reproof, for correction, for instruction in righteousness,
that the man of God may be perfect, thoroughly furnished unto all good works.`"
But if it be denied that this is attainable in this life,
then the Scriptures are to no profit,
for what use shall we have of them in the next life?
Furthermore, this doctrine renders the prayers of the saints altogether useless;
for why should we pray daily that God deliver us from evil and
free us from sin by the help of His Spirit and Grace (as all
confess we ought) if such a thing be unattainable in this life?
Yet the holy apostles prayed earnestly for this end,
and therefore (no doubt) believed it attainable here.
For they were "`always laboring fervently for them in prayers,
that they may stand perfect and complete in all the will of God.`"^
footnote:[Colossians 4:12]
They prayed that God would "`establish their hearts blameless in holiness,`"^
footnote:[1 Thessalonians 3:13]
and "`sanctify them entirely, spirit, soul, and body,`"^
footnote:[1 Thessalonians 5:23] etc.

But fifthly, this doctrine is contrary to common sense and reason.
For sin and righteousness are as two opposite seeds--
the one ruling in the children of darkness,
the other in the children of Light.
And as men are respectively leavened and governed by them,
so they are accounted either reprobated or justified,
seeing it is an "`abomination in the sight of God
either to justify the wicked or to condemn the just.`"^
footnote:[Proverbs 17:15]
Now to say that men cannot be so leavened with
the one as to become delivered from the other,
is, in plain words, to affirm that sin and righteousness are compatible,
and that a man may be truly termed righteous,
though he be daily sinning in everything he does.
And then what difference is there between good and evil?
Is this not to fall into that great abomination of "`putting
light for darkness,`" and "`calling good evil,
and evil good?`"^
footnote:[Isaiah 5:20]
For they say the very best actions of God`'s children are defiled and polluted,
and that those who sin daily in thought, word, and deed are good men and women,
even the saints and holy servants of the holy and pure God.
Can there be anything more repugnant to common reason than this?
Where are the purified ones of whom the Scriptures speak?
Where are they who were formerly unholy, but now have been washed and made holy;^
footnote:[1 Corinthians 6:11]
who were formerly darkness, but now are light in the Lord?^
footnote:[Ephesians 5:8]
According to this sinful doctrine there can indeed be none.

=== Evidence from Scripture

For the further demonstration of the truth,
I shall now proceed to the second thing proposed by me, namely,
to prove our position from several testimonies of the holy Scriptures.

First, I prove it from the absolute,
positive command of Christ and His apostles to keep the commandments,
and to be perfect in this respect, knowing that God requires no impossible thing.
Now, that this is plainly commanded in the New Testament,
without any commentary or consequence, is evident in the following Scripture testimonies:
Matthew 5:48, "`Therefore you shall be perfect,
just as your Father in heaven is perfect.`"
1 Corinthians 7:19, "`Circumcision is nothing, and uncircumcision is nothing,
but the keeping of the commandments of God.`"
1 John 2:3-6, "`Now by this we know that we know Him, if we keep His commandments.
He who says, '`I know Him,`' and does not keep His commandments, is a liar,
and the truth is not in him.
But whoever keeps His word, truly the love of God is perfected in him.
By this we know that we are in Him.`"
1 John 3:5-10, "`And you know that He was manifested to take away our sins,
and in Him there is no sin.
Whoever abides in Him does not sin.
Whoever sins has neither seen Him nor known Him.
Little children, let no one deceive you.
He who practices righteousness is righteous, just as He is righteous.
He who sins is of the devil, for the devil has sinned from the beginning.
For this purpose the Son of God was manifested,
that He might destroy the works of the devil.
Whoever has been born of God does not sin, for His seed remains in him;
and he cannot sin, because he has been born of God.
In this the children of God and the children of the devil are manifest:
Whoever does not practice righteousness is not of God,
nor is he who does not love his brother.`"
See also Matt. 7:21, John 13:17; 1 Cor. 7:19; 2 Cor. 13:11.
All of these scriptures intimate a
positive command for the keeping of His commandments,
and declare the absolute necessity of it.
Therefore,
as if they had been purposely written to answer the objections of our opposers,
they show the folly of those that will esteem themselves children or friends of God,
while they do otherwise.

Secondly,
such a freedom from sin is possible because we receive the Gospel for that very purpose.
This is expressly promised to us as we come under the dominion of grace,
as appears by these scriptures: Romans 6:14,
"`For sin shall not have dominion over you, for you are not under Law but under Grace.`"
Romans 8:3-4, "`For what the Law could not do in that it was weak through the flesh,
God did by sending His own Son... that the righteous
requirement of the law might be fulfilled in us,`" etc.
For if this were not a condition both necessary and attainable under the Gospel,
there would be no difference between "`the Law,
which made nothing perfect,`" and "`the bringing in of a better hope,`"^
footnote:[Hebrews 7:19]
nor between those who are under the Gospel and mere legalists.
But the apostle,
throughout the whole sixth chapter to the Romans argues not only the possibility,
but the necessity of being free from sin by coming under the Gospel and under Grace,
and being no longer under the Law.
In verses 2-7 he states this to be the condition of himself and those to whom he writes,
and then in 11-13 and 16-18 he argues both the
possibility and the necessity of freedom from sin,
saying "`Therefore do not let sin reign in your mortal body,
that you should obey it in its lusts,`" and, "`Having been set free from sin,
you became slaves of righteousness.`"
Finally, in the 22nd verse,
he declares his readers in measure to have attained this condition, in these words,
"`But now having been set free from sin, and having become slaves of God,
you have your fruit to holiness, and the end, everlasting life.`"

Now,
even as this perfection or freedom from sin is attained and made possible
where the Gospel and inward law of the Spirit is received and known,
so the ignorance of this inward life and power has been
and is the reason why so many oppose this truth.
For man, not minding the Light or Law within his heart,
which not only discovers sin but leads out of it,
remains a stranger to the new Life and Birth that is born of God,
which naturally does His will, and cannot, of its own nature,
transgress His commandments.
Such a man, in his natural state,
looks at the commandments of God as they are without him, in the letter,
and finds himself reproved and convicted, and by the letter killed but not made alive.
And so, finding himself wounded,
and not applying himself inwardly to that Light and Grace which can heal,
he labors in his own will after a conformity to the Law as it is written in words,
which he can never obtain, but finds that the more he wrestles, the more he falls short.
Though these may have a notion of Christianity, and an external faith in Christ,
still they are, in effect, in the state of the Jew, with his carnal commandment,
his external law,
in the first covenant state which "`makes not the comers thereunto perfect
as pertaining to the conscience`" (Heb. 9:9). This has made them strain
and twist the Scriptures for an imputed righteousness wholly from without,
in order to cover their ongoing impurities,
and to imagine an acceptance with God to be possible,
even while they hold it impossible ever to obey Christ`'s commands.

But alas, O deceived souls!
This will not avail in the Day wherein God will
judge "`every man according to what he has done,
whether good or bad.`"^
footnote:[2 Corinthians 5:10]
It will not save you to say it was necessary to sin daily in thought, word, and deed;
for those who do so have most certainly "`obeyed unrighteousness.`"^
footnote:[Romans 2:8]
And what is the end of these but tribulation and anguish, indignation and wrath;
even as glory, honor, peace,
and immortality are promised to such as have
done good and patiently continued in well-doing.
So then,
if you desire to know this perfection and freedom from sin made possible for you,
turn your mind to the Light and spiritual Law of Christ in the heart,
and submit to its reproofs.
Bear the judgment and indignation of God upon the
unrighteous nature in you according as it is revealed,
which Christ has made tolerable for you;
and so suffer "`judgment`" in you to be "`brought forth into victory.`"^
footnote:[Matthew 12:20. Editor`'s Note:
Many modern translations use the word __justice__ in place of __judgment__,
but the Greek word is indeed judgment (__krisis__).
The same is true of the Hebrew word in Isaiah 42 from
which this quotation in Matthew is taken (__mishpat__, i.e. judgment).]
In this way you will come to partake of the fellowship of
Christ`'s sufferings and be made conformable unto His death.^
footnote:[Philippians 3:10]
You will feel yourself crucified with Him to the world by the power of His cross in you,
so that that life which formerly was alive in you to this world,
and to its love and lust, may die,
and a new life be raised by which you may live
from now on unto God and not to or for yourself.
Then you will truly be able to say with the apostle, "`I have been crucified with Christ;
it is no longer I who live, but Christ lives in me.`"^
footnote:[Galatians 2:20]
Then you will be a Christian indeed, and not one in name only, as too many are.
Then you will know what it is to have "`put off the old
man with his deeds,`" who indeed sins daily in thought,
word, and deed; and to have "`put on the new man, that is renewed in holiness,
after the image of Him that has created him.`"^
footnote:[Colossians 3:9-10]
And you will witness yourself to be "`God`'s workmanship
created in Christ Jesus unto good works.`"^
footnote:[Ephesians 2:10]
And to this new man "`Christ`'s yoke is easy, and His burden is light;`"^
footnote:[Matthew 11:30]
though it is heavy to the old Adam.
Yes, the commandments of God are not grievous unto this new man;
for it is his food and drink to be found fulfilling the will of God.

=== Objections Considered

But I shall proceed now to answer the objections and arguments of our opposers.

[.discourse-part]
Objection: I shall begin with their chief and great argument,
which is the words of the apostle John: "`If we say that we have no sin,
we deceive ourselves, and the Truth is not in us.`"^
footnote:[1 John 1:8]
This they think invincible.

[.discourse-part]
Answer: But this objection does not suit their purpose,
for John does not say we sin daily in thought, word, and deed,
far less that the very good works which God works in us by His Spirit are sin.
Indeed,
the very next verse clearly shows that upon confession and
repentance we are not only forgiven but also cleansed:
"`He is faithful to forgive us our sins, and to cleanse us from all unrighteousness.`"
Here is both a forgiveness and removing of the guilt,
and a cleansing or removing of the filth;
for it would be both senseless and repetitive to make both
forgiveness and cleansing belong to the removing of guilt.
For this reason, having known both the guilt and the filth of sin removed,
the apostle continues in the past tense in verse 10 saying,
"`If we say we have not __sinned__, we make Him a liar.`"

Furthermore,
as Augustine well observed in his exposition upon the epistle to the Galatians,
"`It is one thing not to sin, and another thing not to have sin.`"
The apostle`'s words are not, "`If we say we do not commit sin daily,
we deceive ourselves;`" but "`if we say we have no sin.`"
And between these two statements there is a great difference!
For we freely acknowledge that all have sinned,
and that all may be said in this sense to have sin.
Moreover, "`sin`" may be taken for the seed of sin which is in all men,
even in those who are redeemed from actual sinning.
But as to the temptations and provocations that proceed from this seed,
when resisted by grace in the servants of God and not yielded to,
the sin belongs to the devil who tempts, and not to the man who is preserved.

But the whole of this controversy is unnecessary, for the very same apostle,
in several places of the same epistle,
plainly and positively asserts the possibility of freedom from sin,
as has been mentioned already.

[.discourse-part]
Objection: Their second objection is from two places of Scripture,
which say very much the same thing.
The one is 1 Kings 8:46, "`For there is no man that does not sin.`"
The other is Ecclesiastes 7:20, "`For there is not a just man upon earth,
that does good, and does not sin.`"

[.discourse-part]
Answer: I answer, first,
that these verses speak nothing of a daily and continual sinning,
so as never to be redeemed from it, but only that all have sinned,
or that there is none that does not sin.
Secondly,
there is something to be said for the covenant
and dispensation in which these were written;
for even if it should be granted that in Solomon`'s time there was none who did not sin,
it will not necessarily follow that there are none such now,
or that it is not now attainable by the grace of God under the Gospel.
And lastly, this whole objection hangs upon a false interpretation of Scripture;
for the Hebrew word __yekhta`'__ may be read in the potential mood,
thus rendering it "`There is no man who __may not__ sin,`" which indeed
is how it is translated from the Hebrew by Junius and Tremellius,
and also Vatablus.
The same word is similarly translated in the potential mood in Ps. 119:11,
"`I have hidden Your word in my heart, that I __may not__ sin against You.`"
And seeing that this translation is more congruent with
the universal scope of the Scriptures,
the testimony of the Truth, and the sense of almost all interpreters,
it doubtless ought to be so understood.

[.discourse-part]
Objection: Thirdly,
they object from some expressions of the apostle Paul in Romans chapter 7:
"`For the good that I will to do, I do not do; but the evil I will not to do,
that I practice.`"^
footnote:[Romans 7:19]
And "`O wretched man that I am!
Who shall deliver me from the body of this death?`"^
footnote:[Romans 7:24]

[.discourse-part]
Answer: I answer,
there is nothing in the text which would suggest
him to be speaking of his present condition,
or of a condition that he must always be under.
On the contrary, in the former chapter (as has been mentioned at large),
he insists that Christians, being "`dead to sin,`" should no longer live therein.
It is apparent then, that the apostle here speaks of a condition he had formerly known,
or that he impersonates (for the benefit of his readers)
the condition of one not yet come to maturity,
which is common in Scripture.

Now, that Paul does not here speak of his present condition is evident,
for previously in this chapter he says (vs. 5), "`For when we __were__ in the flesh,
the sinful passions which were aroused by the law were at work in our members to
bear fruit to death;`" and (vs. 9) "`I __was alive once__ without the law,
but when the commandment came, sin revived and I died.`"
And later he says (vs. 14), "`We know that the law is spiritual, but I am carnal,
sold under sin.`"
But are we to imagine that the apostle Paul was a
carnal man at the time of writing this epistle?
Does he not plainly inform us how he was not left in this condition,
but indeed witnessed deliverance from it?
For after his exclamation,
"`Who will set me free from the body of this
death,`" he happily answers his own question,
saying, "`I thank God--through Jesus Christ our Lord,`"^
footnote:[Romans 7:25]
and then affirms that "`the law of the Spirit of Life in Christ Jesus`" had "`made
him free from the law of sin and death,`" so that "`the righteous requirement of
the law might be fulfilled in us who do not walk according to the flesh but
according to the Spirit.`"^
footnote:[Romans 8:2-4]

[.discourse-part]
Objection: Fourthly, they object from the faults and sins of several eminent saints,
such as Noah, David, etc.

[.discourse-part]
Answer: I answer, this does not at all prove our opponent`'s case;
for the question is not whether good men may not fall into sin (which we do not deny),
but whether it is impossible for them not to sin.
Nor does it follow that, because these men sinned on certain occasions,
that they always sinned, and so never experienced times of true freedom from sin.

[.discourse-part]
Objection: Lastly, they object from the prayer of our Lord,
where He taught His disciples to say, "`forgive us our trespasses,
as we forgive those who trespass against us.`"^
footnote:[Matthew 6:12]

[.discourse-part]
Answer: I answer, we deny not that "`all have sinned,
and fall short of the glory of God,`"^
footnote:[Romans 3:23]
and that all therefore need to pray that their past sins may be blotted out,
and that they may be daily preserved from sinning.
But if some dare say that hoping or believing to be made free
from sin hinders praying for forgiveness of sin,
it would follow by the same rule that "`we should
continue in sin so that grace may abound;`"^
footnote:[Romans 6:1]
for the more men commit sin,
the more plentiful occasion there would be of asking forgiveness of sin.
But the apostle has sufficiently refuted such sin-pleasing
babblings in his response to this very controversy,
saying, "`May it never be!
How shall we who died to sin live any longer in it?`"^
footnote:[Romans 6:2]

To conclude then--blessed are they that believe in Him,
who is both able and willing to deliver from all sin,
as many as come to Him through true repentance,
and who do not resolve (as our adversaries do)
to be the devil`'s servants all their lifetime,
but daily go on forsaking unrighteousness, forgetting those things that are behind,
and "`pressing forward toward the mark, for the prize of the high calling of God,
in Christ Jesus.`"^
footnote:[Philippians 3:14]
Such as these shall find their faith and confidence not to be in vain,
and in due time shall be made conquerors through Him in whom they have believed; and so,
overcoming,
they shall be established as "`pillars in the
house of God,`" so as "`to go out no more.`"^
footnote:[Revelation 3:12]
