[quote.epigraph, , Ps. 62:5]
____
 My soul, wait silently for God alone, for my expectation is from Him.
____

[quote.epigraph, , Lam. 3:25-29]
____
The Lord is good to those who wait for Him, to the soul who seeks Him.
It is good that one should hope and wait quietly for the salvation of the Lord.
It is good for a man to bear the yoke in his youth.
Let him sit alone and keep silent, because God has laid it on him.
Let him put his mouth in the dust; there may yet be hope.
____

[quote.epigraph, , Ps. 130:5-6]
____
I wait for the Lord, my soul waits, and in His word I do hope.
My soul waits for the Lord, more than those who watch for the morning--Yes,
more than those who watch for the morning.
____

[quote.epigraph, , Ps. 123:2]
____
Behold, as the eyes of servants look to the hand of their masters,
as the eyes of a maid to the hand of her mistress, so our eyes look to the Lord our God,
until He has mercy on us.
____

[quote.epigraph, , Lam. 5:1-2]
____
Walk prudently when you go to the house of God;
and draw near to hear rather than to give the sacrifice of fools,
for they do not know that they do evil.
Do not be rash with your mouth, and let not your heart utter anything hastily before God.
For God is in heaven, and you on earth; therefore let your words be few.
____

== Forward

The greatest part of this booklet is an updated version of the eleventh
proposition of Robert Barclay's [.book-title]#Apology for the True Christian Divinity#.^
footnote:[Robert Barclay's [.book-title]#Apology for the True
Christian Divinity# is made available online for free,
and hardcover copies can be purchased through Quaker Heritage Press.
www.qhpress.org]
The entire volume of Barclay's [.book-title]#Apology# (consisting of fifteen
propositions in all) is a tremendous and compelling work that
I strongly recommend to every serious seeker of the Truth.
I have chosen to modernize and republish just this one proposition
because it seems to me that the invaluable practice of waiting upon
the Lord has been especially neglected,
and has all but disappeared from the church today.

The short appendix that begins on page 59 is an excerpt
from [.book-title]#The Works of Isaac Penington# on the same subject.

[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
April, 2016
