== A Brief Account Concerning Silent Meetings

[.chapter-subtitle--blurb]
by Isaac Penington

This is a great mystery, hidden from the eye of man,
who has run from the inward life into outward observations.
He cannot see that this is required by the Lord of his people,
or acknowledge any edification therein, or benefit thereby.
But to the mind that is drawn inward, the thing is plain,
and a true building up in the life of God,
and a fellowship one with another is therein sweetly felt.
For there is precious refreshment from the presence of the
Lord received by them who singly wait upon Him according to
the leadings and requirings of his Holy Spirit.
Now, if the Lord please, I will open the thing a little more for the upright-hearted.

After the mind is in some measure turned to the Lord, and his quickenings are felt,
and his seed begins to arise and spring up in the heart,
then the flesh is to be silent before Him,
and the soul is to wait upon Him (for his further appearings)
in that measure of life which is already revealed.
Now, this is a great thing to know the flesh silenced,
to feel the reasoning thoughts and discourses of the fleshly mind stilled,
and the wisdom, light, and guidance of God's Spirit waited for.
For man is to come into a poverty of self, into true humility, into the nothingness,
into the silence of his spirit before the Lord.
He must come to put off all his knowledge, wisdom, understanding, abilities,
all that he is, has done, or can do, that he may be clothed and filled with the nature,
Spirit, and power of the Lord.

Now, in this measure of life which is of Christ,
and in which Christ is and appears to the soul, there is the power of life and death.
There is power to kill the flesh, and power to quicken to God.
There is power to cause the soul to cease from its own workings,
and power to work in and for the soul what God requires,
and what is acceptable in his sight.
And in this God is to be waited upon and worshipped continually,
both in private and in public, according as his Spirit draws and teaches.

For the Lord requires of his people not only to worship Him privately,
but also to meet together to worship Him, in the seasons, and according to the drawings,
of his Spirit.
And those who are taught of Him dare not forsake the assembling of themselves together,
as is the manner of some,
but rather watch against such temptations and snares of the enemy.

And this is the manner of their worship--they are to wait upon the Lord,
to meet in the silence of flesh,
and to watch for the stirrings of his life and
the breakings forth of his power among them.
And in the breakings forth of that power they may pray, speak, exhort, rebuke, sing,
mourn, etc., according as the Spirit teaches, requires, and gives utterance.
But if the Spirit does not require to speak, and give to utter,
then everyone is to sit still in his place (in his heavenly place I mean),
feeling his own measure, feeding upon it, receiving from it, into his spirit,
whatever the Lord gives.

Now, in this is edifying, pure edifying, precious edifying.
The soul who waits in this way is hereby particularly
edified by the Spirit of the Lord at every meeting.
And also there is the life of the whole felt in every
vessel that is turned inward to its measure.
For the warmth of life in each vessel does not only warm the particular,
but they are like a heap of fresh and living coals, warming one another,
and a great strength, freshness, and vigor of life flows into all.
And if any be burdened, tempted, buffeted by Satan, bowed down, overborne, languishing,
afflicted, distressed, etc., the state of such is felt in Spirit,
and secret cries ascend up to the Lord for them.
And many times these find ease and relief in a few words spoken, or even without words.

Now, as for absolutely silent meetings, wherein there is a resolution not to speak,
these are unknown to us; rather, we wait on the Lord, either to feel Him in words,
or in silence of spirit without words, as he pleases.
And that which we aim at,
and are instructed to by the Spirit of the Lord as to our meetings,
is that the flesh in everyone be kept silent,
and that there be no building up except in the Spirit and power of the Lord.

Now, there are several states of people.
Some feel little of the Lord's presence, but rather feel temptations and thoughts,
with many wanderings and rovings of mind.
These are not yet acquainted with the power, or at least they do not know its dominion,
but still feel dominion of the evil over the good in them.
And this is a sore travailing and mournful state,
and our meetings to such as these (many times)
may seem more for the worse than for the better.
Yet even these, while turning, as much as they may away from such things,
and cleaving (or at least in truth of heart desiring to cleave),
to that which witnesses against the flesh, have acceptance with the Lord herein.
And continuing to wait in this trouble and distress (keeping close to meetings,
in fear and subjection to the Lord who requires it, though with little apparent benefit),
do reap a hidden benefit at present,
and shall reap a more clear and manifest benefit afterwards,
as the Lord wastes away and wears out in them
that part wherein the darkness has its strength.

God is to be worshipped in spirit, in his own power and life,
and this is at his own disposal.
His church is a gathering in the Spirit.
If any man speak there, he must speak as the oracle of God, 1 Pet. 4:11,
as the vessel out of which God speaks, as the trumpet out of which he gives the sound.
Therefore,
there is to be a waiting in silence till the Spirit of the Lord moves to speak,
and also gives words to speak.
For a man is not to speak his own words, or in his own wisdom or time,
but rather the Spirit's words, in the Spirit's wisdom and time,
which is when he moves and gives to speak.
And seeing that the Spirit inwardly nourishes even when he does not move to speak words,
so this inward sense and nourishment is to be
waited for and received when there are no words.
Yes, the ministry of the Spirit and life is more close and
immediate when it is without words than when it is with words,
as has been often felt, and faithfully testified to by many witnesses.
Eye has not seen, nor ear heard, neither has it entered into the heart of man,
how and what things God reveals to his children by his
Spirit when they wait upon Him in his pure fear,
and worship and converse with Him in Spirit.
For then the fountain of the great deep is unsealed,
and the everlasting springs surely give up the pure and living water.^
footnote:[Taken from [.book-title]#The Works of Isaac Penington#, Volume 4, pg. 47. Quaker Heritage Press. www.qhpress.org]
