== Considerations upon Entertainment and Recreation

Let us now consider the use of games, sports, comedies and other such things,
commonly used by all sorts of Christians under
the notion of entertainment and recreation,
and let us see whether such things are consistent with the seriousness, gravity,
and godly fear which the Gospel calls for.
I freely confess that true religion consists not in outward rules,
but in an inward birth of the Spirit, and growth in grace;
but I desire that all carefully consider whether such amusements do not contradict,
dishonor, and war against the purpose of God for the immortal soul of man.

Let any man honestly survey the lives of most who call themselves Christians,
whether Catholic or Protestant,
and see if generally there be any difference from the heathen,
except in mere name and profession of beliefs.
For indeed, does not the same folly, the same vanity,
the same abuse of precious and irrevocable time abound in all?
Is there not the same gaming, sporting, playing, and pleasure-seeking,
giving rise to the same quarreling, fighting, swearing, lusting, obscenity, folly,
and reveling?
And how can these things be remedied so long as
both preachers and professors of Christianity,
and those who are considered leaders of the people,
do openly allow these things and consider them consistent with the gospel?
Is it not strange to see that these things are tolerated almost everywhere?
And if any man reprove another,
or plead with him to forsake such things and come seriously to
serve and worship God in His own pure Spirit,
such a one is quickly made a prey, and often subjected to cruel mocking or suffering.
Does this bear any relation to Christianity?
Do these things look anything like the churches of the primitive Christians?
Surely not at all.

I shall first cite a few Scripture testimonies,
and then see whether those who obey them can allow these aforementioned things.
The apostle commands us, that "`whether we eat or drink, or whatever we do,
we do it all to the glory of God.`"
But I judge none will be so impudent as to affirm that, in the use of these sports,
games, and recreations, God is thereby glorified.
For experience abundantly proves that in the practice of these things,
men mind nothing less than the glory of God,
and nothing more than the satisfaction of their own carnal lusts, wills, and appetites.

Elsewhere the apostle admonishes: "`Because the time is short,
they that buy should buy as though they possessed not.
And they that use this world, as not abusing it,`" etc.
But how can any be found in obedience to this precept, who plead for the use of gaming,
recreation, and entertainment?
These, it seems, must think their time here very long;
for rather than employing time for the care of
their souls or the necessities of their bodies,
they invent games and sports to pass it away,
as though they lacked the ability to serve their Creator, or be useful to His creation.

The apostle Peter desires us "`to pass the time of our sojourning here in fear.`"
But will any say that those who are given to parties, comedies, games, and plays,
do indeed mind this scripture in their use of these things,
where little is seen but lightness, vanity, fleshly freedom, and obscenity?
Do not such things hinder men from the fear of God,
and from all serious and weighty considerations?
There is no duty more frequently commanded in Scripture,
nor more incumbent upon Christians, than the fear of the Lord,
to stand in awe before Him, and to walk as in His presence.
But if those who are given to entertainment and
recreation will speak from their consciences,
they must (I doubt not) experientially declare that all
godly fear is forgotten in their pleasure and mirth.
And if the Lord, by his Light, secretly touch them,
or put them in mind of the vanity of their way, they strive to shut Him out,
using their entertainment as a tool to put away their troublesome Guest,
and thus make merry over the Just One, whom they have slain and crucified in themselves.

But further, if Christ is to be heeded,
who said "`the good man out of the good treasure of the heart brings forth good things;
and an evil man out of the evil treasure brings forth evil
things;`" and that for "`every idle word we shall give an
account in the day of judgment,`" it may be easily seen from
what sort of treasure these amusing inventions come.
For how many idle words do these things necessarily produce?
Yes, what are comedies and plays but a medley of false and idle words?
Now, you who believe your soul to be immortal,
and that there will be a day of judgment in
which these words of Christ will be accomplished,
answer me:
How will you give account in that great and terrible day for
all the idle words that are necessarily employed in gaming,
plays, parties, and other forms of recreation and amusement?
And yet, many who are accounted Christians not only allow these things,
but take up their whole time in them!
Alas, it cannot be denied that such Christians as these make
the care of their souls their least important business,
provoking the Lord to withhold His blessing,
while they pass the time of their pilgrimage in chains of darkness, drowned in lust,
sensuality, and worldly pleasure, without any sense or God's fear,
or of their own soul's salvation.

+++[++++++[+++_s9]]Objection:
But some object that men's spirits could not subsist if they
were always intent upon serious and spiritual matters,
and that therefore there is need of some amusement and
recreation to ease and refresh the mind,
so that it may more vigorously apply itself to spiritual things.

Answer: We freely confess that, so long as we are clothed in this tabernacle of clay,
it not possible to maintain a perfect attention and engagement in heavenly things.
Nevertheless, this will not allow us at any time to disregard our souls' chief concern,
forget the fear of God,
and actively engage in those things which grieve the
Spirit and strive against the operation of His grace.

Now there are necessary things, in which all are involved,
that deal with the care and preservation of the outward man,
and which allow for relaxation of the mind from more serious spiritual duties.
And these things can indeed be performed in the blessing of God;
for as the mind becomes leavened with His love, and with a sense of His presence,
the soul carries with it that divine influence and spiritual sense,
whereby even such acts as eating, drinking, sleeping, working, are done unto the Lord,
pleasing and serving Him, and answering our end in the creation.
But the wicked and profane, having not come to this place,
are cursed in whatsoever they do, so that their "`plowing, as well as praying,
is sin!`" (Prov. 21:4, Ps. 107:9)

Now, if any will plead that, for the relaxation of mind,
there may be freedom allowed beyond the things which are of
absolute need to the sustenance of the outward man;
I will not much contend against it, provided these things be not wholly superfluous,
and that in their nature and tendency they do not lead the mind into lust, vanity,
and carelessness.
There are other innocent diversions which may
sufficiently serve for relaxation to the mind,
such as for friends to visit one another, or to read history, to follow after gardening,
and various other things of this nature.
But in all these things we are not so to forget
the Lord (in whom we both live and are moved,
Acts 17:28) as not to have always some secret attention to Him,
with a sense of His fear and presence,
which frequently exerts itself in the midst of our activities
by some longings and breathings to the God of our life.

But again, I believe it is apparent to all serious persons that gaming, plays, comedies,
amusements,
and most common forms of entertainment and recreation
do but stifle the soul's longings after God,
and serve only to draw men from His fear, making them forget heaven, death, and judgment,
while fostering lust, vanity, and carelessness.
