[quote.epigraph, , Acts 24:14]
____
After the way which they call heresy, so worship I the God of my fathers;
believing all things which are written in the law and the prophets.
____

[quote.epigraph, , Titus 2:11-14]
____
For the grace of God that bringeth salvation hath appeared to all men,
teaching us that denying ungodliness and worldly lusts, we should live soberly,
righteously, and godly in this present world,
looking for that blessed hope and glorious appearing
of the great God and our Saviour Jesus Christ.
Who gave himself for us, that he might redeem us from all iniquity,
and purify unto himself a peculiar people, zealous of good works.
____

[quote.epigraph, , 1 Thess. 5:21]
____
Prove all things; hold fast that which is good.
____

== Editor`'s Introduction

Robert Barclay (1648-1690) wrote his classic exposition and defense of Quakerism
// lint-disable invalid-characters "æ"
in Latin and published it in 1676 as Theologiæ Vere Christianæ Apologia.
He then translated his own book into English.
The Apology has since been reprinted over 60 times
and translated into several other languages.

Barclay`'s education enabled him to understand academic theology.
Most early Quaker publicists used a distinctive Quaker vocabulary
which was often misunderstood by educated theologians,
whom the Quakers misunderstood in turn.
Thus in early debate literature,
Friends and their opponents often talked past each other,
taking the same words in different senses.
Barclay bridges this gap,
defending Quaker usage while clearly explaining it for the
benefit of those who were accustomed to a different vocabulary.

This is not to say that the theological differences between
Quakers and other sects were mere differences of vocabulary.
There were doctrinal differences of substance;
and most of Barclay`'s effort is directed at defending
Quaker doctrine and showing its superiority,
in logic and faithfulness to Scripture, to competing doctrines of his time,
especially those of Calvinism.
His ability to do this effectively is greatly enhanced by
his having a good understanding of the competing theologies,
as well as by his ability to surmount the verbal barrier.

The Apology was frequently reprinted throughout the 18th and 19th centuries.
Suddenly, early in the 20th century, the printings ceased.
The last printing of the full text, so far as we have been able to learn,
was in 1908 in Philadelphia.^
footnote:[Since then, a few very abridged versions have been published,
and a book called Barclay`'s Apology in Modern English, edited by Dean Freiday.
The latter leaves out a great deal of what Barclay wrote
and contains numerous errors in rendering Barclay`'s meaning:
a fuller critique of it can be found in an Appendix to this volume.]

In conversations among Peter Sippel, Edsel Burdge, and Friends at Glenside Meeting (PA),
it was agreed that this important Quaker classic should again be made available.
An electronic text produced with a scanner from a 1789 edition
was provided to Peter Sippel by Raymond Ayoub.
Edsel Burdge offered to compare this text with a 1690 edition of
Truth Triumphant (a collection of Barclay`'s works).
Enough differences in wording were found in the first several pages to convince
us that one edition of the Apology was not necessarily the same as another.
Desiring to stick to Barclay`'s own words we decided
to use the earliest English language edition (1678),
which is believed to have been printed in Aberdeen, Scotland,
though the volume does not say so.
A second, apparently later 1678 edition, believed to have been printed in London,
was also consulted in cases of obscurity in the microfilm of the Aberdeen text.

Peter Sippel proofread the scanned text against the Aberdeen edition, corrected it,
and e-mailed it to Licia Kuenning, who formatted it, made further corrections,
and printed it out: Charlotte Kuenning then proofread the printout twice, line by line,
against the Aberdeen edition,
also checking the Scripture citations for accuracy in chapter+++/+++verse numbers,
since these are often misprinted in old Quaker books.
Larry Kuenning checked Barclay`'s Greek,
Hebrew and Latin words and helped to locate Scripture
texts and to identify the occasional English archaism.
Licia then implemented their corrections and re-proofread
the resulting document on the screen.

The only things we have modernized are spelling, capitalization, italicization,
punctuation.
and the names of authors cited.
Barclay`'s English is modern English.
A brief glossary is provided on page vii of words that have changed their meaning;
the very few words that have dropped out of use are footnoted at places in the text.

Not all of Barclay`'s italics have been preserved.
He used italics more than would be normal in a modern book.
He also used italics for quotations (direct and indirect).
We have substituted quotation marks in these cases,
although this has the disadvantage that their use in this volume does not always
conform to modern conventions for the use of quotation marks (i.e.,
they appear around passages that are not precise direct quotes).
There does not seem to have been any exact equivalent, in 1678, to modern quotation marks.

This volume contains two types of footnotes:
the marginal notes of the Aberdeen edition (marked by raised letters, a, b, etc.),
and our own editorial notes (marked with raised numbers, 1, 2,
etc.) defining archaic words and noting passages that later
editors significantly altered from the first edition.

+++[+++In the print edition the editorial notes are marked with asterisks, +++*+++,
and the lettered notes begin with a on each page instead of continuing
in a single sequence throughout each chapter as they do here.]

The indexes are Barclay`'s,
but we have changed his Latinized author names to
the forms they are better known by today,
and realphabetized accordingly.

In addition to the persons above named,
thanks are due to the librarians at Westminster Theological Seminary
(Glenside, PA) who provided us with microfilms of the two 1678 editions,
and to the many Friends in Quaker e-mail discussion groups,
especially those known as Quaker-G and Q-Text,
for their encouragement as the work progressed.

A few months after printing the Apology we placed
it online at the Quaker Heritage Press website,
www.qhpress.org, where many other historic Quaker writings can be found,
including Barclay`'s earlier work, A Catechism and Confession of Faith.

=== Comments on the Concept of "`Modern English`"

Linguists distinguish three periods in the history of the English language:
Old English or Anglo Saxon, used c450-c1150; Middle English, used c1150-1475;
and Modern English,
used since 1475. Modern English is generally within the reach of today`'s readers.
Middle English, such as that written by Chaucer,
usually requires some special training to be fully understood; and Old English,
such as that in Beowulf, is a foreign language to the large majority of us.

Anything written by a Quaker is well within the Modern period.
The difficulties of some early Quaker writings are due less to
archaism in the language than to the fact that the ideas and controversies
of their time are not widely understood today.
Added to this is the fact that early Quakers had an idiosyncratic vocabulary,
not all of which has survived in the Society of Friends.
The theological vocabulary of other churches, being more widely used,
has survived better; which is one reason why Barclay,
who knew this vocabulary and wrote for those who used it,
is one of the easiest of 17th-century Quaker writers for modern people to read.
Another reason for his understandability is the logical structure of his thought.

Being of the generation whose early religious teachers used the King James Bible,
I find the English of the 17th century as much a part of my native
language as anything I can read on the Internet (an understatement).
To those who think that 17th-century English is difficult,
I can only urge that they read it until it isn`'t difficult any more.^
footnote:[Do not be afraid of the old-fashioned verb endings, +++-+++eth and +++-+++est.
The suffix +++-+++eth is third-person singular, and +++-+++est is second-person singular:
but you don`'t even need to know that.
You can just ignore these endings, as they do not change the meaning of the verbs.]
Not to do so is to incur a great loss of our cultural heritage,
for not only were the major documents of more than one religious
tradition written in the 17th century but the phraseology of the
King James Version is all over the literature of four centuries,
not only in religious works but also in poetry, legal documents,
expressions of philosophical or political ideas, and even romantic fiction.

When well-intentioned editors try to modernize old writings,
thinking to make them more accessible to contemporary readers,
there can be some regrettable consequences.
One of these is to reinforce the idea that the original texts are too difficult.
Since the original texts will never all be modernized the effect can be to make
a great many other books less accessible by scaring people away from them.
An even more serious hazard results from the fact that often it is the ideas,
rather than the words themselves, that have become difficult.
The modernizer may unwittingly alter the ideas in trying to modernize the language.
This has in fact happened in every case that I know of where a
modern editor has tried to paraphrase an early Quaker text.

When readers of an old text find something in it that is obscure to them,
they may realize that they don`'t understand it, look into it,
and thereby increase their historical knowledge.
But readers of a modernized version that seems smooth and clear have no way of
knowing which passages are not accurate representations of the author`'s thought.
Not knowing where the problems are, they don`'t investigate them,
and instead absorb historical errors.

This is in no way to disparage modern English translations of the Bible.
The Bible was not written in English:
those who don`'t know Greek and Hebrew must read it in some translation,
and modern translations may be best for understanding what the authors said,
especially when the translators take into account advances in textual
scholarship and in the study of ancient Greek and Hebrew.
But the King James Version should be read as well--not
because it is needed for understanding the Bible,
but because it is needed for understanding the many
writers of English literature who quoted it.

English was Robert Barclay`'s native language.
He knew how to say what he meant in English,
and his own words are still the best words for understanding him.

Licia Kuenning
Quaker Heritage Press editor

[.asterism]
'''

Glossary of some words whose most common meaning today
is different from their meaning at some places in the Apology.
Some of these words are, at other places, used in their present-day sense:
this must be determined from context:

accident:: trait

acted (as a participle):: motivated, moved

admirable:: strange, astonishing

answer:: correspond, agree

comprehend:: include

day:: period of time (not necessarily a calendar day)

divine+++(+++s) (n):: theologian+++(+++s)

divinity:: theology

doctor:: highly educated person

elementary:: physical

experimentally:: by experience

figure (n):: figurative representation, symbol

formally:: really (only in certain technical theological contexts)

immediate:: without mediation

juggling:: trickery

lawful:: possible to be done without sin

let (v):: prevent

let (n):: obstacle

outside:: superficial

outward:: visible, material

own:: acknowledge, approve

part+++(+++s):: skill+++(+++s)

particular (n):: an individual

pretend:: claim

probation:: proof

professor:: one who claims to be religious

sometimes:: at one time in the past

talent:: an ancient unit of money

typify:: prefigure, symbolize

use (v):: to practice habitually or customarily

vain:: useless

want:: lack
