[short="Unto Charles II, King of Great Britain"]
== Unto Charles the Second / King of Great Britain / and the Dominions Thereunto Belonging

[.section-author]
Robert Barclay

[.heading-continuation-blurb]
A Servant of Jesus Christ, called of God to the dispensation of the Gospel now again revealed;
and, after a long and dark night of apostasy,
commanded to be preached to all nations, wisheth health and salvation.

As the condition of kings and princes puts them in a station more obvious
to the view and observation of the world than that of other men,
of whom, as Cicero observes, neither any word or action can be obscure;
so are those kings,
during whose appearance upon the stage of this world it pleaseth the great King of kings
singularly to make known unto men the wonderful steps of his unsearchable providence,
more signally observed and their lives and actions more
diligently remarked and inquired into by posterity;
especially if those things be such as not only relate to the outward transactions
of this world but also are signalized by the manifestation or revelation
of the knowledge of God in matters spiritual and religious.
These are the things that rendered the lives of Cyrus, Augustus Caesar,
and Constantine the Great in former time,
and of Charles the Fifth and some other modern princes in these last ages,
so considerable.

But among all these transactions which it hath pleased God to permit for
the glory of his power and the manifestation of his wisdom and providence,
no age furnisheth us with things so strange and marvelous,
whether with respect to matters civil or religious,
as these that have fallen out within the compass of thy time; who,
though thou be not yet arrived at the fiftieth year of thy age,
hast yet been a witness of stranger things than many ages before produced.
So that whether we respect those various troubles wherein thou
foundest thyself engaged while scarce got out of thy infancy;
the many different afflictions wherewith men of thy circumstances are often unacquainted;
the strange and unparalleled fortune that befell thy father;
thy own narrow escape and banishment following thereupon,
with the great improbability of thy ever returning (at least
without very much pains and tedious combattings);
or finally the incapacity thou wert under to accomplish such a design;
considering the strength of those who had possessed themselves
of thy throne and the terror they had inflicted upon foreign states;
and yet that after all this thou shouldst be restored without stroke of sword,
the help or assistance of foreign states, or the contrivance and work of human policy;
all these do sufficiently declare that it is the Lord`'s doing, which,
as it is marvelous in our eyes,
so it will justly be a matter of wonder and astonishment
to generations to come and may sufficiently serve,
if rightly observed,
to confute and confound that atheism wherewith this age doth so much abound.

As the vindication of the liberty of conscience (which thy father,
by giving way to the importunate clamours of the clergy,
the answering and fulfilling of whose unrighteous wills
has often proved hurtful and pernicious to princes,
sought in some part to restrain) was a great occasion of these troubles and revolutions;
so the pretense of conscience was that which carried
it on and brought it to that pitch it came to.
And though no doubt some that were engaged in that work designed good things,
at least in the beginning, albeit always wrong in the manner they took to accomplish it,
viz. by carnal weapons;
yet so soon as they had tasted the sweet of the possessions of them they had turned out,
they quickly began to do those things themselves for which they had accused others.
For their hands were found full of oppression,
and "`they hated the reproofs of instruction, which is the way of life`";
and they evilly entreated the messengers of the Lord and caused
to beat and imprison his prophets and persecuted his people,
whom he had called and gathered out from among them,
whom he had made to "`beat their swords into plowshares and their
spears into pruning-hooks,`" and not to learn carnal war any more:
but he raised them up and armed them with spiritual weapons,
even with his own Spirit and power,
whereby they testified in the streets and highways
and public markets and synagogues against the pride,
vanity, lusts, and hypocrisy of that generation who were righteous in their own eyes,
though often cruelly entreated therefor;
and they faithfully prophesied and foretold them
of their judgment and downfall which came upon them,
as by several warnings and epistles delivered to Oliver and Richard Cromwell,
the Parliament, and other then powers yet upon record, doth appear.

And after it pleased God to restore thee, what oppressions,
what banishments and evil entreatings they have met with by men
pretending thy authority and cloaking their mischief with thy name,
is known to most men in this island; especially in England,
where there is scarce a prison that hath not been filled
with them nor a judge before whom they not have been haled;
though they could never yet be found guilty of anything that might deserve that usage.
Therefore the sense of their innocency did no doubt greatly contribute to move thee,
three years ago, to cause some hundreds of them to be set at liberty:
for indeed their sufferings are singular,
and obviously distinguishable from all the rest of
such as live under thee in these two respects.

First,
in that among all the plots contrived by others against thee since thy return into Britain,
there never was any, owned of that people, found or known to be guilty,
though many of them have been taken and imprisoned upon such kind of jealousies,
but were always found innocent and harmless as became the followers of Christ;
not coveting after nor contending for the kingdoms of this world,
but "`subject to every ordinance of man for conscience sake.`"

Secondly,
in that in the hottest times of persecution and the most
violent prosecutions of those laws made against meetings,
being clothed with innocency,
they have boldly stood to their testimony for God without
creeping into holes or corners or once hiding themselves,
as all other dissenters have done; but daily met, according to their custom,
in the public places appointed for that end;
so that none of thy officers can say of them that they have surprised them in a corner,
overtaken them in a private conventicle,
or caught them lurking in their secret chambers;
nor needed they to send out spies to get them,
whom they were sure daily to find in their open assemblies,
testifying for God and his Truth.
By which those that have an eye to see may observe their Christian patience and courage,
constancy and suffering, joined in one,
more than in any other people that differ from them or oppose them.
And yet in the midst of those troubles thou canst bear witness that as on the
one part they never sought to detract from thee or to render thee and thy government
odious to the people by nameless and scandalous pamphlets and libels;
so on the other hand they have not spared to admonish, exhort,
and reprove thee and have faithfully discharged their
consciences towards thee without flattering words,
as ever the true prophets in ancient times used to do to those kings and
princes under whose power violence and oppression was acted.

And albeit it is evident by experience to be most agreeable both to divine Truth
and human policy to allow everyone to serve God according to their consciences,
nevertheless those other sects,
who for the most part durst not peep out in the times of persecution,
while these innocent people stood bold and faithful,
do now combine in a joint confederacy (notwithstanding all the former
janglings and contention among themselves) to render us odious;
seeking unjustly to wrest our doctrine and words as if they
were inconsistent both with Christianity and civil society;
so that to effectuate this their work of malice against us they have not been ashamed
to take the help and commend the labours of some invidious Socinians against us.
So do Herod and Pontius Pilate agree to crucify Christ.

But our practice,
known to thee by good experience to be more consistent with Christianity and civil society
and the peace and welfare of this island than that of those who thus accuse us,
doth sufficiently guard us against this calumny that we may indeed appeal to
the testimony of thy conscience as a witness for us in the face of the nations.

These things moved me to present the world with a brief but true account
of this people`'s principles in some short theological propositions;
which, according to the will of God,
proving successful beyond my expectation to the satisfaction of several and to
the moving in many a desire of being further informed concerning us,
as being everywhere evil spoken of;
and likewise meeting with public opposition by some as such will always
do so long as the devil "`rules in the children of disobedience`";
I was thereby further engaged in the liberty of the Lord to present
to the world this Apology of the Truth held by those people:
which, because of thy interest in them and theirs in thee,
as having first appeared and mostly increased in these nations under thy rule,
I make bold to present unto thee.

Thou knowest and hast experienced their faithfulness towards their God,
their patience in suffering, their peaceableness towards the king, their honesty,
plainness and integrity in their faithful warnings and testimonies to thee;
and if thou wilt allow thyself so much time as to read this thou
mayest find how consonant their principles are both to Scripture,
Truth, and right reason.
The simplicity of their behaviour,
the generality of their condition as being poor men and illiterate,
the manner of their procedure being without the wisdom and policy of this world,
hath made many conclude them fools and madmen and
neglect them as not being capable of reason.
But though it be to them as their crown thus to be esteemed
of the wise and the great and learned of this world,
and though they rejoice to be accounted fools for Christ`'s sake, yet of late some,
even such who in the world`'s account are esteemed both wise and learned,
begin to judge otherwise of them,
and find that they hold forth things very agreeable both to Scripture, reason,
and true learning.

As it is inconsistent with the Truth I bear,
so it is far from me to use this epistle as an engine to flatter thee,
the usual design of such works;
and therefore I can neither dedicate it to thee nor crave thy patronage,
as if thereby I might have more confidence to present
it to the world or be more hopeful of its success.
To God alone I owe what I have, and that more immediately in matters spiritual;
and therefore to him alone, and to the service of his Truth,
I dedicate whatever work he brings forth in me;
to whom only the praise and honor appertain,
whose Truth needs not the patronage of worldly princes,
his arm and power being that alone by which it is propagated, established, and confirmed.
But I found it upon my spirit to take occasion to present this book unto thee,
that as thou hast been often warned by several of
that people who are inhabitants of England,
so thou mayest not want a seasonable advertisement
from a member of thy ancient kingdom of Scotland,
and that thou mayest know (which I hope thou wilt have no reason to be troubled
at) that God is raising up and increasing that people in that nation.
And the nations shall also hereby know that the Truth we
profess is not a work of darkness nor propagated by stealth,
and that we are "`not ashamed of the Gospel of Christ`"
because we know it to be "`the power of God unto salvation`";
and that we are no ways so inconsistent with government,
nor such disturbers of the peace, as our enemies, by traducing us,
have sought to make the world believe we are:
for what to thee I dare appeal as a witness of our peaceableness and Christian patience.

Generations to come shall not more admire that singular step of Divine Providence,
in restoring thee to thy throne without outward bloodshed,
than they shall admire the increase and progress of this Truth
without all outward help and against so great opposition,
which shall be none of the least things rendering thy memory remarkable.
God hath done great things for thee;
he hath sufficiently shown thee that it is by him princes rule,
and that he can pull down and set up at his pleasure.
He hath often faithfully warned thee by his servants,
since he restored thee to thy royal dignity,
that thy heart might not wax wanton against him to
forget his mercies and providence towards thee,
whereby he might permit thee to be soothed up and lulled
asleep in thy sins by the flattering of court-parasites,
who by their fawning are the ruin of many princes.

There is no king in the world,
who can so experimentally testify of God`'s providence and goodness;
neither is there any who rules so many free people, so many true Christians:
which thing renders thy government more honorable, thyself more considerable,
than the accession of many nations filled with slavish and superstitious souls.

Thou hast tasted of prosperity and adversity;
thou knowest what it is to be banished thy native country,
to be overruled as well as to rule and sit upon the throne; and being oppressed,
thou hast reason to know how hateful the oppressor is both to God and man.
If after all these warnings and advertisements thou
dost not turn unto the Lord with all thy heart,
but forget him who remembered thee in thy distress
and give up thyself to follow lust and vanity,
surely great will be thy condemnation.

Against which snare,
as well as the temptation of those that may or do feed thee and prompt thee to evil,
the most excellent and prevalent remedy will be to apply thyself to that Light of Christ,
which shineth in thy conscience,
which neither can nor will flatter thee nor suffer thee to be at ease in thy sins,
but doth and will deal plainly and faithfully with thee
as those that are followers thereof have also done.

God Almighty, who hath so signally hitherto visited thee with his love,
so touch and reach thy heart, ere the day of thy visitation be expired,
that thou mayest effectually turn to him so as to
improve thy place and station for his name.
So wisheth, so prayeth,

[.signed-section-closing]
Thy faithful friend and subject,

[.signed-section-signature]
Robert Barclay

[.signed-section-context-close]
From Ury, the place of my pilgrimage, in my native country of Scotland,
the 25th of the month called November, in the year 1675.
