[short="Unto the Friendly Reader"]
== R.B. Unto the Friendly Reader wisheth Salvation

Forasmuch as that which above all things I propose
to myself is to declare and defend the Truth,
for the service whereof I have given up and devoted myself and all that is mine;
therefore there is nothing which for its sake, by the help and assistance of God,
I may not attempt.
And in this confidence I did some time ago publish certain propositions of divinity,
comprehending briefly the chief principles and doctrines of Truth,
which appearing not unprofitable to some and being
beyond my expectations well received both by foreigners,
though differing from us (albeit also opposed by some envious ones) did so far prevail,
as in some part to remove that false and monstrous opinion which lying fame and the
malice of our adversaries had implanted in the minds of some concerning us and our doctrines.
In this respect it seemed to me not fit to spare my pains and labour.

Therefore,
being acted by the same measure of the Divine Spirit and the like
design of propagating the Truth by which I published the propositions,
I judged it meet to explain them somewhat more largely
at this time and defend them by certain arguments.

Perhaps my method of writing may seem not only different, but even contrary,
to that which is commonly used by the men called divines, with which I am not concerned;
for that I confess myself to be not only no imitator and admirer
of the schoolmen but an opposer and despiser of them as such,
by whose labour I judge the Christian religion to be so far from being bettered,
that it is rather destroyed.
Neither have I sought to accommodate this my work to itching ears,
who desire rather to comprehend in their head the sublime
notions of Truth than to embrace it in their heart.
For what I have written comes more from my heart than from my head;
what I have heard with the ears of my soul and seen with my inward
eyes and my hands have handled of the Word of Life,
and what hath been inwardly manifested to me of the things of God, that do I declare;
not so much minding the eloquence and excellency of speech as desiring
to demonstrate the efficacy and operation of Truth;
and if I err sometime in the former it is no great matter;
for I act not here the grammarian or the orator, but the Christian;
and therefore in this have followed the certain rule of the Divine Light,
and of the Holy Scriptures.

And to make an end; what I have written is written not to feed the wisdom and knowledge,
or rather vain pride of this world, but to starve and oppose it,
as the little preface prefixed to the propositions doth show; which,
with the title of them, is as followeth.
