== THE FIRST PROPOSITION

Seeing the height of all happiness is placed in the true knowledge of God;
"`This is life eternal, to know the true God,
and Jesus Christ whom thou hast sent`";^
footnote:[John 17:3.]
the true and right understanding of this foundation and ground of knowledge is
that which is most necessary to be known and believed in the first place.

He that desireth to acquire any art or science seeketh first
those means by which that art or science is obtained.
If we ought to do so in things natural and earthly, how much more then in spiritual?
In this affair then should our inquiry be the more diligent,
because he that errs in the entrance is not so easily reduced again into the right way;
he that misseth his road from the beginning of his journey,
and is deceived in his first marks, at his first setting forth,
the greater his mistake is, the more difficult will be his entrance into the right way.

Thus when a man first proposeth to himself the knowledge of God,
from a sense of his own unworthiness, and from the great weariness of his mind,
occasioned by the secret checks of his conscience, and the tender,
yet real glances of God`'s Light upon his heart;
the earnest desires he has to be redeemed from his present trouble,
and the fervent breathings he has to be eased of his disordered passions and lusts,
and to find quietness and peace in the certain knowledge of God,
and in the assurance of his love and good-will towards him, makes his heart tender,
and ready to receive any impression;
and so (not having then a distinct discerning) through forwardness,
embraceth any thing that brings present ease.
If either through the reverence he bears to certain persons,
or from the secret inclination to what doth comply with his natural disposition,
he fall upon any principles or means, by which he apprehends he may come to know God,
and so doth center himself, it will be hard to remove him thence again,
how wrong so ever they may be: for the first anguish being over, he becomes more hardy;
and the enemy being near, creates a false peace, and a certain confidence,
which is strengthened by the mind`'s unwillingness to enter again into new doubtfulness,
or the former anxiety of a search.

This is sufficiently verified in the example of the Pharisees and Jewish doctors,
who most of all resisted Christ, disdaining to be esteemed ignorant;
for this vain opinion they had of their knowledge hindered them from the true knowledge;
and the mean people, who were not so much preoccupied with former principles,
nor conceited of their own knowledge, did easily believe.
Wherefore the Pharisees upbraid them, saying,
"`Have any of the rulers or Pharisees believed on him?
But this people, which know not the law, are accursed.`"^
footnote:[John 7:48-49.]
This is also abundantly proved by the experience of all such,
as being secretly touched with the call of God`'s grace unto them,
do apply themselves unto false teachers; where the remedy proves worse than the disease;
because instead of knowing God, or the things relating to their salvation aright,
they drink in wrong opinions of him; from which it is harder to be disentangled,
than while the soul remains a blank, or tabula rasa.
For they that conceit themselves wise,
are worse to deal with than they that are sensible of their ignorance.
Nor hath it been less the device of the devil, the great enemy of mankind,
to persuade men into wrong notions of God,
than to keep them altogether from acknowledging him; the latter taking with few,
because odious; but the other having been the constant ruin of the world:
for there hath scarce been a nation found,
but hath had some notions or other of religion; so that not from their denying any Deity,
but from their mistakes and misapprehensions of it,
hath proceeded all the idolatry and superstition of the world; yea,
hence even atheism itself hath proceeded:
for these many and various opinions of God and religion,
being so much mixed with the guessings and uncertain judgments of men,
have begotten in many the opinion that there is no God at all.
This, and much more that might be said,
may show how dangerous it is to miss in this first step:
"`All that come not in by the door, are accounted as thieves and robbers.`"

Again, how needful and desirable that knowledge is, which brings life eternal,
Epictetus showeth, saying excellently well, cap.
38, RESTORE-GREEK, etc. Know, that the main foundation of piety is this, To have
RESTORE-GREEK, right opinions and apprehensions of God.

This therefore I judged necessary, as a first principle, in the first place to affirm;
and I suppose will not need much further explanation nor defence,
as being generally acknowledged by all (and in these things that
are without controversy I love to be brief) as that which will
easily commend itself to every man`'s reason and conscience;
and therefore I shall proceed to the next proposition; which,
though it be nothing less certain, yet by the malice of Satan, and the ignorance of many,
comes far more under debate.
