== THE SECOND PROPOSITION

Of Immediate Revelation

Seeing "`no man knoweth the Father but the Son, and he to whom the Son revealeth him`";
and seeing the "`revelation of the Son is in and by the Spirit`" (Matt. 11:27);
therefore the testimony of the Spirit is that alone
by which the true knowledge of God hath been,
is, and can be only revealed; who as, by the moving of his own Spirit,
he disposed the chaos of this world into that wonderful
order wherein it was in the beginning,
and created man a living soul, to rule and govern it, so,
by the revelation of the same Spirit,
he hath manifested himself all along unto the sons of men, both patriarchs, prophets,
and apostles; which revelations of God by the Spirit,
whether by outward voices and appearances, dreams,
or inward objective manifestations in the heart,
were of old the formal object of their faith, and remain yet so to be,
since the object of the saints`' faith is the same in all ages,
though held forth under divers administrations.
Moreover, these divine inward revelations,
which we make absolutely necessary for the building up of true faith,
neither do nor can ever contradict the outward testimony of the Scriptures,
or right and sound reason.
Yet from hence it will not follow,
that the divine revelations are to be subjected to the test,
either of the outward testimony of the Scriptures, or of the natural reason of man,
as to a more noble or certain rule and touchstone;
for this divine revelation and inward illumination,
is that which is evident and clear of itself, forcing, by its own evidence and clearness,
the well-disposed understanding to assent, irresistibly moving the same thereunto,
even as the common principles of natural truths do
move and incline the mind to a natural assent:
as, that the whole is greater than its part,
that two contradictories can neither be both true, nor both false.

// lint-disable invalid-characters "§"
§I. It is very probable,
that many carnal and natural Christians will oppose this proposition;
who being wholly unacquainted with the movings and
actings of God`'s Spirit upon their hearts,
judge the same nothing necessary; and some are apt to flout at it as ridiculous; yea,
to that height are the generality of Christians apostatised and degenerated,
that though there be not anything more plainly asserted, more seriously recommended,
nor more certainly attested to, in all the writings of the holy Scriptures,
yet nothing is less minded and more rejected by all sorts of Christians,
than immediate and divine revelation;
insomuch that once to lay claim to it is matter of reproach.
Whereas of old none were ever judged Christians,
but such as "`had the Spirit of Christ`" (Rom. 8:9).
But now many do boldly call themselves Christians,
who make no difficulty of confessing they are without it,
and laugh at such as say they have it.
Of old they were accounted "`the sons of God, who were led by the Spirit of God`" (ibid. v. 14).
But now many aver themselves sons of God, who know nothing of this leader;
and he that affirms himself so led, is, by the pretended orthodox of this age,
presently proclaimed a heretic.
The reason hereof is very manifest, viz.: Because many in these days,
under the name of Christians, do experimentally find,
that they are not acted nor led by God`'s Spirit; yea, many great doctors, divines,
teachers,
and bishops of Christianity (commonly so called)
have wholly shut their ears from hearing,
and their eyes from seeing this inward guide, and so are become strangers unto it;
whence they are, by their own experience, brought to this strait,
either to confess that they are as yet ignorant of God,
and have only the shadow of knowledge, and not the true knowledge of him,
or that this knowledge is acquired without immediate revelation.

For the better understanding then of this proposition,
we do distinguish betwixt the certain knowledge of God, and the uncertain;
betwixt the spiritual knowledge, and the literal; the saving heart-knowledge,
and the soaring, airy head-knowledge.
The last, we confess, may be divers ways obtained; but the first,
by no other way than the inward immediate manifestation and revelation of God`'s Spirit,
shining in and upon the heart, enlightening and opening the understanding.

// lint-disable invalid-characters "§"
§II. Having then proposed to myself, in these propositions,
to affirm those things which relate to the true and effectual
knowledge which brings life eternal with it;
therefore I have affirmed, and that truly, that this knowledge is no otherways attained,
and that none have any true ground to believe they have attained it,
who have it not by this revelation of God`'s Spirit.

The certainty of which truth is such,
that it hath been acknowledged by some of the most refined and
famous of all sorts of professors of Christianity in all ages;
who being truly upright-hearted,
and earnest seekers of the Lord (however stated under the disadvantages
and epidemical errors of their several sects or ages) the true
seed in them hath been answered by God`'s love,
who hath had regard to the good, and hath had of his elect ones among all;
who finding a distaste and disgust in all other outward means,
even in the very principles and precepts more particularly
relative to their own forms and societies,
have at last concluded, with one voice,
that there was no true knowledge of God but that
which is revealed inwardly by his own Spirit.
Whereof take these following testimonies of the ancients:

1+++.+++ "`It is the inward master (saith Augustine) that teacheth, it is Christ that teacheth,
it is inspiration that teacheth: where this inspiration and unction is wanting,
it is in vain that words from without are beaten in.`" And thereafter:
"`For he that created us, and redeemed us, and called us by faith,
and dwelleth in us by his Spirit, unless he speaketh unto us inwardly,
it is needless for us to cry out.`"^
footnote:[Augustine, ex Tract. Epist. John 3.]

2+++.+++ "`There is a difference`" (saith Clement of Alexandria)
"`betwixt that which anyone saith of the Truth,
and that which the Truth itself, interpreting itself, saith.
A conjecture of truth differeth from the Truth itself;
a similitude of a thing differeth from the thing itself;
it is one thing that is acquired by exercise and discipline; and another thing,
which by power and faith.`"^
footnote:[Lib. 1. Strom.]
Lastly, the same Clement saith, "`Truth is neither hard to be arrived at,
nor is it impossible to apprehend it; for it is most nigh unto us, even in our houses,
as the most wise Moses hath insinuated.`"^
footnote:[Paedag.]

3+++.+++ "`How is it`" (saith Tertullian) "`that since the devil always worketh,
and stirreth up the mind to iniquity, that the work of God should either cease,
or desist to act?
Since for this end the Lord did send the Comforter,
that because human weakness could not at once bear all things,
knowledge might be by little and little directed, formed, and brought to perfection,
by the holy Spirit, that vicar of the Lord.
'`I have many things yet,`' saith he, '`to speak unto you, but ye cannot as yet bear them;
but when that Spirit of Truth shall come, he shall lead you into all Truth,
and shall teach you these things that are to come.`'
But of his work we have spoken above.
What is then the administration of the Comforter, but that discipline be derived,
and the Scriptures revealed, etc.`"^
footnote:[Lib. de veland. virginibus cap. 1.]

4+++.+++ "`The law`" (saith Jerome) "`is spiritual,
and there is need of a revelation to understand it.`" And in his Epistle 150, to Hedibia,
Quest.
11, he saith, "`The whole Epistle to the Romans needs an interpretation,
it being involved in so great obscurities,
that for the understanding thereof we need the help of the holy Spirit,
who through the apostle dictated it.`"^
footnote:[Epist. Paulin. 103.]

5+++.+++ "`So great things`" (saith Athanasius) "`doth our Saviour daily: he draws unto piety,
persuades unto virtue, teaches immortality, excites to the desire of heavenly things,
reveals knowledge from the Father, inspires power against death,
and shows himself unto everyone.`"^
footnote:[De incarnatione verbi Dei.]

6+++.+++ Gregory the Great, upon these words, "`He shall teach you all things,`" saith,
"`that unless the same Spirit sit upon the heart of the hearer,
in vain is the discourse of the doctor;
let no man then ascribe unto the man that teacheth,
what he understands from the mouth of him that speaketh;
for unless he that teacheth be within, the tongue of the doctor, that is without,
laboureth in vain.`"^
footnote:[Hom. 30. upon the gospel.]

7+++.+++ Cyril of Alexandria plainly affirmeth that "`men
know that Jesus is the Lord by the Holy Ghost,
no otherwise, than they who taste honey know that it is sweet,
even by its proper quality.`"^
footnote:[In thesau. 10. lib 13. cap. 3.]

8+++.+++ "`Therefore`" (saith Bernard), "`we daily exhort you, brethren, by speech,
that ye walk the ways of the heart, and that your souls be always in your hands,
that ye may hear what the Lord saith in you.`" And again,
upon these words of the apostle ("`Let him that glorieth, glory in the Lord`"),
"`with which threefold vice`" (saith he) "`all sorts
of religious men are less or more dangerously affected,
because they do not so diligently attend, with the ears of the heart,
to what the Spirit of Truth (which flatters none) inwardly speaks.`"^
footnote:[In Ps. 84.]

This was the very basis, and main foundation, upon which the primitive reformers walked.

Luther, in his book to the nobility of Germany, saith, "`This is certain,
that no man can make himself a doctor of the holy Scriptures,
but the holy Spirit alone.`" And upon the Magnificat he saith,
"`No man can rightly understand God, or the Word of God,
unless he immediately receive it from the Holy Spirit;
neither can any one receive it from the Holy Spirit,
except he find it by experience in himself;
and in this experience the Holy Ghost teacheth, as in his proper school;
out of which school nothing is taught but mere talk.`"

Philip Melancthon, in his annotations upon John 6:
"`Who hear only an outward and bodily voice, hear the creature;
but God is a Spirit, and is neither discerned, nor known, nor heard,
but by the Spirit; and therefore to hear the voice of God, to see God,
is to know and hear the Spirit.
By the Spirit alone God is known and perceived.

"`Which also the more serious to this day do acknowledge,
even all such who satisfy themselves not with the superficies of religion,
and use it not as a cover or art.
Yea, all those who apply themselves effectually to Christianity,
and are not satisfied until they have found its effectual work upon their hearts,
redeeming them from sin,
do feel that no knowledge effectually prevails to the producing of this,
but that which proceeds from the warm influence of God`'s Spirit upon the heart,
and from the comfortable shining of his Light upon their understanding.`"

And therefore to this purpose a late modern author saith well,
videlicet Dr. Smith of Cambridge in his select discourses:
"`To seek our divinity merely in books and writings is to seek the living among the dead;
we do but in vain many times seek God in these,
where his Truth is too often not so much enshrined as entombed.
Intra te quaere Deum, Seek God within thine own soul.
He is best discerned, RESTORE-GREEK, as Plotinus phraseth it,
by an intellectual touch of him.
We must see with our eyes and hear with our ears,
and our hands must handle the Word of Life (to express it in St. John`'s words),
RESTORE-GREEK, etc., the soul itself hath its sense as well as the body.
And therefore David, when he would teach us to know what the divine goodness is,
calls not for speculation but sensation:
"`Taste and see how good the Lord is.`" That is not the best and truest
knowledge of God which is wrought out by the labour and sweat of the brain,
but that which is kindled within us, by an heavenly warmth in our hearts.`" And again:
"`There is a knowing of the Truth as it is in Jesus, as it is in a Christlike nature;
as it is in that sweet, mild,
humble and loving Spirit of Jesus which spreads itself
like a morning sun upon the spirits of good men,
full of Light and Life.
It profits little to know Christ himself after the flesh;
but he gives his Spirit to good men, "`that searcheth the deep things of God.`" And again:
"`It is but thin airy knowledge that is got by mere speculation
which is ushered in by syllogisms and demonstrations;
but that which springs forth from true goodness is RESTORE-GREEK
as Origen speaks: '`It brings such a divine Light to the soul,
as is more clear and convincing than any demonstration.`'`"

// lint-disable invalid-characters "§"
§III.
That this certain and undoubted method of the true
knowledge of God hath been brought out of use,
hath been none of the least devices of the devil, to secure mankind to his kingdom.
For after the light and glory of the Christian religion
had prevailed over a good part of the world,
and dispelled the thick mists of the heathenish doctrine of the plurality of gods,
he that knew there was no probability of deluding the world any longer that way,
did then puff man up with a false knowledge of the true God;
setting him on work to seek God the wrong way,
and persuading him to be content with such a knowledge as was of his own acquiring,
and not of God`'s teaching.
And this device hath proved the more successful,
because accommodated to the natural and corrupt spirit and temper of man,
who above all things affects to exalt himself; in which self-exaltation,
as God is most greatly dishonored, so therein the devil hath his end;
who is not anxious how much God be acknowledged in words,
provided himself be but always served;
he matters not how great and high speculations the natural man entertains of God,
so long as he serves his lusts and passions,
and is obedient to his evil suggestions and temptations.
Thus Christianity is become^
footnote:[Some later editors insert "`as it were`" here.]
an art, acquired by human science and industry, as any other art or science is;
and men have not only assumed unto themselves the name of Christians,
but even have procured themselves to be esteemed as masters of Christianity,
by certain artificial tricks,
though altogether strangers to the spirit and life of Jesus.
But if we shall make a right definition of a Christian, according to the Scripture,
videlicit, That he is one that hath the spirit of Christ, and is led by it,
how many Christians, yea, and of these great masters and doctors of Christianity,
so accounted, shall we justly divest of that noble title?

If then such as have all the other means of knowledge,
and are sufficiently learned therein, whether it be the letter of the Scripture,
the traditions of churches, or the works of creation and providence,
whence they are able to deduce strong and undeniable
arguments (which may be true in themselves),
are yet not to be esteemed Christians,
according to the certain and infallible definition above mentioned;
and if the inward and immediate revelation of God`'s Spirit in the heart,
in such as have been altogether ignorant of some, and but very little skilled in others,
of these means of attaining knowledge, hath brought them to salvation;
then it will necessarily and evidently follow,
that inward and immediate revelation is the only sure and
certain way to attain the true and saving knowledge of God.

But the first is true:

Therefore the last.

Now as this argument doth very strongly conclude for this way of knowledge,
and against such as deny it, so herein it is the more considerable,
because the propositions from which it is deduced are so clear,
that our very adversaries cannot deny them.
For as to the first it is acknowledged, that many learned men may be, and have been,
damned.
And as to the second, who will deny but many illiterate men may be, and are, saved?
Nor dare any affirm,
that none come to the knowledge of God and salvation
by the inward revelation of the Spirit,
without these other outward means, unless they be also so bold as to exclude Abel, Seth,
Noah, Abraham, Job, and all the holy patriarchs from true knowledge and salvation.

// lint-disable invalid-characters "§"
§IV. I would however not be understood as if hereby I excluded
those other means of knowledge from any use or service to man;
it is far from me so to judge, as concerning the Scriptures, in the next proposition,
will more plainly appear.
The question is not, what may be profitable or helpful, but what is absolutely necessary.
Many things may contribute to further a work,
which yet are not the main thing that makes the work go on.

The sum then of what is said amounts to this:
That where the true inward knowledge of God is, through the revelation of his Spirit,
there is all; neither is there any absolute necessity of any other.
But where the best, highest, and most profound knowledge is,
without this there is nothing, as to the obtaining of the great end of salvation.
This truth is very effectually confirmed by the first part of the proposition itself,
which in few words comprehendeth divers unquestionable arguments,
which I shall in brief subsume.

First, That there is no knowledge of the Father but by the Son.

Secondly, That there is no knowledge of the Son but by the Spirit.

Thirdly, That by the Spirit God hath always revealed himself to his children.

Fourthly, That these revelations were the formal object of the saints`' faith.

And Lastly, That the same continueth to be the object of the saints`' faith to this day.

Of each of these I shall speak a little particularly, and then proceed to the latter part.

// lint-disable invalid-characters "§"
§V. As to the first, viz: That there is no knowledge of the Father but by the Son,
it will not need much probation, being founded upon the plain words of Scripture,
and is therefore a fit medium to draw the rest of our assertions from.

For the infinite and most wise God, who is the foundation,
root and spring of all operation, hath wrought all things by his eternal Word and Son.
"`This is that Word that was in the beginning with God, and was God,
by whom all things were made,
and without whom was not any thing made that was made.`"^
footnote:[John 1:1-3; Eph. 3:9.]
This is that "`Jesus Christ, by whom God created all things, by whom, and for whom,
all things were created, that are in heaven and in earth, visible and invisible,
whether they be thrones, or dominions, or principalities, or powers`" (Col. 1:16),
who therefore is called,
"`The first-born of every creature`" (Col. 1:15). As then that infinite and incomprehensible
fountain of life and motion operateth in the creatures by his own eternal Word and Power,
so no creature has access again unto him but in and by the Son,
according to his own express words, "`No man knoweth the Father, but the Son,
and he to whom the Son will reveal him`" (Matt. 11:27, Luke 10:22). And again,
he himself saith, "`I am the Way, the Truth, and the Life:
no man cometh unto the Father but by me`" (John 14:6).

Hence he is fitly called, "`The mediator betwixt God and man`":
for having been with God from all eternity, being himself God,
and also in time partaking of the nature of man,
through him is the goodness and love of God conveyed to mankind,
and by him again man receiveth and partaketh of these mercies.

Hence is easily deduced the probation of this first assertion, thus:

If no man knoweth the Father but the Son, and he to whom the Son will reveal him,
then there is no knowledge of the Father but by the Son.

But, no man knoweth the Father but the Son:

Therefore, there is no knowledge of the Father but by the Son.

The first part of the antecedent are the plain words of Scripture:
the consequence thereof is undeniable; except one would say,
that he hath the knowledge of the Father, while yet he knows him not;
which were an absurd repugnance.

Again, If the Son be the Way, the Truth, and the Life,
and that no man cometh unto the Father, but by him;
then there is no knowledge of the Father but by the Son.

But the first is true;

Therefore the last.

The antecedent are the very Scripture words: the consequence is very evident:
for how can any know a thing, who useth not the way, without which it is not knowable?
But it is already proved, that there is no other way but by the Son;
so that whoso uses not that way, cannot know him, neither come unto him.

// lint-disable invalid-characters "§"
§VI. Having then laid down this first principle, I come to the second, viz:
That there is no knowledge of the Son but by the Spirit; or,
that the revelation of the Son of God is by the Spirit.

Where it is to be noted, that I always speak of the saving, certain,
and necessary knowledge of God;
which that it cannot be acquired other ways than by the Spirit,
doth also appear from many clear scriptures.
For Jesus Christ, in and by whom the Father is revealed,
doth also reveal himself to his disciples and friends in and by his Spirit.
As his manifestation was outward,
when he testified and witnessed for the Truth in this world,
and approved himself faithful throughout, so being now withdrawn, as to the outward man,
he doth teach and instruct mankind inwardly by his own Spirit;
"`He standeth at the door, and knocketh, and whoso heareth his voice and openeth,
he comes in,`" to such (Rev. 3:20). Of this revelation
of Christ in him Paul speaketh (Gal. 1:16),
in which he placeth the excellency of his ministry, and the certainty of his calling.
And the promise of Christ to his disciples, "`Lo,
I am with you to the end of the world,`" confirmeth this same thing;
for this is an inward presence, and spiritual, as all acknowledge:
but what relates hereto will again occur.
I shall deduce the proof of this proposition from two manifest places of Scripture.
The first is (1 Cor. 2:11-12), "`What man knoweth the things of a man,
save the spirit of a man which is in him?
Even so the things of God knoweth no man, but the Spirit of God.
Now we have received not the spirit of the world, but the Spirit which is of God,
that we might know the things which are freely given us of God.`" The apostle,
in the verses before, speaking of the wonderful things which are prepared for the saints,
after he hath declared, that "`the natural man cannot reach them,`" adds,
that "`they are revealed by the Spirit of God`" (vv. 9-10), giving this reason,
"`For the Spirit searcheth all things,
even the deep things of God.`" And then he bringeth in the comparison,
in the verses above mentioned, very apt, and answerable to our purpose and doctrine,
that "`as the things of a man are only known by the spirit
of man so the things of God are known by the Spirit of God`";
that is, that as nothing below the spirit of man (as the spirit of brutes,
or any other creatures) can properly reach unto nor comprehend the things of a man,
as being of a more noble and higher nature, so neither can the spirit of man,
or the natural man, as the apostle in the fourteenth verse subsumes,
receive nor discern the things of God, or the things that are spiritual,
as being also of a higher nature; which the apostle himself gives for the reason, saying,
"`Neither can he know them,
because they are spiritually discerned.`" So that the apostle`'s words,
being reduced to an argument, do very well prove the matter under debate, thus:

If that which appertaineth properly to man,
cannot be discerned by any lower or baser principle than the spirit of man;
then cannot these things, that properly relate unto God and Christ,
be known or discerned by any lower or baser thing
than the Spirit of God and Christ.

But the first is true:

Therefore also the second.

The whole strength of the argument is contained in the apostle`'s words before mentioned;
which, therefore, being granted, I shall proceed to deduce a second argument, thus:

That which is spiritual can only be known and discerned by the Spirit of God.

But the revelation of Jesus Christ, and the true and saving knowledge of him,
is spiritual:

Therefore the revelation of Jesus Christ, and the true and saving knowledge of him,
can only be known and discerned by the Spirit of God.

The other scripture is also a saying of the same apostle (1 Cor. 12:3):
"`No man can say that Jesus is the Lord, but by the Holy Ghost.`" The scripture,
which is full of Truth,
and answereth full well to the enlightened understanding of the spiritual and real Christian,
may perhaps prove very strange to the carnal and pretended follower of Christ,
by whom perhaps it hath not been so diligently remarked.
Here the apostle doth so much require the Holy Spirit
in the things that relate to a Christian,
that he positively avers, we cannot so much as affirm Jesus to be the Lord without it;
which insinuates no less,
than that the spiritual truths of the Gospel are
as lies in the mouths of carnal and unspiritual men;
for though in themselves they be true, yet are they not true as to them,
because not known,
nor uttered forth in and by that principle and Spirit that
ought to direct the mind and actuate it in such things:
they are no better than the counterfeit representations of things in a comedy;
neither can it be more truly and properly called
a real and true knowledge of God and Christ,
than the actings of Alexander the Great, and Julius Caesar, etc.,
if now transacted upon a stage, might be called truly and really their doings;
or the persons representing them might be said truly
and really to have conquered Asia and overcome Pompey,
etc.

This knowledge then of Christ,
which is not by the revelation of his own Spirit in the heart,
is no more properly the knowledge of Christ, than the prattling of a parrot,
which has been taught a few words, may be said to be the voice of a man;
for as that, or some other bird,
may be taught to sound or utter forth a rational sentence,
as it hath learned it by the outward ear,
and not from any living principle of reason actuating it;
so just such is that knowledge of the things of God,
which the natural and carnal man hath gathered from
the words or writings of spiritual men,
which are not true to him, because conceived in the natural spirit,
and so brought forth by the wrong organ, and not proceeding from the spiritual principle;
no more than the words of a man acquired by art,
and brought forth by the mouth of a bird, not proceeding from a rational principle,
are true with respect to the bird which utters them.
Wherefore from this scripture I shall further add this argument:

If no man can say Jesus is the Lord, but by the Holy Ghost,
then no man can know Jesus to be the Lord, but by the Holy Ghost.

But the first is true:

Therefore the second.

From this argument there may be another deduced,
concluding in the very terms of this assertion: thus,

If no man can know Jesus to be the Lord, but by the Holy Ghost,
then can there be no certain knowledge or revelation of him but by the Spirit.

But the first is true:

Therefore the second.

// lint-disable invalid-characters "§"
§VII.
The third thing affirmed is,
That by the Spirit God always revealed himself to his children.

For the making appear of the truth of this assertion,
it will be but needful to consider God`'s manifesting himself
towards and in relation to his creatures from the beginning,
which resolves itself always herein.
The first step of all is ascribed hereunto by Moses (Gen. 1:2). "`And the
Spirit of God moved upon the face of the waters.`" I think it will not be denied,
that God`'s converse with man, all along from Adam to Moses,
was by the immediate manifestation of his Spirit: and afterwards,
through the whole tract of the law, he spake to his children no otherways; which,
as it naturally followeth from the principles above proved,
so it cannot be denied by such as acknowledge the Scriptures of
Truth to have been written by the inspiration of the Holy Ghost:
for these writings, from Moses to Malachi, do declare,
that during all that time God revealed himself to his children by his Spirit.

But if any will object,
That after the dispensation of the Law God`'s method of speaking was altered;

I answer: first, that God spake always immediately to the Jews,
in that he spake always immediately to the high priest from betwixt the cherubims; who,
when he entered into the Holy of Holies,
returning did relate to the whole people the voice and will of God,
there immediately revealed.
So that this immediate speaking never ceased in any age.

Secondly, from this immediate fellowship were none shut out,
who earnestly sought after and waited for it; in that many, besides the high priest,
who were not so much as of the kindred of Levi, nor of the prophets,
did receive it and speak from it; as it is written (Num. 11:25),
where the Spirit is said to have "`rested on the seventy elders`";
which Spirit also reached unto two that were not in the tabernacle, but in the camp;
whom when some would have forbidden, Moses would not, but rejoiced,
"`wishing all the Lord`'s people were prophets,
and that he would put his Spirit upon them`" (v. 29).

This is also confirmed (Neh. 9), where the elders of the people,
after their return from captivity,
when they began to sanctify themselves by fasting and prayer, in which,
numbering up the many mercies of God towards their fathers, they say (v. 20),
"`Thou gavest also thy good Spirit to instruct them`"; and (v. 30),
"`Yet many years didst thou forbear,
and testify against them by thy Spirit in thy prophets.`"
Many are the sayings of spiritual David to this purpose,
as Ps. 51:11-12, "`Take not thy holy Spirit from me:
uphold me with thy free Spirit.`" Ps. 139:7,
"`Whither shall I go from thy Spirit?`" Hereunto doth the
prophet Isaiah ascribe the credit of his testimony,
saying (48:16),
"`And now the Lord God and his Spirit hath sent me.`" And that God
revealed himself to his children under the New Testament,
to wit, to the apostles, evangelists, and primitive disciples, is confessed by all.
How far now this yet continueth, and is to be expected, comes hereafter to be spoken to.

// lint-disable invalid-characters "§"
§VIII.
The fourth thing affirmed is,
That these revelations were the object of the saints`' faith of old.

This will easily appear by the definition of faith,
and considering what its object is:
for which we shall not dive into the curious and various notions of the school-men,
but stay in the plain and positive words of the apostle Paul,
who (Heb. 11) describes it two ways.
"`Faith,`" saith he, "`is the substance of things hoped for,
and the evidence of things not seen`": which,
as the apostle illustrateth it in the same chapter by many examples,
is no other but a firm and certain belief of the mind, whereby it resteth,
and in a sense possesseth the substance of some things hoped for,
through its confidence in the promise of God:
and thus the soul hath a most firm evidence, by its faith,
of things not yet seen nor come to pass.
The object of this faith is the promise, word, or testimony of God, speaking to the mind.
Hence it hath been generally affirmed, that the object of faith is Deus loquens,
etc. that is, God speaking,
etc. which is also manifest from all these examples
deduced by the apostle throughout that whole chapter,
whose faith was founded neither upon any outward testimony,
nor upon the voice or writing of man, but upon the revelation of God`'s will,
manifest unto them, and in them; as in the example of Noah (v. 7), thus: "`By faith Noah,
being warned of God of things not seen as yet, moved with fear,
prepared an ark to the saving of his house; by the which he condemned the world,
and became heir of the righteousness which is by
faith.`" What was here the object of Noah`'s faith,
but God speaking unto him?
He had not the writings nor prophesyings of any going before,
nor yet the concurrence of any church or people to strengthen him;
and yet his faith in the Word, by which he contradicted the whole world,
saved him and his house.
Of which also Abraham is set forth as a singular example,
being therefore called the Father of the faithful,
who is said against hope to have believed in hope,
in that he not only willingly forsook his father`'s country, not knowing whither he went;
in that he believed concerning the coming of Isaac,
though contrary to natural probability; but above all,
in that he refused not to offer him up,
not doubting but God was able to raise him from the dead; of whom it is said,
that "`in Isaac shall thy seed be called.`" And last of all,
in that he rested in the promise, that his seed should possess the land,
wherein he himself was but a pilgrim,
and which to them was not to be fulfilled until divers ages after.
The object of Abraham`'s faith in all this was no other but inward and immediate revelation,
or God signifying his will unto him inwardly, and immediately by his Spirit.

But because, in this part of the proposition, we made also mention of external voices,
appearances, and dreams in the alternative, I think also fit to speak hereof,
what in that respect may be objected; to wit,

Obj.
That those who found their faith now upon immediate and objective revelation,
ought to have also outward voices or visions, dreams or appearances for it.

It is not denied, but God made use of the ministry of angels, who,
in the appearance of men, spake outwardly to the saints of old,
and that he did also reveal some things to them in dreams and visions;
none of which we will affirm to be ceased,
so as to limit the power and liberty of God in manifesting himself towards his children.
But while we are considering the object of faith,
we must not stick to that which is but circumstantially and accidentally so,
but to that which is universally, and substantially so.

Next again,
we must distinguish betwixt that which in itself is subject to doubt and delusion,
and therefore is received for and because of another;
and that which is not subject to any doubt,
but is received simply for and because of itself, as being prima veritas,
the very first and original Truth.
Let us then consider how or how far these outward voices, appearances,
and dreams were the object of the saints`' faith: was it because they were simply voices,
appearances, or dreams?
Nay, certainly; we know, and they were not ignorant,
that the devil can form a sound of words, and convey it to the outward ear.
That he can easily deceive the outward senses, by making things to appear that are not.
Yea, do we not see by daily experience,
that the jugglers and mountebanks can do as much as all that by their legerdemain?
God forbid then that the saints`' faith should lie founded upon
so fallacious a foundation as man`'s outward and fallible senses.
What made them then give credit to these visions?
Certainly nothing else but the secret testimony of God`'s Spirit in their hearts,
assuring them that the voices, dreams, and visions were of and from God.
Abraham believed the angels; but who told him that these men were angels?
We must not think his faith then was built upon his outward senses,
but proceeded from the secret persuasion of God`'s Spirit in his heart.
This then must needs be acknowledged to be originally
and principally the object of the saints`' faith,
without which there is no true and certain faith,
and by which many times faith is begotten and strengthened
without any of these outward or visible helps;
as we may observe in many passages of the holy Scripture, where it is only mentioned,
"`And God said,`" etc. "`And the word of the Lord came`" unto such and such, saying, etc.

But if any one should pertinaciously affirm,
That this did import an outward audible voice to the carnal ear;

I would gladly know what other argument such a one could bring for this his affirmation,
saving his own simple conjecture.
It is said indeed, "`The Spirit witnesseth with our spirit`" (Rom. 8:16);
but not to our outward ears.
And seeing the Spirit of God is within us, and not without us,^
footnote:[Some later editors render this "`not without us only.`"]
it speaks to our spiritual, and not to our bodily ear.
Therefore I see no reason, where it is so often said in Scripture, The Spirit said,
moved, hindered, called such or such a one, to do or forbear such or such a thing,
that any have to conclude, that this was not an inward voice to the ear of the soul,
rather than an outward voice to the bodily ear.
If any be otherwise minded, let them, if they can, produce their arguments,
and we may further consider of them.

From all then which is above declared,
I shall deduce an argument to conclude the probation of this assertion, thus:

That which any one firmly believes, as the ground and foundation of his hope in God,
and life eternal, is the formal object of his faith.

But the inward and immediate revelation of God`'s Spirit, speaking in and unto the saints,
was by them believed as the ground and foundation of their hope in God, and life eternal.

Therefore these inward and immediate revelations were the formal object of their faith.

// lint-disable invalid-characters "§"
§IX. That which now cometh under debate, is what we asserted in the last place,
to wit, That the same continueth to be the object of the saints`' faith unto this day.
Many will agree to what we have said before, who differ from us herein.

There is nevertheless a very firm argument, confirming the truth of this assertion,
included in the proposition itself, to wit,
That the object of the saints`' faith is the same in all ages,
though held forth under divers administrations, which I shall reduce to an argument,
and prove thus:

First, Where the faith is one, the object of the faith is one.

But the faith is one:

Therefore, etc.

That the faith is one, is the express words of the apostle (Eph. 4:5),
who placeth the one faith with the one God, importing no less,
than that to affirm two faiths is as absurd as to affirm two gods.

Moreover, if the faith of the ancients were not one and the same with ours,
i.e. agreeing in substance therewith, and receiving the same definition,
it had been impertinent for the apostle (Heb. 11) to have illustrated
the definition of our faith by the examples of that of the ancients,
or to go about to move us by the example of Abraham,
if Abraham`'s faith were different in nature from ours.
Nor doth any difference arise,
because they believed in Christ with respect to his appearance outwardly as future,
and we, as already appeared: for nor did they then so believe in him to come,
as not to feel him present with them, and witness him near; seeing the apostle saith,
"`They all drank of that spiritual rock which followed them, which rock was Christ`";
nor do we so believe concerning his appearance past,
as not also to feel and know him present with us, and to feed upon him;
"`except Christ`" (saith the apostle) "`be in you, ye are reprobates`";
so that both our faith is one, terminating in one and the same thing.
And as to the other part or consequence of the antecedent, to wit,
That the object is one where the faith is one, the apostle also proveth it,
in the forecited chapter, where he makes all the worthies of old examples to us.
Now wherein are they imitable, but because they believed in God?
And what was the object of their faith, but inward and immediate revelation,
as we have before proved?
Their example can be no ways applicable to us, except we believe in God, as they did,
that is, by the same object.
The apostle clears this yet further by his own example (Gal. 1:16), where he saith,
"`So soon as Christ was revealed in him, he consulted not with flesh and blood,
but forthwith believed and obeyed.`" The same apostle (Heb. 13:7-8),
where he exhorteth the Hebrews to follow the faith of the elders, adds this reason,
"`Considering the end of their conversation, Jesus Christ, the same today, yesterday,
and forever`": Hereby notably insinuating, that in the object there is no alteration.

If any now object the diversity of administration;

I answer, that altereth not at all the object:
for the same apostle mentioneth this diversity three times (1 Cor. 12:4-6),
centereth always in the same object; the same Spirit, the same Lord, the same God.

But further: If the object of faith were not one and the same both to us and to them,
then it would follow that we were to know God some other way than by the Spirit.

But this were absurd:

Therefore, etc.

Lastly, this is most firmly proved from a common and received maxim of the school-men,
to wit, Omnis actus specificatur ab objecto, "`Every act is specified from its object`";
from which, if it be true, as they acknowledge,
(though for the sake of many I shall not recur to this argument,
as being too nice and scholastic, neither lay I much stress upon those kind of things,
as being that which commends not the simplicity of the Gospel):
if the object were different, then the faith would be different also.

Such as deny this proposition nowadays use here a distinction;
granting that God is to be known by his Spirit,
but again denying that it is immediate or inward, but in and by the Scriptures;
in which the mind of the Spirit (as they say) being fully and amply expressed,
we are thereby to know God, and be led in all things.

As to the negative of this assertion, That the Scriptures are not sufficient,
neither were ever appointed to be the adequate and only rule,
nor yet can guide or direct a Christian in all those
things that are needful for him to know,
we shall leave that to the next proposition to be examined.
What is proper in this place to be proved is,
That Christians now are to be led inwardly and immediately by the Spirit of God,
even in the same manner, though it befall not to many to be led in the same measure,
as the saints were of old.

// lint-disable invalid-characters "§"
§X. I shall prove this by divers arguments,
and first from the promise of Christ in these words (John 14:16):
"`And I will pray the Father, and he will give you another Comforter,
that he may abide with you forever,`" (17) "`even the Spirit of Truth,
whom the world cannot receive, because it seeth him not, neither knoweth him;
but ye know him, for he dwelleth with you, and shall be in you.`" Again (v. 26),
"`But the Comforter, which is the Holy Ghost, whom the Father will send in my name,
he shall teach you all things, and bring all things to your remembrance.`" And (16:13),
"`But when the Spirit of Truth is come, he will guide you into all Truth:
for he shall not speak of himself; but whatsoever he shall hear he shall speak,
and he will show you things to come.`" We have here first, who this is,
and that is divers ways expressed, to wit: The Comforter, the Spirit of Truth,
the Holy Ghost, the Sent of the Father in the name of Christ.
And hereby is sufficiently proved the sottishness of those Socinians,
and other carnal Christians,
who neither know nor acknowledge any internal Spirit
or power but that which is merely natural;
by which they sufficiently declare themselves to be of the world,
who cannot receive the Spirit, because they neither see him nor know him.
Secondly, where this Spirit is to be, "`He dwelleth with you,
and shall be in you.`" And thirdly, what his work is, "`He shall teach you all things,
and bring all things to your remembrance, and guide you into all Truth,`"
RESTORE-GREEK.

As to the first,
most do acknowledge that there is nothing else understood
than what the plain words signify;
which is also evident by many other places of Scripture that will hereafter occur;
neither do I see how such as affirm otherways can avoid blasphemy:
for if the "`Comforter,`" the "`Holy Ghost,`" and "`Spirit
of Truth,`" be all one with the Scriptures,
then it will follow that the Scriptures are God,
seeing it is true that the Holy Ghost is God.
If these men`'s reasoning might take place,
wherever "`the Spirit`" is mentioned in relation to the saints,
thereby might be truly and properly understood "`the Scriptures`"; which,
what a nonsensical monster it would make of the Christian religion,
will easily appear to all men.
As where it is said,
"`A manifestation of the Spirit is given to every man to profit withal`";
it might be rendered thus,
A manifestation of the Scriptures is given to every man to profit withal;
what notable sense this would make, and what a curious interpretation,
let us consider by the sequel of the same chapter (1 Cor. 12:9-11):
"`To another the gifts of healing, by the same Spirit; to another the working of miracles,
etc. But all these worketh that one and the self-same Spirit,
dividing to every man severally as he will.`" What would now these great masters of reason,
the Socinians, judge,
if we should place the "`Scriptures`" here instead
of the "`Spirit`"? Would it answer their reason,
which is the great guide of their faith?
Would it be good and sound reason in their logical schools,
to affirm that the Scripture divideth severally as it will,
and giveth to some the gift of healing, to others the working of miracles?
If then this Spirit, a manifestation whereof is given to every man to profit withal,
be no other than that Spirit of Truth before-mentioned which guideth into all Truth;
this Spirit of Truth cannot be the Scriptures.
I could infer an hundred more absurdities of this kind upon this sottish opinion,
but what is said may suffice.
For even some of themselves, being at times forgetful or ashamed of their own doctrine,
do acknowledge that the Spirit of God is another thing, and distinct from the Scriptures,
to guide and influence the saints.

Secondly, That this Spirit is inward,
in my opinion needs no interpretation nor commentary: "`He dwelleth with you,
and shall be in you.`" This indwelling of the Spirit in the saints,
as it is a thing most needful to be known and believed,
so is it as positively asserted in the Scripture as anything else can be.
"`If so be that the Spirit of God dwell in you,`" saith the apostle to the Romans (8:9);
and again, "`Know ye not that ye are the temple of the Holy Ghost,
and that the Spirit of God dwelleth in you?`" (1 Cor.
6:19):^
footnote:[Later editors substitute,
"`Know ye not that your body is the temple of the Holy Ghost`" (1 Cor.
6:19). "`And that the Spirit of God dwelleth in you`" (1 Cor. 3:16).]
without this the apostle reckoneth no man a Christian.
"`If any man,`" saith he, "`have not the Spirit of Christ,
he is none of his.`" These words immediately follow
those abovementioned out of the epistle to the Romans,
"`But ye are not in the flesh, but in the Spirit,
if so be the Spirit of God dwell in you.`" The context of which showeth,
that the apostle reckoneth it the main token of a Christian,
both positively and negatively:
for in the former verses he showeth how "`the carnal mind is enmity
against God,`" and that such as are in the flesh cannot please him.
Where subsuming, he adds concerning the Romans,
that they "`are not in the flesh,`" if the Spirit of God dwell in them.
What is this but to affirm,
that they in whom the Spirit dwells are no longer in the flesh,
nor of those who please not God, but are become Christians indeed?
Again, in the same verse he concludes negatively,
that "`If any man have not the Spirit of Christ, he is none of his`"; that is,
he is no Christian.
He then that acknowledges himself ignorant and a stranger
to the inward inbeing of the Spirit of Christ in his heart,
doth thereby acknowledge himself to be yet in the carnal mind, which is enmity to God;
to be yet in the flesh, where God cannot be pleased;
and in short (whatever he may otherways know or believe of Christ,
or however much skilled or acquainted with the letter of the holy Scripture,
not yet to be), notwithstanding all that, attained to the least desire^
footnote:[Later editors substitute "`degree`" for "`desire.`"]
of a Christian; yea, not once to have embraced the Christian religion.
For take but away the Spirit, and Christianity remains no more Christianity,
than the dead carcass of a man, when the soul and spirit is departed, remains a man;
which the living can no more abide, but do bury out of their sight,
as a noisome and useless thing,
however acceptable it hath been when actuated and moved by the soul.

Lastly, "`Whatsoever is excellent, whatsoever is noble, whatsoever is worthy,
whatsoever is desirable`" in the Christian faith, is ascribed to this Spirit,
without which it could no more subsist than the outward world without the sun.
Hereunto have all true Christians, in all ages, attributed their strength and life.
It is by this Spirit that they avouch themselves to have been converted to God,
to have been redeemed from the world, to have been strengthened in their weakness,
comforted in their afflictions, confirmed in their temptations,
emboldened in their sufferings, and triumphed in the midst of all their persecutions.
Yea, the writings of all true Christians are full of the great and notable
things which they all affirm themselves to have done,
by the power, and virtue, and efficacy of this Spirit of God working in them.
"`It is the Spirit that quickeneth`" (John 6:63). It was the Spirit that
gave them utterance (Acts 2:4). It was the Spirit by which Stephen spake,
that the Jews were not able to resist (Acts 6:10). It is such
as walk after the Spirit that receive no condemnation (Rom. 8:1).
It is the law of the Spirit that makes free (v. 2). It is by the
Spirit of God dwelling in us that we are redeemed from the flesh,
and from the carnal mind (v. 9). It is the Spirit of Christ dwelling
in us that quickeneth our mortal bodies (v. 11). It is through
this Spirit that the deeds of the body are mortified,
and life obtained (v. 13). It is by this Spirit that we are adopted,
and "`cry ABBA Father`" (v. 15). It is this "`Spirit that beareth witness with our spirit
that we are the children of God`" (v. 16). It is this "`Spirit that helpeth our infirmities,
and maketh intercession for us,
with groanings which cannot be uttered`" (v. 26). It is by this
Spirit that the glorious things which God hath laid up for us,
which "`neither outward ear hath heard, nor outward eye hath seen,
nor the heart of man conceived`" by all his reasonings,
are revealed unto us (1 Cor. 2:9-10). It is by
this Spirit that both wisdom and knowledge,
and faith, and miracles, and tongues, and prophecies,
are obtained (1 Cor. 12:8-10). It is by this Spirit
that we are "`all baptized into one body`" (v. 13). In short,
what thing relating to the salvation of the soul, and to the life of a Christian,
is rightly performed, or effectually obtained without it?
And what shall I more say?
For the time would fail me to tell of all those things
which the holy men of old have declared,
and the saints of this day do witness themselves to enjoy,
by the virtue and power of this Spirit dwelling in them.
Truly my paper could not contain those many testimonies whereby this truth is confirmed;
wherefore, besides what is above mentioned out of the fathers,
whom all pretend to reverence, and those of Luther and Melancthon,
I shall deduce yet one observable testimony out of Calvin,
because not a few of the followers of his doctrine do refuse and deride and that,
(as it is to be feared,
because of their own nonexperience thereof) this way of the Spirit`'s indwelling,
as uncertain and dangerous; that so, if neither the testimony of the Scripture,
nor the sayings of others, nor right reason can move them,
they may at least be reproved by the words of their own master,
who saith in the third book of his Institutions, cap.
2, on this wise:

"`But they allege,
It is a bold presumption for any to pretend to an undoubted knowledge of God`'s will;
which,`" (saith he) "`I should grant unto them,
if we should ascribe so much to ourselves as to subject the incomprehensible
counsel of God to the rashness of our understandings.
But while we simply say with Paul, that '`we have received not the spirit of this world,
but the Spirit which is of God,`' by whose teaching
we know those things that are given us of God,
what can they prate against it without reproaching the Spirit of God?
For if it be an horrible sacrilege to accuse any revelation coming from him,
either of a lie, of uncertainty or ambiguity,
in asserting its certainty wherein do we offend?
But they cry out,
"`That it is not without great temerity that we dare so boast of the Spirit of Christ.`'
Who would believe that the sottishness of these men were so great,
who would be esteemed the masters of the world,
that they should so fail in the first principles of religion?
Verily I could not believe it, if their own writings did not testify so much.
Paul accounts those the Sons of God, who are acted by the Spirit of God;
but these will have the children of God acted by
their own spirits without the Spirit of God.
He will have us call God Father, the Spirit dictating that term unto us,
which only can witness to our spirits that we are the sons of God.
These, though they cease not to call upon God, do nevertheless demit^
footnote:[demit +++=+++ dismiss]
the Spirit, by whose guiding he is rightly to be called upon.
He denies them to be the sons of God, or the servants of Christ,
who are not led by his Spirit;
but these feign a Christianity that needs not the Spirit of Christ.
He makes no hope of the blessed resurrection, unless we feel the Spirit residing in us;
but these feign a hope without any such feeling; but perhaps they will answer,
that they deny not but that it is necessary to have it,
only of modesty and humility we ought to deny and not acknowledge it.
What means he then, when he commands the Corinthians to try themselves,
if they be in the faith; to examine themselves, whether they have Christ,
whom whosoever acknowledges not dwelling in him, is a reprobate?
'`By the Spirit which he hath given us,`' saith John, '`we know that he abideth in us.`'
And what do we then else but call in question Christ his promise,
while we would be esteemed the servants of God without his Spirit,
which he declared he would pour out upon all his?
Seeing these things are the first grounds of piety,
it is miserable blindness to accuse Christians of pride,
because they dare glory of the presence of the Spirit; without which glorying,
Christianity itself could not be.
But by their example they declare, how truly Christ spake,
saying that his Spirit was unknown to the world, and that those only acknowledge it,
with whom it remains.`" Thus far Calvin.

If therefore it be so, why should any be so foolish as to deny,
or so unwise as not to seek after this Spirit,
which Christ hath promised shall dwell in his children?
They then that do suppose the indwelling and leading of his Spirit to be ceased,
must also suppose Christianity to be ceased, which cannot subsist without it.

Thirdly, What the work of this Spirit is, is partly before shown,
which Christ compriseth in two or three things, "`He will guide you into all Truth`";
"`He will teach you all things, and bring all things to your remembrance.`"^
footnote:[John 16:13-14:26.]
Since Christ hath provided for us so good an instructor,
what need we then lean so much to those traditions and commandments
of men wherewith so many Christians have burdened themselves?
What need we set up our own carnal and corrupt reason for a guide to us in matters spiritual,
as some will needs do?
May it not be complained of all such,
as the Lord did of old concerning Israel by the prophets (Jer. 2:13):
"`For my people have committed two evils, they have forsaken me,
the fountain of living waters, and hewed them out cisterns, broken cisterns,
that can hold no water.`" Have not many forsaken, do not many deride and reject,
this inward and immediate guide, this Spirit that leads into all Truth,
and cast up to themselves other ways, broken ways indeed,
which have not all this while brought them out of the flesh, nor out of the world,
nor from under the dominion of their own lusts and sinful affections, whereby Truth,
which is only rightly learned by this Spirit, is so much a stranger in the earth?

From all then that hath been mentioned concerning this promise,
and these words of Christ, it will follow,
that Christians are always to be led inwardly and
immediately by the Spirit of God dwelling in them,
and that the same is a standing and perpetual ordinance,
as well to the church in general in all ages,
as to every individual member in particular, as appears from this argument:

The promises of Christ to his children are Yea and Amen, and cannot fail,
but must of necessity be fulfilled.

But Christ hath promised, that the Comforter, the Holy Ghost, the Spirit of Truth,
shall abide with his children forever; shall dwell with them, shall be in them,
shall lead them into all Truth, shall teach them all things,
and bring all things to their remembrance:

Therefore, etc.

Again: No man is redeemed from the carnal mind, which is at enmity with God,
which is not subject to the law of God, neither can be: no man is yet in the Spirit,
but in the flesh, and cannot please God, except he in whom the Spirit of God dwells.

But every true Christian is in measure redeemed from the carnal mind,
is gathered out of the enmity, and can be subject to the law of God; is out of the flesh,
and in the Spirit, the Spirit of God dwelling in him.

Therefore every true Christian hath the Spirit of God dwelling in him.

Again: "`Whosoever hath not the Spirit of Christ, is none of his`"; that is, no child,
no friend, no disciple of Christ.

But every true Christian is a child, a friend, a disciple of Christ:

Therefore every true Christian hath the Spirit of Christ.

Moreover: Whosoever is the temple of the Holy Ghost,
in him the Spirit of God dwelleth and abideth.

But every true Christian is the temple of the Holy Ghost:

Therefore in every true Christian the Spirit of God dwelleth and abideth.

But to conclude: He in whom the Spirit of God dwelleth, it is not in him a lazy, dumb,
useless thing; but it moveth, actuateth, governeth, instructeth,
and teacheth him all things whatsoever are needful for him to know; yea,
bringeth all things to his remembrance.

But the Spirit of God dwelleth in every true Christian:

Therefore the Spirit of God leadeth, instructeth,
and teacheth every true Christian whatsoever is needful for him to know.

// lint-disable invalid-characters "§"
§XI. But there are some that will confess,
That the Spirit doth now lead and influence the saints,
but that he doth it only subjectively, or in a blind manner,
by enlightening their understandings,
to understand and believe the Truth delivered in the Scriptures;
but not at all by presenting those truths to the mind by way of object,
and this they call, medium incognitum assentiendi,
as that of whose working a man is not sensible.

This opinion, though somewhat more tolerable than the former,
is nevertheless not altogether according to Truth,
neither doth it reach the fullness of it.

1+++.+++ Because there be many truths,
which as they are applicable to particulars and individuals,
and most needful to be known by them, are nowise to be found in the Scripture,
as in the following proposition shall be shown.

Besides, the arguments already adduced do prove,
that the Spirit doth not only subjectively help us to discern truths elsewhere delivered,
but also objectively present those truths to our minds.
For that which teacheth me all things, and is given me for that end,
without doubt presents those things to my mind which it teacheth me.
It is not said, "`it shall teach you how to understand those things that are written`";
but, "`It shall teach you all things.`" Again,
That which bringeth all things to my remembrance,
must needs present them by way of object; else it were improper to say,
it brought them to my remembrance; but only,
that it helpeth to remember the objects bought from elsewhere.

My second argument shall be drawn from the nature of the new covenant; by which,
and those that follow,
I shall prove that we are led by the Spirit both immediately and objectively.
The nature of the new covenant is expressed in divers places; and

First (Isa. 59:21), "`As for me, this is my covenant with them, saith the Lord;
My Spirit that is upon thee, and my words which I have put in thy mouth,
shall not depart out of thy mouth, nor out of the mouth of thy seed,
nor out of the mouth of thy seed`'s seed, saith the Lord,
from henceforth and forever.`" By the latter part of this is sufficiently
expressed the perpetuity and continuance of this promise,
"`It shall not depart, saith the Lord,
from henceforth and forever.`" In the former part is the promise itself,
which is the Spirit of God being upon them,
and the words of God being put into their mouths.

First, this was immediate, for there is no mention made of any medium; he saith not,
I shall by the means of such and such writings or
books convey such and such words into your mouths;
but "`My words, I, even I, saith the Lord, have put into your mouths.`"

Secondly, this must be objectively;
for the words put into the mouth are the object presented by him.
He saith not, The words which ye shall see written,
my Spirit shall only enlighten your understandings to assent unto; but positively,
"`my words, which I have put in thy mouth,`" etc. From whence I argue thus:

Upon whomsoever the Spirit remaineth always, and putteth words into his mouth,
him doth the Spirit teach immediately, objectively, and continually.

But the Spirit is always upon the seed of the righteous,
and putteth words into their mouths, neither departeth from them:

Therefore the Spirit teacheth the righteous immediately, objectively, and continually.

Secondly, The nature of the new covenant is yet more amply expressed (Jer. 31:33),
which is again repeated and reasserted by the apostle (Heb. 8:10-11), in these words,
"`For this is the covenant that I will make with the house of Israel, after those days,
saith the Lord, I will put my laws into their minds, and write them in their hearts,
and I will be to them a God, and they shall be to me a people.
And they shall not teach every man his neighbour, and every man his brother, saying,
Know the Lord; for all shall know me, from the least to the greatest.`"

The object here is God`'s law placed in the heart, and written in the mind;
from whence they become God`'s people, and are brought truly to know him.

In this then is the Law distinguished from the Gospel; the Law before was outward,
written in tables of stone, but now it is inward, written in the heart:
of old the people depended upon their priests for the knowledge of God,
but now they have all a certain and sensible knowledge of Him;
concerning which Augustine speaketh well, in his book De Litera & Spiritu;
from whom Aquinas first of all seems to have taken occasion to move this question,
Whether the new law be a written law, or an implanted law?
Lex scripta, vel lex indita?
Which he thus resolves, affirming that the new law, or the Gospel,
is not properly a law written, as the old was, but lex indita, an implanted law;
and that the old law was written without, but the new law is written within,
on the table of the heart.

How much then are they deceived, who, instead of making the Gospel preferable to the Law,
have made the condition of such as are under the Gospel far worse?
For no doubt it is a far better and more desirable thing to converse with God immediately,
than only mediately, as being an higher and more glorious dispensation;
and yet these men acknowledge that many under the Law had immediate converse with God,
whereas they now cry it is ceased.

Again: Under the Law there was the holy of holies, into which the high priest did enter,
and received the word of the Lord immediately from betwixt the cherubims,
so that the people could then certainly know the mind of the Lord; but now,
according to these men`'s judgment, we are in a far worse condition,
having nothing but the outward letter of the Scripture to guess and divine from:
concerning the sense or meaning of one verse of which scarce two can be found to agree.
But Jesus Christ hath promised us better things,
though many are so unwise as not to believe him,
even to guide us by his own unerring Spirit, and hath rent and removed the veil,
whereby not only one, and that once a year, may enter; but all of us, at all times,
have access unto him, as often as we draw near unto him with pure hearts.
He reveals his will to us by his Spirit, and writes his laws in our hearts.
These things then being thus premised, I argue,

Where the law of God is put into the mind, and written in the heart,
there the object of faith, and revelation of the knowledge of God, is inward, immediate,
and objective.

But the law of God is put into the mind,
and written in the heart of every true Christian, under the new covenant.

Therefore the object of faith and revelation of the
knowledge of God to every true Christian is inward,
immediate, and objective.

The assumption is the express words of Scripture:
the proposition then must needs be true,
except that which is "`put into the mind,`" and "`written
in the heart,`" were either not inward,
not immediate, or not objective, which is most absurd.

// lint-disable invalid-characters "§"
§XII.
The third argument is from these words of John, (1 John 2:27):
"`But the anointing, which ye have received of him, abideth in you,
and ye need not that any man teach you:
but as the same anointing teacheth you of all things, and is Truth, and is no lie;
and even as it hath taught you, ye shall abide in him.`"

First, This could not be any special, peculiar, or extraordinary privilege,
but that which is common to all the saints, it being a general epistle,
directed to all them of that age.

Secondly, The apostle proposeth this anointing in them,
as a more certain touchstone for them to discern and try seducers by,
even than his own writings; for having in the former verse said,
that he had written some things to them concerning such as seduced them,
he begins the next verse, "`But the anointing,`" etc.,
"`and ye need not that any man teach you,`" etc., which infers,
that having said to them what can be said,
he refers them for all to the inward anointing, which teacheth all things,
as the most firm, constant, and certain bulwark against all seducers.

And lastly: That it is a lasting and continuing thing; the anointing which abideth.
If it had not been to abide in them, it could not have taught them all things,
neither guided them against all hazard.
From which I argue thus,

He that hath an anointing abiding in him, which teacheth him all things,
so that he needs no man to teach him, hath an inward and immediate teacher,
and hath some things inwardly and immediately revealed unto him.

But the saints have such an anointing.

Therefore, etc.

I could prove this doctrine from many more places of Scripture,
which for brevity`'s sake I omit; and now come to the second part of the proposition,
where the objections usually formed against it are answered.

// lint-disable invalid-characters "§"
§XIII.
The most usual is, that these revelations are uncertain.

But this bespeaketh much ignorance in the opposers;
for we distinguish between the thesis and the hypothesis; that is,
between the proposition and supposition.
For it is one thing to affirm,
that the true and undoubted revelation of God`'s Spirit is certain and infallible;
and another thing to affirm,
that this or that particular person or people is led infallibly
by this revelation in what they speak or write,
because they affirm themselves to be so led by the
inward and immediate revelation of the Spirit.
The first is only by us asserted, the latter may be called in question.
The question is not who are or are not so led?
But whether all ought not or may not be so led?

Seeing then we have already proved that Christ hath
promised his Spirit to lead his children,
and that every one of them both ought and may be led by it,
if any depart from this certain guide in deeds,
and yet in words pretend to be led by it into things that are not good,
it will not from thence follow, that the true guidance of the Spirit is uncertain,
or ought not to be followed; no more than it will follow that the sun showeth not light,
because a blind man, or one who willfully shuts his eyes,
falls into a ditch at noon-day for want of light; or that no words are spoken,
because a deaf man hears them not;
or that a garden full of fragrant flowers has no sweet smell,
because he that has lost his smelling doth not savour it; the fault then is in the organ,
and not in the object.

All these mistakes therefore are to be ascribed to the weakness or wickedness of men,
and not to that Holy Spirit.
Such as bend themselves most against this certain and infallible testimony of the Spirit,
use commonly to allege the example of the old Gnostics,
// lint-disable invalid-characters "ü"
and the late monstrous and mischievous actings of the Anabaptists of Münster,
all which toucheth us nothing at all, neither weakens a whit our most true doctrine.
Wherefore, as a most sure bulwark against such kind of assaults,
was subjoined that other part of our proposition thus:
Moreover these divine and inward revelations,
which we establish as absolutely necessary for the founding of the true faith,
as they do not, so neither can they at any time contradict the Scriptures`' testimony,
or sound reason.

Besides the intrinsic and undoubted truth of this assertion,
we can boldly affirm it from our certain and blessed experience.
For this Spirit never deceived us,
never acted nor moved us to any thing that was amiss;
but is clear and manifest in its revelations, which are evidently discerned of us,
as we wait in that pure and undefiled Light of God (that proper and fit organ),
in which they are received.
Therefore if any reason after this manner,

(That because some wicked, ungodly, devilish men have committed wicked actions,
and have yet more wickedly asserted,
that they were led into these things by the Spirit of God;

Therefore, No man ought to lean to the Spirit of God, or seek to be led by it),

I utterly deny the consequence of this proposition, which were it to be received as true,
then would all faith in God and hope of salvation become uncertain,
and the Christian religion be turned into mere skepticism.
For after the same manner I might reason thus:

Because Eve was deceived by the lying of the serpent;

Therefore she ought not to have trusted to the promise of God.

Because the old world was deluded by evil spirits;

Therefore ought neither Noah, nor Abraham, nor Moses,
to have trusted the Spirit of the Lord.

Because a lying spirit spake through the four hundred prophets,
that persuaded Ahab to go up and fight at Ramoth Gilead;

Therefore the testimony of the true Spirit in Micaiah was uncertain,
and dangerous to be followed.

Because there were seducing spirits crept into the church of old;

Therefore it was not good, or uncertain, to follow the anointing which taught all things,
and is Truth, and is no lie.

Who dare say that this is a necessary consequence?
Moreover, not only the faith of the saints, and Church of God of old,
is hereby rendered uncertain,
but also the faith of all sorts of Christians now is liable to the like hazard,
even of those who seek a foundation for their faith elsewhere than from the Spirit.
For I shall prove by an inevitable argument, ab incommodo, i.e.,
from the inconveniency of it, that if the Spirit be not to be followed upon that account,
and that men may not depend upon it as their guide, because some,
while pretending thereunto, commit great evils; that then, nor tradition,
nor the Scriptures, nor reason, which the Papists, Protestants,
and Socinians do respectively make the rule of their faith,
are any whit more certain.
The Romanists reckon it an error to celebrate Easter any other ways than that church doth.
This can only be decided by tradition.
And yet the Greek church, which equally layeth claim to tradition with herself,
doth it otherwise.
Yea, so little effectual is tradition to decide the case, that Polycarp,
the disciple of John, and Anicetus,
the bishop of Rome who immediately succeeded them (according to whose example
both sides concluded the question ought to be decided) could not agree.^
footnote:[Eusebius, Hist. Ecclesi. lib. 5. cap. 26.]
Here of necessity one behooved to err, and that following tradition.
Would the Papists now judge we dealt fairly by them, if we should thence aver,
that tradition is not to be regarded?
Besides, in a matter of far greater importance the same difficulty will occur, to wit,
in the primacy of the bishop of Rome; for many do affirm, and that by tradition,
that in the first six hundred years the Roman prelates never assumed
the title of "`Universal Shepherd,`" nor were acknowledged as such.
And, as that which altogether overturneth this presidency, there are, that allege,
and that from tradition also, that Peter never saw Rome;
and that therefore the bishop of Rome cannot be his successor.
Would ye Romanists think this sound reasoning, to say, as ye do,

Many have been deceived, and erred grievously, in trusting to tradition;

Therefore we ought to reject all traditions, yea,
even those by which we affirm the contrary, and, as we think, prove the Truth?

Lastly, in the Council of Florence,
the chief doctors of the Romish and Greek churches did debate whole sessions
long concerning the interpretation of one sentence of the Council of Ephesus,
and of Epiphanius, and Basil, neither could they ever agree about it.^
footnote:[Conc. Flor. Sess. 5. decreto quodam Concl. Eph. Act. 6. Sess.
11 & 12. Concil. Flor. Sess. 18:20. Conc. Flor. Sess. 21. p. 480 & seqq.]

Secondly, as to the Scripture, the same difficulty occurreth:
the Lutherans affirm they believe consubstantiation by the Scripture;
which the Calvinists deny, as that which, they say,
according to the same Scripture, is a gross error.
The Calvinists again affirm absolute reprobation, which the Arminians deny,
affirming the contrary;
wherein both affirm themselves to be ruled by the Scripture and reason in the matter.
Should I argue thus then to the Calvinists?

Here the Lutherans and Arminians grossly err, by following the Scripture;

// lint-disable invalid-characters "èà"
Therefore the Scripture is not a good nor certain rule; and è contrà.

Would either of them accept of this reasoning as good and sound?
What shall I say of the Episcopalians, Presbyterians, Independents,
and Anabaptists of Great Britain,
who are continually buffeting one another with the Scripture?
To whom the same argument might be alleged,
though they do all unanimously acknowledge it to be the rule.

And thirdly, as to reason, I shall not need to say much;
for whence come all the controversies, contentions and debates in the world,
but because every man thinks he follows right reason?
Hence of old came the jangles between the Stoics, Platonists, Peripatetics, Pythagoreans,
and Cynics, as of late betwixt the Aristotelians, Cartesians, and other naturalists:
Can it be thence inferred, or will the Socinians, those great reasoners,
allow us to conclude, because many, and that very wise men,
have erred by following (as they supposed) their reason, and that with what diligence,
care and industry they could, to find out the Truth,
that therefore no man ought to make use of it at all,
nor be positive in what he knows certainly to be rational?
And thus far as to opinion;
the same uncertainty is no less incident unto those other principles.

// lint-disable invalid-characters "§"
§XIV.
But if we come to practices,
though I confess I do with my whole heart abhor and detest those wild
// lint-disable invalid-characters "ü"
practices which are written concerning the Anabaptists of Münster;
I am bold to say, as bad,
if not worse things have been committed by those that lean to tradition, Scripture,
and reason:
wherein also they have averred themselves to have been authorized by these rules.
I need but mention all the tumults, seditions, and horrible bloodshed,
wherewith Europe hath been afflicted these divers ages; in which Papists against Papists,
Calvinists against Calvinists, Lutherans against Lutherans, and Papists,
assisted by Protestants, against other Protestants assisted by Papists,
have miserably shed one another`'s blood, hiring and forcing men to kill one another,
who were ignorant of the quarrel and strangers one to another: all, meanwhile,
pretending reason for so doing, and pleading the lawfulness of it from Scripture.

For what have the Papists pretended for their many massacres,
acted as well in France as elsewhere, but tradition, Scripture, and reason?
Did they not say, that reason persuaded them, tradition allowed them,
and Scripture commanded them, to persecute, destroy, and burn heretics,
such as denied this plain scripture, Hoc est corpus meum, This is my body?
And are not the Protestants assenting to this bloodshed, who assert the same thing,
and encourage them, by burning and banishing,
while their brethren are so treated for the same cause?
Are not the islands of Great Britain and Ireland (yea,
and all the Christian world) a lively example hereof,
which were divers years together as a theatre of blood; where many lost their lives,
and numbers of families were utterly destroyed and ruined?
For all which no other cause was principally given, than the precepts of the Scripture.
// lint-disable invalid-characters "ü"
If we then compare these actings with those of Münster,
we shall not find great difference; for both affirmed and pretended they were called,
and that it was lawful to kill, burn, and destroy the wicked.
We must kill all the wicked, said those Anabaptists,
that we that are the saints may possess the earth.
We must burn obstinate heretics, say the Papists,
that the holy church of Rome may be purged of rotten members, and may live in peace.
We must cut off seducing separatists, say the Prelatical Protestants,
who trouble the peace of the church, and refuse the divine hierarchy,
and religious ceremonies thereof.
We must kill, say the Calvinistic Presbyterians, the profane malignants,
who accuse the Holy Consistorial and Presbyterian government,
and seek to defend the Popish and Prelatic hierarchy;
as also those other sectaries that trouble the peace of our church.
What difference I pray thee, impartial reader, seest thou betwixt these?

If it be said, The Anabaptists went without, and against the authority of the magistrate,
so did not the other;

I might easily refute it,
by alleging the mutual testimonies of these sects against one another.
The behaviour of the Papists towards Henry the Third and Fourth of France;
their designs upon James the Sixth in the gunpowder treason;
as also their principle of the Pope`'s power to depose kings for the cause of heresy,
and to absolve their subjects from their oath, and give them to others,
proves it against them.

And as to the Protestants,
how much their actions differ from those other above-mentioned,
may be seen by the many conspiracies and tumults which they have been active in,
both in Scotland and England,
and which they have acted within these hundred years
in divers towns and provinces of the Netherlands.
Have they not oftentimes sought, not only from the Popish magistrates,
but even from those that had begun to reform,
or that had given them some liberty of exercising their religion,
that they might only be permitted, without trouble or hindrance,
to exercise their religion,
promising they would not hinder or molest the Papists in the exercise of theirs?
And yet did they not on the contrary, so soon as they had power,
trouble and abuse these fellow-citizens, and turn them out of the city, and,
which is worse, even such who together with them had forsaken the Popish religion?
Did they not these things in many places against the mind of the magistrates?
Have they not publicly, with contumelious speeches, assaulted their magistrates,
from whom they had but just before sought and obtained the free exercise of their religion,
representing them, so soon as they opposed themselves to their hierarchy,
as if they had regarded neither God nor religion?
Have they not by violent hands possessed themselves of the Popish churches, so called,
or by force, against the magistrates`' mind, taken them away?
Have they not turned out of their office and authority whole councils of magistrates,
under pretence that they were addicted to Popery?
Which Popish magistrates nevertheless they did but
a little before acknowledge to be ordained by God;
affirming themselves obliged to yield them obedience and subjection, not only for fear,
but for conscience sake;
to whom moreover the very preachers and overseers
of the reformed church had willingly sworn fidelity;
and yet afterwards have they not said,
that the people are bound to force a wicked prince to the observation of God`'s Word?
There are many other instances of this kind to be found in their histories,
not to mention many worse things, which we know to have been acted in our time,
and which for brevity`'s sake I pass by.

I might say much of the Lutherans,
whose tumultuous actions against their magistrates not professing the Lutheran profession,
are testified of by several historians worthy of credit.
Among others,
I shall propose only one example to the reader`'s consideration
which fell out at Berlin in the year 1615:
"`Where the seditious multitude of the Lutheran citizens,
being stirred up by the daily clamours of their preachers,
did not only violently take up the houses of the reformed teachers,
overturn their libraries, and spoil their furniture; but also with reproachful words,
yea, and with stones, assaulted the Marquis of Brandenburg,
the Elector`'s brother while he sought by smooth words to quiet the fury of the multitude;
they killed ten of his guard, scarcely sparing himself,
who at last by flight escaped out of their hands.`"

All which sufficiently declares,
that the concurrence of the magistrate doth not alter their principles,
but only their method of procedure.
// lint-disable invalid-characters "ü"
So that for my own part, I see no difference betwixt the actings of those of Münster,
and these others, whereof the one pretended to be led by the Spirit,
the other by tradition, Scripture, and reason, save this, that the former were rash,
heady, and foolish, in their proceedings,
and therefore were the sooner brought to nothing, and so into contempt and derision:
but the other, being more politic and wise in their generation, held it out longer,
and so have authorized their wickedness more,
with the seeming authority of law and reason.
But both their actings being equally evil,
the difference appears to me to be only like that which is between a simple silly thief,
that is easily caught, and hanged without any more ado;
and a company of resolute bold robbers, who being better guarded,
though their offence be nothing less, yet by violence do, to evite^
footnote:[evite +++=+++ avoid]
the danger, force their masters to give them good terms.

From all which then it evidently follows that they argue very ill that despise
and reject any principle because men pretending to be led by it do evil,
in case it be not the natural and consequential tendency
of that principle to lead unto those things that are evil.

Again: It doth follow from what is above asserted,
that if the Spirit be to be rejected upon this account,
all those other principles ought on the same account to be rejected.
And for my part,
as I have never a whit the lower esteem of the blessed testimony of the holy Scriptures,
nor do the less respect any solid tradition, that is answerable and according to Truth;
neither at all despise reason, that noble and excellent faculty of the mind,
because wicked men have abused the name of them, to cover their wickedness,
and deceive the simple;
so would I not have any reject or diffide the certainty
of that unerring Spirit which God hath given his children,
as that which can alone guide them into all Truth,
because some have falsely pretended to it.

// lint-disable invalid-characters "§"
§XV. And because the Spirit of God is the fountain of all Truth and sound reason,
therefore we have well said,
that it can not contradict neither the testimony of the Scripture, nor right reason:
yet (as the proposition itself concludeth,
to whose last part I now come) it will not from thence follow,
that these divine revelations are to be subjected to the
examination either of the outward testimony of Scripture,
or of the human or natural reason of man,
as to a more noble and certain rule or touchstone; for the divine revelation,
and inward illumination, is that which is evident by itself,
forcing the well-disposed understanding,
and irresistibly moving it to assent by its own evidence and clearness,
even as the common principles of natural truths do bow the mind to a natural assent.

He that denies this part of the proposition must needs affirm,
that the Spirit of God neither can,
nor ever hath manifested itself to man without the Scripture,
or a distinct discussion of reason; or that the efficacy of this supernatural principle,
working upon the souls of men,
is less evident than natural principles in their common operations; both which are false.

For, First, Through all the Scriptures we may observe,
that the manifestation and revelation of God by his Spirit to the patriarchs, prophets,
and apostles, was immediate and objective, as is above proved;
which they did not examine by any other principle, but their own evidence and clearness.

Secondly,
To say that the Spirit of God has less evidence upon
the mind of man than natural principles have,
is to have too mean and low thoughts of it.
How comes David to invite us to "`taste and see that
God is good,`" if this cannot be felt and tasted?
This were enough to overturn the faith and assurance of all the saints,
both now and of old.
How came Paul to be persuaded, that nothing could separate him from the love of God,
but by that evidence and clearness which the Spirit of God gave him?
The apostle John, who knew well wherein the certainty of faith consisted,
judged it no ways absurd, without further argument,
to ascribe his knowledge and assurance, and that of all the saints,
hereunto in these words: "`Hereby know we that we dwell in him, and he in us,
because he hath given us of his Spirit`" (1 John 4:13). And again (5:6):
"`It is the Spirit that beareth witness, because the Spirit is Truth.`"

Observe the reason brought by him, "`Because the Spirit is Truth`";
of whose certainty and infallibility I have heretofore spoken.
We then trust to and confide in this Spirit, because we know, and certainly believe,
that it can only lead us aright, and never mislead us;
and from this certain confidence it is that we affirm,
that no revelation coming from it can ever contradict
the Scriptures`' testimony nor right reason,
not as making this a more certain rule to ourselves, but as condescending to such,
who not discerning the revelations of the Spirit, as they proceed purely from God,
will try them by these mediums.
Yet those that have their spiritual senses, and can savour the things of the Spirit,
as it were in prima instantia, i.e., at the first blush, can discern them without,
or before they apply them either to Scripture or reason;
just as a good astronomer can calculate an eclipse infallibly, by which he can conclude,
if the order of nature continue, and some strange and unnatural revolution intervene not,
there will be an eclipse of the sun or moon such a day, and such an hour;
yet can he not persuade an ignorant rustic of this, until he visibly see it.
So also a mathematician can infallibly know, by the rules of art,
that the three angles of a right triangle are equal to two right angles; yea,
can know them more certainly than any man by measure.
And some geometrical demonstrations are by all acknowledged to be infallible
which can be scarcely discerned or proved by the senses yet if a geometer be
at the pains to certify some ignorant man concerning the certainty of his art,
by condescending to measure it, and make it obvious to his senses,
it will not thence follow, that that measuring is so certain as the demonstration itself;
or that the demonstration would be uncertain without it.

// lint-disable invalid-characters "§"
§XVI.
But to make an end, I shall add one argument to prove, that this inward,
immediate, objective revelation, which we have pleaded for all along, is the only sure,
certain, and unmovable foundation of all Christian faith; which argument,
when well considered, I hope will have weight with all sorts of Christians,
and it is this:

That which all professors of Christianity, of whatsoever kind,
are forced ultimately to recur unto, when pressed to the last;
that for and because of which all other foundations are recommended,
and accounted worthy to be believed,
and without which they are granted to be of no weight at all,
must needs be the only most true, certain,
and unmovable foundation of all Christian faith.

But inward, immediate, objective revelation by the Spirit,
is that which all professors of Christianity, of whatsoever kind,
are forced ultimately to recur unto, etc.

Therefore, etc.

The proposition is so evident, that it will not be denied;
the assumption shall be proved by parts.

And first, as to the Papists,
they place their foundation in the judgment of the church and tradition.
If we press them to say, why they believe as the church doth?
Their answer is, because the church is always led by the infallible Spirit.
So here the leading of the Spirit is the utmost foundation.
Again, if we ask them, why we ought to trust tradition?
They answer,
Because these traditions were delivered us by the doctors and fathers of the church;
which doctors and fathers, by the revelation of the Holy Ghost,
commanded the church to observe them.
Here again all lands^
footnote:[1678 London edition reads "`all ends in...`"]
in the revelation of the Spirit.

And for the Protestants and Socinians,
both which acknowledge the Scriptures to be the foundation and rule of their faith;
the one as subjectively influenced by the Spirit of God to use them,
the other as managing them with and by their own reason: ask both,
or either of them, why they trust in the Scriptures, and take them to be their rule?
Their answer is,
Because we have in them the mind of God delivered
unto us by those to whom these things were inwardly,
immediately and objectively revealed by the Spirit of God;
and not because this or that man wrote them, but because the Spirit of God dictated them.

It is strange then that men should render that so uncertain and dangerous to follow,
upon which alone the certain ground and foundation of their own faith is built;
or that they should shut themselves out from that holy fellowship with God,
which only is enjoyed in the Spirit, in which we are commanded both to walk and live.

If any reading these things find themselves moved,
by the strength of these Scripture arguments,
to assent and believe such revelations necessary,
and yet find themselves strangers to them, which, as I observed in the beginning,
is the cause that this is so much gainsaid and contradicted, let them know,
that it is not because it is ceased to become the privilege
of every true Christian that they do not feel it,
but rather because they are not so much Christians by nature as by name;
and let such know, that the secret Light which shines in the heart,
and reproves unrighteousness, is the small beginnings of the revelation of God`'s Spirit,
which was first sent into the world to reprove it of sin (John 16:8). And as by forsaking
iniquity thou comest to be acquainted with that heavenly voice in thy heart,
thou shalt feel, as the old man, the natural man,
that savoureth not the things of God`'s kingdom, is put off,
with his evil and corrupt affections and lusts; I say, thou shalt feel the new man,
the spiritual birth and babe raised, which hath its spiritual senses, and can see, feel,
taste, handle and smell the things of the Spirit;
but till then the knowledge of things spiritual is but as an historical faith.
But as the description of the light of the sun, or of curious colors to a blind man, who,
though of the largest capacity,
cannot so well understand it by the most acute and lively description,
as a child can by seeing them; so neither can the natural man, of the largest capacity,
by the best words, even Scripture words,
so well understand the mysteries of God`'s kingdom,
as the least and weakest child who tasteth them,
by having them revealed inwardly and objectively by the Spirit.

Wait then for this in the small revelation of that
pure Light which first reveals things more known;
and as thou becomes fitted for it, thou shalt receive more and more,
and by a living experience easily refute their ignorance, who ask,
how dost thou know that thou art acted by the Spirit of God?
Which will appear to thee a question no less ridiculous,
than to ask one whose eyes are open, how he knows the sun shines at noon-day?
And though this be the surest and most certain way to answer all objections;
yet by what is above written it may appear,
that the mouths of all such opposers as deny this doctrine may be shut,
by unquestionable and unanswerable reasons.
