== THE THIRD PROPOSITION

[.chapter-subtitle--blurb]
Concerning the Scriptures

[.heading-continuation-blurb]
From these revelations of the Spirit of God to the
saints have proceeded the Scriptures of Truth,
which contain,

[.heading-continuation-blurb]
I+++.+++ A faithful historical account of the actings of God`'s people in divers ages;
with many singular and remarkable providences attending them.

[.heading-continuation-blurb]
II. A prophetical account of several things, whereof some are already past,
and some yet to come.

[.heading-continuation-blurb]
III. A full and ample account of all the chief principles of the doctrine of Christ,
held forth in divers precious declarations, exhortations and sentences, which,
by the moving of God`'s Spirit, were at several times, and upon sundry occasions,
spoken and written unto some churches and their pastors.

[.heading-continuation-blurb]
Nevertheless, because they are only a declaration of the fountain,
and not the fountain itself,
therefore they are not to be esteemed the principal ground of all Truth and knowledge,
nor yet the adequate primary rule of faith and manners.
Yet because they give a true and faithful testimony of the first foundation,
they are and may be esteemed a secondary rule, subordinate to the Spirit,
from which they have all their excellency and certainty:
for as by the inward testimony of the Spirit we do alone truly know them,
so they testify,
that the Spirit is that Guide by which the saints are led into all Truth; therefore,
according to the Scriptures,
the Spirit is the first and principal leader.^
footnote:[John 16:13, Rom. 8:14.]
Seeing then that we do therefore receive and believe
the Scriptures because they proceeded from the Spirit,
for the very same reason is the Spirit more originally and principally the rule,
according to that received maxim in the schools,
__Propter quod unumquodque est tale, illud ipsum est magis tale:__
That for which a thing is such, that thing itself is more such.

// lint-disable invalid-characters "§"
§I. The former part of this proposition, though it needs no apology for it,
yet it is a good apology for us, and will help to sweep away that,
among many other calumnies, wherewith we are often loaded,
as if we were vilifiers and deniers of the Scriptures;
for in that which we affirm of them, it doth appear at what high rate we value them,
accounting them, without all deceit or equivocation,
the most excellent writings in the world;
to which not only no other writings are to be preferred,
but even in divers respects not comparable thereunto.
For as we freely acknowledge that their authority doth not
depend upon the approbation or canons of any church or assembly;
so neither can we subject them to the fallen, corrupt and defiled reason of man,
and therein as we do freely agree with the Protestants against the error of the Romanists,
so on the other hand,
we cannot go the length of such Protestants as make their authority to
depend upon any virtue or power that is in the writings themselves;
but we desire to ascribe all to that Spirit from which they proceeded.

We confess indeed there wants not a majesty in the style, a coherence in the parts,
a good scope in the whole; but seeing these things are not discerned by the natural,
but only by the spiritual man,
it is the Spirit of God that must give us that belief
of the Scriptures which may satisfy our consciences;
therefore some of the chief among Protestants,
both in their particular writings and public confessions, are forced to acknowledge this.

Hence, Calvin, though he saith he is able to prove that if there be a God in heaven,
these writings have proceeded from him,
yet he concludes another knowledge to be necessary (__Instit. lib. 1,__ cap. 7 section 4).

"`But if,`" saith he, "`we respect the consciences,
that they be not daily molested with doubts and they stick not at every scruple,
it is requisite that this persuasion which we speak of be taken higher than human reason,
judgment, or conjecture; to wit, from the secret testimony of the Spirit.`" And again,
"`To those who ask, that we prove unto them, by reason,
that Moses and the prophets were inspired of God to speak, I answer,
That the testimony of the Holy Spirit is more excellent than all reason.`" And again,
"`Let this remain a firm truth, that he only whom the Holy Spirit hath persuaded,
can repose himself on the Scripture with a true certainty.`" And lastly,
"`This then is a judgment which cannot be begotten but by an heavenly revelation,`" etc.

The same is also affirmed in the first public confession of the French churches,
published in the year 1559 (Art.
4): "`We know these books to be canonical, and the most certain rule of our faith,
not so much by the common accord and consent of the church,
as by the testimony and inward persuasion of the Holy Spirit.`"

Thus also in the fifth article of the confession of faith of the churches of Holland,
confirmed by the Synod of Dort: "`We receive these books only for holy and canonical,
not so much because the church receives and approves them,
as because the Spirit of God doth witness in our hearts that they are of God.`"

And lastly, The divines, so called, at Westminster, who began to be afraid of,
and guard against the testimony of the Spirit,
because they perceived a dispensation beyond that which they were under,
beginning to dawn, and to eclipse them; yet could they not get by this,
though they have laid it down neither so clearly, distinctly,
nor honestly as they that went before.
It is in these words (Chap.
1, sec.
5): "`Nevertheless, our full persuasion and assurance of the infallible truth thereof,
is from the inward work of the Holy Spirit,
bearing witness by and with the Word in our hearts.`"

By all which it appeareth how necessary it is to
seek the certainty of the Scriptures from the Spirit,
and nowhere else.
The infinite janglings and endless contests of those that seek their authority elsewhere,
do witness to the truth hereof.

For the ancients themselves, even of the first centuries,
were not agreed among themselves concerning them;
while some of them rejected books which we approve,
and others of them approved those which some of us reject.^
footnote:[_Concil. Laod. can. 59. in cod. Ecc. 163. Concil. Laod._
held in the year 364, excluded from the canon Eccl.
the Wisdom of Solomon, Judah, Tobias, the Maccabbes,
which the Council of Carthage held in the year 399 received.]
It is not unknown to such as are in the least acquainted with antiquity,
what great contests are concerning the second epistle of Peter, that of James,
the second and third of John, and the Revelations, which many, even very ancient,
deny to have been written by the beloved disciple and brother of James,
but by another of that name.
What should then become of Christians, if they had not received that Spirit,
and those spiritual senses, by which they know how to discern the true from the false?
It is the privilege of Christ`'s sheep indeed that they hear his voice,
and refuse that of a stranger; which privilege being taken away,
we are left a prey to all manner of wolves.

[.small-break]
'''

// lint-disable invalid-characters "§"
§II. Though then we do acknowledge the Scriptures
to be very heavenly and divine writings,
the use of them to be very comfortable and necessary to the church of Christ,
and that we also admire and give praise to the Lord,
for his wonderful providence in preserving these
writings so pure and uncorrupted as we have them,
through so long a night of apostasy,
to be a testimony for his Truth against the wickedness and abominations
even of those whom he made instrumental in preserving them,
so that they have kept them to be a witness against themselves;
yet we may not call them the principal fountain of all Truth and knowledge,
nor yet the first adequate rule of faith and manners;
because the principal fountain of Truth must be the Truth itself; i.e.,
that whose certainty and authority depends not upon another.
When we doubt of the streams of any river or flood, we recur to the fountain itself; and,
having found it, there we sist,^
footnote:[_sist_ +++=+++ stop.]
we can go no farther; because there it springs out of the bowels of the earth,
which are inscrutable.
Even so the writings and sayings of all men we must bring to the Word of God,
I mean the Eternal Word, and if they agree hereunto, we stand there.
For this Word always proceedeth, and doth eternally proceed from God,
in and by which the unsearchable wisdom of God,
and unsearchable counsel and will conceived in the heart of God, is revealed unto us.
That then the Scripture is not the principal ground of faith and knowledge,
as it appears by what is above spoken,
so it is provided in the latter part of the proposition, which,
being reduced to an argument, runs thus:

[.syllogism]
* That, the certainty and authority whereof depends upon another, and which is received as truth because of its proceeding from another, is not to be accounted the principal ground and origin of all Truth and knowledge:
* But the Scriptures`' authority and certainty depend upon the Spirit by which they were dictated; and the reason why they were received as truth is, because they proceeded from the Spirit:
* Therefore they are not the principal ground of Truth.

To confirm this argument, I added the school maxim: _Propter quod unumquodque est tale,
illud ipsum magis est tale._
Which maxim, though I confess it doth not hold universally in all things,
yet in this it both doth and will very well hold, as by applying it,
as we have above intimated, will appear.

The same argument will hold as to the other branch of the position,
_That it is not the primary adequate rule of faith and manners,_ thus:

[.syllogism]
* That which is not the rule of my faith in believing the Scriptures themselves, is not the primary adequate rule of faith and manners:
* But the Scripture is not, nor can it be the rule of that faith by which I believe them, etc.
* Therefore, etc.

[.offset]
But as to this part, we shall produce divers arguments hereafter.
As to what is affirmed, that the Spirit, and not the Scriptures, is the rule,
it is largely handled in the former proposition;
the sum whereof I shall subsume in one argument, thus:

[.syllogism]
* If by the Spirit we can only come to the true knowledge of God; if by the Spirit we are to be led into all Truth, and so be taught of all things; then the Spirit, and not the Scriptures, is the foundation and ground of all Truth and knowledge, and the primary rule of faith and manners:
* But the first is true:
* Therefore also the last.

Next, the very nature of the Gospel itself declareth that the
Scriptures cannot be the only and chief rule of Christians,
else there should be no difference betwixt the Law and the Gospel;
as from the nature of the new covenant,
by divers scriptures described in the former proposition, is proved.

But besides those which are before mentioned, herein doth the Law and the Gospel differ,
in that the Law, being outwardly written, brings under condemnation,
but hath not life in it to save; whereas the Gospel,
as it declares and makes manifest the evil, so, it being an inward powerful thing,
also gives power to obey, and deliver from the evil.
// lint-disable invalid-characters
Hence it is called Εὐαγγέλιον, which is glad tidings.
The Law or letter, which is without us, kills; but the Gospel,
which is the inward spiritual law, gives life;
for it consists not so much in words as in virtue.
Wherefore such as come to know it, and be acquainted with it,
come to feel greater power over their iniquities
than all outward laws or rules can give them.
Hence the apostle concludes (Rom. 6:14), "`Sin shall not have dominion over you:
for ye are not under the Law, but under grace.`" This grace then that is inward,
and not an outward law, is to be the rule of Christians.
Hereunto the apostle commends the elders of the Church, saying (Acts 20:32), "`And now,
brethren, I commend you to God, and to the Word of his Grace,
which is able to build you up,
and to give you an inheritance among all them which are sanctified.`"
He doth not commend them here to outward laws or writings,
but to the Word of Grace, which is inward; even the spiritual law, which makes free,
as he elsewhere affirms (Rom. 8:2), "`The law of the Spirit of life in Christ Jesus,
hath made me free from the law of sin and death.`" This spiritual law is
that which the apostle declares he preached and directed people unto,
which was not outward, as by Romans 10:8 is manifest;
where distinguishing it from the Law, he saith, "`The Word is nigh thee,
even in thy mouth, and in thy heart;
that is the Word of faith which we preach.`" From what is above said I argue thus:

[.syllogism]
* The principal rule of Christians under the Gospel is not an outward letter, nor law outwardly written and delivered, but an inward spiritual law, engraven in the heart, the law of the Spirit of life, the Word that is nigh in the heart and in the mouth.
* But the letter of the Scripture is outward, of itself a dead thing, a mere declaration of good things, but not the things themselves:
* Therefore it is not, nor can be, the chief or principal rule of Christians.

[.offset]
// lint-disable invalid-characters "§"
§III. Thirdly,

[.syllogism]
* That which is given to Christians for a rule and guide, must needs be so full, that it may clearly and distinctly guide and order them in all things and occurrences that may fall out.
* But in that there are many hundred of things, with a regard to their circumstances, particular Christians may be concerned in, for which there can be no particular rule had in the Scriptures;
* Therefore the Scriptures cannot be a rule to them.

I shall give an instance in two or three particulars for to prove this proposition.
It is not to be doubted but some men are particularly called to some particular services;
there being not found in which, though the act be no general positive duty,
yet in so far as it may be required of them, is a great sin to omit;
forasmuch as God is zealous of his glory,
and every act of disobedience to his will manifested,
is enough not only to hinder one greatly from that comfort
and inward peace which otherwise he might have,
but also bringeth condemnation.

As for instance, some are called to the ministry of the Word:
Paul saith there was a "`necessity upon him to preach the Gospel; woe unto me,
if I preach not.`"

If it be necessary that there be now ministers of the Church, as well as then,
then there is the same necessity upon some, more than upon others to occupy this place;
which necessity, as it may be incumbent upon particular persons,
the Scripture neither doth nor can declare.

If it be said, That the qualifications of a minister are found in the Scripture,
and by applying these qualifications to myself,
I may know whether I be fit for such a place or not;

I answer, The qualifications of a bishop, or minister,
as they are mentioned both in the epistle to Timothy and Titus,
are such as may be found in a private Christian; yea,
which ought in some measure to be in every true Christian:
so that this giveth a man no certainty.
Every capacity to an office giveth me not a sufficient call to it.

Next again, By what rule shall I judge if I be so qualified?
How do I know that I am sober, meek, holy, harmless?
Is it not the testimony of the Spirit in my conscience that must assure me hereof?
And suppose that I was qualified and called, yet what Scripture rule shall inform me,
whether it be my duty to preach in this or that place, in France or England,
Holland or Germany?
Whether I shall take up my time in confirming the faithful, reclaiming heretics,
or converting infidels, as also in writing epistles to this or that church?

The general rules of the Scripture, viz: To be diligent in my duty,
to do all to the glory of God, and for the good of his Church,
can give me no light in this thing.
Seeing two different things may both have a respect to that way,
yet may I commit a great error and offence in doing the one,
when I am called to the other.
If Paul, when his face was turned by the Lord toward Jerusalem, had gone back to Achaia,
or Macedonia, he might have supposed he could have done God more acceptable service,
in preaching and confirming the churches, than in being shut up in prison in Judea;
but would God have been pleased herewith?
Nay certainly.
"`Obedience is better than sacrifice`";
and it is not our doing that which is good simply that pleaseth God,
but that good which he willeth us to do.
Every member hath its particular place in the body,
as the apostle showeth (1 Cor. 12). If then I, being the foot,
should offer to exercise the office of the hand; or being the hand, that of the tongue;
my service would be troublesome, and not acceptable; and instead of helping the body,
I should make a schism in it.
So that that which is good for another to do may be sinful to me:
for as masters will have their servants to obey them, according to their good pleasure,
and not only in blindly doing that which may seem
to them to tend to their master`'s profit,
whereby it may chance (the master having business both in the field and in the
house) that the servant that knows not his master`'s will may go to the field,
when it is the mind of the master he should stay and do the business of the house,
would not this servant then deserve a reproof,
for not answering his master`'s mind?
And what master is so sottish and careless, as, having many servants,
leaves them in such disorder as not to assign each his particular station,
and not only the general term of doing that which is profitable?
which would leave them in various doubts, and no doubt land in confusion.

Shall we then dare to ascribe unto Christ, in the ordering of his church and servants,
that which in man might justly be accounted disorder and confusion?
The apostle showeth this distinction well (Rom. 12:6-8):
"`Having then gifts differing according to the grace that is given to us;
whether prophecy, let us prophesy according to proportion of faith; or ministry,
let us wait on our ministering; or he that teacheth, on teaching; or he that exhorteth,
on exhortation.`" Now what Scripture rule showeth me that I ought to exhort,
rather than prophesy?
or minister, rather than teach?
Surely none at all.
Many more difficulties of this kind occur in the life of a Christian.

Moreover, that which of all things is most needful for him to know, to wit,
whether he really be in the faith, and an heir of salvation, or no,
the Scripture can give him no certainty in, neither can it be a rule to him.
That this knowledge is exceeding desirable and comfortable all do unanimously acknowledge;
besides that it is especially commanded (2 Cor. 13:5), "`Examine yourselves,
whether ye be in the faith, prove your own selves.
Know ye not your own selves, how that Jesus Christ is in you,
except ye be reprobates?`" And (2 Pet. 1:10), "`Wherefore the rather, brethren,
give diligence to make your calling and election sure.`" Now I say,
What Scripture rule can assure me that I have true faith?
That my calling and election is sure?

If it be said, by comparing the Scripture marks of true faith with mine:

I demand, wherewith shall I make this observation?
What shall ascertain me that I am not mistaken?
It cannot be the Scripture: that is the matter under debate.

If it be said, My own heart:

How unfit a judge is it in its own case?
And how like to be partial, especially if it be yet unrenewed?
Doth not the Scripture say, that it is "`deceitful above all things?`" I find the promises,
I find the threatenings, in the Scripture;
but who telleth me that the one belongs to me more than the other?
The Scripture gives me a mere declaration of these things, but makes no application;
so that the assumption must be of my own making, thus; as for example:
I find this proposition in the Scripture;

[.syllogism]
* "`He that believes shall be saved`": thence I draw this assumption:
* But _I, Robert, believe;_
* Therefore _I shall be saved._

The minor is of my own making, not expressed in the Scripture; and so a human conclusion,
not a divine position;
so that my faith and assurance here is not built upon a Scripture proposition,
but upon an human principle; which, unless I be sure of elsewhere,
the Scripture gives me no certainty in the matter.

Again, if I should pursue the argument further,
and seek a new medium out of the Scripture, the same difficulty would occur: thus,

[.syllogism]
* He that hath the true and certain marks of true faith; hath true faith:
* But I have those marks:
* Therefore I have true faith.

For the assumption is still here of my own making, and is not found in the Scriptures;
and by consequence the conclusion can be no better,
since it still followeth the weaker proposition.
This is indeed so pungent, that the best of Protestants, who plead for this assurance,
ascribe it to the inward testimony of the Spirit; as Calvin, in that large citation,
cited in the former proposition.
So that, not to seek further into the writings of the primitive Protestants,
which are full of such expressions,
even the Westminster Confession of Faith affirmeth (chap.
18, sect.
12), "`This certainty is not bare conjecture and probable persuasion,
grounded upon fallible hope, but an infallible assurance of faith,
founded upon the divine truth of the promise of salvation;
the inward evidences of these graces, unto which these promises are made;
the testimony of the Spirit of adoption,
witnessing to our spirits that we are the children of God;
which Spirit is the earnest of our inheritance whereby we are sealed to the day of redemption.`"

Moreover, the Scripture itself,
wherein we are so earnestly pressed to seek after this assurance,
doth not at all affirm itself a rule sufficient to give it,
but wholly ascribeth it to the Spirit, as (Rom. 8:16),
"`The Spirit itself beareth witness with our spirit, that we are the children of God`";
(1 John 4:13) "`Hereby know we that we dwell in him, and he in us,
because he hath given us of his Spirit`"; and (5:6),
"`And it is the Spirit that beareth witness, because the Spirit is Truth.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§IV. Lastly, That cannot be the only, principal nor chief rule,
which doth not universally reach every individual that needeth it,
to produce the necessary effect;
and from the use of which (either by some innocent and sinless defect,
or natural yet harmless and blameless imperfection)
many who are within the compass of the visible church,
and may, without absurdity, yea, with great probability, be accounted of the elect,
are necessarily excluded, and that either wholly,
or at least from the immediate use thereof.
But it so falls out frequently concerning the Scriptures, in the case of deaf people,
children, and idiots, who can by no means have the benefit of the Scripture.
Shall we then affirm, that they are without any rule to God-ward,
or that they are all damned?
As such an opinion is in itself very absurd,
and inconsistent both with the justice and mercy of God,
so I know no sound reason can be alleged for it.
Now if we may suppose any such to be under the New Covenant dispensation,
as I know none will deny but that we may suppose it without any absurdity,
we cannot suppose them without some rule and means of knowledge;
seeing it is expressly affirmed,
"`They shall be all taught of God`" (John 6:45). "`And they all shall know
me from the least to the greatest`" (Heb. 8:11). But secondly,
though we were rid of this difficulty,
how many illiterate and yet good men are there in the church of God,
who cannot read a letter in their own mother tongue?
Which imperfection, though it be inconvenient,
I cannot tell whether we may safely affirm it to be sinful.
These can have no immediate knowledge of the rule of their faith;
so their faith must needs depend upon the credit
of other men`'s reading or relating it unto them;
where either the altering, adding,
or omitting of a little word may be a foundation
in the poor hearer of a very dangerous mistake,
whereby he may either continue in an iniquity ignorantly, or believe a lie confidently.
As for example, the Papists in all their catechisms,
and public exercises of examinations towards the people,
have boldly cut away the second command,
it seems so expressly to strike against their adoration and use of images;
whereas many of these people, in whom by this omission this false opinion is fostered,
are under a simple impossibility, or at least a very great difficulty,
to be outwardly informed of this abuse.
But further; suppose all could read the Scriptures in their own language;
where is there one of a thousand that hath that thorough
knowledge of the original languages in which they were written,
so as in that respect immediately to receive the benefit of them?
Must not all these here depend upon the honesty and faithfulness of the interpreters?
Which how uncertain it is for a man to build his faith upon, the many corrections,
amendments, and various essays, which even among Protestants have been used,
whereof the latter have constantly blamed and corrected the former,
as guilty of defects and errors, doth sufficiently declare.
And that even the last translations in the vulgar languages
need to be corrected (as I could prove at large,
were it proper in this place), learned men do confess.
But last of all,
there is no less difficulty even occurs to those skilled in the original languages,
who cannot so immediately receive the mind of the authors in these writings,
as that their faith doth not at least obliquely depend
upon the honesty and credit of the transcribers,
since the original copies are granted by all not to be now extant.

Of which transcribers Jerome in his time complained,
saying that "`they wrote not what they found,
but what they understood.`" And Epiphanius saith,
That in the good and correct copies of Luke it was written, that Christ wept,
and that Irenaeus doth cite it; but that the Catholics blotted it out,
fearing lest heretics should have abused it.
Other fathers also declare that whole verses were taken out of Mark,
because of the Manichees.^
footnote:[Jerome, _epist. 28 ad Lucin. pag. 247._ Epiphan. _in Anchor. Tom. 2. oper._]

But further,
the various lections of the Hebrew character by reason of the _points,_
which some plead for, as coevous^
footnote:[_coevous_ +++=+++ of the same age.]
with the first writings, which others, with no less probability,
allege to be a later invention;
the disagreement of divers citations of Christ and the apostles
with those passages in the Old Testament they appeal to;
the great controversy among the fathers,
whereof some highly approve the Greek Septuagint,
decrying and rendering very doubtful the Hebrew copy, as in many places vitiated,
and altered by the Jews, other some, and particularly Jerome,
exalting the certainty of the Hebrew, and rejecting, yea,
even deriding the history of the Septuagint,
which the primitive church chiefly made use of;
and some Fathers that lived centuries before him, affirmed to be a most certain thing.
Add the many various lections in divers copies of the Greek,
and the great altercations among the Fathers of the first three centuries (who
had greater opportunity to be better informed than we can now lay claim to),
concerning the books to be admitted or rejected, as above is observed; I say,
all these and much more which might be alleged,
puts the minds even of the learned into infinite doubts, scruples,
and inextricable difficulties.
Whence we may very safely conclude, that Jesus Christ,
who promised to be always with his children, to lead them into all Truth,
to guard them against the devices of the enemy,
and to establish their faith upon an unmovable rock,
left them not to be principally ruled by that,
which was subject in itself to many uncertainties: and therefore he gave them his Spirit,
as their principal guide, which neither moths nor time can wear out,
nor transcribers nor translators corrupt; which none are so young, none so illiterate,
none in so remote a place, but they may come to be reached, and rightly informed by it.

Through and by the clearness which that Spirit gives us, it is,
that we are only best rid of those difficulties that occur to us concerning the Scriptures.
The real and undoubted experience whereof I myself have been a witness of,
with great admiration of the love of God to his children in these latter days:
for I have known some of my friends, who profess the same faith with me,
faithful servants of the Most High God, and full of divine knowledge of his Truth,
as it was immediately and inwardly revealed to them by the Spirit,
from a true and living experience, who not only were ignorant of the Greek and Hebrew,
but even some of them could not read their own vulgar language,
who being pressed by the adversaries with some citations out of the English translation,
and finding them to disagree with the manifestation of Truth in their hearts,
have boldly affirmed the Spirit of God never said so, and that it was certainly wrong;
for they did not believe that any of the holy prophets or apostles had ever written so;
which when I on this account seriously examined,
I really found to be errors and corruptions of the translators; who,
as in most translations, do not so much give us the genuine signification of the words,
as strain them to express that which comes nearest
to that opinion and notion they have of Truth.
And this seemed to me to suit very well with that saying of Augustine (Epist.
19, ad Hier. Tom ii fol. 14), after he has said,
"`That he gives only that honor to those books which are called canonical,
as to believe that the authors thereof did in writing not err,`" he adds,
"`And if I shall meet with anything in these writings that seemeth repugnant to Truth,
I shall not doubt to say, that either the volume is faulty or erroneous;
that the expounder hath not reached what was said;
or that I have in no wise understood it.`" So that he supposes
that in the transcription and translation there may be errors.

[.small-break]
'''

// lint-disable invalid-characters "§"
§V. If it be then asked me,
Whether I think hereby to render the Scriptures altogether uncertain, or useless?

I answer; Not at all.
The proposition itself declares what esteem I have for them;
and provided that to the Spirit from which they came be
but granted that place the Scriptures themselves give it,
I do freely concede to the Scriptures the second place,
even whatsoever they say of themselves;
which the apostle Paul chiefly mentions in two places (Rom. 15:4):
"`Whatsoever things were written aforetime, were written for our learning,
that we through patience and comfort of the Scriptures might have hope`";
(2 Tim. 3:15-17): "`The holy Scriptures are able to make wise unto salvation,
through faith which is in Christ Jesus.
All Scripture given by inspiration from God, is profitable for correction,
for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good work.`"

For though God do principally and chiefly lead us by his Spirit,
yet he sometimes conveys his comfort and consolation to us through his children,
whom he raises up and inspires to speak or write a word in season,
whereby the saints are made instruments in the hand of the
Lord to strengthen and encourage one another,
which do also tend to perfect and make them wise unto salvation;
and such as are led by the Spirit cannot neglect,
but do naturally love and are wonderfully cherished by that
which proceedeth from the same Spirit in another;
because such mutual emanations of the heavenly life tend to quicken
the mind when at any time it is overtaken with heaviness.
Peter himself declares this to have been the end of his writing (2 Pet. 1:12-13):
"`Wherefore I will not be negligent to put you always in remembrance of these things,
though ye know them, and be established in the present Truth; yea, I think it meet,
as long as I am in this tabernacle, to stir you up, by putting you in remembrance.`"

God is teacher of his people himself; and there is nothing more express,
than that such as are under the new covenant, they need no man to teach them:
yet it was a fruit of Christ`'s ascension to send
teachers and pastors for perfecting of the saints.
So that the same work is ascribed to the Scriptures as to teachers;
the one to make the man of God perfect, the other for the perfection of the saints.

As then teachers are not to go before the teaching of God himself under the new covenant,
but to follow after it;
neither are they to rob us of that great privilege
which Christ hath purchased unto us by his blood;
so neither is the Scripture to go before the teaching of the Spirit, or to rob us of it.

Secondly, God hath seen meet that herein we should, as in a looking-glass,
see the conditions and experiences of the saints of old;
that finding our experience answer to theirs,
we might thereby be the more confirmed and comforted,
and our hope of obtaining the same end strengthened;
that observing the providences attending them, seeing the snares they were liable to,
and beholding their deliverances, we may thereby be made wise unto salvation,
and seasonably reproved and instructed in righteousness.

This is the great work of the Scriptures, and their service to us,
that we may witness them fulfilled _in_ us,
and so discern the stamp of God`'s spirit and ways upon them,
by the inward acquaintance we have with the same Spirit and work in our hearts.
The prophecies of the Scriptures are also very comfortable and profitable unto us,
as the same Spirit enlightens us to observe them fulfilled, and to be fulfilled;
for in all this it is to be observed,
that it is only the spiritual man that can make a right use of them:
they are able to make the man of God perfect (so it is not the natural man);
and whatsoever was written aforetime, was written for __our comfort, +++[+++our]__
that are the believers, __+++[+++our]__
that are the saints; concerning such the apostle speaks: for as for the others,
the apostle Peter plainly declares,
that the "`unstable and unlearned wrest them to their own destruction`":
these were they that were unlearned in the divine and heavenly learning of the Spirit,
not in human and school literature; of which we may safely presume that Peter himself,
being a fisherman, had no great skill; for it may with great probability, yea certainty,
be affirmed, that he had no knowledge of Aristotle`'s logic,
which both Papists and Protestants, now degenerating from the simplicity of Truth,
make handmaid of divinity, as they call it, and a necessary introduction to their carnal,
natural, and human ministry.
By the infinite obscure labours of which kind of men, mixing-in their heathenish stuff,
the Scripture is rendered at this day of so little service to the simple people:
whereof if Jerome complained in his time, now twelve hundred years ago __(Epist.
134, ad Cypr. Tom. 3),__ saying, "`It is wont to befall the most part of learned men,
that it is harder to understand their expositions,
than the things which they go about to expound`"; what may we say then,
considering those great heaps of commentaries since, in ages yet far more corrupted?

[.small-break]
'''

// lint-disable invalid-characters "§"
§VI. In this respect above mentioned, then,
we have shown what service and use the holy Scriptures, as managed in and by the Spirit,
are of to the church of God; wherefore we do account them a secondary rule.
Moreover,
because they are commonly acknowledged by all to
have been written by the dictates of the Holy Spirit,
and that the errors which may be supposed by the injury of times
to have slipped in are not such but that there is a sufficient
clear testimony left to all the essentials of the Christian faith;
we do look upon them as the only fit outward judge of controversies among Christians;
and that whatsoever doctrine is contrary unto their
testimony may therefore justly be rejected as false.
And for our parts,
we are very willing that all our doctrines and practices be tried by them;
which we never refused, nor ever shall, in all controversies with our adversaries,
as the judge and test.
We shall also be very willing to admit it as a positive certain maxim,
__That whatsoever any do, pretending to the Spirit, which is contrary to the Scriptures,
be accounted and reckoned a delusion of the devil.__
For as we never lay claim to the Spirit`'s leadings
that we may cover ourselves in anything that is evil;
so we know that as every evil contradicts the Scriptures
so it doth also the Spirit in the first place,
from which the Scriptures came and whose motions can never contradict one another,
though they may appear sometimes to be contradictory to the blind eye of the natural man,
as Paul and James seem to contradict one another.

Thus far we have shown both what we believe, and what we believe not,
concerning the holy Scriptures, hoping we have given them their due place.
But since they that will needs have them to be the only, certain, and principal rule,
want not some show of arguments,
even from the Scripture itself (though it no where calls
itself so) by which they labour to prove their doctrine;
I shall briefly lay them down by way of objections, and answer them,
before I make an end of this matter.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VII.
Their first objection is usually drawn from Isa. 8:20,
"`To the law and to the testimony; if they speak not according to this Word,
it is because there is no Light in them.`" Now this "`law,`"
"`testimony,`" and "`Word,`" they plead to be the Scriptures.

To which I answer, That is to beg the thing in question, and remains yet unproved.
Nor do I know for what reason we may not
safely affirm this law and Word to be inward:
but suppose it was outward, it proves not the case at all for them,
neither makes it against us; for it may be confessed, without any prejudice to our cause,
that the outward law was more particularly to the Jews a rule,
and more principally than to us; seeing their law was outward and literal, but ours,
under the New Covenant, as hath been already said,
is expressly affirmed to be inward and spiritual;
so that this scripture is so far from making against us, that it makes for us.
For if the Jews were directed to try all things by their law, which was without them,
written in tables of stone; then if we will have this advice of the prophet to reach us,
we must make it hold parallel to that dispensation of the Gospel which we are under:
so that we are to try all things, in the first place,
by that "`Word of faith`" which is preached unto us,
which the apostle saith is "`in the heart`"; and by that law which God hath given us,
which the apostle saith also expressly is written and placed in the mind.

Lastly, If we look to this place according to the Greek interpretation of the Septuagint,
our adversaries shall have nothing from thence to carp; yea, it will favour us much;
for there it is said that "`the law is given us for a help`";
which very well agrees with what is above asserted.

Their second objection is from John 5:39, "`Search the Scriptures,`" etc.

Here, say they, we are commanded, by Christ himself, to search the Scriptures.

I answer, First, that the Scriptures ought to be searched, we do not at all deny;
but are very willing to be tried by them, as hath been above declared:
but the question is, whether they be the only and principal rule?
Which this is so far from proving, that it proveth the contrary;
for Christ checks them here for too high an esteem of the Scriptures,
and neglecting of him that was to be preferred before them,
and to whom they bore witness, as the following words declare;
"`for in them ye think ye have eternal life, and they are they which testify of me:
and ye will not come unto me,
that ye might have life.`" This shows that while they
thought they had eternal life in the Scriptures,
they neglected to come unto Christ to have life, of which the Scriptures bore witness.
This answers well to our purpose, since our adversaries now do also exalt the Scriptures,
and think to have life in them;
which is no more than to look upon them as the only principal rule and way to life,
and yet refuse to come unto the Spirit of which they testify,
even the inward spiritual law, which could give them life.
So that the cause of this people`'s ignorance and unbelief
was not their want of respect to the Scriptures,
which though they knew, and had a high esteem of,
yet Christ testifies in the former verses, that they had "`neither seen the Father,
nor heard his voice at any time; neither had his Word abiding in them`";
which had they then had, then they had believed in the Son.
Moreover that place may be taken in the indicative mood,
"`Ye search the Scriptures`"; which interpretation the Greek word will bear,
and so Pasor translateth it:
which by the reproof following seemeth also to be the more genuine interpretation,
as Cyril long ago hath observed.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VIII.
Their third objection is from these words (Acts 17:11),
"`These were more noble than those in Thessalonica in that
they received the Word with all readiness of mind,
and searched the Scriptures daily, whether those things were so.`"

_Obj._ Here, say they, the Bereans are commended for searching the Scriptures,
and making them the rule.

I answer: That the Scriptures either are the principal or only rule,
will not at all from this follow; neither will their searching the Scriptures,
or being commended for it, infer any such thing:
for we recommend and approve the use of them in that respect as much as any;
yet will it not follow, that we affirm them to be the principal and only rule.

Secondly, It is to be observed that these were the Jews of Berea,
to whom these Scriptures, which were the law and the prophets,
were more particularly a rule; and the thing under examination was, whether the birth,
life, works, and sufferings of Christ,
did answer to the prophecies that went before of him;
so that it was most proper for them, being Jews,
to examine the apostle`'s doctrine by the Scriptures;
seeing he pleaded it to be a fulfilling of them.
It is said nevertheless, in the first place,
that "`they received the Word with cheerfulness`"; and in the second place,
"`They searched the Scriptures`": not that they searched the Scriptures,
and then received the Word; for then could not they have prevailed to convert them,
had they not first minded the __Word abiding in them,__ which opened their understandings;
no more than the Scribes and Pharisees,
who (as in the former objection we observed) searched the Scriptures and exalted them,
and yet remained in their unbelief, because they had not the Word abiding in them.

But lastly,
If this commendation of the Jewish Bereans might infer that the Scriptures
were the only and principal rule to try the apostles`' doctrine by,
what should have become of the Gentiles?
How should they ever come to have received the faith of Christ,
who neither knew the Scriptures, nor believed them?
We see in the end of the same chapter, how the apostle, preaching to the Athenians,
took another method, and directed them to somewhat of God _within_ themselves,
that they might __feel after__ him.
He did not go about to proselyte them to the Jewish religion,
and to the belief of the law and the prophets,
and from thence to prove the coming of Christ; nay, he took a nearer way.
Now certainly the principal and only rule is not different--one to the Jews,
and another to the Gentiles--but is universal, reaching both:
though secondary and subordinate rules and means may be various, and diversely suited,
according as the people they are used to are stated and circumstantiated:
even so we see that the apostle to the Athenians
used a testimony of one of their own poets,
which he judged would have credit with them; and no doubt such testimonies,
whose authors they esteemed,
had more weight with them than all the sayings of Moses and the prophets,
whom they neither knew nor would have cared for.
Now because the apostle used the testimony of a poet to the Athenians,
will it therefore follow he made that the principal or only rule to try his doctrine by?
So neither will it follow, that though he made use of the Scriptures to the Jews,
as being a principle already believed by them, to try his doctrine,
that from thence the Scriptures may be accounted the principal or only rule.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IX. The last, and which at first view seems to be the greatest objection,
is this:

_Obj._
If the Scripture be not the adequate, principal, and only rule,
then it would follow that the Scripture is not complete, nor the canon filled;
that if men be now immediately led and ruled by the Spirit,
they may add new scriptures of equal authority with the old;
whereas everyone that adds is cursed: yea, what assurance have we,
but at this rate everyone may bring in a new Gospel according to his fancy?

The dangerous consequences insinuated in this objection
were fully answered in the latter part of the last proposition,
in what was said a little before,
offering freely to disclaim all pretended revelations contrary to the Scriptures.

_Obj._
But if it be urged, that it is not enough to deny these consequences,
if they naturally follow from your doctrine of immediate revelation,
and denying the Scripture to be the only rule:

I answer; We have proved both these doctrines to be true and necessary,
according to the Scriptures themselves;
and therefore to fasten evil consequences upon them,
which we make appear do not follow, is not to accuse us, but Christ and his apostles,
who preached them.

But secondly, we have shut the door upon all such doctrine in this very position;
affirming,
That the Scriptures give a full and ample testimony
to all the principal doctrines of the Christian faith.
For we do firmly believe that there is no other gospel or doctrine to be preached,
but that which was delivered by the apostles; and do freely subscribe to that saying,
"`Let him that preacheth any other gospel,
than that which hath been already preached by the apostles,
and according to the Scriptures, be accursed.`"^
footnote:[Gal. 1:8-9.]

So we distinguish betwixt a revelation of a new gospel, and new doctrines,
and a new revelation of the good old Gospel and doctrines; the last we plead for,
but the first we utterly deny.
For we firmly believe, That "`no other foundation can any man lay,
than that which is laid already.`" But that this revelation
is necessary we have already proved;
and this distinction doth sufficiently guard us against
the hazard insinuated in the objection.

As to the Scriptures being a __filled canon,__ I see no necessity of believing it.
And if these men, that believe the Scriptures to be the only rule,
will be consistent with their own doctrine, they must needs be of my judgment;
seeing it is simply impossible to prove the canon by the Scriptures.
For it cannot be found in any book of the Scriptures, that these books, and just these,
and no other, are canonical, as all are forced to acknowledge;
how can they then evite this argument?

[.syllogism]
* That which cannot be proved by Scripture is no necessary article of faith.
* But the canon of the Scripture; to wit, that there are so many books precisely, neither more nor less, cannot be proved by Scripture:
* Therefore, it is no necessary article of faith.

_Obj._
If they should allege,
that the admitting of any other books to be now written by the
same Spirit might infer the admission of new doctrines;

I deny that consequence;
for the principal or fundamental doctrines of the Christian
religion are contained in the tenth part of the Scripture;
but it will not follow thence that the rest are impertinent or useless.
If it should please God to bring to us any of those books,
which by the injury of time are lost, which are mentioned in the Scripture; as,
The Prophecy of Enoch; the Book of Nathan, etc., or,
the Third Epistle of Paul to the Corinthians;
I see no reason why we might not receive them and place them with the rest.
That which displeaseth me is,
that men should first affirm that the Scripture is the only and principal rule,
and yet make a great article of faith of that which
the Scripture can give us no light in.

As for instance: How shall a Protestant prove by Scripture,
to such as deny the Epistle of James to be authentic, that it ought to be received?

First, if he should say,
because it contradicts not the rest (besides that
there is no mention of it in any of the rest),
perhaps these men think it doth contradict Paul in relation to faith and works.
But, if that should be granted, it would as well follow,
that every writer that contradicts not the Scripture, should be put into the canon;
and by this means these men fall into a greater absurdity than they fix upon us:
for thus they would equal every one the writings of their own sect with the Scriptures;
for I suppose they judge their own confession of faith doth not contradict the Scriptures:
will it therefore follow that it should be bound up with the Bible?
And yet it seems impossible, according to their principles,
to bring any better argument to prove the Epistle of James to be authentic.
There is then this unavoidable necessity to say,
We know it by the same Spirit from which it was written;
or otherwise to step back to Rome, and say,
We know by tradition that the church hath declared it to be canonical;
and the church is infallible.
Let them find a midst, if they can.
So that out of this objection we shall draw an unanswerable argument __ad hominem,__
to our purpose.

[.syllogism]
* That which cannot assure me concerning an article of faith necessary to be believed, is not the primary, adequate, only rule of faith, etc.
* But the Scripture cannot thus assure me;
* Therefore, etc.

[.offset]
I prove the assumption thus:

[.syllogism]
* That which cannot assure me concerning the canon of the Scripture, to wit, that such books are only to be admitted, and the Apocrypha to be excluded, cannot assure me of this.
* Therefore, etc.

_Obj._
And lastly, As to these words (Rev. 22:18),
That "`if any man shall add unto these things,
God shall add unto him the plagues that are written in this book`";
I desire they will show me how it relates to anything else than to that particular prophecy.
It saith not, "`now the canon of the Scriptures is filled up,
no man is to write more from that Spirit`"; yea,
do not all confess that there have been prophecies and true prophets since?
The Papists deny it not.
And do not the Protestants affirm, that John Huss prophesied of the Reformation?
Was he therefore cursed?
or did he therein evil?
I could give many other examples, confessed by themselves.
But, moreover, the same was in effect commanded long before (Prov. 30:6),
"`Add thou not unto his words, lest he reprove thee, and thou be found a liar`":
yet how many books of the prophets were written after?
And the same was said by Moses (Duet. 4:2),
"`Ye shall not add unto the word which I command you;
neither shall ye diminish aught from it.`" So that though we should extend
that of the Revelation beyond the particular prophecy of that book,
it cannot be understood but of a new gospel, or new doctrines,
or of restraining man`'s spirit, that he mix not his human words with the divine;
and not of a new revelation of the old, as we have said before.
