== THE FOURTH PROPOSITION

Concerning the Condition of Man in the Fall

All Adam`'s posterity (or mankind), both Jews and Gentiles,
as to the first Adam (or earthly man), is fallen, degenerated, and dead;
deprived of the sensation (or feeling) of this inward testimony or seed of God;^
footnote:[Rom. 5:12,15.]
and is subject unto the power, nature, power, nature, and seed of the serpent,
which he soweth in men`'s hearts,
while they abide in this natural and corrupted estate:
from whence it comes that not only their words and deeds but all
their imaginations are evil perpetually in the sight of God,
as proceeding from this depraved and wicked seed.
Man therefore, as he is in this state, can know nothing aright;
yea his thoughts and conceptions concerning God and things spiritual,
until he be disjoined from this evil seed and united to the Divine Light,
are unprofitable both to himself and others.
Hence are rejected the Socinian and Pelagian errors in exalting a natural light,
as also of the Papists and most of Protestants,
who affirm that man without the true grace of God may be a true minister of the Gospel.
Nevertheless this seed is not imputed to infants until by
transgression they actually join themselves therewith:
for they are by nature "`the children of wrath`" who walk
according to the "`power of the prince of the air,
the spirit that now worketh in the children of disobedience,`"
having their conversation in the lusts of the flesh,
fulfilling the desires of the flesh and of the mind (Eph. 2).

// lint-disable invalid-characters "§"
§I. Hitherto we have discoursed how the true
knowledge of God is attained and preserved;
also of what use and service the holy Scripture is to the saints.

We come now to examine the state and condition of man as he stands in the fall:
what his capacity and power is and how far he is able, as of himself,
to advance in relation to the things of God.
Of this we touched a little in the beginning of the second Proposition; but the full,
right, and thorough understanding of it is of great use and service;
because from the ignorance and altercations that have been about it,
there have arisen great and dangerous errors, both on the one hand and the other.
While some do so far exalt the light of nature, or the faculty of the natural man,
as capable of himself, by virtue of the inward will, faculty, light,
or power that pertains to his nature,
to follow that which is good and make real progress towards heaven.
And of these are the Pelagians and Semi-Pelagians of old,
and of late the Socinians and divers others among the Papists.
Others again will needs run into another extreme, to whom Augustine,
among the ancients, first made way in his declining age,
through the heat of his zeal against Pelagius,
not only confessing men incapable of themselves to do good, and prone to evil;
but that in his very mother`'s womb, and before he commits any actual transgression,
he is contaminate with a real guilt whereby he deserves eternal death;
in which respect they are not afraid to affirm that many poor infants
are eternally damned and forever endure the torments of hell.
Therefore the God of Truth, having now again revealed his Truth that good and even way,
by his own Spirit, hath taught us to avoid both these extremes.

That then which our proposition leads to treat of is,

First, What the condition of man is in the fall;
and how far incapable to meddle in the things of God.

And, secondly, That God doth not impute this evil to infants,
until they actually join with it: that so, by establishing the Truth,
we may overturn the errors on both parts.

And as for that third thing included in the proposition itself
concerning these teachers which want the grace of God,
we shall refer that to the Tenth Proposition,
where the matter is more particularly handled.

// lint-disable invalid-characters "§"
§II. As to the first,
not to dive into the many curious notions which many have
concerning the condition of Adam before the fall,
all agree in this; that thereby he came to a very great loss,
not only in the things which related to the outward man,
but in regard of that true fellowship and communion he had with God.
This loss was signified unto him in the command, "`For in the day thou eatest thereof,
thou shalt surely die`" (Gen. 2:17). This death could not be an outward death,
or the dissolution of the outward man; for as to that,
he did not die yet many hundred years after;
so that it must needs respect his spiritual life and communion with God.
The consequence of this fall, besides that which relates to the fruits of the earth,
is also expressed (Gen. 3:24), "`So he drove out the man,
and he placed at the east of the garden of Eden cherubims, and a flaming sword,
which turned every way,
to keep the way of the tree of life.`" Now whatsoever literal signification this may have,
we may safely ascribe to this paradise a mystical signification,
and truly account it that spiritual communion and fellowship,
which the saints obtain with God by Jesus Christ;
to whom only these cherubims give way, and unto as many as enter by him,
who calls himself the Door.
So that, though we do not ascribe any whit of Adam`'s guilt to men,
until they make it theirs by the like acts of disobedience;
yet we cannot suppose that men, who are come of Adam naturally,
can have any good thing in their nature, as belonging to it; which he,
from whom they derive their nature, had not himself to communicate unto them.

If then we may affirm that Adam did not retain in his nature (as belonging thereunto)
any will or light capable to give him knowledge in spiritual things,
then neither can his posterity; for whatsoever real good any man doth,
it proceedeth not from his nature as he is man or the son of Adam,
but from the seed of God in him, as a new visitation of life,
in order to bring him out of this natural condition: so that though it be in him,
yet it is not of him; and this the Lord himself witnessed (Gen. 6:5),
where it is said,
he "`saw that every imagination of the thoughts of his heart was only evil continually`":
which words, as they are very positive, so are they very comprehensive.
Observe the emphasis of them: First,
there is "`every imagination of the thoughts of his heart`";
so that this admits of no exception of any imagination of the thoughts of his heart.
Secondly, "`is only evil continually`"; it is neither in some part evil continually,
nor yet only evil at some times; but both only evil and always and continually evil;
which certainly excludes any good as a proper effect of man`'s heart, naturally:
for that which is only evil, and that always,
cannot of its own nature produce any good thing.
The Lord expressed this again a little after (chap.
8:21),
"`The imagination of man`'s heart is evil from his youth.`"
Thus inferring how natural and proper it is unto him;
from which I thus argue:

If the thoughts of man`'s heart be not only evil, but always evil; then are they,
as they simply proceed from his heart, neither good in part, nor at any time.

But the first is true;

Therefore also the last.

Again,

If man`'s thoughts be always and only evil,
then are they altogether useless and ineffectual to him in the things of God.

But the first is true;

Therefore also the last.

Secondly, this appears clearly from that saying of the prophet (Jer. 17:9),
"`The heart is deceitful above all things,
and desperately wicked.`" For who can with any color of reason imagine,
that that which is so hath any power of itself,
or is in any wise fit to lead a man to righteousness,
whereunto it is of its own nature directly opposite?
This is as contrary to reason, as it is impossible in nature that a stone,
of its own nature and proper motion, should fly upwards.
For as a stone of its own nature inclineth and is
prone to move downwards towards the center,
so the heart of man is naturally prone and inclined to evil, some to one,
and some to another.
From this then I also thus argue:

That which is "`deceitful above all things, and desperately wicked,`" is not fit,
neither can it lead a man aright in things that are good and honest.

But the heart of man is such:

Therefore, etc.

But the apostle Paul describeth the condition of men in the fall at large,
taking it out of the Psalmist.
"`There is none righteous, no not one: there is none that understandeth,
there is none that seeketh after God.
They are all gone out of the way, they are altogether become unprofitable;
there is none that doth good, no not one.
Their throat is an open sepulchre, with their tongues they have used deceit,
the poison of asps is under their lips: whose mouths are full of cursing and bitterness.
Their feet are swift to shed blood; destruction and misery are in their ways:
and the way of peace have they not known.
There is no fear of God before their eyes.`"^
footnote:[Rom. 3:10-18, Ps. 14:3,53:2, etc.]
What more positive can be spoken?
He seemeth to be particularly careful to avoid that
any good should be ascribed to the natural man;
he shows how he is polluted in all his ways; he shows how he is void of righteousness,
of understanding, of the knowledge of God; how he is out of the way,
and in short unprofitable;
than which nothing can be more fully said to confirm our judgment:
for if this be the condition of the natural man, or of man as he stands in the fall,
he is unfit to make one right step to heaven.

Obj.
If it be said, that is not spoken of the condition of man in general;
but only of some particulars, or at least that it comprehends not all;

Answ.
The text showeth the clean contrary in the foregoing verses,
where the apostle takes in himself, as he stood in his natural condition.
"`What then?
Are we better than they?
No, in no wise; for we have before proved both Jews and Gentiles,
that they are all under sin, as it is written`": and so he goes on:
by which it is manifest that he speaks of mankind in general.

Obj.
If they object that which the same apostle saith in the foregoing chapter (verse 14),
to wit,
that the Gentiles "`do by nature the things contained in the Law,`" and so consequently
do by nature that which is good and acceptable in the sight of God;

Answ.
I answer: This "`nature`" must not, neither can be understood of man`'s own nature,
which is corrupt and fallen;
but of that spiritual nature which proceedeth from the seed of God in man as
it receiveth a new visitation of God`'s love and is quickened by it:
which clearly appears by the following words, where he saith,
"`These having not the law`" (i.e., outwardly) "`are a law unto themselves;
which show the work of the law written in their hearts.`" These
acts of theirs then are an effect of the law written in their hearts;
but the Scripture declareth that the writing of the law in the heart is a part,
yea and a great part too,
of the New Covenant dispensation and so no consequence nor part of man`'s nature.

Secondly, If this "`nature`" here spoken of could be understood of man`'s own nature,
which he hath as he is a man, then would the apostle unavoidably contradict himself;
since he elsewhere positively declares,
that "`the natural man discerneth not the things of God,`" nor can.
Now I hope the Law of God is among the things of God,
especially as it is written in the heart.
The apostle, in the 7th chapter of the same epistle, saith (v. 12),
that "`the Law is holy, just, and good`"; and (v. 14) that "`the Law is spiritual,
but he is carnal.`" Now in what respect is he carnal,
but as he stands in the fall unregenerate?
Now what inconsistency would here be, to say that he is carnal,
and yet not so of his own nature, seeing it is from his nature that he is so denominated?
We see the apostle contradistinguisheth the Law as spiritual,
from man`'s nature as carnal and sinful.
Wherefore, as Christ saith, there can "`no grapes be expected from thorns,
nor figs of thistles`";^
footnote:[Matt. 7:16.]
so neither can the fulfilling of the Law, which is spiritual, holy, and just,
be expected from that nature which is corrupt, fallen, and unregenerate.
Whence we conclude, with good reason, that the "`nature`" here spoken of,
by which the Gentiles are said to have done the things contained in the Law,
is not the common nature of men;
but that spiritual nature that ariseth from the works of
the righteous and spiritual Law that is written in the heart.
I confess they of the other extreme,
when they are pressed with this testimony by the Socinians and Pelagians,
as well as by us when we use this scripture, to show them how some of the heathen,
by the Light of Christ in their heart, come to be saved, are very far to seek;
giving this answer, That there were some relics of the heavenly image left in Adam,
by which the heathen could do some good things.
Which, as it is in itself without proof,
so it contradicts their own assertions elsewhere, and gives away their cause.
For if these relics were of force to enable them to fulfill the righteous Law of God,
it takes away the necessity of Christ`'s coming;
or at least leaves them a way to be saved without him;
unless they will say (which is worst of all) that though
they really fulfilled the righteous Law of God,
yet God damned them, because of the want of that particular knowledge,
while he himself withheld all means of their coming to him, from them;
but of this hereafter.

// lint-disable invalid-characters "§"
§III.
I might also here use another argument from these words of the apostle, l Cor, 2,
where he so positively excludes the natural man from
an understanding in the things of God;
but because I have spoken of that scripture in the beginning of the second proposition,
I will here avoid to repeat what is there mentioned, referring thereunto:
yet because the Socinians and others, who exalt the light of the natural man,
or a natural light in man, do object against this scripture,
I shall remove it ere I make an end.

Obj.
They say, the Greek word RESTORE-GREEK
ought to be translated animal, and not natural; else, say they,
it would have been RESTORE-GREEK
from which they seek to infer that it is only the animal man, and not the rational,
that is excluded here from the discerning the things of God.
Which shift, without disputing about the word, is easily refuted;
neither is it any wise consistent with the scope of the place.
For, First,
the animal life is no other than that which man hath common with other living creatures;
for as he is a mere man,
he differs no otherwise from beasts than by the rational property.
Now the apostle deduceth his argument in the foregoing verses from this simile:
that as the things of a man cannot be known but by the spirit of a man,
so the things of God no man knoweth but by the Spirit of God.
But I hope these men will confess unto me,
that the things of a man are not known by the animal spirit only,
i.e. by that which he hath in common with the beasts, but by the rational;
so that it must be the rational that is here understood.
Again,
the assumption shows clearly that the apostle had no such
intent as these men`'s gloss would make him to have,
viz: "`So the things of God knoweth no man,
but the Spirit of God.`" According to their judgment he should have said,
"`The things of God knoweth no man by his animal spirit, but by his rational spirit`":
for to say, the Spirit of God, here spoken of,
is no other than the rational spirit of man, would border upon blasphemy,
since they are so often contradistinguished.
Again, going on, he saith not that they are rationally, but spiritually discerned.

Secondly,
The apostle throughout this chapter shows how the wisdom
of man is unfit to judge of the things of God,
and ignorant of them.
Now I ask these men whether a man be called a wise man from his animal property,
or from his rational?
If from his rational, then it is not only the animal but even the rational,
as he is yet in the natural state,
which the apostle excludes here and whom he contradistinguisheth
from the spiritual (v. 15):
"`But the spiritual man judgeth all things.`" This
cannot be said of any man merely because rational,
or as he is a man, seeing the men of the greatest reason,
if we may so esteem men whom the Scripture calls wise, as were the Greeks of old,
not only may be but often are enemies to the kingdom of God;
while both the preaching of Christ is said to be
foolishness with the wise men of this world,
and the wisdom of the world is said to be foolishness with God.
Now whether it be any ways probable that either these wise men
that are said to account the Gospel foolishness are only so called
with respect to their animal property and not their rational;
or that that wisdom that is foolishness with God is not
meant of the rational but only the animal property,
any rational man, laying aside interest, may easily judge.

// lint-disable invalid-characters "§"
§IV. I come now to the other part, to wit,
That this evil and corrupt seed is not imputed to infants,
until they actually join with it.
For this there is a reason given in the end of the proposition itself;
drawn from Eph. 2. For these "`are by nature children of wrath,
who walk according to the prince of the power of the air,
the spirit that now worketh in the children of disobedience.`"
Here the apostle gives their evil walking,
and not any thing that is not reduced to act,
as a reason of their being children of wrath.
And this is suitable to the whole strain of the Gospel,
where no man is ever threatened or judged for what iniquity he hath not actually wrought:
such indeed as continue in iniquity, and so do homologate^
footnote:[homologate +++=+++ approve.]
the sins of their fathers, God will visit the iniquity of the fathers upon the children.

Is it not strange then that men should entertain an opinion so absurd in itself,
and so cruel and contrary to the nature as well of God`'s mercy as justice,
concerning which the Scripture is altogether silent?
But it is manifest that man hath invented this opinion out of self-love,
and from that bitter root from which all errors spring;
for the most of Protestants that hold this, having, as they fancy,
the absolute decree of election to secure them and their children,
so as they cannot miss of salvation, they make no great difficulty to send all others,
both old and young, to hell.
For whereas self-love (which is always apt to believe that which
it desires) possesseth them with a hope that their part is secure,
they are not solicitous how they leave their neighbours,
which are the far greater part of mankind, in these inextricable difficulties.
The Papists again use this opinion as an art to augment the esteem of their church,
and reverence of its sacraments, seeing they pretend it is washed away by baptism;
only in this they appear to be a little more merciful,
in that they send not these unbaptized infants to hell, but to a certain limbus,
concerning which the Scriptures are as silent as of the other.
This then is not only not authorized in the Scriptures,
but contrary to the express tenor of it.
The apostle saith plainly (Rom. 4:15), "`Where no law is,
there is no transgression.`" And again (5:13), "`But sin is not imputed,
where there is no law.`" Than which testimonies there is nothing more positive;
since to infants there is no law, seeing as such they are utterly incapable of it;
the law cannot reach any but such as have in some measure
less or more the exercise of their understanding,
which infants have not.
So that from thence I thus argue:

Sin is imputed to none, where there is no law.

But to infants there is no law:

Therefore sin is not imputed to them.

The proposition is the apostle`'s own words; the assumption is thus proved:

Those who are under a physical impossibility of either hearing, knowing,
or understanding any law,
where the impossibility is not brought upon them by any act of their own,
but is according to the very order of nature appointed by God; to such there is no law.

But infants are under this physical impossibility:

Therefore, etc.

Secondly, What can be more positive than that of Ezek. 18:20, "`The soul that sinneth,
it shall die:
the son shall not bear the iniquity of the father.`" For the prophet
here first showeth what is the cause of man`'s eternal death,
which he saith is in his sinning, and then,
as if he purposed expressly to shut out such an opinion, he assures us,
"`The son shall not bear the iniquity of the father.`" From which I thus argue:

If the son bear not the iniquity of his father, or of his immediate parents,
far less shall he bear the iniquity of Adam.

But the son shall not bear the iniquity of his father.

Therefore, etc.

// lint-disable invalid-characters "§"
§V. Having thus far shown how absurd this opinion is,
I shall briefly examine the reasons its authors bring for it.

Obj.
First, They say, Adam was a public person, and therefore all men sinned in him,
as being in his loins.
And for this they allege that of Rom. 5:12,
"`Wherefore as by one man sin entered into the world, and death by sin;
and so death passed upon all men, for that all have sinned.`" These last words, say they,
may be translated, "`in whom all have sinned.`"

Answ.
To this I answer: That Adam is a public person is not denied;
and that through him there is a seed of sin propagated to all men,
which in its own nature is sinful, and inclines men to iniquity;
yet it will not follow from thence, that infants, who join not with this seed,
are guilty.
As for these words in the Romans, the reason of the guilt there alleged is,
"`for that all have sinned.`" Now no man is said to sin,
unless he actually sin in his own person; for the Greek words
RESTORE-GREEK may very well relate to RESTORE-GREEK,
which is the nearest antecedent; so that they hold forth how that Adam, by his sin,
gave an entrance to sin in the world: and so death entered by sin,
RESTORE-GREEK, i.e., upon which +++[+++viz. occasion], or in which +++[+++viz. death]
all others have sinned; that is, actually in their own persons; to wit,
all that were capable of sinning: of which number that infants could not be,
the apostle clearly shows by the following verse: "`Sin is not imputed,
where there is no law`": and since, as is above proved, there is no law to infants,
they cannot be here included.

Obj.
Their second objection is from Ps. 51:5, "`Behold I was shapen in iniquity,
and in sin did my mother conceive me.`" Hence, say they,
it appears that infants from their conception are guilty.

Answ.
How they infer this consequence, for my part I see not.
The iniquity and sin here appears to be far more
ascribable to the parents than to the child.
It is said indeed, "`In sin did my mother conceive me`";
not my mother did conceive me a sinner.
Besides, that, so interpreted,
contradicts expressly the scripture before-mentioned in making children guilty
of the sins of their immediate parents (for of Adam there is not here any mention),
contrary to the plain words, "`the son shall not bear the father`'s iniquity.`"

Obj.
Thirdly, they object, that "`the wages of sin is death`";
and that seeing children are subject to diseases and death,
therefore they must be guilty of sin.

Answ.
I answer, That these things are a consequence of the fall and of Adam`'s sin is confessed;
but that that infers necessarily a guilt in
all others that are subject to them is denied.
For though the whole outward creation suffered a decay by Adam`'s fall,
which groans under vanity;
according to which it is said in Job that "`the heavens
are not clean in the sight of God`";
yet will it not from thence follow that the herbs, earth, and trees are sinners.

Next, death, though a consequent of the fall, incident to man`'s earthly nature,
is not the wages of sin in the saints, but rather a sleep,
by which they pass from death to life;
which is so far from being troublesome and painful to them,
as all real punishments for sin are, that the apostle counts it gain: "`To me,`" saith he,
"`to die is gain`" (Phil. 1:21).

Obj.
Some are so foolish as to make an objection farther, saying,
that if Adam`'s sin be not imputed to those who actually have not sinned,
then it would follow that all infants are saved.

But we are willing that this supposed absurdity should be the consequence of our doctrine,
rather than that which it seems our adversaries reckon not absurd,
though the undoubted and unavoidable consequence of theirs, viz:
that many infants eternally perish, not for any sin of their own,
but only for Adam`'s iniquity: where we are willing to let the controversy sist,^
footnote:[sist +++=+++ stop.]
commending both to the illuminated understanding of the Christian reader.

This error of our adversaries is both denied and refuted by Zwingli,
that eminent founder of the Protestant churches of Switzerland, in his book De Baptismo,
for which he is anathematized by the Council of Trent, in the fifth session.
We shall only add this information:
That we confess then that a seed of sin is transmitted
to all men from Adam (although imputed to none,
until by sinning they actually join with it),
in which seed he gave occasion to all to sin,
and it is the origin of all evil actions and thoughts in men`'s hearts,
RESTORE-GREEK to wit, RESTORE-GREEK, as it is in Romans 5, i.e.,
in which death all have sinned.
For this seed of sin is frequently called "`death`" in the Scriptures,
and the "`body of death`";
seeing indeed it is a death to the life of righteousness and holiness:
therefore its seed and its product is called the
"`old man,`" the "`old Adam,`" in which all sin is;
for which cause we use this name to express this sin, and not that of "`original`" sin;
of which phrase the Scripture makes no mention,
and under which invented and unscriptural barbarism this
notion of imputed sin to infants took place among Christians.
