== THE FIFTH AND SIXTH PROPOSITIONS

[.chapter-subtitle--blurb]
Concerning the Universal Redemption by Christ,
and also the Saving and Spiritual Light wherewith every man is enlightened

[.centered]
=== THE FIFTH PROPOSITION

[.heading-continuation-blurb]
God, out of his infinite love, who delighteth not in the death of a sinner,
but that all should live and be saved,^
footnote:[Ezek. 18:32; 33:12.]
hath so loved the world, that he hath given his only Son a Light,
that whosoever believeth in him shall be saved (John 3:16),
"`who enlighteneth _every_ man that cometh into the world`" (John 1:9),
and "`maketh manifest all things that are reprovable`" (Eph. 5:13),
and teacheth all temperance, righteousness, and godliness;
and this Light enlighteneth the hearts of all in a day, in order to salvation;
and this is it which reproves the sin of all individuals,
and would work out the salvation of all, if not resisted.
Nor is it less universal than the seed of sin, being the purchase of his death,
"`who tasted death for every man: for as in Adam all die,
even so in Christ all shall be made alive`" (1 Cor. 15:22).

[.centered]
=== THE SIXTH PROPOSITION

[.heading-continuation-blurb]
According to which principle or hypothesis all the objections
against the universality of Christ`'s death are easily solved;
neither is it needful to recur to the ministry of angels,
and those other miraculous means which they say God useth to manifest
the doctrine and history of Christ`'s passion unto such, who,
living in the places of the world where the outward preaching of the Gospel is unknown,
have well improved the first and common grace.
For as hence it well follows that some of the
old philosophers might have been saved,
so also may some,
who by providence are cast into those remote parts of the
world where the knowledge of the history is wanting,
be made partakers of the divine mystery, if they receive and resist not that grace,
"`a manifestation whereof is given to every man to profit withal.`"^
footnote:[1 Cor. 12:7.]
This most certain doctrine being then received,
that there is an evangelical and saving _Light_ and __grace in all,__
the universality of the love and mercy of God towards mankind,
both in the death of his beloved Son the Lord Jesus Christ,
and in the manifestation of the Light in the heart, is established and confirmed,
against all the objections of such as deny it.
Therefore Christ "`hath tasted death for every man,`"^
footnote:[Heb. 2:9.]
not only for all kinds of men, as some vainly talk, but for __every man of all kinds;__
the benefit of whose offering is not only extended to such who
have the distinct outward knowledge of his death and sufferings,
as the same is declared in the Scriptures,
but even unto those who are necessarily excluded from the
benefit of this knowledge by some inevitable accident;
which knowledge we willingly confess to be very profitable and comfortable,
but not absolutely needful unto such from whom God himself hath withheld it;
yet they may be made partakers of the mystery of his death (though ignorant of the history),
if they suffer his Seed and Light, enlightening their hearts, to take place;
in which Light communion with the Father and the Son is enjoyed,
so as of wicked men to become holy, and lovers of that power,
by whose inward and secret touches they feel themselves turned from the evil to the good,
and learn to "`do to others as they would be done by,`" in
which Christ himself affirms all to be included.
As they have then falsely and erroneously taught,
who have denied Christ to have died for all men;
so neither have they sufficiently taught the Truth, who,
affirming him to have died for all,
have added the absolute necessity of the outward knowledge thereof,
in order to obtain its saving effect.
Among whom the Remonstrants of Holland have been chiefly wanting,
and many other asserters of universal redemption,
in that they have not placed the extent of his salvation in that divine and evangelical
principle of _Light_ and _Life_ wherewith Christ hath "`enlightened every man that cometh
into the world,`" which is excellently and evidently held forth in these scriptures:
Gen. 6:3; Duet. 30:14; John 1:7-9,16; Rom. 10:8; Tit. 2:11.

Hitherto we have considered man`'s fallen, lost, corrupted, and degenerated condition.
Now it is fit to enquire how,
and by what means he may come to be freed out of this miserable and depraved condition,
which in these two propositions is declared and demonstrated;
which I thought meet to place together because of their affinity,
the one being as it were an explanation of the other.

As for that doctrine which these propositions chiefly strike at, to wit,
absolute reprobation, according to which some are not afraid to assert: That God,
by an eternal and immutable decree,
hath predestinated to eternal damnation the far greater part of mankind,
not considered as made, much less as fallen,
without any respect to their disobedience or sin,
but only for the demonstrating of the glory of his justice;
and that for the bringing this about he hath appointed these
miserable souls necessarily to walk in their wicked ways,
that so his justice may lay hold on them:
and that God doth therefore not only suffer them to be liable
to this misery in many parts of the world,
by withholding from them the preaching of the Gospel and the knowledge of Christ,
but even in those places where the Gospel is preached,
and salvation by Christ is offered; whom though he publicly invite them,
yet he justly condemns for disobedience,
albeit he hath withheld from them all grace by which
they could have laid hold of the Gospel,
viz.: Because he hath, by a secret will unknown to all men,
ordained and decreed (without any respect had to
their disobedience or sin) that they shall not obey,
and that the offer of the Gospel shall never prove effectual for their salvation,
but only serve to aggravate and occasion their greater condemnation.

I say, as to this horrible and blasphemous doctrine,
our cause is common with many others, who have both wisely and learnedly,
according to Scripture, reason, and antiquity, refuted it.
Seeing then that so much and so well is said already against this doctrine,
that little can be superadded, except what hath been said already,
I shall be short in this respect; yet because it lies so in opposition to my way,
I cannot let it altogether pass.

[.small-break]
'''

// lint-disable invalid-characters "§"
§I. First, We may safely call this doctrine a novelty,
seeing the first four hundred years after Christ there is no mention made of it:
for as it is contrary to the Scripture`'s testimony, and to the tenor of the Gospel,
so all the ancient writers, teachers,
and doctors of the church pass it over with a profound silence.
The first foundations of it were laid in the later writings of Augustine, who,
in his heat against Pelagius,
let fall some expressions which some have unhappily gleaned up,
to the establishing of this error; thereby contradicting the Truth,
and sufficiently gainsaying many others,
and many more and frequent expressions of the same Augustine.
Afterwards was this doctrine fomented by Dominicus, a friar, and the monks of his order;
and at last unhappily taken up by John Calvin (otherwise
a man in divers respects to be commended),
to the great staining of his reputation,
and defamation both of the Protestant and Christian religion;
which though it received the decrees of the Synod of Dort for its confirmation,
hath since lost ground,
and begins to be exploded by most men of learning and piety in all Protestant churches.
However, we should not quarrel it for the silence of the ancients,
paucity of its asserters, or for the learnedness of its opposers,
if we did observe it to have any real bottom in the
writings or sayings of Christ and the apostles,
and that it were not highly injurious to God himself,
to Jesus Christ our Mediator and Redeemer, and to the power, virtue, nobility,
and excellency of his blessed Gospel, and lastly unto all mankind.

[.small-break]
'''

// lint-disable invalid-characters "§"
§II. First, It is highly injurious to God,
because it makes him the author of sin,
which of all things is most contrary to his nature.
I confess the asserters of this principle deny this consequence;
but that is but a pure illusion, seeing it so naturally follows from their doctrine,
and is equally ridiculous,
as if a man should pertinaciously deny that one and two make three.
For if God has decreed that the reprobated ones shall perish,
without all respect to their evil deeds, but only of his own pleasure,
and if he hath also decreed long before they were in being,
or in a capacity to do good or evil, that they should walk in those wicked ways,
by which, as by a secondary means, they are led to that end; who, I pray,
is the first author and cause thereof but God, who so willed and decreed?
This is as natural a consequence as can be: and therefore,
although many of the preachers of this doctrine have sought out various, strange,
strained, and intricate distinctions to defend their opinion,
and avoid this horrid consequence; yet some, and that of the most eminent of them,
have been so plain in the matter, as they have put it beyond all doubt,
of which I shall instance a few among many passages.
"`I say, that by the ordination and will of God, Adam fell.
God would have man to fall.`"^
footnote:[Calvin _in cap. 3. Gen._]
"`Man is blinded by the will and commandment of God.`"^
footnote:[_Id. 1 Inst. c. 18. s. 1._]
"`We refer the causes of hardening us to God.`"^
footnote:[_Id. lib. de praed._]
"`The highest or remote cause of hardening is the will of God.`"^
footnote:[_Idem, lib. de provid._]
"`It followeth that the hidden counsel of God is the cause of hardening.`"^
footnote:[_Id. 3 Inst., cap. 23. s. 1._]
These are Calvin`'s expressions.
"`God,`" saith Beza, "`hath predestinated not only unto damnation,
but also unto the causes of it, whomsoever he saw meet.`"^
footnote:[Beza, _lib. de praed._]
"`The decree of God cannot be excluded from the causes of corruption.`"^
footnote:[_Id. de praed. ad art. 1._]
"`It is certain,`" saith Zanchi, "`that God is the first cause of obduration.`"^
footnote:[Zanchi, _de excaecat. q. 5._]
"`Reprobates are held so fast under God`'s almighty decree,
that they cannot but sin and perish.`"^
footnote:[_Idem, lib. 5 de nat. Dei cap. 2. de praed._]
"`It is the opinion,`" saith Pareus, "`of our doctors,
that God did inevitably decree the temptation and fall of man.
The creature sinneth indeed necessarily, by the most just judgment of God.
Our men do most rightly affirm,
that the fall of man was necessary and inevitable by accident,
because of God`'s decree.`"^
footnote:[Pareus, _lib. 3. de amiss. gratiae. c. 2. ibid., c. 1._]
"`God,`" saith Martyr,
"`doth incline and force the wills of wicked men into great sins.`"^
footnote:[Martyr, _in Rom._]
"`God,`" saith Zwingli, "`moveth the robber to kill.
He killeth, God forcing him thereunto.
But thou wilt say, he is forced to sin; I permit truly that he is forced.`"^
footnote:[Zwingli, _lib. de Prov. 100:5._]
"`Reprobate persons,`" saith Piscator,
"`are absolutely ordained to this twofold end, to undergo everlasting punishment,
and necessarily to sin; and therefore to sin,
that they may be justly punished.`"^
footnote:[_Resp. ad Vorst._ part 1, p. 120.]

If these sayings do not plainly and evidently
import that God is the author of sin,
we must not then seek these men`'s opinions from their words, but some way else.
It seems as if they had assumed to themselves that
monstrous and twofold will they feign of God;
one by which they declare their minds openly, and another more secret and hidden,
which is quite contrary to the other.
Nor doth it at all help them, to say that man sins willingly, since that willingness,
proclivity, and propensity to evil is, according to their judgment,
so necessarily imposed upon him that he cannot but be willing,
because God hath willed and decreed him to be so.
Which shift is just as if I should take a child incapable to resist me,
and throw it down from a great precipice;
the weight of the child`'s body indeed makes it go readily down,
and the violence of the fall upon some rock or stone beats out its brains and kills it.
Now then I pray, though the body of the child goes willingly down (for I suppose it,
as to its mind, incapable of any will), and the weight of its body,
and not any immediate stroke of my hand, who perhaps am at a great distance,
makes it die, whether is the child or I the proper cause of its death?
Let any man of reason judge, if God`'s part be (with them) as great, yea, more immediate,
in the sins of men, as by the testimonies above brought doth appear;
whether doth not this make him not only the author of sin,
but more unjust than the unjustest of men?

[.small-break]
'''

// lint-disable invalid-characters "§"
§III.
Secondly, This doctrine is injurious to God,
because it makes him delight in the death of sinners, yea,
and to will many to die in their sins, contrary to these scriptures: Ezek. 33:11;
1 Tim. 2:4; 2 Pet. 3:9. For if he hath created men only for this very end,
that he might show forth his justice and power in them, as these men affirm,
and for effecting thereof hath not only withheld from them the means of doing good,
but also predestinated the evil, that they might fall into it;
and that he inclines and forces them into great sins;
certainly he must necessarily delight in their death, and will them to die;
seeing against his own will he neither doth, nor can do any thing.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IV. Thirdly, it is highly injurious to Christ our mediator,
and to the efficacy and excellency of his Gospel;
for it renders his mediation ineffectual,
as if he had not by his sufferings thoroughly broken down the middle wall,
nor yet removed the wrath of God, or purchased the love of God towards all mankind,
if it was afore-decreed that it should be of no service to the far greater part of mankind.
It is to no purpose to allege that the death of Christ
was of efficacy enough to have saved all mankind,
if in effect its virtue be not so far extended as
to put all mankind into a capacity of salvation.

Fourthly, it makes the preaching of the Gospel a mere mock and illusion,
if many of these, to whom it is preached,
be by an irrevocable decree excluded from being benefited by it;
it wholly makes useless the preaching of faith and repentance,
and the whole tenor of the Gospel promises and threatenings,
as being all relative to a former decree and means before appointed to such; which,
because they cannot fail,
man needs do nothing but wait for that irresistible snatch,^
footnote:[Later editors replace "`snatch`" with "`juncture.`"]
which will come, though it be but at the last hour of his life,
if he be in the decree of election; and be his diligence and waiting what it can,
he shall never attain it, if he belong to the decree of reprobation.

Fifthly, it makes the coming of Christ, and his propitiatory sacrifice,
which the Scripture affirms to have been the fruit of God`'s love to the world,
and transacted for the sins and salvation of all men,
to have been rather a testimony of God`'s wrath to the world,
and one of the greatest judgments,
and severest acts of God`'s indignation towards mankind,
it being only ordained to save a very few, and for the hardening,
obduring and augmenting the condemnation of the far greater number of men,
because they believe not truly in it;
the cause of which unbelief again (as the divines +++[+++so called]
above assert) is the hidden counsel of God:
certainly the coming of Christ was never to them a testimony of God`'s love,
but rather of his implacable wrath:
and if the world may be taken for the far greater number of such as live in it,
God never loved the world, according to this doctrine, but rather hated it greatly,
in sending his Son to be crucified in it.

[.small-break]
'''

// lint-disable invalid-characters "§"
§V. Sixthly, This doctrine is highly injurious to mankind;
for it renders them in a far worse condition than the devils in hell.
For these were sometimes in a capacity to have stood,
and do suffer only for their own guilt;
whereas many millions of men are forever tormented, according to them, for Adam`'s sin,
which they neither knew of, nor ever were accessary to.
It renders them worse than the beasts of the field,
of whom the master requires not more than they are able to perform;
and if they be killed, death to them is the end of sorrow;
whereas man is forever tormented for not doing that which he never was able to do.
It puts him into a far worse condition than Pharaoh put the Israelites;
for though he withheld straw from them,
yet by much labour and pains they could have gotten it:
but from men they make God to withhold all means of salvation,
so that they can by no means attain it; yea,
they place mankind in that condition which the poets feign of Tantalus, who,
oppressed with thirst, stands in water up to the chin,
yet can by no means reach it with his tongue; and being tormented with hunger,
hath fruits hanging at his very lips,
yet so as he can never lay hold on them with his teeth;
and these things are so near him not to nourish him, but to torment him.
So do these men: they make the outward creation of the works of Providence,
the smitings of conscience, sufficient to convince the heathen of sin,
and so to condemn and judge them: but not at all to help them to salvation.
They make the preaching of the Gospel, the offer of salvation by Christ,
the use of the sacraments, of prayer, and good works,
sufficient to condemn those they account reprobates within the church,
serving only to inform them to beget a seeming faith and vain hope;
yet because of a secret impotency, which they had from their infancy,
all these are wholly ineffectual to bring them the least step towards salvation;
and do only contribute to render their condemnation the
greater and their torments the more violent and intolerable.

Having thus briefly removed this false doctrine which stood in my way,
because they that are desirous may see it both learnedly
and piously refuted by many others,
I come to the matter of our proposition, which is,
"`That God out of his infinite love,
who delighteth not in the death of a sinner but that all should live and be saved,
hath sent his only begotten Son into the world,
that _whosoever_ believeth in him might be saved`":
which also is again affirmed in the Sixth Proposition in these words:
"`Christ then tasted death for every man,
of all kinds.`" Such is the evidence of this truth,
delivered almost wholly in the express words of Scripture,
that it will not need much probation.
Also, because our assertion herein is common with many
others who have both earnestly and soundly,
according to the Scripture, pleaded for this universal redemption,
I shall be the more brief in it that I may come to that
which may seem more singularly and peculiarly ours.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VI. This doctrine of universal redemption, or Christ`'s dying for all men,
is of itself so evident from the Scripture testimony that there
is scarce found any other article of the Christian faith so frequently,
so plainly, and so positively asserted.
It is that which maketh the preaching of Christ to be truly termed the Gospel,
or an annunciation of glad tidings to all.
Thus the angel declared the birth and coming of Christ
to the shepherds to be (Luke 2:10),
"`Behold, I bring you good tidings of great joy, which shall be to all people`":
he saith not to a few people.
Now if this coming of Christ had not brought a possibility of salvation to _all_
it should rather have been accounted bad tidings of great sorrow to most people;
neither should the angel have had reason to have sung "`Peace on
earth and good will towards men`" if the greatest part of mankind
had been necessarily shut out from receiving any benefit by it.
How should Christ have sent out his to "`preach the Gospel to every creature`" (Mark 16:15)?
a very comprehensive commission! that is __to every son and daughter of mankind.__
Without all exception he commands them to preach salvation to all,
repentance and remission of sins to all; warning everyone and exhorting everyone,
as Paul did (Col. 1:28). Now how could they have preached the
Gospel __to every man__ as became the ministers of Jesus Christ,
in much assurance, if salvation by that Gospel had not been possible to all?
What if some of those had asked them,
or should now ask any of these doctors who deny the universality
of Christ`'s death and yet preach it to all promiscuously,
"`Hath Christ died for me?`" How can they with confidence
give a certain answer to this question?
If they give a conditional answer, as their principle obligeth them to do, and say,
If thou repent Christ hath died for thee; doth not the same question still recur?
"`Hath Christ died for me so as to make repentance possible for
me?`" To this they can answer nothing unless they run in a circle;
whereas "`the feet of those that bring the glad tidings of the Gospel of
peace`" are said to be "`beautiful`" for that they preach the common salvation,
repentance unto all;
offering a door of mercy and hope to all through
Jesus Christ who gave himself a ransom for all.
The Gospel invites _all;_
and certainly by the Gospel Christ intended not to deceive and
delude the greater part of mankind when he invites and crieth,
saying,
"`Come unto me all ye that labour and are heavy laden and I
will give you rest.`" If _all_ then ought to seek after him and to look for
salvation by him he must needs have made __salvation possible__ to all;
for who is bound to seek after that which is impossible?
Certainly it were a mocking of men to bid them do so.
And such as deny that by the death of Christ salvation is made possible to all
men do most blasphemously make God mock the world in giving his servants a commission
to preach the Gospel of salvation unto all while he hath before decreed that
it shall not be possible for them to receive it.
Would not this make the Lord to send forth his servants
with a lie in their mouth (which were blasphemous to think),
commanding them to bid _all_ and __every one__ believe that Christ
died for them and had purchased life and salvation?
Whereas it is no such thing according to the afore-mentioned doctrine.
But seeing Christ, after he arose and perfected the work of our redemption,
gave a commission to preach repentance, remission of sins, and salvation to all,
it is manifest that he __died for all.__
For he that hath commissionated his servants thus to preach
is a God of Truth and no mocker of poor mankind;
neither doth he require of any man that which is simply impossible for him to do:
for that no man is bound to do that which is impossible
is a principle of Truth engraven in every man`'s mind.
And seeing he is both a most righteous and merciful God it cannot at all stand,
neither with his justice nor mercy,
to bid such men repent or believe to whom it is impossible.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VII.
Moreover, if we regard the testimony of the Scripture in this matter,
where there is not one scripture which I know of
that affirmeth Christ not to die for _all,_
there are divers that positively and expressly assert he did; as 1 Tim. 2:1,3,4,6:
"`I exhort therefore that first of all supplications, prayers, intercessions,
and giving of thanks,
be made for all men,`" etc. "`For this is good and acceptable in the sight of God our Saviour,
who will have all men to be saved and to come to the knowledge of the Truth;
who gave himself a ransom for all to be testified in due time.`" Except
we will have the apostle here to assert quite another thing than he intended,
there can be nothing more plain to confirm what we have asserted.
And this scripture doth well answer to that manner
of arguing which we have hitherto used:
for first the apostle here recommends them to "`pray for all men`";
and to obviate such an objection, as if he had said with our adversaries,
Christ prayed not for the world neither willeth he us to pray for all;
because he willeth not that all should be saved but hath ordained
many to be damned that he might show forth his justice in them;
he obviates, I say, such an objection,
telling them that "`it is good and acceptable in the sight of God,
who will have all men to be saved.`" I desire to know what can be more expressly affirmed?
or can any two propositions be stated in terms more contradictory than these two?
God willeth not some to be saved; and God willeth all men to be saved,
or God will have no man perish.
If we believe the last, as the apostle hath affirmed, the first must be destroyed;
seeing of contradictory propositions the one being placed, the other is destroyed.
Whence to conclude he gives us a reason of his willingness that all men should be saved,
in these words: "`Who gave himself a ransom for all`"; as if he would have said,
Since Christ died for all, since he gave himself a ransom for all,
therefore he will have all men to be saved.
This Christ himself gives as a reason of God`'s love to the world,
in these words (John 3:16): "`God so loved the world that he gave his only begotten Son,
that whosoever believeth in him should not perish but have everlasting life`";
compared with 1 John 4:9. This __+++[+++whosoever]__
is an indefinite term, from which no man is excluded.
From all which then I thus argue:

[.offset]
_Argument:_

[.syllogism]
* For whomsoever it is lawful to pray, to them salvation is possible:
* But it is lawful to pray for every individual man in the whole world:
* Therefore salvation is possible unto them.

[.offset]
I prove the major proposition thus;

[.syllogism]
* No man is bound to pray for that which is impossible to be attained:
* But every man is bound and commanded to pray for all men:
* Therefore it is not impossible to be attained.

[.offset]
I prove also this proposition further, thus;

[.syllogism]
* No man is bound to pray, but in faith:
* But he that prayeth for that, which he judges simply impossible to be obtained, cannot pray in faith:
* Therefore, etc.

[.offset]
Again,

[.syllogism]
* That which God willeth is not impossible:
* But God willeth all men to be saved:
* Therefore it is not impossible.

[.offset]
And lastly;

[.syllogism]
* Those for whom our Saviour gave himself a ransom, to such salvation is possible:
* But our Saviour gave himself a ransom for all:
* Therefore salvation is possible unto them.

// lint-disable invalid-characters "§"
§VIII.
This is very positively affirmed (Heb. 2:9) in these words,
"`But we see Jesus, who was made a little lower than the angels,
for the suffering of death crowned with glory and honor that he
by the grace of God should taste death for every man.`" He that
will but open his eyes may see this truth here asserted:
if he "`tasted death for every man`" then certainly
there is no man for whom he did not taste death;
then there is no man who may not be made a sharer of the benefit of it;
for he came not "`to condemn the world but that the world through
him might be saved`" (John 3:17). "`He came not to judge the world
but to save the world`" (John 12:47). Whereas,
according to the doctrine of our adversaries he behooved
to come to condemn the world and judge it;
and not that it might be saved by him or to save it.
For if he never came to bring salvation to the greater part of mankind,
but that his coming, though it could never do them good,
yet shall augment their condemnation;
from thence it necessarily follows that he came not of intention
to save but to judge and condemn the greater part of the world,
contrary to his own express testimony;
and as the apostle Paul in the words above cited doth assert affirmatively
that "`God willeth the salvation of all,`" so doth the apostle Peter
assert negatively that "`he willeth not the perishing of any`" (2
Pet. 3:9). "`The Lord is not slack concerning his promise,
as some men count slackness; but is long-suffering to us-ward,
not willing that any should perish but that all should come to repentance.`"
And this is correspondent to that of the prophet (Ezek. 33:11):
"`As I live, saith the Lord, I have no pleasure in the death of the wicked;
but that the wicked turn from his way and live.`" If it be safe
to believe God and trust in him we must not think that he intends
to cheat us by all these expressions through his servants,
but that he was in good earnest.
And that this will and desire of his hath not taken effect, the blame is on our parts,
as shall be after spoken of;
which could not be if so be we never were in any capacity of salvation or that
Christ had never died for us but left us under an impossibility of salvation.
What means all those earnest invitations, all those serious expostulations,
all those regretting contemplations wherewith the holy Scriptures are full?
As, "`Why will ye die, O house of Israel!`" "`Why will ye not come unto me,
that ye might have life?`" "`I have waited to be gracious unto you`";
"`I have sought to gather you`"; "`I have knocked at the door of your hearts`";
"`is not your destruction of yourselves?`" "`I have called all the day long.`"
If men who are so invited be under no capacity of being saved,
if salvation be impossible unto them,
shall we suppose God in this to be no other but like
the author of a romance or master of a comedy,
who amuses and raises the various affections and passions
of his spectators by divers and strange accidents,
sometimes leading them into hope and sometimes into despair; all those actions,
in effect, being but a mere illusion,
while he hath appointed what the conclusion of all shall be?

Thirdly, This doctrine is abundantly confirmed by that of the apostle (1 John 2:1-2):
"`And if any man sin, we have an advocate with the Father, Jesus Christ the righteous.
And he is the propitiation for our sins;
and not for ours only but also for the sins of the whole world.`" The way which
our adversaries take to evite this testimony is most foolish and ridiculous:
the world here, say they, is the world of believers:
for this commentary we have nothing but their own assertion,
and so while it manifestly destroys the text may be justly rejected.
For first let them show me, if they can, in all the Scripture,
where "`the whole world`" is taken for believers only;
I shall show them where it is many times taken for the quite contrary; as,
"`The world knows me not.`" "`The world receives me not.`" "`I
am not of this world.`" Besides all these scriptures:
Ps. 17:14; Isa. 13:11; Matt. 18:7; John 7:7-8:26, 12:19, 14:17, 15:18-19,
17:14, and 18:20; 1 Cor. 1:2,21:12, and 6:2; Gal. 6:14; James 1:27;
2 Pet. 2:20; 1 John 2:15-3:1, and 4:4-5, and many more.
Secondly,
The apostle in this very place contradistinguisheth the _world_ from the _saints_ thus:
"`And not for ours only but for the sins of the whole world`":
What means the apostle by "`ours`" here?
Is not that the sins of believers?
Was not he one of those believers?
And was not this a universal epistle written to all the saints that then were?
So that according to these men`'s comment there should be a very
unnecessary and foolish redundancy in the apostle`'s words,
as if he had said,
"`He is a propitiation not only for the sins of all
believers but for the sins of all believers`":
is not this to make the apostle`'s words void of good sense?
Let them show us wherever there is such a manner of speaking in all the Scripture,
// lint-disable invalid-characters "ô"
where any of the penmen first name the _believers_ in _concretô_ with themselves
and then contradistinguish them from some other whole world of believers?
That "`whole world,`" if it be of believers, must not be the world we live in.
But we need no better interpreter for the apostle than himself,
who uses the very same expression and phrase in the same epistle (5:19), saying,
"`We know that we are of God,
and the whole world lieth in wickedness.`" There cannot be
found in all the Scripture two places which run more parallel;
seeing in both the same apostle, in the same epistle to the same persons,
contradistinguisheth himself and the saints to whom he writes from the whole world;
which, according to these men`'s commentary ought to be understood of believers:
as if John had said, "`We know particular believers are of God;
but the whole world of believers lieth in wickedness.`"
What absurd wresting of Scripture were this?
And yet it may be as well pleaded for as the other; for they differ not at all.
Seeing then that the apostle John tells us plainly that Christ
not only died for him and for the saints and members of the church
of God to whom he wrote but for the __whole world,__
let us then hold it for a certain and undoubted truth
notwithstanding the cavils of such as oppose.

This might also be proved from many more Scripture testimonies,
if it were at this season needful.
All the Fathers, so called, and doctors of the church,
for the first four centuries, preached this doctrine;
according to which they boldly held forth the Gospel of Christ,
and efficacy of his death;
inviting and entreating the heathen to come and be partakers of the benefits of it,
showing them how there was a door opened for them all to be saved through Jesus Christ;
not telling them that God had predestinated any of them to damnation,
or had made salvation impossible to them, by withholding power and grace,
necessary to believe, from them.
But of many of their sayings, which might be alleged, I shall only instance a few.

Augustine on the 95th Psalm saith, "`The blood of Christ is of so great worth,
that it is of no less value than the whole world.`"

Prosper __ad Gall__ (c.9): "`The redeemer of the world gave his blood for the world,
and the world would not be redeemed, because the darkness did not receive the Light.
He that saith, the Saviour was not crucified for the redemption of the whole world,
looks not to the virtue of the sacrament, but to the part of infidels;
since the blood of our Lord Jesus Christ is the price of the whole world;
from which redemption they are strangers,
who either delighting in their captivity would not be redeemed,
or after they were redeemed returned to the same servitude.`"

The same Prosper, in his answer to Vincent`'s first objection:
"`Seeing therefore because of one common nature and cause in Truth,
undertaken by our Lord, all are rightly said to be redeemed,
and nevertheless all are not brought out of captivity;
the property of redemption without doubt belongeth to those
from whom the prince of this world is shut out,
and now are not vessels of the devil but members of Christ;
whose death was so bestowed upon mankind that it belonged
to the redemption of such who were not to be regenerated.
But so that that which was done by the example of one for all might,
by a singular mystery, be celebrated in everyone.
For the cup of immortality, which is made up of our infirmity and the divine power,
hath indeed that in it which may profit all; but if it be not drunk it doth not heal.`"

The author __de vocat.__ [.book-title]#Gentium (lib. 11. cap. 6):#
"`There is no cause to doubt but that our Lord Jesus
Christ died for sinners and wicked men.
And if there can be any found, who may be said not to be of this number,
Christ hath not died for all; he made himself a redeemer for the whole world.`"

Chrysostom on John 1: "`If he enlightens every man coming into the world,
how comes it that so many men remain without light?
For all do not so much as acknowledge Christ.
How then doth he enlighten every man?
He illuminates indeed so far as in him is; but if any of their own accord,
closing the eyes of their mind, will not direct their eyes unto the beams of this Light,
the cause that they remain in darkness is not from the nature of the Light,
but through their own malignity,
who willingly have rendered themselves unworthy of so great a gift.
But why believed they not?
Because they would not: Christ did his part.`"

The Synod of Arles, held about the year 490, pronounced him "`accursed,
who should say that Christ hath not died for all,
or that he would not have all men to be saved.`"

Ambrose on Ps. 118 (Serm.
8): "`The mystical Sun of Righteousness is arisen to all; he came to all;
he suffered for all and rose again for all;
and therefore he suffered that he might take away the sin of the world.
But if any one believe not in Christ he robs himself of this general benefit,
even as if one by closing the windows should hold out the sunbeams;
the sun is not therefore not arisen to all because
such a one hath so robbed himself of its heat;
but the sun keeps its prerogative;
it is such a one`'s imprudence that he shuts himself
out from the common benefit of the light.`"

The same man in his 11th book of Cain and Abel, cap.
13, saith, "`Therefore he brought unto all the means of health,
that whosoever should perish, may ascribe to himself the causes of his death,
who would not be cured when he had the remedy by which he might have escaped.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§IX. Seeing then that this doctrine of the universality
of Christ`'s death is so certain and agreeable to the Scripture`'s
testimony and to the sense of the purest antiquity,
it may be wondered how so many, some whereof have been esteemed not only learned,
but also pious, have been capable to fall into so gross and strange an error.
But the cause of this doth evidently appear in that the way and method by which the
virtue and efficacy of his death is communicated to all men hath not been rightly understood,
or indeed hath been erroneously affirmed.
The Pelagians, ascribing all to man`'s will and nature,
denied man to have any seed of sin conveyed to him from Adam.
And the Semi-Pelagians,
making grace as a gift following upon man`'s merit or right improving of his nature,
according to their known principle, __Facienti quod in se est Deus non denegat gratiam.__

This gave Augustine, Prosper, and some others occasion,
labouring in opposition to these opinions,
to magnify the grace of God and paint out the corruption of man`'s nature,
as the proverb is of those that seek to make straight a crooked stick,
to incline to the other extreme.
So also the reformers, Luther and others,
finding among other errors the strange expressions used by some of the
Popish scholastics concerning free-will and how much the tendency of their
principles is to exalt man`'s nature and lessen God`'s grace,
having all those sayings of Augustine and others for a pattern,
through the like mistake ran upon the same extreme; though afterwards the Lutherans,
seeing how far Calvin and his followers drove this
matter (who as a man of subtle and profound judgment,
foreseeing where it would land,
resolved aboveboard to assert that God had decreed the means as well as
the end and therefore had ordained men to sin and excites them thereto,
which he labours earnestly to defend),
and that there was no avoiding the making God the author of sin,
thereby received occasion to discern the falsity of this doctrine and disclaimed it,
// lint-disable invalid-characters "é"
as appears by the later writings of Melancthon and the Montbéliard conference,
where Lucas Osiander, one of the collocutors,
terms it "`impious,`" calls it a making God the author
of sin and an horrid and horrible blasphemy.^
footnote:[_Epist. Hist. Eccl. Lucae Osiand. Cent. 16. lib. 4 cap. 32._]
Yet because none of those who have asserted this
universal redemption since the reformation have given a clear,
distinct, and satisfactory testimony how it is communicated to all,
and so have fallen short of fully declaring the perfection of the Gospel dispensation,
others have been thereby the more strengthened in their errors;
which I shall illustrate by one singular example.

The Arminians, and other assertors of universal grace,
use this as a chief argument:

[.syllogism]
* That which every man is bound to believe, is true:
* But every man is bound to believe that Christ died for them:
* Therefore, etc.

Of this argument the other party deny the assumption, saying,
That they who never heard of Christ, are not obliged to believe in him;
and seeing the Remonstrants (as they are commonly called) do generally themselves acknowledge,
that without the outward knowledge of Christ there is no salvation,
that gives the other party yet a stronger argument for their precise decree of reprobation.
For, say they, seeing we all see really and in effect,
that God hath withheld from many generations, and yet from many nations,
that knowledge which is absolutely needful to salvation,
and so hath rendered it simply impossible unto them;
why may he not as well withhold the grace necessary
to make a saving application of that knowledge,
where it is preached?
For there is no ground to say that this were injustice in God, or impartiality,
more than his leaving those others in utter ignorance;
the one being but a withholding grace to apprehend the object of faith,
the other a withdrawing the object itself.
For answer to this,
they are forced to draw a conclusion from their former
hypothesis of Christ`'s dying for all,
and God`'s mercy and justice, saying that if these heathens,
who live in these remote places where the outward knowledge of Christ is not,
did improve that common knowledge they have,
to whom the outward creation is for an object of faith,
by which they may gather that there is a God, then the Lord would, by some providence,
either send an angel to tell them of Christ, or convey the Scriptures to them,
or bring them some way to an opportunity to meet with such as might inform them.
Which, as it gives always too much to the power and strength of man`'s will and nature,
and savours a little of Socinianism and Pelagianism, or at least of Semipelagianism, so,
since it is only built upon probable conjectures,
neither hath it evidence enough to convince any strongly tainted with the other doctrine;
nor yet doth it make the equity and wonderful harmony of God`'s
mercy and justice towards _all_ so manifest to the understanding.
So that I have often observed,
that these assertors of universal grace did far more pithily
and strongly overturn the false doctrine of their adversaries,
than they did establish and confirm the truth and certainty of their own.
And though they have proof sufficient from the holy Scriptures
to confirm the universality of Christ`'s death,
and that none are precisely, by any irrevocable decree, excluded from salvation,
yet I find when they are pressed in the respects above mentioned,
to show how God hath so far equally extended the capacity
to partake of the benefit of Christ`'s death unto all,
as to communicate unto them a sufficient way of so doing, they are somewhat in a strait,
and are put more to give us their conjectures from
the certainty of the former presupposed truth;
to wit, that because Christ hath certainly died for all,
and God hath not rendered salvation impossible to any,
therefore there must be some way or other by which they may be saved;
which must be by improving some common grace,
or by gathering from the works of creation and providence, than by really demonstrating,
by convincing and spiritual arguments, what that way is.

[.small-break]
'''

// lint-disable invalid-characters "§"
§X. It falls out then, that as darkness, and the great apostasy,
came not upon the Christian world all at once, but by several degrees,
one thing making way for another; until that thick and gross veil came to be overspread,
wherewith the nations were so blindly covered, from the seventh and eighth,
until the sixteenth century;
even as the darkness of the night comes not upon the outward creation all at once,
but by degrees, according as the sun declines in each horizon;
so neither did that full and clear light and knowledge of the glorious
dispensation of the Gospel of Christ appear all at once;
the work of the first witnesses being more to testify
against and discover the abuses of the apostasy,
than to establish the Truth in purity.
He that comes to build a new city, must first remove the old rubbish,
before he can see to lay a new foundation;
and he that comes to a house greatly polluted and full of dirt,
will first sweep away and remove the filth,
before he put up his own good and new furniture.
The dawning of the day dispels the darkness,
and makes us see the things that are most conspicuous:
but the distinct discovering and discerning of things,
so as to make a certain and perfect observation,
is reserved for the arising of the sun, and its shining in full brightness.
And we can, from a certain experience, boldly affirm, that the not waiting for this,
but building among, yea, and with, the old Popish rubbish,
and setting up before a full purgation,
hath been to most Protestants the foundation of many a mistake,
and an occasion of unspeakable hurt.
Therefore the Lord God,
who as he seeth meet doth communicate and make known to man the more full, evident,
and perfect knowledge of his everlasting Truth,
hath been pleased to reserve the more full discovery of this glorious
and evangelical dispensation to this our age (albeit divers testimonies
have thereunto been borne by some noted men in several ages,
as shall hereafter appear).
And for the greater augmentation of the glory of his grace,
that no man might have whereof to boast,
he hath raised up a few despicable and illiterate men,
and for the most part mechanics, to be the dispensers of it;
by which Gospel all the scruples, doubts,
hesitations and objections above mentioned are easily and evidently answered,
and the justice as well as mercy of God, according to their divine and heavenly harmony,
are exhibited, established, and confirmed.
According to which certain Light and Gospel,
as the knowledge thereof has been manifested to us
by the revelation of Jesus Christ in us,
fortified by our own sensible experience,
and sealed by the testimony of the Spirit in our hearts,
we can confidently affirm, and clearly evince,
according to the testimony of the holy Scriptures, the following points:

[.small-break]
'''

// lint-disable invalid-characters "§"
§XI. First, That God, who out of his infinite love sent his Son,
the Lord Jesus Christ, into the world, who tasted death for every man,
hath given to every man, whether Jew or Gentile, Turk or Scythian, Indian or Barbarian,
of whatsoever nation, country, or place, a certain day or time of visitation;
during which day or time it is possible for them to be saved,
and to partake of the fruit of Christ`'s death.

Secondly,
That for this end God hath communicated and given unto every
man a measure of the Light of his own Son,
a measure of grace, or a measure of the Spirit,
which the Scripture expresses by several names,
as sometimes of "`the seed of the kingdom`" (Matt. 13:18-19);
the "`Light that makes all things manifest`" (Eph. 5:13);
the "`Word of God`" (Rom. 10:17);
or "`manifestation of the Spirit given to profit withal`" (1 Cor. 12:7);
"`a talent`" (Matt. 25:15); "`a little leaven`" (Matt. 13:33);
"`the Gospel preached in every creature`" (Col. 1:23).

Thirdly, That God, in and by this Light and Seed, invites, calls, exhorts,
and strives with every man, in order to save him; which as it is received,
and not resisted, works the salvation of all,
even of those who are ignorant of the death and sufferings of Christ, and of Adam`'s fall,
both by bringing them to a sense of their own misery,
and to be sharers in the sufferings of Christ inwardly,
and by making them partakers of his Resurrection, in becoming holy, pure, and righteous,
and recovered out of their sins.
By which also are saved they that have the knowledge of Christ outwardly,
in that it opens their understanding rightly to use
and apply the things delivered in the Scriptures,
and to receive the saving use of them.
But that this may be resisted and rejected in both,
in which then God is said to be resisted and pressed down,
and Christ to be again crucified, and put to open shame in and among men,
and to those as thus resist and refuse him, he becomes their condemnation.

First, then,
according to this doctrine the mercy of God is excellently well exhibited,
in that none are necessarily shut out from salvation: and his justice is demonstrated,
in that he condemns none but such to whom he really made offer of salvation,
affording them the means sufficient thereunto.

Secondly, This doctrine, if well weighed,
will be found to be the foundation of Christianity, salvation, and assurance.

Thirdly, It agrees and answers with the whole tenor of the Gospel promises and threats,
and with the nature of the ministry of Christ, according to which, the Gospel, salvation,
repentance are commanded to be preached to every creature, without respect of nations,
kindred, families, or tongues.

Fourthly, It magnifies and commends the merits and death of Christ,
in that it not only accounts them sufficient to save all,
but declares them to be brought so nigh unto all as thereby
to be put into the nearest capacity of salvation.

Fifthly, It exalts above all the grace of God, to which it attributeth all good,
even the least and smallest actions that are so;
ascribing thereunto not only the first beginnings and motions of good,
but also the whole conversion and salvation of the soul.

Sixthly, It contradicts, overturns, and enervates, the false doctrine of the Pelagians,
Semi-Pelagians, Socinians, and others, who exalt the light of nature,
the liberty of man`'s will,
in that it wholly excludes the natural man from having
any place or portion in his own salvation,
by any acting, moving, or working of his own, until he be first quickened, raised up,
and actuated by God`'s Spirit.

Seventhly, As it makes the whole salvation of man solely and alone to depend upon God,
so it makes his condemnation wholly and in every respect to be of himself,
in that he refused and resisted somewhat that from God wrestled and strove in his heart;
and forces him to acknowledge God`'s just judgment in rejecting him and forsaking of him.

Eighthly, It takes away all ground of despair,
in that it gives every one ground of hope and certain assurance, that they may be saved;
neither doth feed any in security,
in that none are certain how soon their day may expire:
and therefore it is a constant incitement and provocation,
and lively encouragement to every man, to forsake evil, and close with that,
which is good.

Ninthly,
It wonderfully commends as well the certainty of the Christian religion among infidels,
as it manifests its own verity to all,
in that it is confirmed and established by the experience of all men;
seeing there was never yet a man found in any place of the earth,
however barbarous and wild, but hath acknowledged that at some time or other,
less or more, he hath found somewhat in his heart,
reproving him for some things evil which he hath done, threatening a certain horror,
if he continued in them,
as also promising and communicating a certain peace and sweetness,
as he has given way to it, and not resisted it.

Tenthly, It wonderfully showeth the excellent wisdom of God,
by which he hath made the means of salvation so universal and comprehensive,
that it is not needful to recur to those miraculous and strange ways; seeing,
according to this most true doctrine, the Gospel reacheth all, of whatsoever condition,
age, or nation.

Eleventhly, It is really and effectively, though not in so many words, yet by deeds,
established and confirmed by all the preachers, promulgators,
and doctors of the Christian religion that ever were, or now are, even by those,
that otherways in their judgment oppose this doctrine; in that they all,
wherever they have been or are, or whatsoever people, place, or country they come to,
do preach to the people, and to every individual among them, that they may be saved;
entreating and desiring them to believe in Christ, who hath died for them;
so that what they deny in the general, they acknowledge of every particular:
there being no man, to whom they do not preach in order to salvation,
telling him Jesus Christ calls and wills him to believe and be saved,
and that if he refuse, he shall therefore be condemned,
and that his condemnation is of himself, such is the evidence and virtue of Truth,
that constrains its adversaries even against their wills to plead for it.

Lastly, According to this doctrine, the former argument used by the Arminians,
and evited by the Calvinists,
concerning every man`'s being bound to believe that Christ died for him, is,
by altering the assumption, rendered invincible; thus,

[.syllogism]
* That which every man is bound to believe, is true:
* But every man is bound to believe that God is merciful unto him:
* Therefore, etc.

This assumption no man can deny, seeing his mercies are said to be over all his works.
And herein, the Scripture everywhere declares the mercy of God to be,
in that he invites and calls sinners to repentance,
and hath opened a way of salvation for them;
so that though those men be not bound to believe the history of Christ`'s death and passion,
who never came to know of it,
yet they are bound to believe that God will be merciful to them, if they follow his ways,
and that he is merciful unto them, in that he reproves them for evil,
and encourages them to good.
Neither ought any man to believe that God is unmerciful to him,
or that he hath from the beginning ordained him to come into the world,
that he might be left to his own evil inclinations,
and so do wickedly as a means appointed by God, to bring him to eternal damnation; which,
were it true, as our adversaries affirm it to be of many thousands,
I see no reason why a man might not believe; for certainly a man may believe the truth.

As it manifestly appears, from the thing itself,
that these good and excellent consequences follow,
from the belief of this doctrine,
so from the probation of them it will yet more evidently appear.
To which before I come,
it is requisite to speak somewhat concerning the state of the controversy,
which will bring great light to the matter.
For from the not right understanding of a matter under debate,
sometimes both arguments on the one hand, and objections on the other, are brought,
which do no way hit the case;
and hereby also our sense and judgment therein will be more fully understood and opened.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XII.
First, then, by this __day and time of visitation__ which, we say,
God gives unto all, during which they may be saved,
we do not understand the whole time of every man`'s life;
though to some it may be extended even to the very hour of death;
as we see in the example of the thief converted upon the cross;
but such a season at least as sufficiently exonerateth God of every man`'s condemnation,
which to some may be sooner, and to others later,
according as the Lord in his wisdom sees meet.
So that many men may outlive this day,
after which there may be no possibility of salvation to them,
and God justly suffers them to be hardened, as a just punishment of their unbelief,
and even raises them up as instruments of wrath,
and makes them a scourge one against another.
Whence,
to men in this condition may be fitly applied those scriptures
which are abused to prove that God incites men necessarily to sin:
this is notably expressed by the apostle (Rom. 1, from v. 17 to the end),
but especially v. 28, "`And even as they did not like to retain God in their knowledge,
God gave them over to a reprobate mind,
to do those things which are not convenient.`" That many
may outlive this day of God`'s gracious visitation unto them,
is shown by the example of Esau (Heb. 12:16-17), who sold his birthright,
so he had it once, and was capable to have kept it; but afterwards,
when he would have inherited the blessing, he was rejected.
This appears also by Christ`'s weeping over Jerusalem (Luke 19:42), saying,
"`If thou hadst known in this thy day the things that belong unto thy peace,
but now they are hid from thine eyes,`" which plainly
imports a time when they might have known them,
which now was removed from them, though they were yet alive,
but of this more shall be said hereafter.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIII.
Secondly, by this Seed, Grace, and Word of God, and Light,
wherewith we say every man is enlightened, and hath a measure of it,
which strives with them in order to save them, and which may,
by the stubbornness and wickedness of man`'s will, be quenched, bruised, wounded,
pressed down, slain and crucified;
we understand not the proper essence and nature of God, precisely taken,
which is not divisible into parts and measures, as being a most pure, simple being,
void of all composition or division, and therefore can neither be resisted, hurt,
wounded, crucified, or slain by all the efforts and strength of men;
but we understand a spiritual, heavenly, and invisible principle, in which God,
as Father, Son and Spirit, dwells:
a measure of which divine and glorious life is in all men, as a seed,
which of its own nature, draws, invites, and inclines to God; and this we^
footnote:[Later editors substitute "`some`" for "`we.`"]
call __vehiculum Dei,__ or the spiritual body of Christ, the flesh and blood of Christ,
which came down from heaven, of which all the saints do feed,
and are thereby nourished unto eternal life.
And as every unrighteous action is witnessed against,
and reproved by this Light and Seed, so, by such actions, it is hurt, wounded, and slain,
and resiles^
footnote:[_resiles_ +++=+++ recoils. Later editors drop "`resiles or.`"]
or flees from them, even as the flesh of man flees from that,
which is of a contrary nature to it.
Now, because it is never separated from God, nor Christ, but wherever it is,
God and Christ are as wrapped up therein, therefore,
and in that respect as it is resisted, God is said to be resisted;
and where it is borne down, God is said to be pressed, as a cart under sheaves,
and Christ is said to be slain and crucified.
And on the contrary, as this seed is received in the heart,
and suffered to bring forth its natural and proper effect,
Christ comes to be formed and raised, of which the Scripture makes so much mention,
calling it "`the new man`": "`Christ within, the hope of glory.`" This is that Christ within,
which we are heard so much to speak and declare of; everywhere preaching him up,
and exhorting people to believe in the Light, and obey it,
that they may come to know Christ in them, to deliver them from all sin.

But by this,
as we do not at all intend either to equal ourselves
to that holy man the Lord Jesus Christ,
who was born of the virgin Mary, in whom all the fullness of the Godhead dwelt bodily,
nor to destroy the reality of his present existence, so neither do we,
as some have falsely calumniated us.
For, though we affirm that Christ dwells _in_ us, yet not immediately, but mediately,
as he is in that _seed,_ which is in us; whereas he, to wit, the Eternal Word,
which was with God, and was God, dwelt immediately in that holy man.
He then is as the head, and we as the members; he the vine, and we the branches.
Now as the soul of man dwells otherways and in a far more
immediate manner in the head and in the heart,
than in the hands or legs.
And as the sap, virtue,
and life of the vine lodgeth far otherwise in the stock and root than in the branches,
so God dwelleth otherwise in the man Jesus than in us.
We also freely reject the heresy of Apollinaris, who denied him to have any soul,
but said the body was only acted by the Godhead.
As also the error of Eutyches,
who made the manhood to be wholly swallowed up of the Godhead; wherefore,
as we believe he was a true and real man,
so we also believe that he continues so to be glorified in the heavens, in soul and body,
by whom God shall judge the world, in the great and general day of judgment.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIV.
Thirdly, We understand not this Seed, Light,
or Grace to be an accident, as most men ignorantly do, but a real spiritual substance,
which the soul of man is capable to feel and apprehend; from which that real, spiritual,
inward birth in believers arises called the new creature, the new man in the heart.
This seems strange to carnally minded men, because they are not acquainted with it;
but we know it, and are sensible of it, by a true and certain experience,
though it be hard for man in his natural wisdom to comprehend it,
until he come to feel it in himself, and, if he should, holding it in the mere notion,
it would avail him little.
Yet we are able to make it appear to be true,
and that our faith concerning it is not without a solid ground: for it is in, and by,
this inward and substantial seed in our hearts, as it comes to receive nourishment,
and to have a birth or geniture in us,
that we come to have those spiritual senses raised,
by which we are made capable of tasting, smelling, seeing,
and handling the things of God.
For a man cannot reach unto those things by his natural spirit and senses,
as is above declared.

Next, we know it to be a _substance_ because it subsists in the
hearts of wicked men even while they are in their wickedness,
as shall be hereafter proved more at large.
Now no accident can be in a subject without it give the subject its own denomination;
as where whiteness is in a subject, there the subject is called white.
So we distinguish betwixt holiness as it is an accident,
which denominates man so as the seed receives a place in him,
and betwixt this holy substantial seed,
which many times lies in man`'s heart as a naked grain in a stony ground.
So also as we may distinguish betwixt health and medicine:
health cannot be in a body, without the body be called healthful,
because health is an accident;
but medicine may be in a body that is most unhealthful for that it is a substance.
And as when a medicine begins to work,
the body may in some respect be called healthful and in some respect unhealthful,
so we acknowledge as this divine medicine receives place in man`'s
heart it may denominate him in some part holy and good,
though there remain yet a corrupted, unmortified part,
or some part of the evil humors unpurged out;
for where two contrary accidents are in one subject, as health and sickness in a body,
the subject receives its denomination from the accident which prevails most;
so many men are called saints, good and holy men, and that truly,
when this holy seed hath wrought in them in a good measure
and hath somewhat leavened them into its nature,
though they may be yet liable to many infirmities and weaknesses,
yes and to some iniquities.
For as the seed of sin and ground of corruption,
yea and the capacity of yielding thereunto and sometimes actually falling,
doth not denominate a good and holy man impious;
so neither doth the seed of righteousness in evil men,
and the possibility of their becoming one with it,
denominate them good or holy.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XV. Fourthly,
We do not hereby intend any ways to lessen or derogate
from the atonement and sacrifice of Jesus Christ:
but on the contrary, do magnify and exalt it.
For as we believe all those things to have been certainly
transacted which are recorded in the holy Scriptures,
concerning the birth, life, miracles, sufferings, resurrection and ascension of Christ;
so we do also believe,
that it is the duty of everyone to believe it to
whom it pleases God to reveal the same,
and to bring to them the knowledge of it;
yea we believe it were damnable unbelief not to believe, when so declared;
but to resist that holy seed, which,
as minded would lead and incline every one to believe it, as it is offered unto them;
though it revealeth not in everyone the outwardly and explicit knowledge of it,
nevertheless it always assenteth to it, __ubi declaratur,__ where it is declared.
Nevertheless as we firmly believe it was necessary that Christ should come,
that by his death and sufferings he might offer up himself a sacrifice to God,
for our sins, who his own self "`bore our sins in his own body on the tree`";
so we believe, that the remission of sins, which any partake of, is only in,
and by virtue of that most satisfactory sacrifice, and no otherwise.
For it is "`by the obedience of that one that the free gift
is come upon all to justification,`" for we affirm,
that as all men partake of the fruit of Adam`'s fall, in that,
by reason of that evil seed, which through him is communicated unto them,
they are prone and inclined unto evil,
though thousands of thousands be ignorant of Adam`'s fall,
neither ever knew of the eating of the forbidden fruit;
so also many may come to feel the influence of this holy and divine Seed, and Light,
and be turned from evil to good by it,
though they knew nothing of Christ`'s coming in the flesh,
through whose obedience and sufferings it is purchased unto them.
And, as we affirm it is absolutely needful that those
do believe the history of Christ`'s outward appearance,
whom it pleased God to bring to the knowledge of it; so we do freely confess,
that even that outward knowledge is very comfortable to such as are subject to,
and led by the inward Seed and Light.
For, not only doth the sense of Christ`'s love and sufferings tend to humble them,
but they are thereby also strengthened in their faith,
and encouraged to follow that excellent pattern which he hath left us,
"`who suffered for us,`" as saith the apostle Peter (1 Pet. 2:21),
"`leaving us an example that we should follow his steps`":
and many times we are greatly edified and refreshed with the gracious sayings,
which proceed out of his mouth.
The history then is profitable and comfortable, with the mystery, and never without it;
but the mystery is,
and may be profitable without the explicit and outward knowledge of the history.

But Fifthly, this brings us to another question, to wit,
Whether Christ be in all men or no?
Which sometimes hath been asked us, and arguments brought against it,
because indeed it is to be found in some of our writings
that "`Christ is in all men,`" and we often are heard,
in our public meetings and declarations, to desire every man to come to^
footnote:[Later editors drop "`come to.`"]
know and be acquainted with Christ in them, telling them, that Christ is in them.
It is fit therefore, for removing of all mistakes, to say something, in this place,
concerning this matter.
We have said before how that a divine, spiritual, and supernatural Light is in all men;
how that divine supernatural Light or Seed is vehiculum Dei:
how that God and Christ dwelleth in it and is never separated from it;
also how that (as it is received and closed with in the
heart) Christ comes to be formed and brought forth.
But we are far from ever having said, that Christ is thus formed in all men,
or in the wicked.
For that is a great attainment,
which the apostle travailed that it might be brought forth in the Galatians.
Neither is Christ in all men by way of union, or indeed, to speak strictly,
by way of inhabitation; because this inhabitation, as it is generally taken,
imports union, or the manner of Christ`'s being in the saints.
As it is written "`I will dwell in them,
and walk in them`" (2 Cor. 6:16). But in regard __Christ is in all men as in a seed,__
yea, and that he never is,
nor can be separate from that holy pure Seed and Light which is in all men;
therefore may it be said in a larger sense that he is in all, even as we observed before.
The Scripture saith (Amos 2:13), God is pressed down as a cart under sheaves;
and (Heb. 6:6) Christ is crucified in the ungodly;
though to speak properly and strictly, neither can God be pressed down, nor Christ,
as God, be crucified.
In this respect then, as he is in the seed, which is in all men,
we have said "`Christ is in all men,`" and have preached
and directed all men to __Christ in them;__
who lies crucified in them by their sins and iniquities,
that they may "`look upon him whom they have pierced,`" and repent: whereby he,
that now lies, as it were slain and buried in them, may come to be raised,
and have dominion in their hearts, over all.
And thus also the apostle Paul preached to the Corinthians
and Galatians (1 Cor. 2:2),
// lint-disable invalid-characters
"`Christ crucified in them,`" ἐν ὑμῖν as the Greek hath it.
This Jesus Christ was that which the apostle desired to know in them,
and make known _unto_ them, that they might come to be sensible,
how they had thus been crucifying Christ, that so they might repent and be saved.
And forasmuch as Christ is called "`that Light,
that enlightens every man,`" "`the Light of the world,`"
therefore the Light is taken for Christ,
who truly is the fountain of all light, and hath his habitation in it forever.
Thus the Light of Christ is sometimes called Christ, i.e., that in which Christ is,
and from which he is never separated.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XVI.
Sixthly, It will manifestly appear by what is above said,
that we understand not this divine principle to be any part of man`'s nature,
nor yet to be any relics of any good which Adam lost by his fall:
in that we make it a distinct separate thing from man`'s soul,
and all the faculties of it.
Yet such is the malice of our adversaries,
that they cease not sometimes to calumniate us, as if we preached up a natural light,
or the light of man`'s natural conscience.
Next, there are, that lean to the doctrine of Socinus and Pelagius,
who persuade themselves through mistake, and out of no ill design to injure us,
as if this, which we preach up, were some natural power and faculty of the soul,
and that we only differ in the wording of it, and not in the thing itself.
Whereas there can be no greater difference than is betwixt us in that matter:
for we certainly know that this Light of which we speak is not only distinct,
but of a different nature from the soul of man, and its faculties.
Indeed that man, as he is a rational creature,
hath reason as a natural faculty of his soul,
by which he can discern things that are rational, we deny not;
for this is a property natural and essential to him,
by which he can know and learn many arts and sciences,
beyond what any other animal can do by the mere animal principle.
Neither do we deny, but by this rational principle man may apprehend in his brain,
and in the notions, a knowledge of God and spiritual things;
yet that not being the right organ, as,
in the second proposition hath more at length been signified,
it cannot profit him towards salvation, but rather hindereth;
and indeed the great cause of the apostasy hath been,
that man hath sought to fathom the things of God,
in and by this natural and rational principle, and to build up a religion in it,
neglecting and overlooking this principle and seed of God in the heart;
so that herein, in the most universal and catholic sense,
hath Antichrist in every man "`set up himself, and sitteth in the temple of God, as God,
and above everything that is called God.`" For men being "`the temple
of the Holy Ghost,`" as saith the apostle (1 Cor. 3:16),
when the rational principle sets up itself there, above the seed of God,
to reign and rule as a prince in spiritual things,
while the holy seed is wounded and bruised, there is Antichrist in every man,
or somewhat exalted above and against Christ.
Nevertheless we do not hereby affirm, as if man had received his reason to no purpose,
or to be of no service unto him, in no wise;
we look upon reason as fit to order and rule man in things natural: for,
as God gave two great lights to rule the outward world, the sun and moon,
the greater light to rule the day, and the lesser light to rule the night;
so hath he given man the Light of his Son, a spiritual divine Light,
to rule him in the things spiritual,
and the light of reason to rule him in things natural.
And even as the moon borrows her light from the sun, so ought men,
if they would be rightly and comfortably ordered in natural things,
to have their reason enlightened by this divine and pure Light.
Which enlightened reason, in those that obey and follow this true Light,
we confess may be useful to man even in spiritual things,
as it is still subservient and subject to the other; even as the animal life in man,
regulated and ordered by his reason, helps him in going about things, that are rational.
We do further rightly distinguish this from man`'s natural conscience; for conscience,
being that in man which ariseth from the natural faculties of man`'s soul,
may be defiled and corrupted; it is said expressly of the impure (Tit. 1:15),
"`That even their mind and conscience is defiled.`"
But this Light can never be corrupted nor defiled;
neither did it ever consent to evil or wickedness in any: for it is said expressly,
that it "`makes all things manifest that are reprovable`" (Eph. 5:13),
and so is a faithful witness for God against every unrighteousness in man.
Now conscience, to define it truly, comes from _conscire,_
and is that knowledge, which ariseth in man`'s heart from what agreeth, contradicteth,
or is contrary to anything believed by him,
whereby he becomes conscious to himself that he transgresseth by
doing that which he is persuaded he ought not to do.
So that, the mind being once blinded or defiled with a wrong belief,
there ariseth a conscience from that belief, which troubles him when he goes against it.
As for example:
a Turk who hath possessed himself with a false belief
that it is unlawful for him to drink wine,
if he do it, his conscience smites him for it; but though he keep many concubines,
his conscience troubles him not,
because his judgment is already defiled with a false
opinion that it is lawful for him to do the one,
and unlawful to do the other.
Whereas if the Light of Christ in him were minded, it would reprove him,
not only for committing fornication, but also, as he became obedient thereunto,
inform him that Muhammad is an impostor; as well as Socrates was informed by it,
in his day, of the falsity of the heathens`' gods.

So, if a Papist eat flesh in Lent,
or be not diligent enough in adoration of saints and images,
or if he should condemn images, his conscience would smite him for it,
because his judgment is already blinded with a false belief concerning these things.
Whereas the Light of Christ never consented to any of those abominations.
Thus then, man`'s natural conscience is sufficiently distinguished from it;
for conscience followeth the judgment, doth not inform it.
But this Light, as it is received, removes the blindness of the judgment,
opens the understanding, and rectifies both the judgment and conscience.
So we confess also, that conscience is an excellent thing,
where it is rightly informed and enlightened.
Wherefore some of us have fitly compared it to a lantern,
and the Light of Christ to the candle:
a lantern is useful when a clear candle burns and shines in it, but otherwise of no use.
To the Light of Christ then _in_ the conscience, and not to man`'s natural conscience,
it is that we continually commend men: this, not that, is it which we preach up,
and direct people to, as to a most certain guide unto life eternal.

Lastly, This Light, Seed, etc., appears to be no power or natural faculty of man`'s mind;
because a man that is in his health, can, when he pleases, stir up, move,
and exercise the faculties of his soul; he is absolute master of them;
and except there be some natural cause or impediment in the way,
he can use them at his pleasure:
but this Light and Seed of God in man he cannot move and stir up when he pleaseth;
but it moves, blows, and strives with man, as the Lord seeth meet.
For though there be a possibility of salvation to every man during the day of his visitation,
yet cannot a man,
at any time when he pleaseth or hath some sense of his misery,
stir up that Light and Grace, so as to procure to himself tenderness of heart;
but he must wait for it: which comes upon _all_ at certain times and seasons,
wherein it works powerfully upon the soul, mightily tenders it, and breaks it;
at which time, if man resist it not, but closes with it,
he comes to know salvation by it.
Even as the lake of Bethesda did not cure all those that washed in it,
but such only as washed first after the angel had moved upon the waters;
so God moves in love to mankind, in this seed in his heart, at some singular times,
setting his sins in order before him, and seriously inviting him to repentance,
offering to him remission of sins and salvation; which if man accept of, he may be saved.
Now there is no man alive, and I am confident there shall be none,
to whom this paper shall come, who,
if they will deal faithfully and honestly with their own hearts,
will not be forced to acknowledge, that they have been sensible of this in some measure,
less or more;
which is a thing that man cannot bring upon himself with all his pains and industry.
This then, O man and woman, is the day of God`'s gracious visitation to thy soul,
which thou shalt be happy forever if thou resist not.
This is the day of the Lord, which, as Christ saith, is like the lightning,
which shineth from the east unto the west; and the wind or spirit,
which blows upon the heart, and no man knows whither it goes,
nor whence it comes.^
footnote:[Matt. 24:27; John 3:8.]

[.small-break]
'''

// lint-disable invalid-characters "§"
§XVII.
And lastly,
this leads me to speak concerning the manner of this
Seed or Light`'s operation in the hearts of all men,
which will show yet more manifestly how we differ vastly
from all those that exalt a natural power or light in man;
and how our principle leads, above all others,
to attribute our whole salvation to the mere power, spirit, and grace of God.

To them then, that ask us after this manner,
How do ye differ from the Pelagians and Arminians?
For if two men have equal sufficient Light and Grace, and the one be saved by it,
and the other not; is it not because the one improves it, the other not?
Is not then the will of man the cause of the one`'s salvation, beyond the other?
I say, to such we thus answer,
that as the Grace and Light in all is sufficient to save all,
and of its own nature would save all; so, it strives and wrestles with all,
for to save them; he that resists its striving, is the cause of his own condemnation;
he that resists it not, it becomes his salvation: so that in him, that is saved,
the working is __of the grace,__ and not __of the man;__ and it is a passiveness,
rather than an act: though afterwards, as man is wrought upon,
there is a will raised in him, by which he comes to be a coworker with the grace:
for according to that of Augustine, "`He that made us without us,
will not save us without us.`" So that the first step is not by man`'s working,
but by his not contrary working.
And we believe, that at these singular seasons of every man`'s visitation above mentioned,
as man is wholly unable, of himself, to work with the grace,
neither can he move one step out of the natural condition,
until the grace lay hold upon him; so it is possible for him to be passive,
and not to resist it, as it is also possible for him to resist it.
So we say, the grace of God works in and upon man`'s nature, which,
though of itself wholly corrupted and defiled, and prone to evil, yet,
is capable to be wrought upon by the grace of God; even as iron,
though a hard and cold metal, of itself,
may be warmed and softened by the heat of the fire, and wax melted by the sun.
And, as iron or wax, when removed from the fire, or sun,
returneth to its former condition of coldness and hardness; so man`'s heart,
as it resists, or retires, from the grace of God, returns to its former condition again.
I have often had the manner of God`'s working, in order to salvation towards _all_ men,
illustrated to my mind by one or two clear examples, which I shall here add,
for the information of others.

The first is, of a man heavily diseased;
to whom I compare man in his fallen and natural condition.
I suppose God, who is the great physician, not only to give this man physic,
after he hath used all the industry he can for his own health,
by any skill or knowledge he hath of his own.
As those, that say, If a man improve his reason or natural faculties,
God will superadd grace.
Or, as others say,
that he cometh and maketh offer of a remedy to this man outwardly,
leaving it to the liberty of man`'s will either to receive it or reject it.
But He, even the Lord, this great physician,
cometh and poureth the remedy into his mouth, and as it were layeth him in his bed,
so that, if the sick man be but passive, it will necessarily work the effect:
but if he be stubborn and untoward, and will needs rise up and go forth into the cold,
or eat such fruits as are hurtful to him, while the medicine should operate; then,
though of its nature it tendeth to cure him, yet it will prove destructive to him,
because of those obstructions which it meeteth with.
Now as the man that should thus undo himself would
certainly be the cause of his own death;
so, who will say, that, if cured, he owes not his health wholly to the physician,
and not to any deed of his own?
Seeing his part was not any action, but a passiveness?

The second example is of divers men lying in a dark pit together,
where all their senses are so stupefied that they are scarce sensible of their own misery.
To this I compare man in his natural, corrupt, fallen condition; I suppose not,
that any of these men wrestling to deliver themselves,
do thereby stir up or engage one able to deliver them to give them his help.
Saying within himself, I see one of these men willing to be delivered,
and doing what in him lies, therefore he deserves to be assisted; as say the Socinians,
Pelagians, and Semi-Pelagians.
Neither do I suppose that this deliverer comes to
the top of the pit and puts down a ladder,
desiring them that will to come up;
and so put them upon using their own strength and will to come up;
as do the Jesuits and Arminians: yet, as they say,
such are not delivered without the grace;
seeing the grace is that ladder by which they were delivered.
But I suppose that the deliverer comes at certain times,
and fully discovers and informs them of the great misery and hazard they are in,
if they continue in that noisome and pestiferous place; yea,
forces them to a certain sense of their misery,
(for the wickedest men at times are made sensible of their misery by God`'s visitation),
and not only so, but lays hold upon them, and gives them a pull,
in order to lift them out of their misery; which if they resist not, will save them;
only they may resist it.
This, being applied as the former, doth the same way illustrate the matter.
Neither is the Grace of God frustrated, though the effect of it be diverse,
according to its object,
being the ministration of mercy and love in those that reject it not,
but receive it (John 1:12), but the ministration of wrath and condemnation,
in those that do reject it (John 3:19), even as the sun, by one act or operation,
melteth and softeneth the wax, and hardeneth the clay.
The nature of the sun is to cherish the creation,
and therefore the living are refreshed by it, and the flowers send forth a good savour,
as it shines upon them, and the fruits of the trees are ripened;
yet cast forth a dead carcass, a thing without life,
and the same reflection of the sun will cause it to stink, and putrefy it;
yet is not the sun said thereby to be frustrated of its proper effect.
So every man, during the day of his visitation,
is shined upon by the sun of righteousness, and capable of being influenced by it,
so as to send forth good fruit, and a good savour, and to be melted by it;
but when he hath sinned out his day, then the same sun hardeneth him,
as it doth the clay, and makes his wickedness more to appear and putrefy,
and send forth an evil savour.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XVIII.
Lastly, As we truly affirm that God willeth no man to perish,
and therefore hath given to all, grace sufficient for salvation, so we do not deny,
but that, in a special manner he worketh in some, in whom grace so prevaileth,
that they necessarily obtain salvation; neither doth God suffer them to resist.
For it were absurd to say that God had not far otherwise extended
himself towards the virgin Mary and the apostle Paul,
than towards many others.
Neither can we affirm, that God equally loved the beloved disciple John,
and Judas the traitor.
In so far, nevertheless,
as none wanted such a measure of grace by which they might have been saved,
all are justly inexcusable.
And also, God working in those to whom this prevalency of grace is given,
doth so hide himself, to shut out all security and presumption, that such may be humbled,
and the free grace of God magnified, and all reputed to be of the free gift;
and nothing from the strength of self.
Those also, who perish, when they remember those times of God`'s visitation towards them,
wherein he wrestled with them by his Light and Spirit,
are forced to confess that there was a time wherein the door of mercy was open unto them,
and that they are justly condemned, because they rejected their own salvation.

Thus both the mercy and justice of God are established,
and the will and strength of man are brought down and rejected;
his condemnation is made to be of himself, and his salvation only to depend upon God:
also by these positions two great objections,
which often are brought against this doctrine, are well solved.

The first is deduced from those places of Scripture,
wherein God seems precisely to have decreed and predestinated some to salvation;
and for that end, to have ordained certain means, which fall not out to others;
as in the calling of Abraham, David, and others, and in the conversion of Paul, for,
these being numbered among such to whom this prevalency is given,
the objection is easily loosed.

The second is drawn from those places,
wherein God seems to have ordained some wicked persons to destruction;
and therefore to have obdured their hearts, to force them unto great sins,
and to have raised them up, that he might show in them his power: who,
if they be numbered amongst those men whose day of visitation is passed over,
that objection is also solved;
as will more evidently appear to any one that will
make a particular application of those things,
which I at this time, for brevity`'s sake, thought meet to pass.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIX.
Having thus clearly and evidently stated the question,
and opened our mind and judgment in this matter,
as divers objections are hereby prevented,
so will it make our proof both the easier and the shorter.

The first thing to be proved, is,
__that God hath given to every man a day or time of visitation,
wherein it is possible for him to be saved.__
If we can prove that there is a day and time given, in which those might have been saved,
that actually perish, the matter is done.
For none deny but those that are saved have a day of visitation.
This then appears by the regrets and complaints which the
Spirit of God throughout the whole Scriptures makes,
even to those that did perish;
challenging them for that they did not accept of nor close
with God`'s visitation and offer of mercy to them.
Thus the Lord express himself then first of all to Cain (Gen. 4:6-7),
"`And the Lord said unto Cain, Why art thou wroth?
and why is thy countenance fallen?
If thou dost well, shalt thou not be accepted?
If thou dost not well,
sin lieth at the door.`" This was said to Cain before he slew his brother Abel,
when the evil seed began to tempt him and work in his heart,
we see how God gave warning to Cain in season,
and in the day of his visitation towards him acceptance and remission if he did well:
for this interrogation, "`Shalt thou not be accepted?`" imports an affirmative,
"`Thou shalt be accepted, if thou dost well.`" So that if we may trust God Almighty,
the fountain of all Truth and equity,
it was possible in a day even for Cain to be accepted.
Neither could God have proposed the doing of good as a condition,
if he had not given Cain sufficient strength whereby he was capable to do good.
This the Lord himself also shows,
even that he gave a day of visitation to the old world (Gen. 6:3):
"`And the Lord said, My Spirit shall not always strive in man`";
for so it ought to be translated.
This manifestly implies that his Spirit did strive with man,
and doth strive with him for a season;
which season expiring God ceaseth to strive with them in order to save them;
for the Spirit of God cannot be said to strive with
man after the day of his visitation is expired,
seeing it naturally and without any resistance works its effect then,
to wit continually to judge and condemn them.
From this day of visitation that God hath given to everyone,
is it that he is said to "`wait to be gracious`" (Isa. 30:18),
and to be "`long-suffering`" (Ex. 34:6; Num. 14:18; Ps. 86:15;
Jer. 15:15). Here the prophet Jeremy, in his prayer,
lays hold upon the long-suffering of God;
and in his expostulating with God he shuts out the
objection of our adversaries in the 18th verse:
"`Why is my pain perpetual?
and my wound incurable?
which refuseth to be healed, wilt thou altogether be unto me as a liar,
and as waters that fail?`" Whereas according to our adversaries`' opinion,
the pain of the most part of men is perpetual, and their wound altogether incurable.
Yea, the offer of the Gospel and of salvation unto them is as a lie,
and as waters that fail, being never intended to be of any effect unto them.
The apostle Peter says expressly that this "`long-suffering of God
waited in the days of Noah for those of the old world`" (1 Pet. 3:20),
which being compared with that of Gen. 6:3, before mentioned,
doth sufficiently hold forth our proposition.
And that none may object that this long-suffering or striving
of the Lord was not in order to save them,
the same apostle saith expressly (2 Pet. 3:15),
that "`the long-suffering of God is to be accounted salvation`";
and with this "`long suffering,`" a little before, in the 9th verse,
he couples "`that God is not willing that any should perish.`" Where,
taking himself to be his own interpreter, as he is most fit,
he holdeth forth that those to whom the Lord is long-suffering (which
he declareth he was to the wicked of the old world and is now to all,
"`not willing that any should perish`") they are to
account this long-suffering of God to them salvation.
Now how or in what respect can they account it salvation,
if there be not so much as a possibility of salvation conveyed to them therein?
For it were not salvation to them if they could not be saved by it.
In this matter Peter further refers to the writings of Paul,
holding forth this to have been the universal doctrine.
Where it is observable what he adds upon this occasion,
how there are some things in Paul`'s epistles hard to be understood,
which the unstable and unlearned wrest to their own destruction:
insinuating plainly this of those expressions in Paul`'s epistles, as Rom. 9, etc.,
which some, unlearned in spiritual things,
did make to contradict the truth of God`'s long-suffering towards all,
in which he willeth not any of them should perish, and in which they all may be saved.
Would to God many had taken more heed than they have done to this
advertisement! That place of the apostle Paul,
which Peter seems here most particularly to hint at,
doth much contribute also to clear the matter (Rom. 2:4):
"`Despisest thou the riches of his goodness and forbearance and long-suffering,
not knowing that the goodness of God leadeth thee to repentance?`"
Paul speaketh here to the unregenerate and to the wicked,
who in the following verse he saith "`treasure up wrath unto the day of wrath`";
and to such he commends the riches of the forbearance and long-suffering of God;
showing that the tendency of God`'s goodness leadeth to repentance.
How could it necessarily tend to lead them to repentance,
how could it be called "`riches`" or "`goodness`" to them,
if there were not a time wherein they might repent by it,
and come to be sharers of the riches exhibited in it?
From all which I thus argue:

[.syllogism]
* If God plead with the wicked, from the possibility of their being accepted; if God`'s Spirit strive _in_ them for a season, in order to save them, who afterwards perish; if he wait to be gracious unto them; if he be long-suffering towards them; and if this long suffering be salvation to them, while it endureth, during which time God willeth them not to perish, but exhibiteth to them the riches of his goodness and forbearance, to lead them to repentance; then there is a day of visitation wherein such might have been, or some such now may be saved, who have perished and may, if they repent, not perish:^
footnote:[Later editors replace "`may, if they repent,
not perish`" with "`may perish, if they repent not.`"]
* But the first is true;
* Therefore also the last.

// lint-disable invalid-characters "§"
§XX. Secondly, This appeareth from the prophet Isaiah (5:4):
"`What could I have done more to my vineyard?`" For in the 2nd verse he saith:
"`He had fenced it, and gathered out the stones thereof,
and planted it with the choicest vine; and yet,`" saith he,
"`when I looked it should have brought forth grapes,
it brought forth wild grapes.`" Wherefore he calleth the inhabitants of Jerusalem,
and men of Judah, to judge betwixt him and his vineyard, saying;
"`What could I have done more to my vineyard than I have done in it?`" and yet, as is said,
"`it brought forth wild grapes.`" Which was applied to many in Israel,
who refused God`'s mercy.
The same example is used by Christ (Matt. 21:33; Mark 12:1; Luke 20:9),
where Jesus shows how to some a vineyard was planted,
and all things given necessary for them,
to get them fruit to pay or restore to their master;
and how the master many times waited to be merciful to them,
in sending servants after servants, and passing by many offenses,
before he determined to destroy and cast them out.
First then, this cannot be understood of the saints, or of such as repent, and are saved;
for it is said expressly,
"`He will destroy them.`" Neither would the parable any ways have answered the end,
for which it is alleged, if these men had not been in a capacity to have done good, yea,
such was their capacity, that Christ saith in the prophet,
"`What could I have done more?`" So that it is more than manifest, that by this parable,
repeated in three sundry evangelists, Christ holds forth his long-suffering towards men,
and their wickedness, to whom means of salvation being afforded, do nevertheless resist,
to their own condemnation.
To these also are parallel these scriptures: Prov. 1:24-26; Jer. 18:9-10;
Matt. 18:32-34; Acts 13:46.

Lastly, that there is a day of visitation given to the wicked,
wherein they might have been saved, and, which being expired,
they are shut out from salvation,
appears evidently by Christ`'s lamentation over Jerusalem,
expressed in three sundry places (Matt. 23:37; Luke 13:34; and 19:41-42):
"`And when he was come near, he beheld the city, and wept over it, saying,
if thou hadst known, even thou, at least, in this thy day, the things,
which belong unto thy peace; but now they are hid from thine eyes.`" Than which,
nothing can be said more evident to prove our doctrine.
For first,
he insinuates that there was a day wherein the inhabitants of Jerusalem
might have known those things that belonged to their peace.
Secondly, that during that day he was willing to have gathered them,
even as a hen gathereth her chickens.
A familiar example, yet very significative, in this case,
which shows that the offer of salvation made unto them was not in vain,
on his part, but as really, and with as great cheerfulness and willingness,
as a hen gathereth her chickens.
Such as is the love and care of the hen towards her brood,
such is the care of Christ to gather lost men and women,
to redeem them out of their corrupt and degenerate state.
Thirdly, that because they refused,
the things belonging to their peace were hid from their eyes.
Why were they hid?
because ye would not suffer me to gather you; ye would not see those things,
that are good for you, in the season of God`'s love towards you; and therefore, now,
that day being expired, ye cannot see them: and, for a farther judgment,
God suffers you to be hardened in unbelief.

So it is, after real offers of mercy and salvation rejected,
that God hardens men`'s hearts,^
footnote:[Later editors replace "`God hardens men`'s hearts`" with "`men`'s hearts are hardened.`"]
and not before.
Thus that saying is verified, "`To him that hath, shall be given;
and from him that hath not,
shall be taken away even that which he hath.`" This may seem a riddle,
yet is according to this doctrine easily solved.
He hath not, because he hath lost the season of using it,
and so to him it is now as nothing;
for Christ uses this expression (Matt. 25:26) upon the occasion
of the taking the one talent from the slothful servant,
and giving it to him that was diligent; which talent was no ways insufficient, of itself,
but of the same nature with those given to the others;
and therefore the Lord had reason to exact the profit of it proportionably,
as well as from the rest.
So I say, it is after the rejecting of the day of visitation,
that the judgment of obduration is inflicted upon men and women,
as Christ pronounceth it upon the Jews, out of Isa. 6:9,
which all the four evangelists make mention of (Matt. 13:14; Mark 4:12;
Luke 8:10; John 12:40). And last of all the apostle Paul,
after he had made offer of the Gospel of salvation to the Jews at Rome,
pronounceth the same (Acts 28:26), after that some believed not;
"`Well spake the Holy Ghost, by Isaiah the prophet, unto our fathers, saying,
Go unto this people, and say, Hearing ye shall hear, and shall not understand;
and seeing ye shall see, and shall not perceive.
For the heart of this people is waxed gross, and their ears are dull of hearing,
and their eyes have they closed; lest they should see with their eyes,
and hear with their ears, and understand with their hearts, and should be converted,
and I should heal them.`" So it appears, that God would have them to see,
but they closed their eyes; and therefore they are justly hardened.
Of this matter Cyril of Alexandria upon John, lib.
6, cap.
21, speaks well, answering to this objection:

"`But some may say, if Christ be come into the world, that those that see may be blinded,
their blindness is not to be imputed unto them;
but it rather seems that Christ is the cause of their blindness, who saith,
he is come into the world, that those that see may be blinded.
But they speak not rationally, who object these things unto God,
and are not afraid to call him the author of evil.
For, as the sensible sun is carried upon our horizon,
that it may communicate the gift of its clearness unto all,
and make its light shine upon all; yet if anyone close his eyelids,
or willingly turn himself from the sun, refusing the benefit of its light,
he wants its illumination, and remains in darkness, not through the defect of the sun,
but through his own fault.
So that the true Sun, who came to enlighten those, that sat in darkness,
and in the region of the shadow of death, visited the earth, for this cause,
that he might communicate unto all the gift of knowledge and grace,
and illuminate the inward eyes of all, by a peculiar^
footnote:[Later editors replace "`peculiar`" with "`spiritual.`"]
splendor:
but many reject the gift of this heavenly Light freely given to them,
and have closed the eyes of their minds,
lest so excellent an illumination or irradiation
of the eternal Light should shine unto them.
It is not then through defect of the true Sun that they are blinded,
but only through their own iniquity and hardness; for, as the wise man saith (Wisdom 2),
'`their wickedness hath blinded them.`'`"

[.offset]
From all which I thus argue:

[.syllogism]
* If there was a day, wherein the obstinate Jews might have known the things that belonged to their peace, which, because they rejected it, was hid from their eyes; if there was a time, wherein Christ would have gathered them, who, because they refused, could not be gathered; then such as might have been saved, do actually perish, that slighted the day of God`'s visitation towards them, wherein they might have been converted and saved.
* But the first is true;
* Therefore also the last.

// lint-disable invalid-characters "§"
§XXI.
Secondly, That which comes in the second place to be proved is,
that whereby God offers to work this salvation during the day of every man`'s visitation,
and that is that he hath given to every man a measure of saving, sufficient,
and supernatural Light and Grace.
This I shall do, by God`'s assistance,
by some plain and clear testimonies of the Scripture.

First, from that of John 1:9: "`That was the true Light,
which lighteth every man that cometh into the world.`"
This place doth so clearly favour us,
that, by some, it is called "`the Quakers`' text`";
for it doth evidently demonstrate our assertion;
so that it scarce needs either consequence or deduction,
seeing itself is a consequence of two propositions asserted in the former verses,
from which it followeth, as a conclusion in the very terms of our faith.
The first of these propositions is, "`The life that is in him is the Light of men`";
the second, "`The Light shineth in the darkness,`" and from these two, he infers,
and "`He is the true Light, that lighteth every man that cometh into the world.`"

From whence I do, in short, observe,
that this divine apostle calls Christ the Light of men,
and giveth us this as one of the chief properties,
at least considerably and especially to be observed by us; seeing hereby,
as he is the Light, and as we walk with him in that Light, which he communicates to us,
we come to have fellowship and communion with him;
as the same apostle saith elsewhere (1 John 1:7). Secondly,
that "`this Light shineth in darkness,
though the darkness comprehend it not.`" Thirdly,
that this "`true Light enlighteneth every man that
cometh into the world.`" Where the apostle,
being directed by God`'s Spirit, hath carefully avoided their captiousness,
that would have restricted this to any certain number.
Where every one is, there is none excluded.
Next, should they be so obstinate, as sometimes they are,
as to say that this +++[+++"`every man`"]
is only every one of the elect: these words following,
"`every man that cometh into the world,`" would obviate that objection.
So that, it is plain, there comes no man into the world,
whom Christ hath not enlightened in some measure,
and in whose dark heart this Light doth not shine,
though the "`darkness comprehend it not,`" yet it shineth there;
and the nature thereof is to dispel the darkness, where men shut not their eyes upon it.
Now for what end this Light is given, is expressed (v. 7),
where John is said to come for a "`witness, to bear witness to the Light,
that all men through it might believe`"; to wit, through the Light,
// lint-disable invalid-characters
δί αὐτοῦ which doth very well agree with ϕωτὸῦ,
as being the nearest antecedent;
though most translators have (to make it suit with
their own doctrine) made it relate to John,
as if all men were to believe through John.
For which, as there is nothing directly in the text,
so it is contrary to the very strain of the context.
For, seeing Christ hath lighted every man with this Light,
is it not that they may come to believe through it?
All could not believe through John, because all men could not know of John`'s testimony;
whereas every man being lighted by this, may come therethrough to believe.
John shined not in the darkness; but this Light shineth in the darkness, that,
having dispelled the darkness, it may produce and beget faith.
And lastly, we must believe through that, and become believers through that,
by walking in which, fellowship with God is known and enjoyed; but,
as hath been above observed,
it is by walking in this Light that we have this communion and fellowship,
not by walking in John, which were nonsense.
// lint-disable invalid-characters
So that this relative δί αὐτοῦ
must needs be referred to the Light, whereof John bears witness,
that through that Light, wherewith Christ hath lighted every man,
all men might come to believe.
Seeing then this Light is the Light of Jesus Christ,
and the Light through which men come to believe,
I think it needs not be doubted but that it is a supernatural, saving,
and sufficient Light.
If it were not supernatural, it could not be properly called the Light of Jesus;
for though all things be his, and _of_ him, and _from_ him,
yet those things which are common and peculiar to our nature, as being a part of it,
we are not said in so special a manner to have from Christ.
Moreover, the evangelist is holding out to us here the office of Christ as mediator,
and the benefits which, from him, as such, do redound unto us.

Secondly, It cannot be any of the natural gifts or faculties of our soul,
whereby we are said here to be enlightened,
because this Light is said to "`shine in the darkness`" and cannot be comprehended by it.
Now this darkness is no other but man`'s natural condition and state;
in which natural state he can easily comprehend, and doth comprehend,
those things that are peculiar and common to him as such.
That man in his natural condition is called darkness, see Eph. 5:8:
"`For ye were sometimes darkness, but now are ye light in the Lord.`" And in other places,
as Acts 26:18, Col. 1:1,13 Thess.
5:5, where the condition of man in his natural state is termed "`darkness`": therefore,
I say, this Light cannot be any natural property or faculty of man`'s soul,
but a supernatural gift and grace of Christ.

Thirdly, It is __sufficient and saving.__

[.syllogism]
* That, which is given, "`that all men through it may believe,`" must needs be saving and sufficient: that, by walking in which, fellowship with the saints, and "`the blood of Christ, which cleanseth from all sin,`" is possessed, must be sufficient:
* But such is the Light (1 John 1:7).
* Therefore, etc.

[.offset]
Moreover,

[.syllogism]
* That, which we are commanded to believe in, "`that we may become the children of the Light,`" must be a supernatural, sufficient, and saving principle:
* But we are commanded to believe in this Light:
* Therefore, etc.

The proposition cannot be denied.
The assumption is Christ`'s own words (John 12:36): "`While ye have the Light,
believe in the Light, that ye may be the children of the Light.`"

To this they object, that by "`Light`" here is understood Christ`'s outward person,
in whom he would have them believe.

That they ought to have believed in Christ, that is,
that he was the Messiah that was to come, is not denied;
but how they evince that Christ intended that here I see not:
nay the place itself shows the contrary by these words, "`While ye have the Light`";
and by the verse going before,
"`Walk while ye have the Light lest darkness come upon you.`" Which
words import that when that Light in which they were to believe was removed,
then they should lose the capacity or season of believing.
Now this could not be understood of Christ`'s person; the Jews might have believed in him,
and many did savingly believe in him, as all Christians do at this day, when the person,
to wit, his bodily presence or outward man is far removed from them.
So that this Light in which they were commanded to believe must be that inward,
spiritual Light, that shines _in_ their hearts for a season,
even during the day of man`'s visitation; which while it continueth to call,
invite and exhort, men are said to have it and may believe in it;
but when men refuse to believe in it, and reject it,
then it ceaseth to be a Light to show them the way,
but leaves the sense of their unfaithfulness as a sting in their conscience,
which is a terror and darkness unto them and upon
them in which they cannot know where to go,
neither can work any ways profitably in order to their salvation:
and therefore to such rebellious ones the "`day of the
Lord`" is said to be "`darkness and not light`" (Amos 5:18).

From whence it appears that though many receive not the Light (as the darkness comprehends
it not) nevertheless this saving Light shines __in all__ that it may save them.
Concerning which also Cyril of Alexandria saith well, and defends our principle:

"`With great diligence and watchfulness,
doth the apostle John endeavour to anticipate and prevent the vain thoughts of men;
for there is here a wonderful method of sublime things and overturning of objections,
he had just now called the Son the true Light,
by whom he affirmed that every man coming into the world was enlightened;
yea that he was in the world and the world was made by him.
One may then object,
if the Word of God be the Light and if this Light enlighten the hearts
of men and suggest unto men piety and the understanding of things;
if he was always in the world and was the creator or builder of the world,
why was he so long unknown unto the world?
It seems rather to follow because he was unknown to the world,
therefore the world was not enlightened by him, nor he totally Light.
Lest any should so object he divinely infers, '`and the world knew him not.`'
Let not the world accuse the Word of God, and his eternal Light,
but its own weakness: for the Son enlightens,
but the creature rejects the grace that is given unto it and abuseth the sharpness
of understanding granted it by which it might have naturally known God,
and as a prodigal hath turned its sight to the creatures, neglecting to go forward,
and through laziness and negligence buried the illumination and despised this grace.
Which, that the disciple of Paul might not do, he was commanded to watch;
therefore it is to be imputed to their wickedness who are illuminated,
and not unto the Light; for as, albeit the sun riseth upon all,
yet he that is blind receiveth no benefit thereby;
none thence can justly accuse the brightness of the sun,
but will ascribe the cause of not seeing to the blindness;
so I judge it is to be understood of the only begotten Son of God,
for he is the true Light and sendeth forth his brightness upon all;
but the god of this world, as Paul saith,
hath blinded the minds of those that believe not (2 Cor. 4:4),
that the Light of the Gospel shine not unto them.
We say then that darkness is come upon men not because
they are altogether deprived of Light;
for nature retaineth still the strength of understanding divinely given it,
but because man is dulled by an evil habit and become worse,
and hath made the measure of grace in some respect to languish.
When therefore the like befalls to man, the Psalmist justly prays,
crying '`Open mine eyes that I may behold the wonderful things of thy law.`'
For the law was given that this Light might be kindled in us,
the blearedness of the eyes of our minds being wiped away and the
blindness being removed which detained us in our former ignorance.
By these words, then, the world is accused as ungrateful and insensible,
not knowing its Author nor bringing forth the good fruit of the illumination;
that it may now seem to be said truly of all,
which was of old said by the prophet of the Jews,
I expected that it should have brought forth grapes, but it brought forth wild grapes.
For the good fruit of the illumination was the knowledge of the Only-Begotten,
as a cluster hanging from a fruitful branch, etc.`"^
footnote:[Upon John, _lib. 1, cap. 2._]

From which it appears, Cyril believed, that a saving illumination was given unto _all._
For, as to what he speaks of nature,
he understands it not of the common nature of man by itself,
but of that nature which hath the strength of understanding divinely given it:
for he understands this universal illumination to be of the same
kind with that grace of which Paul makes mention to Timothy,
saying, "`Neglect not the grace that is in thee.`" Now, it is not to be believed,
that Cyril was so ignorant, as to judge that grace to have been some natural gift.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXII.
That this saving Light and Seed, or a measure of it, is given to all,
Christ telleth expressly in the parable of the sower (Matt. 13 from v. 18; Mark 4,
and Luke 8:11),
he saith That this "`seed`" sown in those several sorts of grounds is the "`Word
of the Kingdom,`" which the apostle calls the Word of faith (Rom. 10:8,
// lint-disable invalid-characters
James 1:21), ὁ λόγοϛ ἓμϕυτοϛ, the "`implanted ingrafted Word, which is able to save the soul`";
the words themselves declare that it is that, which is saving, in the nature of it,
for in the good ground, it fructified abundantly.

Let us then observe that this Seed of the Kingdom, this saving, supernatural,
and sufficient Word was really sown in the stony, thorny ground and by the wayside,
where it did not profit but became useless as to these grounds.
It was, I say, the same Seed that was sown in the good ground.
It is then the fear of persecution and deceitfulness of riches (as Christ himself interpreteth
the parable) which hindereth this Seed to grow in the hearts of many.
Not but that in its own nature it is sufficient,
being the same with that which groweth up and prospereth
in the hearts of those who receive it.
So that though all are not saved by it,
yet there is a seed of salvation planted and sown in the hearts of all by God,
which would grow up and redeem the soul if it were not choked and hindered.
Concerning this parable Victor of Antioch (on the fourth chapter of Mark,
as he is cited by Voss in his [.book-title]#Pelagian History,# Book 7) saith,
"`That our Lord Christ hath liberally sown the divine Seed
of the Word and proposed it to all without respect of persons;
and as he that soweth distinguisheth not betwixt ground
and ground but simply casteth in the seed without distinction,
so our Saviour hath offered the food of the divine Word, so far as was his part,
although he was not ignorant what would become of many.
Lastly, he so behaved himself as he might justly say,
'`What should I have done that I have not done?`'`" And
to this answereth the parable of the talents (Matt. 25):
he that had two talents was accepted as well as he that
had five because he used them to his master`'s profit.
And he that had one might have done so: his talent was of the same nature with the rest,
it was as capable to have proportionably brought forth its interest as the rest.
And so though there be not a like proportion of grace given to all, to some five talents,
to some two talents and to some but one talent;
yet there is given to all that which is sufficient,
and no more is required than according to that which is given:
"`For unto whomsoever much is given, from him shall much be required`" (Luke 12:48);
he that had the two talents was accepted for giving four,
nothing less than he that gave the ten:
so should he also that gave the one if he had given two;
and no doubt one was capable to have produced two, as well as five to have produced ten,
or two four.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXIII.
Thirdly, this saving spiritual Light is the _Gospel,_
which the apostle saith expressly is preached "`in every creature under heaven`";
even that very "`Gospel whereof Paul was made a minister`" (Col.
1:23). For the Gospel is not a mere declaration of good things,
being the "`power of God unto salvation,
to all those that believe`" (Rom. 1:16). Though the outward
declaration of the Gospel be taken sometimes for the Gospel;
yet it is but figuratively and by a _metonymy._
For to speak properly,
the Gospel is this inward power and life which preacheth
glad tidings in the hearts of all men,
offering salvation unto them and seeking to redeem them from their iniquities,
and therefore it is said to be preached "`in every creature under heaven`":
whereas there are many thousands of men and women
to whom the outward gospel was never preached.
Therefore the apostle Paul (Rom. 1),
where he saith "`the Gospel is the power of God unto salvation,`" adds
that "`therein is revealed the righteousness of God from faith to faith`";
and also the "`wrath of God against such as hold the Truth of God in unrighteousness`":
for this reason (saith he) "`because that which may be known of God is manifest in them;
for God hath showed it unto them.`" Now that which
may be known of God is known by the Gospel,
which was manifest _in_ them.
For those of whom the apostle speaks had no outward gospel preached unto them;
so that it was by the inward manifestation of the knowledge of God _in_ them,
which is indeed the Gospel preached in man,
that "`the righteousness of God is revealed from faith to faith`"; that is,
it reveals to the soul that which is just, good, and righteous, and that,
as the soul receiveth it and believes,
righteousness comes more and more to be revealed from one degree of faith to another.
For though, as the following verse saith, the outward creation declares the power of God;
yet that which may be known of him is manifest within:
by which inward manifestation we are made capable to see and discern
the Eternal Power and Godhead in the outward creation;
so were it not for this inward principle we could no more understand the invisible
things of God by the outward visible creation than a blind man can see and discern
the variety of shapes and colors or judge of the beauty of the outward creation.
Therefore he saith, first,
"`That which may be known of God is manifest in them,`" and _in_ and _by_ that they may read
and understand the power and Godhead in those things that are outward and visible.
And though any might pretend that the outward creation doth, of itself,
without any supernatural or saving principle in the heart,
even declare to the natural man that there is a God;
yet what would such a knowledge avail if it did not
also communicate to me what the will of God is,
and how I shall do that which is acceptable to him?
For the outward creation,
though it may beget a persuasion that there is some eternal
power or virtue by which the world hath had its beginning;
yet it doth not tell me nor doth it inform me of that which is just, holy, and righteous,
how I shall be delivered from my temptations and evil affections and come unto righteousness:
that must be from some inward manifestation __in my heart.__
Whereas those Gentiles of whom the apostle speaks knew by that __inward law__ and manifestation
of the knowledge of God _in_ them to distinguish betwixt good and evil,
as in the next chapter appears, of which we shall speak hereafter.

The prophet Micah, speaking of man indefinitely or in general,
declares this (Mic. 6:8): "`He hath showed thee, O man, what is good.
And what doth the Lord require of thee but to do justly, and to love mercy,
and to walk humbly with thy God?`" He doth not say God requires
till he hath first assured that he hath showed unto them.
Now because this is showed unto _all_ men and manifest _in_ them, therefore,
saith the apostle,
is the "`wrath of God revealed against them for that they hold the Truth in unrighteousness`";
that is the measure of Truth, the Light, the Seed, the Grace in them:
for that they "`hide the talent in the earth,`" that
is in the earthly and unrighteous part in their hearts,
and suffer it not to bring forth fruit but to be
choked with the sensual cares of this life,
the fear of reproach, and the deceitfulness of riches,
as by the parables above mentioned doth appear.
But the apostle Paul opens and illustrates this matter yet more
(Rom. 10) where he declares that the Word which he preached (now
the Word which he preached and the Gospel which he preached,
and whereof he was a minster, is one and the same) "`is not far off,
but nigh in the heart and in the mouth`"; which done, he frameth, as it were,
the objection of our adversaries in the 14th and 15th verses:
"`How shall they believe in him of whom they have not heard?
And how shall they hear without a preacher?`" This he answers in the 18th verse, saying,
"`But, I say, have they not heard?
Yes verily, their sound went into all the earth,
and their words unto the ends of the world`";
insinuating that this divine preacher hath sounded in the ears and hearts of all men:
for of the outward apostles that saying was not true,
neither then nor many hundred years after;
yea for aught we know there may be yet great and spacious nations
and kingdoms who never have heard of Christ nor his apostles,
as outwardly.

This inward and powerful Word of God is yet more
fully described in the epistle to the Hebrews (chap.
4:12-13): "`For the Word of God is quick,^
footnote:[Later editors insert "`and powerful.`"]
and sharper than any two-edged sword,
piercing even to the dividing asunder of soul and spirit and of the joints and marrow,
and is a discerner of the thoughts and intents of the heart.`"
The virtues of this spiritual Word are here enumerated,
it is _quick,_ because it searches and tries the hearts of all:
no man`'s heart is exempt from it, for the apostle gives this reason of its being so,
in the following verse: "`But all things are naked and opened unto the eyes of him,
with whom we have to do: and there is not any creature,
that is not manifest in his sight.`" Though this ultimately
and mediately be referred to God,
yet nearly and immediately it relates to the _Word_ or _Light,_ which,
as hath been before proved, is __in the hearts of all,__
else it had been improper to have brought it in here.
The apostle shows how every intent and thought of
the heart is discerned by the Word of God,
because all things are naked before God, which imports nothing else,
but it is in and by this Word whereby God sees and discerns man`'s thoughts;
and so must needs be in all men, because the apostle saith,
"`there is no creature that is not manifest in his sight.`"
This then is that faithful witness and messenger of God,
that bears witness for God, and for his righteousness in the hearts of all men:
for "`he hath not left man without a witness`" (Acts 14:17),
and he is said to be "`given for a witness to the people`"
(Isa. 55:4). And as this Word beareth witness for God,
so it is not placed in men only to condemn them: for as he is given for a witness, so,
saith the prophet,
"`he is given for a leader and commander.`"
The Light is given that all through it may believe (John 1:7),
"`for faith cometh by hearing,
and hearing by the Word of God,`" which is placed in man`'s heart,
both to be a witness for God, and to be a means to bring man to God,
through faith and repentance: it is therefore _powerful,_
that it may divide betwixt the soul and the spirit.
It is like a two-edged sword, that it may cut off iniquity from him,
and separate betwixt the precious and the vile; and because man`'s heart is cold and hard,
like iron, naturally, therefore hath God placed this Word _in_ him,
which is said to be like a fire, and like a hammer, (Jer. 23:29), that,
like as by the heat of the fire the iron, of its own nature cold, is warmed,
and by the strength of the hammer is softened and
framed according to the mind of the worker;
so the cold and hard heart of man is,
by the virtue and powerfulness of this Word of God near and in the heart,
as it resists not, warmed and softened,
and receiveth a heavenly and celestial impression and image.
The most part of the fathers have spoken at large touching this Word, Seed, Light,
and saving voice calling all unto salvation, and able to save.

Clement of Alexandria saith [.book-title]#(lib.
2, Stromat.),# "`The divine Word hath cried, calling all,
knowing well those that will not obey.
And yet, because it is in our power either to obey or not to obey,
that none may have a pretext of ignorance it hath made a righteous call and requireth
but that which is according to the ability and strength of every one.`" The selfsame,
in his [.book-title]#Warning to the Gentiles:#
"`For as`" (saith he) "`that heavenly ambassador of the Lord,
the grace of God that brings salvation, hath appeared unto all, etc. This is the new song,
coming, and manifestation of the Word which now shows itself in us,
which was in the beginning and was first of all.`" And again, "`Hear, therefore,
ye that are afar off; hear ye who are near; the Word is hid from none,
the Light is common to all and shineth to all.
There is no darkness in the Word; let us hasten to salvation, to the new birth, that we,
being many, may be gathered unto the one alone love.`" Ibid.,
he saith that "`There is infused into all,
but principally into those that are trained up in doctrine, a certain divine influence,
// lint-disable invalid-characters
τίϛ ἀπόρροια θείκή.`"
And again he speaketh concerning "`the innate witness, worthy of belief,
which of itself doth plainly choose that which is most honest.`" And again he saith,
"`That it is not impossible to come unto the Truth and lay hold of it,
seeing it is most near to us, in our own houses, as the most wise Moses declareth,
living in three parts of us: viz., in our hands, in our mouth, and in our heart.
This,`" saith he, "`is a most true badge of the Truth,
which is also fulfilled in three things, namely in counsel, in action,
in speaking.`" And again he saith also unto the unbelieving nations, "`Receive Christ,
receive Light, receive sight to the end thou mayest rightly know both God and man.
The Word that hath enlightened us is more pleasant than gold,
and the stone of great value.`" And again he saith,
"`Let us receive the Light that we may receive God;
let us receive the Light that we may be the scholars of
the Lord.`" And again he saith to those infidel nations,
"`The heavenly Spirit helpeth thee; resist and flee pleasure.`"
Again [.book-title]#(lib. Strom. 5)# he saith,
"`God forbid that man be not a partaker of divine acquaintance,
// lint-disable invalid-characters
θείαϛ ἐννοίαϛ, who in Genesis is said to be a partaker of inspiration.`"
And [.book-title]#(Paed. lib,+++.+++ 1, cap. 3),# "`There is,`" saith he,
"`some lovely and some desirable thing in man which is called the in-breathing of God,
// lint-disable invalid-characters
ἐμϕύσηυα θεοῦ.`" The same man [.book-title]#(lib. Strom. 10)# directeth men unto
the _Light_ and _Water_ in themselves,
who have the eye of the soul darkened or dimmed through evil upbringing and learning:
let them enter in unto their own _domestic_ Light,
// lint-disable invalid-characters
or unto the Light which is _in_ their own house, πρόϛ τό οἰκεῖον ϕῶϛ βαδιζέτω,
unto the Truth which manifests accurately and clearly these things that have been written.

Justin Martyr, in his first apology, saith, "`that the Word which was and is, is in all;
even that very same Word which, through the prophets, foretold things to come.`"

The writer of the [.book-title]#Call of All Nations,# saith [.book-title]#(lib. i, cap. 2),#
"`We believe according to the same (viz. Scripture), and most religiously confess,
that God was never wanting in care to the generality of men;
who although he did lead by particular lessons,
a people gathered to himself unto godliness,
yet he withdrew from no nation of men the gifts of his own goodness,
that they might be convinced that they had received the words of the prophets,
and legal commands in services and testimonies of the first principles.`" [.book-title]#Cap.
7,# he saith,
"`That he believes that the help of grace hath been wholly withdrawn from no man.`" [.book-title]#Lib.
2, cap.#
l, "`Because, albeit salvation is far from sinners,
yet there is nothing void of the presence and virtue of his salvation.`" [.book-title]#Cap.
2,# "`But seeing none of that people over whom was set both the doctrines,
were justified but through Grace by the Spirit of faith, who can question, but that they,
who of whatsoever nation, in whatsoever times, could please God,
were ordered by the Spirit of the Grace of God:
which albeit in fore-time it was more sparing and hid, yet denied itself to no ages,
being in virtue one, in quantity different, in counsel unchangeable,
in operation multifarious.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXIV.
The third proposition which ought to be proved is, That it is by this Light,
Seed, or Grace that God works the salvation of all men,
and many come to partake of the benefit of Christ`'s death,
and salvation purchased by him.
By the inward and effectual operations of which,
as many heathens have come to be partakers of the promises
who were not of the seed of Abraham after the flesh,
so may some now,
to whom God hath rendered the knowledge of the history impossible,
come to be saved by Christ.
Having already proved that Christ hath died for all,
that there is a day of visitation given to all,
during which salvation is possible unto them,
and that God hath actually given a measure of saving Grace and Light unto all,
preached the Gospel to and in them, and placed the Word of faith in their hearts,
the matter of this proposition may seem to be proved.
Yet shall I a little,
for the further satisfaction of all who desire to
know the Truth and hold it as it is in Jesus,
prove this, from two or three clear Scripture testimonies, and remove the most common,
as well as the more strong, objections usually brought against it.

Our theme then hath two parts: First,
that those that have the Gospel and Christ outwardly preached unto them,
are not saved but by the working of the Grace and Light in their hearts.

Secondly, that by the working and operation of this, many have been,
and some may be saved, to whom the Gospel hath never been outwardly preached,
and who are utterly ignorant of the outward history of Christ.

As to the first, though it be granted by most,
yet because it is more in words than deeds (the more full discussing of
which will fall-in in the next Proposition concerning justification,
I shall prove it in few words.
And first from the words of Christ to Nicodemus (John 3:3), "`Verily,
verily I say unto thee, except a man be born again,
he cannot see the kingdom of God.`" Now this birth
cometh not by the outward preaching of the Gospel,
or knowledge of Christ, or historical faith in him;
seeing many have that and firmly believe it who are never thus renewed.
The apostle Paul also goes so far,
while he commends the necessity and excellence of this "`new creation,`" as,
in a certain respect,
to lay aside the outward knowledge of Christ or the knowledge of him after the flesh,
in these words (2 Cor. 5:16-17):
"`Wherefore henceforth know we no man after the flesh;
yea though we have known Christ after the flesh yet now henceforth know we him no more.
Therefore if any man be in Christ he is a new creature; old things are passed away,
behold all things are become new.`" Whence it manifestly appears that he makes the knowledge
of Christ after the flesh but as it were the rudiments which young children learn,
which after they are become better scholars are of less use to them because
they have and possess the very substance of those first precepts in their minds.
As all comparisons halt in some part so shall I not affirm this to hold in every respect;
yet so far will this hold that as those things that go no
farther than the rudiments are never to be accounted learned,
and as they grow beyond these things, so they have less use of them;
even so such as go no further than the outward knowledge
of Christ shall never inherit the kingdom of heaven.
But such as come to know this new birth, to be in Christ indeed, to be a new creature,
to have "`old things passed away and all things become
new,`" may safely say with the apostle,
"`Though we have known Christ after the flesh yet now henceforth know we him no more.`"
Now this new creature proceeds from the work of this Light and Grace in the heart.
It is that Word which we speak of that is sharp and piercing,
that _implanted_ Word able to save the soul, by which this birth is begotten;
and therefore Christ has purchased unto us this holy Seed,
that thereby this birth might be brought forth in us which is therefore also
called "`the manifestation of the Spirit given to every one to profit withal`";
for it is written that "`by one Spirit we are all baptized into
one body.`" And the apostle Peter also ascribeth this birth to the
Seed and Word of God which we have so much declared of,
saying (1 Pet. 1:23), "`Being born again,
not of corruptible seed but of incorruptible,
by the Word of God which liveth and abideth forever.`"
Though then this Seed be small in its appearance,
so that Christ compares it to a "`grain of mustard-seed,
which is the least of all seeds`" (Matt. 13:31-32),
and that it be hid in the earthly part of man`'s heart;
yet therein is life and salvation towards the sons of men wrapped up,
which comes to be revealed as they give way to it.
And in this Seed in the hearts of all men is the Kingdom of God,
as in capacity to be produced, or rather exhibited, according as it receives depth,
is nourished, and not choked:
hence Christ saith that the Kingdom of God was in the very Pharisees
(Luke 17:20-21) who did oppose and resist him and were justly
accounted as serpents and a generation of vipers.

Now the Kingdom of God could be no otherways in them than in a Seed,
even as the thirty-fold and the hundred-fold is wrapt
up in a small seed lying in a barren ground,
which springs not forth because it wants nourishment:
and as the whole body of a great tree is wrapped up potentially in the seed of the tree,
and so is brought forth in due season;
and as the capacity of a man or a woman is not only
in a child but even in the very _embryo,_
even so the Kingdom of Jesus Christ, yea Jesus Christ himself, "`Christ within,
who is the hope of glory,`" and becometh wisdom, righteousness,
sanctification and redemption, is in every man`'s and woman`'s heart,
in that little incorruptible Seed,
ready to be brought forth as it is cherished and received in the love of it.
For there can be no men worse than those rebellious and unbelieving Pharisees were;
and yet this Kingdom was thus _within_ them, and they were directed to look for it there:
so it is neither "`lo here`" nor "`lo there,`" in this or the other observation,
that this is known, but as this Seed of God in the heart is minded and entertained.
And certainly hence it is (even because this Light, Seed,
and Grace that appears in the heart of man is so little regarded and so
much overlooked) that so few know Christ brought forth in them.
The one sort, to wit the Calvinists,
they look upon grace as an irresistible power and therefore neglect and
despise this eternal Seed of the Kingdom in their hearts as a low,
insufficient, useless thing as to their salvation.
On the other hand the Papists, Arminians, and Socinians,
they go about to set up their natural power and will,
with one consent denying that this little Seed, this small appearance of the Light,
is that supernatural saving grace of God given to every man to save him.
And so upon them is verified that saying of the Lord Jesus Christ,
"`This is the condemnation of the world, that Light is come into the world,
but men love darkness rather than Light`"; the reason is added,
"`because their deeds are evil.`" All confess they feel this;
but they will not have it to be of that virtue.
Some will have it to be reason; some a natural conscience; some,
certain relics of God`'s image that remained in Adam.
So Christ,
as he met with opposition from all kinds of professors in his outward appearance,
so doth he now in his inward.
It was the meanness of his outward man that made many despise him, saying,
"`Is not this the son of the carpenter?
Are not his brethren and sisters among us?
Is not this a Galilean?
And came there ever a prophet out of Galilee?`" And suchlike reasonings.
For they expected an outward deliverer who, as a prince,
should deliver them with great ease from their outward enemies,
and not such a messiah as should be crucified shamefully
and as it were lead them into many sorrows,
troubles, and afflictions.
So the meanness of this appearance makes the crafty Jesuits,
the pretended rational Socinians, and the learned Arminians overlook it;
desiring rather something that they might exercise their subtlety, reason,
and learning about, and use the liberty of their own wills.
And the secure Calvinists, they would have a Christ to save them without any trouble;
to destroy all their enemies for them without them, and nothing or little within,
while they meanwhile be at ease to live in their sins secure.

Whence when all is well examined the cause is plain:
it is "`because their deeds are evil`" that with one consent they reject this Light;
for it checks the wisest of them all and the learnedest of them all in secret;
it reproves them;
neither can all their logic silence it nor can the securest among
them stop its voice from crying and reproving them within,
for all their confidence in the outward knowledge of Christ,
or of what he hath suffered outwardly for them.
For as hath been often said, in a day it strives with all, wrestles with all;
and it`'s the unmortified nature, the first nature, the old Adam, yet alive in the wisest,
in the learnedest, in the most zealous for the outward knowledge of Christ,
that denies this, that despises it, that shuts it out to their own condemnation.
They come all under this description:`" Every one that doth evil hateth the Light,
neither cometh to the Light,
lest his deeds should be reproved`" (John 3:20). So that it may be said now,
and we can say from a true and certain experience as it was said of old (Ps. 118:22;
Matt. 21:42; Mark 12:10; Luke 20:17; Acts 4:11),
"`The stone which the builders of all kinds have rejected,
the same is become unto us the head of the corner.`" Glory to God forever! who hath chosen
us a first-fruits to himself in this day wherein he is arisen to plead with the nations,
and therefore hath sent us forth to preach this everlasting Gospel unto all,
Christ nigh to all, the Light in all, the Seed sown in the hearts of all,
that men may come and apply their minds to it.
And we rejoice that we have been made to lay down our wisdom
and learning (such of us as have had some of it) and our carnal reasoning,
to learn of Jesus and sit down at the feet of Jesus in our hearts and hear him,
who there makes all things manifest and reproves all things by
his Light (Eph. 5:13). For many are wise and learned in the notion,
in the letter of the Scripture, as the Pharisees were,
and can speak much of Christ and plead strongly against infidels, Turks and Jews,
and it may be also against some heresies,
who in the meantime are crucifying Christ in the
small appearance of his Seed in their hearts.
Oh! better were it to be stripped and naked of all,
to account it as dross and dung, and become a fool for Christ`'s sake,
thus knowing him to teach thee in thy heart so as thou mayest witness him raised there,
feel the virtue of his cross there, and say with the apostle,
"`I glory in nothing save in the cross of Christ whereby I am crucified
to the world and the world unto me.`" This is better than to write
thousands of commentaries and to preach many sermons.
And it is thus to preach Christ and direct people to his pure Light in the heart that
God hath raised us up and for which the wise men of this world account us fools;
because by the operation of this cross of Christ _in_ our hearts we have denied
our own wisdom and wills in many things and have forsaken the vain worships,
fashions, and customs of this world.

For these divers centuries the world hath been full of a dry, fruitless,
and barren knowledge of Christ, feeding upon the husk and neglecting the kernel;
following after the shadow but strangers to the substance.
Hence the devil matters not how much of that knowledge abounds,
provided he can but possess the heart and rule in the will,
crucify the appearance of Christ there,
and so keep the Seed of the Kingdom from taking root.
For he has led them abroad, lo here and lo there,
and has made them wrestle in a false zeal, so much one against another,
contending for this outward observation and for the other outward observation,
seeking Christ in this and the other external thing, as in bread and wine;
contending one with another how he is there,
while some will have him to be present therein this way, and some the other way;
and some in Scriptures, in books, in societies and pilgrimages and merits.
But some confiding in an external barren faith think all is well
if they do but firmly believe that he died for their sins,
past, present, and to come,
while in the meantime Christ lies crucified and slain and is daily
resisted and gainsaid in his appearance in their hearts.
Thus, from a sense of this blindness and ignorance that is come over Christendom,
it is that we are led and moved of the Lord so constantly and frequently to call all,
invite all, request all to turn to the Light _in_ them, to mind the Light _in_ them,
to believe in Christ as he is _in_ them.
And that in the name, power, and authority of the Lord,
not in school arguments and distinctions (for which many of the wise men of this world
account us fools and madmen) we do charge and command them to lay aside their wisdom,
to come down out of that proud, airy brain-knowledge, and to stop that mouth,
how eloquent soever to the worldly ear it may appear,
and to be silent and sit down as in the dust,
and to mind the Light of Christ in their own consciences.
Which if minded they would find as a sharp two-edged sword in their hearts,
and as a fire and a hammer that would knock against and burn up all that carnal,
gathered, natural stuff,
and make the stoutest of them all tremble and become "`Quakers`" indeed;
which those that come not to feel now, and kiss not the Son while the day lasteth,
but harden their hearts, will feel to be a certain truth when it is too late.
To conclude, as saith the apostle,
"`All ought to examine themselves whether they be in the faith indeed;
and try their ownselves:
for except Jesus Christ be in them they are certainly reprobates`" (2 Cor. 13:5).

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXV.
Secondly, that which remains now to be proved is,
that by the operation of this Light and Seed some have been and may yet be saved,
to whom the Gospel is not outwardly preached, nor the history of Christ outwardly known.
To make this the easier, we have already shown how that Christ hath died for all men;
and consequently these are enlightened by Christ,
and have a measure of saving Light and Grace; yea, that the Gospel,
though not in any outward dispensation, is preached to them, and in them;
so that thereby they are stated in a possibility of salvation.
From which I may thus argue:

[.offset]
_Argument:_

[.syllogism]
* To whom the Gospel, the power of God unto salvation, is manifest, they may be saved, whatever outward knowledge they want:
* But this Gospel is preached _in_ every creature; in which is certainly comprehended many that have not the outward knowledge:
* Therefore of those, many may be saved.

But to those arguments by which it hath been proved
that all men have a measure of saving grace,
I shall add one, and that very observable, not yet mentioned, viz,
that excellent saying of the apostle Paul to Titus (2:11),
"`The grace of God that brings salvation hath appeared to all men;
teaching us that denying ungodliness and worldly lusts, we should live soberly,
righteously,
and godly in this present world.`" Than which there can be nothing more clear,
it comprehending both the parts of the controversy.
First, it testifies that it is no natural principle or light, but saith plainly,
"`it brings salvation.`" Secondly, it says not that it hath appeared to a few,
but unto _all_ men.
The fruit of it declares also how efficacious it is,
seeing it comprehends the whole duty of man.
It both teacheth us first to forsake evil, to deny ungodliness and worldly lusts;
and then it teacheth us our whole duty.
First, to live _soberly,_ that comprehends temperance, chastity, meekness,
and those things that relate unto a man`'s self.
Secondly, _righteously,_ that comprehends equity, justice, and honesty,
and those things which relate to our neighbours.
And lastly, _godly;_ which comprehends piety, faithfulness, and devotion,
which are the duties relating to God.
So then there is nothing required of man or is needful
to man which this grace teacheth not.
Yet I have heard a public preacher, one of those that are accounted zealous men,
to evite the strength of this text, deny this grace to be saving,
and say it was only intended of common favours and graces such
as is the heat of the fire and outward light of the sun.
Such is the darkness and ignorance of those that oppose the Truth,
whereas the text saith expressly that it is _saving._
Others, that cannot deny but it is saving,
allege this "`all`" comprehends not every individual but only all kinds.
But is a bare negation sufficient to overturn the strength of a positive assertion?
If the Scriptures may be so abused, what so absurd as may not be pleaded for from them?
or what so manifest as may not be denied?
But we have not reason to be staggered by their denying so long
as our faith is found in express terms of the Scripture;
they may as well seek to persuade us that we do not intend that which we affirm,
though we know the contrary,
as make us believe that when the apostle speaks forth
our doctrine in plain words yet he intends theirs,
which is quite the contrary, and indeed, can there be anything more absurd than to say,
where the word is plainly "`all,`" few is only intended.
For they will not have "`all`" taken here for the greater number.
Indeed, as the case may be sometimes,
by a figure "`all`" may be taken of two numbers for the greater number;
but let them show us, if they can, either in Scripture,
or profane or ecclesiastical writings,
that any man that wrote sense did ever use the word "`all`" to express, of two numbers,
the lesser.
Whereas they affirm that the far lesser number have received saving grace;
and yet will they have the apostle, by "`all,`" to have signified so.
Though this might suffice, yet to put it further beyond all question,
I shall instance another saying of the same apostle that we
may use him as his own commentator (Rom. 5:18):
"`Therefore as by the offence of one judgment came upon all men to condemnation,
even so by the righteousness of one the free gift came upon
all men unto justification of life.`" Here no man of reason,
except he will be obstinately ignorant,
will deny but this similitive particle "`as`" makes
the "`all,`" which goes before and comes after,
to be of one and the same extent.
Or else let them show one example, either in Scripture or elsewhere,
among men that speak proper language, where it is otherwise.
We must then either affirm that this loss which leads
to condemnation hath not come upon all;
or say that this free gift is come upon all by Christ.
Whence I thus argue, First,

[.offset]
_Argument:_

[.syllogism]
* If _all_ men have received a loss from Adam, which leads to condemnation; then _all_ men have received a gift from Christ, which leads to justification:
* But the first is true;
* Therefore also the last.

From all which it naturally follows that all men, even the heathen, may be saved:
for Christ was given as a "`Light to enlighten the Gentiles`" (Isa. 49:6).
Now to say that though they might have been saved yet none were,
is to judge too uncharitably.
I see not what reason can be alleged for it; yea, though it were granted,
which never can be, that none of the heathen were saved,
it will not from thence follow that they could not have been saved;
or that none now in their condition can be saved.
For, __A non esse ad non posse non datur sequela,__ i.e.,
That consequence is false that concludes a thing cannot be because it is not.

[.offset]
_Objection:_

[.syllogism]
* But if it be objected, which is the great objection, that "`there is no name under heaven, by which salvation is known, but by the name Jesus.`"
* Therefore they (not knowing this) cannot be saved.

_Answ._
I answer: though they know it not outwardly,
yet if they know it inwardly by feeling the virtue and power of it,
the Name "`Jesus`" indeed (which signifies a Saviour)
to free them from sin and iniquity in their hearts,
they are saved by it.
I confess there is no other name to be saved by:
but salvation lieth not in the literal but in the experimental knowledge;
albeit those that have the literal knowledge are
not saved by it without this real experimental knowledge.
Yet those that have the real knowledge may be saved without the external,
as by the arguments hereafter brought will more appear.
For if the outward distinct knowledge of him by whose means I receive
benefit were necessary for me before I could reap any fruit of it,
then by the rule of contraries it would follow that I could receive no hurt without
I had also the distinct knowledge of him that occasioned it;
whereas experience proves the contrary.
How many are injured by Adam`'s fall that know nothing
of there ever being such a man in the world?
or of his eating the forbidden fruit?
Why may they not then be saved by the gift and grace of Christ _in_ them,
making them righteous and holy,
though they know not distinctly how that was purchased unto them
by the death and sufferings of Jesus that was crucified at Jerusalem;
especially seeing God hath made that knowledge simply impossible to them?
As many men are killed by poison infused into their meat,
though they neither know what the poison was nor who infused it;
so also on the other hand how many are cured of their diseases
by good remedies who know not how the medicine is prepared,
what the ingredients are, nor oftentimes who made it?
The like may also hold in spiritual things, as we shall hereafter prove.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXVI.
First, If there were such an absolute necessity for this outward knowledge,
that it were even of the essentials of salvation, then none could be saved without it;
whereas our adversaries deny not, but readily confess,
that many infants and deaf persons are saved without it.
So that here they break that general rule, and make salvation possible without it.
Neither can they allege that it is because such are free from sin;
seeing they also affirm, that all infants, because of Adam`'s sin,
deserve eternal condemnation, as being really guilty in the sight of God;
and of deaf people, it is not to be doubted,
and experience shows us that they are subject to
many common iniquities as well as other men.

_Obj._
If it be said, that these children are the children of believing parents:

_Answ._
What then?
They will not say that they transmit grace to their children.
Do they not affirm, that the children of believing parents are guilty of original sin,
and deserve death as well as others?
How prove they that makes up the loss of all explicit knowledge?

_Obj._
If they say, deaf people may be made sensible of the Gospel by signs:

_Answ._
All the signs cannot give them any explicit knowledge of the history of the death,
sufferings, and resurrection of Christ.
For what signs can inform a deaf man that the son of God took on him man`'s nature,
was born of a virgin, and suffered under Pontius Pilate?

_Obj._
And if they should further allege, that they are within the bosom of the visible church,
and partakers of the sacraments:

_Answ._
All that gives no certainty of salvation;
for (as the Protestants confess) they confer not grace __ex opere operato.__
And will not they acknowledge that many are in the bosom of the church,
who are visibly no members of it?
But if this charity be extended towards such, who are where the Gospel is preached,
so that they may be judged capable of salvation,
because they are under a simple impossibility of distinctly knowing the means of salvation,
what reason can be alleged why the like charity may
not be had to such as though they can hear,
yet are under a simple impossibility of hearing, because it is not spoken unto them?
Is not a man in China, or in India,
as much to be excused for not knowing a thing which he never heard of,
as a deaf man here, who cannot hear?
For as the deaf man is not to be blamed,
because God hath been pleased to suffer him to be under this infirmity;
so is the Chinese or the Indian as excusable,
because God hath withheld from him the opportunity of hearing.
He, that cannot hear a thing, as being necessarily absent, and he that cannot hear it,
as being naturally deaf, are to be placed in the same category.

Secondly, This manifestly appears by that saying of Peter (Acts 10:34-35):
"`Of a truth I perceive that God is no respecter of persons: but in every nation,
he that feareth him and worketh righteousness,
is accepted of him.`" Peter was before liable to that
mistake that the rest of the Jews were in;
judging that all were unclean except themselves, and that no man could be saved,
except they were proselyted to their religion, and circumcised.
But God showed Peter other ways in a vision,
and taught him to call nothing common or unclean; and therefore,
seeing that God regarded the prayers of Cornelius, who was a stranger to the law,
and to Jesus Christ, as to the outward, yet Peter saw that God had accepted him.
And he is said to fear God, before he had this outward knowledge,
therefore Peter concludes that everyone that in every nation, without respect of persons,
feareth God and worketh righteousness, is accepted of him.
So he makes the fear of God and the working of righteousness,
and not an outward historical knowledge, the qualification: they then that have this,
wherever they be, they are saved.
Now we have already proved, that to every man that grace is given,
whereby he may live godly and righteously;
and we see that by this grace Cornelius did so, and was accepted,
and his prayers came up for a memorial before God, before he had this outward knowledge.
Also, was not Job "`a perfect and upright man, that feared God,
and eschewed evil?`" Who taught Job this?
How knew Job Adam`'s fall?
And from what scripture learned he that excellent knowledge he had and that faith,
by which he knew his Redeemer lived?
For many make him as old as Moses, was not this by an inward grace in the heart?
Was it not that inward grace that taught Job to eschew evil, and to fear God?
And was it not by the workings thereof that he became a just and upright man?
How doth he reprove the wickedness of men (chap.
24)! And after he hath numbered up their wickedness, doth he not condemn them (v. 13),
for "`rebelling against this Light,`" for not knowing the way thereof,
nor abiding in the paths thereof?
It appears then Job believed that men had a Light,
and that because they rebelled against it, therefore they knew not its ways,
and abode not in its paths, even as the Pharisees, who had the Scriptures,
are said to err, not knowing the Scriptures.
And also Job`'s friends, though in some things wrong;
yet who taught them all those excellent sayings and knowledge which they had?
Did not God give it them, in order to save them, or was it merely to condemn them?
Who taught Elihu that "`the inspiration of the Almighty giveth understanding;
that the Spirit of God made him,
and the breath of the Almighty gave him life?`" And
did not the Lord accept a sacrifice for them?
And who dare say that they are damned?
But further, the apostle puts this controversy out of doubt, for,
if we may believe his plain assertions, he tells us (Rom. 2),
"`that the heathen did the things contained in the
law.`" From whence I thus argue:

[.offset]
_Argument:_

[.syllogism]
* In every nation, he that feareth God and worketh righteousness is accepted:
* But many of the heathen feared God and wrought righteousness:
* Therefore they were accepted.

[.offset]
The minor is proved from the example of Cornelius; but I shall further prove it thus:

[.syllogism]
* He that doth the things contained in the Law feareth God and worketh righteousness;
* But the heathen did the things contained in the Law:
* Therefore they feared God, and wrought righteousness.

Can there be anything more clear?
For if to do the things contained in the Law, be not to fear God and work righteousness,
then what can be said to do so, seeing the apostle calls the Law spiritual, holy, just,
and good?
But this appears manifestly by another medium,
taken out of the same chapter (v. 13). So that nothing can be more clear; the words are,
"`The doers of the Law shall be justified.`" From which I thus argue,
without adding any word of my own:

[.syllogism]
* The doers of the Law shall be justified:
* But the Gentiles do the things contained in the Law:

All that know but a conclusion do easily see
what follows from these express words of the apostle.
And indeed he, through that whole chapter,
labours as if he were contending now with our adversaries,
to confirm this doctrine (vv. 9-11),
"`Tribulation and anguish upon every soul of man that doth evil, to the Jew first,
and also to the Gentile.
For there is no respect of persons with God.`" Where the apostle clearly homologates^
footnote:[_homologate_ +++=+++ approve]
the sentence of Peter, before mentioned, and shows that Jew and Gentile,
or as he himself explains in the following verses,
both they that have an outward law and they that have none,
when they do good shall be justified.
And to put us out of doubt, in the very following verses he tells,
that "`the doers of the law are justified`";
and that the "`Gentiles did the law.`" So that except we think he spake not what he intended,
we may safely conclude that such Gentiles were justified, and did partake of that "`honor,
glory and peace, which comes upon every one that doth good`":
even the Gentiles that are without the law, when they work good,
seeing with God there is no respect of persons;
so as we see that it is not the having the outward knowledge that doth save,
without the inward; so neither doth the want of it,
to such to whom God hath made it impossible, who have the inward, bring condemnation.
And many that have wanted the outward have had a knowledge of this inwardly,
by virtue of that inward Grace and Light, given to every man, working in them,
by which they forsook iniquity and became just and holy, as is above proved; who,
though they knew not the history of Adam`'s fall,
yet were sensible in themselves of the loss that came by it,
feeling their inclinations to sin and the body of sin in them:
and though they knew not the coming of Christ,
yet were sensible of that inward power and salvation which came by him,
even before as well as since his appearance in the flesh.
For I question whether these men can prove that all the patriarchs and fathers
before Moses had a distinct knowledge either of the one or the other,
or that they knew the history of the tree of knowledge of good and evil,
and of Adam`'s eating the forbidden fruit;
far less that Christ should be born of a virgin, should be crucified,
and treated in the manner he was.
For it is justly to be believed that, what Moses wrote of Adam, and of the first times,
was not by tradition but by revelation; yea,
we see that not only after the writing of Moses, but even of David and all the prophets,
who prophesied so much of Christ, how little the Jews,
that were expecting and wishing for the Messiah, could thereby discern him when he came,
that they crucified him as a blasphemer, not as the Messiah,
by mistaking the prophesies concerning him; for Peter saith expressly (Acts 3:17),
to the Jews,
that both "`they and their rulers did it through ignorance.`"
And Paul saith (1 Cor. 2:8),
that "`had they known it, they would not have crucified the Lord of Glory.`" Yea,
Mary herself, to whom the angel had spoken,
and who had laid up all the miraculous things accompanying his birth, in her heart,
she did not understand how,
when he "`disputed with the doctors in the temple,`" that he was "`about
his father`'s business.`" And the apostles that had believed him,
conversed daily with him, and saw his miracles, could not understand,
neither believe those things, which related to his death, sufferings, and resurrection,
but were, in a certain respect, stumbled at them.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXVII.
So, we see how that it is the inward work,
and not the outward history and Scripture, that gives the true knowledge;
and by this inward Light many of the heathen philosophers
were sensible of the loss received by Adam,
though they knew not the outward history; hence Plato asserted,
That "`man`'s soul was fallen into a dark cave,
where it only conversed with shadows.`" Pythagoras saith,
"`Man wandereth in this world as a stranger,
banished from the presence of God.`" And Plotinus compareth "`man`'s soul, fallen from God,
to a cinder, or dead coal,
out of which the fire is extinguished.`" Some of them said
that "`the wings of the soul were clipped or fallen off,
so that they could not flee unto God.`" All which,
and many more such expressions that might be gathered out of their writings,
show that they were not without a sense of this loss.
Also they had a knowledge and discovery of Jesus Christ inwardly, as a remedy _in_ them,
to deliver them, from that evil seed, and the evil inclinations of their own hearts,
though not under that particular denomination.

Some called him a Holy Spirit, as Seneca [.book-title]#(Epist.
41),# who said,
"`There is a Holy Spirit in us that treateth us as we treat him.`"
Cicero calleth it an "`innate light,`" in his book [.book-title]#De Republica,#
cited by Lactantius [.book-title]#(6 Instit.),#^
footnote:[_In Sect. 8._]
where he calls this "`right reason, given unto all, constant and eternal,
calling unto duty by commanding, and deterring from deceit by forbidding.`" Adding,
"`that it cannot be abrogated, neither can any be freed from it,
neither by senate nor people; that it is one eternal and the same always to all nations;
so that there is not one at Rome and another at Athens:
Whoso obeys it not must flee from himself,
and in this is greatly tormented although he should escape
all other punishment.`" Plotinus also calls him Light,
saying that "`as the sun cannot be known but by its own light,
so God cannot be known but with his own Light:
and as the eye cannot see the sun but by receiving its image,
so man cannot know God but by receiving his image;
and that it behooveth man to come to purity of heart before he could know God`";
calling him also "`Wisdom,`" a name frequently given
him in Scripture (see Prov. 1:20 to the end;
and Prov. 8:9-34, where Wisdom is said to cry, entreat,
and invite all to come unto her and learn of her).
And what is this Wisdom, but Christ?
Hence such as came, among the heathen, to forsake evil and cleave to righteousness,
were called "`philosophers,`" that is, lovers of wisdom.
They knew this wisdom was nigh unto them,
and that "`the best knowledge of God and divine mysteries was by
the inspiration of the wisdom of God.`" Phocylides affirmed,
that "`the word of the wisdom of God was the best.`" His words in the Greek are,
// lint-disable invalid-characters
Τῆϛ δὲ Θεοπνεύστηϛ σοϕίαϛ λόγοϛ ἐστὶν ἄριστοϛ.

And much more of this kind might be instanced, by which it appears they knew _Christ,_
and by his working in them were brought from unrighteousness to righteousness,
and to love that power by which they felt themselves redeemed; so that,
as saith the apostle,
"`They show the work of the law written in their hearts,`"
and "`did the things contained in the law`";
and therefore, as all doers of the law are, were no doubt justified,
and saved thus by the power of Christ in them.
And, as this was the judgment of the apostle, so was it of the primitive Christians.
Hence Justin Martyr stuck not to call Socrates a Christian,
saying that "`all such as lived according to the divine Word in them,
which was in all men, were Christians, such as Socrates and Heraclitus,
and others among the Greeks,`" etc. "`That such as live with the Word,
are Christians without fear or anxiety.`"

Clement of Alexandria saith [.book-title]#(Apol. ii., Strom. lib. i.),#
that "`this wisdom or philosophy was necessary to the Gentiles,
and was their schoolmaster to lead them unto Christ,
by which of old the Greeks were justified.`"

"`Nor do I think,`" saith Augustine, in his book of the [.book-title]#City of God, lib. 18, cap. 47,#
"`that the Jews dare affirm that none belonged unto God
but the Israelites.`" Upon which place Ludovicus Vives saith,
that "`thus the Gentiles, not having a law, were a law unto themselves;
and the light of so living is the gift of God, and proceeds from the Son;
of whom it is written that he enlighteneth every man that cometh into the world.`"

Augustine also testifies in his [.book-title]#Confessions (lib.
7, cap. 9),# that "`he had read in the writings of the Platonists,
though not in the very same words,
yet that which by many and multiplied reasons did persuade,
that '`in the beginning was the Word, and the Word was with God,
this was in the beginning with God, by which all things were made,
and without which nothing was made that was made: in him was Life,
and the Life was the Light of men: and the Light shined in the darkness,
and the darkness did not comprehend it.
And, albeit the soul gives testimony concerning the Light, yet it is not the Light,
but the Word of God; for God is the true Light,
which enlighteneth every man that cometh into the world`'"`;
and so repeats to verse 14 of John 1, adding, "`These things have I there read.`"

Yea, there is a book translated out of the Arabic,
which gives an account of one Hai Eben Yokdan, who, without converse of man,
living in an island alone, attained to such a profound knowledge of God,
as to have immediate converse with him, and to affirm,
"`That the best and most certain knowledge of God,
is not that which is attained by premises premised, and conclusions deduced,
but that which is enjoyed by conjunction of the mind of man with the supreme intellect,
after the mind is purified from its corruptions, and is separated from all bodily images,
and is gathered into a profound stillness!"`^
footnote:[This paragraph is omitted from some later editions.]

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXVIII.
Seeing then it is by this inward Gift, Grace, and Light, that both those,
that have the Gospel preached unto them, come to have Jesus brought forth in them,
and to have the saving and sanctified use of all outward helps and advantages;
and also by this same Light, that all may come to be saved; and that God calls, invites,
and strives with all, in a day, and saveth many,
to whom he hath not seen meet to convey this outward knowledge; therefore we,
having the experience of the inward and powerful work of this Light in our hearts,
even _Jesus_ revealed in us, cannot cease to proclaim the day of the Lord,
that it is arisen in it, crying out with the woman of Samaria; "`Come and see one,
that hath told me all that ever I have done:
Is not this the Christ?`" That others may come and feel the same in themselves,
and may know, that little small thing that reproves them in their hearts,
however they have despised it and neglected it,
is nothing less than the Gospel preached _in_ them; "`Christ,
the wisdom and power of God,`" being in and by that Seed seeking to save their souls.

Of this Light therefore Augustine speaks in his [.book-title]#Confessions (lib.
11, cap. 9):# "`In this beginning, O God! thou madest the heavens and the earth, in thy Word,
in thy Son, in thy virtue, in thy wisdom, wonderfully saying, and wonderfully doing.
Who shall comprehend it?
Who shall declare it?
What is that which shineth in unto me, and smites my heart without hurt,
at which I both tremble, and am inflamed?
I tremble, in so far as I am unlike unto it;
and I am inflamed in so far as I am like unto it?
It is Wisdom, which shineth in unto me and dispelleth my cloud,
which had again covered me, after I was departed from that darkness and rampier^
footnote:[Later editors substitute "`heap`" for "`rampier.`"]
of my punishments.`" And again he saith [.book-title]#(lib.
x., cap.
27),# "`It is too late that I have loved thee, O thou beautifulness, so ancient,
and so new, late have I loved thee, and behold thou wast within, and I was without,
and there was seeking thee! thou didst call, thou didst cry,
thou didst break my deafness, thou glancedst, thou didst shine,
thou chasedst away my darkness.`"

Of this also our countryman, George Buchanan, speaketh thus in his book, [.book-title]#De Jure Regni apud Scotos:#
"`Truly I understand no other thing at present,
than that Light, which is divinely infused into our souls; for when God formed man,
he not only gave him eyes to his body,
by which he might shun those things that are hurtful to him,
and follow those things that are profitable.
But also hath set before his mind, as it were, a certain Light,
by which he may discern things that are vile from things that are honest.
Some call this power nature, others the law of nature; I truly judge it to be divine,
and am persuaded that nature and wisdom never say different things.
Moreover God hath given us a compend of the law,
which in few words comprehends the whole: to wit,
that we should love him from our hearts, and our neighbours as ourselves.
And of this law all the books of the Holy Scriptures,
which pertain to the forming of manners, contain no other but an explication.`"

This is that universal,
evangelical principle in and by which this salvation of Christ is exhibited to all men,
both Jew and Gentile, Scythian and Barbarian, of whatsoever country or kindred he be.
And therefore God hath raised up unto himself, in this our age,
faithful witnesses and evangelists to preach again his everlasting Gospel,
and to direct all, as well the high professors, who boast of the Law,
and the Scriptures, and the outward knowledge of Christ,
as the infidels and heathens that know not him that way,
that they may all come to mind the Light in them, and know Christ in them,
// lint-disable invalid-characters
"`the Just One +++[+++τὸν Δίκαιον], whom they have so long killed and made merry over,
and he hath not resisted`" (James 5:6), and give up their sins, iniquities, false faith,
professions, and outside righteousness,
to be crucified by the power of his cross in them,
so as they may know Christ within to be the "`hope of glory,`"
and may come to walk in his Light and be saved,
who is that "`true Light that enlighteneth every man that cometh into the world.`"
