== THE SEVENTH PROPOSITION

[.chapter-subtitle--blurb]
Concerning Justification

[.heading-continuation-blurb]
As many as resist not this Light, but receive the same, it becomes in them a holy, pure,
and spiritual birth, bringing forth holiness, righteousness, purity,
and all those other blessed fruits, which are acceptable to God, by which holy birth,
to wit, __Jesus Christ formed within us,__ and working his works _in_ us, as we are sanctified,
so are we justified in the sight of God, according to the apostle`'s words:
"`But ye are washed, but ye are sanctified,
but ye are justified in the name of the Lord Jesus,
and by the Spirit of our God`" (1 Cor. 6:11).
Therefore it is not by our works wrought in our will,
nor yet by good works, considered as of themselves; but by _Christ,_
who is both the _gift_ and the _giver,_ and the cause producing the effects _in_ us,
who, as he hath reconciled us while we were enemies, doth also in his wisdom save us,
and justify us after this manner, as saith the same apostle elsewhere,
"`According to his mercy he saved us, by the washing of regeneration,
and the renewing of the Holy Ghost`" (Tit. 3:5).

// lint-disable invalid-characters "§"
§I. The doctrine of justification comes well in
order after the discussing of the extent of Christ`'s death,
and of the grace thereby communicated;
some of the sharpest contests concerning this having from thence their rise.
Many are the disputes, among those called Christians, concerning this point; and indeed,
if all were truly minding that which justifieth,
there would be less noise about the notions of justification.
I shall briefly review this controversy, as it stands among others,
and as I have often seriously observed it; then in short state the controversy as to us,
and open our sense and judgment of it;
and lastly prove it (if the Lord will) by some Scripture testimonies,
and the certain experience of all, ever were truly justified.

[.small-break]
'''

// lint-disable invalid-characters "§"
§II. That this doctrine of _justification_ hath been and
is greatly vitiated in the church of Rome is not by us questioned,
though our adversaries, who for want of better arguments do often make lies their refuge,
have not spared in this respect to stigmatize us with Popery,
but how untruly will hereafter appear.
For to speak little of their __meritum ex condigno,__
which was no doubt a very common doctrine of the Romish church, especially before Luther,
though most of their modern writers, especially in their controversies with Protestants,
do partly deny it, partly qualify it,
and seem to state the matter only as if they were propagators
and pleaders for good works by the others denied.
Yet if we look to the effects of this doctrine among them
as they appear in the generality of their church members,
not in things disapproved but highly approved and
commended by their father the Pope and all his clients,
as the most beneficial casualty of all his revenue,
we shall find that Luther did not without great ground
oppose himself to them in this matter,
and if he had not run himself into another extreme (of which
hereafter) his work would have stood the better.
For in this, as in most other things,
he is more to be commended for what he pulled down
of Babylon than for what he built of his own.
Whatever then the Papists may pretend,
or even some good men among them may have thought, experience showeth,
and it is more than manifest by the universal and approved practice of their people,
that they place not their justification so much in works that are truly and morally good,
and in the being truly renewed and sanctified in the mind,
as in such things as are either nor good nor evil, or may truly be called evil,
and can no otherways be reckoned good than because the Pope pleases to call them so.
So that if the matter be well sifted it will be found that the greatest part of their
justification depends upon the authority of his bulls and not upon the power,
virtue and grace of Christ revealed in the heart, and renewing of it.
As will appear, first, from their principle concerning their sacraments,
which they say confer grace __ex opere operato.__
So that if a man partake but of them,
he thereby obtains remission of sin though he remain as he was;
the virtue of the sacraments making up the want that is in the man.
So that this act of submission and faith to the laws of the church,
and not any real inward change, is that which justifieth him.
As for example, if a man make use of the sacrament (as they call it) of penance,
so as to tell over his sins to a priest, though he have not true contrition,
which the Lord hath made absolutely necessary for penitent sinners, but only attrition,
a figment of their own; that is,
if he be sorry he hath sinned not out of any love to God or his
law which he hath transgressed but for fear of punishment,
yet doth the virtue of the sacrament (as they affirm) procure to him remission of sins;
so that being absolved by the priest he stands accepted
and justified in the sight of God.
This man`'s justification then proceedeth not from his being truly penitent and in any
measure inwardly changed and renewed by the working of God`'s grace in his heart,
but merely from the authority of the priest and virtue of the sacrament,
who hath pronounced him absolved; so that his justification is from somewhat without him,
and not within him.

Secondly, this will yet more appear in the matter of indulgences,
where remission of all sins, not only past but for years to come,
is annexed to the visiting such and such churches and relics,
saying such and such prayers;
so that the person that so doth is presently cleared from the guilt
of his sin and justified and accepted in the sight of God.
As for example:
he that in the great Jubilee will go to Rome and present himself
before the gate of Peter and Paul and there receive the Pope`'s blessing;
or he that will go a pilgrimage to James`'s sepulchre in Spain, or to Mary of Loretto,
is upon the performance of those things promised forgiveness of sins.
Now if we ask them the reason,
how such things as are not morally good in themselves come to have virtue,
they have no other answer but "`because of the church and Pope`'s
authority,`" who being the great treasurer of the magazine of Christ`'s
merits lets them out upon such and such conditions.
Thus also the invention of saying Mass is made a chief instrument of justification;
for in it they pretend to offer Christ daily to the Father,
a propitiatory sacrifice for the sins of the living and the dead: so that a man,
for money, can procure Christ thus to be offered for him when he pleases,
by which offering he is said to obtain remission of sins,
and to stand justified in the sight of God.
From all which, and much more of this nature which might be mentioned,
it doth appear that the Papists place their justification not so
much in any work of holiness really brought forth in them,
and real forsaking of iniquity,
as in the mere performance of some ceremonies and a blind
belief which their teachers have begotten in them,
that the church and the Pope having the absolute dispensation of the merits of Christ,
have power to make these merits effectual for the remission of
sins and justification of such as will perform these ceremonies.
This is the true and real method of justification
taken by the generality of the church of Rome,
and highly commended by their public preachers, especially the monks,
in their sermons to the people, of which I myself have been an ear- and an eye-witness.
However some of their modern writers have laboured to qualify it in their controversies.
This doctrine Luther and the Protestants then had good room to deny and oppose;
though many of them ran into another extreme,
so as to deny good works to be necessary to justification and to preach
up not only remission of sins but justification by faith alone,
without all works, however good.
So that men do not obtain their justification according
as they are inwardly sanctified and renewed,
but are justified merely by believing that Christ died for them;
and so some may perfectly be justified though they be lying in gross wickedness,
as appears by the example of David,
who they say was fully and perfectly justified,
while he was lying in the gross sins of murder and adultery.
As then the Protestants have sufficient ground to quarrel and confute
the Papists concerning those many abuses in the matter of justification,
showing how the doctrine of Christ is thereby vitiated and overturned
and the Word of God made void by many and useless traditions,
the law of God neglected while foolish and needless ceremonies are prized and followed,
through a false opinion of being justified by the performance of them;
and the merits and sufferings of Christ (which is the only sacrifice appointed
of God for remission of sins) derogated from by the setting up of a __daily sacrifice,__
never appointed by God, and chiefly devised out of covetousness to get money by;
so the Protestants, on the other hand,
by not rightly establishing and holding forth the doctrine of justification
according as it is delivered in the Holy Scriptures,
have opened a door for the Papists to accuse them
as if they were neglecters of good works,
enemies to mortification and holiness,
such as esteem themselves justified while lying in great sins:
by which kind of accusations (for which too great ground hath been
given out of the writings of some rigid Protestants) the reformation
hath been greatly defamed and hindered and the souls of many ensnared.
Whereas, who will narrowly look into the matter may observe
these debates to be more in specie than __in genere,__
seeing both do upon the matter land in one; and like two men in a circle, who,
though they go sundry ways, yet meet at last in the same centre.

For the Papists, they say they obtain remission of sins,
and are justified by the merits of Christ,
as the same are applied unto them in the use of the sacraments of the church,
and are dispensed in the performance of such and such ceremonies, pilgrimages, prayers,
and performances, though there be not any inward renewing of the mind,
nor knowing of Christ inwardly formed;
yet they are remitted and made righteous __ex opere operato,__
because of the power and authority accompanying the
sacraments and the dispensers of them.

The Protestants say that they obtain remission of sins,
and stand justified in the sight of God by virtue of the merits and sufferings of Christ,
not by infusing righteousness into them, but by pardoning their sins,
and by accounting and accepting their persons as righteous: they resting on him,
and his righteousness by faith; which faith, the act of believing,
is not imputed unto them for righteousness.^
footnote:[So saith the [.book-title]#Westminster Confession of Faith,# chap.
11, sect.
1.]

So the justification of neither here is placed in any inward renewing of the mind,
or by virtue of any spiritual birth or formation of Christ _in_ them;
but only by a bare application of the death and sufferings
of Christ outwardly performed for them:
whereof the one lays hold on a faith resting upon them,
and hoping to be justified by them alone;
the other by the saying of some outward prayers and ceremonies,
which they judge makes the death of Christ effectual unto them.
I except here (being unwilling to wrong any) what things
have been said as to the necessity of inward holiness,
either by some modern Papists, or some modern Protestants,
who insofar as they have laboured after a midst betwixt these two extremes,
have come near to the Truth, as by some citations out of them, hereafter to be mentioned,
will appear; though this doctrine hath not, since the apostasy,
so far as ever I could observe,
been so distinctly and evidently held forth according to the Scripture`'s testimony,
as it hath pleased God to reveal it and preach it forth in this
day by the witnesses of his Truth whom he hath raised to that end;
which doctrine, though it be briefly held forth and comprehended in the thesis itself,
yet I shall a little more fully explain the state of the controversy
as it stands betwixt us and those that now oppose us.

[.small-break]
'''

// lint-disable invalid-characters "§"
§III.
First then, as by the explanation of the former thesis appears,
we renounce all natural power and ability in ourselves,
in order to bring us out of our lost and fallen condition and first nature;
and confess that as of ourselves we are able to do nothing that is good:
so neither can we procure remission of sins or justification by any act
of our own so as to merit it or draw it as a debt from God due unto us,
but we acknowledge all to be _of_ and _from_ his _love,_
which is the original and fundamental cause of our acceptance.

Secondly, God manifested this love towards us in the sending of his beloved Son,
the Lord Jesus Christ, into the world,
who gave himself for us an offering and a sacrifice to God for a sweet-smelling savour;
and having made peace through the blood of his cross,
that he might reconcile us unto himself,
and by the Eternal Spirit offered himself without spot unto God,
and suffered for our sins, the just for the unjust, that he might bring us unto God.

Thirdly then,
forasmuch as all men who have come to man`'s estate
(the man Jesus only excepted) have sinned,
therefore all have need of this Saviour, to remove the wrath of God from them,
due to their offences; in this respect,
he is truly said to have "`borne the iniquities of us all
in his body on the tree,`" and therefore is the only Mediator,
having qualified the wrath of God towards us;
so that our former sins stand not in our way,
being by virtue of his most satisfactory sacrifice, removed and pardoned.
Neither do we think that remission of sins is to be expected, sought,
or obtained any other way, or by any works or sacrifice whatsoever (though,
as has been said formerly,
they may come to partake of this remission that are ignorant of the history).
So then Christ by his death and sufferings hath reconciled us to God,
even while we are enemies, that is, he offers reconciliation unto us,
we are put into a capacity of being reconciled,
God is willing to forgive us our iniquities and to accept us,
as is well expressed by the apostle (2 Cor. 5:19): "`God was in Christ,
reconciling the world unto himself, not imputing their trespasses unto them,
and hath put in us the word of reconciliation.`" And therefore the apostle,
in the next verses, entreats them "`in Christ`'s stead to be reconciled to God`";
intimating, that the wrath of God being removed by the obedience of Christ Jesus,
he is willing to be reconciled unto them, and ready to remit the sins that are past,
if they repent.

We consider then our redemption in a two-fold respect or state,
both which in their own nature are perfect though
in their application to us the one is not,
nor cannot be, without respect to the other.

The first is the redemption performed and accomplished
by Christ __for us__ in his crucified body without us.
The other is the redemption wrought by Christ __in us,__
which no less properly is called and accounted a redemption than the former.
The first then is that whereby man, as he stands in the fall,
is put into a capacity of salvation, and hath conveyed unto him a measure of that power,
virtue, spirit, life, and grace that was in Christ Jesus: which, as the free gift of God,
is able to counterbalance, overcome,
and root out the evil seed wherewith we are naturally as in the fall, leavened.

The second is that whereby we witness and know this pure and perfect redemption _in_ ourselves,
purifying, cleansing, and redeeming us from the power of corruption,
and bringing us into unity, favour, and friendship with God.

By the first of these two, we, that were lost in Adam,
plunged into the bitter and corrupt seed, unable, of ourselves, to do any good thing,
but naturally joined and united to evil, forward and propense to all iniquity,
servants and slaves to the power and spirit of darkness, are, notwithstanding all this,
so far reconciled to God by the death of his Son, while enemies,
that we are put into a capacity of salvation,
having the glad tidings of the Gospel of peace offered unto us,
and God is reconciled unto us in Christ, calls and invites us to himself,
in which respect, we understand these scriptures:
"`He slew the enmity in himself.`"^
footnote:[Eph. 2:15.]
"`He loved us first,`"^
footnote:[1 John 4:10.]
"`seeing us in our blood, he said unto us, Live`";^
footnote:[Ezek. 16:6.]
"`he who did not sin his own self, bare our sins in his own body on the tree`";^
footnote:[1 Pet. 2:22-24.]
and "`he died for our sins, the just for the unjust.`"^
footnote:[1 Pet. 3:18.]

By the second, we witness this capacity brought into act,
whereby receiving and not resisting the purchase of his death, to wit, the Light, Spirit,
and Grace of Christ revealed in us,
we witness and possess a real true and inward redemption
from the power and prevalency of sin,
and so come to be truly and really redeemed, justified, and made righteous,
and to a sensible union and friendship with God.
Thus he died "`for us, that he might redeem us from all iniquity`";^
footnote:[Tit. 2:14.]
and thus "`we know him and the power of his resurrection,
and the fellowship of his sufferings, being made conformable to his death.`"^
footnote:[Phil. 3:10.]
This last follows the first in order, and is a consequence of it,
proceeding from it, as an effect from its cause.
So as none could have enjoyed the last,
without the first had been (such being the will of God);
so also can none now partake of the first, but as he witnesseth the last.
Wherefore as to us, they are both causes of our justification;
the first the __procuring efficient,__ the other the __formal cause.__

Fourthly, we understand not by this justification by Christ, barely the good works,
even as wrought by the Spirit of Christ; for they, as Protestants truly affirm,
are rather an effect of justification, than the cause of it.
But we understand the _formation of Christ in us, Christ born and brought forth in us,_
from which good works as naturally proceed as fruit from a fruitful tree.
It is _this inward birth in us, bringing forth righteousness and holiness in us,
that doth justify us,_ which, having removed and done away the contrary nature and spirit,
that did bear rule and bring condemnation, now is in dominion over all, in our hearts.
Those then, that come to know Christ thus formed in them,
do enjoy him wholly and undivided,
who is "`the Lord our righteousness,`" (Jer. 23:6). This is to be clothed with Christ,
and to have put him on, whom God therefore truly accounteth righteous and just.
This is so far from being the doctrine of Papists, that,
as the generality of them do not understand it, so the learned among them oppose it,
and dispute against it, and particularly Bellarmine.
Thus then, as I may say, the formal cause of justification is not the works,
to speak properly, they being but an effect of it; but this inward birth,
this Jesus brought forth in the heart, who is the well-beloved,
whom the Father cannot but accept,
and all those who thus are sprinkled with the _blood_ of _Jesus,_ and washed with it.
By this also comes that communication of the goods of Christ unto us,
"`by which we come to be made partakers of the divine
nature,`" as saith Peter (2 Pet. 1:4),
and are made one with him, as the branches with the vine,
and have a title and right to what he hath done and suffered for us.
So that his obedience becomes ours, his righteousness ours, his death and sufferings ours.
And by this nearness we come to have a sense of his sufferings,
and to suffer with his seed,
that yet lies pressed and crucified in the hearts of the ungodly, and so travail with it,
and for its redemption, and for the repentance of those souls,
that in it are crucifying as yet the "`Lord of Glory.`" Even as the apostle Paul,
who by his sufferings is said to "`fill up that which
is behind of the afflictions of Christ for his body,
which is the church.`" Though this be a mystery sealed up from all the wise men,
that are yet ignorant of this seed _in_ themselves, and oppose it,
nevertheless some Protestants speak of this justification by Christ inwardly put on,
as shall hereafter be recited in its place.

Lastly,
though we place remission of sins in the righteousness
and obedience of Christ performed by him in the flesh,
as to what pertains to the remote procuring cause,
and that we hold ourselves formally justified by
Christ Jesus formed and brought forth in us;
yet can we not (as some Protestants have unwarily done) exclude works from justification:
for, though properly we be not justified __for them,__ yet are we justified __in them;__
and they are necessary, even as __causa sine qua non,__ i.e.,
the cause without which none are justified.
For the denying of this, as it is contrary to the Scripture`'s testimony,
so it hath brought a great scandal to the Protestant religion,
opened the mouths of Papists, and made many too secure,
while they have believed to be justified without good works.
Moreover, though it be not so safe to say they are meritorious, yet,
seeing they are rewarded,
many of those called the Fathers have not spared to use
the word "`merit,`" which some of us have perhaps also done,
in a qualified sense, but no ways to infer the Popish abuses above mentioned.
And lastly, if we had that notion of good works which most Protestants have,
we could freely agree to make them not only not necessary, but reject them as hurtful,
viz.: that the best works, even of the saints, are defiled and polluted.
For though we judge so of the best works performed
by man endeavouring a conformity to the outward law,
by his own strength, and in his own will,
yet we believe that such works as naturally proceed from this spiritual birth,
and formation of Christ in us, are pure and holy, even as the root from which they come,
and therefore God accepts them, justifies us __in them,__ and rewards us _for_ them,
of his own free grace.
The state of the controversy being thus laid down,
these following positions do from hence arise in the next place to be proved.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IV. First, that the obedience, sufferings,
and death of Christ is that by which the soul obtains remission of sins,
and is the procuring cause of that grace by whose
inward workings Christ comes to be formed inwardly,
and the soul to be made conformable unto him, and so just and justified.
And that therefore, in respect of this capacity and offer of grace,
God is said to be "`reconciled,`" not as if he were actually reconciled,
or did actually justify, or account any just,
so long as they remain in their sins really impure and unjust.

Secondly, that it is by this inward birth of Christ in man that man is made just,
and therefore so accounted by God, wherefore to be plain, we are thereby,
and not till that be brought forth _in_ us _formally_ (if we
must use that word) justified in the sight of God:
because _justification_ is, both more properly and frequently in Scripture,
taken in its proper signification, for making one just, and not reputing one merely such,
and is all one with _sanctification._

Thirdly, that since __good works__ as naturally follow from this birth as heat from fire,
therefore are they of __absolute necessity to justification,__ as __causa sine qua non,__
i.e. though not as the cause for which, yet as that in which we are,
and without which we cannot be, justified.
And though they be not meritorious, and draw no debt upon God,
yet he cannot but accept and reward them,
for it is contrary to his nature to deny his own:
since they may be perfect in their kind, as proceeding from a pure holy birth and root.
Wherefore their judgment is false, and against the Truth,
that say that the holiest works of the saints are defiled and sinful in the sight of God:
for these good works are not the works of the law excluded by the apostle from justification.

[.small-break]
'''

// lint-disable invalid-characters "§"
§V. As to the first, I prove it from Rom. 3:25:
"`Whom God hath set forth to be a propitiation through faith in his blood,
to declare his righteousness for the remission of sins that are past,
through the forbearance of God.`" Here the apostle
holds forth the extent and efficacy of Christ`'s death,
showing that thereby, and by faith therein, remission of sins that are past is obtained:
as being that, wherein the forbearance of God is exercised towards mankind.
So that though men, for the sins they daily commit, deserve eternal death,
and that the wrath of God should lay hold upon them; yet,
by virtue of that most satisfactory sacrifice of Christ Jesus,
the grace and seed of God moves in love towards
them during the day of their visitation:
yet not so as not to strike against the evil, for that must be burnt up and destroyed,
but to redeem man out of the evil.

Secondly, if God were perfectly reconciled with men, and did esteem them just,
while they are actually unjust and do continue in their sins,
then should God have no controversy with them;^
footnote:[I do not only speak concerning men before conversion,
who afterwards are converted, whom yet some of our antagonists, called Antinomians,
do aver were justified from the beginning; but also touching those who,
according to the common opinion of Protestants, have been converted; whom,
albeit they confess they persist always in some misdeeds, and sometimes in heinous sins,
as is manifest in David`'s adultery and murder,
yet they assert to be perfectly and wholly justified.]
how comes he then so often to complain, and to expostulate so much,
throughout the whole Scripture, with such as our adversaries confess to be justified,
telling them "`that their sins separate betwixt him and them?`" (Isa.
59:2). For where there is a perfect and full reconciliation,
there there is no separation.
Yea, from this doctrine it necessarily follows, either that such for whom Christ died,
and whom he hath thus reconciled, never sin, or that, when they so do,
they are still reconciled, and their sins make not the least separation from God, yea,
that they are justified in their sins.
From whence also would follow this abominable consequence,
that the good works and greatest sins of such are alike in the sight of God,
seeing neither the one serves to justify them,
nor the other to break their reconciliation, which occasions great security,
and opens a door to every lewd practice.

Thirdly, this would make void the whole practical doctrine of the Gospel,
and make faith itself needless; for if faith and repentance,
and the other conditions called for throughout the Gospel,
be a qualification upon our part necessary to be performed,
then before this be performed by us, we are either fully reconciled to God,
or but in a capacity of being reconciled to God,
he being ready to reconcile and justify us as these conditions are performed:
which latter, if granted, is according to the Truth we profess;
and if we are already perfectly reconciled and justified,
before these conditions are performed (which conditions are of
that nature that they cannot be performed at one time,
but are to be done all one`'s lifetime),
then can they not be said to be absolutely needful;
which is contrary to the very express testimony of Scripture,
which is acknowledged by all Christians:
"`For without faith it is impossible to please God.`"^
footnote:[Heb. 11:6.]
"`They that believe not are condemned already,
because they believe not in the only begotten Son of God.`"^
footnote:[John 3:18.]
"`Except ye repent, ye cannot be saved`":^
footnote:[Luke 13:3.]
for "`if ye live after the flesh, ye shall die.`"^
footnote:[Rom. 8:13.]
And of those that were converted, "`I will remove your candlestick from you,
unless ye repent.`"^
footnote:[Rev. 2:5.]
Should I mention all the Scriptures that positively and evidently prove this,
I might transcribe much of all the doctrinal part of the Bible.
For since Christ said,
"`It is finished,`" and did finish his work sixteen hundred years ago and upwards,
if he so fully perfected redemption then,
and did then actually reconcile everyone that is to be saved,
not simply opening a door of mercy for them, offering the sacrifice of his body,
by which they may obtain remission of their sins, when they repent,
and communicating unto them a measure of his grace, by which they may see their sins,
and be able to repent; but really make them to be reputed as just,
either before they believe (as say the Antinomians) or after
they have assented to the truth of the history of Christ,
or are sprinkled with the baptism of water, while nevertheless they are actually unjust,
so that no part of their redemption is to be wrought by him now,
as to their reconciliation and justification;
then the whole doctrinal part of the Bible is useless and of no profit;
in vain were the apostles sent forth to preach repentance and remission of sins,
and in vain do all the preachers bestow their labour, spend their lungs,
and give forth writings; yea much more in vain do the people spend their money,
which they give them for preaching, seeing it is all but __actum agere,__
but a vain and ineffectual essay,
to do that which is already perfectly done without them.

But lastly, To disregard
their human labours, as not worth the disputing, whether they be needful or not,
since (as we shall hereafter show) themselves confess the best of them is sinful;
this also makes void the present intercession of Christ for men.
What shall become of that great article of faith, by which we affirm,
"`That he sits at the right hand of God daily making intercession for us,
and for which end the Spirit itself maketh intercession for us
with groanings which cannot be uttered?`" For Christ maketh not
intercession for those that are not in a possibility of salvation;
that is absurd.

Our adversaries will not admit that he prayed for the world at all.
And to pray for those that are already reconciled, and perfectly justified,
is to no purpose: to pray for remission of sins is yet more needless, if all be remitted,
past, present, and to come.
Indeed there is not any solid solving of this, but by acknowledging,
according to the Truth, that Christ by his death removed the wrath of God,
so far as to obtain remission of sins for as many as receive that _Grace_ and _Light,_
that he communicates unto them, and hath purchased for them by his _blood:_
which as they believe in, they come to know remission of sins past,
and power to save them from sin, and to wipe it away,
so often as they may fall into it by unwatchfulness or weakness, if,
applying themselves to this grace, they truly repent: for "`to as many as receive him,
he gives power to become the sons of God.`" So none are sons, none are justified,
none reconciled, until they thus receive him in that little Seed in their hearts.
And life eternal is offered to those, "`who by patient continuance in well-doing,
seek for glory, honor, and immortality.`" For,
"`if the righteous man depart from his righteousness,
his righteousness shall be remembered no more`"; and therefore on the other part,
none are longer sons of God, and justified,
than they patiently continue in righteousness and welldoing.
And therefore Christ lives always making intercession,
during the day of every man`'s visitation, that they may be converted:
and when men are in some measure converted, he makes intercession that they may continue,
and go on, and not faint, nor go back again.
Much more might be said to confirm this truth;
but I go on to take notice of the common objections against it,
which are the arguments made use of to propagate the errors contrary to it.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VI. The first and chief is drawn from that
saying of the apostle before mentioned (2 Cor. 5:18-19),
"`God hath reconciled us to himself by Jesus Christ:
God was in Christ reconciling the world unto himself,
not imputing their trespasses unto them.`"

_Obj._
From hence they seek to infer that Christ fully perfected
the work of reconciliation while he was on earth.

_Answ._
I answer: If by "`reconciliation`" be understood the removing of wrath,
and the purchase of that Grace by which we may come to be reconciled, we agree to it;
but that that place speaks no more, appears from the place itself;
for when the apostle speaks in the __perfect time,__ saying,
"`He hath reconciled us,`" he speaks of himself and the saints, who,
having received the Grace of God purchased by Christ,
were through faith in him actually reconciled.
But as to the _world,_ he saith "`reconciling`" not "`reconciled`"; which reconciling,
though it denotes a time somewhat past, yet it is by the __imperfect time,__
denoting that the thing begun was not perfected.
For this work Christ began towards _all,_ in the days of his flesh, yea and long before:
for he was the mediator from the beginning,
and the "`Lamb slain from the foundation of the world.`" But in his flesh,
after he had perfectly "`fulfilled the law,`" and the "`righteousness
thereof,`" and "`rent the veil,`" and made way for the more
clear and universal revelation of the Gospel to _all,_
both Jew and Gentile,
he "`gave up himself a most satisfactory sacrifice for sin,`" which
becomes effectual to as many as receive him in his inward appearance,
in __his Light__ in the heart.
Again,
this very place showeth that no other reconciliation
is intended but the opening of a door of mercy,
upon God`'s part, and a removing of wrath for sins that are past, so as men,
notwithstanding their sins, are stated in a capacity of salvation.
For the apostle, in the following verse, saith, "`Now then we are ambassadors for Christ,
as though God did beseech you by us;
we pray you in Christ`'s stead be ye reconciled to God.`" For if
their reconciliation had already been perfectly accomplished,
what need any entreating then to be reconciled?
Ambassadors are not sent, after a peace already perfected, and reconciliation made,
to entreat for a reconciliation; for that implies a manifest contradiction.

Secondly, they object (v. 21 of the same chapter),
"`For he hath made him to be sin for us, who knew no sin,
that we might be made the righteousness of God in him.`"

_Obj._
From whence they argue, that as our sin is imputed to Christ, who had no sin;
so Christ`'s righteousness is imputed to us, without our being righteous.

_Answ._
But this interpretation is easily rejected;
for though "`Christ bare our sins,`" and "`suffered for us,`" and was
among men "`accounted a sinner,`" and "`numbered among transgressors`";
yet that God reputed him a sinner is nowhere proved.
For it is said, "`He was found before him holy, harmless, and undefiled,
neither was there found any guile in his mouth.`"^
footnote:[Heb. 7:26; 1 Pet. 2:22.]
That _we_ deserved these things, and much more for our sins,
which he endured in obedience to the Father, and according to his counsel, is true;
but that ever God reputed _him_ a sinner, is denied.
Neither did he ever die that we should be reputed righteous,
though no more really such than he was a sinner (as hereafter appears).
For indeed, if this argument hold,
it might be stretched that length as to become very pleasing
to wicked men that love to abide in their sins:
for if we be made righteous, as Christ was made a sinner, merely by imputation;
then as there was no sin, not in the least, in Christ,
so it would follow that there needed no more righteousness, no more holiness,
no more inward sanctification in us, than there was sin in him.
So then, by his "`being made sin for us`" must be understood his suffering for our sins,
that we might be made partakers of the grace purchased by him,
by the workings whereof we are made the righteousness of God in him.
For, that the apostle understood here a being made really righteous,
and not merely a being imputed such, appears by what follows,
seeing in verses 14-16 of the following chapter he argues
largely against any supposed agreement of light and darkness,
righteousness and unrighteousness; which must needs be admitted,
if men are to be reckoned engrafted in Christ, and real members of him,
merely by an imputative righteousness, wholly without them,
while they themselves are actually unrighteous.
And indeed it may be thought strange,
how some men have made this so fundamental an article of their faith,
which is so contrary to the whole strain of the Gospel.
A thing Christ in none of all his sermons and gracious
speeches ever willed any to rely upon;
always recommending to us _works,_ as instrumental in our justification;
and the more it is to be admired at,
because that that sentence or term (so frequently
in their mouths and so often pressed by them,
as the very basis of their hope and confidence), to wit,
"`the imputed righteousness of Christ,`" is not to be found in all the Bible,
at least as to my observation.
Thus have I passed through the first part, and that the more briefly,
because many who assert this justification by bare imputation,
do nevertheless confess that even the elect are not justified until they be converted;
that is, not until this imputative justification be applied to them by the Spirit.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VII.
I come then to the second thing proposed by me, which is,
that it is by this inward birth, or Christ formed within, that we are, so to speak,
formally justified in the sight of God.
I suppose I have said enough already to demonstrate how
much we ascribe to the death and sufferings of Christ,
as that whereby satisfaction is made to the justice of God, remission of sins obtained,
and this Grace and Seed purchased, by and from which this birth proceeds.
The thing now to be proved is, that by Christ Jesus formed in us we are justified,
or made just.
Let it be marked, I use "`justification`" in this sense upon this occasion.

First then I prove this by that of the apostle Paul (1 Cor. 6:11),
"`And such were some of you; but ye are washed, but ye are sanctified,
but ye are justified in the name of the Lord Jesus,
and by the Spirit of our God.`" First, this "`justified`" here understood,
must needs be __a being made really just,__ and not a being merely imputed such;
else "`sanctified`" and "`washed`" might be reputed a being esteemed so,
and not a being really so; and then it overturns the whole intent of the context.
For the apostle showing them in the preceding verses,
how the "`unrighteous cannot inherit the kingdom of God,`"
and descending to the several species of wickedness,
subsumes, that they __were sometimes__ such, but now are not any more such.
Wherefore, as they are now washed and sanctified, so are they justified:
for if this justification were not real,
then it might be alleged that the Corinthians had not forsaken these evils, but, were,
though still they continued in them, notwithstanding justified.
Which, as in itself, it is most absurd, so it very clearly
overturneth the very import and intent of the place;
as if the Corinthians turning Christians had not wrought any real change _in_ them,
but had only been a belief of some barren notions,
which had wrought no alteration in their affections, will, or manner of life.
For my own part, I neither see anything, nor could ever yet hear or read anything,
that with any color of reason did evince "`justified`" in this place to be understood
any other ways than in its own proper and genuine interpretation of being __made just.__
And for the more clear understanding hereof let it be considered,
that this word "`justify`" is derived either from the substantive "`justice,`"
or the adjective "`just.`" Both which words import the substantive,
that true and real __virtue in the soul,__ as it is in itself, to wit, it signifies really,
and not suppositively,
that excellent quality expressed and understood among men by the word "`justice`":
and the adjective "`just`" as applied signifies a man or woman who is just, that is,
in whom this quality of _justice_ is stated, for it would not only be great impropriety,
but also manifest falsity, to call a man just merely by supposition,
especially if he were really unjust.
Now this word "`justify`" formed or from "`justice,`" or "`just,`"
doth beyond all question signify a making just,
it being nothing else but a composition of the verb _facio,_ and the adjective _justus,_
which is nothing else than thus, _justifico,_ i.e., __justum facio,__ I make just;
and justified of _justus_ and _fio,_ as __justus fio,__ I become just, and _justificatus,_ i.e.,
__justus factus,__ I am made just.
Thus also is it with verbs of this kind, as _sanctifico,_ from _sanctus,_ holy, and _facio;_
_honorifico,_ from _honor_ and _facio;_ _sacrifico,_ from _sacer_ and _facio:_
all which are still understood of the subject really and truly
endued with that virtue and quality from which the verb is derived.
Therefore, as none are said to be sanctified that are really unholy, while they are such;
so neither can any be truly said to be justified, while they actually remain unjust.
Only this verb "`justify`" hath, in a metaphorical and figurative sense,
been otherwise taken, to wit, in a law sense;
as when a man really guilty of a crime is freed from the punishment of his sin,
he is said to be justified; that is, put in the place, as if he were just.
For this use of the word hath proceeded from that true supposition,
that none ought to be acquitted but the innocent.
Hence also that manner of speaking,
"`I will justify such a man,`" or "`I will justify this or that,`" is used
from the supposition that the person and thing is really justifiable.
And where there is an error and abuse in the matter,
so far there is also in the expression.

This is so manifest and apparent that Pareus,
a chief Protestant and a Calvinist also in his opinion, acknowledges this:
"`We never at any time said`" (saith he) "`nor thought that the righteousness
of Christ was imputed to us that by him we should be named formally just,
and be so, as we have divers times already showed;
for that would no less soundly fight with right reason than if a guilty
man absolved in judgment should say that he himself was formally just
by the clemency of the judge granting him his life.`"^
footnote:[_De Just. con. Bell. lib. 2 cap. 7 pag. 469._]
Now is it not strange that men should be so facile in a matter
of so great concernment as to build the stress of their acceptance
with God upon a mere borrowed and metaphorical signification,
to the excluding or at least esteeming that not necessary,
without which the Scripture saith expressly "`No man shall
ever see God?`" For if holiness be requisite and necessary,
of which this is said, then must good works also;
unless our adversaries can show us a holy man without good works.
But moreover "`justified`" in this figurative sense is used for "`approved`";
and indeed for the most part, if not always in Scripture,
when the word "`justify`" is used, it is taken in the worst part, that is,
that as the use of the word, that way, is a usurpation,
so it is spoken of such as usurp the thing to themselves,
while it properly doth not belong unto them,
as will appear to those that will be at the pains to examine these places: Ex. 23:7;
Job 9:20, and 27:5; Prov. 17:15; Isa. 5:23; Jer. 3:11; Ezek. 16:51-52;
Luke 10:29, and 16:15,
which are all spoken of men "`justifying the wicked,`" or of "`wicked men justifying themselves`";
that is, approving themselves in their wickedness.
If it be at any time in this signification taken in good part,
it is very seldom,
and that so obvious and plain by the context as leaves no scruple.
But the question is not so much of the use of the word,
where it is passingly or occasionally used,
as where the very doctrine of _justification_ is handled.
Where indeed to mistake it, viz., in its proper place,
so as to content ourselves with an _imaginary_ justification, while God requires a _real,_
is of most dangerous consequence, for the disquisition of which, let it be considered,
that in all these places to the Romans, Corinthians, Galatians, and elsewhere,
where the apostle handles this theme,
the word may be taken in its own proper signification, without any absurdity: as,
where it is often asserted in the above mentioned epistles to the Romans and Galatians,
that "`a man cannot be justified by the law of Moses, nor by the works of the law`";
there is no absurdity nor danger in understanding it,
according to its own proper signification, to wit,
that a man cannot be __made just__ by the law of Moses,
seeing this so well agrees with that saying of the same apostle,
That "`the law makes nothing perfect.`" And also where it is said,
"`We are justified by faith,`" it may be very well understood of being __made just,__
seeing it is also said that "`faith purifies the heart`";
and no doubt the pure in heart are just; and "`the just live by faith.`" Again,
where it is said,
"`We are justified by grace,`" "`We are justified by
Christ,`" "`We are justified by the Spirit`";
it is no ways absurd to understand it of being __made just,__
seeing by his Spirit and Grace he doth make men just.
But to understand it universally the other way, merely for _acceptance_ and _imputation,_
would infer great absurdities, as may be proved at large,
but because I judged it would be acknowledged, I forbear at present, for brevity`'s sake.
But further, in the most weighty places, where this word "`justify`" is used in Scripture,
with an immediate relation to the doctrine of justification,
our adversaries must needs acknowledge it to be understood of __making just,__
and not barely in the legal acceptation; as first, in that of 1 Cor. 6:11,
"`But ye are washed, but ye are sanctified,
but ye are justified,`" as I before have proved;
which also many Protestants are forced to acknowledge.
"`Neither diffide we,`" saith Thysius,
"`because of the most great and strict connection,
that justification doth sometimes seem also to comprehend sanctification as a consequence,
as in Rom. 8:30; Tit. 3:7; 1 Cor. 6:11, '`And such sometimes were ye,
but ye are washed,`'`" etc.^
footnote:[_Disp. de lust. Thes. 3._]
Zanchi having spoken concerning this sense of justification, adds, saying:
"`There is another signification of the word, viz: for a man from unjust to be made just,
even as sanctified signifies from unholy to be made holy.
In which signification the apostle said (in the place
above cited) '`And such were some of you,`' etc.,
that is, of unclean ye are made holy, and of unjust ye are made just by the Holy Spirit,
for Christ`'s sake, in whom ye have believed.
Of this signification is that (Rev. 22:11), '`Let him that is just, be just still`';
that is, really from just become more just, even as from unjust he became just.
And according to this signification the Fathers, and especially Augustine,
have interpreted this word.`"^
footnote:[_In cap. 2. ad Eph. ver 4. loc. de lust._]
Thus far he,
H+++.+++ Bullinger, on the same place (1 Cor. 6), speaketh thus:
"`By divers words`" (saith he) "`the apostle signifies the same thing when he saith,
Ye are washed, ye are sanctified, ye are justified.`"

Secondly, in that excellent saying of the apostle, so much observed (Rom. 8:30),
"`Whom he called, them he also justified, and whom he justified, them he also glorified`":
this is commonly called the "`golden chain,`" as being acknowledged
to comprehend the method and order of salvation.
And therefore, if "`justified`" were not understood here in its proper signification,
of being __made just,__ sanctification would be excluded out of this chain.
And truly it is very worthy of observation, that the apostle,
in this succinct and compendious account,
makes the word "`justified`" to comprehend all betwixt calling and glorifying;
thereby clearly insinuating that the being really _righteous_ is
that only medium by which from our calling we pass to glorification.
All for the most part do acknowledge the word to be so taken in this place,
and not only so,
but most of those who oppose are forced to acknowledge that as this is the most proper,
so the most common signification of it:
thus divers famous Protestants do acknowledge.
"`We are not,`" saith D. Chamierus,^
footnote:[_Tom. 3. de Sanct. lib. 10 cap. 1._]
"`such impertinent esteemers of words, as to be ignorant,
nor yet such importunate sophists,
as to deny that the words '`justification`' and '`sanctification`' do infer one another; yea,
we know that the saints are chiefly for this reason so called,
because that in Christ they have received remission of sins:
and we read in the Revelation, '`Let him that is just,
be just still,`' which cannot be understood,
except of the fruit of inherent righteousness.
Nor do we deny, but perhaps in other places they may be promiscuously taken,
especially by the Fathers.`"
"`I take,`" saith Beza,^
footnote:[_In cap. 3. ad Tit. ver. 7._]
"`the name of justification largely,
so as it comprehends whatsoever we acquire from Christ, as well by imputation,
as by the efficacy of the Spirit in sanctifying us.
So likewise is the word '`justification`' taken (Rom. 8:30).`" Melancthon saith,^
footnote:[_In Apol. Confess. Aug._]
"`That to be justified by faith, signifies in Scripture not only to be pronounced just,
but also of unrighteous to be made righteous.`"

Also some chief Protestants,
though not so clearly, yet in part, hinted at our doctrine,
whereby we ascribe unto the death of Christ remission of sins,
and the work of justification unto the grace of the Spirit acquired by his death.
Martin Borrhaus, explaining that place of the apostle (Rom. 4:25):
"`Who was given for our sins, and rose again for our justification,`" saith:
"`There are two things beheld in Christ, which are necessary to our justification;
the one is his death, the other is his arising from the dead.
By his death, the sins of this world behooved to be expiated.
By his rising from the dead, it pleased the same goodness of God to give the Holy Spirit,
whereby both the Gospel is believed, and the righteousness,
lost by the fault of the first Adam, is restored.`"^
footnote:[_In Gen. cap. 15. ad verb. Cred dit Abraham Deo+++.+++, p. 161._]
And afterwards he saith, "`The apostle expresseth both parts in these words,
who was given for our sins, etc. In his death is beheld the satisfaction for sin;
in his resurrection, the gift of the Holy Spirit,
by which our justification is perfected.`"^
footnote:[_lib. 3. Reg. cap. 9. ver. 4., p. 681._]
And again, the same man saith elsewhere:
"`Both these kinds of righteousness are therefore contained in justification,
neither can the one be separate from the other.
So that in the definition of justification, the merit of the blood of Christ is included,
both with the remission of sins,
and with the gift of the Holy Spirit of justification
and regeneration.`" Martin Bucer saith:^
footnote:[_In Rom. 4 3rd ver. 16._]
"`Seeing, by one sin of Adam the world was lost,
the grace of Christ hath not only abolished that one sin,
and death which came by it but hath together taken away those infinite sins,
and also led into full justification as many as are of Christ;
so that God now not only remits unto them Adam`'s sin, and their own,
but also gives them therewith the Spirit of a solid and perfect righteousness,
which renders us conformed unto the image of the first begotten.`" And upon these words,
"`by Jesus Christ`" he saith:
"`We always judge that the whole benefit of Christ tends to this,
that we might be strong through the gift of righteousness,
being rightly and orderly adorned with all virtue, that is,
restored to the image of God.`" And lastly, William Forbes, our countryman,
bishop of Edinburgh, saith,^
footnote:[_In considerat. modest. de Just. lib. 2. Sect. 8._]
"`Whensoever the Scripture makes mention of the justification before God,
as speaketh Paul, and from him, besides others, Augustine,
it appears that the word '`justify`' necessarily signifies not only to pronounce just,
in a law sense, but also really and inherently to make just,
because that God doth other ways justify a wicked man, than earthly judges.
For he, when he justifies a wicked or unjust man,
doth indeed pronounce him as these also do; but by pronouncing him just,
because his judgment is according to Truth,
he also makes him really of unjust to become just.`" And again, the same man,
upon the same occasion, answering the more rigid Protestants,
who say that God first justifies and then makes just, he adds, "`But let them have a care,
lest by too great and empty subtlety, unknown both to the Scriptures and the Fathers,
they lessen and diminish the weight and dignity of so great and divine a benefit,
so much celebrated in the Scripture, to wit, justification of the wicked.
For if,
to the formal reason of justification of the ungodly doth
not at all belong his justification (so to speak),
i.e., his being made righteous, then in the justification of a sinner,
although he be justified, yet the stain of sin is not taken away,
but remains the same in his soul, as before justification.
And so, notwithstanding the benefit of justification, he remains, as before,
unjust and a sinner, and nothing is taken away but the guilt and obligation to pain,
and the offence and enmity of God through nonimputation.
But both the Scriptures and Fathers do affirm, that in the justification of a sinner,
their sins are not only remitted, forgiven, covered, not imputed, but also taken away,
blotted out, cleansed, washed, purged, and very far removed from us,
as appears from many places of the holy Scriptures.`"

The same Forbes shows us at length,
in the following chapter, that this was the confessed judgment of the Fathers,
out of the writings of those who hold the contrary opinion, some whereof, out of him,
I shall note.
As first, Calvin saith:^
footnote:[_Inst. lib. 5. cap. 11, Sect. 15._]
"`That the judgment of Augustine, or at least his manner of speaking,
is not throughout to be received;
who although he took from man all praise of righteousness,
and ascribed all to the grace of God, yet he refers grace to sanctification,
by which we are regenerate through the Spirit unto newness of life.`" Chemnitz saith:^
footnote:[_In exam. Concil. Trid. de Just+++.+++, p. 129._]
"`That they do not deny, but that the Fathers take the word '`justify`' for renewing,
by which works of righteousness are wrought in us by the Spirit.`" And (p. 130):
"`I am not ignorant,
that the Fathers indeed often use the word '`justify`' in this signification, to wit,
of making just.`" Zanchi saith,^
footnote:[_In cap. 2. ad Eph. ver. 4 loc. de lust. Thes. 19._]
"`That the Fathers, and chiefly Augustine,
interpret the word '`justify`' according to this signification, to wit, of making just;
so that, according to them, to be justified was no other than of unjust to be made just,
through the grace of God for Christ.`" He mentioneth more,
but this may suffice to our purpose.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VIII.
Having thus sufficiently proved,
that by "`justification`" is to be understood a really being __made righteous,__
I do boldly affirm, and that not only from a notional knowledge, but from a real,
inward experimental feeling of the thing, that the immediate, nearest,
or formal cause (if we must, in condescendence to some,
use this word) of a man`'s justification in the sight of God,
is the __revelation of Jesus Christ in the soul,__ changing, altering, and renewing the mind,
by whom (even the Author of this inward work) thus formed and revealed,
we are truly justified and accepted in the sight of God.
For it is as we are thus covered and clothed with him,
in whom the Father is always well pleased, that we may draw near to God,
and stand with confidence before his throne,
being purged by the blood of Jesus inwardly poured into our souls,
and clothed with his life and righteousness therein revealed.
And this is that order and method of salvation held forth
by the apostle in that divine saying (Rom. 5:10):
"`For if, when we were enemies, we were reconciled to God by the death of his Son,
much more being reconciled,
we shall be saved by his life.`" For the apostle first holding
forth the reconciliation wrought by the death of Christ,
wherein God is near to receive and redeem man,
holds forth his salvation and justification to be by the __life of Jesus.__
Now that this life is an inward spiritual thing revealed _in_ the
soul whereby it is renewed and brought forth out of death,
where it naturally has been by the fall; and so quickened and made alive unto God.
The same apostle shows (Eph. 2:5):
"`Even when we were dead in sins and trespasses he hath quickened us together
with Christ (by whose grace ye are saved) and hath raised us up together.`" Now,
this none will deny to be the inward work of renovation,
and therefore the apostle gives that reason of their being __saved by grace,__
which is the inward virtue and power of Christ in the soul:
but of this place more hereafter.
Of the revelation of this inward life the apostle also speaketh (2 Cor. 4:10):
"`That the life also of Jesus might be made manifest in our body`"; and (v. 11):
"`That the life also of Jesus might be made manifest in our
mortal flesh.`" Now this inward life of Jesus is that whereby,
as is before observed, he said, "`we are saved.`"

Secondly, That it is by this revelation of Jesus Christ, and the new creation in us,
that we are justified,
doth evidently appear from that excellent saying of the
apostle included in the proposition itself (Tit. 3:5):
"`According to his mercy he hath saved us, by the washing of regeneration,
and renewing of the Holy Ghost,`" etc. Now that whereby we are saved,
that we are also no doubt justified by, which words are in this respect synonymous.
Here the apostle clearly ascribes the immediate cause
of justification to this inward work of regeneration,
which is Jesus Christ revealed _in_ the soul,
as being that which formally states us in a capacity of being reconciled with God;
the washing of regeneration being that inward power and virtue whereby
the soul is cleansed and clothed with the righteousness of Christ,
so as to be made fit to appear before God.

Thirdly, this doctrine is manifest from 2 Cor. 13:5:
"`Examine your own selves whether ye be in the faith, prove your own selves:
know ye not your own selves how that Jesus Christ is in you,
except ye be reprobates?`" First,
it appears here how earnest the apostle was that they should know __Christ in them,__
so that he presses this exhortation upon them and inculcates it three times.
Secondly, he makes the cause of reprobation, or not-justification,
the want of Christ thus revealed and known in the soul:
whereby it necessarily follows by the rule of contraries,
where the parity is alike (as in this case it is evident),
that where Christ is inwardly known there the persons
subjected to him are approved and justified.
For there can be nothing more plain than this, that if we must know Christ in us,
except we be reprobates, or unjustified persons;
that if we do know him in us we are not reprobates, and consequently justified ones.
Like unto this is that other saying of the same apostle (Gal. 4:19):
"`My little children,
of whom I travail in birth again until Christ be
formed in you,`" and therefore the apostle terms this,
"`Christ within,
the hope of glory`" (Col. 1:27-28). Now that which is the hope of glory
can be no other than that which we immediately and most nearly rely upon
for our justification and that whereby we are really and truly made just.
And as we do not hereby deny but the original and fundamental cause of our justification
is the love of God manifested in the appearance of Jesus Christ in the flesh,
who by his life, death,
sufferings and obedience made a way for our reconciliation and
became a sacrifice for the remission of sins that are past,
and purchased unto us this _seed_ and _grace_ from which this birth arises,
and in which Jesus Christ is inwardly received, formed,
and brought forth _in_ us in his own pure and holy image of righteousness;
by which our souls live unto God and are clothed with him, and have put him on,
even as the Scripture speaks (Eph. 4:23-24;
Gal. 3:27). We stand justified and saved in and by him,
and by his Spirit and grace (Rom. 3:24; 1 Cor. 6:11;
Tit. 3:7). So again reciprocally we are hereby
made partakers of the fullness of his merits,
and his cleansing blood is near to wash away every
sin and infirmity and to heal all our backslidings,
as often as we turn towards him by unfeigned repentance and become renewed by his Spirit.
Those then that find him thus raised and ruling in them have a
true ground of hope to believe that they are _justified_ by his blood.
But let not any deceive themselves,
so as to foster themselves in a vain hope and confidence
that by the death and sufferings of Christ they are justified,
so long as "`sin lies at their door`" (Gen. 4:7), iniquity prevails,
and they remain yet unrenewed and unregenerate; lest it be said unto them,
"`I know you not.`" Let that saying of Christ be remembered, "`Not everyone that saith Lord,
Lord, shall enter,
but he that doth the will of my Father`" (Matt. 7:21). To which
let these excellent sayings of the beloved disciple be added:
"`Little children, let no man deceive you, he that doth righteousness is righteous,
even as he is righteous.
He that committeth sin is of the devil; for if our heart condemn us,
God is greater than our heart and knoweth all things`" (1 John 3:20-7).

Many famous Protestants bear witness to this inward justification
by Christ inwardly revealed and formed _in_ man,
as 1) M. Borrhaus: "`In the imputation,`" saith he,
"`wherein Christ is ascribed and imputed to believers for righteousness,
the merit of his blood and the Holy Ghost given unto us by virtue of his merits,
are equally included.
And so it shall be confessed that _Christ_ is our _righteousness_ as well from his merit,
satisfaction,
and remission of sins obtained by him as from the gifts of the Spirit of righteousness.
And if we do this,
we shall consider the whole Christ proposed to us for our
salvation and not any single part of him.`"^
footnote:[_In Gen._ pag. 162.]
The same man (p. 169), "`In our justification then Christ is considered,
who breathes and lives _in_ us, to wit,
by his Spirit put on by us concerning which putting on the apostle saith,
'`Ye have put on Christ.`'`" And again (p. 171), "`We endeavour to treat, in justification,
not of part of Christ, but him wholly,
in so far as he is our righteousness every way.`" And a little after:
"`As then blessed Paul, in our justification, when he saith, '`Whom he justified,
them he glorified,`' comprehends all things which
pertain to our being reconciled to God the Father,
and our renewing which fits us for attaining unto glory, such as faith, righteousness,
Christ, and the gift of righteousness exhibited by him,
whereby we are regenerated to the fulfilling of the justification which the law requires;
so we also will have all things comprehended in this cause,
which are contained in the recovery of righteousness and innocency.`" And (p. 181):
"`The form,`" saith he, "`of our justification is the divine righteousness itself,
by which we are formed just and good.
This is Jesus Christ, who is esteemed our righteousness,
partly from the forgiveness of sins,
and partly from the renewing and the restoring of that integrity
which was lost by the fault of the first Adam:
so that this new and heavenly Adam being put on by us, of which the apostle saith,
'`Ye have put on Christ,`' ye have put him on, I say, as the form, so the righteousness,
wisdom, and life of God.`" So also affirmeth Claudius Alberius Inuncanus, see his [.book-title]#Orat. Apodict.
Lausaniae Excus+++.+++,# 1587. _Orat. 2,_ pp. 86-87.
Zwingli also, in his epistle to the princes of Germany,
as cited by Himelius, c+++.+++ vii., p. 60, saith,
"`That the sanctification of the Spirit is true justification,
which alone suffices to justify.`" Estius, upon 1 Cor. 6:11, saith,
"`Lest Christian righteousness should be thought to consist in the washing alone, that is,
in the remission of sins, he addeth the other degree or part, '`but ye are sanctified`';
that is, ye have attained to purity, so that ye are now truly holy before God.
Lastly,
expressing the sum of the benefit received in one word which includes both the parts,
but ye are justified, the apostle adds, in the name of the Lord Jesus Christ, that is,
by his merits, and in the Spirit of our God, that is the Holy Spirit,
proceeding from God, and communicated to us by Christ.`" And lastly Richard Baxter,
a famous English preacher,
in his book called [.book-title]#Aphorisms of Justification# (p. 80), saith,
"`That some ignorant wretches gnash their teeth at this doctrine,
as if it were flat Popery,
not understanding the nature of the righteousness of the new covenant;
which is all out of Christ in ourselves,
though wrought by the power of the Spirit of Christ in us.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§IX. The third thing proposed to be considered is concerning good works,
their necessity to justification.
I suppose there is enough said before to clear us
from any imputation of being Popish in this matter.

_Quest._
But if it be queried, Whether we have not said, or will not affirm,
that a man is justified by works?

_Answ._
I answer; I hope none need, neither ought to take offence,
if in this matter we use the plain language of the Holy Scripture,
which saith expressly in answer hereunto (James 2:24),
"`Ye see then how that by works a man is justified,
and not by faith only.`" I shall not offer to prove the truth of this saying,
since what is said in this chapter by the apostle is sufficient to convince any man,
that will read and believe it, I shall only from this derive this one argument:

[.syllogism]
* _Arg._ If no man can be justified without _faith,_ and no faith be _living_ nor yet available to justification without works, then __works are necessary to justification.__
* But the first is true;
* Therefore the last.

For this truth is so apparent and evident in the Scriptures that for the
proof of it we might transcribe most of the precepts of the Gospel.
I shall instance a few which of themselves do so clearly assert the thing
in question that they need no commentary nor further demonstration.
And then I shall answer the objections made against this
which indeed are the arguments used for the contrary opinion:
Heb. 12:14, "`Without holiness no man shall see God`"; Matt. 7:21,
"`Not every one that saith unto me, Lord, Lord, shall enter into the kingdom of heaven,
but he that doth the will of my Father which is in heaven`"; John 13:17,
"`If ye know these things, happy are ye if ye do them`"; 1 Cor. 7:19,
"`Circumcision is nothing, and uncircumcision is nothing,
but the keeping of the commandments of God`"; Rev. 22:14,
"`Blessed are they that do his commandments,
that they may have right to the tree of life and
through the gates may enter into the city`";
and many more that might be instanced.
From all which I thus argue:

[.syllogism]
* _Arg._ If those only can enter into the Kingdom, that do the will of the Father; if those be accounted only the wise builders and happy, that do the sayings of Christ; if no observation avail, but only the keeping of the commandments; and if they be blessed that do the commandments, and thereby have right to the tree of life, and entrance through the gates into the city; then works are absolutely necessary to salvation and justification:
* But the first is true;
* And therefore also the last.

The consequence of the antecedent is so clear and evident,
that I think no man of sound reason will call for a proof of it.

[.small-break]
'''

// lint-disable invalid-characters "§"
§X. _Obj._
But they object that works are not necessary to justification, first,
because of that saying of Christ (Luke 17:10),
"`When ye shall have done all these things that are commanded you, say,
we are unprofitable servants,`" etc.

_Answer:_ As to God we are indeed unprofitable, for he needeth nothing,
neither can we add anything unto him: but as to ourselves we are not unprofitable,
else it might be said that it is not profitable for a man to keep God`'s commandments,
which is most absurd and would contradict Christ`'s doctrine throughout.
Doth not Christ (Matt. 5), through all those beatitudes,
pronounce men blessed for their purity, for their meekness, for their peaceableness,
etc.? And is not then that for which Christ pronounceth men blessed profitable unto them?
Moreover (Matt. 25:21, 23),
doth not Christ pronounce the men "`good and faithful servants`" that improved their talents?
Was not their doing of that then profitable unto them?
And (v. 30) it is said of him that hid his talent and did not improve it,
"`Cast ye the unprofitable servant into utter darkness.`" If then
their not improving of the talent made the man unprofitable,
and he was therefore cast into utter darkness, it will follow by the rule of contraries,
so far at least that the improving made the other profitable; seeing,
if our adversaries will allow us to believe Christ`'s words,
this is made a _reason_ and so at least a __cause instrumental__ of their acceptance:
"`Well done, good and faithful servant, thou hast been faithful over a few things,
I will make thee ruler over many things; enter thou into the joy of thy Lord.`"

_Obj._
Secondly, they object those sayings of the apostle,
where he excludes the deeds of the law from justification;
as first (Rom. 3:20),
"`Because by the deeds of the law therefore shall be no flesh justified in his sight,
and (v. 28) "`therefore we conclude that a man is
justified by faith without the deeds of the law.`"

_Answ._
We have shown already what place we give to works, even to the best of works,
in justification,
and how we ascribe its immediate and formal cause to the _worker_ brought forth _in_ us,
but not to the _works._
But in answer to this objection, I say,
there is a great difference betwixt the works of the Law,
and those of grace or of the Gospel.
The first are excluded, the second not, but are necessary.
The first are those which are performed in man`'s own will and by his strength,
in a conformity to the outward law and letter,
and therefore are man`'s own imperfect works, or works of the Law,
which __makes nothing perfect.__
And to this belong all the ceremonies, purifications, washings,
and traditions of the Jews.
The second are the works of the Spirit of Grace in the heart,
wrought in conformity to the inward and spiritual law:
which works are not wrought in man`'s will, nor by his power and ability,
but in and by the power and Spirit of Christ _in_ us,
and therefore are _pure_ and _perfect_ in their kind, as shall hereafter be proven,
and may be called Christ`'s works, for that he is the immediate author and worker of them.
Such works we affirm __absolutely necessary to justification,__
so that a man cannot be justified without them;
and all faith without them is dead and useless, as the apostle James saith.
Now that such a distinction is to be admitted,
and that the works excluded by the apostle in the
matter of justification are of the first kind,
will appear, if we consider the occasion of the apostle`'s mentioning this, as well here,
as throughout his epistle to the Galatians, where he speaks of this matter,
and to this purpose, at large: which was this,
that whereas many of the Gentiles that were not of the race nor seed of Abraham,
as concerning the flesh, were come to be converted to the Christian faith,
and to believe in him,
some of those that were of the Jewish proselytes thought to subject the
faithful and believing Gentiles to the legal ceremonies and observations,
as necessary to their justification.
This gave the apostle Paul occasion at length, in his epistle to the Romans,
Galatians and elsewhere, to show the use and tendency of the Law,
and of its works,
and to contradistinguish them from the faith of Christ and the righteousness thereof;
showing how the former was ceased and become ineffectual; the other remaining,
and yet necessary.
And that the works excluded by the apostle are of this kind of works of the Law,
appears by the whole strain of his epistle to the Galatians, chaps.
1-4. For after, in the 4th chapter,
he upbraideth them for their returning unto the observation of days and times, and that,
in the beginning of the 5th chapter,
he showeth them their folly and the evil consequence
of adhering to the ceremonies of circumcision,
then he adds (v. 6),
"`For in Christ Jesus neither circumcision nor uncircumcision availeth,
but faith which worketh by love`"; and thus he concludes again (chap.
6, v. 15), "`For in Christ Jesus neither circumcision availeth, nor uncircumcision,
but a new creature.`" From which places appeareth that distinction of works afore-mentioned,
whereof the one is excluded, the other necessary to justification.
For the apostle showeth here that circumcision,
which word is often used to comprehend the whole
ceremonies and legal performances of the Jews,
is not necessary, nor doth avail.
Here are then the works which are excluded, by which no man is justified; but faith,
which worketh by love, but the new creature, this is that which availeth,
which is absolutely necessary; for faith that worketh by love, cannot be without works;
for, as it is said in the same 5th chapter, verse 22,
"`Love is a work of the Spirit.`" Also the new creature, if it avail and be necessary,
cannot be without works,
seeing it is natural for it to bring forth works of righteousness.
Again, that the apostle no ways intends to exclude such good works appears,
in that in the same epistle he exhorts the Galatians to them,
and holds forth the usefulness and necessity of them, and that very plainly, (chap.
6, vv.
7-9): "`Be not deceived,`" saith he, "`God is not mocked; for whatsoever a man soweth,
that shall he also reap: for he that soweth to the flesh,
shall of the flesh reap corruption; but he that soweth to the Spirit,
shall of the Spirit reap life everlasting.
And let us not be weary in well-doing, for in due season we shall reap,
if we faint not.`" Doth it not hereby appear,
how necessary the apostle would have the Galatians
know that he esteemed good works to be?
To wit, not the outward ceremonies and traditions of the Law,
but the fruits of the Spirit mentioned a little before,
by which Spirit he would have them to be led, and walk in those good works: as also,
how much he ascribed to these good works by which he affirms life everlasting is reaped.
Now, that cannot be useless to man`'s justification,
which capacitates him to reap so rich a harvest.

But lastly, for a full answer to this objection,
and for the establishing of this doctrine of good works,
I shall instance another saying of the same apostle Paul,
which our adversaries also in the blindness of their minds make use of against us,
to wit (Tit. 3:5): "`Not by works of righteousness which we have done,
but according to his mercy he saved us, by the washing of regeneration,
and renewing of the Holy Ghost.`" It is generally granted by all,
that "`saved`" is here all one as if it had been said "`justified.`"
Now there are two kinds of works here mentioned:
one by which we are not saved, that is, not justified; and another by which we are saved,
or justified.
The first, the works of righteousness which we have wrought, that is,
which we in our first, fallen nature, by our own strength, have wrought,
our own legal performances, and therefore may truly and properly be called ours,
whatever specious appearances they may seem to have.
And that it must needs and ought so to be understood, doth appear from the other part:
"`But by the washing of regeneration, and renewing of the Holy Ghost`";
seeing regeneration is a work, comprehensive of many good works,
even of all those which are called "`the fruits of the Spirit.`"

_Obj._
Now in case it should be objected that these may also be called ours,
because wrought in us, and also by us many times as instruments.

_Answ._
I answer, it is far otherwise than the former:
for in the first we are yet alive in our own natural state, unrenewed,
working of ourselves,
seeking to save ourselves by imitating and endeavouring
a conformity to the outward letter of the Law,
and so wrestling and striving in the carnal mind that is
enmity to God and in the cursed will not yet subdued.
But in this second we are "`crucified with Christ,`" we are become
"`dead with him,`" have "`partaken of the fellowship of his sufferings,`"
are made "`conformable to his death,`" and our first man,
our "`old man with all his deeds,`" as well the openly wicked as the seeming righteous,
our legal endeavours and foolish wrestlings are all
buried and nailed to the cross of Christ,
and so it is no more we but __Christ alive in__ us, the worker in us.
So that though it be we in a sense,
yet it is according to that of the apostle to the same (Gal. 2:20),
"`I am crucified with Christ,
nevertheless I live, yet not I, but Christ liveth in me,`" not I,
but the Grace of Christ in me.
These works are especially to be ascribed to the
Spirit of Christ and the grace of God _in_ us,
as being immediately thereby acted and led in them, and enabled to perform them.
And this manner of speech is not strained, but familiar to the apostles,
as appears (Gal. 2:8):
"`For he that wrought effectually in Peter to the apostleship of the circumcision,
the same was mighty in me,`" etc. (Phil. 2:13): "`For it is God which worketh in you,
both to will and to do,`" etc. So that it appears by this place, that,
since the washing of regeneration is necessary to justification,
and that regeneration comprehends works, works are necessary;
and that these works of the law that are excluded,
are different from these that are necessary and admitted.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XI. _Obj._
Thirdly, they object that no works, yea, not the works of Christ in us,
can have place in justification, because nothing that is impure can be useful in it;
and all the works wrought in us are impure.
For this they allege that saying of the prophet Isaiah (64:6):
"`All our righteousnesses are as filthy rags`"; adding this reason, that,
seeing we are impure, so must our works be, which, though good in themselves,
yet as performed by us they receive a tincture of impurity,
even as clean water passing through an unclean pipe is defiled.

_Answ._
That no impure works are useful to justification is confessed;
but that all the works wrought _in_ the saints are such is denied.
And for answer to this, the former distinction will serve.
We confess that the first sort of works, above mentioned, are impure; but not the second:
because the first are wrought in the unrenewed state, but not the other.
And as for that of Isaiah, it must relate to the first kind; for though he saith,
"`All our righteousnesses are as filthy rags,`" yet that will
not comprehend the righteousness of Christ _in_ us,
but only that, which we work _of_ and _by_ ourselves.
For should we so conclude,
then it would follow that we should throw away all holiness and righteousness,
since that which is as filthy rags, and as a menstruous garment, ought to be thrown away;
yea, it would follow that all the fruits of the Spirit, mentioned Gal. 5,
were as filthy rags: whereas, on the contrary,
some of the works of the saints are said to have
a "`sweet savour in the nostrils of the Lord`";
are said to be an "`ornament of great price in the sight of God`";
are said to "`prevail with him,`" and to be "`acceptable to him`";
which filthy rags and a menstruous garment cannot be.
Yea many famous Protestants have acknowledged that this place is not, therefore,
so to be understood.
Calvin upon this place saith, "`That it is used to be cited by some,
that they may prove there is so little merit in our works, that they are, before God,
filthy and defiled;
but this seems to me to be different from the prophet`'s mind`" (saith he)
"`seeing he speaks not here of all mankind.`" Musculus upon this place saith,
"`That it was usual for this people to presume much of their legal righteousness,
as if thereby they were made clean; nevertheless,
they had no more cleanness than the unclean garment of a man.
Others expound this place concerning all the righteousness of our flesh;
that opinion indeed is true.
Yet I think that the prophet did rather accommodate these sayings to the impurity
of that people in legal terms.`" The author (commonly supposed Bertius) speaking
concerning the true sense of the 7th chapter of the epistle to the Romans,
hath a digression touching this of Isaiah, saying,
"`This place is commonly corrupted by a pernicious wresting: for it is still alleged,
as if the meaning thereof inferred the most excellent
works of the best Christians,`" etc.^
footnote:[_Epistola praefixiae dissert. ann._]
James Coret, a French minister in the church of Basil,
in his Apology concerning Justification against Alescales, saith; "`Nevertheless,
according to the counsel of certain good men,
I must admonish the reader that it never came into
our minds to abuse that saying of Isaiah (64:6),
against good works, in which it is said, that all our righteousnesses are as filthy rags,
as if we would have that which is good in our good works,
and proceedeth from the Holy Spirit,
to be esteemed as a filthy and unclean thing.`"^
footnote:[_Impress. Paris ann. 1597, pag. 78._]

[.small-break]
'''

// lint-disable invalid-characters "§"
§XII.
As to the other part,
that seeing the best of men are still impure and imperfect,
therefore their works must be so; it is to beg the question,
and depends upon a proposition denied,
and which is to be discussed at further length in the next proposition.
But though we should suppose a man not thoroughly perfect in all respects,
yet will not that hinder,
but good and perfect works in their kind may be brought
forth _in_ him by the Spirit of Christ;
neither doth the example of water going through an unclean pipe hit the matter;
because though water may be capable to be tinctured with uncleanness,
yet the Spirit of God cannot,
whom we assert to be the immediate author of those works that avail in justification;
and therefore Jesus Christ`'s works in his children are pure and perfect,
and he worketh in and through that pure thing of his own forming and creating _in_ them.
Moreover, if this did hold, according to our adversaries`' supposition,
that no man ever was or can be perfect,
it would follow that the very miracles and works of the apostles,
which Christ wrought in them, and they wrought in and by the Power,
Spirit and Grace of Christ, were also impure and imperfect,
such as their converting of the nations to the Christian faith,
their gathering of the churches, their writing of the Holy Scriptures, yea,
and their offering up and sacrificing of their lives for the testimony of Jesus.
What may our adversaries think of this argument, whereby it will follow,
that the Holy Scriptures, whose perfection and excellency they seem so much to magnify,
are proved to be impure and imperfect,
because they came through impure and imperfect vessels?
It appears by the confessions of Protestants,
that the Fathers did frequently attribute unto works of this kind,
that instrumental work, which we have spoken of,
in justification (albeit some ignorant persons cry out it is Popery) and also divers,
and that famous Protestants, do of themselves confess it.
Amandus Polanus, in his [.book-title]#Symphonia Catholica, cap.
27, de Remissione Peccatorum,# p. 651,
places this thesis as the common opinion of Protestants,
most agreeable to the doctrine of the Fathers:
"`We obtain the remission of sins by repentance, confession, prayers,
and tears proceeding from faith, but do not merit, to speak properly;
and therefore we obtain remission of sins,
not by the merit of our repentance and prayers,
but by the mercy and goodness of God.`" Innocentius Gentiletus,
a lawyer of great fame among Protestants,
in his [.book-title]#Examen of the Council of Trent# (pages 66-67, of justification),
having before spoken of faith and works, adds these words:
"`But seeing the one cannot be without the other,
we call them both conjunctly instrumental causes.`"^
footnote:[_Impress Genevae 1536._]
Zanchi, in his fifth book [.book-title]#De Natura Dei,# saith;
"`We do not simply deny that good works are the cause of salvation, to wit,
the instrumental, rather than the efficient cause,
which they call __sine qua non.`"__ And afterwards,
"`Good works are the instrumental cause of the possession of life eternal, for by these,
as by a means and a lawful way,
God leads unto the possession of life eternal.`" W. Ames saith, "`That our obedience,
albeit it be not the principal and meritorious cause of life eternal,
is nevertheless a cause in some respect, administering, helping,
and advancing towards the possession of the life.`"^
footnote:[_In medulla S. Theologiae, lib.
2, cap.
1, thesi 30._]
Also Richard Baxter, in the book above cited (p. 155), saith,
"`That we are justified by works in the same kind of causality as by faith, to wit,
as being both causes __sine qua non,__
or conditions of the new covenant on our part requisite
to justification.`" And (p. 195) he saith,
"`It is needless to teach any scholar, who hath read the writings of Papists,
how this doctrine differs from them.`"

But lastly, because it is fit here to say something of the _merit_ and _reward_ of _works,_
I shall add something in this place of our sense and belief concerning that matter:
we are far from thinking or believing that man merits anything by his works from God,
all being of __free grace,__ and therefore do we,
and always have denied that Popish notion of __meritum ex condigno,__
nevertheless we cannot deny but that God out of his
infinite goodness wherewith he hath loved mankind,
after he communicates to him his holy Grace and Spirit, doth, according to his own will,
recompense and reward the good works of his children:
and therefore this merit of congruity or reward,
insofar as the Scripture is plain and positive for it, we may not deny;
neither wholly reject the word in so far as the Scripture makes use of it.
// lint-disable invalid-characters
For the same Greek ἄξιον, which signifies "`merit,`"
is also in those places where the translators express it _worth,_
or _worthy,_ as Matt. 3:8; 1 Thess. 2:12; 2 Thess.
1:5,11. Concerning which R. Baxter saith, in the above cited book (p. 8),
"`But in a larger sense as promise is an obligation,
and the thing promised is said to be debt,
so the performers of the conditions are called worthy, and that which they perform merit,
although properly all be of grace and not of debt.`" Also those who are called
the Fathers of the church frequently used this word of "`merit,`" whose sayings
concerning this matter I think not needful to insert because it is not doubted,
but evident,
that many Protestants are not averse from this word in the sense that we use it.
The [.book-title]#Apology for the Augustan Confession,# art.
20, hath these words: "`We agree that works are truly meritorious,
not of remission of sins or justification;
but they are meritorious of other rewards corporal and spiritual,
which are indeed as well in this life as after this life.`" And further,
"`Seeing works are a certain fulfilling of the law,
they are rightly said to be meritorious;
it is rightly said that a reward is due to them.`"

In the acts of the conference of Oldenburgh the Electoral Divines (pp. 110 and 265) say,
"`In this sense our churches also are not averse from the word '`merit`' used by the Fathers;
neither therefore do they defend the Popish doctrine of merit.`"

G+++.+++ Voss, in his theological thesis concerning the merits of good works, saith;
"`We have not adventured to condemn the word '`merit`' wholly,
as being that which both many of the ancients use,
and also the reformed churches have used in their confessions.
Now that God judgeth and accepteth men, according to their works,
is beyond doubt to those, that seriously will read and consider these scriptures:
Matt. 16:27; Rom. 2:6-7,10; 2 Cor. 5:10; James 1:25; Heb. 10:35;
1 Pet. 1:17; Rev. 22:12.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIII.
And to conclude this theme, let none be so bold as to mock God,
supposing themselves justified and accepted in the sight of God,
by virtue of Christ`'s death and sufferings,
while they remain unsanctified and unjustified in their own hearts,
and polluted in their sins, lest their _hope_ prove that of the _hypocrite,_
which __perisheth.__^
footnote:[Job 8:13.]
Neither let any foolishly imagine that they can, by their own works,
or by the performance of any ceremonies or traditions,
or by the giving of gold or money,
or by afflicting their bodies in will worship and voluntary humility,
or foolishly striving to conform their way to the outward letter of the law,
flatter themselves that they merit before God, or draw a debt upon him, or that any man,
or men, have power to make such kind of things effectual to their justification,
lest they be found foolish boasters and strangers to Christ and his righteousness indeed.
But blessed forever are they,
that having truly had a sense of their own unworthiness and sinfulness,
and having seen all their own endeavours and performances fruitless and vain,
and beheld their own emptiness, and the vanity of their vain hopes, faith,
and confidence, while they remained inwardly pricked, pursued,
and condemned by __God`'s holy witness__ in their _hearts,_
and so having applied themselves thereto, and suffered his grace to work in them;
are become changed and _renewed in the spirit of_ their _minds,_ passed from death to life,
and know _Jesus_ arisen _in_ them, working both the will and the deed;
and so having "`put on the Lord Jesus Christ,`" in effect are clothed
with him and partake of his righteousness and nature;
such can draw near to the Lord with boldness, and know their acceptance _in,_ and _by_ him;
__in whom,__ and in as many as are found in him, __the Father is well pleased.__
