== THE EIGHTH PROPOSITION

[.chapter-subtitle--blurb]
Concerning Perfection

[.heading-continuation-blurb]
In whom this pure and holy birth is fully brought forth,
the body of death and sin comes to be crucified and removed,
and their hearts united and subjected to the Truth:
so as not to obey any suggestions or temptations of the evil one,
but to be free from actual sinning and transgressing of the law of God,
and in that respect perfect: yet doth this perfection still admit of a growth;
and there remaineth always, in some part, a possibility of sinning,
where the mind doth not most diligently and watchfully attend unto the Lord.

// lint-disable invalid-characters "§"
§I. Since we have placed justification in the revelation
of Jesus Christ formed and brought forth in the heart,
there working his works of righteousness and bringing forth the fruits of the Spirit.
The question is how far he may prevail _in_ us, while we are in this life,
or we over our souls`' enemies, in and by his strength?
Those that plead for justification wholly without them,
merely by imputative righteousness,
denying the necessity of being clothed with real and inward righteousness,
do consequently affirm that it is "`impossible`" for a man, even "`the best of men,
to be free of sin in this life, which,`" they say, "`no man ever was`"; but on the contrary,
that none can, "`neither of himself,
nor by any grace received in this life`" +++[+++O! wicked
saying against the power of God`'s Grace],
"`keep the commandments of God perfectly,
but that every man doth break the commandments in thought, word and deed.`"^
footnote:[These are the words of the Westminster larger Catechism.]
Whence they also affirm, as was a little before observed,
that the very best actions of the saints, their prayers, their worships,
are impure and polluted.
We, on the contrary, though we freely acknowledge this of the natural, fallen man,
in his first state, whatever his profession or pretence may be,
so long as he is unconverted and unregenerate:
yet we do believe that to those in whom Christ comes to be formed
and the new man brought forth and born of the incorruptible seed,
as that birth and man in union therewith naturally doth the will of God,
so it is possible so far to keep to it as not to
be found daily transgressors of the law of God.
And for the more clear stating of the controversy, let it be considered.

[.small-break]
'''

// lint-disable invalid-characters "§"
§II. First, that we place not this possibility in man`'s own will and capacity,
as he is a man, the son of fallen Adam, or as he is in his natural state,
however wise or knowing,
or however much endued with a notional and literal knowledge of Christ,
thereby endeavouring a conformity to the letter of the law, as it is outward.

Secondly, That we attribute it wholly to man as he is born again, renewed in his mind,
raised by Christ, knowing Christ alive, reigning and ruling in him,
and guiding and leading him by his Spirit,
and revealing in him the law of the Spirit of life;
which not only manifests and reproves sin but also gives power to come out of it.

Thirdly,
that by this we understand not such a perfection as may not daily admit of a growth,
and consequently mean not, as if we were to be as pure, holy,
and perfect as God in his divine attributes of wisdom, knowledge and purity;
but __only a perfection proportionable and answerable to man`'s measure,__
whereby we are kept from transgressing the law of
God and enabled to answer what he requires of us,
even as he that improved his two talents so as to make four of them perfected his work,
and was so accepted of his Lord as to be called a "`good and faithful
servant,`" nothing less than he that made his five ten.
Even as a little gold is perfect gold in its kind, as well as a great mass,
and a child hath a perfect body as well as a man, though it daily grow more and more.
Thus Christ is said (Luke 2:52) to have "`increased in wisdom and stature,
and in favour with God and man,`" though before that time he had __never sinned,__
and was (no doubt) perfect, in a true and proper sense.

Fourthly, though a man may witness this for a season,
and therefore all ought to press after it, yet we do not affirm but _those,
that have attained it in a measure, may, by the wiles and temptations of the enemy,
fall into iniquity, and lose it sometimes, if they be not watchful,
and do not diligently attend to that of God in the heart._
And we doubt not but many good and holy men, who have arrived to everlasting life,
have had divers ebbings and flowings of this kind,
for though every sin weakens a man in his spiritual condition,
yet it doth not so as to destroy him altogether, or render him incapable of rising again.

Lastly,
though I affirm that after a man hath arrived to
such a condition in which a man may not sin,
he yet may sin;
I will nevertheless not deny but there may be a state attainable in this life,
in which to do righteousness may become so natural to the regenerate soul,
that in the stability of this condition they can not sin.
Others may perhaps speak more certainly of this state, as having arrived to it.
For me, I shall speak modestly, as acknowledging myself not to have arrived at it;
yet I dare not deny it, for that it seems so positively to be asserted by the apostle,
in these words (1 John 3:9), "`He that is born of God sinneth not, neither can he,
because the seed of God remaineth in him.`"^
footnote:[Later editors render this paragraph as follows: "`Lastly,
though I affirm that after a man hath arrived at
such a state in which he may be able not to sin,
yet he may sin;
nevertheless I will not affirm that a state is not attainable in this life,
in which to do righteousness may be so natural to the regenerate soul,
that in the stability of that condition he cannot sin.
Others may speak more certainly of this state, if they have arrived at it.
With respect to myself, I speak modestly,
because I ingenuously confess that I have not yet attained it;
but I cannot deny that there is such a state,
as it seems to be so clearly asserted by the apostle, 1 John 3:9,
'`whosoever is born of God doth not commit sin; for his seed remaineth in him:
and he cannot sin, because he is born of God.`'`" ]

The controversy being thus stated, which will serve to obviate objections,
I shall proceed first to show the absurdity of that
doctrine that pleads for __sin for term of life,__
even in the saints.

Secondly,
prove this doctrine of perfection from many pregnant testimonies of the holy Scripture.

And lastly, answer the arguments and objections of our opposers.

[.small-break]
'''

// lint-disable invalid-characters "§"
§III.
First then, this doctrine, viz:
that the saints nor can nor ever will be free of sinning in this life,
is __inconsistent with the wisdom of God and with his glorious power and majesty,__
"`who is of purer eyes than to behold iniquity,`"^
footnote:[Hab. 1:13.]
who having purposed in himself to gather to him, that should worship him,
and be witnesses for him on earth, a chosen people,
doth also no doubt sanctify and purify them.
For God hath no delight in iniquity, but abhors transgression,
and though he regard man in transgression,
so far as to pity him and afford him means to come out of it, yet he loves him not,
neither delights in him, as he is joined thereunto.
Wherefore, if man must always be joined to sin,
then God should always be at a distance with them, as it is written (Isa. 59:2),
"`Your iniquities have separated between you and your God,
and your sins have hid his face from you`"; whereas, on the contrary,
the saints are said to "`partake,`" even while here,
"`of the divine nature`" (2 Pet. 1:4),
and to be "`one spirit`" with the Lord (1 Cor. 6:17); now no unclean thing can be so.
It is expressly written,
that there is "`no communion betwixt light and darkness`"
(2 Cor. 6:14). But God is Light,
and every sin is darkness in a measure.
What greater stain then can there be than this upon God`'s wisdom?
as if he had been wanting to prepare a means whereby
his children might perfectly serve and worship him,
or had not provided a way whereby they might serve him in anything
but that they must withal still serve the devil no less,
yea more than himself.
For "`he that sinneth is the servant of sin`" (Rom. 6:16),
and every sin is an act of service and obedience to the devil.
So then if the saints sin daily, in thought, word and deed, yea,
if the very service they offer to God be sin,
surely they serve the devil more than they do God.
For besides that they give the devil many entire
services without mixture of the least grain to God,
they give God not the least service in which the devil hath not a large share;
and if their prayers and all their spiritual performances be sinful,
the devil is as much served by them in these as God, and in most of them much more:
since they confess that many of them are performed
without the leadings and influence of God`'s Spirit.
Now, who would not account him a foolish master among men, who being able to do it,
and also desirous it might be so,
yet would not provide a way whereby his children and servants
might serve him more entirely than his avowed enemy,
or would not guard against their serving of him;
but be so imprudent and unadvised in his contrivance that
whatever way his servants and children served him,
they should no less, yea often much more, serve his enemy?
What may we then think of that doctrine that would infer
this folly upon the omnipotent and only wise God?

[.small-break]
'''

// lint-disable invalid-characters "§"
§IV. Secondly, __It is inconsistent with the justice of God.__
For since he requires purity from his children,
and commands them to abstain from every iniquity, so frequently and precisely,
as shall hereafter appear;
and since "`his wrath is revealed against all ungodliness and unrighteousness
of men,`" it must needs follow that he hath capacitated man to answer his will,
or else that he requires more than he has given power to perform:
which is to declare him openly unjust, and with the slothful servant,
to be a "`hard master.`" We have elsewhere spoken of
the injustice these men ascribe to God,
in making him to damn the wicked,
to whom they allege he never afforded any means of being good.
But this is yet an aggravation more irrational and inconsistent,
to say that God will not afford to those whom he hath chosen to be his
own (whom they confess he loveth) the means to please him.
What can follow then from so strange a doctrine?
This imperfection in the saints either proceeds from God, or from themselves.
If it proceeds from them,
it must be because they are short in improving or making use of the power given them,
whereby they are capable to obey;
and so it is a thing possible to them (as indeed it is by the help of that power),
but this our adversaries deny;
they are then not to be blamed for their imperfection and continuing in sin,
since it is not possible for them to do otherwise.
If it be not of themselves, it must be of God,
who hath not seen meet to allow them grace in that degree to produce that effect.
And what is this but to attribute to God the height of injustice,
to make him require his children to forsake sin,
and yet not to afford them sufficient means for so doing?
Surely this makes God more unrighteous than wicked men, who if, as Christ saith,
"`their children require bread of them, will not give them a stone,
or instead of a fish a serpent.`" But these men confess,
we ought to seek of God power to redeem us from sin,
and yet believe they are never to receive such a power:
such prayers then cannot be in faith, but are all vain.
Is not this to make God as unjust to his children as Pharaoh was to the Israelites,
in requiring brick and not giving them straw?
But blessed be God, he deals not so with those that truly trust in him and wait upon him,
as these men vainly imagine; for such faithful ones find of a truth,
that his grace is sufficient for them,
and know how by his power and Spirit to overcome the evil one.

[.small-break]
'''

// lint-disable invalid-characters "§"
§V. Thirdly,
This evil doctrine is highly injurious to Jesus Christ and
greatly derogates from the power and virtue of his sacrifice,
and renders his coming and ministry, as to the great end of it, ineffectual.
For Christ (as for other ends) so principally he appeared for the removing of sin,
for gathering a righteous generation that might serve the
Lord in purity of mind and walk before him in fear,
and to bring in everlasting righteousness and that
evangelic perfection which the Law could not do.
Hence he is said (Tit. 2:14) "`to have given himself for us that he might
redeem us from all iniquity and purify unto himself a peculiar people,
zealous of good works.`" This is certainly spoken of the saints while upon earth.
But contrary thereunto,
these men affirm that we __are never redeemed from all iniquity,__
and so make Christ`'s giving of himself for us void and ineffectual
and give the apostle Paul the lie plainly,
by denying that "`Christ purifieth to himself a peculiar people,
zealous of good works.`" How are they zealous of good
works who are ever committing evil ones?
How are they a purified people that are still in impurity, as are they that daily sin,
unless sin be accounted no impurity?
Moreover,
it is said expressly (1 John 3:5,8) that "`for this purpose the Son of God was manifested,
that he might destroy the works of the devil,
and ye know that he was manifested to take away our
sins.`" But these men make this purpose of none effect,
for they will not have the Son of God to destroy
the works of the devil in his children in this world.
Neither will they at all believe that he was manifest to take away our sins,
seeing they plead a necessity of always living in them.
And lest any should wrest this place of the apostle as if
it were spoken only of taking away the guilt of sin,
as if it related not to this life, the apostle,
as of purpose to obviate such an objection, adds in the following verses,
"`Whosoever abideth in him sinneth not,`" etc. I hope then they sin not daily in thought,
word and deed.
"`Let no man deceive you, he that doth righteousness is righteous,
even as he is righteous;
he that committeth sin is of the devil.`" But he that sinneth daily in thought,
word and deed, committeth sin.
How comes such a one then to be the child of God?
And if Christ was manifest to take away sin,
how strangely do they overturn the doctrine of Christ,
that deny that it is ever taken away here?
And how injurious are they to the efficacy and power of Christ`'s appearance?
Came not Christ to gather a people out of sin into righteousness;
out from the kingdom of Satan into the kingdom of the dear Son of God?
and are not they that are thus gathered by him his servants, his children, his brethren,
his friends?
Who "`as he was, so are they to be in this world,`" holy, pure, and undefiled.
And doth not Christ still watch over them, stand by them, pray for them,
preserve them by his Power and Spirit, walk in them and dwell among them;
even as the devil, on the other hand, doth among the reprobate ones?
How comes it then that the servants of Christ are
less his servants than the devil`'s are his?
Or is he unwilling to have his servants thoroughly pure?
which were gross blasphemy to assert, contrary to many scriptures.
Or is Christ not able by his power to preserve
and enable his children to serve him?
Which were no less blasphemous to affirm of him,
concerning whom the Scriptures declare that he has "`overcome sin, death,
hell and the grave,`" and triumphed over them openly,
and that all power in heaven and earth is given to him.
But certainly, if the saints sin daily in thought, word and deed, as these men assert,
they serve the devil daily, and are subject to his power,
and so he prevails more than Christ doth and holds the servants of Christ in bondage,
whether Christ will or not.
But how greatly then doth it contradict the end of Christ`'s coming?
as it is expressed by the apostle (Eph. 5:25-27),
"`Even as Christ also loved the church and gave himself for it:
that he might sanctify and cleanse it with the washing of water by the Word:
that he might present it to himself a glorious church,
not having spot or wrinkle or any such thing,
but that it should be holy and without blemish.`" Now,
if Christ hath really thus answered the thing he came for,
then the members of this church are not always sinning in thought, word and deed.
Or there is no difference betwixt being sanctified and unsanctified, clean and unclean,
holy and unholy, being daily blemished with sin, and being without blemish.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VI. Fourthly, this doctrine renders the work of the ministry,
the preaching of the Word, the writing of the Scriptures,
and the prayers of holy men altogether useless and ineffectual.
As to the first (Eph. 4:11-13),
pastors and teachers are said to be "`given for the perfection of the saints,`" etc.,
"`til we all come in the unity of the faith and of the knowledge of the Son of God,
unto a perfect man, unto the measure of the stature of the fullness of Christ.`" Now,
if there be a necessity of sinning daily and in all things,
then there can be no perfection.
For such as do so cannot be esteemed perfect.
And if,
for effectuating this perfection in the saints the
ministry be appointed and disposed of God,
do not such as deny the possibility hereof, render the ministry useless and of no profit?
seeing there can be no other true use assigned but to lead people out of sin into righteousness.
If so be these ministers assure us that we need never expect to be delivered from it,
do not they render their own work needless?
What needs preaching against sin, for the reproving of which all preaching is,
if it can never be forsaken?
Our adversaries are exalters of the Scriptures in words,
much crying up their usefulness and perfection.
Now the apostle tells us (2 Tim. 3:17) that the "`Scriptures are for making
the man of God perfect.`" And if this be denied to be attainable in this life,
then the Scriptures are of no profit,
for in the other life we shall not have use for them.
It renders the prayers of the saints altogether useless,
seeing themselves do confess they ought to pray daily that God would deliver
them from evil and free them from sin by the help of his Spirit and Grace,
while in this world.
But though we might suppose this absurdity to follow,
that their prayers are without faith,
yet were not that so much if it did not infer the like upon the holy apostles,
who prayed earnestly for this end and therefore (no
doubt) believed it attainable (Col. 4:12),
"`Labouring fervently for you in prayers that ye may
stand perfect,`" etc. (1 Thess. 3:13;
and 5:23, etc..

[.small-break]
'''

// lint-disable invalid-characters "§"
§VII.
But fifthly, this doctrine is contrary to common reason and sense.
For the two opposite principles, whereof the one rules in the children of _darkness,_
the other in the children of _Light,_ are _sin_ and _righteousness._
And as they are respectively leavened and acted by them,
so they are accounted either as reprobated or justified:
seeing it is "`abomination in the sight of God either
to justify the wicked or condemn the just.`"^
footnote:[Prov. 17:15.]
Now to say that men cannot be so leavened with the one as to be delivered from the other,
is, in plain words, to affirm that sin and righteousness are consistent,
and that a man may be truly termed righteous,
though he be daily sinning in everything he doth.
And then what difference betwixt good and evil?
Is not this to fall into that great abomination of
"`putting light for darkness,`" and "`calling good evil,
and evil good`"? Since they say the very best actions
of God`'s children are defiled and polluted,
and that those that sin daily in thought, word and deed are good men and women,
the saints and holy servants of the holy pure God.
Can there be anything more repugnant than this to common reason?
Since the subject is still denominated from that accident that doth most influence it,
as a wall is called white when there is much whiteness,
and black when there is much blackness, and suchlike.
But when there is more unrighteousness in a man than righteousness,
that man ought rather to be denominated unrighteous than righteous.
Then surely, if every man sin daily in thought, word and deed,
and that in his sins there is no righteousness at all,
and that all his righteous actions are polluted and mixed with sin,
then there is in every man more unrighteousness than righteousness;
and so no man ought to be called righteous,
no man can be said to be sanctified or washed.
Where are then the children of God?
Where are the purified ones?
Where are they who were sometimes unholy, but now holy?
that "`sometimes were darkness,
but now are light in the Lord`"? There can none such be found then at this rate,
except that unrighteousness be esteemed so.
And is not this to fall into that abomination above mentioned of justifying the ungodly?
This certainly lands in that horrid blasphemy of the Ranters,
that affirm there is no difference betwixt good and evil,
and that all is one in the sight of God.
I could show many more gross absurdities, evil consequences,
and manifest contradictions implied in this sinful doctrine;
but this may suffice at present, by which also, in a good measure,
the probation of the Truth we affirm is advanced.
Yet nevertheless, for the further evidencing of it,
I shall proceed to the second thing proposed by me, to wit,
to prove this from several testimonies of the holy Scriptures.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VIII.
And first,
I prove it from the peremptory positive command of Christ and his apostles,
seeing this is a maxim engraven in every man`'s heart naturally,
that no man is bound to that which is impossible:
since then Christ and his apostles have commanded us to keep all the commandments,
and to be perfect in this respect, it is possible for us so to do.
Now that this is thus commanded without any commentary or consequence,
is evidently apparent from these plain testimonies: Matt. 5:48 and 7:21;
John 13:17; 1 Cor. 7:19; 2 Cor. 13:11; 1 John 2:3-6,
and 3:2-10. These scriptures intimate a positive command for it,
they declare the absolute necessity of it, and therefore,
as if they had purposely been written to answer the objections of our opposers,
they show the folly of those that will esteem themselves children or friends of God,
while they do otherwise.

Secondly,
it is possible because we receive the Gospel and law thereof for that effect,
and it is expressly promised to us as we are under grace, as appears by these scriptures:
Rom. 6:14: "`Sin shall not have dominion over you;
for ye are not under the Law but under Grace`"; and Rom. 8:3:
"`For what the Law could not do in that it was weak through the flesh,
God sending his own Son,`" etc.,
"`that the righteousness of the law might be fulfilled in
us,`" etc. For if this were not a condition both requisite,
necessary and attainable under the Gospel,
there were no difference betwixt the bringing in of a better hope and the Law,
which made nothing perfect, neither betwixt those which are under the Gospel, or who,
under the Law, enjoyed and walked in the life of the Gospel and mere legalists:
whereas the apostle, throughout the whole sixth to the Romans,
argues not only the possibility but the necessity of being free from sin
from their being under the Gospel and under Grace and not under the Law,
and therefore states himself and those to whom he wrote in that condition in these verses,
2-7;
and therefore in the 11-13 and 16-18 verses he argues both the possibility and necessity
of this freedom from sin almost in the same manner we did a little before:
and in the 22nd he declares them in measure to have attained this condition,
in these words, "`But now being made free from sin and become servants to God,
ye have your fruit unto holiness,
and the end everlasting life.`" And as this perfection or freedom from sin is attained
and made possible where the Gospel and inward law of the Spirit is received and known,
so the ignorance hereof has been and is an occasion of opposing this Truth.
For man not minding the _Light_ and __Law^
footnote:[Later editors replace "`Light and Law`" with "`Light or Law.`"]
within his heart,__ which not only discovers sin but leads out of it,
and so being a stranger to the new Life and Birth that is born of God,
which naturally doeth his will and can not of its
own nature transgress the commandments of God,
doth, I say, in his natural state, look at the commandments as they are without him,
in the letter,
and finding himself reproved and convicted is by the letter killed but not made alive.
So man finding himself wounded and not applying himself inwardly to that which can heal,
labours in his own will after a conformity to the Law as it is without him,
which he can never obtain but finds, the more he wrestles,
the more he falleth short.
So this is the Jew still, in effect, with his carnal commandment, with the law without,
in the first covenant state which "`makes not the comers thereunto
perfect as pertaining to the conscience`" (Heb. 9:9):
though they may have here a notion of Christianity and an external faith in Christ.
This hath made them strain and wrest the Scriptures for an __imputative righteousness,__
wholly without them, to cover their impurities,
and this hath made them imagine an acceptance with God possible
though they suppose it impossible ever to obey Christ`'s commands.
But alas!
O deceived souls! that will not avail in the day wherein
"`God will judge every man according to his works,
whether good or bad.`" It will not save thee to say
it was necessary for thee to sin daily in thought,
word and deed; for such as do so have certainly obeyed unrighteousness.
And what is provided for such but tribulation and anguish, indignation and wrath,
even as glory, honor and peace,
immortality and eternal life to such as have done good and patiently continued in well-doing.
So then, if thou desirest to know this perfection and freedom from sin possible for thee,
turn thy mind to the Light and spiritual law of Christ
in the heart and suffer the reproofs thereof,
bear the judgment and indignation of God upon the
unrighteous part in thee as therein it is revealed;
which Christ hath made tolerable for thee;
and so suffer "`judgment`" in thee to be "`brought forth into victory,`" and thus come to
partake of the fellowship of Christ`'s sufferings and be made conformable unto his death,
that thou mayest feel thyself crucified with him
to the world by the power of his cross in thee,
so that that life that sometimes was alive in thee to this
world and the love and lusts thereof may die,
and a new life be raised by which thou mayest live
henceforward to God and not to or for thyself;
and with the apostle thou mayest say (Gal. 2:20):
"`It is no more I but Christ alive^
footnote:[Later editors replace "`alive`" with "`liveth.`"]
in me`"; and then thou wilt be a Christian indeed, and not in name only, as too many are:
then thou wilt know what it is to have "`put off the old
man with his deeds,`" who indeed sins daily in thought,
word, and deed; and to have "`put on the new man, that is renewed in holiness,
after the image of him that hath created him`" (Eph. 4:24):
and thou wilt witness thyself to be God`'s
workmanship created in Christ Jesus unto good works,
and so not to sin always.
And to this new man "`Christ`'s yoke is easy, and his burden is light`";^
footnote:[Matt. 11:30; 2 John 5:3.]
though it be heavy to the old Adam; yea,
the commandments of God are not unto this man grievous;
for it is his meat and drink to be found fulfilling the will of God.

Lastly, this perfection or freedom from sin is possible, because many have attained it,
according to the express testimony of the Scripture.
Some before the Law, and some under the Law,
through witnessing and partaking of the benefit and effect of the Gospel,
and much more many under the Gospel.
As first,
it is written of Enoch (Gen. 5:22-24) that he
"`walked with God,`" which no man while sinning can,
nor doth the Scripture record any failing of his.
It is said of Noah (Gen. 6:9) and of Job (1:8),
and of Zacharias and Elizabeth (Luke 1:6), that they were perfect.
But under the Gospel, besides that of the Romans above mentioned,
see what the apostle saith of many saints in general (Eph. 2:4-6): "`But God,
who is rich in mercy, for his great love wherewith be hath loved us,
even when we were dead in sins,
hath quickened us together with Christ (by grace ye are saved) and hath raised us up
together and made us sit together in heavenly places in Christ Jesus,`" etc. I judge,
while they were sitting in these heavenly places,
they could not be daily sinning in thought, word and deed,
neither were all their works which they did there as filthy rags or a menstruous garment.
See what is further said to the Hebrews (12:22-23),
"`Spirits of just men made perfect.`" And to conclude,
let that of the Revelation 14:1-5 be considered.
Where, though their being found without fault be spoken in the present time,
yet is it not without respect to their innocency while upon earth,
and their being "`redeemed from among men,
and no guile found in their mouth,`" is expressly mentioned in the time past.
But I shall proceed now, in the third place,
to answer the objections which indeed are the arguments of our opposers.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IX. _Obj._
I shall begin with their chief and great argument,
which is the words of the apostle (1 John 1:8): "`If we say that we have no sin,
we deceive ourselves, and the Truth is not in us.`" This they think invincible.

_Answ._
But is it not strange to see men so blinded with partiality?
How many scriptures tenfold more plain do they reject,
and yet stick so tenaciously to this, that can receive so many answers?
As first, "`If we say we have no sin,`" etc.,
will not import the apostle himself to be included.
Sometimes the Scripture useth this manner of expression
when the person speaking cannot be included,
which manner of speech the grammarians call metaschematismus.
Thus James (3:9-10), speaking of the tongue, saith, "`Therewith bless we God,
and therewith curse we men`"; adding, "`These things ought not so to be`":
who from this will conclude that the apostle was one of those cursers?
But secondly, this objection hitteth not the matter; he saith not,
we sin daily in thought, word, and deed;
far less that the very good works which God works in us by his Spirit are sin,
yea the very next verse clearly shows that upon confession
and repentance we are not only forgiven but also cleansed;
"`He is faithful to forgive us our sins,
and to cleanse us from all unrighteousness.`" Here
is both a forgiveness and removing of the guilt,
and a cleansing or removing of the filth;
for to make forgiveness and cleansing to belong both to the removing of the guilt,
as there is no reason for it from the text,
so it were a most violent forcing of the words and would imply a needless tautology.
The apostle having shown how that not the guilt only,
but even the filth also of sin is removed,
subsumes his words in the time past in the 10th verse, "`If we say we have not sinned,
we make him a liar.`" Thirdly,
as Augustine well observed in his exposition upon the epistle to the Galatians,
"`It is one thing not to sin and another thing not to have
sin.`" The apostle`'s words are not "`if we say we sin not,
or commit not sin daily,`" but "`if we say we have no sin.`"
And betwixt these two there is a manifest difference,
for in respect all have sinned, as we freely acknowledge,
all may be said in a sense to have sin.
Again, "`sin`" may be taken for the _seed of sin,_
which may be in those that are redeemed from actual sinning:
but as to the temptations and provocations proceeding from it,
being resisted by the servants of God, and not yielded to,
they are the devil`'s sin that tempteth, not the man`'s that is preserved.
Fourthly, this being considered,
as also how positive and plain once and again the same
apostle is in the very same epistle as in divers places above cited,
is it equal or rational to strain this one place,
presently after so qualified and subsumed in the time past,
to contradict not only other positive expressions of his but the whole tendency
of his epistle and of the rest of the holy commands and precepts of the Scripture?

_Obj._
Secondly, their second objection is from two places of Scripture,
much of one signification: the one is (1 Kings 8:46),
"`For there is no man that sinneth not.`" The other is (Ecc. 7:20),
"`For there is not a just man upon earth, that doeth good, and sinneth not.`"

_Answ._
I answer, first, these affirm nothing of a daily and continual sinning,
so as never to be redeemed from it, but only that all have sinned,
or that there is none that doth not sin, though not always, so as never to cease to sin:
and in this lies the question.
Yea, in that place of the Kings he speaks within two verses of the returning of such "`with
all their souls and hearts`" which implies a possibility of leaving off sin.
Secondly there is a respect to be had to the seasons and dispensations;
for if it should be granted that in Solomon`'s time there was none that sinned not,
it will not follow that there are none such now,
or that it is a thing not now attainable by the grace of God under the Gospel,
for a _non esse ad non posse non valet sequela._
And lastly, this whole objection hangs upon a false interpretation;
// lint-disable invalid-characters
for the Hebrew word ׳חטא
may be read in the potential mood, thus, _There is no man who may not sin,_
as well as in the indicative: so both the old Latin, Junius and Tremellius,
and Vatablus have it; and the same word is so used (Ps. 119:11),
// lint-disable invalid-characters
"`I have hid thy word in my heart, למען לא אחטא־לר׃
that is to say, that I may not sin against thee, in the potential mood,
and not in the indicative as it is in the English;^
footnote:[Later editors drop "`as it is in the English.`"]
which being more answerable to the universal scope of the Scriptures,
the testimony of the Truth and the sense almost of all interpreters,
doubtless ought to be so understood, and the other interpretation rejected as spurious.

_Obj._
Thirdly, they object some expressions of the apostle Paul (Rom. 7:19),
"`For the good that I would I do not; but the evil which I would not,
that I do.`" And (v. 24) "`O wretched man that I am!
who shall deliver me from the body of this death?`"

_Answ._
I answer,
this place infers nothing unless it were apparent that the apostle here
were speaking of his own condition and not rather in the person of others,
or what he himself had sometimes borne, which is frequent in Scripture,
as in the case of cursing in James, before mentioned.
But there is nothing in the text that doth clearly signify the apostle to be
speaking of himself or of a condition he was then under or was always to be under;
yea, on the contrary, in the former chapter, as afore is at large shown,
he declares they were "`dead to sin`";
demanding how such should yet live any longer therein?
Secondly,
it appears that the apostle personated one not yet come
to a spiritual condition in that he saith (v. 14),
"`But I am carnal, sold under sin.`" Now is it to be imagined that the apostle Paul,
as to his own proper condition when he wrote that epistle, was a carnal man,
who in chapter 1 testifies of himself that he was "`separated to be an apostle,
capable to impart to the Romans spiritual gifts`"? and (8:2) that "`the law of the Spirit
of Life in Christ Jesus`" had "`made him free from the law of sin and death`";
so then he was not carnal.
And seeing there are spiritual men in this life, as our adversaries will not deny,
and is intimated through the whole 8th chapter to the Romans,
it will not be denied but the apostle was one of them.
So then as his calling himself "`carnal`" in chapter
7 can not be understood of his own proper state,
neither can the rest of what he speaks there of that kind be so understood; yea,
after (v. 24), where he makes that exclamation, he adds in the next verse, "`I thank God,
through Jesus Christ our Lord`"; signifying that by him he witnessed deliverance,
and so goeth on, showing how he had obtained it, in the next chapter, viz. 8:35,
"`Who shall separate us from the love of Christ?`" And (v. 37),
"`But in all these things we are more than conquerors`"; and in the last verse,
"`Nothing shall be able to separate us,`" etc. But wherever there is a continuing in sin,
there there is a separation, in some degree, seeing every sin is contrary to God, and
// lint-disable invalid-characters
άνομία, i.e., a transgression of the law (1 John 3:4),
and whoever committeth the least sin is overcome of it,
and so in that respect is not a conqueror but conquered.
This condition then,
which the apostle plainly testified he with some others had obtained,
could not consist with continual remaining and abiding in sin.

_Obj._
Fourthly, they object the faults and sins of several eminent saints, as Noah, David, etc.

_Answ._
I answer, that doth not at all prove the case,
for the question is not whether good men may not fall into sin, which is not denied;
but whether it be not possible for them not to sin?
It will not follow, because these men sinned, that therefore they were never free of sin,
but always sinned.
For at this rate of arguing it might be urged, according to this rule,
_Contrariorum par ratio,_ i.e.,
"`the reason of contraries is alike,`" that if because
a good man hath sinned once or twice,
he can never be free from sin, but must always be daily and continually a sinner,
all his life long, then by the rule of contraries,
if a wicked man have done good once or twice, he can never be free from righteousness,
but must always be a righteous man all his life time: which,
as it is most absurd in itself,
so it is contrary to the plain testimony of the Scripture (Ezek. 33:12-18).

_Obj._
Lastly, they object, that if perfection or freedom from sin be attainable,
this will render mortification of sin useless,
and make the blood of Christ of no service to us,
neither need we any more pray for forgiveness of sins.

_Answ._
I answer, I had almost omitted this objection because of the manifest absurdity of it,
for can mortification of sin be useless where the end of it is obtained?
seeing there is no attaining of this perfection but by mortification
doth the hope and belief of overcoming render the fight unnecessary?
Let rational men judge which hath most sense in it, to say as our adversaries do,
it is necessary that we fight and wrestle, but we must never think of overcoming.
We must resolve still to be overcome.
Or to say let us fight, because we may overcome.
Whether do such as believe they may be cleansed by it,
or those that believe they can never be cleansed by it,
render the blood of Christ most effectual?
If two men were both grievously diseased and applied themselves to a physician for remedy,
which of those does most commend the physician and his cure:
he that believeth he may be cured by him and as he
feels himself cured confesseth that he is so,
and so can say this is a skillful physician, this is a good medicine, behold!
I am made whole by it?
Or he that never is cured, nor ever believes that he can, so long as he lives?
As for praying for forgiveness, we deny it not,
for that "`all have sinned,`" and therefore all need to pray that their sins past
may be blotted out and that they may be daily preserved from sinning.
And if hoping or believing to be made free from sin
hinders praying for forgiveness of sin,
it would follow by the same inference that men ought not to forsake murder, adultery,
or any of these gross evils,
seeing the more men are sinful the more plentiful occasion
there would be of asking forgiveness of sin,
and the more work for mortification.
But the apostle hath sufficiently refuted such sin-pleasing
cavils in these words (Rom. 6:1-2):
"`Shall we continue in sin that grace may abound?
God forbid.`"

But lastly,
it may be easily answered by a retortion to those
that press this from the words of the Lord`'s Prayer,
"`forgive us our debts,`" that this militates no less against
perfect justification than against perfect sanctification.
For if all the saints, the least as well as the greatest,
be perfectly justified in that very hour wherein they are converted,
as our adversaries will have it, then they have remission of sins long before they die.
May it not then be said to them,
what need have ye to pray for remission of sin who are already justified,
whose sins are long ago forgiven, both past and to come?

[.small-break]
'''

// lint-disable invalid-characters "§"
§X. But this may suffice;
concerning this possibility Jerome speaks clearly enough _(lib. iii., adver. Pelagium),_
"`This we also say that a man may not sin, if he will, for a time and place,
according to his bodily weakness, so long as his mind is intent,
so long as the cords of the zither relax not by any vice,`" and again in the same book,
"`Which is that, that I said, that it is put in our power (to wit,
being helped by the grace of God) either to sin or
not to sin.`" For this was the error of Pelagius,
which we indeed reject and abhor, and which the Fathers deservedly withstood,
"`That man by his natural strength, without the help of God`'s grace,
could attain to that state so as not to sin.`" And Augustine himself,
a great opposer of the Pelagian heresy,
did not deny this possibility as attainable by the help of God`'s grace,
as in his book [.book-title]#de Spiritu et Litera,# _cap. 2_
and his book [.book-title]#de Natura et Gratia# against Pelagius, _cap.
42, 50, 60, and 63,_ [.book-title]#de Gestis Concilii Palaestini,#
_cap. 7 and 11,_
and [.book-title]#de Peccato Originali,# _lib. 2, cap. 11._
Gelasius also, in his disputation against Pelagius, saith,
"`But if any affirm that this may be given to some saints in this life,
not by the power of man`'s strength but by the grace of God,
he doth well to think so confidently and hope it faithfully;
for by this gift of God all things are possible.`" That this was the common
opinion of the Fathers appears from the words of the Aszansic Council,
canon last, "`We believe also this according to the Catholic faith,
that all who are baptized through grace by baptism received,
and Christ helping them and co-working,
may and ought to do whatsoever belongs to salvation if they will faithfully labour.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§XI. Blessed then are they that believe in him,
who is both able and willing to deliver as many as come to him through true repentance,
from all sin, and do not resolve, as these men do,
to be the devil`'s servants all their lifetime, but daily go on forsaking unrighteousness,
and forgetting those things that are behind, "`press forward toward the mark,
for the prize of the high calling of God, in Christ Jesus`";^
footnote:[Phil. 3:14.]
such shall not find their faith and confidence to be in vain,
but in due time shall be made conquerors through him in whom they have believed; and so,
overcoming,
shall be established as "`pillars in the house of
God,`" so as "`they shall go no more out`" (Rev. 3:12).
