== THE NINTH PROPOSITION

[.chapter-subtitle--blurb]
Concerning Perseverance, and the Possibility of Falling from Grace

[.heading-continuation-blurb]
Although this gift and inward grace of God be sufficient to work out salvation,
yet in those in whom it is resisted it both may and doth become their condemnation.
Moreover,
they in whose hearts it hath wrought in part to purify and sanctify them
in order to their further perfection may by disobedience fall from it,
"`turn it to wantonness,`" "`make shipwreck of faith`" (1 Tim. 1:19),
and "`after having tasted the heavenly gift and been made partakers of the Holy Ghost,
again fall away`" (Heb. 6:4-6), yet such an increase and stability in the Truth may,
in this life, be attained, from which there can not be a total apostasy.

// lint-disable invalid-characters "§"
§I. The first sentence of this proposition hath
already been treated of in the Fifth and Sixth Propositions,
where it hath been shown that that _Light_ which is given for life
and salvation becomes the condemnation of those that refuse it,
and therefore is already proved in those places where did demonstrate
the possibility of man`'s resisting the Grace and Spirit of God;
and indeed it is so apparent in the Scriptures that it cannot be
denied by such as will but seriously consider these testimonies:
Prov. 1:24-26; John 3:18-19; 2 Thess. 2:11-12; Acts 7:51, and 13:46; Rom. 1:18.
As for the other part of it,
that they in whom this grace may have wrought in
a good measure in order to purify and sanctify them,
tending to their further perfection, may afterwards through disobedience fall away, etc.,
the testimonies of the Scripture included in the proposition
itself are sufficient to prove it to men of unbiased judgments.
But because as to this part our cause is common with many
other Protestants I shall be the more brief in it.
For it is not my design to do that which is done already,
neither do I covet to appear knowing by writing much;
but simply purpose to present to the world a faithful account of our principles
and briefly to let them understand what we have to say for ourselves.

[.offset]
// lint-disable invalid-characters "§"
§II. From these scriptures then included in the proposition
(not to mention many more which might be urged) I argue thus:

[.syllogism]
* Arg. 1+++.+++ If men may turn the grace of God into wantonness, then they must once have had it:
* But the first is true,
* Therefore also the second.

[.syllogism]
* Arg. 2+++.+++ If men may make shipwreck of faith, they must once have had it, neither could they ever have had true faith without the grace of God.
* But the first is true,
* Therefore also the last.

[.syllogism]
* Arg. 3+++.+++ If men may have tasted of the heavenly gift and been made partakers of the Holy Spirit, and afterwards fall away, they must needs have known in measure the operation of God`'s saving Grace and Spirit, without which no man could taste the heavenly gift, nor yet partake of the Holy Spirit:
* But the first is true,
* Therefore also the last.

Secondly, Seeing the contrary doctrine is built upon this false hypothesis,
that Grace is not given for salvation to any but to a certain elect number,
which cannot lose it, and that all the rest of mankind, by an absolute decree,
are debarred from Grace and salvation; that being destroyed, this falls to the ground.
Now as that doctrine of theirs is wholly inconsistent
with the daily practice of those that preach it,
in that they exhort people to believe and be saved; while in the meantime,
if they belong to the decree of reprobation, it is simply impossible for them so to do,
and, if to the decree of election, it is needless;
seeing it is as impossible to them to miss of it, as hath been before demonstrated:
so also in this matter of perseverance,
their practice and principle are no less inconsistent and contradictory,
for while they daily exhort people to be faithful to the end, showing them,
if they continue not, they shall be cut off, and fall short of the reward:
which is very true, but no less inconsistent with that doctrine,
that affirms there is no hazard,
because no possibility of departing from the least measure of true Grace.
Which if true, it is to no purpose to beseech them to stand,
to whom God hath made it impossible to fall.
I shall not longer insist upon the probation of this,
seeing what is said may suffice to answer my design,
and that the thing is also abundantly proved by many of the same judgment.
That this was the doctrine of the primitive Protestants, thence appears,
that the Augustan confession condemns it as an error of the Anabaptists
to say that they who once are justified cannot lose the Holy Spirit.
Many suchlike sayings are to be found in the common places of Philip Melancthon.
Voss, in his [.book-title]#Pelagian History# (lib.
6), testifies that this was the common opinion of the Fathers;
in the confirmation of the twelfth thesis (page 587) he hath these words: "`That this,
which we have said was the common sentiment of antiquity, those at present can only deny,
who otherways perhaps are men not unlearned,
but nevertheless in antiquity altogether strangers,`" etc. These things thus observed,
I come to the objections of our opposers.

[.small-break]
'''

// lint-disable invalid-characters "§"
§III.
_Obj._ First,
they allege that those places mentioned of "`making shipwreck
of faith,`" are only to be understood of seeming faith,
and not of a real true faith.

_Answ._
This objection is very weak,
and apparently contrary to the text (1 Tim. 1:19),
where the apostle addeth "`to faith a good conscience,`" by way of complaint; whereas,
if their faith had been only seeming and hypocritical,
the men had been better without it than with it,
neither had they been worthy of blame for losing that which in itself was evil.
But the apostle expressly adds "`and of a good conscience,`" which shows it was real,
neither can it be supposed that men could truly attain a
good conscience without the operation of God`'s saving Grace;
far less that a good conscience doth consist with a seeming false and hypocritical faith.
Again, these places of the apostle, being spoken by way of regret,
clearly import that these attainments they had fallen from were good and real,
not false and deceitful, else he would not have regretted their falling from them.
And so he saith positively,
"`They tasted of the heavenly gift and were made partakers of the Holy Ghost,`" etc.,
not that they seemed to be so, which showeth this objection is very frivolous.

_Obj._
Secondly, they allege (Phil. 1:6), "`Being confident of this very thing,
that he which hath begun a good work in you will
perform it until the day of Jesus Christ,`" etc.,
and (1 Pet. 1:5): "`Who are kept by the power of God through faith unto salvation.`"

_Answ._
These scriptures, as they do not affirm anything positively contrary to us,
so they cannot be understood otherwise than as the condition is performed upon our part,
seeing salvation is no otherways proposed there,
but upon certain necessary conditions to be performed by us, as hath been above proved,
and as our adversaries also acknowledge, as (Rom. 8:13):
"`For if ye live after the flesh, ye shall die: but if ye, through the Spirit,
do mortify the deeds of the body, ye shall live.`" And (Heb. 3:14):
"`We are made partakers of Christ,
if we hold the beginning of our confidence steadfast unto the end.`"
For if these places of the Scripture upon which they build their
objection were to be admitted without these conditions,
it would manifestly overturn the whole tenor of their
exhortations throughout all their writings.
Some other objections there are of the same nature, which are solved by the same answers,
which also, because largely treated of by others, I omit,
to come to that testimony of the Truth which is more especially ours in this matter,
and is contained in the latter part of the proposition in these words:
"`Yet such an increase and stability in the Truth may in this life be attained,
from which there cannot be a total apostasy.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§IV. As,
in the explanation of the fifth and sixth propositions I observed that
some that had denied the errors of others concerning reprobation,
and affirmed the universality of Christ`'s death,
did notwithstanding fall short in sufficiently holding forth the Truth,
and so gave the contrary party an occasion by their
defects to be strengthened in their errors:
so it may be said in this case.
As upon the one hand they err who affirm that the least
degree of true and saving grace cannot be fallen from,
so do they err, upon the other hand,
that deny any such stability to be attained from
which there cannot be a total and final apostasy.
And betwixt these two extremes lieth the Truth, apparent in the Scriptures,
which God hath revealed unto us by the testimony of his Spirit,
and which also we are made sensible of by our own experience.
And even as in the former controversy was observed,
so also in this the defence of Truth will readily appear,
to such as seriously weigh the matter: for the arguments upon both hands,
rightly applied, will, as to this, hold good; and the objections, which are strong,
as they are respectively urged against the two opposite false opinions,
are here easily solved by the establishing of this Truth.
For all the arguments which these allege, that affirm there can be no falling away,
may well be received upon the one part,
as of those who have attained to this stability & establishment,
and their objections solved by this confession: so, upon the other hand,
the arguments alleged, from Scripture testimonies,
by those that affirm the possibility of falling away,
may well be received of such as are not come to this establishment,
though having attained a measure of true grace.
Thus then the contrary batterings of our adversaries, who miss the Truth,
do concur the more strongly to establish it, while they are destroying each other.
But lest this may not seem to suffice to satisfy such as
judge it always possible for the best of men,
before they die, to fall away, I shall add, for the proof of it,
some brief considerations from some few testimonies of the Scripture.

[.small-break]
'''

// lint-disable invalid-characters "§"
§V. And first, I freely acknowledge that it is good for all to be humble,
and in this respect not overconfident, so as to lean to this,
to foster themselves in iniquity,
or lie down in security as if they had attained this condition,
seeing watchfulness and diligence is of indispensable necessity to all mortal men,
so long as they breathe in this world:
for God will have this to be the constant practice of a Christian,
that thereby he may be the more fit to serve him,
and better armed against all the daily temptations of the enemy.
For since "`the wages of sin is death,`" there is no man,
while he sinneth and is subject thereunto,
but may lawfully suppose himself capable of perishing.
Hence the apostle Paul himself saith (1 Cor. 9:27): "`But I keep under my body,
and bring it into subjection, lest that by any means, when I have preached to others,
I myself should be a castaway.`" Here the apostle
supposes it possible for him to be a castaway,
and yet it may be judged he was far more advanced in the inward work of regeneration,
when he wrote that epistle,
than many who nowadays too presumptuously suppose they cannot fall away,
because they feel themselves to have attained some small degree of true grace.
But the apostle makes use of this supposition or possibility of his being
a castaway (as I before observed) as an inducement to him to be watchful,
"`I keep under my body, lest,`" etc. Nevertheless the same apostle, at another time,
in the sense and feeling of God`'s holy power, and in the dominion thereof,
finding himself a conqueror therethrough over sin and his soul`'s enemies,
maketh no difficulty to affirm (Rom. 8:38):
"`For I am persuaded that neither death nor life,`" etc.,
which clearly showeth that he had attained a condition,
from which he knew he could not fall away.

But secondly, it appears such a condition is attainable because we are exhorted to it,
and, as hath been proved before, the Scripture never proposeth to us things impossible.
Such an exhortation we have from the apostle (2 Pet. 1:10): "`Wherefore the rather,
brethren, give diligence to make your calling and election sure.`"^
footnote:[Later editors complete the 2 Peter quote
with "`for if ye do these things ye shall never fall.`"]
And though there be a condition here proposed,
yet since we have already proved that it is possible to fulfill this condition,
then also the promise annexed thereunto may be attained.
And since, where assurance is wanting,
there is still a place left for doubtings and despairs,
if we should affirm it never attainable,
then should there never be a place known by the saints in this world,
wherein they might be free of doubting and despair: which,
as it is most absurd in itself,
so it is contrary to the manifest experience of thousands.

Thirdly, God hath given to many of his saints and children,
and is ready to give unto all, a full and certain assurance that they are his,
and that no power shall be able to pluck them out of his hand.
But this assurance would be no assurance, if those,
who are so assured were not established and confirmed beyond all doubt and hesitation.
If so, then surely there is no possibility for such to miss of that,
which God hath assured them of.
And that there is such assurance attainable in this life,
the Scripture abundantly declareth, both in general, and as to particular persons.
As first (Rev. 3:12):
"`Him that overcometh will I make a pillar in the temple of my God,
and he shall go no more out,`" etc., which containeth a general promise unto all.
Hence the apostle speaks of some that are sealed (2 Cor. 1:22):
"`Who hath also sealed us, and given the earnest of the Spirit in our hearts`":
wherefore the Spirit so sealing is called the earnest
or "`pledge of our inheritance`" (Eph. 1:13),
"`In whom ye were sealed with that Holy Spirit of
promise.`" And therefore the apostle Paul,
not only in that of the Romans above noted,
declareth himself to have attained that condition,
but (2 Tim. 4:7) he affirmeth in these words, "`I have fought a good fight,`" etc.,
which also many good men have, and do witness.
And therefore,
as there can be nothing more manifest than that which
the manifest experience of this time showeth,
and therein is found agreeable to the experience of former times,
so we see there have been both of old, and of late,
that have turned the grace of God into wantonness,
that have fallen from their faith and integrity,
thence we may safely conclude such a falling away possible.
We also see that some of old and of late have attained a certain assurance,
some time before they departed, that they should inherit eternal life,
and have accordingly died in that good hope.
Of and concerning whom the Spirit of God testified that they are saved.
Wherefore we also see such a state is attainable in this life,
from which there is not a falling away.
For seeing the Spirit of God did so testify, it was not possible that they should perish,
concerning whom _he who cannot lie_ thus bare witness.
