== THE TENTH PROPOSITION

[.chapter-subtitle--blurb]
Concerning the Ministry

[.heading-continuation-blurb]
As by the Light or gift of God all true knowledge
in things spiritual is received and revealed,
so by the same, as it is manifested and received in the heart,
by the strength and power thereof every true minister of the Gospel is ordained,
prepared and supplied in the work of the ministry, and by the leading,
moving and drawing hereof,
ought every evangelist and Christian pastor to be
led and ordered in his labour and work of the Gospel,
both as to the place where, as to the persons to whom,
and as to the time wherein he is to minister.
Moreover, who have this authority may and ought to preach the Gospel,
though without human commission or literature, as, on the other hand,
who want the authority of this divine gift,
however learned or authorized by the commission of men and churches,
are to be esteemed but as deceivers and not true ministers of the Gospel.
Also, they who have received this holy and unspotted gift,
as they have freely received it, so are they freely to give it^
footnote:[Matt. 10:8.]
without hire or bargaining, far less to use it as a trade to get money by;
yet if God hath called anyone from their employment
or trades by which they acquire their livelihood,
it may be lawful for such,
according to the liberty which they feel given them in the Lord,
to receive such temporals (to wit,
what may be needful for them for meat and clothing) as are given them
freely and cordially by those to whom they have communicated spirituals.

[.small-break]
'''

// lint-disable invalid-characters "§"
§I. Hitherto I have treated of those things,
which relate to the Christian faith, and Christians,
as they stand each in his private and particular condition,
and how and what way every man may be a Christian indeed, and so abide.
Now I come in order to speak of those things that relate to Christians
as they are stated in a joint fellowship and communion,
and come under a visible and outward society,
which society is called the "`Church of God,`" and in Scripture compared to a body,
and therefore named the Body of Christ.
As then in the natural body there be divers members,
all concurring to the common end of preserving and confirming the whole body;
so in this spiritual and mystical body there are also divers
according to the different measures of Grace,
and of the Spirit diversely administered unto each member;
and from this diversity ariseth that distinction
of persons in the visible society of Christians,
as of apostles, pastors, evangelists, ministers,
etc. That which in this proposition is proposed,
is what makes or constitutes any a minister of the Church,
what his qualifications ought to be, and how he ought to behave himself.
But because it may seem somewhat preposterous to
speak of the distinct offices of the Church,
until something be said of the Church in general,
though nothing positively be said of it in the proposition, yet, as here implied,
I shall briefly premise something thereof and then
proceed to the particular members of it.

[.small-break]
'''

// lint-disable invalid-characters "§"
§II. It is not in the least my design to meddle with those
tedious and many controversies wherewith the Papists and Protestants
do tear one another concerning this thing,
but only, according to the Truth manifested to me,
and revealed _in_ me by the testimony of the Spirit,
according to that proportion of wisdom given me,
briefly to hold forth as a necessary introduction both to
this matter of the ministry and of worship which followeth,
those things which I, together with my brethren, do believe concerning the Church.

The "`Church`" then,
according to the grammatical signification of the word as it is used in the holy Scripture,
signifies an _assembly_ or _gathering_ of _many_ into one place; for the substantive
// lint-disable invalid-characters
ἐκκλησία comes from the word ἐκκαλέω, "`I call out of,`" and originally from
// lint-disable invalid-characters
καλέω, "`I call,`" and indeed as this is the grammatical sense of the word
so also it is the real and proper signification of the thing,
the Church being no other thing but the society, gathering,
or company of such as God hath called out of the world and worldly spirit,
to walk in his Light and Life.
The church then so designed is to be considered as it comprehends
all that are thus called and gathered truly by God,
both such as are yet in this inferior world and such as having already
laid down the earthly tabernacle are passed into their heavenly mansions,
which together do make up the One catholic Church (concerning which there is so much
controversy) out of which Church we freely acknowledge there can be no salvation,
because under this church and its denomination are comprehended all, and as many,
of whatsoever nation, kindred,
tongue or people they be (though outwardly strangers and remote from those who
profess Christ and Christianity in words and have the benefit of the Scriptures),
as become obedient to the holy Light and testimony of God in their hearts,
so as to become sanctified by it and cleansed from the evils of their ways.
For this is the universal or catholic Spirit by which many are called
"`from all the four corners of the earth and shall sit down with Abraham,
Isaac,
and Jacob.`" By this the secret life and virtue of
Jesus is conveyed into many that are afar off,
even as by the blood that runs into the veins and arteries of the natural body,
the life is conveyed from the head and heart unto the extremest parts.
There may be members therefore of this catholic Church both among Heathen, Turks, Jews,
and all the several sorts of Christians,
men and women of integrity and simplicity of heart,
who though blinded in something in their understanding and perhaps burdened with
the superstitions and formality of the several sects in which they are engrossed,
yet being upright in their hearts before the Lord,
chiefly aiming and labouring to be delivered from iniquity and loving to follow righteousness,
are by the secret touches of this holy Light in their souls enlivened and quickened,
thereby secretly united to God,
and therethrough become true members of this catholic Church.
Now the Church, in this respect, hath been in being in all generations;
for God never wanted some such witnesses for him,
though many times slighted and not much observed by this world.
And therefore this Church, though still in being,
hath been oftentimes as it were invisible,
in that it hath not come under the observation of the men of this world, being,
as saith the Scripture (Jer. 3:14), "`one of a city, and two of a family.`" And yet,
though the Church thus considered may be, as it were, hid from wicked men,
as not then gathered into a visible fellowship,
yea and not observed even by some that are members of it,
yet may there notwithstanding many belong to it;
as when Elias complained he was left alone (1 Kings 19:18), God answered unto him,
"`I have reserved to myself seven thousand men who have not bowed
their knees to the image of Baal,`" whence the apostle argues (Rom.
11) the being of a remnant in his day.

[.small-break]
'''

// lint-disable invalid-characters "§"
§III.
Secondly the Church is to be considered as it signifies
a certain number of persons gathered by God`'s Spirit,
and by the testimony of some of his servants raised up for that end,
unto the belief of the true principles and doctrines of the Christian faith,
who through their hearts being united by the same love,
and their understandings informed in the same truths, gather, meet,
and assemble together to wait upon God, to worship him,
and to bear a joint testimony for the Truth against error; suffering for the same;
and so becoming through this fellowship as one family and household in certain respects,
do each of them watch over, teach, instruct and care for one another,
according to their several measures and attainments.
Such were the churches of the primitive times gathered by the apostles,
whereof we have divers mentioned in the Holy Scriptures.
And as to the visibility of the Church in this respect,
there hath been a great interruption since the apostles`' days, by reason of the apostasy,
as will hereafter appear.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IV. To be a member then of the catholic Church,
there is need of the _inward calling of God_ by his Light in the heart,
and a being leavened into the nature and spirit of it,
so as to forsake unrighteousness and be turned to righteousness, and,
in the inwardness of the mind,
to be cut out of the wild olive tree of our own first fallen nature
and ingrafted into Christ by his Word and Spirit in the heart.
And this may be done in those who are strangers to the history
(God not having pleased to make them partakers thereof) as in the
fifth and sixth propositions hath already been proved.

To be a member of a particular church of Christ,
as this inward work is indispensably necessary, so is also the outward profession of,
and belief in Jesus Christ and those holy truths delivered by his Spirit in the Scriptures,
seeing the testimony of the Spirit recorded in the Scriptures
doth answer the testimony of the same Spirit in the heart,
even as "`face answereth face in a glass.`" Hence it follows that
the inward work of holiness and forsaking iniquity is necessary,
in every respect, to the being a member in the Church of Christ;
and that the outward profession is necessary to be
a member of a particular gathered church,
but not to the being a member of the catholic Church;
yet it is absolutely necessary where God affords the opportunity of knowing it:
the outward testimony is to be believed where it is presented and revealed;
the sum whereof hath upon other occasions been already proved.

[.small-break]
'''

// lint-disable invalid-characters "§"
§V. But contrary hereunto the devil,
that worketh and hath wrought in the "`mystery of iniquity,`"
hath taught his followers to affirm that no man,
however holy,
is a member of the Church of Christ without the outward profession
and that he be initiated thereunto by some outward ceremonies.
And again that men who have this outward profession, though inwardly unholy,
may be members of the true Church of Christ, yea and ought to be so esteemed.
This is plainly to put "`light for darkness and darkness for light`";
as if God had a greater regard to words than actions and
were more pleased with vain professions than with real holiness;
but these things I have sufficiently refuted heretofore.
Only from hence let it be observed that upon this false and rotten
foundation Antichrist hath built his Babylonish structure,
and the Antichristian church in the apostasy hath hereby reared
herself up to that height and grandeur she hath attained,
so as to exalt herself "`above all that is called God, and sit in the temple of God,
as God.`"

For the particular churches of Christ gathered in the apostles`' days,
soon after beginning to decay as to the inward Life,
came to be overgrown with several errors,
and the hearts of the professors of Christianity to be leavened
with the old spirit and conversation of the world.
Yet it pleased God for some centuries to preserve that life in many,
whom he emboldened with zeal to stand and suffer for his Name through the ten persecutions.
But these being over, the meekness, gentleness, love, long-suffering, goodness,
and temperance of Christianity began to be lost.
For after that the princes of the earth came to take upon them that profession,
and that it ceased to be a reproach to be a Christian but rather became a means to preferment,
men became such by birth and education, and not by conversion and renovation of spirit:
then there was none so vile, none so wicked, none so profane,
who became not a member of the church.
And the teachers and pastors thereof becoming the companions of princes,
and so being enriched by their benevolence and getting vast treasures and estates,
became puffed up and, as it were, drunken with the vain pomp and glory of this world,
and so marshaled themselves in manifold orders and degrees,
not without innumerable contests and altercations who should have the precedency.^
footnote:[As was betwixt the bishop of Rome, and the bishop of Constantinople.]
So the virtue, life, substance, and kernel of the Christian religion came to be lost,
and nothing remained but a shadow and image,
which dead image or carcass of Christianity (to make it take the better with
the superstitious multitude of heathens that became engrossed in it,
not by any inward conversion of their hearts or by becoming less wicked or superstitious,
but by a little change in the object of their superstition),
not having the inward ornament and life of the Spirit,
became decked with many outward and visible orders, and beautified with the gold, silver,
precious stones and the other splendid ornaments of this perishing world;
so that this was no more to be accounted the Christian religion and Christian Church,
notwithstanding the outward profession,
than the dead body of a man is to be accounted a living man, which,
however cunningly embalmed, and adorned with ever so much gold or silver,
or most precious stones, or sweet ointments, is but a dead body still, without sense,
life, or motion.
For that _apostate_ Church of _Rome_ has introduced no less ceremonies and superstitions
into the Christian profession than was either among Jews or heathens;
and that there is and hath been as much, yea and more pride, covetousness,
unclean lust,^
footnote:[Later editors substitute "`uncleanness`" for "`unclean lust.`"]
luxury, fornication, profanity and atheism among her teachers and chief bishops,
as ever was among any sort of people, none need doubt that have read their own authors,
to wit Platina and others.

Now though Protestants have reformed from her in some of the most
gross points and absurd doctrines relating to the church and ministry,
yet (which is to be regretted) they have but lopped the branches but retain
and plead earnestly for the same root from which these abuses have sprung,
so that even among them, though all that mass of superstition, ceremonies,
and orders be not again established, yet the same pride,
covetousness and sensuality is found to have overspread
and leavened their churches and ministry;
and the life, power and virtue of true religion is lost among them;
and the very same death, barrenness,
dryness and emptiness is found in their ministry,
so that in effect they differ from Papists but in form and some ceremonies,
being with them apostatized from the life and power
the true primitive Church and her pastors were in,
so that of both it may be said truly (without breach of charity) that having only a
form of godliness (and many of them not so much as that) they are deniers of,
yea enemies to, the power of it.
And this proceeds not simply from their not walking answerably to their own principles,
and so degenerating that way (which also is true), but which is worse,
their setting down to themselves and adhering to certain principles which naturally,
as a cursed root, bring forth these bitter fruits:
these therefore shall afterwards be examined and refuted,
as the contrary positions of Truth in the Proposition are explained and proved.

For as to the nature and constitution of a church (abstract
from their disputes concerning its constant visibility,
infallibility, and the primacy of the Church of Rome) the Protestants,
as in practice so in principles, differ not from Papists,
for they engross within the compass of their church whole nations,
making their infants members of it by sprinkling a little water upon them,
so that there is none so wicked or profane who is not a fellow member,
no evidence of holiness being required to constitute a member of the church;
and look through the Protestant nations and there will no difference appear
in the lives of the generality of the one more than of the other;
but he who "`ruleth in the children of disobedience`" reigning in both,
so that the reformation, through this defect,
is but in holding some less gross errors in the notion,
but not in having the heart reformed and renewed,
in which mainly the life of Christianity consisteth.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VI. But the Popish errors concerning the ministry
which they have retained are most of all to be regretted,
by which chiefly the life and power of Christianity is barred out among them,
and they kept in death, barrenness and dryness:
there being nothing more hurtful than an error in this respect,
for where a false and corrupt ministry entereth,
all manner of other evils follow upon it, according to that Scripture adage,
"`Like people, like priest.`"^
footnote:[Hos. 4:9.]
For by their influence,
instead of ministering life and righteousness, they minister death and iniquity.
The whole backslidings of the Jewish congregations of old is hereto ascribed:
"`The leaders of my people have caused them to err.`" The
whole writings of the prophets are full of such complaints;
and for this cause, under the New Testament,
we are so often warned and guarded to "`beware of false prophets
and false teachers,`" etc. What may be thought then,
where all, as to this, is out of order, where both the foundation, call, qualifications,
maintenance, and whole discipline are different from,
and opposite to the ministry of the primitive Church,
yea and necessarily tend to the shutting out of a _spiritual ministry,_
and the bringing in and establishing of a carnal?
This shall appear by parts.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VII.
_Quest._
That then, which comes first to be questioned in this matter,
is concerning _the call of a minister;_ to wit, what maketh,
or how cometh a man to be a minister, pastor, or teacher in the church of Christ?

_Answ._
We answer, by the _inward power_ and _virtue_ of the _Spirit of God._
For, as saith our proposition,
having received the true knowledge of things spiritual by the Spirit of God (without
which they cannot be known) and being by the same in measure purified and sanctified,
he comes thereby to be called and moved to minister to others,
being able to speak from a living experience of what he himself is a witness;
and therefore knowing the terror of the Lord, he is fit to persuade men,
etc. (2 Cor. 5:11), and his words and ministry,
proceeding from the inward power and virtue,
reaches to the heart of his hearers and makes them
approve of him and be subject unto him.
Our adversaries are forced to confess that this were indeed desirable and best,
but this they will not have to be absolutely necessary.
I shall first prove the necessity of it,
and then show how much they err in that which they make
more necessary than this divine and heavenly call.

_Arg._
First; that which is necessary to make a man a Christian,
so as without it he cannot be truly one,
must be much more necessary to make a man a minister of Christianity,
seeing the one is a degree above the other, and has it included in it,
nothing less than he, that supposeth a master,
supposeth him first to have attained the knowledge and capacity of a scholar.
They that are not Christians cannot be teachers and ministers among Christians:

But this inward call, power and virtue of the Spirit of God,
is necessary to make a man a Christian;
as we have abundantly proved before in the second proposition,
according to these scriptures: "`He that hath not the Spirit of Christ,
is none of his.`" "`As many as are led by the Spirit of God, are the Sons of God`":

Therefore this call, moving, and drawing of the Spirit,
must be much more necessary to make a minister.

Secondly, all ministers of the New Testament ought to be ministers of the Spirit,
and not of the letter, according to that of 2 Cor. 3:6, and as the old Latin hath it,
"`Not by the letter, but by the Spirit.`" But how can a man be a minister of the Spirit,
who is not inwardly called by it,
and who looks not upon the operation and testimony
of the Spirit as essential to his call?
As he could not be a minister of the letter who had thence no ground for his call, yea,
who was altogether a stranger to and unacquainted with it,
so neither can he be a minister of the Spirit who is a stranger to it,
and unacquainted with the motions thereof, and knows it not to draw, act, and move him,
and go before him in the work of the ministry.
I would willingly know, how those,
that take upon them to be ministers (as they suppose) of the Gospel,
merely from an outward vocation,
without so much as being any ways sensible of the
work of the Spirit or any inward call therefrom,
can either satisfy themselves or others that they are ministers of the Spirit,
or wherein they differ from the ministers of the letter?
For

Thirdly;
if this inward call or testimony of the Spirit were
not essential and necessary to a minister,
then the ministry of the New Testament should not only be no ways preferable to,
but in divers respects far worse than that of the Law:
for under the Law there was a certain tribe allotted for the ministry,
and of that tribe certain families set apart for the priesthood
and other offices by the immediate command of God to Moses,
so that the people needed not be in any doubt who
should be priests and ministers of the holy things:
yea and besides this, God called forth, by the immediate testimony of his Spirit,
severals, at divers times, to teach, instruct, and reprove his people, as Samuel, Nathan,
Elias, Elisha, Jeremiah, Amos, and many more of the prophets:
but now under the New Covenant, where the ministry ought to be more spiritual,
the way more certain, and the access more easy unto the Lord, our adversaries,
by denying the necessity of this inward and spiritual vocation, make it quite otherways;
for there being now no certain family or tribe to which the ministry is limited,
we are left in uncertainty to choose and have pastors at a venture,
without all certain assent of the will of God;
having neither an outward rule nor certainty, in this affair, to walk by;
for that the Scripture cannot give any certain rule in this matter, hath,
in the third proposition concerning it been already shown.

Fourthly;
Christ proclaims them all "`thieves and robbers,`"
that "`enter not by him the door into the sheepfold,
but climb up some other way,`"^
footnote:[John 10:1.]
whom the sheep ought not to hear, but such as come in without the call, movings,
and leadings of the Spirit of Christ, wherewith he leads his children into all Truth,
come in certainly not by Christ, who is the _door,_ but some other way,
and therefore are not true shepherds.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VIII.
_Obj._ To all this they object the succession of the church, alleging, that,
since Christ gave a call to his apostles and disciples,
they have conveyed that call to their successors,
having power to ordain pastors and teachers,
by which power the authority of ordaining and making ministers
and pastors is successively conveyed to us,
so that such who are ordained and called by the pastors
of the church are therefore true and lawful ministers,
and others who are not so called are to be accounted but intruders.
Hereunto also some Protestants add a necessity,
though they make it not as a thing essential, that besides this calling of the church,
every one being called ought to have the inward call of the Spirit, inclining him,
so chosen, to his work, but this they say is subjective and not objective,
of which before.

_Answ._
As to what is subjoined of the inward call of the Spirit,
in that they make it not essential to a true call but a supererogation as it were,
it showeth how little they set by it,
since those they admit to the ministry are not so much as questioned, in their trials,
whether they have this or not.
Yet in that it hath been often mentioned,
especially by the primitive Protestants in their treatises on this subject,
it showeth how much they were secretly convinced in their
minds that this inward call of the Spirit was most excellent,
and preferable to any other;
and therefore in the most noble and heroic acts of
the reformation they laid claim unto it,
so that many of the primitive Protestants did not scruple
both to despise and disown this outward call^
footnote:[succession.]
when urged by the Papists against them.
But now Protestants, having gone from the testimony of the Spirit,
plead for the same succession,
& being pressed by those whom God now raiseth up by his Spirit to reform these abuses
that are among them with the example of their forefathers`' practice against Rome,
they are not at all ashamed utterly to deny that their fathers were called
to their work by the inward and immediate vocation of the Spirit,
clothing themselves with that call which they say
their forefathers had as pastors of the Roman church.
For thus (not to go further) affirmeth Nicolaus Arnoldus^
footnote:[who gives himself out Doctor and Professor of the sacred theology at Franeker.]
in a pamphlet written against the same propositions, called [.book-title]#A Theologic Exercitation,#
sect.
40,
averring that they pretended not to an immediate act of the Holy Spirit but reformed
by the virtue of the ordinary vocation which they had in the church,
as it then was, to wit that of Rome, etc.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IX. Many absurdities do Protestants fall into by
deriving their ministry thus through the church of Rome.
As first they must acknowledge her to be a true church of Christ,
though only erroneous in some things, which contradicts their forefathers so frequently,
and yet truly, calling her Antichrist.
Secondly,
they must needs acknowledge that the priests and bishops of the
Romish church are true ministers and pastors of the church of Christ,
to the essential part,
else they could not have been fit subjects for that
power and authority to have resided in,
neither could they have been vessels capable to receive
that power and again transmit it to their successors.
Thirdly,
it would follow from this that the priests and bishops of the Romish
church are yet really true pastors and teachers;
for if Protestant ministers have no authority but what they received from them,
and since the church of Rome is the same she was at that time of the reformation,
in doctrine and manners, and she has the same power now she had then,
and if the power lie in the succession, then these priests of the Romish churchnow,
which derive their ordination from those bishops that ordained the first reformers,
have the same authority which the successors of the reformed have,
and consequently are no less ministers of the church than they are.
But how will this agree with that opinion which the primitive
Protestants had of the Romish priests and clergy,
to whom Luther did not only deny any power or authority but contrariwise
affirmed that it was wickedly done of them to assume to themselves
only this authority to teach and be priests and ministers,
etc. For he himself affirmed that "`every good Christian (not only men,
but even women also) is a preacher.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§X. But against this vain succession,
as asserted either by the Papists or Protestants
as a necessary thing to the call of a minister,
I answer that such as plead for it as a sufficient or necessary thing to the call of
a minister do thereby sufficiently declare their ignorance of the nature of Christianity
and how much they are strangers to the life and power of a Christian ministry,
which is not entailed to succession, as an outward inheritance; and herein,
as hath been often before observed, to not only make the Gospel not better than the Law,
but even far short of it: for Jesus Christ,
as he regardeth not any distinct particular family
or nation in the gathering of his children,
but only such as are joined to and leavened with his own pure and righteous Seed,
so neither regards he a bare outward succession, where his pure, immaculate,
and righteous Life is wanting; for that were all one.
He took not in the nations within the New Covenant that he might
suffer them to fall into the old errors of the Jews,
or to approve them in their errors;
but that he might gather unto himself a pure people out of the earth.
Now this was the great error of the Jews,
to think they were the church and people of God because
they could derive their outward succession from Abraham,
whereby they reckoned themselves the children of God, as being the offspring of Abraham,
who was the father of the faithful.
But how severely doth the Scripture rebuke this vain and frivolous pretence?
Telling them,
"`that God is able of the stones to raise children
unto Abraham,`" and that not the outward seed,
but those that were found in the faith of Abraham,
are the true children of faithful Abraham.
Far less then can this pretence hold among Christians,
seeing Christ rejects all outward affinity of that kind: "`These,`" saith he,
"`are my mother, brethren and sisters,
who do the will of my Father which is in heaven.`"^
footnote:[Matt. 12:48 etc.]
And again: "`He looked round about him and said, '`who shall do the will of God,
these,`' said he, '`are my brethren.`'"`^
footnote:[Mark 3:33. etc.]
So then such as do not the commands of Christ,
as are not found clothed with his righteousness, are not his disciples;
and that which a man hath not, he cannot give to another;
and it is clear that no man nor church, though truly called of God,
and as such having the authority of a Church and minister,
can any longer retain that authority than they retain the power, life,
and righteousness of Christianity; for the form is entailed to the power and substance,
and not the substance to the form.
So that when a man ceaseth inwardly in his heart to be a Christian (where
his Christianity must lie) by turning to Satan and becoming a reprobate,
he is no more a Christian, though he retain the name and form, than a dead man is a man,
though he hath the image and representation of one,
or than the picture or statue of a man is a man;
and though a dead man may serve to a painter to retain some
imperfect representation of the man that sometimes was alive,
and so one picture may serve to make another by,
yet none of those can serve to make a true living man again,
neither can they convey the life and spirit of the man: it must be God,
that made the man at first, that alone can revive him.
As death then makes such interruption of an outward natural succession,
that no art nor outward form can uphold, and as a dead man, after he is dead,
can have no issue, neither can dead images of men make living men,
so that it is the living that are only capable to succeed one another; and such as die,
so soon as they die cease to succeed, or to transmit succession.
So it is in spiritual things:
it is the life of Christianity taking place in the heart that makes a Christian,
and so it is a number of such, being alive,
joined together in the life of Christianity, that make a Church of Christ,
and it is all those that are thus alive and quickened, considered together,
that make the catholic Church of Christ; therefore when this life ceaseth in one,
then that one ceaseth to be a Christian, and all power,
virtue and authority which he had as a Christian ceaseth with it;
so that if he hath been a minister or teacher, he ceaseth to be so any more;
and though he retain the form, and hold to the authority in words,
yet that signifies no more, nor is it of any more real virtue and authority,
than the mere image of a dead man; and as this is most agreeable to reason,
so it is the Scripture`'s testimony,
for it is said of Judas (Acts 1:25) that Judas
fell from his ministry and apostleship by transgression.
So his transgression caused him to cease to be an apostle any more;
whereas had the apostleship been entailed to his person,
so that transgression could not cause him to lose it until he had been
formally degraded by the church (which Judas never was so long as he lived),
Judas had been as really an apostle after he betrayed Christ as before:
and as it is of one, so of many, yea of a whole Church:
for seeing nothing makes a man truly a Christian but the
life of Christianity inwardly ruling in his heart,
so nothing makes a church but the gathering of several true Christians into one body.
Now where all these members lose this life, there the church ceaseth to be,
though they still uphold the form and retain the name:
for when that which made them a church, and for which they were a church, ceaseth,
then they cease also to be a church: and therefore the Spirit,
speaking to the church of Laodicea, because of her lukewarmness (Rev. 3:16),
threateneth to "`spew her out of his mouth.`" Now suppose the church of Laodicea
had continued in that lukewarmness and had come under that condemnation and judgment,
though she had retained the name and form of a church, and had her pastors and ministers,
as no doubt she had at that time, yet surely she had been no true church of Christ,
nor had the authority of her pastors and teachers
been to be regarded because of any outward succession,
though perhaps some of them had it immediately from the apostles.
From all which I infer that since the authority of the Christian Church
and her pastors is always united and never separated from the inward power,
virtue and righteous life of Christianity; where this ceaseth, that ceaseth also.
But our adversaries acknowledge that many,
if not most of those by and through whom they derive this authority,
were altogether destitute of this life and virtue of Christianity.
Therefore they could neither receive, have, nor transmit any Christian authority.

_Obj._
But if it be objected that though the generality of the bishops and priests
of the church of Rome during the apostasy were such wicked men,
yet Protestants affirm, and thou thyself seemest to acknowledge,
that there were some good men among them, whom the Lord regarded,
and who were true members of the catholic Church of Christ;
might not they then have transmitted this authority?

_Answ._
I answer, this saith nothing,
in respect Protestants do not at all lay claim to their ministry
as transmitted to them by a direct line of good men,
which they can never show nor yet pretend to,
but generally place this succession as inherent in
the whole pastors of the apostate church,
neither do they plead their call to be good and valid because
they can derive it through a line of good men,
separate and observably distinguishable from the
rest of the bishops and clergy of the Romish church;
but they derive it as an authority residing in the whole;
for they think it heresy to judge that the quality or condition of the
administrator doth any ways invalidate or prejudice his work.

This vain then and pretended succession not only militates against and fights with the
very manifest purpose and intent of Christ in the gathering and calling of his Church,
but makes him (so to speak) more blind and less prudent than natural
men are in conveying and establishing their outward inheritances:
for where an estate is entailed to a certain name and family,
when that family weareth out and there is no lawful successor
found of it that can make a just title appear,
as being really of blood and affinity to the family,
it is not lawful for anyone of another race or blood,
because he assumes the name or arms of that family,
to possess the estate and claim the superiorities and privileges of the family,
but by the law of nations the inheritance devolves
// lint-disable invalid-characters "œ"
into the prince as being _ultimus hœres,_
and so he giveth it again immediately to whom he sees meet and makes them bear the name
and arms of the family who then are entitled to the privileges and revenues thereof.
So in like manner, the true name and title of a Christian,
by which he hath right to the heavenly inheritance and is a member of Jesus Christ,
is inward righteousness and holiness, and the mind redeemed from the vanities, lusts,
and iniquities of this world.
And a gathering or company made up of such members make a church;
where this is lost the title is lost, and so the true seed to which the promise is,
and to which the inheritance is due, becomes extinguished in them,
and they become dead as to it; and so it retires and devolves itself again unto Christ,
who is the righteous heir of life;
and he gives the title and true right again immediately to whom it pleaseth him,
even to as many as being turned to his pure Light in their consciences come again to
walk in his righteous and innocent life and so become true members of his body,
which is the church.
So the authority,
power and heirship are not annexed to persons as
they bear the bare names or retain a form,
holding the mere shell or shadow of Christianity;
but the promise is to Christ and to the Seed, in whom the authority is inherent,
and in as many as are one with him and united unto him by purity and holiness
and by the inward renovation and regeneration of their minds.

Moreover,
this pretended succession is contrary to Scripture definitions
and nature of the Church of Christ and of the true members.
For, first, "`The church is the house of God,
the pillar and ground of Truth`" (1 Tim. 3:15). But according to this doctrine
the house of God is a polluted nest of all sort of wickedness and abominations,
made up of the most ugly, defiled and perverse stones that are in the earth,
where the devil rules in all manner of unrighteousness.
For so our adversaries confess, and history informs the church of Rome to have been,
as some of their historians acknowledge;
and if that be truly the house of God what may we call the house of Satan?
Or may we call it therefore the house of God, notwithstanding all this impiety,
because they had a bare form, and that vitiated many ways also,
and because they pretended to the name of Christianity, though they were antichristian,
devilish, and atheistical in their whole practice and spirit,
and also in many of their principles?
Would not this infer yet a greater absurdity,
as if they had been something to be accounted of because
of their hypocrisy and deceit and false pretences?
Whereas the Scripture looks upon that as an aggravation
of guilt and calls it blasphemy (Rev. 2:9). Of two wicked men,
he is most to be abhorred who covereth his wickedness
with a vain pretence of God and righteousness;
even so these abominable beasts and fearful monsters who look upon themselves
to be bishops in the apostate church were never a whit the better that
they falsely pretended to be the successors of the holy apostles;
unless to lie be commendable and that hypocrisy be the way to heaven.
Yea, were not this to fall into that evil condemned among the Jews?
(Jer. 7:4): "`Trust ye not in lying words, saying, The Temple of the Lord,
the Temple of the Lord, the Temple of the Lord are these;
thoroughly amend your ways,`" etc.,
as if such outward names and things were the thing
the Lord regarded and not inward holiness?
Or can that then be the pillar and ground of Truth
which is the very sink and pit of wickedness,
from which so much error, superstition, idolatry and all abomination spring?
Can there be anything more contrary both to Scripture and reason?

Secondly, the Church is defined to be "`the kingdom of the dear Son of God,
into which the saints are translated,`" being "`delivered from the power
of darkness.`" It is called "`the body of Christ,`" which from him "`by joints
and bands having nourishment ministered and knit together increaseth with
the increase of God`" (Col. 2:19). But can such members,
such a gathering as we have demonstrated that church and members to be,
among whom they allege their pretended authority to have been preserved,
and through which they derive their call, can such, I say, be the body of Christ,
or the members thereof?
Or is Christ the head of such a corrupt, dead, dark, abominable, stinking carcass?
If so, then might we not as well affirm against the apostle (2 Cor. 6:14):
"`That righteousness hath fellowship with unrighteousness,
that light hath communion with darkness, that Christ hath concord with Belial,
that a believer hath part with an infidel,
and that the temple of God hath agreement with idols`"?
Moreover no man is called the temple of God,
nor of the Holy Ghost,
but as his vessel is purified and so he fitted and prepared for God to dwell in;
and many thus fitted by Christ become his body, in and among whom he dwells and walks,
according as it is written, "`I will dwell in them and walk in them,
and I will be their God,
and they shall be my people.`" It is therefore that we may become the temple
of Christ and people of God that the apostle in the following verse exhorts,
saying out of the prophet,
"`Wherefore come out from out from among them and be ye separate, saith the Lord,
and touch not the unclean thing, and I will receive you;
and I will be a father unto you and ye shall be my sons and daughters,
saith the Lord Almighty`".^
footnote:[2 Cor. 6:17-18.]
But to what purpose is all this exhortation, and why should we separate from the unclean,
if a mere outward profession and name be enough to make the true church;
and if the unclean and polluted were both the church and lawful successors of the apostles,
inheriting their authority and transmitting it to others?
Yea, how can the church be the kingdom of the Son of God as contradistinguished
from the kingdom and power of darkness?
And what need, yea what possibility of being translated out of the one into the other,
if those that make up the kingdom and power of darkness
be real members of the true church of Christ,
and not simple members only, but the very pastors and teachers of it?
But how do they "`increase in the increase of God,
and receive spiritual nourishment from Christ the
head,`" that are enemies of him in their hearts,
by wicked works, and openly go into perdition?
Verily as no metaphysical and nice distinctions (that though they were practically,
as to their own private estates, enemies to God and Christ, and so servants of Satan,
yet they were by virtue of their office members and ministers of the Church,
and so able to transmit the succession),
I say as such invented and frivolous distinctions will not please the Lord God,
neither will he be deluded by such,
nor make up the glorious body of his Church with such mere outside hypocritical shows,
nor be beholden to such painted sepulchres for to be members of his body, which is sound,
pure and undefiled;
and therefore he needs not such false and corrupt members to make up the defects of it;
so neither will such distinctions satisfy truly tender and Christian consciences,
especially considering the apostle is so far from desiring us to regard this
as that we are expressly commanded to turn away from such as "`have a form of
godliness but deny the power of it.`" For we may well object against these,
as the poor man did against the proud prelate,
that went about to cover his vain and unchristian-like sumptuousness
by distinguishing that it was not as bishop,
but as prince he had all that splendor.
To which the poor rustic wisely is said to have answered, "`When the prince goeth to hell,
what shall become of the prelate?`" And indeed this
were to suppose the body of Christ to be defective,
and that to fill up these defective places he puts counterfeit and dead stuff,
instead of real living members; like such as lose their eyes, arms,
or legs make counterfeit ones of timber or glass, instead of them.
But we cannot think so of Christ, neither can we believe, for the reasons above adduced,
that either we are to account, or that Christ doth account,
any man or men a whit the more members of his body, because though they be really wicked,
they hypocritically and deceitfully clothe themselves with his name pretended to it;
for this is contrary to his own doctrine, where he saith expressly (John 15:1-6,
etc.) that "`he is the vine and his disciples are the branches,`"
that "`except they abide in him they cannot bear fruit,
and if they be unfruitful they shall be cast forth as a branch and wither.`" Now I suppose
these cut and withered branches are no more true branches nor members of the vine,
they can draw no more sap nor nourishment from it after that they are cut off,
and so have no more virtue, sap, nor life.
What have they then to boast or glory of any authority, seeing they want that life,
virtue and nourishment, from which all authority comes?
So such members of Christ as are become dead to him through unrighteousness,
and so derive no more virtue nor life from him, are cut off by their sins and wither,
and have no longer any true or real authority,
and their boasting of any is but an aggravation of their iniquity by hypocrisy and deceit.
But further, would not this make Christ`'s body a mere shadow and phantasm?
Yea would it not make him head of a lifeless, rotten, stinking carcass,
having only some little outward false show, while inwardly full of rottenness and dirt?
And what a monster would these men make of Christ`'s body, by assigning it a real, pure,
living, quick Head, full of virtue and life, and yet tied to such a dead,
lifeless body as we have already described these members to be,
which they allege to have been the church of Christ?
Again, the members of the church of Christ are specified by this definition,
to wit,
as being "`the sanctified in Christ Jesus`" (1 Cor. 1:2). But this notion of succession
supposeth not only some unsanctified members to be of the church of Christ,
but even the whole to consist of unsanctified members;
yea that such as were professed necromancers and open servants
of Satan were the true successors of the apostles,
and in whom the apostolic authority resided,
these being the vessels through whom this succession is transmitted; though many of them,
as all Protestants and also some Papists confess,
attained these offices in the (so called) church
not only by such means as Simon Magus sought it,
but by much worse, even by witchcraft, murder, traditions, money, and treachery,
which Platina himself confesseth^
footnote:[In the Life of Benedict 4. of John 16. of Sylvester 3. of Boniface 8.
of Steph 6. of Jean 8. Also Onuphrius`' annotations upon this Papass,
towards the end.]
of divers bishops of Rome.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XI. But such as object not this succession of the church (which
yet most Protestants begin now to do) distinguish in this matter,
affirming that in a great apostasy such as was that of the church of Rome,
God may raise up some singularly, by his Spirit,
who from the testimony of the Scriptures perceiving the errors
into which such as bear the name of Christians are fallen,
may instruct and teach them and then become authorized by the people`'s joining with,
and accepting of their ministry only.
Most of them also will affirm that the Spirit herein is subjective, and not objective.

_Obj._
But they say that where a church is reformed,
such as they pretend the Protestant churches are,
there an ordinary orderly call is necessary; and that of the Spirit, as extraordinary,
is not to be sought after: alleging that
_res aliter se habet in ecclesia constituenda, quam in ecclesia constituta,_
that is, there is a difference in the constituting of a church, and after it is constitute.

_Answ._
I answer, this objection as to us saith nothing, seeing we accuse,
and are ready from the Scriptures to prove the Protestants guilty of gross errors,
and needing reformation, as well as they did and do the Papists;
and therefore we may justly lay claim, if we would,
to the same extraordinary call, having the same reason for it,
and as good evidence to prove ours as they had for theirs.
As for that maxim, viz: that the case is different in a constituting church,
and a church constituted, I do not deny it;
and therefore there may be a greater measure of power
required to the one than to the other,
and God in his wisdom distributes the same as he sees meet,
but that the same immediate assistance of the Spirit is not necessary for ministers
in a gathered church as well as in gathering one I see no solid reason alleged for it.
For sure Christ`'s promise was to be "`with his children to the end of the world`";
and they need him no less to preserve and guide his Church and children,
than to gather and beget them.
Nature taught the Gentiles this maxim:

[verse]
____
_Non minor est virtus, quam quaerere, parta tueri._
____

[.offset]
Englished thus,

[verse]
____
For to defend what you attain
Requires no less strength than to gain.
____

For it is by this inward and immediate operation of the Spirit (which
Christ hath promised to "`lead his children with into all Truth,`" and to
"`teach them all things`") that Christians are to be led in all steps (as
well last as first) which relate to God`'s glory and their own salvation,
as we have heretofore sufficiently proven and therefore need not now repeat it.
And truly this device of Satan,
whereby he has got people to put the immediate guidings
and leadings of God`'s Spirit as an extraordinary thing,
afar off,
which the forefathers had but which they now are neither to wait for nor expect,
is a great cause of the growing apostasy upon the many gathered churches,
and is one great reason why a dry, dead, barren, lifeless, spiritless ministry,
which leavens the people into the same death, doth so much abound,
and is so much overspreading even the Protestant nations that their preachings and worships,
as well as whole conversation,
is not to be discerned from Popish by any fresh living
zeal or lively power of the Spirit accompanying it,
but merely by the difference of some notions and opinions.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XII.
_Obj._ Some unwise and unwary Protestants do sometimes object to us,
that if we have such an immediate call as we lay
claim to we ought to confirm it by miracles.

_Answ._
But this being an objection once and again objected
to the primitive Protestants by the Papists,
we need but short return the answer to it that they did to the Papists, to wit,
that we need not miracles because we preach no new gospel,
but that which is already confirmed by all the miracles of Christ and his apostles,
and that we offer nothing but that which we are ready
and able to confirm by the testimony of the Scriptures,
which both already acknowledge to be true.
And that John the Baptist and divers of the prophets did none that we hear of,
and yet were both immediately and extraordinarily sent.
This is the common Protestant answer, therefore may suffice in this place,
though if need were I could say more to this purpose, but that I study brevity.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIII.
There is also another sort of Protestants, to wit the English Independents, who,
differing from the Calvinistical Presbyterians and denying the
necessity of this succession or the authority of any national church,
take another way; affirming that such as have the benefit of the Scriptures,
any company of people agreeing in the principles of Truth as they find them there declared,
may constitute among themselves a church, without the authority of any other,
and may choose to themselves a pastor, who by the church thus constitute and consenting,
is authorized,
requiring only the assistance and concurrence of the pastors
of the neighbouring churches (if any be);
not so much as absolutely necessary to authorize, as decent for order`'s sake.
Also they go so far as to affirm that in a church so constitute, any gifted brother,
as they call them, if he find himself qualified thereto, may instruct, exhort,
and preach in the church;
though as not having the pastoral office he can not
administer that they call their sacraments.

To this I answer that this was a good step out of the Babylonish darkness,
and no doubt did proceed from a real discovery of the Truth,
and from the sense of a great abuse of the promiscuous national gatherings.
Also this preaching of the gifted brethren (as they called them) did proceed
at first from certain lively touches and movings of the Spirit of God upon many.
But alas! because they went not forward, that is much decayed among them,
and the motions of God`'s Spirit begin to be denied and rejected among them now,
as much as by others.

But as to their pretended call from the Scripture, I answer:
the Scripture gives a mere declaration of true things,
but no call to particular persons,
so that though I believe the things there written to be true,
and deny the errors which I find there testified against,
yet as to these things which may be my particular duty, I am still to seek,
and therefore I can never be resolved in the Scripture whether I, such a one by name,
ought to be a minister.
And for the resolving this doubt,
I must needs recur to the inward and immediate testimony of the Spirit,
as in the proposition concerning the Scriptures more at large is shown.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIV.
From all this then we do firmly conclude,
that not only in a general apostasy it is needful men be
extraordinarily called and raised up by the Spirit of God,
but that even when several assemblies or churches are gathered by the power of God,
not only into the belief of the principles of Truth, so as to deny errors and heresies,
but also into the life, spirit, and power of Christianity,
so as to be the body and house of Christ indeed, and a fit spouse for him,
that he who gathers them doth also, for the preserving them in a lively, fresh,
and powerful condition, raise up and move among them,
by the inward immediate operation of his own Spirit,
ministers and teachers to instruct and teach and watch over them,
who being thus called are manifest in the hearts of their brethren,
and their call is thus verified in them who,
by the feeling of that life and power that passeth through them,
being inwardly builded up by them daily in the most holy faith,
become the seals of their apostleship;
and this is answerable to another saying of the same apostle Paul (2 Cor. 13:3):
"`Since ye seek a proof of Christ`'s speaking in me, which to you-wards is not weak,
but is mighty in you.`" So this is that which gives a true substantial
call and title to a minister whereby he is a real successor of the virtue,
life and power that was in the apostles, and not of the bare name;
and to such ministers we think the outward ceremony
of ordination or laying on of hands not necessary,
neither can we see the use of it,
seeing our adversaries who use it acknowledge that the virtue and
power of communicating the Holy Ghost by it is ceased among them.
And is it not then foolish and ridiculous for them, by an apish imitation,
to keep up the shadow where the substance is wanting?
And may not they by the same rule, where they see blind and lame men,
in imitation of Christ and his apostles, bid them see and walk?
Yea, is it not in them a mocking of God and men to put on their hands
and bid men receive the Holy Ghost while they believe the thing impossible,
and confess that that ceremony has no real effect?
Having thus far spoken of the call,
I shall proceed next to treat of the qualifications and work of a true minister.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XV. As I have placed the true call of a
minister in the motion of the Holy Spirit,
so is the power, life, and virtue thereof,
and the pure Grace of God that comes therefrom,
the chief and most necessary qualification without which he can no ways perform his duty,
neither acceptably to God nor beneficially to men.
Our adversaries in this case affirm that three things go to the making up of a minister,
viz: 1) natural parts, that he be not a fool; 2) acquired parts,
that he be learned in the languages, philosophy and school divinity; 3) the Grace of God.

The two first they reckon necessary to the being of a minister,
so as a man cannot be one without them;
the third they say goeth to the well-being of one, but not to the being;
so that a man may truly be a lawful minister without it,
and ought to be heard and received as such.
But we (supposing a natural capacity,
that one be not an idiot) judge the grace of God
indispensably necessary to the very being of a minister,
as that without which any can neither be a true, nor lawful, nor good minister.
As for letter-learning, we judge it not so much necessary to the well- being of one,
though accidentally sometimes in certain respects it may concur,
but more frequently it is hurtful than helpful, as appeared in the example of Taulerus,
who, being a learned man, and who could make an eloquent preaching,
needed nevertheless to be instructed in the way of the Lord by a poor laic.
I shall first speak of the necessity of grace and then proceed
to say something of that literature which they judge so needful.

First then, as we said in the call, so may we much more here.
If the Grace of God be a necessary qualification to make one a true Christian,
it must be a qualification much more necessary to constitute a true minister of Christianity.
That Grace is necessary to make up a true Christian I think will not be questioned,
since it is "`by Grace we are saved`" (Eph. 2:8),
it is the "`Grace of God that teacheth us to deny ungodliness and the lusts of this world,
and to live godly and righteously`" (Tit. 2:11), yea, Christ saith expressly,
that without him we can do nothing (John 15:5); and the way whereby Christ helpeth,
assisteth, and worketh with us is by his grace: hence he saith to Paul,
"`My grace is sufficient for thee.`" A Christian without grace is indeed no Christian,
but an hypocrite and a false pretender.
Then I say, If grace be necessary to a private Christian,
far more to a teacher among Christians, who must be as a father and instructor of others,
seeing this dignity is bestowed upon such as have
attained a greater measure than their brethren.
Even nature itself may teach us that there is more
required in a teacher than in those that are taught,
and that the master must be above and before the scholar
in that art or science which he teacheth others.
Since then Christianity cannot be truly enjoyed,
neither any man denominated a Christian without the true grace of God,
therefore neither can any man be a true and lawful teacher of Christianity without it.

[.syllogism]
* _Arg._ Secondly, No man can be a minister of the Church of Christ, which is his body, unless he be a member of the body, and receive of the virtue and life of the _Head._
* But he that hath not true Grace can neither be a member of the body, neither receive of that life and nourishment which comes from the Head:
* Therefore far less can he be a minister to edify the body.

That he cannot be a minister who is not a member is evident,
because who is not a member is shut out and cut off, and hath no place in the body,
whereas the ministers are counted among the most eminent members of the body;
but no man can be a member unless he receive of the virtue, life,
and nourishment of the Head; for the members that receive not this life and nourishment,
decay and wither, and then are cut off.
And that every true member doth thus receive nourishment and life from the Head,
the apostle expressly affirmeth (Eph. 4:16):
"`From whom the whole body being fitly joined together,
and compacted by that which every joint supplieth,
according to the effectual working in the measure of every part,
maketh increase of the body unto the edifying of
itself in love.`" Now this that thus is communicated,
and which thus uniteth the whole, is no other than the Grace of God,
and therefore the apostle in the same chapter (v. 7), saith,
"`But unto every one of us is given Grace according to the measure of the gift of Christ,`"
and (v. 11) he showeth how that "`by this Grace and Gift both apostles,
prophets, evangelists,
pastors and teachers are given for the work of the ministry and edifying of the body
of Christ.`" And certainly then no man destitute of this Grace is fit for this work,
seeing that all that Christ gives are so qualified;
and these that are not so qualified are not given nor sent of Christ,
are not to be heard, nor received, nor acknowledged as ministers of the Gospel,
because his sheep neither ought nor will hear the voice of a stranger.
This is also clear from 1 Cor. 12 throughout; for the apostle in that chapter,
treating of the diversity of gifts and members of the body,
showeth how by the working of the same Spirit in different manifestations
or measures in the several members the whole body is edified,
saying (v. 13), that "`we are all baptized by the one Spirit into one body`";
and then (v. 28) he numbers out the several dispensations thereof,
which by God are set in the Church through the various working of his Spirit,
for the edification of the whole.
Then if there be no true member of the body which is not thus baptized by this Spirit,
neither anything that worketh to the edifying of it,
but according to a measure of grace received from the Spirit,
surely without grace none ought to be admitted to work or labour in the body,
because their labour and work, without this Grace and Spirit, would be but ineffectual.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XVI.
Thirdly,
that this Grace and Gift is a necessary qualification to a minister
is clear from that of the apostle Peter (1 Pet. 4:10-11),
"`As every man hath received the gift, even so minister the same one to another,
as good stewards of the manifold grace of God.
If any man speak, let him speak as the oracles of God: if any man minister,
let him do it as of the ability which God giveth;
that God in all things may be glorified through Jesus Christ;
to whom be praise and dominion forever and ever,
Amen.`" From which it appears that these that minister
must minister according to the Gift and Grace received;
but they that have not such a gift cannot minister according thereunto.
Secondly, "`As good stewards of the manifold Grace of God`":
but how can a man be a good steward of that which he hath not?
Can ungodly men, that are not gracious themselves,
be good stewards of the manifold Grace of God?
and therefore in the following verses he makes an exclusive
limitation of such that are not thus furnished,
saying, "`If any man speak, let him speak as the oracles of God; and if any man minister,
let him do it as of the ability that God giveth,`" which is as much as if he had said,
They that cannot thus speak and thus minister ought not to do it:
for this "`if`" denotes a necessary condition.
Now what this ability is, is manifest by the former words, to wit, the Gift received,
and the Grace whereof they are stewards,
as by the immediate context and dependency of the words doth appear:
neither can it be understood of a mere natural ability,
because man in this condition is said "`not to know the things
of God,`" and so he cannot minister them to others.
And the following words show this also, in that he immediately subjoineth,
"`that God in all things may be glorified`";
but surely God is not glorified but greatly dishonored when natural men from their mere
natural ability meddle in spiritual things which they neither know nor understand.

Fourthly, that Grace is a most necessary qualification for a minister,
appears by these qualifications, which the apostle expressly requires (1 Tim. 3:2;
Tit. 1, etc.), where he saith, "`A bishop must be blameless, vigilant, sober,
of good behaviour, apt to teach, patient, a lover of good men, just, holy, temperate,
as the steward of God holding fast the faithful Word
as he hath been taught.`" Upon the other hand,
"`He must neither be given to wine, nor a striker, nor covetous, nor proud,
nor self-willed,
nor soon angry.`" Now I ask if it be not impossible
that a man can have all these above named virtues,
and be free of all these evils, without the grace of God?
If then these virtues (for the producing of which in a man Grace
is absolutely necessary) be necessary to make a true minister of
the Church of Christ according to the apostle`'s judgment,
surely Grace must he necessary also.

Concerning this thing a learned man, and well skilled in antiquity,
about the time of the reformation, writeth thus: "`Whatsoever is done in the church,
either for ornament or edification of religion,
whether in choosing magistrates or instituting ministers of the church,
except it be done by the ministry of God`'s Spirit,
which is as it were the soul of the church, it is vain and wicked.
For whoever hath not been called by the Spirit of God to
the great office of God and dignity of apostleship,
as Aaron was, and hath not entered in by the door which is Christ,
but hath otherways risen in the church by the window, by the favours of men, etc.,
truly such a one is not the vicar of Christ and the apostles, but a thief and robber,
and the vicar of Judas Iscariot and Simon the Samaritan.
Hence it was so strictly appointed concerning the election of prelates (which holy Dionysius
calls the sacrament of nomination) that the bishops and apostles who should oversee
the service of the church should be men of most entire manners and life,
powerful in sound doctrine, to give a reason for all things.`" So also another^
footnote:[Francis Lambert of Avenion, in his book concerning prophecy, learning,
tongues and the spirit of prophecy.
_Argentorat. excus. anno 1516, deprov. cap. 24._]
about the same time writeth thus:
"`Therefore it can never be that by the tongues or learning any can give
a sound judgment concerning the Holy Scriptures and the truth of God.
Lastly,`" saith he, "`the sheep of Christ seeketh nothing but the voice of Christ,
which he knoweth by the Holy Spirit, wherewith he is filled: he regards not learning,
tongues, or any outward thing,
so as therefore to believe this or that to be the voice of Christ his true shepherd;
he knoweth that there is need of no other thing but the testimony of the Spirit of God.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§XVII.
_Obj._ Against this absolute necessity of Grace they
object that if all ministers had the saving Grace of God,
then all ministers should be saved, seeing none can fall away from or lose saving Grace.

_Answ._
But this objection is built upon a false hypothesis, purely denied by us,
and we have in the former proposition concerning perseverance already refuted it.

_Obj._
Secondly,
it may be objected to us that since we affirm that
every man hath a measure of true and saving Grace,
there needs no singular qualification neither to a Christian nor minister;
for seeing every man hath this Grace,
then no man needs forbear to be a minister for want of Grace.

_Answ._
I answer, we have above shown that there is necessary to the making a minister,
a special and particular call from the Spirit of God,
which is something besides the universal dispensation of grace to _all,_
according to that of the apostle, "`No man taketh this honor unto himself,
but he that is called of God, as was Aaron.`"^
footnote:[Heb. 5:4.]
Moreover, we understand by Grace, as a qualification to a minister,
not the mere measure of Light, as it is given to reprove and call him to righteousness;
but we understand Grace as it hath converted the soul, and operateth powerfully in it,
as hereafter, concerning the work of ministers, will further appear.
So we understand not men simply,
as having Grace in them as a seed (which we indeed affirm
all have in a measure) but we understand men that are gracious,
leavened by it into the nature thereof,
so as thereby to bring forth those good fruits of a blameless conversation,
and of justice, holiness, patience and temperance,
which the apostle requires as necessary in a true Christian bishop and minister.

Thirdly, they object the example of the false prophets, of the Pharisees,
and of Judas.^
footnote:[So Nic. Arnoldus, sect. 32 upon the 4 _These._]

But first, As to the false prophets, there can nothing be more foolish and ridiculous;
as if, because there were false prophets, truly false, without the Grace of God,
therefore Grace is not necessary to a true Christian minister.
Indeed, if they had proven that true prophets wanted this Grace, they had said something.
But what have false prophets common with true ministers?
but that they pretend falsely that which they have not.
And because false prophets want true Grace,
will it therefore follow that true prophets ought not to have it, or need it not?
yea doth it not much rather follow that they ought to have it,^
footnote:[Later editors omit "`or need it not?
yea doth it not much rather follow that they ought to have it.`"]
that they may be true and not false?
The example of the Pharisees and priests under the
Law will not answer to the Gospel times,
because God set apart a particular tribe for that service, and particular families,
to whom it belonged by a lineal succession;
and also their service and work was not purely spiritual,
but only the performance of some outward and carnal observations and ceremonies,
which were but a shadow of the Substance that was to come,
and therefore their work "`made not the comers thereunto
perfect as appertaining to the conscience,`" seeing they
were appointed only according to the law of a carnal commandment,
and not according to the power of an endless life.
Notwithstanding as in the figure they behooved to
be "`without blemish`" as to their outward man,
and in the performance of their work they behooved to be
washed and purified from their outward pollutions;
so now, under the Gospel times,
the ministers in the antitype must be inwardly "`without
blemish`" in their souls and spirits,
being, as the apostle requires, blameless,
and in their work and service must be pure and undefiled from their inward pollutions;
and so clean and holy,
that they may "`offer up spiritual sacrifices acceptable
to God by Jesus Christ`" (1 Pet. 2:5). As to Judas,
the season of his ministry was not wholly evangelical,
as being before the work was finished,
and while Christ himself and his disciples were yet
subject to the Jewish observances and constitutions,
and therefore his commission,
as well as that which the rest received with him at that time,
was "`only to the house of Israel`" (Matt. 10:5-6);
which made that by virtue of that commission the rest of the apostles
were not empowered to go forth and preach after the resurrection until
they had waited at Jerusalem for the pouring forth of the Spirit.
So that it appears Judas`'s ministry was more legal than evangelical.
Secondly, Judas`'s case, as all will acknowledge, was singular and extraordinary,
he being immediately called by Christ himself,
and accordingly furnished and empowered by him to preach and do miracles;
which immediate commission our adversaries do not so much as pretend to,
and so fall short of Judas, who trusted in Christ`'s words,
and therefore went forth and preached, "`without gold or silver or scrip for his journey;
giving freely as he had freely received`"; which our adversaries will not do,
as hereafter shall be observed;
also that Judas at that time had not the least measure of God`'s Grace,
I have not as yet heard proved.
But is it not sad that even Protestants should lay
aside the eleven good and faithful apostles,
and all the rest of the holy disciples and ministers of Christ,
and betake them to that one of whom it was testified that he was a devil,
for a pattern and example to their ministry?
Alas! it is to be regretted that too many of them resemble this pattern overmuch.

_Obj._
Another objection is usually made against the necessity of Grace,^
footnote:[_Ibid.,_ Nic. Arnoldus.]
that in case it were necessary then such as wanted
it could not truly administer the sacraments;
and consequently the people would be left in doubts and infinite scruples,
as not knowing certainly whether they had truly received them because not knowing
infallibly whether the administrators were truly gracious men.

_Answ._
But this objection hitteth not us at all,
because the nature of that spiritual and Christian worship which we,
according to the Truth, plead for,
is such as is not necessarily attended with these carnal and outward
institutions from the administering of which the objection ariseth,
and so hath not any such absurdity following upon it,
as will afterwards more clearly appear.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XVIII.
Though then we make not human learning necessary,
yet we are far from excluding true learning, to wit,
that learning which proceedeth from the inward teachings and instructions of the Spirit,
whereby the soul learneth the secret ways of the Lord,
becomes acquainted with many inward travels and exercises of the mind,
and learneth by a living experience how to overcome evil and the
temptations of it by following the Lord and walking in his light,
and waiting daily for wisdom and knowledge immediately from the revelation thereof,
and so layeth up these heavenly and divine lessons in the good treasure of the
heart as honest Mary did the sayings which she heard and things which she observed;
and also out of this treasure of the soul, as the good scribe,
brings forth things new and old,
according as the same Spirit moves and gives a true liberty,
and as need is for the Lord`'s glory, whose the soul is, and for whom,
and with an eye to whose glory, she^
footnote:[Later editors replace "`as need is for the Lord`'s glory, whose the soul is,
and for whom, and with an eye to whose glory, she`" with "`as the glory of God requires,
for whose glory the soul.`"]
which is the temple of God learneth to do all things.
This is that good learning which we think necessary to a true minister;
by and through which learning a man can well instruct, teach, and admonish in due season,
and testify for God from a certain experience, as did David, Solomon,
and the holy prophets of old, and the blessed apostles of our Lord Jesus Christ,
who "`testified of what they had seen, heard, felt,
and handled of the Word of Life`" (1 John 1:1),
ministering the gift according as they had received the same,
as good stewards of the manifold grace of God,
and preached not the uncertain rumors of others^
footnote:[Later editors replace "`others`" with "`men.`"]
by hearsay which they had gathered merely in the comprehension,
while they were strangers to the thing in their own experience in themselves:
as to teach people how to believe while themselves were unbelieving,
or how to overcome sin while themselves are slaves to it, as all ungracious men are;
or to believe and hope for an eternal reward which themselves have not as yet arrived at,
etc.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIX.
But let us examine this literature which
they make so necessary to the being of a minister;
as in the first place, the knowledge of the _tongues,_ at least of the Latin, Greek,
and Hebrew.
The reason for this is that they may read the Scriptures, which is their only rule,
in the original languages,
and thereby be the more capable to comment upon it and interpret it,
etc. That also which made this knowledge be the more prized by the
primitive Protestants was indeed the dark barbarity that was over
the world in the centuries immediately preceding the reformation;
the knowledge of the tongues being about that time,
until it was even then restored by Erasmus and some others, almost lost and extinct.
And this barbarity was so much the more abominable,
that the whole worship and prayers of the people were in the Latin tongue;
and among that vast number of priests, monks and friars,
scarce one of a thousand understood his breviary
or that mass which he daily read and repeated.
The Scriptures being, not only to the people but to the greater part of the clergy,
even as to the literal knowledge of it, as a sealed book.
I shall not at all discommend the zeal that the first
reformers had against this Babylonish darkness,
nor their pious endeavours to translate the holy Scriptures; but I do truly believe,
according to their knowledge, that they did it candidly:
and therefore to answer the just desires of those that desire to read them,
and for other very good reasons,
as maintaining a commerce and understanding among divers
nations by these common languages and other of that kind,
we judge it necessary and commendable that there be public schools for the teaching
and instructing youth as are inclinable thereunto in the languages.
And although that papal ignorance deserved justly to be abhorred and abominated,
we see nevertheless that the true reformation consists not in that knowledge,
because although, since that time, the Papists,
stirred up through emulation of the Protestants,
have more applied themselves to literature,
and it now more flourisheth in their universities and cloisters than before,
especially in the Ignatian or Jesuitic sect,
they are as far now as ever from a true reformation,
and more obdured in their pernicious doctrines.
But all this will not make this a necessary qualification to a minister,
far less a more necessary qualification than the Grace of God and his Spirit,
because the Spirit and Grace of God can make up this want in the most rustic and ignorant.
But this knowledge can no ways make up the want of
the Spirit in the most learned and eloquent.
For all that which man by his own industry, learning, and knowledge in the languages,
can interpret of the Scriptures, or find out, is nothing without the Spirit;
he cannot be certain of it and may still miss of the sense of it: but a poor man,
that knoweth not a letter, when he heareth the Scriptures read, by the same Spirit,
he can say, this is true; and by the same Spirit he can understand, open,
and interpret it, if need be: yea he,
finding his condition to answer the condition and experience of the saints of old,
knoweth and possesseth the truths there delivered,
because they are sealed and witnessed in his own heart by the same Spirit.
And this we have plentiful experience of,
in many of those illiterate men whom God hath raised
up to be ministers in his Church in this day;
so that some such by his Spirit have corrected some of the errors of the translators,
as in the third proposition concerning the Scriptures I before observed.
Yea, I know myself a poor shoemaker that cannot read a word,
who being assaulted with a false citation of Scripture,
from a public professor of divinity, before the magistrate of a city,
when he had been taken for preaching to some few that came to hear him, I say,
I know such a one, and he yet liveth,
who though the professor (who also is esteemed a learned
man) constantly asserted his saying to be a Scripture sentence,
yet affirmed, not through any certain letter-knowledge he had of it,
but from the most certain evidence of the Spirit in himself,
that the professor lied;^
footnote:[Later editors substitute "`was mistaken`" for "`lied.`"]
and that the Spirit of God never said any such thing as the other affirmed:
and the Bible being brought, it was found as the poor shoemaker had said.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XX. The second part of their literature is logic and philosophy,
an art so little needful to a true minister,
that if one that comes to be a true minister hath had it,
it is safest for him to forget and lose it;
for it is the root and ground of all contention and debate,
and the way to make a thing a great deal darker than clearer.
For under the pretence of regulating man`'s reason into a certain order and rules,
that he may find out, as they pretend, the Truth,
it leads into such a labyrinth of contention as is
far more fit to make a skeptic than a Christian,
far less a minister of Christ;
yea it often hinders man from a clear understanding
of things that his own reason would give him;
and therefore through its manifold rules and divers inventions it often gives
occasion for a man that hath little reason foolishly to speak much to no purpose,
seeing a man that is not very wise, may notwithstanding be a perfect logician, and then,
if ye would make a man a fool to purpose, that is not very wise,
do but teach him logic and philosophy,
and whereas before he might have been fit for something,
he shall then be good for nothing but to speak nonsense,
for these notions will so swim in his head that they
will make him extremely busy about nothing.
The use that wise men and solid make of it, is to see the emptiness thereof;
therefore saith one "`It is an art of contention and darkness,
by which all other sciences are rendered more obscure, and harder to be understood.`"

_Inst._
If it be urged that thereby the Truth may be maintained and confirmed and heretics confuted;

_Answ._
I answer, the Truth, in men truly rational, needeth not the help thereof,
and such as are obstinate this will not convince;
for by this they may learn twenty tricks and distinctions, how to shut out the Truth;
and the Truth proceeding from an honest heart and spoken forth
from the Virtue and Spirit of God will have more influence,
and take sooner and more effectually, than by a thousand demonstrations of logic;
as that heathen philosopher^
footnote:[Lucas Osiander, _epit hist. Eccles+++.+++, lib. 2, cap. 5, cent. 4._]
acknowledged who, disputing with the Christian bishops in the Council of Nice,
was so subtle that he could not be overcome by them;
but yet by a few words spoken by a simple old rustic was presently
convinced by him and converted to the Christian faith,
and being inquired how he came to yield to that ignorant old man and not to the bishops,
he said that "`they contended with him in his own way,
and he could still give words for words: but there came from the old man that virtue,
which he was not able to resist.`" This secret virtue and power ought to
be the logic and philosophy wherewith a true Christian minister should
be furnished and for which they need not be beholden to Aristotle.
As to natural logic, by which rational men without that art and rules,
or sophistical learning, deduce a certain conclusion out of true propositions,
which scarce any man of reason wants, we deny not the use of it;
and I have sometimes used it in this treatise;
which also may serve without that dialectical art.
As for the other part of philosophy, which is called morals or ethics,
it is not so necessary to Christians,
who have the rules of the holy Scriptures and the gift of
the Holy Spirit by which they can be much better instructed.
The physical and metaphysical part may be reduced to the arts of medicine and the mathematics,
which have nothing to do with the essence of a Christian minister.
And therefore the apostle Paul,
who well understood what was good for Christian ministers and what was hurtful,
thus exhorted the Colossians (Col. 2:8):
"`Beware lest any man spoil you through philosophy and vain deceit.`" And
to his beloved disciple Timothy he writes also thus (1 Tim. 6:20):
"`O Timothy, keep that which is committed to thy trust,
avoiding profane and vain babblings, and oppositions of science falsely so called.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXI.
The third and main part of their literature is school divinity,
a monster made up betwixt some Scriptural notions
of truth and the heathenish terms and maxims,
being, as it were, the heathenish philosophy Christianized,
or rather the literal external knowledge of Christ heathenized; it is man in his first,
fallen, natural state, with his devilish wisdom,
pleasing himself with some notions of truth and adorning
them with his own serpentine and worldly wisdom,
because he thinks the simplicity of the Truth too low and mean a thing for him;
and so despiseth that simplicity, wheresoever it is found,
that he may set up and exalt himself, puffed up with this, his monstrous birth;
it is the devil darkening, obscuring,
and veiling the knowledge of God with his sensual and carnal wisdom,
that so he may the more securely deceive the hearts of the simple and make the Truth,
as it is in itself, despicable and hard to be known and understood,
by multiplying a thousand hard and needless questions and endless contentions and debates,
all which, whoso perfectly knoweth, he is not a whit less the servant of sin,
than he was, but ten times more, in that he is exalted and proud of iniquity,
and so much the further from receiving, understanding, or learning the truth,
as it is in its own naked simplicity, because he is full, learned, rich,
and wise in his own conceit;
and so those that are most skilled in it wear out their day and
spend their precious time about the infinite and innumerable questions
they have feigned and invented concerning it.
A certain learned man called it "`A twofold discipline, as of the race of the centaurs,
partly proceeding from divine sayings,
partly from philosophical reasons.`" A thousand of their questions
they confess themselves to be no ways necessary to salvation,
and yet many more of them they could never agree upon,
but are and still will be in endless janglings about them.
The volumes that have been written about it, a man in his whole age,
though he lived very old, could scarce read, and when he has read them all,
he has but wrought himself a great deal more vexation
and trouble of spirit than he had before.
These certainly are the "`words multiplied without knowledge,
by which counsel hath been darkened`" (Job 38:2).
They make the Scripture the text of all this mass,
and it is concerning the sense of it that their voluminous debates arise.
But a man of a good upright heart may learn more in half an hour,
and be more certain of it,
by waiting upon God and his Spirit in the heart than
by reading a thousand of their volumes which,
by filling his head with many needless imaginations,
may well stagger his faith but never confirm it;
and indeed those that give themselves most to it are most capable to fall into error,
as appeareth by the example of Origen,
who by his learning was one of the first that falling into
this way of interpreting the Scriptures wrote so many volumes,
and in them so many errors as very much troubled the church.
Also Arius, led by this curiosity and human scrutiny,
despising the simplicity of the Gospel, fell into his error,
which was the cause of that horrible heresy which so much troubled the church;
methinks the simplicity, plainness,
and brevity of the Scriptures themselves should be a sufficient reproof for such a science;
and the apostles being honest, plain, illiterate men,
may be better understood by such kind of men now
than with all that mass of scholastic stuff,
which neither Peter, nor Paul, nor John, ever thought of.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXII.
But this invention of Satan, wherewith he began the apostasy,
hath been of dangerous consequence,
for thereby he at first spoiled the simplicity of Truth by keeping up the heathenish
learning which occasioned such uncertainty even among those called Fathers,
and such debate that there are few of them to be found who, by reason of this mixture,
do not only frequently contradict one another but themselves also.
And therefore, when the apostasy grew greater, he, as it were,
buried the Truth with this veil of darkness,
wholly shutting out people from true knowledge and making the learned, so accounted,
busy themselves with idle and needless questions,
while the weighty truths of God were neglected and, as it were, went into desuetude.
Now, though the grossest of these abuses be swept away by Protestants,
yet the evil root still remains and is nourished and upheld, and upon the growing hand,
that this science is still kept up and deemed necessary for a minister;
for while the pure learning of the Spirit of Truth
is despised and neglected and made ineffectual,
man`'s fallen, earthly wisdom is upheld;
and so in that he labours and works with the Scriptures,
being out of the Life and Spirit those that wrote were in,
by which they are only rightly understood and made use of.
And so he that is to be a minister must learn this art or trade of merchandising
with the Scriptures and be that which the apostle would not be,
to wit, a trader with them (2 Cor.
2:17).^
footnote:[see also 2 Pet. 2:3.]
That he may acquire a trick from a verse of Scripture
by adding his own barren notions and conceptions to it,
and his uncertain conjectures,
and what he hath stolen out of books (for which end he must have
of necessity a good many by him) and may each Sabbath day (as they
call it) or oftener make a discourse for an hour long;
and this is called the preaching of the word; whereas the Gift, Grace, and Spirit of God,
to teach, open, and instruct, and to preach a word in season, is neglected;
and so man`'s arts and parts, and knowledge and wisdom which is from below,
set up and established in the temple of God, yea and above the little seed:
which in effect is Antichrist working in the mystery;
and so the devil may be as good and able a minister as the best of them;
for he has better skill in languages, and more logic,
philosophy and school divinity than any of them,
and knows the Truth in the notion better than they all,
and can talk more eloquently than all those preachers.
But what availeth all this?
Is it not all but as death, as a painted sepulchre and dead carcass without the Power,
Life and Spirit of Christianity,
which is the marrow and substance of a Christian ministry,
and he that hath this and can speak from it, though he be a poor shepherd or a fisherman,
and ignorant of all that learning and of all those questions and notions,
yet speaking from the Spirit,
his ministry will have more influence towards the
converting of a sinner unto God than all of them,
learned after the flesh;
as in that example of the old man at the Council of Nice did appear.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXIII.
And if in any age since the apostles`' days God
hath purposed to show his power by weak instruments,
for the battering down of that carnal and heathenish wisdom,
and restoring again the ancient simplicity of Truth, this is it;
for in our day God hath raised up witnesses for himself, as he did fishermen of old,
many, yea most of whom are labouring and mechanic men, who,
altogether without that learning,
have by the power and Spirit of God struck at the very root and ground of Babylon,
and in the strength and might of this power have gathered thousands,
by reaching their consciences, into the same power and life; who, as to the outward part,
have been far more knowing than they,
yet not able to resist the virtue that proceeded from them.
Of which I myself am a true witness, and can declare from a certain experience,
because my heart hath been often greatly broken and tendered by that virtuous
Life that proceeded from the powerful ministry of those illiterate men:
so that by their very countenance, as well as words,
I have felt the evil in me often chained down and the good reached to and raised.
What shall I then say to you who are lovers of learning and admirers of knowledge?
Was not I also a lover and admirer of it,
who also sought after it according to my age and capacity?
But it pleased God,
in his unutterable love early to withstand my vain endeavours
while I was yet but eighteen years of age,
and made me seriously to consider (which I wish also may
befall others) that "`without holiness and regeneration,
no man can see God`"; and that "`the fear of the Lord is the beginning of wisdom,
and to depart from iniquity a good understanding.`"^
footnote:[Job 28:28.]
And how much "`knowledge puffeth up`" and leadeth away from that inward quietness,
stillness,
and humility of mind where the Lord appears and his heavenly wisdom is revealed.
If ye consider these things, then will ye say with me, that all this learning,
wisdom and knowledge, gathered in this fallen nature,
is but as dross and dung in comparison of the cross of Christ,
especially being destitute of that Power, Life and Virtue,
which I perceived these excellent, though despised because illiterate,
witnesses of God to be filled with; and therefore,
seeing that in and among them I with many others
have found the heavenly food that gives contentment,
let my soul seek after this learning and wait for it forever.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXIV.
Having thus spoken of the call and qualifications of a Gospel minister,
that which, comes next to be considered is what his proper work is,
how and by what rule he is to be ordered.
Our adversaries do all along go upon outwards,
and therefore have certain prescribed rules and methods,
contrived according to their human and earthly wisdom.
We, on the contrary, walk still upon the same foundation,
and lean always upon the immediate assistance and influence of that Holy
Spirit which God hath given his children to teach them all things,
and lead them in all things; which Spirit,
being the Spirit of order and not of confusion,
leads us and as many as follow it into such a comely
and decent order as becometh the Church of God.
But our adversaries,
having shut themselves out from this immediate counsel and influence of the Spirit,
have run themselves into many confusions and disorders,
seeking to establish an order in this matter.
For some will have first a chief bishop or pope to rule and be a prince over all;
and under him by degrees, cardinals, patriarchs, archbishops, priests, deacons,
sub-deacons and besides these, _acoluthi, tonsorati, ostiarii,_ etc. And in their theology,
as they call it, professors, bachelors, doctors,
etc. And others would have every nation independent of another,
having its own metropolitan or patriarch, and the rest in order subject to him,
as before.
Others again are against all precedency among pastors,
and constitute their subordination not of persons but of powers:
as first the consistory or session; then the class, or presbytery; then the provincial;
and then the national synod or assembly.
Thus do they tear one another and contend among themselves concerning the ordering,
distinguishing, and making their several orders and offices,
concerning which there hath been no less contest, not only by way of verbal dispute,
but even by fighting, tumults, wars, devastations, and bloodshed,
than about the conquering, overturning, and establishing of kingdoms.
And the histories of late times are as full of the various tragedies acted upon
the account of this spiritual and ecclesiastical monarchy and commonwealth,
as the histories of old times,
that gave account of the wars and contests that fell out both in the Assyrian, Persian,
Greek and Roman empires.
These last upon this account, though among those that are called Christians,
have been no less bloody and monstrous than the former among heathens,
concerning their outward empires and governments.

Now all this, both among Papists and Protestants, proceedeth,
in that they seek in imitation to uphold a form and shadow of things,
though they want the Power, Virtue and Substance,
though for many of their orders and forms they have not so much as the name in the Scripture.
But in opposition to all this mass of formality and heap of orders,
rules and governments, we say the substance is chiefly to be sought after, and the Power,
Virtue and Spirit is to be known and waited for,
which is One in all the different names and offices the Scripture makes use of;
as appears by 1 Cor. 12:4 (often before mentioned),
"`There are diversities of gifts, but the same Spirit.`" And after the apostle,
throughout the whole chapter,
hath shown how one and the selfsame Spirit worketh in and quickeneth each member,
then in verse 28 he showeth how thereby God hath set in the church, "`first apostles,
secondly prophets, teachers,`" etc. And likewise to the same purpose (Eph. 4:11),
he showeth how by these gifts "`he hath given some apostles, some prophets,
some evangelists, some pastors, some teachers,`" etc. Now it was never Christ`'s purpose,
nor the apostles`', that Christians should without this Spirit and heavenly gift,
set up a shadow and form of these orders,
and so make several ranks and degrees to establish a carnal ministry of men`'s making,
without the Life, Power and Spirit of Christ:
this is that work of antichrist and mystery of iniquity
that hath got up in the dark night of apostasy;
but in a true church of Christ, gathered together by God,
not only unto the belief of the principles of Truth but also into the Power,
Life and Spirit of Christ, the Spirit of God is the Orderer, Ruler and Governor,
as in each particular, so in the general:
and when they assemble together to wait upon God and worship and adore him,
then such as the Spirit sets apart to the ministry by its divine
Power and influence opening their mouths and giving them to exhort,
reprove and instruct with virtue and power,
these are thus of God ordained and admitted into the ministry,
and their brethren cannot but hear them, receive them,
and also honor them for their work`'s sake,
and so this is not monopolized to a certain kind of men,
as the clergy (who are to that purpose educated and brought up,
as other carnal artists) and the rest to be despised as laics;
but it is left to the free gift of God to choose any whom he seeth meet thereunto,
whether rich or poor, servant or master, young or old, yea male or female.
And such as have this call verify the Gospel, by "`preaching not in speech only,
but also in power and in the Holy Ghost, and in much fullness`" (1 Thess. 1:5),
and cannot but be received and heard by the sheep of Christ.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXV.
_Obj._ But if it be objected here that I seem hereby
to make no distinction at all betwixt ministers and others;
which is contrary to the apostle`'s saying (1 Cor. 12:29), "`Are all apostles?
Are all prophets?
Are all teachers?`" etc. from thence they insinuate that I also contradict his comparison,
in that chapter, of the church of Christ with a human body;
as where he saith (v. 17), "`If the whole body were an eye, where were the hearing?
If the whole were hearing,
where were the smelling?`" etc. Also the apostle not only distinguisheth the ministers
of the Church in general from the rest of the members but also from themselves,
as naming them distinctly and separately, apostles, prophets, evangelists, pastors,
teachers, etc.

_Answ._
As to the last part of this objection, to which I shall first answer:
it is apparent that this diversity of names is not for to distinguish separate offices,
but to denote the different and various operations of the Spirit,
a manner of speech frequent with the apostle Paul wherein he sometimes
expatiates to the illustrating of the glory and praise of God`'s Grace,
as in particular (Rom. 12:6):
"`Having then gifts differing according to the Grace that is given us, whether prophecy,
let us prophesy according to the proportion of faith; or ministry,
let us wait on our ministering; or he that teacheth, on teaching; or he that exhorteth,
on exhortation.`" Now none will say from all this that these are distinct offices,
or do not or may not coincide in one person,
as may all those other things mentioned by him, in the subsequent verses, viz.,
of loving, being kindly affectioned, fervency of spirit, hospitality, diligence,
blessing, rejoicing, etc. Which yet he numbers forth as different gifts of the Spirit.
And, according to this objection might be placed as distinct and separate offices,
which were most absurd.

Secondly,
in these very places mentioned it is clear that it
is no real distinction of separate offices;
because all acknowledge that pastors and teachers,
which the apostle there no less separateth and distinguisheth than pastors and prophets,
or apostles, are one and the same, and coincide in the same office and person,
and therefore so may be said of the rest.
For "`prophecy`" as it signifieth the _foretelling of things to come,_
is indeed a distinct gift, but no distinct office,
and therefore our adversaries do not place it among their several orders,
neither will they deny but that both may be and hath been given
of God to some that not only have been pastors and teachers,
and that there it hath coincided in one person with these other offices,
but also to some of the laics, and so it hath been found,
according to their own concession, without the limits of their clergy.
Prophecy in the other sense, to wit,
as it signifieth a speaking from the Spirit of Truth,
is not only peculiar to pastors and teachers, who ought so to prophesy,
but even a common privilege to the saints: for though to instruct,
teach and exhort be proper to such as are more particularly
called to the work of the ministry,
yet it is not so proper to them, as not to be, when the saints are met together,
as any of them are moved by the Spirit, common to others:
for some acts belong to all in such a relation,
but not only to those within that relation, _Competunt omni, sed non soli:_
thus to see and hear are proper acts of a man;
seeing it may be properly predicated of him, that he heareth and seeth:
yet are they common to other creatures also.
So to prophesy, in this sense, is indeed proper to ministers and teachers; yet not so,
but that it is common and lawful to other saints, when moved thereunto,
though it be not proper to them by way of relation, because, notwithstanding that motion,
they are not particularly called to the work of the ministry, as appears by 1 Cor. 14,
where the apostle at large declaring the order and
ordinary method of the church saith (vv. 30-31),
"`But if anything be revealed to another that sitteth by let the first hold his peace,
for ye may all prophesy one by one, that all may learn and all be comforted`":
which showeth that none is here excluded.
But yet that there is a subordination,
according to the various measures of the gift received, the next verse showeth:
"`And the spirits of the prophets are subject to the prophets.
For God is not the author of confusion but of peace.`" Now that prophesying,
in this sense, may be common to all saints, appears by verse 39 of the same chapter,
where speaking to _all_ in general he saith, "`Therefore, brethren, covet to prophesy`";
and (v. 1) he exhorts them, saying "`Covet^
footnote:[Later editors change "`covet`" to "`desire.`"]
spiritual gifts, but the rather that ye may prophesy.`"

Secondly, as to evangelists, the same may be said:
for whoever preacheth the Gospel is really an evangelist,
and so consequently every true minister of the Gospel is one,
else what proper office can they assign to it,
unless they should be so foolish as to affirm that none were evangelists but Matthew,
Mark, Luke, and John, who wrote the account of Christ`'s life and sufferings?
And then it were neither a particular office,
seeing John and Matthew were apostles, Mark and Luke pastors and teachers,
so that there they coincided in one, and indeed it is absurd to think,
that upon that particular account the apostle used the word
"`evangelist.`" Calvin acknowledgeth that "`such,
as preach the Gospel in purity after some time of apostasy,
may be truly called evangelists,`" and therefore saith,
"`that there were apostles in his time`";
and hence the Protestants at their first coming forth, termed themselves _evangelici,_
or evangelics.

Lastly, an apostle, if we look to the etymology of the word, signifies one that is sent,
and in respect every true minister is sent of God in so far he is an apostle,
though these twelve, because of their being specially sent of Christ,
// lint-disable invalid-characters
were therefore called apostles, κατʹ ἐξοχὴν, or _per eminentiam,_ i.e., by way of excellency.
And yet that there was no limitation to such a number as some foolishly imagine,
it appears, because after that number was filled up,
the apostle Paul was afterwards so called;
therefore we judge that these are no distinct separate offices,
but only names used upon occasions to express the
more eminent arising and shining forth of God`'s grace,
as if any minister of Christ should now proselyte
and turn a whole nation to the Christian faith,
though he had no distinct office,
yet I doubt not but both Papists and Protestants would judge
it tolerable to call such an one an apostle or an evangelist.
For some of the Jesuits call of their sect apostles of India and of Japan,
upon this alleged^
footnote:[Later editors omit "`alleged.`"]
account.
And Calvin testifies that there were apostles and evangelists in his time,
upon the account of the Reformation,
upon which account we have known John Knox often called the apostle of Scotland,
so that we conclude that ministers, pastors, or teachers doth comprehend all,
and that the office is but one,
and therefore in that respect we judge there ought to be no precedency among them;
to prove which I shall not insist,
seeing it is shown largely and treated of by such as have denied the diocesan episcopacy,
as they call it.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXVI.
As to the first part of the objection, viz.,
that I seem to make no distinction betwixt the minister and people, I answer,
If it be understood of a liberty to speak or prophesy by the Spirit,
I say all may do that, when moved thereunto, as above is shown;
but we do believe and affirm that some are more particularly called to the work
of the ministry and therefore are fitted of the Lord for that purpose,
whose work is more constantly and particularly to instruct, exhort, admonish, oversee,
and watch over their brethren;
and that as there is something more incumbent upon
them in that respect than upon every common believer,
so also, as in that relation,
there is due to them from the flock such obedience and subjection
as is mentioned in these testimonies of the Scripture:
Heb. 13:17; 1 Thess. 5:12-13; 1 Tim. 5:17; 1 Pet. 5:5.
Also besides these,
who are thus particularly called to the ministry
and constant labour in the Word and doctrine,
there are also the elders, who,
though they be not moved to a frequent testimony by way of declaration in words,
yet as such are grown up in the experience of the blessed work of Truth in their hearts,
watch over and privately admonish the young, care for the widows, the poor,
and fatherless, and care and look that nothing be wanting, but that peace, love, unity,
concord and soundness be preserved in the Church of Christ;
and this answers to the deacons mentioned (Acts 6).

That which we oppose is the distinction of laity and clergy (which in
the Scripture is not to be found) whereby none are admitted unto the work
of the ministry but such as are educated at schools on purpose,
and instructed in logic and philosophy, etc.,
and so are at their apprenticeship to learn the art and
trade of preaching even as a man learns any other art,
whereby all other honest mechanic men, who have not got this heathenish art,
are excluded from having this privilege;
and so he that is a scholar thus bred up must not
have any honest trade whereby to get him a livelihood,
if he once intend for the ministry, but he must see to get him a place,
and then he hath his set hire for a livelihood to him;
he must also be distinguished from the rest by the color of his clothes,
for he must only wear black, and must be a master of arts: but more of this hereafter.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXVII.
As this manner of separating men for the ministry
is nothing like the church in the apostles`' days,
so great evils have and do follow upon it.
For first parents, seeing both the honor and profit that attends the clergy,
do allot their children sometimes from their infancy to it,
and so breed them up on purpose: and others, come to age,
upon the same account betake them to the same trade,
and having these natural and acquired parts,
that are judged the necessary qualifications of a minister, are thereby admitted,
and so are bred up in idleness and pleasure,
thinking it a disgrace for them to work with their hands;
only if they study a little out of their books,
to make a discourse once or twice in a week during the running of an hourglass:
whereas the Gift, Grace and Spirit of God to call,
gift and qualify for the ministry is neglected and overlooked.
And many covetous, corrupt, earthly, carnal men, having a mere show and form,
but strangers to and utterly ignorant of the inward work of grace upon their hearts,
are brought in and intrude themselves, and so, through them, death, barrenness,
and darkness, and by consequence, superstition,
error and idolatry hath entered and leavened the church;
and they that will narrowly observe shall find that
it was thus the apostasy came to take place;
of the truth of which I could give many examples which for brevity`'s sake I omit.
For so the office, reverence, and respect due to it was annexed to the mere name,
so that when once a man was ordained a bishop or a priest he was heard and believed,
though he had nothing of the Spirit, Power,
and Life that the true apostles and ministers were in,
that in a short time the succession came to be of
the name and title and the office was thereto annexed,
and not of the nature, virtue, and life.
Which in effect made them to cease to be the ministry and ministers of Christ,
but only a shadow and vain image of it,
which also decaying was in some ages so metamorphosed,
that not only the substance was lost, but the very form wholly vitiated, altered,
and marred, that it may be far better said of the pretended Christian Church,
as was disputed of Theseus`'s boat (which by the piecing of many new pieces
of timber was wholly altered) whether indeed it were the same or another.
But in case that the first had been of oak, and the last pieces put in but of rotten fir,
and that also the form had been so far changed as to be nothing like the first,
I think it would have suffered no dispute,
but might have easily been concluded to be quite another, retaining nothing but the name,
and that also unjustly.
Secondly, from this distinction of laity and clergy this abuse also follows, that good,
honest, mechanic men,
and others who have not learned the art and trade of preaching and so
are not licentiated according to these rules they prescribe unto themselves,
such, I say,
being possessed with a false opinion that it is not
lawful for them to meddle with the ministry,
nor that they are any ways fit for it, because of the defect of that literature,
do thereby neglect the gift in themselves and quench many times
the pure breathings of the Spirit of God in their hearts;
which, if given way to,
might have proved much more for the edification of the Church than many of the cunned^
footnote:[_cunned_ +++=+++ researched.]
sermons of the learned.
And so by this means the apostle`'s command and advice is slighted,
who exhorteth (1 Thess. 5:19-20) "`not to quench the Spirit, nor despise prophesying`":
and all this is done by men pretending to be Christians,
who glory that the first preachers and propagators of their
religion were such kind of plain mechanic men and illiterate.
And even Protestants do no less than Papists exclude
such kind of men from being ministers among them,
and thus limit the Spirit and gift of God, though their fathers,
in opposition to Papists, asserted the contrary;
and also their own histories declare how that kind of illiterate men did,
without learning, by the Spirit of God,
greatly contribute in divers places to the Reformation.

By this it may appear that as in calling and qualifying so in preaching
and praying and the other particular steps of the ministry,
every true minister is to know the Spirit of God by its virtue and life,
to accompany and assist him.
But, because this relates to worship,
I shall speak of it more largely in the next proposition, which is concerning worship.
The last thing to be considered and inquired into
is concerning the maintenance of a Gospel minister;
but before I proceed I judge it fit to speak something
in short concerning the _preaching of women,_
and to declare what we hold in that matter.

Seeing "`male and female are one in Christ Jesus,`" and that
he gives his Spirit no less to one than to the other,
when God moveth by his Spirit in a woman we judge it no ways unlawful
for her to preach in the assemblies of God`'s people.
Neither think we that of Paul (1 Cor. 14:34),
to reprove the inconsiderate and talkative women among the Corinthians,
who troubled the church of Christ with their unprofitable questions,
or that (1 Tim. 2:11), that "`women ought to learn in all silence,
not usurping authority over the man,`" any ways repugnant to this doctrine;
because it`'s clear that women have prophesied and preached in the Church,
else had that saying of Joel been badly applied by Peter (Acts 2:17). And,
seeing Paul himself, in the same epistle to the Corinthians,
giveth rules how women should behave themselves in their public preaching and praying,
it would be a manifest contradiction if that place
were other ways taken in a larger sense;
and the same Paul speaks of a woman that laboured with him in the work of the gospel;
and it is written that Philip had four daughters that prophesied;^
footnote:[Acts 21:9.]
and lastly,
it hath been observed that God hath effectually in this
day converted many souls by the ministry of women,
and by them also frequently comforted the souls of his children;
which manifest experience puts the thing beyond all controversy:
but now I shall proceed to speak of the maintenance of ministers.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXVIII.
We freely acknowledge, as the Proposition holds forth,
that there is an obligation upon such to whom God sends,
or among whom he raiseth up a minister, that if need be they minister to his necessities.
Secondly, that it is lawful for him to receive what is necessary and convenient.
To prove this I need not insist, for our adversaries will readily grant it to us,
for the thing we affirm is that this is all that these scripture
testimonies relating to this thing do grant (Gal. 6:6;
1 Cor. 9:11-14; 1 Tim. 5:18). That which we then oppose in this matter is first,
that it should be constrained and limited.
Secondly, that it should be superfluous, chargeable, and sumptuous.
And thirdly, the manifest abuse hereof, of which I shall also briefly treat.

As to the first, our adversaries are forced to recur to the example of the Law,
a refuge they use in defending most of their errors and superstitions
which are contrary to the nature and purity of the Gospel.

_Obj._
They say, God appointed the Levites the tithes,
therefore they belong also to such as minister in holy things under the Gospel.

_Answ._
I answer,
all that can be gathered from this is that as the priests
had a maintenance allowed them under the law,
so also the ministers and preachers under the Gospel, which is not denied:
but the comparison will not hold that they should have the very same, since First,
there is no express Gospel command for it, neither by Christ nor his apostles.
Secondly, the parity doth no ways hold betwixt the Levites under the Law,
and the preachers under the Gospel;
because the Levites were one of the tribes of Israel and so had a right to a
part of the inheritance of the land as well as the rest of their brethren,
and having none had this allotted to them in lieu of it.
Next, the tenth of the tithes was only allowed to the priests that served at the altar,
the rest being for the Levites,
and also to be put up in storehouses for entertaining of the widows and strangers.
But these preachers,
notwithstanding they inherit what they have by their parents as well as other men,
yet claim the whole tithes, allowing nothing either to widow or stranger.
But as to the tithes I shall not insist,
because divers others have clearly and learnedly treated of it apart,
and also divers Protestants do confess them not to be _jure divino,_
and the parity as to the quota doth not hold,
but only in general as to the obligation of a maintenance.
Which maintenance,
though the hearers be obliged to give and fail of their duty if they do not,
yet that it ought neither to be received nor yet forced, I prove, because Christ,
when he sent forth his apostles, said, "`Freely ye have received,
freely give`" (Matt. 10:8),
and yet they had liberty to receive meat and drink
from such as offered them to supply their need.
Which shows that they were not to seek or require anything by force, or to stint,
or make a bargain beforehand,
as the preachers as well among Papists as Protestants do in these days,
who will not preach to any until they be first sure of so much a year;
but on the contrary,
these were to do their duty and freely to communicate
(as the Lord should order them) what they had received,
without seeking or expecting a reward.

The answer given to this by Nicolaus Arnoldus, [.book-title]#Exercit.
Theolog.#
sect.
42-43, is not to be forgotten,
but indeed to be kept upon record for a perpetual remembrance of him and his brethren,
for he frankly answers after this manner, "`We have not freely received,
and therefore are not bound to give freely.`" The answer I confess is ingenuous and good.
For if those that receive freely are to give freely,
it would seem to follow by the rule of contraries,
that those that receive not freely ought not to give freely, and I shall grant it.
Only they must grant me that they preach not by and
according to the Gift and Grace of God received,
nor can they be good stewards of the "`manifold grace
of God,`" as every true minister ought to be;
or else they have gotten this gift or grace by money,
as Simon Magus would have been compassing it,
since they think themselves not bound to give it without money again.
But to be plain,
I believe he intended not that it was from the gift or grace of God they were to preach,
but from their acquired arts and studies,
which have cost them much labour and also some money at the University; and therefore,
as he that puts his stock into the public bank expects interest again,
so these scholars having spent some money learning the art of preaching
think they may boldly say they have it not freely,
for it hath cost them both money and pains,
and therefore they expect both money and ease again.
And therefore,
as Arnoldus gets money for teaching his young students the art and trade of preaching,
so he intends they should be repaid before they give it again to others.
It was of old said, __"`Omnia venalia Romae,`"__ i.e.,
"`All things are set out to sale at Rome,`" but now
the same proverb may be applied to Franeker.
And therefore Arnoldus`'s students, when they go about to preach,
may safely seek and require hereby, telling their hearers their master`'s maxim,
_Nos gratis non accepimus, ergo neque gratis dare tenemur._
But then they may answer again that they find them
and their master to be none of his ministers,
who when he sent forth his disciples, gave them this command, "`Freely ye have received,
freely give,`" and therefore we will have none of your teaching,
because we perceive you to be of the number of those
"`that look for their gain from their quarter.`"^
footnote:[Isa. 56:11.]

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXIX.
Secondly,
The Scripture testimonies that urge this are in the same nature of those
that press charity and liberality towards the poor and command hospitality,
etc. But these are not, nor can be stinted to a certain quantity,
because they are deeds merely voluntary,
where the obedience to the command lieth in the good will of the giver,
and not in the matter of the thing given,
as Christ showeth in the example of the widow`'s mite.
So that though there be an obligation upon Christians
to minister of outward things to their ministers,
yet there can be no definition of the quantity, but by the giver`'s own consent,
and a little from one may more truly fulfill the obligation than a great deal from another.
And therefore as acts of charity and hospitality can neither be limited nor forced,
so neither can this.

_Obj._
If it be objected that ministers may and ought to exhort, persuade,
yea and earnestly press Christians (if they find
them defective therein) to acts of charity and hospitality,
and so may they do also to the giving of maintenance;

_Answ._
I answer,
all this saith nothing for a stinted and forced maintenance (for which there
cannot so much as the show of one solid argument be brought from Scripture).
I confess ministers may use exhortation in this as much as in any other case,
even as the apostle did to the Corinthians, showing them their duty;
but it were fit for ministers that do so that their testimony might have the more weight,
and be the freer of all suspicion of covetousness and self-interest,
that they might be able to say truly in the sight of God that which
the same apostle subjoins upon the same occasion (1 Cor. 9:15-18):
"`But I have used none of these things.
Neither have I written these things that it should be so done unto me:
for it were better for me to die than that any man should make my glorying void.
For though I preach the Gospel, I have nothing to glory of;
for necessity is laid upon me, yea woe is unto me if I preach not the Gospel.
For if I do this thing willingly I have a reward; but if against my will,
a dispensation of the Gospel is committed unto me.
What is my reward then?
Verily that when I preach the Gospel I may make the Gospel of Christ without charge,
that I abuse not my power in the Gospel.`"

Thirdly,
As there is neither precept nor example for this
forced and stinted maintenance in the Scripture,
so the apostle,
in his solemn farewell to the pastors and elders of the church of Ephesus,
guards them against it (Acts 20:33-35). But if
the thing had been either lawful or practised,
he would rather have exhorted them to be content with their stinted hire,
and not to covet more; whereas he showeth them, first, by his own example,
that they were not to covet or expect any man`'s silver or gold.
Secondly, that they ought to work with their hands for an honest livelihood,
as he had done.
And lastly, he exhorts them so to do from the words of Christ,
"`because it is a more blessed thing to give than to receive`";
showing that it is so far from a thing that a true minister ought to aim at or expect,
that it is rather a burden to a true minister, and cross to him,
to be brought upon necessity so to lack.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXX.
Fourthly, If a forced and stinted maintenance were to be supposed,
it would make the ministers of Christ just one with
those hirelings whom the prophets cried out against.
For certainly, if a man make a bargain to preach to people for so much a year,
so as to refuse to preach unless he have,
and seek to force the people to give it by violence,
it cannot be denied that such a one preacheth for hire and so "`looks for his gain from
his quarter,`" yea and "`prepares war against such as put not into his mouth`":^
footnote:[Micah 3:5.]
but this is the particular special mark of a false prophet and a hireling,
and therefore can no ways compete^
footnote:[_compete_ +++=+++ to be suitable, competent.]
to a true minister of Christ.

Next, that a superfluous maintenance, that is,
more than in reason is needful ought not to be received by Christian ministers,
will not need much proof, seeing the more moderate and sober,
both among Papists and Protestants, readily confess it,
who with one voice exclaim against the excessive revenues of the clergy:
and that it may not want a proof from Scripture,
what can be more plain than that of the apostle to Timothy?
(1 Tim. 6:7-11), where he both shows wherewith we ought to be content,
and also the hazard of such as look after more; and indeed,
since that very obligation of giving maintenance
to a minister is founded upon their need,
and such as have opportunity to work are commended rather in not receiving than in receiving,
it can no ways be supposed lawful for them to receive more than is sufficient,
and indeed, were they truly pious and right, though necessitate,
they would rather incline to take too little, than be gaping after too much.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXXI.
Now that there is great excess and abuse hereof among Christians,
the vast revenues which the bishops and priests have, both Papists and Protestants,
do declare,
since I judge it may be said without any hyperbole that some particular persons have
more paid them yearly than Christ and his apostles made use of their whole lifetime,
who yet wanted not what was needful as to the outward man,
and no doubt deserved it far better than those that enjoy that fulness.
But it is manifest these bishops and priests love their fat benefices and the
pleasure and honor that attend them so well that they purpose neither to follow
Christ nor his apostles`' example nor advice in this matter.

_Obj._
But it is usually objected, that Christians are become so hardhearted,
and generally so little heed spiritual things,
that if ministers had not a settled and stinted maintenance secured
them by law they and their families might starve for want of bread.

_Answ._
I answer, This objection might have some weight as to a carnal ministry,
made up of natural men who have no life, power, nor virtue with them,
and so may insinuate some need of such a maintenance for such a ministry;
but it saith nothing as to such as are called and sent of God,
who sends no man away faring upon his own charges,
and so go forth in the authority and power of God, to turn people from darkness to Light,
for such can trust to him that sendeth them,
and do believe that he will provide for them, knowing that he requireth nothing of any,
but what he giveth power to perform; and so when they return, if he inquire,
can say they wanted nothing.
And such also,
when they stay in a place (being immediately furnished by God and not needing
to borrow and steal what they preach from books and take up their time that way)
fall a-working at their lawful employments and labour with their hands,
as Paul did, when he gathered the church of Corinth.
And indeed, if this objection had any weight,
the apostles and primitive pastors should never have
gone forth to convert the nations,
for fear of want.
Doth not the doctrine of Christ teach us to venture all and part with all, to serve God?
Can they then be accounted ministers of Christ who are afraid
to preach him lest they get not money for it,
or will not do it until they be sure of their payment?
What for serves the ministry but to perfect the saints,
and so to convert them from that hard-heartedness?

_Obj._
But thou wilt say, I have laboured and preached to them,
and they are hardhearted still and will not give me anything.

_Answ._
Then surely thou hast either not been sent to them of God,
and so thy ministry and preaching hath not been among them in the Power, Virtue,
and Life of Christ, and so thou deservest nothing;
or else they have rejected thy testimony, and so are not worthy,
and from such thou oughtest not to expect,
yea nor yet receive anything if they would give thee,
but thou oughtest to "`shake off the dust from thy feet,`"^
footnote:[Matt. 10:14.]
and leave them.
And how frivolous this objection is,
appears in that in the darkest and most superstitious
times the priests`' revenues increased most,
and they were most richly rewarded, though they deserved least.
So that he that is truly sent of God, as he needs not,
so neither will he be afraid of want, so long as he serves so good a master;
neither will he ever forbear to do his work for that cause.
And indeed such as make this objection show truly that they
serve not the Lord Christ but their own belly,
and that makes them so anxious for want of food to it.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXXII.
But lastly, as to the abuses of this kind of maintenance,
indeed he that would go through them all, though he did it passingly,
might make of it alone a huge volume, they are so great and numerous.
For this abuse, as others, crept in with the apostasy,
there being nothing of this in the primitive times, then the ministers claimed no tithes,
neither sought they a stinted or forced maintenance,
but such as wanted had their necessity supplied by the Church,
and others wrought with their hands.
But the persecutions being over,
and the emperors and princes coming under the name of Christians,
the zeal of those great men was quickly abused by the covetousness of the clergy,
who soon learned to change their cottages with the palaces of princes,
and rested not until by degrees some of them came to be princes themselves,
nothing inferior to them in splendor, luxury and magnificence,
a method of living that honest Peter and John the fishermen, and Paul the tentmaker,
never coveted.
And perhaps as little imagined that men pretending to be
their successors should have arrived to these things;
and so soon as the bishops were thus seated and constitute,
forgetting the life and work of a Christian,
they went usually by the ears together about the precedency and revenues,
each coveting the chiefest and fattest benefice.
It is also to be regretted to think how soon this mischief crept in among Protestants,
who had scarce well appeared when the clergy among them began to speak at the old rate,
and show that though they had forsaken the Bishop of Rome
they were not resolved to part with their old benefices,
and therefore so soon as any princes or states shook off the Pope`'s authority,
and so demolished the abbeys, nunneries, and other monuments of superstition,
the reformed clergy began presently to cry out to the magistrates
to beware of meddling with the church`'s patrimony,
severely exclaiming against making a lawful use of those
vast revenues that had been superstitiously bestowed upon
the church (so called) to the good and benefit of the commonwealth,
as no less than sacrilege.

But by keeping up of this kind of maintenance for the ministry and clergymen, so called,
there is first a bait laid for covetousness, which is idolatry,
and of all things most hurtful; so that for covetousness sake many,
being led by the desire of filthy lucre,
do apply themselves to be ministers that they may get a livelihood by it;
if a man have several children, he will allot one of them to be a minister;
which if he can get him to be, he reckons it as good as a patrimony,
so that a fat benefice hath always many expectants, and then what bribing, what courting,
what industry and shameful actions are used to acquire these
things is too openly known and needs not be proven.

The scandal that herethrough is raised among Christians
is so manifest that it is become a proverb,
that "`the kirk is always greedy.`" Whereby the Gift and Grace of God being neglected,
they have for the most part no other motive or rule
in applying themselves to one church more than another,
but the greater benefice.
For though they hypocritically pretend,
at their accepting of and entering into their church,
that they have nothing before them but the glory of God and the salvation of souls,
yet if a richer benefice offer itself,
they presently find it more for God`'s glory to remove from the first and go thither.
And thus they make no difficulty often to change,
while notwithstanding they accuse us that we allow ministers to go from place to place,
and not to be tied to one place;
but we allow this not for the gaining of money but as moved of God;
for if a minister be called to minister in a particular place,
he ought not to leave it except God call him from it, and then he ought to obey,
for we make the will of God inwardly revealed, and not the love of money and more gain,
the ground of removing.

Secondly,
From this abuse hath proceeded that luxury and idleness that most of the clergy live in,
even among Protestants as well as Papists, to the great scandal of Christianity.
For not having lawful trades, to work with their hands,
and being so superfluously and sumptuously provided for,
they live in idleness and luxury: and there doth more pride, vanity,
and worldly glory appear in their wives and children than in most others,
which is open and evident.

Thirdly, They become hereby so glued to the love of money,
that there is none like them in malice, rage and cruelty, if they be denied their hire,
they rage like drunken men, fret, fume and as it were go mad.
A man may sooner satisfy the severest creditor than them,
the general voice of the poor doth confirm this, for indeed,
they are far more exact in taking up the tithes of sheep, geese, swine, and eggs, etc.,
and look more narrowly to it than to the members of their flock;
they will miss the least mite;
and the poorest widow cannot escape their avaricious hands:
twenty lies they will hear unreproved,
and as many oaths a man may swear in their hearing without offending them,
and greater evils than all this they can overlook,
but if thou owest them aught & refuse to pay it,
then nothing but _war_ will they thunder against thee,
and they will stigmatize thee with the horrible title of sacrilege,
and send thee to hell without mercy,
as if thou hadst committed the sin against the Holy Ghost.
Of all people we can best bear witness to this:
for God having shown us this corrupt and anti-Christian
ministry and called us out from it,
and gathered us unto his own power and life to be a separate people,
so that we dare not join with nor hear these anti-Christian hirelings,
neither yet put into their mouths or feed them.
Oh! what malice, envy and fury hath this raised in their hearts against us?
that though we get none of their wares, neither will buy them,
as knowing them to be naught, yet will they force us to give them money;
and because we cannot for conscience`' sake do it,
our sufferings have upon that account been unutterable.
Yea to give account of their cruelty and several sorts of
inhumanity used against us would make no small history.
These avaricious hirelings have come to that degree of malice and
rage that several poor labouring men have been carried hundreds
of miles from their own dwellings and shut up in prison,
some two, some three, yea, some seven years together,
for the value of one pound sterling and less.
I know myself a poor widow that for the tithes of her geese,
which amounted not to five shillings, was about four years kept in prison,
thirty miles from her house.
Yea they by violence for this cause have plundered of men`'s goods the hundredfold,
and prejudiced much more;
yea hundreds have hereby spilt their innocent blood
by dying in the filthy noisome holes and prisons,
and some of the priests have been so enraged that
goods thus ravished could not satisfy them,
but they must also satisfy their fury by beating, knocking,
and wounding with their hands innocent men and women,
for refusing (for conscience`' sake) to put into their mouths.

The only way then soundly to reform and remove all these abuses and take away the ground
and occasion of them is to take away all stinted and forced maintenance and stipends:
and seeing those things were anciently given by the people,
that they return again into the public treasure,
and thereby the people may be greatly benefitted by them,
for that they may supply for these public taxations
and impositions that are put upon them,
and may ease themselves of them.
And whoever call or appoint teachers to themselves, let them accordingly entertain them.
And for such as are called and moved to the ministry by the Spirit of God,
those that receive them and taste of the good of their ministry
will no doubt provide things needful for them,
and there will be no need of a law to force a hire for them;
for he that sends them will take care for them; and they also,
having "`food and raiment,`" will "`therewith be content.`"^
footnote:[1 Tim. 6:8.]

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXXIII.
The sum then of what is said is that the ministry that we have pleaded for,
and which also the Lord hath raised up among us,
is in all its parts like the true ministry of the apostles and primitive Church.
Whereas the ministry our adversaries seek to uphold and plead for,
as it doth in all its parts differ from them, so, on the other hand,
it is very like the false prophets and teachers testified
against and condemned in the Scripture,
as may be thus briefly illustrated.

[.numbered-group]
====

[.numbered]
1+++.+++ The ministry and ministers we plead for are such as are immediately called
and sent forth by Christ and his Spirit unto the work of the ministry,
so were the holy apostles and prophets, as appears by these places: Matt. 10:1,5;
Eph. 4:11, Heb. 5:4.

1) But the ministry and ministers our opposers plead
for are such as have no immediate call from Christ,
to whom the leading and motion of the Spirit is not reckoned necessary,
but who are called, sent forth, and ordained by wicked and ungodly men,
such were of old the false prophets and teachers, as appears by these places:
Jer. 14:14-15; 23:21; and 27:15.

[.numbered]
2+++.+++ The ministers we plead for are such as are acted and led by God`'s Spirit,
and by the Power and operation of his Grace in their
hearts are in some measure converted and regenerate,
and so are good, holy, and gracious men, such were the holy prophets and apostles,
as appears from 1 Tim. 3:2-6; Tit. 1:7-9.

2) But the ministers our adversaries plead for are such
to whom the grace of God is no needful qualification,
and so may be true ministers, according to them, though they be ungodly, unholy,
and profligate men: such were the false prophets and apostles,
as appears from Mic. 3:5,11; 1 Tim. 6:5-8, etc.; 2 Tim. 3:2; 2 Pet. 2:1-3.

[.numbered]
3+++.+++ The ministers we plead for are such as act,
move and labour in the work of the ministry,
not from their own mere natural strength and ability, but as they are acted, moved,
under-propped, assisted and influenced by the Spirit of God,
and minister according to the gift received,
as good stewards of the manifold grace of God, such were the holy prophets and apostles:
1 Pet. 4:10-11; 1 Cor. 1:17; 2:3-5,13; Acts 2:4; Matt. 10:20; Mark 13:11;
Luke 12:12; 1 Cor. 13:2.

3) But the ministers our adversaries plead for are such as wait not for, nor expect,
nor need the Spirit of God to act and move them in the work of the ministry,
but what they do they do from their own mere natural strength and ability and what they
have gathered and stolen from the letter of the Scripture and other books,
and so speak it forth in the strength of their own wisdom and eloquence,
and not in the evidence and demonstration of the Spirit and power:
such were the false prophets and apostles, as appears: Jer. 23:30-32,34, etc.;
1 Cor. 4:18; Jude 16.

[.numbered]
4+++.+++ The ministers we plead for are such as, being holy and humble,
contend not for precedency and priority,
but rather strive to prefer one another and serve one another in love;
neither desire to be distinguished from the rest by their garments and large phylacteries,
nor seek the greetings in the marketplaces, nor uppermost rooms at feasts,
nor the chief seats in the synagogues; nor yet to be called of men Master,
etc. Such were the holy prophets and apostles, as appears from Matt. 23:8-10,
and 20:25-27.

4) But the ministers our adversaries plead for are such as strive and contend for superiority,
and claim precedency over one another,
affecting and ambitiously seeking after the forementioned things,
such were the false prophets and apostles in time past: Matt. 23:5-7.

[.numbered]
5+++.+++ The ministers we plead for are such as having freely received, freely give;
who covet no man`'s silver, gold or garments; who seek no man`'s goods, but seek them,
and the salvation of their souls; whose hands supply their own necessities,
working honestly for bread to themselves and their families:
and if at any time they be called of God so as the work
of the Lord hinder them from the use of their trades,
take what is freely given them by such to whom they have communicated spirituals;
and having food and raiment are therewith content;
such were the holy prophets and apostles, as appears from Matt. 10:8;
Acts 20:33-35; 1 Tim. 6:8.

5) But the ministers our adversaries plead for are such as not having freely received,
will not freely give, but are covetous,
doing that which they ought not for filthy lucre`'s sake,
as to preach for hire and divine for money, and look for their gain from their quarter,
and prepare war against such as put not into their mouths,
etc. Greedy dogs which can never have enough.
Shepherds who feed themselves and not the flock,
eating the fat and clothing themselves with the wool, making merchandise of souls,
and following the way of Balaam that loved the wages of unrighteousness.
Such were the false prophets and apostles: Isa. 56:11, Ezek. 34:2-3,8;
Mic. 3:11-5; Tit. 1:10-11; 2 Pet. 2:1-2,14,15.

====

And in a word, We are for a holy, spiritual,
pure and living ministry where the ministers are both called, qualified and ordered,
acted and influenced in all the steps of their ministry by the Spirit of God;
which being wanting, we judge cease to be the ministers of Christ.

But they judging this Life, Grace, and Spirit no essential part of their ministry,
are therefore for the upholding of a human, carnal, dry, barren,
fruitless and dead ministry;
of which (alas!) we have seen the fruits in the most part of their churches;
of whom that saying of the Lord is certainly verified (Jer. 23:32):
"`I sent them not nor commanded them, therefore they shall not profit this people at all,
saith the Lord.`"
