== THE ELEVENTH PROPOSITION

[.chapter-subtitle--blurb]
Concerning Worship

[.heading-continuation-blurb]
All true and acceptable worship to God is offered in the
inward and immediate moving and drawing of his own Spirit,
which is neither limited to places, times, nor persons:
for though we be to worship him always, and that we are continually to fear before him,
yet as to the outward signification thereof in prayers, praises or preachings,
we ought not to do it in our own will, where and when we will;
but where and when we are moved thereunto by the stirring
and secret inspiration of the Spirit of God in our hearts;
which God heareth and accepteth of,
and is never wanting to move us thereunto when need is,
of which he himself is the alone proper judge.
All other worship then, both praises, prayers or preachings,
which man sets about in his own will and at his own appointment,
which he can both begin and end at his pleasure,
do or leave undone as himself seeth meet, whether they be a prescribed form,
as a liturgy, etc.,
or prayers conceived _extempore_ by the natural strength and faculty of the mind,
they are all but superstitions, will-worship,
and abominable idolatry in the sight of God, which are now to be denied and rejected,
and separated from in this day of his spiritual arising,
however it might have pleased him (who "`winked at the times of
ignorance,`" with a respect to the simplicity and integrity of some,
and of his own innocent Seed, which lay, as it were,
buried in the hearts of men under that mass of superstition) to "`blow upon the
dead and dry bones,`" and to raise some breathings of his own and answer them;
and that until the day should more clearly dawn and break forth.

// lint-disable invalid-characters "§"
§I. The duty of man towards God lieth chiefly in these two generals:
1) In an holy conformity to the pure Law and Light of God,
so as both to forsake the evil and be found in the practice of
these perpetual and moral precepts of righteousness and equity.
And 2) In rendering that reverence,
honor and adoration to God that he requires and demands of us,
which is comprehended under worship.
Of the former we have already spoken, as also of the different relations of Christians,
as they are distinguished by the several measures
of grace received and given to every one,
and in that respect have their several offices in the body of Christ,
which is the Church.
Now I come to speak of worship, or of those acts, whether private or public,
general or particular,
whereby man renders to God that part of his duty which relates immediately to him;
and as "`obedience is better than sacrifice,`" so neither is any sacrifice acceptable,
but that which is done according to the will of him to whom it is offered.
But men, finding it easier to sacrifice in their own wills than obey God`'s will,
have heaped up sacrifices without obedience,
and thinking to deceive God as they do one another, give him a show of reverence,
honor and worship,
while they are both inwardly estranged and alienated from his holy and righteous life,
and wholly strangers to the pure breathings of his Spirit,
in which the acceptable sacrifice and worship is only offered up.
Hence it is that there is not anything relating to man`'s duty towards
God which among all sorts of people hath been more vitiated,
and in which the devil hath more prevailed,
than in abusing man`'s mind concerning this thing: and as among many others,
so among those called Christians, nothing hath been more out of order and more corrupted,
as some Papists, and all Protestants, do acknowledge.
As I freely approve whatsoever the Protestants have reformed from Papists in this respect,
so I meddle not at this time with their controversies about it;
only it suffices me with them to deny, as no part of the true worship of God,
that abominable superstition and idolatry the Popish mass,
the adoration of saints and angels, the veneration of relics,
the visitation of sepulchres, and all these other superstitious ceremonies,
confraternities, and endless pilgrimages of the Romish synagogue.
Which all may suffice to evince to Protestants,
that antichrist hath wrought more in this,
than in any other part of the Christian religion,
and so it concerns them narrowly to consider whether
herein they have made a clear and perfect reformation,
as to which stands the controversy betwixt them and us.
For we find many of the branches lopped off by them, but the root yet remaining, to wit,
a worship acted in and from man`'s will and spirit, and not by and from the Spirit of God;
for the true Christian and spiritual worship of God hath been so early lost,
and man`'s wisdom and will hath so quickly and thoroughly mixed itself herein,
that both the apostasy in this respect hath been greatest, and the reformation herefrom,
as to the evil root, most difficult.
Therefore let not the reader suddenly stumble at
the account of our Proposition in this matter,
but hear us patiently in this respect explain ourselves,
and I hope (by the assistance of God) to make it appear,
that though our manner of speaking and doctrine seem most
singular and different from all other sorts of Christians;
yet it is most according to the purest Christian religion,
and indeed most needful to be observed and followed;
and that there be no ground of mistake (for that I was necessitate to speak in few words,
and therefore more obscurely and dubiously in the Proposition itself),
it is fit in the first place to declare and explain our sense,
and clear the state of the controversy.

[.small-break]
'''

// lint-disable invalid-characters "§"
§II. And first let it be considered that what is here
affirmed is spoken of the worship of God in these Gospel times,
and not of the worship that was under or before the Law:
for the particular commands of God to men then are not sufficient
to authorize us now to do the same things;
else we might be supposed at present acceptably to offer sacrifice as they did,
which all acknowledge to be ceased.
So that what might have been both commendable and acceptable
under the Law may justly now be charged with superstition,
yea and idolatry.
So that impertinently, in this respect,
doth Arnoldus rage against this Proposition (_Exercit.
Theolog._
sect.
44), saying that I "`deny all public worship,`" and that according to me,
"`such as in Enoch`'s time publicly began to call upon the name of the Lord,
and such as at the command of God went twice^
footnote:[Later editors substitute "`thrice`" for "`twice.`"]
up to Jerusalem to worship; and that Anna, Simeon, Mary, etc., were idolaters,
because they used the public worship of those times.`" Such a consequence is most impertinent,
and no less foolish and absurd than if I should infer from Paul`'s expostulating
with the Galatians for their returning to the Jewish ceremonies,
that he therefore condemned Moses and all the prophets as foolish and ignorant,
because they used those things: the forward man,
not heeding the different dispensations of times, ran into this impertinency.
Though a spiritual worship might have been,
and no doubt was practised by many under the Law in great simplicity,
yet will it not follow that it were no superstition
to use all those ceremonies that they used,
which were by God dispensed to the Jews not as being essential to true worship,
or necessary as of themselves for transmitting and entertaining
a holy fellowship betwixt him and his people,
but in condescension to them who were inclinable to idolatry; albeit then in this,
as in most other things,
the Substance was enjoyed under the Law by such as were spiritual indeed;
yet was it veiled and surrounded with many rites and ceremonies
which is no ways lawful for us to use now under the Gospel.

[.small-break]
'''

// lint-disable invalid-characters "§"
§III.
Secondly, albeit I say that this worship is neither limited to times, places,
nor persons,
yet I would not be understood as if I intended the putting
away of all set times and places to worship.
God forbid I should think of such an opinion.
Nay, we are none of those that "`forsake the assembling of ourselves together,`" but have even
certain times and places in which we carefully meet together (nor can we be driven therefrom
by the threats and persecutions of men) to wait upon God and worship him.
To meet together we think necessary for the people of God,
because so long as we are clothed with this outward tabernacle there is
a necessity to the entertaining of a joint and visible fellowship,
and bearing of an outward testimony for God, and seeing of the faces of one another,
that we concur with our persons as well as spirits.
To be accompanied with that inward love and unity of spirit
doth greatly tend to encourage and refresh the saints.

But the limitation we condemn is that whereas the
Spirit of God should be the immediate actor,
mover,
persuader and influencer of man in the particular
acts of worship when the saints are met together,
this Spirit is limited in its operations by setting up a
particular man or men to preach and pray in man`'s will,
and all the rest are excluded from so much as believing that they
are to wait for God`'s Spirit to move them in such things;
and so they neglecting that which should quicken them in themselves,
and not waiting to feel the pure breathings of God`'s Spirit so as to obey them,
are led merely to depend upon the preacher and hear what he will say.

Secondly,
in that these peculiar men come not thither to meet with the Lord
and to wait for the inward motions and operations of his Spirit,
and so to pray as they feel the Spirit to breathe _through_ them, and _in_ them,
and to preach as they find themselves acted and moved
by God`'s Spirit and as he gives utterance,
so as to speak a word in season to refresh weary souls,
and as the present condition and state of the people`'s hearts requires,
suffering God by his Spirit both to prepare people`'s hearts and also give
the preacher to speak what may be fit and seasonable for them.
But he hath hammered together in his closet, according to his own will,
by his human wisdom and literature,
and by stealing the words of Truth from the letter of the Scriptures
and patching together other men`'s writings and observations,
so much as will hold him speaking an hour while the glass runs,
and without waiting or feeling the inward influence of the Spirit of God,
declaims that by haphazard,
whether it be fit or seasonable for the people`'s condition or no,
and when he has ended his sermon, he saith his prayer also in his own will,
and so there is an end of the business.
Which customary worship, as it is no ways acceptable to God, so how unfruitful it is,
and unprofitable to those that are found in it,
the present condition of the nations doth sufficiently declare.
It appears then that we are not against set times for worship,
as Arnoldus against this proposition (sect.
45) no less impertinently allegeth,
offering needlessly to prove that which is not denied:
only these times being appointed for outward conveniency we may
not therefore think with the Papists that these _days_ are holy,
and lead people into a superstitious observation of them,
being persuaded that all days are alike holy in the sight of God.
And albeit it be not my present purpose to make a long digression concerning
the debates among Protestants concerning the first day of the week,
commonly called "`the Lord`'s day,`" yet forasmuch as it comes
fitly in here I shall briefly signify our sense thereof.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IV. We, not seeing any ground in scripture for it,
cannot be so superstitious as to believe that either the Jewish sabbath now continues
or that the first day of the week is the antitype thereof or the true Christian sabbath,
which with Calvin we believe to have a more spiritual sense,
and therefore we know no moral obligation by the fourth command
or elsewhere to keep the first day of the week more as any other,
or any holiness inherent in it.
But first,
forasmuch as it is necessary that there be some time set
apart for the saints to meet together to wait upon God;
and that secondly,
it is fit at some times they be freed from their other outward affairs; and that thirdly,
reason and equity doth allow that servants and beasts have some
time allowed them to be eased from their continual labour;
and that fourthly,
it appears that the apostles and primitive Christians
did use the first day of the week for these purposes:
we find ourselves sufficiently moved for these causes to do so also,
without superstitiously straining the Scriptures for another reason,
which that it is not to be there found, many Protestants,
yea Calvin himself upon the fourth command, hath abundantly evinced.
And though we therefore meet and abstain from working upon this day,
yet doth not that hinder us from having meetings also for worship at other times.

[.small-break]
'''

// lint-disable invalid-characters "§"
§V. Thirdly,
though according to the knowledge of God revealed unto us by the Spirit,
through that more full dispensation of Light which
we believe the Lord hath brought about in this day,
we judge it our duty to hold forth that pure and spiritual worship which is acceptable
to God and answerable to the testimony of Christ and his apostles,
and likewise to testify against and deny not only manifest superstition and idolatry,
but also all formal will-worship, which stands not in the power of God, yet, I say,
we do not deny the whole worship of all those that have
borne the name of Christians even in the apostasy,
as if God had never heard their prayers nor accepted any of them.
God forbid we should be so void of charity.
The latter part of the Proposition showeth the contrary;
and as we would not be so absurd on the one hand to conclude,
because of the errors and darkness that many were covered and surrounded with in Babylon,
that none of their prayers were heard or accepted of God,
so will we not be so unwary on the other as to conclude
that because God heard and pitied them so,
we ought to continue in these errors and darkness,
and not come out of Babylon when it is by God discovered unto us.
The Popish mass and vespers I do believe to be, as to the matter of them,
abominable idolatry and superstition, and so also believe the Protestants;
yet will either I or they affirm that in the darkness of Popery no upright-hearted men,
though zealous in these abominations, have been heard of God or accepted of him?^
footnote:[Later editors change Barclay`'s rhetorical question to an assertion:
"`yet will neither I or they affirm that in the darkness of Popery no upright-hearted men,
though zealous in these abominations, have been heard of God, or accepted of him.`"]
// lint-disable invalid-characters "à"
Who can deny but that both Bernard and Bonaventure, Taulerus, Thomas à Kempis,
and divers others have both known and tasted of the love of God and felt
the power and virtue of God`'s Spirit working with them for their salvation?
And yet ought we not to forsake and deny those superstitions which they were found in?
The Calvinistical Presbyterians do much upbraid (and I say not without reason)
the formality and deadness of the Episcopalian and Lutheran liturgies,
and yet, as they will not deny but there have been some good men among them,
so neither dare they refuse but that when that good step was brought
in by them of turning the public prayers into the vulgar tongues,
though continued in a liturgy, it was acceptable to God,
& sometimes accompanied with his power and presence:
yet will not the Presbyterians have it from thence
concluded that the common prayers should still continue;
so likewise,
though we should confess that through the mercy and wonderful condescension
of God there have been uprightin heart both among Papists and Protestants,
yet can we not therefore approve of their ways in the general or not go on to
the upholding of that spiritual worship which the Lord is calling all to,
and so to the testifying against whatsoever stands in the way of it.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VI. Fourthly, to come then to the state of the controversy,
as to the public worship we judge it the duty of all to be diligent
in the assembling of themselves together (and what we have been,
and are, in this matter, our enemies in Great Britain,
who have used all means to hinder our assembling together to worship God,
may bear witness) and when assembled,
the great work of one and all ought to be to wait upon God,
and returning out of their own thoughts and imaginations,
to feel the Lord`'s presence and know a "`gathering into his Name`" indeed,
where he is "`in the midst`" according to his promise.
And as every one is thus gathered,
and so met together inwardly in their spirits as well as outwardly in their persons,
there the secret power and virtue of life is known to refresh the soul,
and the pure motions and breathings of God`'s Spirit are felt to arise,
from which as words of declaration, prayers, or praises arise,
the acceptable worship is known which edifies the Church and is well-pleasing to God,
and no man here limits the Spirit of God nor bringeth forth his own cunned^
footnote:[_cunned_ +++=+++ researched.]
and gathered stuff, but everyone puts that forth which the Lord puts into their hearts:
and it is uttered forth not in man`'s will and wisdom but "`in the
evidence and demonstration of the Spirit and of Power.`" Yea,
though there be not a word spoken,
yet is the true spiritual worship performed and the body of Christ edified;
yea it may and hath often fallen out among us that
divers meetings have past without one word,
and yet our souls have been greatly edified and refreshed,
and our hearts wonderfully overcome with the
secret sense of God`'s Power and Spirit,
which without words hath been ministered from one vessel to another.
This is indeed strange and incredible to the mere natural and carnally-minded man,
who will be apt to judge all time lost,
where there is not something spoken that is obvious to the outward senses;
and therefore I shall insist a little upon this subject,
as one that can speak from a certain experience and not by mere hearsay,
of this wonderful and glorious dispensation which hath so
much the more of the wisdom and glory of God in it,
as it`'s contrary to the nature of man`'s spirit, will, and wisdom.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VII.
As there can be nothing more opposite to the natural
will and wisdom of man than this silent waiting upon God,
so neither can it be obtained nor rightly comprehended by man but as he layeth down
his own wisdom and will so as to be content to be thoroughly subject to God.
And therefore it was not preached, nor can be so practised,
but by such as find no outward ceremony, no observations, no words,
yea not the best and purest words, even the words of Scripture,
able to satisfy their weary and afflicted souls; because where all these may be,
the life, power, and virtue which make such things effectual may be wanting.
Such, I say,
were necessitated to cease from all outwards and to be silent before the Lord,
and being directed to that inward principle of Life
and Light in themselves as the most excellent teacher,
which "`can never be removed into a corner,`"^
footnote:[Isa. 30:20.]
came thereby to be learned to wait upon God in the
measure of life and grace received from him,
and to cease from their own forward words and actings in the natural
willing and comprehension and feel after this inward Seed of Life;
that, as it moveth, they may move with it and be acted by its power and influenced,
whether to pray, preach or sing.
And so from this principle of man`'s being silent and not acting in the things
of God of himself until thus acted by God`'s Light and Grace in the heart,
did naturally spring that manner of sitting silent
together and waiting together upon the Lord.
For many thus principled, meeting together in the pure fear of the Lord,
did not apply themselves presently to speak, pray, or sing, etc.,
being afraid to be found acting forwardly in their own wills,
but each made it their work to retire inwardly to the measure of Grace in themselves,
not only being silent as to words but even abstaining from all their own thoughts,
imaginations and desires,
so watching in a holy dependence upon the Lord and meeting together not only
outwardly in one place but thus inwardly in one Spirit and in one name of Jesus,
which is his Power and Virtue.
They come thereby to enjoy and feel the arisings of this Life, which,
as it prevails in each particular,
becomes as a flood of refreshment and overspreads the whole meeting,
for man and man`'s part and wisdom being denied and chained down in every individual,
and God exalted, and his Grace in dominion in the heart,
thus his Name comes to be one in all, and his glory breaks forth and covers all;
and there is such a holy awe and reverence upon every
soul that if the natural part should arise in any,
or the wise part, or what is not one with the Life,
it would presently be chained down and judged out.
And when any are through the breaking forth of this power
constrained to utter a sentence of exhortation or praise,
or to breathe to the Lord in prayer, then all are sensible of it;
for the same Life in them answers to it "`as in water face answereth to face.`"^
footnote:[Prov. 27:19.]

This is that divine and spiritual worship which the world neither knoweth nor understandeth,
which the vulture`'s eye seeth not into.
Yet many and great are the advantages which my soul
with many others have tasted of hereby,
and which would be found of all such as would seriously apply themselves hereunto.
For when people are gathered thus together, not merely to hear men nor depend upon them,
but all are inwardly taught to stay their minds upon the Lord^
footnote:[Isa. 10:20; 26:3.]
and wait for his appearance in their hearts,
thereby the forward working of the spirit of man is stayed
and hindered from mixing itself with the worship of God;
and the form of this worship is so naked and void of all outward
and worldly splendor that all occasion for man`'s wisdom to be exercised
in that superstition and idolatry hath no lodging here;
and so there being also an inward quietness and retiredness of mind,
the witness of God ariseth in the heart,
and the Light of Christ shineth whereby the soul cometh to see its own condition.
And there being many joined together in this same work,
there is an inward travail and wrestling; and also, as the measure of Grace is abode in,
an overcoming of the power and spirit of darkness;
and thus we are often greatly strengthened and renewed in the spirits of our minds^
footnote:[Eph. 4:23.]
without a word,
and we enjoy and possess the holy fellowship and "`communion of the body
and blood of Christ,`" by which our inward man is nourished and fed.
Which makes us not to dote upon outward water and bread and wine in our spiritual things.

Now as many thus gathered together grow up in the strength, power, and virtue of Truth,
and as Truth comes thus to have victory & dominion in their souls,
then they receive an utterance & speak steadily to the edification of their brethren,
and the pure Life hath a free passage through them,
and what is thus spoken edifieth the body indeed.
Such is the evident certainty of that divine strength that is communicated
by thus meeting together and waiting in silence upon God,
that sometimes, when one hath come in that hath been unwatchful,
and wandering in his mind, or suddenly out of the hurry of outward business,
& so not inwardly gathered with the rest, so soon as he retires himself inwardly,
this Power, being in a good measure raised in the whole meeting,
will suddenly lay hold upon his spirit,
and wonderfully help to raise up the good in him
and beget him into the sense of the same Power,
to the melting and warming of his heart,
even as the warmth would take hold upon a man that is cold, coming in to a stove,
or as a flame will lay hold upon some little combustible matter lying near unto it;
yea if it fall out that several met together be straying in their minds,
though outwardly silent,
and so wandering from the measure of grace in themselves (which through the working
of the enemy and negligence of some may fall out) if either one come in,
or may be in, who is watchful, and in whom the Life is raised in a great measure,
as that one keeps his place he will feel a secret travail for the
rest in a sympathy with the Seed which is oppressed in
the other and kept from arising by their thoughts and wanderings;
and as such a faithful one waits in the Light, and keeps in this divine work,
God oftentimes answers the secret travail and breathings
of his own Seed through such a one,
so that the rest will find themselves secretly smitten without words,
and that one will be as a midwife, through the secret travail of his soul,
to bring forth the Life in them,
just as a little water thrown into a pump brings up the rest,
whereby Life will come to be raised in all and the vain imaginations brought down,
and such a one is felt by the rest to minister life unto them without words;
yea sometimes when there is not a word in the meeting, but all are silently waiting,
if one come in that is rude and wicked and in whom the power of darkness prevaileth much,
perhaps with an intention to mock or do mischief,
if the whole meeting be gathered into the Life, and it be raised in a good measure,
it will strike terror into such an one, and he will feel himself unable to resist,
but by the secret strength and virtue thereof the
power of darkness in him will be chained down,
and if the day of his visitation be not expired it will reach to the measure
of Grace in him and raise it up to the redeeming of his soul,
and this we often bear witness of, so that we have had frequent occasion,
in this respect, since God hath gathered us to be a people,
to renew this old saying of many, "`Is Saul also among the prophets?`"^
footnote:[1 Sam. 10:12.]
For not a few have come to be convinced of the Truth after this manner,
of which I myself, in a part, am a true witness,
who not by strength of arguments or by a particular disquisition
of each doctrine and convincement of my understanding thereby,
came to receive and bear witness of the Truth,
but by being secretly reached by this Life:
for when I came into the silent assemblies of God`'s people
I felt a secret power among them which touched my heart,
and as I gave way unto it, I found the evil weakening in me and the good raised up,
and so I became thus knit and united unto them,
hungering more and more after the increase of this Power
and Life whereby I might feel myself perfectly redeemed:
and indeed this is the surest way to become a Christian,
to whom afterwards the knowledge and understanding of principles
will not be wanting but will grow up so much as is needful,
as the natural fruit of this good root,
and such a knowledge will not be barren nor unfruitful after this manner.
We desire therefore all that come among us to be proselyted,
knowing that though thousands should be convinced
in their understandings of all the truths we maintain,
yet if they were not sensible of this inward Life,
and their souls not changed from unrighteousness to righteousness,
they could add nothing to us;
for this is that cement whereby we are joined "`as to the Lord,`"^
footnote:[1 Cor. 6:17.]
so to one another, and without this none can worship with us.
Yea if such should come among us and from that understanding and
convincement they have of the Truth speak ever so true things,
and utter them forth with ever so much excellency of speech,
if this Life were wanting it would not edify us at all but
be as "`sounding brass or a tinkling cymbal`" (1 Cor. 13:1).

[.small-break]
'''

// lint-disable invalid-characters "§"
§VIII.
Our work then and worship is, when we meet together,
for everyone to watch and wait upon God in themselves
& to be gathered from all visibles thereunto.
And as everyone is thus stated they come to find the good
arise over the evil and the pure over the impure,
in which God reveals himself and draweth near to every individual,
and so he in the midst in the general.
Whereby each not only partakes of the particular refreshment and strength
which comes from the good in himself but is a sharer in the whole body,
as being a living member of the body, having a joint fellowship and communion with all;
and as this worship is steadfastly preached and kept to it becomes easy,
though it be very hard at first to the natural man,
whose roving imaginations and running worldly desires are not so easily brought to silence;
and therefore the Lord oftentimes,
when any turn towards him and have true desires thus to wait upon him,
and find great difficulty through the unstayedness of their minds,
doth in condescension and compassion cause his Power
to break forth in a more strong and powerful manner;
and when the mind sinks down and waits for the appearance of life,
and that the power of darkness in the soul wrestles and works against it,
then the good Seed, as it ariseth, will be found to work as physic in the soul,
especially if such a weak one be in the assembly of divers
others in whom the life is arisen in greater dominion,
and through the contrary workings of the power of darkness
there will be found an inward striving in the soul,
as really in the mystery as ever Esau and Jacob strove in Rebecca`'s womb.
And from this inward travail, while the darkness seeks to obscure the Light,
and the Light break through the darkness (which it always will do if the
soul give not its strength to the darkness) there will be such a painful
travail found in the soul that will even work upon the outward man;
so that oftentimes through the working thereof the body will be greatly shaken,
and many groans and sighs and tears, even as the pangs of a woman in travail,
will lay hold upon it; yea and this not only as to one, but when the enemy (who,
when the children of God assemble together,
is not wanting to be present to see if he can let^
footnote:[_let_ +++=+++ prevent.]
their comfort) hath prevailed in any measure in a whole meeting,
and strongly worketh against it by spreading and propagating his dark power and
by drawing out the minds of such as are met from the Life in them,
as they come to be sensible of this power of his that works against
them and to wrestle with it by the "`armour of light,`" sometimes
the power of God will break forth into a whole meeting,
and there will be such an inward travail,
while each is seeking to overcome the evil in themselves,
that by the strong contrary workings of these opposite powers,
like the going of two contrary tides,
every individual will be strongly exercised as in a day of battle;
and thereby trembling and a motion of body will be upon most, if not upon all, which,
as the power of Truth prevails,
will from pangs and groans end with a sweet sound of thanksgiving and praise,
and from this the name of "`Quakers,`" i.e., _Tremblers,_
was first reproachfully cast upon us, which though it be none of our choosing,
yet in this respect we are not ashamed of it but have rather reason to rejoice therefore,
even that we are sensible of this Power that hath oftentimes laid hold
of our adversaries and made them yield unto us and join with us,
and confess to the Truth before they had any distinct
or discursive knowledge of our doctrines,
so that sometimes many at one meeting have been thus convinced,
and this Power would sometimes also reach to and wonderfully work even in little children,
to the admiration and astonishment of many.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IX. Many are the blessed experiences which
I could relate of this silence and manner of worship,
yet I do not so much commend and speak of silence as if we had a law in it to shut out^
footnote:[Later editors replace "`as if we had a law in it to shut
out`" with "`as if we had bound ourselves by any law to exclude.`"]
praying or preaching, or tied ourselves thereunto; not at all:
for as our worship consisteth not in words, so neither in silence, as silence;
but in an holy dependence of the mind upon God,
from which dependence silence necessarily follows in the first place,
until words can be brought forth which are from God`'s Spirit;
and God is not wanting to move _in_ his children to bring
forth words of exhortation or prayer when it is needful,
so that of the many gatherings and meetings of such as are convinced of the truth there
is scarce any in whom God raiseth not up some or other to minister to his brethren,
that there are few meetings that are altogether silent.
For when many are met together in this one Life and Name,
it doth most naturally and frequently excite them to pray to and praise
God and stir up one another by mutual exhortation and instructions;
yet we judge it needful there be in the first place some time of silence,
during which every one may be gathered inward to the Word and Gift of Grace,
from which he that ministereth may receive strength to bring forth what he ministereth,
and that they that hear may have a sense to discern betwixt the precious and the vile,
and not to hurry into the exercise of these things so soon as the bell rings,
as other Christians do;
yea and we doubt not but assuredly know that the meeting may be good and refreshful,
though from the sitting down to the rising up thereof
there hath not been a word as outwardly spoken;
and yet Life may have been known to abound in each particular,
and an inward growing up therein and thereby,
yea so as words might have been spoken acceptably and from the Life;
yet there being no absolute necessity laid upon any so to do,
all might have chosen rather quietly and silently
to possess and enjoy the Lord in themselves,
which is very sweet and comfortable to the soul that hath thus
learned to be gathered out of all its own thoughts and workings,
to feel the Lord to bring forth both the will and the deed,
which many can declare by a blessed experience,
though indeed it cannot but be hard for the natural man to receive or believe this doctrine;
and therefore it must be rather by a sensible experience,
and by coming to make proof of it,
than by arguments that such can be convinced of this thing,
seeing it is not enough to believe it if they come not also to enjoy and possess it;
yet in condescension to and for the sake of such as may be the
more willing to apply themselves to the practice and experience
hereof that they found their understandings convinced of it,
and that it is founded upon Scripture and reason,
I find a freedom of mind to add some few considerations
of this kind for the confirmation hereof,
besides what is before mentioned of our experience.

[.small-break]
'''

// lint-disable invalid-characters "§"
§X. That to wait upon God, and to watch before him,
is a duty incumbent upon all, I suppose none will deny;
and that this also is a part of worship will not be called in question,
since there is scarce any other so frequently commanded in the holy Scriptures,
as may appear from Ps. 27:14; 37:7,34; Prov. 20:22; Isa. 30:18; Hosea 12:6;
Zach.
3:8; Matt. 24:42; 25:13; 26:41; Mark 13:33,35,37; Luke 21:36; Acts 1:4; 20:31;
1 Cor. 16:13; Col. 4:2; 1 Thess. 5:6; 2 Tim. 4:5; 1 Pet. 4:7.
Also this duty is often recommended with very great and precious promises,
as Ps. 25:3; 37:9; 69:6; Isa. 40:31; Lam. 3:25-26,
"`They that wait upon the Lord shall renew their strength,`" etc. Now,
how is this waiting upon God, or watching before him,
but by this silence of which we have spoken?
Which, as it is in itself a great and principal duty,
so it necessarily in order both of nature and time precedeth all other.
But that it may be the better and more perfectly understood,
as it is not only an outward silence of the body but an inward silence
of the mind from all its own imaginations and self-cogitations,
let it be considered according to Truth and to the principles
and doctrines heretofore affirmed and proven,
that man is to be considered in a twofold respect, to wit: in his natural, unregenerate,
and fallen state; and in his spiritual and renewed condition;
from whence ariseth that distinction of the "`natural`"
and "`spiritual man`" so much used by the apostle,
and heretofore spoken of,
also these two births of the mind proceed from the two seeds in man respectively, to wit,
the good Seed and the evil.
And from the evil seed doth not only proceed all manner
of gross and abominable wickedness and profanity,
but also hypocrisy, and these wickednesses which the Scripture calls spiritual,
because it is the serpent working in and by the natural man in things that are spiritual,
which having a show and appearance of good are so much the more hurtful and dangerous,
as it is "`Satan transformed and transforming himself into an angel of light`";
and therefore doth the Scripture so pressingly and frequently (as
we have heretofore had occasion to observe) shut out and exclude
the natural man from meddling with the things of God,
denying his endeavours therein,
though acted and performed by the most eminent of his parts, as of wisdom and utterance.

Also this spiritual wickedness is of two sorts,
though both one in kind as proceeding from one root, yet differing in their degrees,
and in the subjects also sometimes.
The one is, when as the natural man is meddling in and working in the things of religion,
doth from his own conceptions and divinations affirm or propose wrong
and erroneous notions and opinions of God and things spiritual,
and invent superstitions, ceremonies, observations, and rites in worship,
from whence have sprung all the heresies and superstitions that are among Christians.
The other is, when as the natural man, from a mere conviction of his understanding,
doth in the forwardness of his own will and by his own natural strength,
without the influence and leading of God`'s Spirit,
go about either in his understanding to imagine, conceive, or think of the things of God,
or actually to perform them by preaching or praying.
The first is a missing both in matter and form.
The second is a retaining of the form without the Life and Substance of Christianity
because Christian religion consisteth not in a mere belief of true doctrines,
or a mere performance of acts good in themselves,
or else the bare letter of the Scripture, though spoken by a drunkard or a devil,
might be said to be spirit and life, which I judge none will be so absurd as to affirm:
and also it would follow that where the form of godliness is there the power is also,
which is contrary to the express words of the apostle.
For the form of godliness cannot be said to be,
where either the notions and opinions believed are erroneous and ungodly,
or the acts performed evil and wicked; for then it would be the form of ungodliness,
and not of godliness.
But of this further hereafter, when we shall speak particularly of preaching and praying.
Now though this last be not so bad as the former, yet hath it made way for it;
for men having first departed from the Life and Substance of true Religion and worship,
to wit, from the inward power and virtue of the Spirit,
so as therein to act and thereby to have all their actions enlivened,
have only retained the form and show, to wit,
the true words and appearance and so acting in their
own natural and unrenewed wills in this form,
the form could not but quickly decay and be vitiated,
for the working and active spirit of man could not contain
itself within the simplicity and plainness of Truth,
but giving way to his own numerous inventions and imaginations,
began to vary in the form and adapt it to his own inventions,
until by degrees the form of godliness for the most part came to be lost,
as well as the power.
For this kind of idolatry, whereby man loveth, idolizeth,
and huggeth his own conceptions, inventions, and product of his own brain,
is so incident unto him, and seated in his fallen nature,
that so long as his natural spirit is the first author and actor of him,
and is that by which he only is guided and moved in his worship towards God,
so as not first to wait for another Guide to direct him,
he can never perform the pure spiritual worship nor
bring forth anything but the fruit of the first,
fallen, natural and corrupt root.
Wherefore the time appointed of God being come wherein by Jesus
Christ he hath been pleased to restore the true spiritual worship;
and the outward form of worship which was appointed by God to the Jews,
and whereof the manner and time of its performance
was particularly determined by God himself,
being come to an end, we find that Jesus Christ, the author of the Christian religion,
prescribes no set form of worship to his children under
the more pure administration of the New Covenant,^
footnote:[Obj. If any object here that the Lord`'s prayer is a prescribed form of prayer,
and therefore of worship given by Christ to his children:
{footnote-paragraph-split}
Answ. I answer, first, this cannot be objected by any sort of Christians that I know,
because there are none who use not other prayers or that limit their worship to this.
Secondly, this was commanded to the disciples while yet weak,
before they had received the dispensation of the Gospel,
not that they should only use it in praying,
but that he might show the by one example how that their prayers ought to be short,
and not like the long prayers of the Pharisee;
and that this was the use of it appears by all their prayers,
which divers saints afterwards made use of, whereof the Scripture makes mention;
for none made use of this, neither repeated it, but used other words,
according as the thing required and as the Spirit gave utterance.
Thirdly,
that this ought so to be understood appears from Rom. 8:26
of which afterwards mention shall be made at greater length,
where the apostle saith, "`We know not what we should pray for as we ought;
but the Spirit itself maketh intercession for us,`" etc. But if this
prayer had been such a prescribed form of prayer to the church,
that had not been true, neither had they been ignorant what to pray for,
nor should they have needed the help of the Spirit to teach them.]
save that he only tells them that the worship now to be performed is spiritual,
and in the Spirit;
and it`'s especially to be observed that in the whole New Testament there is no
order nor command given in this thing but to follow the revelations of the Spirit,
save only that general, of meeting together:
a thing dearly owned and diligently practised by us, as shall hereafter more appear.

True it is, mention is made of the duties of praying, preaching and singing;
but what order or method should be kept in so doing,
or that presently they should be set about so soon as the saints are gathered,
there is not one word to be found;
yea these duties (as shall afterwards be made appear) are always annexed to the assistance,
leadings, and motions of God`'s Spirit.
Since then man in his natural state is thus excluded
from acting or moving in things spiritual,
how or what way shall he exercise this first and previous duty of waiting upon God,
but by silence, and by bringing that natural part to silence?
Which is no other ways but by abstaining from his own thoughts and imaginations
and from all the self-workings and motions of his own mind,
as well in things materially good, as evil, that he being silent, God may speak in him,
and the good Seed may arise.
This, though hard to the natural man,
is so answerable to reason and even natural experience in other things,
that it cannot be denied.
He, that cometh to learn of a master,
if he expect to hear his master & be instructed by him,
must not continually be speaking of the matter to be taught and never be quiet,
otherwise how shall his master have time to instruct him?
yea though the scholar were never so earnest to learn the science,
yet would the master have reason to reprove him, as untoward & indocile,
if he would always be meddling of himself, and still speaking,
and not wait in silence patiently to hear his master instructing and teaching him,
who ought not to open a mouth until by his master he were commanded and allowed so to do.
So also, if one were about to attend a great prince,
he would be thought an impertinent and imprudent servant, who,
while he ought patiently and readily to wait,
that he might answer the king when he speaks,
and have his eye upon him to observe the least motions and inclinations of his will,
and to do accordingly, would be still deafening him with discourse,
though it were in praises of him, and running to and fro,
without any particular and immediate order to do things,
that perhaps might be good in themselves,
or might have been commanded at other times to others.
Would the kings of the earth accept of such servants, or service?

Since then we are commanded to "`wait upon God diligently,`" and in so doing it
is promised that our "`strength shall be renewed,`" this waiting cannot be performed
but by a silence or cessation of the natural part on our side,
since God manifests himself not to the outward man or senses, so much as to the inward,
to wit, to the soul and spirit;
if the soul be still thinking and working in her
own will and busily exercised in her own imaginations,
though the matters as in themselves may be good concerning God,
yet thereby she incapacitates herself from discerning the "`still,
small voice`" of the Spirit, and so hurts herself greatly,
in that she neglects her chief business of waiting upon the Lord;
nothing less than if I should busy myself crying out and speaking of a business,
while in the meantime I neglect to hear one who is quietly whispering into my ear,
and informing me in these things which are most needful
for me to hear and know concerning that business.
And since it is the chief work of a Christian to know the natural will,
in its own proper motions, crucified, that God may both move in the act and in the will,
the Lord chiefly regards this profound subjection and self-denial.
For some men please themselves as much,
and gratify their own sensual wills and humors in high and curious speculations of religion,
affecting a name and reputation that way, or because those things by custom,
or other-ways, are become pleasant and habitual to them,
though not a whit more regenerated or inwardly sanctified in their spirits,
as others gratify their lusts in acts of sensuality,
and therefore both are alike hurtful to men, and sinful in the sight of God,
it being nothing but the mere fruit and effect of
man`'s natural and unrenewed will and spirit.
Yea should one (as many no doubt do) from a sense of sin
and fear of punishment seek to terrify themselves from sin,
by multiplying thoughts of death, hell and judgment,
and by presenting to their imaginations the happiness and joys of heaven,
and also by multiplying prayers and other religious performances,
as these things could never deliver him from one iniquity without
the secret and inward power of God`'s Spirit and Grace,
so would they signify no more than the fig-leaves
wherewith Adam thought to cover his nakedness;
and seeing it is only the product of man`'s own natural will,
proceeding from a self-love and seeking to save himself,
and not arising purely from that divine Seed of Righteousness
which is given of God to all for grace and salvation,
it is rejected of God and no ways acceptable unto him, since the natural man, as natural,
while he stands in that state, is with all his arts, parts, and actings,
reprobated by him.
This great duty then of waiting upon God must needs be exercised in man`'s denying self,
both inwardly and outwardly, in a still and mere dependence upon God,
in abstracting from all the workings, imaginations and speculations of his own mind,
that being emptied, as it were, of himself;
and so thoroughly crucified to the natural products
thereof he may be fit to receive the Lord,
who will have no co-partner nor co-rival of his glory and power.
And man being thus stated,
the little Seed of Righteousness which God hath planted
in his soul and Christ hath purchased for him,
even the measure of Grace and Life (which is burdened and
crucified by man`'s natural thoughts and imaginations),
receives a place to arise and becometh a holy birth and geniture in man,
and is that divine air in and by which man`'s soul and spirit comes to be leavened.
And by waiting therein he comes to be accepted in the sight of God,
to stand in his presence, hear his voice, and observe the motions of his holy Spirit.
And so man`'s place is to wait in this;
and as hereby there are any objects presented to
his mind concerning God or things relating to religion,
his soul may be exercised in them without hurt and to the
great profit both of himself and others because those things
have their rise not from his own will but from God`'s Spirit.
And therefore,
as in the arisings and movings of this his mind is
still to be exercised in thinking and meditating,
so also in the more obvious acts of preaching and praying.
And so it may hence appear we are not against meditation,
as some have sought falsely to infer from our doctrine;
but we are against the thoughts and imaginations of the natural man in his own will,
from which all errors and heresies concerning the
Christian religion in the whole world have proceeded.
But if it please God at any time when one or more are waiting upon him,
not to present such objects as give them occasion
to exercise their minds in thoughts and imaginations,
but purely to keep them in this holy dependence, and, as they persist therein,
to cause his secret refreshment and the pure incomes
of his holy Life to flow in upon them,
then they have good reason to be content,
because by this (as we know by good and blessed experience) the soul is more strengthened,
renewed and confirmed in the love of God, and armed against the power of sin,
than any ways else;
this being a foretaste of that real and sensible enjoyment
of God which the saints in heaven daily possess,
which God frequently affords to his children here for their comfort and encouragement,
especially when they are assembled together to wait upon him.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XI. For there are two contrary powers or spirits, to wit,
the power and spirit of this world, in which the Prince of darkness bears rule,
and over as many as are acted by it and work from it, and the power of the Spirit of God,
in which God worketh and beareth rule, and over as many as act in and from it.
So whatever be the things that a man thinketh of or acteth in,
however spiritual or religious, as to the notion or form of them,
so long as he acteth and moveth in the natural and corrupt spirit and will, and not from,
in and by the Power of God, he sinneth in all and is not accepted of God.
For hence both the "`ploughing and praying of the wicked is sin`";^
footnote:[Prov. 21:4.]
as also whatever a man acts in and from the Spirit and power of God,
having his understanding and will influenced and moved by it,
whether it be actions religious, civil, or even natural,
he is accepted in so doing in the sight of God and is blessed in them.^
footnote:[James 1:25.]
From what is said it doth appear how frivolous and impertinent their objection is,
that say they wait upon God in praying and preaching,
since waiting doth of itself imply a passive dependence, rather than an acting;
and since it is, and shall yet be more shown,
that preaching and praying without the Spirit is
an offending of God not a waiting upon him,
and that praying and preaching by the Spirit presupposes necessarily a silent waiting,
for to feel the motions and influence of the Spirit to lead thereunto.
And lastly, that in several of these places where praying is commanded,
as Matt. 26:41; Mark 13:33; Luke 21:36; 1 Pet. 4:7,
watching is specially prefixed, as a previous preparation thereunto.
So that we do well and certainly conclude that since waiting
and watching are so particularly commanded and recommended,
and this cannot be truly performed but in this inward silence
of the mind from men`'s own thoughts and imaginations,
this silence is and must necessarily be a special and principal part of God`'s worship.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XII.
But secondly:
the excellency of this silent waiting upon God doth
appear in that it is impossible for the enemy,
viz. the devil, to counterfeit it,
so as for any soul to be deceived or deluded by him in the exercise thereof.
Now, in all other matters he may mix himself in with the natural mind of man,
and so by transforming himself he may deceive the soul by
busying it about things perhaps innocent in themselves,
while yet he keeps them from beholding the pure Light
of Christ and so from knowing distinctly his duty,
and doing of it.
For that envious spirit of man`'s eternal happiness knoweth well how to accommodate himself
and fit his snares for all the several dispositions and inclinations of men;
if he find one not fit to be engaged with gross sins or worldly lusts,
but rather averse from them and religiously inclined,
he can fit himself to beguile such a one by suffering his thoughts and imaginations
to run upon spiritual matters and so hurry them to work,
act, and meditate in their own wills,
for he well knoweth that so long as self bears rule,
and the Spirit of God is not the principal and chief actor,
man is not put out of his reach; so therefore he can accompany the priest to the altar,
the preacher to the pulpit, the zealot to his prayers,
yea the doctor and professor of divinity to his study,
and there he can cheerfully suffer him to labour and work among his books,
yea and help him to find out and invent subtle distinctions
and quiddities by which both his mind,
and others through him,
may be kept from heeding God`'s Light in the conscience and waiting upon him.
There is not any exercise whatsoever wherein he cannot enter and have a chief place,
so as the soul many times cannot discern it, except in this alone;
for he can only work in and by the natural man and his faculties,
by secretly acting upon his imaginations and desires, etc., and therefore when he,
to wit the natural man, is silent, there he must also stand.
And therefore, when the soul comes to this silence, and, as it were,
is brought to nothingness, as to her own workings, then the devil is shut out;
for the pure presence of God and shining of his Light he cannot abide,
because so long as a man is thinking and meditating as of himself,
he cannot be sure but the devil is influencing him therein,
but when he comes wholly to be silent, as the pure Light of God shines in upon him,
then he is sure that the devil is shut out, for beyond the imaginations he cannot go,
which we often find by sensible experience.
For he that of old is said to have come to the gathering together
of the children of God is not wanting to come to our assemblies,
and indeed he can well enter and work in a meeting that is silent only as to words,
either by keeping the minds in various thoughts and imaginations,
or by stupefying them so as to overwhelm them with a spirit of heaviness and slothfulness;
but when we retire out of all and are turned in,
both by being diligent and watchful upon the one hand,
and also silent and retired out of all our thoughts upon the other,
as we abide in this sure place, we feel ourselves out of his reach;
yea oftentimes the power and glory of God will break forth and appear,
just as the bright sun through many clouds and mists,
to the dispelling of that power of darkness;
which will also be sensibly felt seeking to cloud and darken the mind,
and wholly to keep it from purely waiting upon God.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIII.
Thirdly: the excellency of this worship doth appear,
in that it can neither be stopped nor interrupted by the malice of men or devils,
as all others can.
Now interruptions and stoppings of worship may be understood in a two-fold respect,
either as we are hindered from meeting,
as being outwardly by violence separated one from another;
or when permitted to meet together, as we are interrupted by the tumult,
noise and confusion which such as are malicious may use to molest or distract us.
Now in both these respects this worship doth greatly overpass all others,
for how far soever people be separate or hindered from coming together,
yet as every one is inwardly gathered to the measure of life in
himself there is a secret unity and fellowship enjoyed,
which the devil and all his instruments can never break or hinder.
But secondly, it doth as well appear,
as to those molestations which occur when we are met together,
what advantage this true and spiritual worship gives us beyond all others;
seeing in despite of a thousand interruptions and abuses,
one of which were sufficient to have stopped all other sorts of Christians,
we have been able, through the nature of this worship,
to keep it uninterrupted as to God and also at the same time to
show forth an example of our Christian patience towards all,
even oftentimes to the reaching and convincing of our opposers;
for there is no sort of worship used by others which can subsist (though
they be permitted to meet) unless they be either authorized and protected
by the magistrate or defend themselves with the arm of flesh,
but we at the same time exercise worship towards God and also patiently bear the reproaches
and ignominies which Christ prophesied should be so incident and frequent to Christians;
for how can the Papists say their Mass if there be
any there to disturb and interrupt them?
Do but take away the Mass book, the chalice, the host, or the priest`'s garments, yea,
do but spill the water or the wine,
or blow out the candles (a thing quickly done) and the whole business is marred,
and no sacrifice can be offered.
Take from the Lutherans or Episcopalians their liturgy
or [.book-title]#Common Prayer Book# and no service can be said.
Remove from the Calvinists, Arminians, Socinians, Independents, or Anabaptists,
the pulpit, the Bible, and the hourglass, or make but such a noise,
as the voice of the preacher cannot be heard,
or disturb him but so before he come, or strip him of his Bible and his books,
and he must be dumb:
for they all think it an heresy to wait to speak as the Spirit of God give utterance;
and thus easily their whole worship may be marred.
But where people meet together, and their worship consisteth not in such outward acts,
and they depend not upon anyone`'s speaking but merely sit
down to wait upon God and to be gathered out of all visibles,
and to feel the Lord in Spirit, none of these things can hinder them;
of which we may say of a truth we are sensible witnesses; for when the magistrates,
stirred up by the malice and envy of our opposers, have used all means possible,
and yet in vain, to deter us from meeting together,
and that openly and publicly in our own hired houses for that purpose, both death,
banishments, imprisonments, finings, beatings, whippings,
and other such devilish inventions have proved ineffectual
to terrify us from our holy assemblies,
I say, and we having thus oftentimes purchased our liberty to meet by deep sufferings,
our opposers have then taken another way,
by turning in upon us the worst & wickedest people, yea the very off-scourings of men,
who by all manner of inhuman, beastly and brutish behaviour have sought to provoke us,
weary us, and molest us, but in vain.
It would be almost incredible to declare, and indeed a shame,
that among men pretending to be Christians it should be mentioned,
what things of this kind men`'s eyes have seen, and I myself, with others,
have shared of in suffering; there they have often beaten us,
and cast water and dirt upon us; there they have danced, leaped, sung,
and spoken all manner of profane and ungodly words,
offered violence and shameful behaviour to grave women and virgins, jeered,
mocked and scoffed, asking us,
"`if the Spirit was not yet come,`" and much more which were tedious here to relate;
and all this while we have been seriously and silently
sitting together and waiting upon the Lord,
so that by these things our inward and spiritual fellowship with God and one with another,
in the pure life of righteousness, hath not been hindered.
But on the contrary, the Lord,
knowing our sufferings and reproaches for his testimony`'s sake,
hath caused his power and glory more to abound among us,
and hath mightily refreshed us by the sense of his love,
which hath filled our souls,
and so much the rather as we found ourselves gathered into the "`Name of
the Lord,`" which is the "`strong tower`" of the righteous;^
footnote:[Prov. 18:10.]
whereby we felt ourselves sheltered from receiving any inward hurt through their malice,
and also that he had delivered us from that vain name and profession of Christianity
under which our opposers were not ashamed to bring forth these bitter and cursed fruits;
yea sometimes in the midst of this tumult and opposition
God would powerfully move some or other of us by his Spirit,
both to testify of that joy which, notwithstanding their malice, we enjoyed,
and powerfully to declare, in the evidence and demonstration of the Spirit,
against their folly and wickedness,
so as the power of Truth hath brought them to some measure of quietness and stillness,
and stopped the impetuous streams of their fury and madness;
that as ever of old Moses by his rod divided the
waves of the Red Sea that the Israelites might pass,
so God hath thus by his Spirit made a way for us in the midst of this raging wickedness,
peaceably to enjoy and possess him, and accomplish our worship to him:
so that sometimes upon such occasions several of our opposers and
interrupters have hereby been convinced of the Truth and gathered
from being persecutors to be sufferers with us.
And let it not be forgotten,
but let it be inscribed and abide for a constant remembrance of the thing,
that in these beastly and brutish pranks used to molest us in our spiritual meetings,
none have been more busy, than the young students of the universities,
who were learning philosophy and divinity, so called,
and many of them preparing themselves for the ministry.
Should we commit to writing,
all the abominations committed in this respect by the young fry of the clergy,
it would make no small volume; as the churches of Christ,
gathered into his pure worship in Oxford and Cambridge in England,
and Edinburgh and Aberdeen in Scotland, where the universities are,
can well bear witness.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIV.
Moreover,
in this we know that we are partakers of the New Covenant`'s dispensation,
and disciples of Christ indeed,
sharing with him in that spiritual worship which
is performed in the Spirit and in Truth,
because as he was, so are we in this world.
For the Old Covenant worship had an outward glory, temple, and ceremonies,
and was full of outward splendor and majesty, having an outward tabernacle and altar,
beautified with gold, silver and precious stones;
and their sacrifices were tied to an outward particular place,
even the outward Mount Zion;
and those that prayed behooved to pray with their faces towards that outward temple,
and therefore all this behooved to be protected by an outward arm,
nor could the Jews peaceably have enjoyed it but when they
were secured from the violence of their outward enemies,
and therefore when at any time their enemies prevailed over
them their glory was darkened and their sacrifices stopped,
& the face of their worship marred; hence they complain, lament,
and bewail the destroying of the temple, as a loss irreparable.
But Jesus Christ, the author and institutor of the New Covenant worship,
testifies that God is neither to be worshipped in this nor that place,
but in the Spirit and in Truth;
and forasmuch as his "`kingdom is not of this world,`"^
footnote:[John 18:36.]
neither doth his worship consist in it or need either the wisdom, glory,
riches or splendor of this world to beautify or adorn it,
nor yet the outward power or arm of flesh to maintain, uphold, or protect it;
but it is and may be performed by those that are spiritually minded,
notwithstanding all the opposition, violence, and malice of men;
because it being purely spiritual,
it is out of the reach of natural men to interrupt or molest it.
Even as Jesus Christ, the author thereof,
did enjoy and possess his spiritual kingdom while oppressed, persecuted,
and rejected of men, and as, in despite of the malice and rage of the devil,
"`he spoiled principalities and powers, triumphing over them,
and through death destroyed him that had the power of death, that is,
the devil`";^
footnote:[Col. 2:15.]
so also all his followers both can and do worship him not
only without the arm of flesh to protect them,
but even when oppressed.
For their worship, being spiritual,
is by the power of the Spirit defended and maintained;
but such worships as are carnal and consist in carnal and outward ceremonies and observations
need a carnal and outward arm to protect them and defend them,
else they cannot stand and subsist.
And therefore it appears that the several worships of our
opposers both Papists and Protestants are of this kind,
and not the true spiritual and New Covenant worship of Christ, because,
as hath been observed,
they cannot stand without the protection or countenance of the outward magistrate,
neither can be performed if there be the least opposition:
for they are not in the patience of Jesus, to serve and worship him with sufferings,
ignominies, calumnies, and reproaches.
And from hence have sprung all those wars, fightings, and bloodshed among Christians,
while each by the arm of flesh endeavoured to defend and protect their own way and worship;
and from this also sprung up that monstrous opinion of persecution,
of which we shall speak more at length hereafter.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XV. But fourthly,
the nature of this worship which is performed by the operation of the Spirit,
the natural man being silent, doth appear from these words of Christ (John 4:23-24):
"`But the hour cometh, and now is,
when the true worshippers shall worship the Father in Spirit and in Truth:
for the Father seeketh such to worship him.
God is a Spirit and they that worship him,
must worship him in Spirit and in Truth.`" This testimony
is the more specially to be observed,
for that it is both the first, chiefest, and most ample testimony,
which Christ gives us of his Christian worship,
as different and contradistinguished from that under the Law.
For first,
he showeth that the season is now come wherein the
worship must be "`in Spirit and in Truth,
for the Father seeketh such to worship him`":
so then it is no more a worship consisting in outward observations,
to be performed by man at set times or opportunities,
which he can do in his own will and by his own natural strength:
for else it would not differ in matter but only in
some circumstances from that under the law.
Next, as for a reason of this worship, we need not to give any other,
and indeed none can give a better than that which Christ giveth,
which I think should be sufficient to satisfy every Christian, to wit, "`God is a Spirit,
and they that worship him must worship him in Spirit and in Truth.`"
As this ought to be received because it is the words of Christ,
so also it is founded upon so clear a demonstration
of reason as sufficiently evidenceth its verity.
For Christ excellently argues from the analogy that ought to be
betwixt the object and the worship directed thereunto:

[.syllogism]
* _Arg.:_ God is a Spirit;
* Therefore he must be worshipped in Spirit.

This is so certain that it can suffer no contradiction;
yea and this analogy is so necessary to be minded, that under the Law,
when God instituted and appointed that ceremonial worship to the Jews,
because that worship was outward, that there might be an analogy,
he saw it necessary to condescend to them as in a special manner,
to dwell betwixt the cherubims within the tabernacle,
and afterwards to make the temple of Jerusalem in a sort his habitation
and cause something of an outward glory and majesty to appear,
by causing fire from heaven to consume the sacrifices
and filling the temple with a cloud,
through and by which mediums, visible to the outward eye,
he manifested himself proportionably to that outward
worship which he had commanded them to perform.
So now under the New Covenant,
he seeing meet in his heavenly wisdom to lead his
children in a path more heavenly and spiritual,
and in a way both more easy and familiar,
and also purposing to disappoint carnal and outward observations,
that his may have an eye more to an inward glory and kingdom than to an outward,
he hath given us for an example hereof the appearance of his beloved Son,
the Lord Jesus Christ,
who (instead that Moses delivered the Israelites out of their outward bondage,
and by outwardly destroying their enemies) hath delivered and doth
deliver us by suffering and dying by the hands of his enemies,
thereby triumphing over the devil, and his and our inward enemies,
and delivering us therefrom: he hath also instituted an inward and spiritual worship,
so that God now tieth not his people to the temple of Jerusalem
nor yet unto outward ceremonies and observations,
but taketh the heart of every Christian for a temple to dwell in,
and there immediately appeareth and giveth him directions
how to serve him in any outward acts.
Since, as Christ argueth,
"`God is a Spirit,`" he will now be worshipped in the Spirit where
he reveals himself and dwelleth with the contrite in heart;
now,
since it is the heart of man that now is become the
temple of God in which he will be worshipped,
and no more in particular outward temples (since, as blessed Stephen said,
out of the prophet, to the professing Jews of old,
"`The most High dwelleth not in temples made with hands`");^
footnote:[Acts 7:48 +++[+++citing Isa. 66:1-2 -- QHP ed.+++]+++]
as before the glory of the Lord descended to fill the outward
temple it behooved to be purified and cleansed,
and all polluted stuff removed out of it,
yea and the place for the tabernacle was overlaid with gold, the most precious,
clean and clearest of metals;
so also before God be worshipped in the inward temple
of the heart it must also be purged of its own filth,
and all its own thoughts and imaginations,
that so it may be fit to receive the Spirit of God and to be acted by it;
and doth not this directly lead us to that inward silence
of which we have spoken and exactly pointed out?
And further, this worship must be "`in Truth`"; intimating that this spiritual worship,
thus acted, is only and properly a true worship, as being that which,
for the reasons above observed, cannot be counterfeited by the enemy,
nor yet performed by the hypocrite.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XVI.
And though this worship be indeed very different from
the divers established invented worships among Christians,
and therefore may seem strange to many, yet hath it been testified of,
commended and practised by the most pious of all sorts in all ages,
by many evident testimonies might be proved,
so that from the professing and practising thereof the name of mystics hath arisen,
as of a certain sect generally commended by all,
whose writings are full both of the explanation and
of the commendation of this sort of worship,
where they plentifully assert this inward introversion and abstraction of the mind,
as they call it, from all images and thoughts and the prayer of the will;
yea they look upon this as the height of Christian perfection, so that some of them,
though professed Papists, do not doubt to affirm,
"`That such as have attained this method of worship or are
aiming at it`" (as in a book called [.book-title]#Sancta Sophia,#
put out by the English Benedictines, printed at Douay, _anno 1657, tract.
I, sect.
ii, cap.
5_) "`need not,
nor ought to trouble or busy themselves with frequent and unnecessary confessions,
with exercising corporal labours and austerities, the using of vocal voluntary prayers,
the hearing of a number of masses.
or set devotions, or exercises to saints, or prayers for the dead,
or having solicitous and distracting cares to gain
indulgences by going to such and such churches,
or adjoining oneself to confraternities, or entangling oneself with vows and promises;
because such kind of things hinder the soul from observing the operations
of the divine Spirit in it and from having liberty to follow the Spirit
whither it would draw her.`" And yet who knows not that in such kind of
observations the very substance of the Popish religion consisteth?
Yet nevertheless it appears by this and many other passages
which out of their mystic writers might be mentioned,
how they look upon this worship as excelling all other,
and that such as arrived hereunto had no absolute need of the others;
yea (see the Life of Balthazar Alvares, in the same [.book-title]#Sancta Sophia,# _tract.
III, sect.
i, cap.
7_) such as tasted of this quickly confessed that the other
forms and ceremonies of worship were useless as to them;
neither did they perform them as things necessary but merely for order or example`'s sake;
and therefore,
though some of them were so overclouded with the common darkness of their profession,
yet could they affirm that this spiritual worship
was still to be retained and sought for,
though there be a necessity of omitting their outward ceremonies.
Hence Bernard, as in many other places, so in his [.book-title]#Epistle# to one William,
abbot of the same order, saith, "`Take heed to the rule of God,
the kingdom of God is within you`";
and afterwards saying that their outward orders and rules should be observed, he adds:
"`But otherwise when it shall happen that one of those two must be omitted,
in such a case these are much rather to be omitted than those former;
for by how much the Spirit is more excellent and noble than the body,
by so much are spiritual exercises more profitable than corporal.`" Is not that then
the best of worships which the best of men in all ages and of all sects have commended,
and which is most suitable to the doctrine of Christ; I say,
is not that worship to be followed and performed?
And so much the rather as God hath raised a people to testify for it,
and preach it to their great refreshment and strengthening,
in the very face of the world, and notwithstanding much opposition; who do not,
as these mystics,
make of it a mystery only to be attained by a few men or women in a cloister, or,
as their mistake was,
after wearying themselves with many outward ceremonies and observations,
as if it were the consequence of such a labour.
But who in the free love of God (who respects not persons,
and was near to hear and reveal himself as well to Cornelius, a centurion and a Roman,
as to Simeon and Anna, and who discovered his glory to Mary, a poor handmaid,
and to the poor shepherds,
rather than to the high priests and devout proselytes among the Jews),
in and according to his free love finding that God
is revealing and establishing this worship,
and making many poor tradesmen, yea young boys and girls, witnesses of it,
do entreat and beseech all to lay aside their own will-worships and voluntary acts performed
in their own wills and by their own mere natural strength and power,
without retiring out of their vain imaginations and thoughts
or feeling the pure Spirit of God to move and stir _in_ them,
that they may come to practise this acceptable worship which is
"`in Spirit and in Truth.`" But against this worship they object.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XVII.
_Obj._ First,
it seems to be an unprofitable exercise for a man to be doing or thinking
nothing and that one might be much better employed either in meditating
upon some good subject or otherwise praying to or praising God.

_Answ._
I answer, that is not unprofitable which is of absolute necessity,
before any other duty can be acceptably performed, as we have shown this waiting to be.
Moreover,
those have but a carnal and gross apprehension of God and of the things of his kingdom,
that imagine that men please him by their own workings and actings, whereas,
as hath been shown,
the first step for man to fear God is to cease from his own thoughts
and imaginations and suffer God`'s Spirit to work in him:
for we must "`cease to do evil,`" ere we "`learn to do well`";^
footnote:[Isa. 1:16-17.]
and this meddling in things spiritual by man`'s own natural understanding
is one of the greatest and most dangerous evils that man is incident to,
being that which occasioned our first parents`' fall, to wit,
a forwardness to desire to know things,
and a meddling with them both without and contrary to the Lord`'s command.

_Obj._
Secondly some object,
If your worship merely consist in inwardly retiring
to the Lord and feeling of his Spirit arise in you,
and then to do outward acts as ye are led by it,
what need ye have public meetings at set times and places,
since everyone may enjoy this at home?
or should not everyone stay at home until they be particularly
moved to go to such a place at such a time;
since to meet at set times and places seems to be an outward observation and ceremony,
contrary to what ye at other times assert?

_Answ._
I answer first:
to meet at set times and places is not any religious act or part of worship, in itself,
but only an outward conveniency necessary for our seeing one another,
so long as we are clothed with this outward tabernacle;
and therefore our meeting at set times and places is not a part
of our worship but a preparatory accommodation of our outward man,
in order to a public visible worship,
since we set not about the visible acts of worship when
we meet together until we be led thereunto.^
footnote:[Later editors add here, "`by the Spirit of God.`"]
Secondly, God hath seen meet, so long as his children are in this world,
to make use of the outward senses as a means to convey spiritual life, as by speaking,
praying, praising, etc.,
which cannot be done to mutual edification but when we hear and see one another,
but also to entertain an outward visible testimony for his Name in the world:
he causeth the inward life (which is also many times not conveyed
by the outward senses) the more to abound when his children assemble
themselves diligently together to wait upon him;
that as "`iron sharpeneth iron,`"^
footnote:[Prov. 27:14.]
so the seeing of the face one of another, when both are inwardly gathered unto the Life,
giveth occasion for the Life secretly to rise and pass from vessel to vessel;
and as many candles lighted and put in one place do greatly augment the light,
and makes it more to shine forth; so when many are gathered together into the same Life,
there is more of the glory of God,
and his power appears to the refreshment of each individual for that he partakes
not only of the Light and Life raised in himself but in all the rest;
and therefore Christ hath particularly promised
a blessing to such as assemble together in his Name,
seeing he will be "`in the midst of them`" (Matt. 18:20). And the author
to the Hebrews doth precisely prohibit the neglect of this duty,
as being of very dangerous and dreadful consequence, in these words (Heb. 10:24-26):
"`And let us consider one another, to provoke unto love and to good works:
not forsaking the assembling of ourselves together as the manner of some is,--for
if we sin willfully after that we have received the knowledge of the Truth there
remaineth no more sacrifice for sins.`" And therefore the Lord hath shown that
he hath a particular respect to such as thus assemble themselves together,
because that thereby a public testimony for him is
upheld in the earth and his Name is thereby glorified;
and therefore such as are right in their spirits are naturally drawn to keep the meetings
of God`'s people and never want a spiritual influence to lead them thereunto.
And if any do it in a mere customary way they will no doubt suffer condemnation for it.
Yet cannot the appointing of places and times be accounted a ceremony
and observation done in man`'s will in the worship of God,
seeing none can say that it is an act of worship,
but only a mere presenting of our persons in order to it, as is above said.
Which that it was practised by the primitive Church and saints,
all our adversaries do acknowledge.

_Obj._
Lastly,
some object that this manner of worship in silence is not to be found in all the Scripture.

_Answ._
I answer, we make not silence to be the sole matter of our worship, since,
as I have above said, there are many meetings, which are seldom, if ever,
altogether silent, some or other are still moved either to preach, pray, and praise,
and so, in this,
our meetings cannot be but like the meetings of the primitive churches recorded in Scripture,
since our adversaries confess that they did preach and pray by the Spirit.
And then,
what absurdity is it to suppose that at some times
the Spirit did not move them to these outward acts,
and that then they were silent,
since we may well conclude they did not speak until they were moved,
and so no doubt had sometimes silence (Acts 2:1) before the Spirit came upon them,
it is said, "`They were all with one accord in one place`"; and then it is said,
"`The Spirit suddenly came upon them`";
but no mention is made of anyone speaking at that time,
and I would willingly know what absurdity our adversaries can infer,
should we conclude they were a while silent.

_Inst._
But if it be urged that a whole silent meeting cannot be found in Scripture.

_Answ._
I answer; supposing such a thing were not recorded,
it will not therefore follow that it is not lawful,
seeing it naturally followeth from other Scripture precepts, as we have proven this doth,
for seeing the Scripture commands to meet together,
and when met the Scripture prohibits prayers or preachings
but as the Spirit moveth thereunto,
if people meet together and the Spirit move not to such
acts it will necessarily follow that they must be silent.
But further,
there might have been many such things among the
saints of old though not recorded in Scripture,
and yet we have enough in Scripture signifying that such things were.
For Job sat silent seven days with his friends together;^
footnote:[Job 2:13.]
here was a long silent meeting.
See also Ezra 9:4 and Ezekiel 14:1 and 20:1.
Thus having shown the excellency of this worship,
proven it from Scripture and reason,
and answered the objections which are commonly made against it,
which though it might suffice to the explanation and probation of our proposition,
yet I shall add something more particularly of preaching, praying, and singing,
and so proceed to the following proposition.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XVIII.
Preaching, as it`'s used both among Papists and Protestants,
is for one man to take some place or verse of Scripture and thereon speak for
an hour or two what he hath studied and premeditated in his closet and gathered
together from his own inventions or from the writings and observations of others,
and then having got it by heart, as a schoolboy doth his lesson,
he brings it forth and repeats it before the people;
and how much the fertiler and stronger a man`'s invention is,
and the more industrious and laborious he is in collecting such observations
and can utter them with the excellency of speech and human eloquence,
so much the more is he accounted an able and excellent preacher.

To this we oppose that when the saints are met together,
and every one gathered to the Gift and Grace of God in themselves,
he that ministereth being acted thereunto by the arising of the Grace
in himself ought to speak forth what the Spirit of God furnisheth him with,
not minding the eloquence and wisdom of words,
but the demonstration of the Spirit and of power,
and that either in the interpreting some part of Scripture, in case the Spirit,
which is the good remembrancer, lead him so to do, or otherwise words of exhortation,
advice, reproof and instruction, or the sense of some spiritual experiences,
all which will still be agreeable to the Scripture,
though perhaps not relative to nor founded upon any
particular chapter or verse as a text.
Now let us examine and consider which of these two sorts of preaching be most agreeable
to the precepts and practice of Christ and his apostles and the primitive church,
recorded in Scripture.
For first, as to their preaching upon a text,
if it were not merely customary or premeditated,
but done by the immediate motion of the Spirit, we should not blame it,
but to do it as they do there is neither precept nor practice, that ever I could observe,
in the New Testament, as a part of the instituted worship thereof.

_Obj._
But they allege that Christ took the book of Isaiah and read out of it,
and spake therefrom; and that Peter preached from a sentence of the prophet Joel.

_Answ._
I answer that Christ and Peter did it not but as immediately
acted and moved thereunto by the Spirit of God,
and that without premeditation, which I suppose our adversaries will not deny;
in which case we willingly approve of it; but what is this to their customary conned way,
without either waiting for or expecting the movings or leadings of the Spirit?
Moreover, that neither Christ nor Peter did it as a settled custom or form,
to be constantly practised by all the ministers of the Church,
appears in that most of all the sermons recorded of Christ
and his apostles in Scripture were without this,
as appears from Christ`'s sermon upon the mount (Matt. 5:1, etc.; Mark 4:1,
etc.) and Paul`'s preaching to the Athenians and to the Jews,
etc. As then it appears that this method of preaching
is not grounded upon any Scripture precept,
so the nature of it is contrary to the preaching of Christ under the New Covenant,
as expressed and recommended in Scripture; for Christ, in sending forth his disciples,
expressly mentioneth that they are not to speak of
or from themselves or to forecast beforehand,
but that which "`the Spirit in the same hour shall teach them,`" as is particularly
mentioned in the three evangelists (Matt. 10:20;
Mark 13:11; Luke 12:12). Now,
if Christ gave this order to his disciples before he departed from them,
as that which they were to practise, during his abode outwardly with them,
much more were they to do it after his departure,
since then they were more especially to receive the Spirit "`to lead them in all things`"
and to "`bring all things to their remembrance`" (John 14:26). And if they were to do
so when they appeared before the magistrates and princes of the earth,
much more in the worship of God, when they stand especially before him, seeing,
as is above shown, his worship is to be performed in Spirit; and therefore,
after their receiving of the Holy Ghost, it is said (Acts 2:4):
"`They spake as the Spirit gave them utterance,`" not what they had studied
and gathered from books in their closets in a premeditated way.

Francis Lambert, before cited, speaketh well, and showeth their hypocrisy (Tract.
5, of [.book-title]#Prophecy,# chap.
3), saying, "`Where are they now that glory in their inventions, who say,
a brave invention! a brave invention! this they call
invention which themselves have made up,
but what have the faithful to do with such kind of inventions?
It is not figments, nor yet inventions, that we will have, but things that are solid,
invincible, eternal and heavenly, not which men have invented,
but which God hath revealed; for if we believe the Scripture,
our invention profiteth nothing but to provoke God to our ruin.`" And afterwards,
"`Beware,`" saith he,
"`that thou determine not precisely to speak what before thou hast meditated,
whatsoever it be,
for though it be lawful to determine the text which thou art to expound,
yet not at all the interpretation; lest, if thou so dost,
thou take from the Holy Spirit that which is his, to wit, to direct thy speech,
that thou mayest prophesy in the Name of the Lord, denuded of all learning, meditation,
and experience, and as if thou hadst studied nothing at all; committing thy heart,
thy tongue, and thyself wholly unto his Spirit,
and trusting nothing to thy former studying or meditation, but saying with thyself,
in great confidence of the divine promise,
the Lord will give a word with much power unto those that preach the gospel.
But above all things be careful thou follow not the manner of hypocrites,
who have written almost word by word what they are to say,
as if they were to repeat some verses upon a theatre have learned all their preaching,
as they do that act tragedies, and afterwards, when they are in the place of prophesying,
pray the Lord to direct their tongue:
but in the meantime shutting up the way of the Holy Spirit
they determine to say nothing but what they have written.
O unhappy kind of prophets, yea and truly cursed,
which depend not upon God`'s Spirit but upon their own writings or meditation!
Why prayest thou to the Lord, thou false prophet, to give thee his holy Spirit,
by which thou mayest speak things profitable, and yet thou repell`'st the Spirit?
why preferr`'st thou thy meditation or study to the Spirit of God?
Otherwise why committ`'st thou not thyself to the Spirit?`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§XIX.
Secondly, this manner of preaching as used by them,
considering that they also affirm that it may be and often
is performed by men who are wicked or void of true grace,
can not only not edify the church, beget or nourish true faith, but is destructive to it,
being directly contrary to the nature of the Christian
and apostolic ministry mentioned in the Scriptures;
for the apostle preached the gospel "`not in the wisdom of words,
lest the cross of Christ should be of none effect`" (1 Cor. 1:17). But this preaching,
not being done by the actings and movings of God`'s
Spirit but by man`'s invention and eloquence,
in his own will and through his natural and acquired parts and learning,
is in the wisdom of words,
and therefore the cross of Christ is thereby made of none effect.
The apostle`'s speech and preaching was not "`with enticing words of man`'s wisdom,
but in demonstration of the Spirit and of power,`" that the faith
of their hearers "`should not stand in the wisdom of men,
but in the power of God`" (1 Cor. 2:3-5). But this preaching
having nothing of the Spirit and power in it,
both the preachers and hearers confessing they wait for
no such thing nor yet are oftentimes sensible of it,
must needs stand in the enticing words of man`'s wisdom,
since it is by the mere wisdom of man it is sought after and the
mere strength of man`'s eloquence and enticing words it is uttered,
and therefore no wonder if the faith of such as hear and depend
upon such preachers and preachings stand in the wisdom of men,
and not in the power of God.
The apostles declared that they "`spake not in the words which man`'s wisdom teacheth,
but which the Holy Ghost teacheth`" (1 Cor. 2:13). But these
preachers confess that they are strangers to the Holy Ghost,
his motions and operations, neither do they wait to feel them,
and therefore they speak in the words which their
own natural wisdom and learning teach them,
mixing them in and adding them to such words as they
steal out of the Scripture and other books,
and therefore speak not what the Holy Ghost teacheth.

Thirdly,
this is contrary to the method and order of the primitive
church mentioned by the apostle (1 Cor. 14:30,
etc.), where in preaching every one is to wait for his revelation,
and to give place one unto another, according as things are revealed;
but here there is no waiting for a revelation, but the preacher must speak,
and not that which is revealed unto him,
but what he hath prepared and premeditated beforehand.

Lastly, by this kind of preaching, the Spirit of God,
which should be the chief instructor and teacher of God`'s people,
and whose influence is that only which makes all preaching
effectual and beneficial for the edifying of souls,
is shut out, and man`'s natural wisdom, learning and parts set up and exalted,
which (no doubt) is a great and chief reason why the preaching
among the generality of Christians is so unfruitful and unsuccessful;
yea according to this doctrine the devil may preach, and ought to be heard also,
seeing he both knoweth the truth and hath as much eloquence as any.
But what avails excellency of speech,
if the demonstration and power of the Spirit be wanting, which toucheth the conscience?
We see that when the devil confessed to the Truth,
yet Christ would have none of his testimony.
And as these pregnant testimonies of the Scripture do prove this
part of preaching to be contrary to the doctrine of Christ,
so do they also prove that of ours, before affirmed, to be conform thereunto.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XX. _Obj._
But if any object after this manner, have not many been benefited,
yea & both converted and edified by the ministry
of such as have premeditated their preaching?
yea and hath not the Spirit often concurred by its
divine influence with preachings thus premeditated,
so as they have been powerfully borne in upon the souls of the hearers to their advantage?

_Answ._
I answer, though that be granted, which I shall not deny,
it will not infer that the thing was good in itself,
more than because Paul was met with by Christ, to the converting of his soul,
riding to Damascus to persecute the saints, that he did well in so doing;
neither particular actions,
nor yet whole congregations (as we above observed) are to be measured
by the acts of God`'s condescension in times of ignorance.
But besides, it hath oftentimes fallen out that God,
having a regard to the simplicity and integrity either of the preacher or hearers,
hath fallen in upon the heart of a preacher by his power and holy influence,
and thereby hath led them to speak things which were not in his premeditated discourse,
and which perhaps he never thought of before:
and those passing ejaculations and unpremeditated but living exhortations
have proved more beneficial and refreshful both to preacher and
hearers than all their premeditated sermons.
But all that will not allow them to continue in these
things which in themselves are not approved,
but contrary to the practice of the apostles,
when God is raising up a people to serve him according to the primitive purity and spirituality,
yea such acts of God`'s condescension in times of darkness and ignorance
should engage all more and more to follow him,
according as he reveals his most perfect and spiritual way.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXI.
Having hitherto spoken of preaching, now it is fit to speak of praying,
concerning which the like controversy ariseth.
Our adversaries, whose religion is all, for the most part, outside,
and such whose acts are the mere products of man`'s natural will and abilities,
as they can preach, so can they pray, when they please,
and therefore have their set particular prayers.
I meddle not with the controversies among themselves concerning this,
some of them being for set prayers, as a liturgy,
others for such as are _extempore_ conceived:
it suffices me that all of them agree in this,
that the motions and influence of the Spirit of God
are not necessary to be previous thereunto;
and therefore they have set times in their public worship, as before and after preaching,
and in their private devotion, as morning and evening, and before and after meat,
and other such occasions,
at which they precisely set about the performing
of their prayers by speaking words to God,
whether they feel any motion or influence of the Spirit or not;
so that some of the chiefest have confessed that they have
thus prayed without the motions or assistance of the Spirit,
acknowledging that they sinned in so doing,
yet they said they look upon it as their duty to do so,
though to pray without the Spirit be sin.
We freely confess that prayer is both very profitable and a necessary duty,
commanded and fit to be practised frequently by all Christians;
but as we can do nothing without Christ,
so neither can we pray without the concurrence and assistance of his Spirit.
But that the state of the controversy may be the better understood, let it be considered,
first, that prayer is twofold: inward and outward.
Inward prayer is that secret turning of the mind towards God whereby,
being secretly touched and awakened by the Light of Christ in the conscience,
and so bowed down under the sense of its iniquities, unworthiness, and misery,
it looks up to God,
and joining issue with the secret shinings of the Seed of God it breathes towards him
and is constantly breathing forth some secret desires and aspirations towards him.
It is in this sense that we are so frequently in
Scripture commanded to "`pray continually`" (Luke 18:1;
1 Thess. 5:17; Eph. 6:18; Luke 21:36),
which cannot be understood of outward prayer,
because it were impossible that men should be always upon their knees,
expressing words of prayer; and this would hinder them from the exercise of those duties,
no less positively commanded.
Outward prayer is when as the spirit (being thus in the exercise of inward retirement,
and feeling the breathing of the Spirit of God to arise
powerfully in the soul) receives strength and liberty,
by a superadded motion and influence of the Spirit, to bring forth either audible sighs,
groans or words, and that either in public assemblies, or in private, or at meat, etc.

As then inward prayer is necessary at all times, so,
so long as the day of every man`'s visitation lasteth, he never wants some influence,
less or more, for the practice of it.
Because he no sooner retires his mind and considers himself in
God`'s presence but he finds himself in the practice of it.

The outward exercise of prayer as needing a greater
and superadded influence and motion of the Spirit,
as it cannot be continually practised, so neither can it be so readily,
so as to be effectually performed,
until his mind be sometime acquainted with the inward;
therefore such as are diligent and watchful in their minds and much retired in the exercise
of this inward prayer are more capable to be frequent in the use of the outward,
because that this holy influence doth more constantly attend them,
and they being better acquainted with, and accustomed to the motions of God`'s Spirit,
can easily perceive and discern them;
and indeed as such who are most diligent have a near access to God,
and he taketh most delight to draw them by his Spirit, to approach and call upon him.
So when many are gathered together in this watchful mind,
God doth frequently pour forth the Spirit of prayer among them, and stir them thereunto,
to the edifying and building up of one another in love.
But because this outward prayer depends upon the inward, as that, which must follow it,
and cannot be acceptably performed,
but as attended with a superadded influence and motion of the Spirit,
therefore cannot we prefix set times to pray outwardly,
so as to lay a necessity to speak words at such and such times,
whether we feel this heavenly influence, and assistance or no;
for that we judge were a tempting of God,
and a coming before him without due preparation.
We think it fit for us to present ourselves before
him by this inward retirement of the mind,
and so to proceed further, as his Spirit shall help us and draw us thereunto,
and we find that the Lord accepts of this,
yea and seeth meet sometimes to exercise us in this silent place,
for the trial of our patience, without allowing us to speak further,
that he may teach us not to rely upon outward performances, or satisfy ourselves,
as too many do, with the saying of our prayers, and,
that our dependence upon him may be the more firm and constant,
to wait for the holding out of his sceptre, and for his allowance to draw near unto him,
and with greater freedom and enlargement of Spirit upon our hearts towards him;
yet nevertheless we do not deny but sometimes God, upon particular occasions,
very suddenly, yea upon the very first turning in of the mind,
may give power and liberty to bring forth words or acts of outward prayer,
so as the soul can scarce discern any previous motion,
but the influence and bringing forth thereof may be, as it were _simul et semel:_
nevertheless that saying of Bernard is true,
that "`_all_ prayer is tepid which hath not an inspiration
preceding it.`" Though we affirm,
that none ought to go about prayer without this motion, yet we do not deny but such sin,
as neglect prayer; but their sin is in that they come not to that place,
where they may feel that, that would lead them thereunto,
and therefore we question not but many, through neglect of this inward watchfulness,
and retiredness of mind, miss many precious opportunities to pray,
and thereby are guilty in the sight of God, yet would they sin,
if they should set about the act, until they first felt the influence.
For as he grossly offends his master that lieth in his bed and sleeps,
and neglects to do his master`'s business,
yet if such a one should suddenly get up without putting on his clothes or taking along
with him those necessary tools and instruments without which he could not possibly work,
should forwardly fall a-doing to no purpose, he would be so far, thereby,
from repairing his former fault, that he would justly incur a new censure: and,
as one that is careless and otherways busied may miss to hear one speaking unto him,
or even not hear the bell of a clock, though striking hard by him,
so may many through negligence, miss to hear God oftentimes
calling upon them and giving them access to pray unto him;
yet will not that allow them, without his liberty, in their own wills to fall to work.

And lastly, though this be the only true and proper method of prayer,
as that which is alone acceptable to God,
yet shall we not deny but he oftentimes answered
the prayers and concurred with the desires of some,
especially in times of darkness, who have greatly erred herein;
so that some that have sit down in formal prayers,
though far wrong in the matter as well as manner,
without the assistance or influence of God`'s Spirit,
yet have found him to take occasion therethrough to break
in upon their souls and wonderfully tender and refresh them;
yet, as in preaching and elsewhere hath afore been observed,
that will not prove any such practices or be a just let to hinder
any from coming to practise that pure spiritual and acceptable
prayer which God is again restoring and leading his people into,
out of all superstitious and mere empty formalities.
The state of the controversy and our sense thereof being thus clearly stated will both
obviate many objections and make the answer to others more brief and easy;
I shall first prove this spiritual prayer by some
short considerations from Scripture,
and then answer the objections of our opposers,
which will also serve to refute their method and manner thereof.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXII.
And first, that there is a necessity of this inward retirement of the mind,
as previous to prayer, that the Spirit may be felt to draw thereunto, appears,
for that in most of those places where prayer is commanded,
watching is prefixed thereunto as necessary to go before, as Matt. 24:42;
Mark 13:33, and 14:38; Luke 21:36,
from which it is evident that this watching was to go before prayer.
Now to what end is this watching,
or what is it but a waiting to feel God`'s Spirit to draw unto prayer,
that so it may be done acceptably?
For since we are to "`pray always in the Spirit,`"^
footnote:[Eph. 6:18.]
and cannot pray of ourselves without it acceptably,
this watching must be for this end recommended to us as preceding prayer,
that we may watch and wait for the seasonable time to pray,
which is when the Spirit moves thereunto.

Secondly,
this necessity of the Spirit`'s moving and concurrence appears
abundantly from that of the apostle Paul (Rom. 8:26-27):
"`Likewise the Spirit also helpeth our infirmities:
for we know not what we should pray for as we ought;
but the Spirit itself maketh intercession for us with groanings which cannot be uttered.
And he that searcheth the hearts knoweth what is the mind of the Spirit because
he maketh intercession for the saints according to the will of God.`" Which _first,_
holds forth the incapacity of men, as of themselves,
to pray or call upon God in their own wills,
even such as have received the faith of Christ and are in measure sanctified by it,
as was the Church of Rome, to whom the apostle then wrote.
_Secondly,_ it holds forth that which can only help and assist men to pray,
to wit the Spirit,
as that without which they cannot do it acceptably
to God nor beneficially to their own souls.
_Thirdly,_ the manner and way of the Spirit`'s intercession,
with "`sighs and groans which are unutterable.`" And _fourthly,_
that God receiveth graciously the prayers of such as are
presented and offered unto himself by the Spirit,
knowing it to be according to his will.
Now it cannot be conceived but this order of prayer thus
asserted by the apostle is most consistent with those other testimonies
of Scripture commending and recommending to us the use of prayer.
From which I thus argue,

[.syllogism]
* _Arg._ If man know not how to pray, neither can do it, without the help of the Spirit, then it is to no purpose for him, but altogether unprofitable, to pray without it.
* But the first is true,
* Therefore also the last.

Thirdly,
this necessity of the Spirit to true prayer appears from Eph. 6:18 and Jude 20,
where the apostle commands to "`pray always in the Spirit,`" and "`watching thereunto`";
which is as much as if he had said that we were never
to pray without the Spirit or watching thereunto.
And Jude showeth us that such prayers as are "`in the Holy Ghost`"
only tend to the "`building up of ourselves in our most holy faith.`"

Fourthly,
the apostle Paul saith expressly (1 Cor. 12:3) that "`no man
can say that Jesus is the Lord but by the Holy Ghost.`" If then
Jesus cannot be thus rightly named but by the Holy Ghost,
far less can he be acceptably called upon.
Hence the same apostle declares (1 Cor. 14:15) that he "`will pray with the Spirit,`"
etc. A clear evidence that it was none of his method to pray without it!

But fifthly, all prayer without the Spirit is abomination,
such as are "`the prayers of the wicked`" (Prov. 28:9),
and the confidence that the saints have that God will hear them,
is if they "`ask anything according to his will`" (1 John 5:14). So if the prayer
be not according to his will there is no ground of confidence that he will hear.
Now our adversaries will acknowledge that prayers without
the Spirit are not according to the will of God;
and therefore such as pray without it have no ground to expect an answer;
for indeed to bid a man pray without the Spirit is
all one as to bid one see without eyes,
work without hands, or go without feet.
And to desire a man to fall to prayer ere the Spirit, in some measure less or more,
move him thereunto is to desire a man to see before he open his eyes,
or to walk before he rise up, or to work with his hands before he moves them.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXIII.
But lastly, from this false opinion of praying without the Spirit,
and not judging it necessary to be waited for,
as that which may be felt to move us thereunto,
hath proceeded all the superstition and idolatry that is among those called Christians,
and those many abominations wherewith the Lord is provoked and his Spirit grieved;
so that many deceive themselves now, as the Jews did of old,
thinking it sufficient if they pay their daily sacrifices
and offer their customary oblations,
from thence thinking all is well and creating a false peace
to themselves as the whore in the Proverbs,^
footnote:[Prov. 7:14.]
because they have offered up their sacrifices of morning and evening prayers.
And therefore it is manifest that their constant use of things
doth not a whit influence their lives and conversations,
but they remain for the most part as bad as ever,
yea it is frequent both among Papists and Protestants for them to leap, as it were,
out of their vain, light,
and profane conversations at their set hours and
seasons and fall to their customary devotion,
and then, when it is scarce finished and the words to God scarce out,
the former profane talk comes after it,
so that the same wicked profane spirit of this world acts them in both.
If there be any such thing as vain oblations, or prayers that are abomination,
which God heareth not (as is certain there are, and the Scripture testifies,
Isa. 66:3; Jer. 14:12),
certainly such prayers as are acted in man`'s will and by his own strength,
without God`'s Spirit, must be of that number.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXIV.
Let this suffice for probation.
Now I shall proceed to answer their objections when I have
said something concerning joining in prayer with others:
those that pray together with one accord use not only to concur in their spirits,
but also in the gesture of their body, which we also willingly approve of.
It becometh those who approach before God to pray that they
do it with bowed knees and with their heads uncovered,
which is our practice.

_Obj._
But here ariseth a controversy whether it be lawful
to join with others (by those external signs of reverence,
albeit not in heart) who pray formally,
not waiting for the motion of the Spirit nor judging it necessary.

_Answ._
We answer, not at all;
and for our testimony in this thing we have suffered not a little,
for when it hath fallen out that either accidentally,
or to witness against their worship,
we have been present during the same and have not
found it lawful for us to bow with them thereunto,
they have often persecuted us not only with reproaches
but also with strokes and cruel beatings;
for this cause, they use to accuse us of pride, profanity, and madness,
as if we had no respect or reverence to the worship of God,
and as if we judged none could pray or were heard of God but ourselves.
Unto all which and many more reproaches of this kind we answer briefly and modestly,
that it sufficeth us that we are found so doing neither
through pride nor madness nor profanity,
but merely lest we should hurt our consciences; the reason of which is plain and evident,
for since our principle and doctrine oblige us to believe that the prayers of
those who themselves confess they are not acted by the Spirit are abominations,
how can we with a safe conscience join with them?

_Obj._
If they urge that this is the height of uncharitableness and arrogancy,
as if we judged ourselves always to pray by the Spirit`'s motion but they never;
as if we were never deceived by praying without the motions of the Spirit,
and that they were never acted by it: seeing,
albeit they judge not the motion of the Spirit always necessary,
they confess nevertheless that it is very profitable and comfortable,
and they feel it often influencing them;
which that it sometimes falls out we cannot deny.

_Answ._
To all which I answer distinctly,
if it were their known and avowed doctrine not to pray without the motion of the Spirit,
and that seriously holding thereunto they did not bind themselves to pray at
certain prescribed times precisely (at which times they determine to pray,
though without the Spirit),
then indeed we might be accused of uncharitableness
and pride if we never joined with then;
and if they so taught and practised, I doubt not but it should be lawful for us so to do,
unless there should appear some manifest and evident hypocrisy or delusion.
But seeing they profess that they pray without the Spirit,
and seeing God hath persuaded us that such prayers are abominable,
how can we with a safe conscience join with an abomination?
That God sometimes condescends to them, we do not deny (albeit now,
when the spiritual worship is openly proclaimed, and all are invited unto it,
the case is otherwise than in those old times of apostasy and darkness), and therefore,
albeit any should begin to pray in our presence not expecting the motion of the Spirit,
yet if it manifestly appear, that God in condescension did concur with such a one, then,
according to God`'s will, we should not refuse to join also; but this is rare,
lest thence they should be confirmed in their false principle.
And albeit this seem hard in our profession,
nevertheless it is so confirmed by the authority both of Scripture and right reason,
that many, convinced thereof, have embraced this part before other,^
footnote:[Later editors insert "`truths, which were easier, and, as they seemed to some,
clearer.`"]
among whom is memorable of late years Alexander Skein,
a magistrate of the City of Aberdeen,
a man very modest and very averse from giving offence to others, who nevertheless,
being overcome by the power of Truth in this matter,
behooved for this cause to separate himself from the public assemblies and prayers,
and join himself unto us; who also gave the reason of his change,
and likewise succinctly but yet substantially comprehended this controversy concerning
worship in some short questions which he offered to the public preachers of the city,
which I think meet to insert in this place.

[.numbered-group]
====

[.numbered]
_Query:_ 1+++.+++ Whether or not should any act of God`'s worship be
gone about without the motions, leadings, and actings of the Holy Spirit?

[.numbered]
2+++.+++ If the motions of the Spirit be necessary to every particular duty,
whether should he be waited upon,
that all our acts and words may be according as he gives utterance and assistance?

[.numbered]
3+++.+++ Whether every one that bears the name of a Christian, or professes to be a Protestant,
hath such an uninterrupted measure thereof that he may, without waiting,
go immediately about the duty?

[.numbered]
4+++.+++ If there be an indisposition and unfitness, at some times, for such exercises,
at least as to the spiritual and lively performance thereof,
whether ought they to be performed in that case and at that time?

[.numbered]
5+++.+++ If any duty be gone about under pretence that
it is in obedience to the external command,
without the spiritual Life and motion necessary,
whether such a duty thus performed can in faith be expected to be accepted of God,
and not rather reckoned as a bringing of strange fire before the Lord,^
footnote:[Lev. 10:1.]
seeing it is performed (at best) by the strength of natural and acquired parts,
and not by the strength and assistance of the Holy Ghost,
which was typified by the fire that came down from heaven,
which alone behooved to consume the sacrifice and no other?

[.numbered]
6+++.+++ Whether duties gone about in the mere strength of natural and
acquired parts (whether in public or in private) be not as really,
upon the matter, an image of man`'s invention, as the Popish worship,
though not so gross in the outward appearance?
And therefore whether it be not as real superstition to countenance
any worship of that nature as it is to countenance Popish worship,
though there be a difference in the degree?

[.numbered]
7+++.+++ Whether it be a ground of offence or just scandal to countenance the worship
of those whose professed principle it is neither to speak for edification,
nor to pray, but as the Holy Ghost shall be pleased to assist them, in some measure,
less or more,
without which they rather choose to be silent than to speak without this influence?

====

Unto these they answered but very coldly and faintly,
whose answers likewise long ago he refuted.

Seeing then God hath called us to his spiritual worship and to
testify against the human and voluntary worships of the apostasy,
if we did not, this way, stand immovable to the Truth revealed,
but should join with them,
both our testimony for God would be weakened and lost and it would
be impossible steadily to propagate this worship in the world,
whose progress we dare neither retard nor hinder by any act of ours,
though therefore we shall lose not only worldly honor, but even our lives.
And truly many Protestants, through their unsteadiness in this thing,
for politic ends complying with the Popish abominations,
have greatly scandalized their profession and hurt the Reformation;
as appeared in the example of the Elector of Saxony, who,
in the convention at Augsburg in the year 1530,
being commanded by the Emperor Charles the Fifth to be present at the Mass,
that he might carry the sword before him according to his place;
which when he justly scrupled to perform, his preachers,
taking more care for their prince`'s honor than for his conscience,
persuaded him that it was lawful to do it, against his conscience,
which was both a very bad example, and great scandal to the Reformation,
and displeased many,
as the author of the history of the Council of Trent in his first book well observes.
But now I hasten to the objections of our adversaries against this method of praying.

[.small-break]
'''

[.offset]
// lint-disable invalid-characters "§"
§XXV.

[.syllogism]
* _Obj._ First, They object, that if such particular influences were needful to outward acts of worship, then they should also be needful to inward acts, as to wait, desire, and love God:
* But this is absurd:
* Therefore also that from whence it follows.

_Answ._
I answer, that which was said in the state of the controversy cleareth this,
because as to those general duties there never wants an
influence so long as the day of a man`'s visitation lasteth,
during which time God is always near to him, and wrestling with him by his Spirit,
to turn him to himself,
so that if he do but stand still and cease from his evil thoughts,
the Lord is near to help him,
etc. But as to the outward acts of prayer they need a more special motion and influence,
as hath been proved.

_Obj._
Secondly,
they object that it might be also alleged that men ought not to do moral duties,
as children to honor their parents, men to do right to their neighbours,
except the Spirit move them to it.

_Answ._
I answer, there is a great difference betwixt these general duties betwixt man and man,
and the particular express acts of worship towards God:
the one is merely spiritual and commanded by God to be performed by his Spirit;
the other answer their end as to them whom they are immediately directed to and concern,
though done from a mere natural principle of self-love,
even as beasts have natural affections one to another,
and therefore may be thus performed,
though I shall not deny but that they are not works accepted of God,
or beneficial to the soul, but as they are done in the fear of God and in his blessing,
in which his children do all things and therefore
are accepted and blessed in whatsoever they do.

_Obj._
Thirdly,
they object that if a wicked man ought not to pray without a motion of the Spirit,
because his prayer would be sinful.
neither ought he to plough by the same reason because
"`the ploughing of the wicked,`" as well as his praying,
is sin.^
footnote:[Prov. 21:4.]

_Answ._
This objection is of the same nature with the former
and therefore may be answered the same way,
seeing there is a great difference betwixt natural acts such as eating, drinking,
sleeping, and seeking sustenance for the body, which things man hath common with beasts,
and spiritual acts.
And it doth not follow because man ought not to go
about spiritual acts without the Spirit,
that therefore he may not go about natural acts without it.
The analogy holds better thus, and that for the proof of our affirmation,
that as man for the going about natural acts needs his natural spirit,
so to perform spiritual acts he needs the Spirit of God.
That the natural acts of the wicked and unregenerate are sinful is not denied,
though not as in themselves but in so far as man in that
state is in all things reprobated in the sight of God.

_Obj._
Fourthly, they object that wicked men may, according to this doctrine,
forbear to pray for years together, alleging they want a motion to it.

_Answ._
I answer,
the false pretences of wicked men do nothing invalidate the truth of this doctrine,
for at that rate there is no doctrine of Christ which men might not turn by.
That they ought not to pray without the Spirit is granted,
but then they ought to come to that place of watching
where they may be capable to feel the Spirit`'s motion.
They sin indeed in not praying; but the cause of this sin is their not watching,
so their neglect proceeds not from this doctrine but from their disobedience to it;
seeing if they did pray without this, it would be a double sin,
and no fulfilling of the command to pray, nor yet would their prayer,
without this Spirit, be useful unto them;
and this our adversaries are forced to acknowledge in another case;
for they say it is a duty incumbent on Christians to frequent
the sacrament of the Lord`'s Supper (as they call it).
Yet they say,
"`No man ought to take it unworthily,`" yea they plead that
such as find themselves unprepared must abstain,
and therefore do usually excommunicate them from the Table.
Now though, according to them, it be necessary to partake of this sacrament,
yet it is also necessary that those that do it do first examine themselves,
lest they eat and drink their own condemnation,
and though they reckon it sinful for them to forbear yet they account
it more sinful for them to do it without this examination.

_Obj._
Fifthly, they object Acts 8:22, where Peter commanded Simon Magus,
that wicked sorcerer, to pray,
from thence inferring that wicked men may and ought to pray.

_Answ._
I answer that in the citing of this place, as I have often observed,
they omit the first and chiefest part of the verse, which is thus (Acts 8:22):
"`Repent therefore of this thy wickedness,
and pray God if perhaps the thought of thine heart may be
forgiven thee,`" so here he bids him first "`Repent`";
now the least measure of true repentance cannot be without somewhat
of that inward retirement of the mind which we speak of;
and indeed where true repentance goeth first we do not doubt
but the Spirit of God will be near to concur with,
and influence such to pray to and call upon God.

_Obj._
And lastly, they object that many prayers, begun without the Spirit,
have proved effectual,
and that the prayers of wicked men have been heard and found acceptable, as Ahab`'s.

_Answ._
This objection was before solved; for the acts of God`'s compassion and indulgence,
at some times and to some persons, upon singular extraordinary occasions,
are not to be a rule of our actions.
For if we should make that the measure of our obedience,
great inconveniences would follow, as is evident and will be acknowledged by all.
Next, we do not deny but wicked men are sensible of the
motions and operations of God`'s Spirit oftentimes,
before their day be expired; from which they may at times pray acceptably,
not as remaining altogether wicked, but as entering into piety,
from whence they afterwards fall away.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXVI.
As to the singing of psalms, there will not be need of any long discourse,
for that the case is just the same as in the two former of preaching and prayer.
We confess this to be a part of God`'s worship, and very sweet and refreshful,
when it proceeds from a true sense of God`'s love _in_ the heart,
and arises from the divine influence of the Spirit,
which leads souls to breathe forth either a sweet harmony,
or words suitable to the present condition,
whether they be words formerly used by the saints and recorded in Scripture,
such as the Psalms of David, or other words, as were the hymns and songs of Zacharias,
Simeon, and the blessed Virgin Mary.
But as for the formal customary way of singing, it hath in scripture no foundation,
nor any ground in true Christianity:
yea besides all the abuses incident to prayer and preaching it hath this more peculiar,
that oftentimes great and horrid lies are said in the sight of God,
for all manner of wicked profane people take upon them to
personate the experiences and conditions of blessed David,
which are not only false as to them,
but also as to some of more sobriety who utter them forth:
as where they will sing sometimes (Ps. 22:14)--"`My heart is like wax,
it is melted in the midst of my bowels`"; and verse 15,
"`My strength is dried up like a potsherd, and my tongue cleaveth to my jaws;
and thou hast brought me into the dust of death`" and Ps. 6:6,
"`I am weary with my groaning, all the night make I my bed to swim:
I water my couch with my tears.`" And many more which those that speak know to be false,
as to them.
And sometimes will confess, just after, in their prayers,
that they are guilty of the vices opposite to those virtues which
but just before they have asserted themselves endued with.
Who can suppose that God accepts of such juggling?
And indeed such singing doth more please the carnal
ears of men than the pure ears of the Lord,
who abhors all lying and hypocrisy.

That singing, then,
that pleaseth him must proceed from that which is
pure _in_ the _heart_ (even from the _Word of Life_ therein),
in and by which richly dwelling in us,
spiritual songs and hymns are returned to the Lord,
according to that of the apostle (Col. 3:16).

But as to their artificial music, either by organs or other instruments, or voice,
we have neither example nor precept for it in the New Testament.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXVII.
But lastly,
the great advantage of this true worship of God which we profess
and practise is that it consisteth not in man`'s wisdom,
arts or industry, neither needeth the glory, pomp, riches,
nor splendor of this world to beautify it,
as being of a spiritual and heavenly nature and therefore
too simple and contemptible to the natural mind and will of man,
that hath no delight to abide in it because he finds no room there for his imaginations
and inventions and hath not the opportunity to gratify his outward and carnal senses:
so that this form being observed is not likely to be long kept pure without the power:
for it is, of itself,
so naked without it that it hath nothing in it to invite and tempt men to dote upon it,
further than it is accompanied with the power.
Whereas the worship of our adversaries, being performed in their own wills,
is _self-pleasing,_
as in which they can largely exercise their natural parts and invention:
and (as to most of them) having somewhat of an outward and worldly splendor,
delectable to the carnal and worldly senses,
they can pleasantly continue in it and satisfy themselves,
though without the Spirit and Power,
which they make no ways essential to the performance of their worship
and therefore neither wait for nor expect it.

[.small-break]
'''

// lint-disable invalid-characters "§"
§XXVIII.
So that to conclude, the worship, preaching,
praying and singing which we plead for is such as proceedeth from
the Spirit of God and is always accompanied with its influence,
being begun by its motion and carried on by the power and strength thereof,
and so is a worship purely spiritual such as the Scripture holds forth (John 4:23-24;
1 Cor. 14:15; Eph. 6:18, etc.).

But the worship, preaching, praying and singing which our adversaries plead for,
and which we oppose, is a worship which is both begun, carried on,
and concluded in man`'s own natural will and strength,
without the motion or influence of God`'s Spirit, which they judge they need not wait for,
and therefore may be truly acted, both as to the matter and manner,
by the wickedest of men.
Such was the worship and vain oblations which God always rejected,
as appears from Isa. 66:3; Jer. 14:12, etc.; Isa. 1:13; Prov. 15:29; John 9:31.
