== THE TWELFTH PROPOSITION

[.chapter-subtitle--blurb]
Concerning Baptism

[.heading-continuation-blurb]
As there is one Lord and one faith, so there is one baptism,
which is not the putting away the filth of the flesh
but the answer of a good conscience before God,
by the resurrection of Jesus Christ,
and this baptism is a pure and spiritual thing, to wit,
the baptism of the Spirit and fire, by which we are buried with him,
that being washed and purged from our sins, we may walk in newness of life;
of which the baptism of John was a figure which was
commanded for a time and not to continue forever;
as to the baptism of infants it is a mere human tradition for which neither
precept nor practice is to be found in all the Scripture.^
footnote:[Eph. 4:1,5 Pet.
3:21, Rom. 6:4, Gal. 3:27, Col. 2:12, John 3:1,30 Cor.
1:17.]

// lint-disable invalid-characters "§"
§I. I did sufficiently demonstrate,
in the explanation and probation of the former Proposition,
how greatly the professors of Christianity, as well Protestants as Papists,
were degenerated in the matter of worship, and how much strangers to,
and averse from that true and acceptable worship
that is performed in the Spirit of Truth,
because of man`'s natural propensity, in his fallen state, to exalt his own inventions,
and to intermix his own work and product in the service of God;
and from this root sprung all the idle worships, idolatries,
and numerous superstitious inventions among the heathens.
For when God, in condescension to his chosen people, the Jews,
did prescribe to them by his servant Moses many ceremonies and observations,
as types and shadows of the substance which in due time was to be revealed,
which consisted for the most part in washings, outward purifications and cleansings,
which were to continue until the time of the reformation,
until the spiritual worship should be set up, and that God,
by the more powerful^
footnote:[Later editors change "`powerful`" to "`plentiful.`"]
pouring forth of his Spirit and guiding of that anointing,
which was to lead his children "`into all Truth,`" and teach them
to worship him in a way more spiritual and acceptable to him,
though less agreeable to the carnal and outward senses:
notwithstanding God`'s condescension to the Jews in such things we see that part
in man which delights to follow its own inventions could not be restrained,
nor yet satisfied with all these observations,
but that oftentimes they would be either declining
to the other superstitions of the Gentiles,
or adding some new observations and ceremonies of their own,
to which they were so devoted that they were still
apt to prefer them before the commands of God,
and that under the notion of zeal and piety.
This we see abundantly in the example of the Pharisees, the chiefest sect among the Jews,
whom Christ so frequently reproves for "`making void the
commandments of God by their traditions`" (Matt. 15:6, 9,
etc.). This complaint may at this day be no less justly
made as to many bearing the name of Christians,
who have introduced many things of this kind, partly borrowed from the Jews,
which they more tenaciously stick to and more earnestly
contend for than for the weightier points of Christianity:
because that self, yet alive and ruling in them,
loves their own inventions better than God`'s commands.
But if they can by any means stretch any Scripture
practice or conditional precept or permission,
fitted to the weakness or capacity of some,
or appropriate to some particular dispensation,
to give some color for any of these their inventions,
they do then so tenaciously stick to them,
and so obstinately and obstreperously plead for them,
that they will not patiently hear the most solid Christian reasons against them.
Which zeal, if they would but seriously examine it,
they would find to be but the prejudice of education and
the love of self more than of God or his pure worship.
This is verified concerning those things which are called "`sacraments,`" about which
they are very ignorant in religious controversies who understand not how much debate,
contention, jangling and quarrelling there has been among those called Christians,
so that I may safely say, the controversy about them, to wit, about their number, nature,
virtue, efficacy, administration and other things,
hath been more than about any other doctrine of Christ,
whether as betwixt Papists and Protestants or among Protestants betwixt themselves,
and how great prejudice these controversies have brought to Christians is very obvious,
whereas the things contended for among them are for the
most part but empty shadows and mere outside things,
as I hope hereafter to make appear to the patient and unprejudicate reader.

[.small-break]
'''

// lint-disable invalid-characters "§"
§II. That which comes first under observation is the name "`sacrament,`"
which is strange that Christians should stick to and contend so much for;
since it is not to be found in all the Scripture,
but was borrowed from the military oaths among the heathens, from whom the Christians,
when they began to apostatize, did borrow many superstitious terms and observations,
that they might thereby ingratiate themselves and
the more easily gain the heathens to their religion,
which practice (though perhaps intended by them for good,
yet as being the fruit of human policy and not according
to God`'s wisdom) has had very pernicious consequences.
I see not how any, whether Papists or Protestants, especially the latter,
can in reason quarrel us for denying this term,
which it seems the Spirit of God saw not meet to inspire
the penmen of the Scriptures to leave unto us.

_Obj._ But if it be said that it is not the name but the thing they contend for:

_Answ._
I answer, let the name then, as not being Scriptural, be laid aside,
and we shall see at first entrance how much benefit will redound by laying aside
this traditional term and betaking us to plainness of Scripture language,
for presently the great contest about the number of them will vanish:
since there is no term used in Scripture that can be made use of,
whether we call them "`institutions,`" "`ordinances,`" "`precepts,`"
"`commandments,`" "`appointments`" or "`laws,`" etc.,
that would afford ground for such a debate,
since neither will Papists affirm that there are only seven, or Protestants only two,
of any of these aforementioned.

_Obj._
If it be said that this controversy arises from the
definition of the thing as well as from the name:

_Answ._
It will be found otherwise,
for whatever way we take their definition of a "`sacrament,`" whether as an "`outward visible
sign whereby inward grace is conferred,`" or only "`signified.`" This definition will agree
to many things which neither Papists nor Protestants will acknowledge to be sacraments.
If they be expressed under the name of "`sealing ordinances,`" as some do,
I could never see neither by reason nor Scripture
how this title could be appropriate to them,
more than to any other Christian religious performance:
for that must needs properly be "`a sealing ordinance,`" which makes
the persons receiving it infallibly certain of the promise,
or thing sealed to them.

_Obj._
If it be said it is so to them that are faithful;

_Answ._
I answer, so is praying and preaching, and doing of every good work.
Seeing the partaking,
or performing of the one gives not to any a more certain title to heaven,
yea (in some respect) not so much,
there is no reason to call them so more than the other.

Besides,
we find not anything called the "`seal`" and "`pledge`"
of our inheritance but the Spirit of God;
it is by that we are said to be sealed (Eph. 1:14 and 4:30),
which is also termed the "`earnest of our inheritance`" (2 Cor. 1:22),
and not by outward water, or eating and drinking;
which as the wickedest of men may partake of, so many that do,
do notwithstanding it go to perdition;
for it is not outward washing with water that maketh the heart clean,
by which men are fitted for heaven;
and as "`that which goeth into the mouth doth not defile a man,
because it is put forth again`" and so goeth to the dunghill,
neither doth anything which man eateth purify him or fit him for heaven.
What is said here in general may serve for an introduction
not only to this Proposition but also to the other,
concerning the Supper.
Of these "`sacraments`" (so called) baptism is always first numbered,
which is the subject of the present proposition,
in whose explanation I shall first demonstrate and prove our judgment
and then answer the objections and refute the sentiments of our opposers.
As to the first part, these things following,
which are briefly comprehended in the proposition, come to be proposed and proved.

[.small-break]
'''

// lint-disable invalid-characters "§"
§III.
First, that there is but one baptism, as well as but one Lord, one faith, etc.

Secondly, that this one baptism, which is the baptism of Christ, is not a washing with,
or dipping in, water, but a being baptized by the Spirit.

Thirdly, that the baptism of John was but a figure of this, and therefore,
as the figure (to give place to the substance) which, though it be to continue,
yet the other is ceased.

As for the first, viz.,
"`that there is but one baptism,`" there needs no other
proof than the words of the text (Eph. 4:5):
"`One Lord, one faith, one baptism`"; where the apostle positively and plainly affirms,
that as there is but one body, one Spirit, one faith, one God, etc.,
so there is but one baptism.

_Obj._
As to what is commonly alleged by way of explanation upon the text,
that the baptism of water and of the Spirit make up this one baptism,
by virtue of the sacramental union.

_Answ._
I answer,
This exposition hath taken place not because grounded upon the testimony of the Scripture
but because it wrests the Scripture to make it suit to their principle of water baptism,
and so there needs no other reply but to deny it,
as being repugnant to the plain words of the text,
which saith not that there are two baptisms, to wit, one of water,
the other of the Spirit, which do make up one baptism, but plainly,
that there is "`one baptism,`" as there is "`one faith`"
and "`one God.`" Now there goeth not two faiths,
nor two Gods, nor two Spirits, nor two bodies,
whereof the one is outward and elementary and the other spiritual and pure,
to the making up of the one faith, the one God, the one body, and the one Spirit;
so neither ought there to go two baptisms to make up the one baptism.

_Obj._
But secondly, if it be said the baptism is but one, whereof water is the one part,
to wit, the sign; and the Spirit, the thing signified, the other.

_Answ._
I answer, this yet more confirmeth our doctrine, for, if water be only the sign,
it is not the matter of the one baptism (as shall further
hereafter by its definition in Scripture appear),
and we are to take the one baptism for the matter of it, not for the sign,
or figure and type, that went before,
even as where Christ is called the "`one offering`" in Scripture though
he was typified by many sacrifices and offerings under the Law,
we understand only by the one offering, his offering himself upon the cross,
whereof though those many offerings were figures and types,
yet we say not that they go together with that offering
of Christ to make up the one offering;
so neither, though water baptism was a sign of Christ`'s baptism,
will it follow that it goeth now to make up the baptism of Christ.
If any should be so absurd as to affirm that this one baptism
here were the baptism of water and not of the Spirit,
that were foolishly to contradict the positive testimony of the Scripture,
which saith the contrary, as by what followeth will more amply appear.

Secondly, that this one baptism, which is the baptism of Christ,
is not a washing with water, appears, first, from the testimony of John,
the proper and peculiar administrator of water baptism (Matt. 3:11),
"`I indeed baptize you with water unto repentance;
but he that cometh after me is mightier than I, whose shoes I am not worthy to bear;
he shall baptize you with the Holy Ghost and with fire.`" Here John
mentions two manners of baptizings and two different baptisms,
the one with water, and the other with the Spirit,
the one whereof he was the minister of, the other whereof Christ was the minister of:
and such as were baptized with the first were not therefore baptized with the second:
"`I indeed baptize you,
but he shall baptize you.`" Though in the present
time they were baptized with the baptism of water,
yet they were not as yet, but were to be, baptized with the baptism of Christ.
From all which I thus argue,

[.syllogism]
* _Arg. 1+++.+++_ If those that were baptized with the baptism of water were not therefore baptized with the baptism of Christ, then the baptism of water is not the baptism of Christ:
* But the first is true;
* Therefore also the last.

[.offset]
And again,

[.syllogism]
* _Arg. 2+++.+++_ If he that truly and really administered the baptism of water did notwithstanding declare that he neither could nor did baptize with the baptism of Christ, then the baptism of water is not the baptism of Christ:
* But the first is true:
* Therefore, etc.

And indeed to understand it otherwise would make John`'s words void of good sense;
for if their baptisms had been all one,
why should he have so precisely contradistinguished them?
Why should he have said that those whom he had already
baptized should yet be baptized by another baptism?

_Obj._
If it be urged that baptism with water was the one
part and that with the Spirit the other part,
or effect only of the former.

I answer: this exposition contradicts the plain words of the text: for he saith not,
I baptize you with water and he that cometh after shall
produce the effects of this my baptism in you by the Spirit,
etc., or he shall accomplish this baptism in you; but "`he shall baptize you.`" So then,
if we understand the words truly and properly when he saith,
"`I baptize you,`" as consenting that thereby is really signified
that he did baptize with the baptism of water,
we must needs, unless we offer violence to the text,
understand the other part of the sentence the same way; that where he adds presently,
"`But he shall baptize you,`" etc.,
that he understood it of their being truly to be baptized
with another baptism than what he did baptize with;
else it had been nonsense for him thus to have contradistinguished them.

Secondly,
This is further confirmed by the saying of Christ himself
(Acts 1:4-5)--"`But wait for the promise of the Father,
which,`" saith he "`ye have heard of me: for John truly baptized with water,
but ye shall be baptized with the Holy Ghost,
not many days hence.`" There can scarce two places of Scripture run more parallel,
than this doth with the former, a little before mentioned,
and therefore concludeth the same way, as did the other.
For Christ here grants fully, that John completed his baptism,
as to the matter and substance of it: "`John,`" saith he,
"`truly baptized with water,`" which is as much, as if he had said,
John did truly and fully administer the baptism of water;
"`But ye shall be baptized with,`" etc. This showeth
that they were to be baptized with some other baptism,
than the baptism of water, and that,
although they were formerly baptized with the baptism of water,
yet not with that of Christ, which they were to be baptized with.

Thirdly, Peter observes the same distinction (Acts 11:16):
"`Then remembered I the word of the Lord, how that he said,
John indeed baptized with water;
but ye shall be baptized with the Holy Ghost.`" The apostle makes
this application upon the Holy Ghost`'s falling upon them.
Whence he infers, that they were then baptized with the baptism of the Spirit.
As to what is urged from his calling afterwards for water,
to it shall be hereafter spoken to.
From all which three sentences relative one to another, first of John,
secondly of Christ, and thirdly of Peter, it doth evidently follow, that such,
as were truly and really baptized with the baptism of water;
were notwithstanding not baptized with the baptism of the Spirit;
which is that of Christ;
and such as truly and really did administer the baptism of water, did,
in so doing not administer the baptism of Christ,
so that if there be now but one baptism, as we have already proved,
we may safely conclude, that it is that of the Spirit, and not of water;
else it would follow, that the one baptism, which now continues,
were the baptism of water, i.e., John`'s baptism,
and not the baptism of the Spirit, i.e., Christ`'s; which were most absurd.

_Obj._
If it be said further, that though the baptism of John, before Christ`'s was administered,
was different from it, as being the figure only, yet now that both it, as the figure,
and that of the Spirit, as the substance, is necessary to make up the one baptism:

_Answ._
I answer: this urgeth nothing,
unless it be granted also that both of them belong to the essence of baptism,
so that baptism is not to be accounted as truly administered where both are not:
which none of our adversaries will acknowledge,
but on the contrary account not only all those truly baptized
with the baptism of Christ who are baptized with water,
though they be uncertain whether they be baptized with the Spirit or not;
but they even account such truly baptized with the baptism
of Christ because sprinkled or baptized with water,
though it be manifest and most certain that they are not baptized with the Spirit,
as being enemies thereunto in their hearts, by wicked works.
So here, by their own confession, baptism with water is without the Spirit:
wherefore we may far safer conclude that the baptism of the Spirit,
which is that of Christ, is and may be without that of water,
as appears in that of Acts 11:15,
where Peter testifies of these men that they were baptized with the Spirit,
though not then baptized with water; and indeed the controversy in this,
as in most other things, stands betwixt us and our opposers,
in that they not only oftentimes prefer the form and shadow to the power and substance,
by denominating persons as inheritors and possessors
of the thing from their having the form and shadow,
though really wanting the power and substance;
and not admitting those to be so denominated who have the power and substance,
if they want the form and shadow.
This appears evidently in that they account those truly baptized
with the one baptism of Christ who are not baptized with the Spirit,
which in Scripture is particularly called the baptism of Christ,
if they be only baptized with water,
which themselves yet confess to be but the shadow or figure.
And moreover,
in that they account not those who are surely baptized with the baptism of the Spirit,
baptized, neither will they have them so denominated unless they be also sprinkled with,
or dipped in water.
But we, on the contrary, do always prefer the power to the form,
the substance to the shadow;
and where the substance and power is we doubt not to denominate the person accordingly,
though the form be wanting;
and therefore we always seek first and plead for the substance and power,
as knowing that to be indispensably necessary,
though the form sometimes may be dispensed with,
and the figure or type may cease when the substance and antitype comes to be enjoyed,
as it doth in this case, which shall hereafter be made appear.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IV. Fourthly, that the one baptism of Christ is not a washing with water,
appears from 1 Pet. 3:21: "`The like figure whereunto, even baptism,
doth also now save us (not the putting away of the filth of the flesh
but the answer of a good conscience towards God) by the resurrection of
Jesus Christ.`" So plain a definition of baptism is not in all the Bible,
and therefore, seeing it is so plain,
it may well be preferred to all the coined definitions of the schoolmen.
The apostle tells us, first, negatively, what it is not,
viz. "`not a putting away of the filth of the flesh,`"
then surely it is not a washing with water,
since that is so.
Secondly, he tells us, affirmatively, what it is, viz.,
"`the answer of a good conscience toward God, by the resurrection of Jesus Christ`";
where he affirmatively defines it to be the "`answer`" (or "`confession,`"
as the Syriac version hath it) "`of a good conscience.`" Now this answer
cannot be but where the Spirit of God hath purified the soul and the fire
of his judgment hath burned up the unrighteous nature;
and those in whom this work is wrought may be truly
said to be baptized with the baptism of Christ,
i.e.,
"`of the Spirit and of fire.`" Whatever way then we
take this definition of the apostle of Christ`'s baptism,
it confirmeth our sentence; for if we take the first or negative part, viz.,
"`that it is not a putting away of the filth of the flesh,`"
then it will follow that water baptism is not it,
because that is a putting away of the filth of the flesh.
If we take the second and affirmative definition, to wit,
that it is the "`answer`" or "`confession of a good conscience,`" etc.,
then water-baptism is not it; since, as our adversaries will not deny,
water baptism doth not always imply it, neither is it any necessary consequence thereof.
Moreover the apostle, in this place,
doth seem especially to guard against those that
might esteem water-baptism the true baptism of Christ;
because (lest by the comparison induced by him,
in the preceding verse betwixt the souls that were saved in Noah`'s ark,
and us that are now saved by baptism, lest, I say,
any should have thence hastily concluded,
that because the former were saved by water this place must needs
be taken to speak of water-baptism) to prevent such a mistake,
he plainly affirms that it is not that, but another thing.
He saith not, that it is the water, or the putting away of the filth of the flesh,
as accompanied with the answer of a good conscience, whereof the one, viz. water,
is the sacramental element administered by the minister, and the other,
the grace or thing signified, conferred by Christ; but plainly,
that it is "`not the putting away,`" etc.,
than which there can be nothing more manifest to men unprejudicate and judicious.
// lint-disable invalid-characters
Moreover, Peter calls this here, which saves, ἀντίτυπον,
the "`antitype`" or the thing figured,
whereas it is usually translated as if the like figure did now save us,
thereby insinuating, that, as they were saved by water in the ark,
so are we now by water-baptism.
But this interpretation crosseth his sense, he presently after declaring the contrary,
as hath above been observed:
and likewise it would contradict the opinion of all our opposers.
For Protestants deny it to be absolutely necessary to salvation.
And though Papists say none are saved without it, yet in this they admit an exception,
as of martyrs, etc.,
and they will not say that all that have it are saved by water baptism:^
footnote:[Later editors insert here, "`which they ought to say,
if they will understand by baptism, by which the apostle saith we are saved,
water baptism.`"]
for seeing we are saved by this baptism,
as those that were in the ark were "`saved by water,`" and
that all those that were in the ark were saved by water,
it would then follow that all those that have this baptism are saved by it.
Now this consequence would be false if it were understood of water-baptism; because many,
by the confession of all, are baptized with water that are not saved,
but this consequence holds most true if it be understood as we do,
of the baptism of the Spirit, since none can have this answer of a good conscience, and,
abiding in it, not be saved by it.

Fifthly, that the one baptism of Christ is not a washing with water,
as it hath been proved by the definition of the one baptism,
so it is also manifest from the necessary fruits and effects of it,
which are three times particularly expressed by the apostle Paul;
as first (Rom. 6:3-4),
where he saith that "`so many of them as were baptized
into Jesus Christ were baptized into his death,
buried with him by baptism into death,
that they should walk in newness of life.`" Secondly, to the Galatians (3:27),
he saith positively,
"`For as many of you as have been baptized into Christ have put on Christ,`" and thirdly,
to the Colossians (2:12),
he saith that they were "`buried with him in baptism,`" and "`risen with him through the
faith of the operation of God.`" It is to be observed here that the apostle speaks generally,
without any exclusive term, but comprehensive of all; he saith not,
"`some of you that were baptized into Christ have put on Christ,`"
but "`as many of you,`" which is as much as if he had said,
every one of you that hath been baptized into Christ hath put on Christ.
Whereby it is evident that this is not meant of water-baptism,
but of the baptism of the Spirit;
because else it would follow that whosoever had been baptized with
water-baptism had put on Christ and were risen with him,
which all acknowledge to be most absurd.
Now supposing all the visible members of the churches of Rome, Galatia,
and Colossae had been outwardly baptized with water (I do not say they were,
but our adversaries will not only readily grant it, but also contend for it), suppose,
I say, the case so, they will not say they had all put on Christ,
since divers expressions, in these epistles to them, show the contrary:
so that the apostle can not mean baptism with water,
and yet that he meaneth the baptism of Christ, i.e., of the Spirit, cannot be denied;
or that the baptism wherewith these were baptized (of whom the apostle
here testifies that they had put on Christ) was the one baptism,
I think none will call in question.
Now admit, as our adversaries contend,
that many in these churches who had been baptized with water had not put on Christ,
it will follow that notwithstanding that water baptism they were not baptized into Christ,
or with the baptism of Christ,
seeing as many of them as were baptized into Christ had put on Christ,
etc. From all which I thus argue:

[.syllogism]
* _Arg. 1+++.+++_ If the baptism with water were the one baptism, i.e., the baptism of Christ, as many as were baptized with water would have put on Christ:
* But the last is false,
* Therefore also the first.

[.offset]
And again,

[.syllogism]
* _Arg. 2+++.+++_ Since "`as many as are baptized into Christ,`" i.e., with the "`one baptism`" which is the baptism of Christ, "`have put on Christ,`" then water baptism is not the one baptism, viz. the baptism of Christ.
* But the first is true,
* Therefore also the last.

// lint-disable invalid-characters "§"
§V. Thirdly, since John`'s baptism was a figure,
and seeing the figure gives way to the substance, albeit the thing figured remain,
to wit, the one baptism of Christ, yet the other ceaseth, which was the baptism of John.

That John`'s baptism was a figure of Christ`'s baptism, I judge will not readily be denied:
but in case it should it can easily be proved from the nature of it:
John`'s baptism was a being baptized with water,
but Christ`'s is a baptizing with the Spirit.
Therefore John`'s baptism must have been a figure of Christ`'s. But further,
that water baptism was John`'s baptism will not be denied;
that water baptism is not Christ`'s baptism is already proved.
From which doth arise the confirmation of our proposition thus:

[.syllogism]
* _Arg._ There is no baptism to continue now but the one baptism of Christ:
* Therefore water baptism is not to continue now, because it is not the baptism of Christ.

That John`'s baptism is ceased many of our adversaries confess;
but if any should allege it is otherwise it may be
easily proved by the express words of John,
not only as being insinuated there,
where he contradistinguisheth his baptism from that of Christ,
but particularly where he saith (John 3:30),
"`He`" (Christ) "`must increase but I`" (John) "`must decrease.`" From
whence it clearly follows that the increasing or taking place of
Christ`'s baptism is the decreasing or abolishing of John`'s baptism;
so that if water-baptism was a particular part of
John`'s ministry and is no part of Christ`'s baptism,
as we have already proved, it will necessarily follow that it is not to continue.

[.syllogism]
* _Arg._ Secondly, if water baptism had been to continue a perpetual ordinance of Christ in his church, he would either have practised it himself or commanded his apostles so to do.
* But that he practised it not, the scripture plainly affirms (John 4:2). And that he commanded his disciples to baptize with water, I could never yet read. As for what is alleged, that Matt. 28:19, etc. (where he bids them baptize) is to be understood of water-baptism, that is but to beg the question, and the grounds for that shall be hereafter examined.
* Therefore, to baptize with water is no perpetual ordinance of Christ to his Church.

This hath had the more weight with me,
because I find not any standing ordinance or appointment of Christ,
necessary to Christians, for which we have not either Christ`'s own practice or command,
as to obey all the commandments, which comprehend both our duty towards God and man,
etc. and where the Gospel requires more than the Law,
which is abundantly signified in the 5th and 6th chapters of Matthew, and elsewhere.
Besides, as to the duties of worship, he exhorts us to meet, promising his presence,
commands to pray, preach, watch, etc. and gives precepts concerning some temporary things,
as the washing of one another`'s feet, the breaking of bread (hereafter to be discussed),
only for this one thing of baptizing with water (though
so earnestly contended for) we find not any precept of Christ.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VI. But to make water baptism a necessary institution of the Christian religion,
which is pure and spiritual, and not carnal and ceremonial,
is to derogate from the New Covenant dispensation and set
up the legal rites and ceremonies of which this of baptism,
or washing with water, was one, as appears from Heb. 9:10,
where the apostle speaking thereof saith that "`it stood only in meats and drinks,
and divers baptisms,^
footnote:[Later editors substitute "`washings`" for "`baptisms.`"]
and carnal ordinances imposed until the time of reformation.`" If then the time of reformation,
or the dispensation of the Gospel, which puts an end to the shadows, be come,
then such baptisms and carnal ordinances are no more to be imposed.
For how baptism with water comes now to be a spiritual ordinance,
more than before in the time of the Law, doth not appear: seeing it is but water still,
and a washing of the outward man, and a putting away of the filth of the flesh still;
and as before those that were so washed were not thereby made perfect,
as pertaining to the conscience, neither are they at this day,
as our adversaries must needs acknowledge and experience abundantly showeth.
So that the matter of it, which is a washing with water, and the effect of it,
which is only an outward cleansing, being still the same,
how comes water-baptism to be less a carnal ordinance now than before?

_Obj._
If it be said, That God confers inward grace upon some that are now baptized:

_Answ._
So no doubt he did also upon some that used those baptisms among the Jews.

_Obj._
Or if it be said, because it is commanded by Christ now, under the New Covenant:

_Answ._
I answer, first, that is to beg the question, of which hereafter.

But secondly, we find that where the matter of ordinances is the same,
and the end the same,
they are never accounted more or less spiritual because of their different times.
Now was not God the author of the purifications and baptisms under the Law?
Was not water the matter of them, which is so now?
Was not the end of them to signify an inward purifying by an outward washing?
And is not that alleged to be the end still?
And are the necessary effects or consequences of it any better now than before,
since men are now by the virtue of water-baptism, as a necessary consequence of it,
no more than before made inwardly clean?
And if some by God`'s grace, that are baptized with water, are inwardly purified,
so were some also under the Law;
so that this is not any necessary consequence nor effect,
neither of this nor that baptism; it is then plainly repugnant to right reason,
as well as to the Scripture testimony,
to affirm that to be a spiritual ordinance now which was a carnal ordinance before.
If it be still the same both as to its author, matter, and end,
however made to vary in some small circumstances.
The spirituality of the New Covenant and of its worship established by
Christ consisted not in such superficial alterations of circumstances,
but after another manner,
therefore let our adversaries show us if they can (without begging the question and
building upon some one or other of their own principles denied by us) where ever Christ
appointed or ordained any institution or observation under the New Covenant,
as belonging to the nature of it,
or such a necessary part of its worship as is perpetually to continue,
which being one in substance and effects (I speak of necessary, not accidental effects),
yet because of some small difference in form or circumstance was before carnal,
notwithstanding it was commanded by God under the Law, but now is become spiritual,
because commanded by Christ under the Gospel?
And if they can not do this, then if water-baptism was once a carnal ordinance,
as the apostle positively affirms it to have been, it remains a carnal ordinance still;
and if a carnal ordinance then no necessary part of the Gospel or New Covenant dispensation;
and if no necessary part of it,
then not needful to continue nor to be practised
by such as live and walk under this dispensation.
But in this, as in most other things (according as we have often observed),
our adversaries Judaize,
and renouncing the glorious and spiritual privileges of the New Covenant are sticking in,
and cleaving to the rudiments of the Old, both in doctrine and worship,
as being more suited and agreeable to their carnal apprehensions and natural senses.
But we, on the contrary,
travail above all to lay hold upon and cleave unto
the Light of the glorious Gospel revealed unto us.
And the harmony of the Truth we profess in this may appear,
by briefly observing how in all things we follow the spiritual Gospel of Christ,
as contradistinguished from the carnality of the legal dispensation;
while our adversaries, through rejecting this Gospel,
are still labouring under the burden of the Law,
which neither they nor their fathers were able to bear.

For the Law and rule of the Old Covenant, and Jews, was outward,
written in tables of stone and parchments.
So also is that of our adversaries.
But the Law of the New Covenant is inward and perpetual, written in the heart; so is ours.

The worship of the Jews was outward and carnal, limited to set times, places and persons,
and performed according to set prescribed forms and observations;
so is that of our adversaries.
But the worship of the New Covenant is neither limited to time, place, nor person,
but is performed in the Spirit and in Truth;
and it is not acted according to set forms and prescriptions,
but as the Spirit of God immediately acts, moves, and leads, whether it be to preach,
pray, or sing; and such is also our worship.

So likewise the baptism among the Jews under the
Law was an outward washing with outward water,
only to typify an inward purification of the soul,
which did not necessarily follow upon those that were thus baptized;
but the baptism of Christ under the Gospel is the baptism of the Spirit and of fire,
"`not the putting away of the filth of the flesh,
but the answer of a good conscience towards God,`" and such is the
baptism that we labour to be baptized withal and contend for.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VII.
_Arg._ But again, if water baptism had been an ordinance of the gospel,
then the apostle Paul would have been sent to administer it,
but he declares positively (1 Cor. 1:17), "`That Christ sent him not to baptize,
but to preach the gospel.`" The reason of that consequence is undeniable,
because the apostle Paul`'s commission was as large as that of any of them;
and consequently he being in special manner the apostle of Christ to the Gentiles,
if water baptism (as our adversaries contend) be to be accounted the badge of Christianity,
he had more need than any of the rest to be sent to baptize with water,
that he might mark the Gentiles converted by him, with that Christian sign.
But indeed the reason holds better thus, that since Paul was the apostle of the Gentiles,
and that in his ministry he doth through all (as by his epistles appears) labour,
to wean them from the former Jewish ceremonies and observations (though
in so doing he was sometimes undeservedly judged by others of his brethren,
who were unwilling to lay aside those ceremonies) therefore his commission
(though as full as to the preaching of the Gospel and New Covenant dispensation
as that of the other apostles) did not require of him that he should lead
those converts into such Jewish observations and baptisms;
however that practice was indulged in and practised
by the other apostles among their Jewish proselytes,
for which cause he "`thanks God that he had baptized so few`":^
footnote:[1 Cor. 1:14.]
intimating that what he did therein,
he did not by virtue of his apostolic commission
but rather in condescension to their weakness,
even as, at another time, he circumcised Timothy.

_Obj._
Our adversaries, to evade the Truth of this testimony, usually allege,
that by this is only to be understood,
that he was not sent principally to baptize, not that he was not sent at all.

_Answ._
But this exposition, since it contradicts the positive words of the text,
and has no better foundation than the affirmation of its assertors,
is justly rejected as spurious, until they bring some better proof for it; he saith not,
I was not sent principally to baptize, but, "`I was not sent to baptize.`"

_Confir._
As for what they urge, by way of confirmation from other places of Scripture,
where "`not`" is to be so taken, as where it is said, "`I will have mercy,
and not sacrifice,`"^
footnote:[Matt. 9:13.]
which is to be understood that God requires principally mercy, not excluding sacrifices:

_Refut._
I say this place is abundantly explained by the following words,
"`and the knowledge of God more than burnt offerings`";
by which it clearly appears that burnt offerings, which are one with sacrifices,
are not excluded, but there is no such word, added in that of Paul,
and therefore the parity is not demonstrated to be alike,
and consequently the instance not sufficient,
unless they can prove that it ought so to be admitted here: else we might interpret,
by the same rule, all other places of Scripture the same way,
as where the apostle saith (1 Cor. 2:5),
"`that your faith might not stand in the wisdom of men,
but in the power of God,`" it might be understood, it shall not stand principally so.
How might the Gospel, by this liberty of interpretation, be perverted?

_Obj._
If it be said that the abuse of this baptism among the Corinthians,
in dividing themselves according to the persons by whom they were baptized,
made the apostle speak so, but that the abuse of a thing doth not abolish it.

_Answ._
I answer, it is true, it doth not, provided the thing be lawful and necessary; and that,
no doubt, the abuse abovesaid gave the apostle occasion so to write.
But let it, from this, be considered, how the apostle excludes baptizing, not preaching,
though the abuse (mark) proceeded from that, less than from the other.
For these Corinthians did denominate themselves from those different persons by whose
preaching (as well as from those by whom they were baptized) they were converted,
as by the 4th, 5th, 6th, 7th, and 8th verses of the third chapter may appear:
and yet for to remove that abuse, the apostle doth not say he was not sent to preach,
nor yet doth he rejoice that he had only preached to a few; because preaching,
being a standing ordinance in the Church, is not,
because of any abuse that the devil may tempt any to make of it,
to be forborne by such as are called to perform it by the Spirit of God.
Wherefore the apostle accordingly (3:8-9) informs them, as to that,
how to remove that abuse; but as to water-baptism,
for that it was no standing ordinance of Christ,
but only practised as in condescension to the Jews,
& by some apostles to some Gentiles also,
there so soon as the apostle perceived the abuse of,
he let the Corinthians understand how little stress was to be laid upon it,
by showing them that he was glad that he had administered
this ceremony to so few of them,
and by telling them plainly that it was no part of his commission,
neither that which he was sent to administer.

_Quest._
Some ask us how we know that baptizing here is meant of water, and not of the Spirit,
which if it be, then it will exclude baptism of the Spirit, as well as of water.

_Answ._
I answer, such as ask the question, I suppose,
speak it not as doubting that this was said of water-baptism,
which is more than manifest:
for since the apostle Paul`'s message was "`to turn people from darkness to Light,
and convert them to God`";
and that as many as are thus turned and converted (so as to have "`the answer
of a good conscience towards God,`" and to have "`put on Christ,`" and be "`risen
with him in newness of life`") are baptized with the baptism of the Spirit.
But who will say that only these few mentioned there
to be baptized by Paul were come to this?
Or that to turn or bring them to this condition,
was not (even admitting our adversaries`' interpretation)
as principal a part of Paul`'s ministry as any other?
Since then our adversaries do take this place for water-baptism (as indeed it is),
we may lawfully, taking it so also, urge it upon them.
Why the word "`baptism`" and "`baptizing`" is used by the apostle, where that of water,
and not of the Spirit, is only understood shall hereafter be spoken to.
I come now to consider the reasons alleged by such as plead for water-baptism,
which are also the objections used against the discontinuance of it.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VIII.^
footnote:[Barclay does not number this section.
A later editor has supplied the number VIII.]
First, some object that Christ, who had the Spirit above measure,
was notwithstanding baptized with water.^
footnote:[John 3:34.]
As Nic. Arnold, against this thesis, Sect. 46 of his [.book-title]#Theological Exercitation.#

I answer, so was he also circumcised;
it will not follow from thence that circumcision is to continue;
for it behooved Christ to fulfill all righteousness, not only the ministry of John,
but the Law also.
Therefore did he observe the Jewish feasts and rites, and kept the passover:
it will not thence follow that Christians ought to do so now;
and therefore Christ (Matt. 3:15) gives John this reason of his being baptized,
desiring him to "`suffer it to be so now`":
whereby he sufficiently intimates that he intended not thereby
to perpetuate it as an ordinance to his disciples.

_Obj._
Secondly, they object (Matt. 28:19): "`Go ye therefore and teach all nations,
baptizing them in the name of the Father, and of the Son, and of the Holy Ghost.`"

_Answ._
This is the great objection, and upon which they build the whole superstructure,
whereunto the first general and sound answer is, by granting the whole,
but putting them to prove that water is here meant, since the text is silent of it.
And though in reason it be sufficient upon our part
that we concede the whole expressed in the place,
but deny that it is by water, which is an addition to the text,
yet I shall premise some reasons why we do so,
and then consider the reasons alleged by those that will have water to be here understood.

[.syllogism]
* _Arg._ The first is a maxim yielded to by all, that we ought not to go from literal signification of the text, except some urgent necessity force us thereunto:
* But no urgent necessity in this place forceth us thereunto:
* Therefore we ought not to go from it.

[.syllogism]
* _Arg._ Secondly, that baptism, which Christ commanded his apostles, was the "`one baptism,`" _id est,_ his own baptism;
* But the "`one baptism,`" which is Christ`'s baptism, is not with water, we have already proved:
* Therefore the baptism commanded by Christ to his apostles was not water-baptism.

[.syllogism]
* _Arg._ Thirdly, that baptism, which Christ commanded his apostles was such that as many as were therewith baptized did "`put on Christ`";
* But this is not true of water-baptism:
* Therefore, etc.

[.syllogism]
* Fourthly, the baptism commanded by Christ to his apostles was not John`'s baptism:
* But baptism with water was John`'s baptism:
* Therefore, etc.

_Allegation:_ But first, they allege, that Christ`'s baptism, though a baptism with water,
did differ from John`'s, because John only baptized with water unto repentance,
but Christ commands his disciples to baptize in the name of the Father, Son,
and Holy Ghost, reckoning, that in this form,
there lieth a great difference betwixt the baptism of John and that of Christ.

_Answ._
I answer, as to that John`'s baptism was unto repentance, the difference lieth not there,
because so is Christ`'s also;
for our adversaries will not deny but that adult persons that are to be baptized ought,
ere they be admitted to it, to repent and confess their sins, yea and that infants,
with a respect to and consideration of their baptism, ought to repent and confess:
so that the difference lieth not here,
since this of repentance and confession agrees as well to Christ`'s as to John`'s baptism.
But in this our adversaries are divided:
for Calvin will have Christ`'s and John`'s to be all one (Inst.
lib. 4, cap.
15, sect.
7,8). Yet they do differ, and the difference is in that the one is by water,
the other not, etc.

Secondly,
as to what Christ saith in commanding them to "`baptize in the Name of the Father, Son,
and Spirit,`" I confess that states the difference, & it is great;
but that lies not only in admitting water-baptism in this different form,
by a bare expressing of these words: for as the text saith no such thing,
neither do I see how it can be inferred from it.
// lint-disable invalid-characters
For the Greek is ἐιϛ τὸ ὂνμα, that is, "`into the name`";
now the name of the Lord is often taken in Scripture for something
else than a bare sound of words or literal expression,
even for his virtue and power, as may appear from Ps. 54:1, Song. 1:3,
Prov. 18:10, and in many more.
Now that the apostles were, by their ministry, to baptize the nations into this Name,
Virtue and Power, and that they did so,
is evident by these testimonies of Paul above mentioned,
where he saith that "`as many of them as were baptized into Christ have put on Christ`";
this must have been a baptizing into the Name, i.e., Power and Virtue,
and not mere formal expression of words adjoined with water-baptism,
because as hath been above observed,
it doth not follow as a natural or necessary consequence of it.
I would have those who desire to have their faith built upon no other
foundation than the testimony of God`'s Spirit and Scriptures of Truth,
thoroughly to consider whether there can be anything further alleged for this interpretation
than what the prejudice of education and influence of tradition hath imposed;
perhaps it may stumble the unwary and inconsiderate reader,
as if the very character of Christianity were abolished,
to tell him plainly that this Scripture is not to be understood of baptizing
with water and that this form of "`baptizing in the name of the Father,
Son, and Spirit,`" hath no warrant from Matt. 28, etc.

For which,
besides the reason taken from the signification of "`the
Name`" as being the Virtue and Power above expressed,
let it be considered that if it had been a form prescribed by Christ to his apostles,
then surely they would have made use of that form in the administering of water-baptism,
to such as they baptized with water;
but though particular mention be made in divers places of the Acts,
who were baptized and how;
and though it be particularly expressed that they baptized such and such, as Acts 2:41;
8:12-13, 38; 9:18; 10:48; 16:15, 18:8, yet there is not a word of this form;
and in two places (Acts 8:16, 19:5) it is said of some that they were
"`baptized in the name of the Lord Jesus,`" by which it yet more appears,
that either the author of this history hath been very defective,
who having so often occasion to mention this yet omitteth so substantial
a part of baptism (which were to accuse the Holy Ghost,
by whose guidance Luke wrote it) or else that the apostle did no ways understand that
Christ by his commission (Matt. 28) did enjoin them such a form of water-baptism,
seeing they did not use it;
and therefore it is safer to conclude that what they did
in administering water-baptism they did not by virtue of that commission;
else they would have so used it: for our adversaries, I suppose,
would judge it a great heresy to administer water baptism without that,
or only in the name of Jesus without mention of Father or Spirit,
as it is expressly said they did in the two places above cited.

Secondly, they say, If this were not understood of water-baptism,
it would be a tautology, and all one with teaching.

I say nay:
baptizing with the Spirit is somewhat further than teaching or informing the understanding;
for it imports a reaching to, and melting the heart, whereby it is turned,
as well as the understanding informed: besides, we find often in the Scripture,
that teaching and instructing are put together without any absurdity or needless tautology,
and yet the two have a greater affinity, than teaching and baptizing with the Spirit.

_Obj._
Thirdly, they say, baptism, in this place, must be understood with water,
because it is the action of the apostles, and so cannot be the baptism of the Spirit,
which is the work of Christ, and his Grace; not of man, etc.

_Answ._
I answer, baptism with the Spirit, though not wrought without Christ and his Grace,
is instrumentally done by men fitted of God for that purpose,
and therefore no absurdity follows,
that baptism with the Spirit should be expressed as the action of the apostles:
for though it be Christ by his Grace that gives spiritual gifts,
yet the apostle (Rom. 1:11) speaks of his "`imparting to them spiritual gifts,`" and
he tells the Corinthians that he had "`begotten them through the Gospel`" (1 Cor. 4:15),
and yet to beget people unto the faith is the work of Christ and his Grace, not of men;
to convert the heart is properly the work of Christ,
and yet the Scripture oftentimes ascribes it to men, as being the instruments:
and since Paul`'s commission was "`to turn people from darkness to light,`"
though that be not done without Christ cooperating by his Grace,
so may also baptizing with the Spirit be expressed as performable by man,
as the instrument, though the work of Christ`'s Grace, be needful to concur thereunto;
so that it is no absurdity to say that the apostles
did administer the baptism of the Spirit.

_Obj._
Lastly, they say,
that since Christ saith here that he will
be with his disciples to the end of the world,
therefore water-baptism must continue so long.

_Answ._
If he had been speaking here of water-baptism, then that might have been urged;
but seeing that is denied and proved to be false, nothing from thence can be gathered,
he speaking of the baptism of the Spirit,
which we freely confess doth remain to the end of the world,
yea so long as Christ`'s presence abideth with his children.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IX. _Obj._
Thirdly,
they object the constant practice of the apostles in the primitive Church,
who they say did always administer water-baptism
to such as they converted to the faith of Christ,
and hence also they further urge that of Matt. 28 to have been meant of water,
or else the apostles did not understand it, in that in baptizing they used water;
or that in so doing they walked without a commission.

I answer, that it was the constant practice of the apostles, is denied,
for we have shown, in the example of Paul, that it was not so,
since it were most absurd to judge, that he converted only those few,
even of the church of Corinth, whom he saith he baptized;
nor were it less absurd to think that was a constant apostolic practice, which he,
that was not inferior to the chiefest of the apostles, and who declares,
he laboured as much as they all, rejoiceth he was so little in.
But further, the conclusion,
inferred from the apostles`' practice of baptizing with water,
to evince that they understood Matt. 28 of water-baptism, doth not hold: for,
though they baptized with water;
it will not follow that either they did it by virtue of that commission,
or that they mistook that place; nor can there be any medium brought,
that will infer such a conclusion.
As to the other insinuated absurdity, that they did it without a commission:
it is none at all, for they might have done it by a permission,
as being in use before Christ`'s death.
And because the people, nursed up with outward ceremonies,
could not be weaned wholly from them.
And thus they used other things, as circumcision, and legal purifications,
which yet they had no commission from Christ to do (to which we shall
speak more at length in the following Proposition concerning the Supper.)

_Obj._
But if, from the sameness of the word, because Christ bids them baptize,
and they afterwards, in the use of water, are said to baptize, it be judged probable,
that they did understand that commission, Matt. 28,
to authorize them to baptize with water, and accordingly practised it.

_Answ._
Although it should be granted that for a season they did so far mistake it,
as to judge that water belonged to that baptism (which
however I find no necessity of granting),
yet I see not any great absurdity would thence follow;
for it is plain they did mistake that commission, as to a main part of it, for a season;
as where he bids them "`Go, teach all nations`";
since some time after they judged it unlawful to teach the Gentiles;
yea Peter himself scrupled it, until, by a vision, constrained thereunto, for which,
after he had done it,
he was for a season (until they were better informed) judged by the rest of his brethren.
Now, if the education of the apostles as Jews,
and their propensity to adhere and stick to the Jewish religion,
did so far influence them, that even after Christ`'s resurrection,
and the pouring forth of the Spirit,
they could not receive nor admit of the teaching of the Gentiles, though Christ,
in his commission to them, commanded them to preach to them;
what further absurdity were it to suppose that through
the like mistake the chiefest of them,
having been the disciples of John,
and his baptism being so much prized there among the Jews,
that they also took Christ`'s baptism, intended by him of the Spirit, to be that of water,
which was John`'s, and accordingly practised it, for a season; it suffices us,
that if they were so mistaken (though I say not that they
were so) they did not always remain under that mistake,
else Peter would not have said of the baptism which now saves,
"`that it is not a putting away of the filth of the
flesh,`" which certainly water baptism is.

But further, they urge much Peter`'s baptizing Cornelius: in which they press two things:
first, that water baptism is used, even to those that had received the Spirit; secondly,
that it is said positively, "`he commanded them to be baptized`" (Acts 10:47-48).

But neither of these doth necessarily infer water-baptism
to belong to the New Covenant dispensation,
nor yet to be a perpetual standing ordinance in the Church.
For first, all that this will amount to,
was that Peter at that time baptized these men,
but that he did it by virtue of that commission, Matt. 28, remains yet to be proved.
And how doth the baptizing with water,
after the receiving of the Holy Ghost prove the case,
more than the use of circumcision and other legal rites
acknowledged to have been acted by him afterwards;
also, no wonder if Peter,
that thought it so strange (notwithstanding all that had been professed before
and spoken by Christ) that the Gentiles should be made partakers of the Gospel,
and with great difficulty, not without a very extraordinary impulse thereunto,
was brought to come to them, and eat with them, was apt to put this ceremony upon them,
which being, as it were, the particular dispensation of John, the forerunner of Christ,
seemed to have greater affinity with the Gospel, than the other Jewish ceremonies,
then used by the Church; but that will no ways infer our adversaries`' conclusion.
Secondly, as to these words,
"`And he commanded them to be baptized,`" it declareth matter of _fact,_ not of _right,_
and amounteth to no more than that Peter did at that time, _pro hic et nunc,_
command those persons to be baptized with water, which is not denied,
but it saith nothing that Peter commanded water-baptism
to be a standing and perpetual ordinance to the Church;
neither can any man of sound reason say, if he heed what he says,
that a command in matter of fact to particular persons doth infer
the thing commanded to be of general obligation to all;
if it be not otherways bottomed upon some positive precept;
why doth Peter`'s commanding Cornelius and his household
to be baptized at that time infer water-baptism to continue,
more than his constraining (which is more than commanding)
the Gentiles in general to be circumcised,
and observe the Law?
We find at that time, when Peter baptized Cornelius,
it was not yet determined whether the Gentiles should not be circumcised;
but on the contrary, it was the most general sense of the Church that they should.
And therefore no wonder,
if they thought it needful at that time that they should be baptized;
which had more affinity with the Gospel, and was a burden less grievous.

[.small-break]
'''

// lint-disable invalid-characters "§"
§X. _Obj._
Fourthly,
they object from the signification of the word "`baptize,`"
which is as much as to dip and wash with water;
alleging thence that the very word imports a being baptized with water.

_Answ._
This objection is very weak.
For since baptizing with water was a rite among the Jews, as Paulus Riccius showeth,
even before the coming of John,
and that the ceremony received that name from the nature of the practice,
as used both by the Jews and by John,
yet we find that Christ and his apostles frequently make
use of these terms to a more spiritual signification.
Circumcision was only used and understood, among the Jews, to be that of the flesh.
But the apostle tells us of the "`circumcision of the heart and
spirit made without hands.`" So that though baptism was used,
among the Jews, only to signify a washing with water, yet both John, Christ,
and his apostles, speak of a being "`baptized with the Spirit,
and with fire,`" which they make the peculiar baptism of Christ,
as contradistinguished from that of water, which was John`'s (as is above shown).
So that though baptism, among the Jews, was only understood of water,
yet among Christians, it is very well understood of the Spirit without water,
as we see Christ and his apostles spiritually to understand things,
under the terms of what had been shadows before.
Thus Christ,
speaking of his body (though the Jews mistook him) said he would
"`destroy this temple,`" and "`build it again in three days`";
and many more that might be instanced.
But if the etymology of the word should be tenaciously adhered to,
it would militate against most of our adversaries, as well as against us; for the Greek
// lint-disable invalid-characters
βαπτίζω signifies _immergo,_ that is, to "`plunge`" and "`dip in`";
and that was the proper use of water-baptism among the Jews, and also by John,
and the primitive Christians, who used it; whereas our adversaries, for the most part,
only sprinkle a little water upon the forehead,
which doth not at all answer to the word "`baptism.`" Yea those of old among Christians,
that used water baptism, thought this dipping or plunging so needful,
that they thus dipped children.
And forasmuch as it was judged that it might prove hurtful to some weak constitutions,
sprinkling, to prevent that hurt, was introduced; yet then it was likewise appointed,
that such as were only sprinkled and not dipped,
should not be admitted to have any office in the Church,
as not being sufficiently baptized.
So that if our adversaries will stick to the word,
they must alter their method of sprinkling.

_Obj._
Fifthly, They object (John 3:5), "`Except a man be born of Water,
and of the Spirit,`" etc., hence inferring the necessity of water baptism,
as well as of the Spirit.

_Answ._
But, if this prove any thing, it will prove water-baptism to be of absolute necessity;
and therefore Protestants rightly affirm, when this is urged upon them by Papists,
to evince the absolute necessity of water-baptism,
that "`water`" is not here understood of outward water;
but mystically of an inward cleansing and washing;
even as where Christ speaks of being "`baptized with fire,`"
it is not to be understood of outward material fire,
but only of purifying, by a metonymy; because to purify is a proper effect of fire,
as to wash and make clean is of water; where it can as little be so understood,
as where we are said to be "`saved by the washing of regeneration`"
(Tit. 3:5). Yea Peter saith expressly,
in the place often cited, as Calvin well observes,^
footnote:[In the 4th book of his _Instit._ chap. 15.]
"`that the baptism which saves is not the putting away of the filth of
the flesh.`" So that since "`water`" cannot be understood of outward water,
this can serve nothing to prove water baptism.

_Obj._
If it be said, that "`water`" imports here _necessitatem praecepti,_ though not _medii;_

_Answ._
I answer, that is first to take it for granted that outward water is here understood,
the contrary whereof we have already proved.
Next, "`water`" and the "`Spirit`" are placed here together:
"`Except a man be born of water and the Spirit,`" where the necessity of the one is urged,
as much as of the other.
Now, if the Spirit be absolutely necessary, so will also water,
and then we must either say, that to be born of the Spirit is not absolutely necessary,
which all acknowledge to be false; or else that water is absolutely necessary, which,
as Protestants, we affirm, and have proved, is false: else we must confess,
that "`water`" is not here understood of outward water.
For to say, that when "`water`" and the "`Spirit`" are placed here just together,
and in the same manner,
though there be not any difference or ground for it visible in the text,
or deducible from it, that the necessity of water is here _praecepti,_ but not _medii,_
but the necessity of the Spirit is both _medii_ and _praecepti,_
is indeed confidently to affirm, but not to prove.

_Obj._
Sixthly and lastly, they object that the baptism of water is a visible sign, or badge,
to distinguish Christians from infidels, even as circumcision did the Jews.

_Answ._
I answer; This saith nothing at all, unless it be proved to be a necessary precept,
or part of the New Covenant dispensation;
it not being lawful for us to impose outward ceremonies and rites,
and say they will distinguish us from infidels.
Circumcision was positively commanded, and said to be a seal of the first Covenant, but,
as we have already proved that there is no such command for baptism,
so there is not any word in all the New Testament, calling it a badge of Christianity,
or seal of the New Covenant; and therefore,
to conclude it is so because circumcision was so (unless some better
proof be alleged for it) is miserably to beg the question.
The professing of faith in Christ, and a holy life answering thereunto,
is a far better badge of Christianity than any outward washing,
which yet answers not to that of circumcision,
since that affixed a character in the flesh, which this doth not;
so that a Christian is not known to be a Christian by his being baptized,
especially when he was a child, unless he tell them so much;
and may not the professing faith in Christ signify that as well?
I know there are divers of those, called Fathers, that speak much of water baptism,
calling it _character Christianitatis,_ but so did they also of the sign of the cross,
and other such things, justly rejected by Protestants.
For the mystery of iniquity, which began to work even in the apostles`' days,
soon spoiled the simplicity and purity of the Christian worship,
so that not only many Jewish rites were retained,
but many heathenish customs and ceremonies introduced into the Christian worship,
as particularly that word "`sacrament,`" so that it is a great folly,
especially for Protestants, to plead anything of this from tradition or antiquity;
for we find that neither Papists nor^
footnote:[Some later editors insert "`most`" before "`Protestants`" here.]
Protestants use these rites exactly as the ancients did, who, in such things,
not walking by the most certain rule of God`'s Spirit, but doting too much upon outwards,
were very uncertain: for most of them all, in the primitive times,
did wholly plunge and dip those they baptized, which neither Papists nor Protestants do:
yea,
several of the Fathers accused some as heretics in their days for
holding some principles common with Protestants concerning it;
as particularly Augustine doth the Pelagians,
for saying that infants dying unbaptized may be saved.
And the Manichees were condemned for denying that grace is universally given by baptism;
and Julian the Pelagian by Augustine,
for denying exorcism and insufflation in the use of baptism:
all which things Protestants deny also.
So that Protestants do but foolishly to upbraid us,
as if we could not show any among the ancients that denied water baptism,
seeing they cannot show any,
whom they acknowledge not to have been heretical in several things, to have used it,
nor yet who using it did not use also the sign of the cross, and other things with it,
which they deny.
There were some nevertheless in the darkest times of Popery,
who testified against water-baptism.
For one Alain (pages 103, 104,
107) speaks of some in his time that were burnt for the denying of it:
for they said that baptism had no efficacy either in children or adult persons;
and therefore men were not obliged to take baptism.
Particularly ten canonics, so called,
were burnt for that crime by the order of King Robert of France.
And P. Pithaeus tells in his fragments of the history of Guienne,
which is also confirmed by one Johannes Floracensis, a monk, who was famous at that time,
in his epistle to Oliva, Abbot of the Ausonian church.
"`I will,`" saith he,
"`give you to understand concerning the heresy that was in the city of Orleans on Childermas-day;
for it was true, if ye have heard anything, that King Robert caused to be burnt alive,
nigh fourteen of that city, of the chief of their clergy,
and the more noble of their laics, who were hateful to God,
and abominable to heaven and earth, for they did stiffly deny the Grace of holy baptism,
and also the consecration of our Lord`'s body and blood.`"
The time of this deed is noted in these words by Papir.
Masson, in his [.book-title]#Annals of France,# lib.
3; in Hugh and Robert,
__Actum Aureliae publice anno Incarnationis Domini 1022; regni Roberti Regis 28;
Indictione 5. quando Stephanus Haeresiarcha et Complices ejus damnati sunt et exusti Aurelia.__

Now for their calling them heretics and Manichees,
we have nothing but the testimony of their accusers,
which will no more invalidate their testimony
for this truth against the use of water-baptism,
or give more ground to charge us as being one with Manichees, than, because some,
called by them Manichees, do agree with Protestants in some things,
that therefore Protestants are Manichees or heretics, which Protestants can no ways shun.
For the question is, whether, in what they did,
they walked according to the Truth testified of by the Spirit in the Holy Scriptures;
so that the controversy is brought back again to the Scriptures,
according to which I suppose I have formerly discussed it.

As for the latter part of the thesis, denying the use of infant baptism,
it necessarily follows from what is above said, for if water-baptism be ceased,
then surely baptizing of infants is not warrantable.
But those that take upon them to oppose us in this matter will have more to do,
as to this latter part: for after they have done what they can to prove water-baptism,
it remains for them to prove that infants ought to be baptized.
For he that proves water baptism ceased, proves that infant baptism is vain.
But he that should prove that water-baptism continues,
has not thence proved that infant baptism is necessary.
That needs something further, and therefore it was a pitiful subterfuge of Nic.
Arnoldus against this,
to say that the denying of infant baptism belonged to the gangrene of Anabaptists,
without adding any further probation.
