== THE THIRTEENTH PROPOSITION

Concerning the Communion, or participation of the Body and Blood of Christ

The communion of the body and blood of Christ is inward and spiritual,
which is the participation of his flesh and blood,
by which the inward man is daily nourished in the hearts of those in whom Christ dwells,
of which things the breaking of bread by Christ with his disciples was a figure,
which they even used in the Church for a time,^
footnote:[1 Cor. 10:16-17; John 6:32-35; 1 Cor. 5:8.]
who had received the Substance, for the sake of the weak:
even as abstaining from things strangled, and from blood,
the washing one another`'s feet, and the anointing of the sick with oil,
all which are commanded with no less authority and solemnity than the former;^
footnote:[Acts 15:20; John 13:14; James 5:14.]
yet seeing they are but shadows of better things,
they cease in such as have obtained the Substance.

// lint-disable invalid-characters "§"
§I. The communion of the body and blood of Christ is a mystery
hid from all natural men in their first fallen and degenerate state,
which they cannot understand, reach to, nor comprehend, as they there abide; neither,
as they there are, can they be partakers of it,
nor yet are they able to "`discern the Lord`'s body`": and forasmuch as the Christian world,
so called, for the most part hath been still labouring, working, conceiving,
and imagining in their own natural and unrenewed
understandings about the things of God and religion,
therefore hath this mystery much been hid and sealed up from them,
while they have been contending, quarrelling,
and fighting one with another about the mere shadow, outside, and form,
but strangers to the Substance, Life and Virtue.

// lint-disable invalid-characters "§"
§II. The body, then, of Christ, which believers partake of,
is spiritual and not carnal, and his blood, which they drink of, is pure and heavenly,
and not human or elementary,
as Augustine also affirms of the body of Christ which is eaten, in his Tractat+++.+++,
Ps. 98, "`Except a man eat my flesh, he hath not in him life eternal,`" and he saith,
"`The words which I speak unto you are Spirit and life,
understand spiritually what I have spoken.
Ye shall not eat of this body, which ye see, and drink this blood,
which they shall spill, that crucify me--I am the living bread,
who have descended from heaven; he called himself the bread, who descended from heaven,
exhorting that we might believe in him,`" etc.

Quest.
If it be asked then what that body, what that flesh and blood is?

Answ.
I answer, it is that heavenly Seed, that divine, spiritual, celestial Substance,
of which we spake before, in the Fifth and Sixth Propositions.
This is that vehiculum Dei, or^
footnote:[Later editions omit "`vehiculum Dei, or`"]
spiritual body of Christ, whereby and wherethrough he communicateth life to man,
and salvation "`to as many as believe in him,`" and "`receive him,`" and whereby
also man comes to have fellowship and communion with God.
This is proved from the 6th of John, from verse 32 to the end,
where Christ speaks more at large of this matter, than in any other place:
and indeed this evangelist and beloved disciple, who lay in the bosom of our Lord,
gives us a more full account of the spiritual sayings and doctrine of Christ;
and it`'s observable that though he speaks nothing of the ceremony, used by Christ,
of breaking bread with his disciples,
neither in his evangelical account of Christ`'s life and sufferings, nor in his epistles,
yet he is more large in this account of the participation of the body,
flesh and blood of Christ, than any of them all.
For Christ, in this chapter,
perceiving that the Jews did follow him for love of the loaves,
desires them (verse 27) to "`labour, not for the meat which perisheth,
but for that meat which endureth forever`"; but forasmuch as they,
being carnal in their apprehensions,
and not understanding the spiritual language and doctrine of Christ, did judge the manna,
which Moses gave their fathers, to be the most excellent bread, as coming from heaven.
Christ, to rectify that mistake, and better inform them, affirmeth, first,
that it is not Moses, but his Father,
that giveth the "`true bread from heaven`" (vv. 32 and 48). Secondly,
this bread he calls himself (verse 35),
"`I am the bread of life.`" And (verse 51) "`I am the
living bread which came down from heaven.`" Thirdly,
he declares that this bread is his flesh (verse 51),
"`The bread that I will give is my flesh.`" And (verse 55) "`For my flesh is meat indeed,
and my blood is drink indeed.`" Fourthly, the necessity of partaking thereof (verse 53),
"`Except ye eat the flesh of the Son of man, and drink his blood,
ye have no life in you.`" And lastly (verse 33),
the blessed fruits and necessary effects of this
communion of the body and blood of Christ:
"`This bread giveth life to the world`" (verse 50),
"`He that eateth thereof dieth not`" (verse 58), "`he that eateth of this bread,
shall live forever`" (verse 51), "`whoso eateth this flesh, and drinketh this blood,
shall live forever`" (verse 54), "`and he dwelleth in Christ,
and Christ in him`" (verse 56),
"`and shall live by Christ`" (verse 57). From this large description of the origin, nature,
and effects of this body, flesh, and blood of Christ,
it is apparent that it is spiritual, and to be understood of a spiritual body,
and not of that body, or temple of Jesus Christ, which was born of the virgin Mary,
and in which he walked, lived, and suffered in the land of Judea;
because that it is said both, that it came down from heaven, yea that it is he,
that came down from heaven.
Now all Christians at present generally acknowledge that
the outward body of Christ came not down from heaven,
neither was it that part of Christ, which came down from heaven.
And to put the matter out of doubt,
when the carnal Jews would have been so understanding it,
he tells them plainly (verse 63), "`It is the Spirit that quickeneth,
but the flesh profiteth nothing.`" This is also founded upon most sound and solid reason,
because it is the soul, not the body, that is to be nourished by this flesh and blood.
Now outward flesh cannot nourish nor feed the soul, there is no proportion,
nor analogy betwixt them,
neither is the communion of the saints with God by
a conjunction and mutual participation of flesh,
but of the Spirit: "`He that is joined to the Lord, is one Spirit,`"^
footnote:[Cor. 6:17.]
not by flesh (I mean outward flesh, even such as was that,
wherein Christ lived and walked when upon earth, and not flesh,
when transposed by a metaphor, to be understood spiritually) can only partake of flesh,
as Spirit of Spirit, as the body cannot feed upon Spirit,
neither can the Spirit feed upon flesh:
and that the flesh here spoken of is spiritually understood, appears further,
in that that which feedeth upon it shall never die: but the bodies of all men once die,
yea it behooved the body of Christ himself to die,
that this body and spiritual flesh and blood of Christ
is to be understood of that divine and heavenly Seed,
before spoken of by us, appears both by the nature and fruits of it: first, it`'s said,
"`it is that, which cometh down from heaven, and giveth life unto the world`": now,
this answers to that Light and Seed,
which is testified of (John 1) to be the "`Light of the world,`"
and the "`Life of men.`" For that spiritual Light and Seed,
as it receives place in men`'s hearts, and room to spring up there,
is as bread to the hungry and fainting soul, that is, as it were,
buried and dead in the lusts of the world, which receives life again,
and revives, as it tasteth and partaketh of this heavenly bread;
and they that partake of it are said to come to Christ;
neither can any have it but by coming to him,
and believing in the appearance of his Light in their hearts, by receiving which,
and believing in it, the participation of this body and bread is known.
And that Christ understands the same thing here by his body, flesh, and blood,
which is understood (John 1) by the "`Light enlightening every man,`" and the Life, etc.,
appears, for the Light and Life, spoken of (John 1), is said to be Christ,
he is the true Light; and the bread and flesh, etc., spoken of in John 6,
is called Christ; "`I am the bread of life,`" saith he.
Again, "`They, that received that light and life`" (John 1:12),
"`obtained power to become the sons of God, by believing in his name`":
so also here (John 6:35), "`he that cometh unto this bread of life shall not hunger,
and he that believes in him, who is this bread, shall never thirst.`" So then,
as there was the outward visible body and temple of Jesus Christ,
which took its origin from the virgin Mary,
so there is also the Spiritual body of Christ, by and through which he,
that was the "`Word in the beginning with God,`" and was, and is, God,
did reveal himself to the sons of men in all ages,
and whereby men in all ages come to be made partakers of eternal life,
and to have communion and fellowship with God and Christ.
Of which body of Christ, and flesh and blood, if both Adam, and Seth, and Enoch,
and Noah, and Abraham, and Moses, and David,
and all the prophets and holy men of God had not eaten, they had not had life in them,
nor could their inward man have been nourished.
Now, as the outward body and temple was called Christ, so was also this spiritual body,
no less properly, and that long before that outward body was in being.
Hence the apostle saith (1 Cor. 10:3-4),
that the "`fathers did all eat the same spiritual meat;
and did all drink the same spiritual drink (for they
drank of that Spiritual Rock that followed them,
and that Rock was Christ.)`" This cannot be understood
otherwise than of this spiritual body of Christ:
which spiritual body of Christ, though it was the saving food of the righteous,
both before the Law, and under the Law, yet under the Law it was veiled and shadowed,
and covered under divers types, ceremonies, and observations; yea and not only so,
but it was veiled and hid, in some respect,
under the outward temple and body of Christ, or during the continuance of it:
so that the Jews could not understand Christ`'s preaching about it, while on earth.
And, not the Jews only, but many of his disciples, judging it a "`hard saying,
murmured at it, and many from that time went back from him,
and walked no more with him.`"^
footnote:[John 6:60-66.]
I doubt not but that there are many also at this
day professing to be the disciples of Christ,
that do as little understand this matter, as those did,
and are as apt to be offended and stumble at it,
while they are gazing and following after the outward body,
and look not to that by which the saints are daily fed and nourished.
For as Jesus Christ, in obedience to the will of the Father,
did by the eternal Spirit offer up that body for
a propitiation for the remission of sins,
and finished his testimony upon earth thereby, in a most perfect example of patience,
resignation and holiness,
that all might be made partakers of the fruit of that sacrifice,
so hath he likewise poured forth into the hearts
of all men a measure of that divine Light and Seed,
wherewith he is clothed, that thereby, reaching unto the consciences of all,
he may raise them up out of death and darkness, by his Life and Light,
and thereby may be made partakers of his body,
and therethrough come to have fellowship with the Father and with the Son.

// lint-disable invalid-characters "§"
§III.
Quest.
If it be asked, how, and after what manner man comes to partake of it,
and to be fed by it?

Answ.
I answer in the plain and express words of Christ,
"`I am the bread of life`" (saith he) "`he that cometh to me shall never hunger;
he that believeth in me shall never thirst`": and again, "`for my flesh is meat indeed,
and my blood is drink indeed.`"^
footnote:[John 6:35,55.]
So whosoever thou art that askest this question, or readest these lines,
whether thou accountest thyself a believer, or really feelest,
by a certain and sad experience, that thou art yet in the unbelief,
and findest that the outward body and flesh of Christ is so far from thee,
that thou canst not reach it, nor feed upon it: yea,
though thou hast often swallowed down and taken in that which the Papists
have persuaded thee to be the real flesh and blood of Christ,
and hast believed it to be so, though all thy senses told thee the contrary;
or (being a Lutheran) hast taken that bread, in, and with, and under which,
the Lutherans have assured thee that the flesh and blood of Christ is:
or (being a Calvinist) hast partaken of that which the Calvinists say (though a figure
only of the body) gives them that take it a real participation of the body,
flesh, and blood of Christ, though they never knew how, norwhat way.
I say, if, for all this, thou findest thy soul yet barren, yea hungry,
and ready to starve for want of something thou longest for; know, that Light,
that discovers thy iniquity to thee, that shows thee thy barrenness, thy nakedness,
thy emptiness, is that body that thou must partake of, and feed upon; but that till,
by forsaking iniquity, thou turnest to it, comest unto it, receivest it,
though thou mayest hunger after it, thou canst not be satisfied with it;
for it "`hath no communion with darkness,`"^
footnote:[2 Cor. 6:14.]
nor canst thou "`drink of the cup of the Lord and the cup of devils,`" and
be "`partaker of the Lord`'s table and the table of devils`" (1 Cor. 10:21).
But as thou sufferest that small Seed of righteousness to arise in thee,
and to be formed into a birth, that new substantial birth,
that is brought forth in the soul, naturally feeds upon,
and is nourished by this spiritual body: yea,
as this outward birth lives not but as it sucks in breath by the outward elementary air,
so this new birth lives not in the soul,
but as it draws in and breathes by that spiritual air or vehicle:
and as the outward birth cannot subsist without some outward body to feed upon,
some outward flesh, and some outward drink, so neither can this inward birth,
without it be fed by this inward body, by this inward flesh and blood of Christ,
which answers to it after the same manner, by way of analogy.
And this is most agreeable to the doctrine of Christ concerning this matter, for,
as without outward food the natural body hath not life, so also saith Christ,
"`Except ye eat the flesh of the Son of man, and drink his blood,
ye have no life in you.`"^
footnote:[John 6:53.]
And as the outward body, eating outward food, lives thereby, so Christ saith,
that he that eateth him shall live by him.^
footnote:[John 6:57.]
So it is this inward participation of this inward man,
of this inward and spiritual body,
by which man is united to God and has fellowship and communion with him.
"`He that eateth my flesh, and drinketh my blood`" (saith Christ) "`dwelleth in me,
and I in him.`"^
footnote:[John 6:56.]
This cannot be understood of our outward eating of outward bread;
and as by this the soul must have fellowship with God,
so also insofar as all the saints are partakers of this one body, and one blood,
they come also to have a joint communion.
Hence the Apostle (1 Cor. 10:17), in this respect saith,
that they "`being many are one bread, and one body`":
and to the wise among the Corinthians he saith "`The bread which we break,
is the communion^
footnote:[Later editors replace "`is the communion`" with "`is it not the communion...?]
of the body of Christ.`"^
footnote:[Verse 16.]
This is the true and spiritual supper of the Lord,
which men come to partake of by hearing the voice of Christ,
and opening the door of their hearts, and so letting him in, in the manner above said,
according to the plain words of the scripture (Rev. 3:20), "`Behold,
I stand at the door and knock: if any man hear my voice, and open the door,
I will come in to him, and will sup with him,
and he with me.`" So that the supper of the Lord, and the supping with the Lord,
and partaking of his flesh and blood is no ways limited
to the ceremony of breaking bread,
and drinking wine at particular times; but is truly and really enjoyed,
as often as the soul retires into the Light of the Lord,
and feels and partakes of that heavenly Life, by which the inward man is nourished,
which may be, and is often witnessed by the faithful at all times,
though more particularly, when they are assembled together to wait upon the Lord.

// lint-disable invalid-characters "§"
§IV. But what confusion the professors of
Christianity have run into concerning this matter,
is more than obvious, who, as in most other things they have done,
for want of a true spiritual understanding,
have sought to tie this supper of the Lord to that ceremony (used by Christ
before his death) of breaking bread and drinking wine with his disciples.
And though they for most agree in this generally,
yet how do they contend and debate, one against another?
How strangely are they pinched, pained,
and straitened to make the spiritual mystery agree to that ceremony?
And what monstrous and wild opinions and conceivings have they invented
to enclose or affix the body of Christ to their bread and wine?
From which opinion not only the greatest and fiercest and most hurtful contests,
both among the professors of Christianity in general,
and among Protestants in particular, have arisen, but also such absurdities,
irrational and blasphemous consequences have ensued,
as makes the Christian religion odious and hateful to Jews, Turks, and heathens.
The professors of Christianity do chiefly divide, in this matter, into three opinions.

The first is of those that say the substance of the bread is transubstantiated
into the very substance of that same body,
flesh, and blood of Christ, which was born of the virgin Mary, and crucified by the Jews:
so that, after the words of consecration (as they call them) it is no more bread,
but the body of Christ.

The second is of such who say the substance of the bread remains,
but that also that body is in, and with, and under the bread:
so that both the substance of bread and of the body, flesh,
and blood of Christ is there also.

The third is of those that (denying both these) do affirm,
that the body of Christ is not there corporally, or substantially,
but yet that it is really and sacramentally received
by the faithful in the use of bread and wine;
but how, or what way it is there, they know not, nor can they tell,
only we must believe it is there, yet so that it is only properly in heaven.

It is not my design to enter into a refutation of these several opinions,
for each of their authors and assertors have sufficiently refuted one another,
and are all of them no less strong both from Scripture and reason,
in refuting each their contrary party`'s opinion,
than they are weak in establishing their own;
for I often have seriously observed in reading their respective
writings (and so it may be have others) that all of them do notably,
in so far as they refute the contrary opinions,
but that they are mightily pained when they come to confirm and plead for their own:
hence I necessarily to conclude,
that none of them had attained to the Truth and Substance of this mystery.
Let us see if Calvin,^
footnote:[Inst. lib. 4, cap. 17.]
after he had refuted the two former opinions, be more successful,
in what he affirms and asserts for the truth of his opinion, who,
after he hath much laboured in overturning and refuting the two former opinions,
plainly confesseth that he knows not what to affirm instead of them, for,
after he has spoken much, and at last concluded "`that the body of Christ is there,
and that the saints must needs partake thereof,`" at last he lands in these words (sect.
32), "`But if it be asked me, how it is,
I shall not be ashamed to confess that it is a secret,
too high for me to comprehend in my spirit,
or explain in words.`" Here he deals very ingenuously,
and yet who would have thought that such a man would have been brought to this strait,
in the confirming of his opinion; considering a little before, in the same chapter (sect.
15), he accuseth the schoolmen among the Papists (and I confess, truly),
in that they neither understand nor explain to others how Christ is in the Eucharist,
which shortly after he confesseth he himself cannot do.
If then the schoolmen among the Papists do neither understand, nor yet explain to others,
their doctrine in this matter,
nor Calvin can comprehend it in his spirit (which I judge is as much as not to understand
it) nor express it in words (and then surely he cannot explain it to others),
then no certainty is to be had from either of them.
There have been great endeavours used for reconcilement in this matter,
both betwixt Papists and Lutherans, Lutherans and Calvinists,
yea and Calvinists and Papists, but all to no purpose:
and many forms and manners of expressions drawn up, to which all might yield,
which in the end proved in vain,
seeing every one understood them and interpreted them their own way,
and so they did thereby but equivocate and deceive one another.
The reason of all this contention is,
because they all wanted a clear understanding of the mystery,
and were doting about the shadow and externals.
For both the ground and matter of their contest lies in things extrinsic from,
and unnecessary to the main matter;
and this hath been often the policy of Satan to busy people,
and amuse them with outward signs, shadows, and forms,
making them contend about that, while in the meantime the Substance is neglected;
yea and in contending for these shadows he stirs them up to the practice of malice, heat,
revenge, and other vices, by which he establisheth his kingdom of darkness among them,
and ruins the life of Christianity:
for there has been more animosity and heat about this one particular,
and more bloodshed and contention, than about any other.
And surely they are little acquainted with the state of Protestant affairs,
who know not that their contentions about this have been more hurtful to the Reformation,
than all the opposition they met with from their common adversaries.
Now all these uncertain and absurd opinions and the contentions therefrom arising have
proceeded from their all agreeing in two general errors concerning this thing.
Which being denied and receded from, as they are by us,
there would be an easy way made for reconciliation,
and we should all meet in the one spiritual and true understanding of this mystery; and,
as the contentions so would also the absurdities,
which follow from all the three forementioned opinions, cease and fall to the ground.

The first of these errors is, in making the communion or participation of the body,
flesh, and blood of Christ to relate to that outward body, vessel, or temple,
that was born of the virgin Mary, and walked and suffered in Judea,
whereas it should relate to the spiritual body, flesh and blood of Christ,
even that heavenly and celestial Light and Life,
which was the food and nourishment of the regenerate in all ages,
as we have already proved.

The second error is, in tying this participation of the body and blood of Christ,
to that ceremony, used by him with his disciples, in the breaking of bread, etc.,
as if it had only a relation thereto, or were only enjoyed in the use of that ceremony,
which it neither hath nor is.
For this is that bread, which Christ in his prayer teaches to call for, terming it
RESTORE-GREEK, i.e., the supersubstantial bread,
as the Greek hath it, and which the soul partakes of,
without any relation or necessary respect to this ceremony,
as shall be hereafter proved more at length.

These two errors being thus laid aside, and the contentions arising therefrom buried,
all are agreed in the main positions, viz., first, that the body, flesh,
and blood of Christ is necessary for the nourishing of the soul.
Secondly, that the souls of believers do really and truly partake and feed upon the body,
flesh, and blood of Christ.
But while men are not content with the spirituality of this mystery, going,
in their own wills, and according to their own inventions,
to strain and wrest the Scriptures,
for to tie this spiritual communion of the flesh and blood of Christ,
to outward bread and wine, and suchlike carnal ordinances, no wonder, if,
by their carnal apprehensions, they run into heaps and confusion.
But because it hath been generally supposed that the communion of the body and
blood of Christ had some special relation to the ceremony of breaking bread,
I shall first refute that opinion,
and then proceed to consider the nature and use of that ceremony,
and whether it be now necessary to continue,
answering the reasons and objections of such as plead its continuance,
as a necessary and standing ordinance of Jesus Christ.

// lint-disable invalid-characters "§"
§V. First it must be understood,
that I speak of a necessary and peculiar relation, otherwise than in a general respect:
for, forasmuch as our communion with Christ is,
and ought to be our greatest and chiefest work,
we ought to do all other things with a respect to God, and our fellowship with him;
but a special and necessary respect or relation is such
as where the two things are so tied and united together,
either of their own nature, or by the command of God, that the one cannot be enjoyed,
or at least is not (except very extraordinarily) without the other.
Thus salvation hath a necessary respect to holiness,
because "`without holiness no man shall see God.`" And the eating of the
flesh and blood of Christ hath a necessary respect to our having life,
because, if we eat not his flesh, and drink not his blood, we cannot have life;
and our feeling of God`'s presence hath a necessary
respect to our being found meeting in his Name,
by divine precept, because he has promised,
"`where two or three are met together in his Name, he will be in the midst of them`";
in like manner our receiving benefits and blessings
from God has a necessary respect to our praying,
because if we ask, he hath promised we shall receive.
Now the communion or participation of the flesh and blood of Christ hath
no such necessary relation to the breaking of bread and drinking of wine.
For, if it had any such necessary relation,
it would either be from the nature of the thing, or from some divine precept:
but we shall show it is from neither; therefore, etc. First,
it is not from the nature of it,
because to partake of the flesh and blood of Christ is a spiritual exercise,
and all confess that it is by the soul and spirit that we become real partakers of it,
as it is the soul, and not the body, that is nourished by it:
but to eat bread and drink wine is a natural act, which, in itself,
adds nothing to the soul, neither has anything that is spiritual in it,
because the most carnal man that is, can as fully, as perfectly,
and as wholly eat bread and drink wine as the most spiritual.
Secondly, their relation is not by nature, else they would infer one another:
but all acknowledge that many eat of the bread, and drink of the wine, even that which,
they say, is consecrate and transubstantiate into the very body of Christ,
who notwithstanding have not life eternal, have not Christ dwelling in them,
nor do live by him, as all do, who truly partake of the flesh and blood of Christ,
without the use of this ceremony, as all the patriarchs and prophets did,
before this ordinance (as they account it) was instituted:
neither was there anything under the Law,
that had any direct or necessary relation hereunto,
though to partake of the flesh and blood of Christ
in all ages was indispensably necessary to salvation.
For as for the Paschal lamb,
the whole end of it is signified particularly (Ex. 13:8-9), to wit,
that the Jews might thereby be kept in remembrance of their deliverance out of Egypt.
Secondly, it hath no relation by divine precept, for if it had,
it would be mentioned in that which our adversaries account the institution of it,
or else in the practice of it by the saints recorded in Scripture, but so it is not.
For as to the institution, or rather narration, of Christ`'s practice in this matter,
we have it recorded by the evangelists Matthew, Mark, and Luke.^
footnote:[Matt. 26:26; Mark 14:22; Luke 22:19.]
In the first two there is only an account of the matter of fact, to wit,
that Christ brake bread, and gave it his disciples to eat, saying, "`this is my body`";
and blessing the cup, he gave it them to drink, saying, "`this is my blood`";
but nothing of any desire to them to do it.
In the last, after the bread (but before the blessing, or giving them the wine),
he bids them "`do it in remembrance of him`";
what we are to think of this practice of Christ shall be spoken of hereafter.
But what necessary relation hath all this to the
believers`' partaking of the flesh and blood of Christ?
The end of this for which they were to do it (if at all) is to remember Christ,
which the apostle yet more particularly expresses (1 Cor. 11:26),
"`to show forth the Lord`'s death.`" But to remember the Lord, or declare his death,
which are the special and particular ends annexed to the use of this ceremony,
is not at all to partake of the flesh and blood of Christ,
neither have they any more necessary relation to it,
than any other two different spiritual duties.
For though they that partake of the flesh and blood of Christ cannot but remember him,
yet the Lord and his death may be remembered (as none can
deny) where his flesh and blood is not truly partaken of.
So that,
since the very particular and express end of this ceremony may be witnessed (to wit,
the remembrance of the Lord`'s death) and yet the
flesh and blood of Christ not partaken of,
it cannot have had any necessary relation to it,
else the partaking thereof would have been the end of it,
and could not have been attained without this participation.
But, on the contrary, we may well infer hence,
that since the positive end of this ceremony is not
the partaking of the flesh and blood of Christ,
and that whoever partakes of the flesh and blood of Christ, cannot but remember him;
that therefore such need not this ceremony to put them in remembrance of him.

Obj.
But if it be said, that Jesus Christ calls the bread here his body,
and the wine his blood,
therefore he seems to have had a special relation
to his disciples partaking of his flesh and blood,
in the use of this thing.

Answ.
I answer, his calling the bread his body, and the wine his blood,
would yet infer no such thing: though it is not denied but that Jesus Christ,
in all things he did, yea and from the use of all natural things,
took occasion to raise the minds of his disciples and hearers to spirituals.
Hence from the woman of Samaria her drawing water,
he took occasion to tell her of that Living Water,
which "`whoso drinketh of shall never thirst,`"^
footnote:[John 4:14.]which indeed is all one with his blood here spoken of.
Yet it will not follow that well or water had any necessary relation to the living water,
or the living water to it, etc. So Christ takes occasion,
from the Jews following him for the loaves,
to tell them of this spiritual bread and flesh of his body,
which was more necessary for them to feed upon.
It will not therefore follow,
that their following him for the loaves had any necessary relation thereunto.
So also Christ, here being at supper with his disciples,
takes occasion from the bread and wine, which was before them, to signify unto them,
that, as that bread, which he brake unto them, and that wine,
which he blessed and gave unto them,
did contribute to the preserving and nourishing of their bodies,
so was he also to give his body, and shed his blood for the salvation of their souls;
and therefore the very end proposed in this ceremony, to those, that observe it,
is to be a memorial of his death.

But if it be said that the apostle (1 Cor. 10:16) calls the bread
which he brake "`the communion of the body of Christ,`" and the cup,
"`the communion of his blood.`"

I do most willingly subscribe unto it,
but do deny that this is understood of the outward bread, neither can it be evinced,
but the contrary is manifest from the context,
for the apostle in this chapter speaks not one word of that ceremony; for,
having in the beginning of it shown them,
how the Jews of old were made partakers of the spiritual food and water,
which was Christ, and how several of them, through disobedience and idolatry,
fell from that good condition, he exhorts them by the example of those Jews,
whom God destroyed of old, to flee those evils, showing them that they,
to wit the Corinthians, are likewise partakers of the body and blood of Christ,
of which communion they would rob themselves if they did evil,
because "`they could not drink of the cup of the Lord, and the cup of devils,
and partake of the Lord`'s table, and the table of devils`" (v. 21),
which shows that he understands not here the using of outward bread and wine:
because those that do drink the cup of devils, and eat of the table of devils,
yea the wickedest of men, may partake of the outward bread and outward wine.
For there the apostle calls the bread one (v. 17), and he saith,
"`We being many are one bread and one body,
for we are all partakers of that one bread.`" Now, if the bread be one,
it cannot be the outward, or the inward would be excluded,
whereas it cannot be denied but that it`'s the partaking of inward bread,
and not the outward,
that makes the saints truly "`one body,`" and "`one bread.`" And whereas they
say that the one bread here comprehendeth both the outward and inward,
by virtue of the sacramental union: that indeed is to affirm, but not to prove.
As for that figment of a sacramental union, I find not such a thing in all the Scripture,
especially in the New Testament,
nor is there anything can give a rise for such a thing in this chapter,
where the apostle, as is above observed, is not at all treating of that ceremony,
but only, from the excellency of that privilege, which the Corinthians had,
as believing Christians, to partake of the flesh and blood of Christ,
dehorts them from idolatry and partaking of the sacrifices offered to idols,
so as thereby to offend or hurt their weak brethren.

Obj.
But that which they most of all cry out for in this matter, and are always noising,
is from 1 Cor. 11, where the apostle is particularly treating of this matter,
and therefore from some words here they have the
greatest appearance of truth for their assertion,
as (v. 27) where he calls the cup the "`cup of the Lord,`" and saith,
"`that they who eat of it and drink it unworthily,
are guilty of the body and blood of the Lord,`" and (v. 29),
"`eat and drink their own damnation,`" intimating thence that
this hath an immediate or necessary relation to the body,
flesh, and blood of Christ.

Answ.
Though this, at first view, may catch the unwary reader, yet being well considered,
it doth no ways evince the matter in controversy.
As for the Corinthians being in the use of this ceremony, why they were so,
and how that obliges not Christians now to the same, shall be spoken of hereafter:
it suffices at this time to consider that they were in the use of it.
Secondly, that in the use of it they were guilty of, and committed divers abuses.
Thirdly, that the apostle here is giving them directions how they may do it aright,
in showing them the right and proper use and end of it.

These things being premised,
let it be observed that the very express and particular use of it,
according to the apostle,
is "`to show forth the Lord`'s death,`" etc. But to show forth the
Lord`'s death and partake of the flesh and blood of Christ,
are different things.
He saith not, as often as ye eat this bread, and drink this cup,
ye partake of the body and blood of Christ; but,
"`ye show forth the Lord`'s death.`" So I acknowledge that this ceremony,
by those that practise it,
hath an immediate relation to the outward body and death of Christ upon the cross,
as being properly a memorial of it, but it doth not thence follow,
that it hath any inward or immediate relation to believers communicating
or partaking of the spiritual body and blood of Christ,
or that spiritual supper, spoken of (Rev. 3:20), for though, in a general way,
as every religious action, in some respect,
hath a common relation to the spiritual communion of the saints with God,
so we shall not deny but this hath a relation, as others.
Now for his calling the cup, "`the cup of the Lord,`" and saying,
"`they are guilty of the body and blood of Christ,
and eat their own damnation in not discerning the Lord`'s body,`" etc., I answer,
that this infers no more necessary relation than any other religious act;
and amounts to no more than this,
that since the Corinthians were in the use of this ceremony, and so performed it,
as a religious act, they ought to do it worthily,
else they should bring condemnation upon themselves.
Now, this will not more infer the thing, so practised by them,
to be a necessary religious act obligatory upon others,
than when the apostle saith (Rom. 14:6), "`He that regardeth the day,
regardeth it unto the Lord,`" it can be thence inferred,
that the days that some esteemed observed did lay
an obligation upon others to do the same:
but yet as he that "`esteemed a day,`" and placed conscience in keeping it,
was to "`regard it to the Lord,`" and so it was to him,
in so far as he dedicated it unto the Lord, the Lord`'s day, he was to do it worthily,
and if he did it unworthily, he would be guilty of the Lord`'s day,
and so keep it to his own damnation:
so also such as observe this ceremony of bread and wine,
it is to them "`the bread of the Lord,`" and "`the cup of the
Lord,`" because they use it as a religious act,
and forasmuch as their end therein is to "`show forth
the Lord`'s death,`" and remember his body,
that was crucified for them, and his blood, that was shed for them.
If notwithstanding, they believe it is their duty to do it,
and make it a matter of conscience to forbear,
if they do it without that due preparation and examination
which every religious act ought to be performed in,
then instead of truly remembering the Lord`'s death, and his body and his blood,
they render themselves guilty of it,
as being in one spirit with those that crucified him, and shed his blood,
though pretending with thanksgiving and joy to remember it.
Thus the scribes and Pharisees of old,
though in memory of the prophets they garnished their sepulchres,
yet are said by Christ to be "`guilty of their blood.`"
And that no more can be hence inferred,
appears from another saying of the same apostle (Rom. 14:23), "`He that doubteth,
is damned if he eat,`" etc., where he, speaking of those,
that judged it unlawful to eat flesh, etc., saith, if they eat doubting,
they eat their own damnation.
Now it is manifest from all this, that either the doing or forbearing of this was,
to another, that placed no conscience in it, of no moment.
So I say, he that eateth that,
which in his conscience he is persuaded it is not lawful for him to eat,
doth eat his own damnation; so he also, that placeth conscience in eating bread and wine,
as a religious act, if he do it unprepared, and without that due respect,
wherein such acts should be gone about, he eateth and drinketh his own damnation,
not "`discerning the Lord`'s body,`" i.e., not minding what he doth, to wit,
with a special respect to the Lord,
and by way of special commemoration of the death of Christ.

// lint-disable invalid-characters "§"
§VI. I having now sufficiently shown what the true
communion of the body and blood of Christ is,
how it is partaken of,
and how it has no necessary relation to that ceremony
of bread and wine used by Christ with his disciples;
it is fit now to consider the nature and constitution
of that ceremony (for as to the proper use of it,
we have had occasion to speak of before) whether it be a standing
ordinance in the Church of Christ obligatory upon all,
or indeed whether it be any necessary part of the worship of the New Covenant dispensation,
or hath any better or more binding foundation than several other
ceremonies appointed and practised about the same time,
which the most of our opposers acknowledge to be ceased,
and now no ways binding upon Christians.
We find this ceremony only mentioned in Scripture in four places, to wit, Matthew, Mark,
and Luke, and by Paul to the Corinthians.
If any would infer anything from the frequency of the mentioning of it,
that will add nothing,
for it being a matter of fact is therefore mentioned by the evangelists;^
footnote:[Matt. 26:26; Mark 14:22; Luke 22:19; 1 Cor. 11:23.]
and there are other things less memorable as often, yea, oftener mentioned.
Matthew and Mark give only an account of the matter of fact,
without any precept to do so afterwards, simply declaring that Jesus, at that time,
did desire them to eat of the bread and drink of the cup.
To which Luke adds these words,
"`This do in remembrance of me.`" If we consider this action of Christ with his apostles,
there will appear nothing singular in it,
for a foundation to such a strange superstructure as many
in their airy imaginations have sought to build upon it;
for both Matthew and Mark press it as an act done by him as he was eating; Matthew saith,
"`and as they were eating`"; and Mark, "`and as they did eat,
Jesus took bread,`" etc. Now this act was no singular thing,
neither any solemn institution of a Gospel ordinance,
because it was a constant custom among the Jews,
as Paulus Riccius observes at length in his Celestial Agriculture,
that when they did eat the Passover,
the master of the family did take bread and bless it,
and breaking it gave of it to the rest, and likewise taking wine did the same;
so that there can nothing further appear in this, than that Jesus Christ,
who "`fulfilled all righteousness,`" and also observed the Jewish feasts and customs,
used this also among his disciples, only that as in most other things,
he laboured to draw their minds to a further thing, so, in the use of this,
he takes occasion to put them in mind of his death and sufferings,
which were shortly to be, which he did the oftener inculcate unto them,
for that they were averse from believing it.
And as for that expression of Luke,
"`Do this in remembrance of me,`" it will amount to no more than
being the last time that Christ did eat with his disciples,
he desired them that in their eating and drinking they might have regard to him,
and by the remembering of that opportunity be the more stirred
up to follow him diligently through sufferings and death,
etc. But what man of reason,
laying aside the prejudice of education and the influence of tradition,
will say that this account of the matter of fact, given by Matthew and Mark,
or this expression of Luke,
to "`do`" that "`in remembrance of him,`" will amount to these consequences,
which the generality of Christians have sought to draw from it,
as calling it "`augustissimum eucharistiae sacramentum`",
"`venerabile altaris sacramentum,`" "`the principal seal of the covenant of Grace,
by which all the benefits of Christ`'s death are sealed to believers,`" and suchlike things.
But to give a further evidence how these consequences
have not any bottom from the practice of that ceremony,
nor from the words following, "`do this,`" etc., let us consider another of the like nature,
as it is at length expressed by John 13:4-5,8,13-15: "`Jesus riseth from supper,
and laid aside his garments, and took a towel, and girded himself.
After that, he poureth water into a basin, and began to wash the disciples`' feet,
and to wipe them with the towel, wherewith he was girded.
Peter saith unto him, Thou shalt never wash my feet.
Jesus answered him, If I wash thee not, thou hast no part with me.
So after he had washed their feet, &hellip;he said, Know ye what I have done to you?
If I then your Lord and Master have washed your feet,
ye also ought to wash one another`'s feet.
For I have given you an example,
that ye should do as I have done to you.`" As to which let it be observed,
that John relates this passage to have been done
at the same time with the other of breaking bread.
Both being done the night of the Passover, after supper.
If we regard the narration of this, and the circumstances attending it,
it was done with far more solemnity, and prescribed far more punctually and particularly,
than the former.
It is said only, "`As he was eating,
he took bread,`" so that this would seem to be but an occasional business.
But here "`he rose up,`" "`he laid by his garments,`" "`he girded himself,`"
"`he poured out the water,`" "`he washed their feet,`" "`he wiped them
with a towel.`" "`He did this to all of them,`" which are circumstances
surely far more observable than those noted in the other.
The former was a practice common among the Jews,
used by all masters of families upon that occasion: but this, as to the manner,
and person acting it, to wit,
for the Master to rise up and wash the feet of his servants and disciples,
was more singular and observable.
In the breaking of bread and giving of wine, it is not pleaded by our adversaries,
nor yet mentioned in the text, that he particularly put them into the hands of all;
but breaking it and blessing it, gave it the nearest,
and so they from hand to hand.
But here it is mentioned that he washed not the feet of one or two, but of many.
He saith not in the former, that if they do not eat of that bread,
and drink of that wine, they shall be prejudiced by it:
but here he saith expressly to Peter, that, if he wash not him, he hath no part with him,
which, being spoken upon Peter`'s refusing to let him wash his feet,
would seem to import no less, than not the continuance only,
but even the necessity of this ceremony.
In the former he saith, as it were passingly, "`Do this in remembrance of me`":
but here he sitteth down, again he desires them to consider what he hath done,
tells them positively, that as he hath done to them, so ought they to do to one another,
and yet again he redoubles that precept, by telling them he has given them an example,
that they should do so likewise.
If we respect the nature of the thing,
it hath as much in it as either baptism or the breaking of bread,
seeing it is an outward element of a cleansing nature, applied to the outward man,
by the command and the example of Christ, to signify an inward purifying.
I would willingly propose this seriously to men,
that will be pleased to make use of that reason and understanding,
that God hath given them, and not be imposed upon,
nor abused by the custom or tradition of others, whether this ceremony,
if we respect either the time that it was appointed in,
or the circumstances wherewith it was performed, or the command enjoining the use of it,
hath not as much to recommend it for a standing ordinance of the Gospel,
as either water baptism, or bread and wine, or any other of that kind?
I wonder then, what reason the Papists can give,
why they have not numbered it among their sacraments,
except merely voluntas ecclesiae & traditio patrum.

But if they say, that it is used among them,
in that the Pope and some other persons among them
use to do it once a year to some poor people.

I would willingly know what reason they have why this should not be extended to all,
as well as that of the Eucharist (as they term it) or whence it appears from the text,
that "`Do this in remembrance of me,`" should be interpreted that
the bread and wine were every day to be taken by all priests,
or the bread every day, or every week, by the people:
and that that other command of Christ,
"`ye ought to do as I have done to you,`" etc.,
is only to be understood of the Pope or some other persons, to be done only to a few,
and that once a year.
Surely there can be no other reason for this difference assigned from the text.
And as to Protestants, who use not this ceremony at all,
if they will but open their eyes they may see how that by
custom and tradition they are abused in this matter,
as were their fathers in divers Popish traditions.
For if we look into the plain Scripture,
what can be thence inferred to urge the one which
may not be likewise pleaded for the other,
or for laying aside the one,
which may not be likewise said against the continuance of the other?
If they say that the former, of washing the feet, was only a ceremony,
what have they whence they can show that this breaking of bread is more?
If they say that the former was only a sign of humility and purifying,
what have they to prove that this was more?
If they say the one was only for a time and was no evangelical ordinance,
what hath this to make it such, that the other wanted?
Surely there is no way of reason to evite this,
neither can anything be alleged that the one should cease and not the other,
or the one continue and not the other, but the mere opinion of the affirmers,
which by custom, education, and tradition,
hath begotten in the hearts of people a greater reverence
for and esteem of the one than the other,
which, if it had fallen out to be as much recommended to us by tradition,
would no doubt have been as tenaciously pleaded for,
as having no less foundation in the Scripture.
But since the former, to wit the washing of one another`'s feet, is justly laid aside,
as not binding upon Christians, so ought also the other for the same reason.

// lint-disable invalid-characters "§"
§VII.
But it is strange that those that are so clamorous for this ceremony,
and stick so much to it,
take liberty to dispense with the manner or method that Christ did it in, since none,
that ever I could hear of,^
footnote:[Later editors insert, "`except some Baptists.`"]
who now do it, use it in the same way that he did: Christ did it at supper,
while they were eating, but they^
footnote:[Later editors change "`they`" to "`the generality of Protestants.`"]
do it in the morning only by itself.
What rule walk they by in this change?

Obj.
If it be said, these are but circumstances, and not the matter,
and if the matter be kept to, the alteration of circumstances is but of small moment.

Answ.
What if it should be said, the whole is but a circumstance, which fell out at that time,
when Christ did eat the Passover?
For, if we have regard to that, which alone can be pleaded for an institution,
viz. these words,
"`Do this in remembrance of me,`" it doth as properly relate to the manner, as matter.
For what may, or can they evince in reason, that these words,
"`Do this,`" only signify eat bread and drink wine; but it is no matter, when ye eat,
nor how ye eat it, and not, as ye have seen me eat it at supper with you, who take bread,
and break it, and give it you, and take the cup, and bless it, and give it you;
so do ye likewise?
And seeing Christ makes no distinction in those words,
"`Do this,`" it cannot be judged in reason but to relate to the whole.
Which if it do, all those that at present use this ceremony among Christians,
have not yet obeyed this precept, nor fulfilled this institution,
for all their clamors concerning it.

Obj.
If it be said, that the time and manner of doing it by Christ was but accidentally,
as being after the Jewish passover, which was at supper.

Answ.
Besides that it may be answered and easily proved, that the whole was accidental,
as being the practice of a Jewish ceremony, as is above observed:
may it not the same way be urged, that the drinking of wine was accidental,
as being the natural product of that country, and so be pleaded, that,
in those countries where wine doth not grow, as in our nation of Scotland,
we may make use of beer or ale in the use of this ceremony,
or bread made of other grain than that which Christ used?
And yet would not our adversaries judge this an abuse,
and not right performing of this "`sacrament`"? Yea have not scruples of
this kind occasioned no little contention among the professors of Christianity?
What great contest and strife hath been betwixt the
Greek and Latin churches concerning the bread?
While the one will have it unleavened, reckoning,
because the Jews made use of unleavened bread in the Passover,
that it was such kind of bread, that Christ did break to his disciples,
the other leavened; therefore the Lutherans make use of unleavened bread,
the Calvinists of leavened: and this contest was so hot,
when the Reformation was beginning at Geneva,
that Calvin and Farellus were forced to flee for it.
But do not Protestants by these uncertainties open a door
to Papists for their excluding the people from the cup?
Will not "`Do this`" infer positively that they should do in the same manner,
and at the same time, which Christ did it, as well as that they should use the cup,
and not the bread only?
Or what reason have they to dispense with the one,
more than the Papists have to do with the other?
O! What strange absurdities and inconveniences have Christians brought upon themselves,
by superstitiously adhering to this ceremony?
Out of which difficulties it is impossible for them to extricate themselves,
but by laying it aside, as they have done others of the like nature.
For, besides what is above mentioned,
I would gladly know how from the words they can be certainly resolved,
that these words "`Do this`" must be understood to the clergy, take,
bless and break this bread, and give it to others, but to the laity only, take and eat,
but do not bless, etc.

Obj.
If it be said, that the clergy were only present:

Answ.
Then will not that open a door for the Popish argument
against the administration of the cup to the people?
Or may not another from thence as easily infer that
only the clergy ought to partake of this ceremony,
because they were only those present, to whom it was said,
"`Do this?`" But if this "`Do this`" be extended to all,
how comes it all have not liberty to obey it in both blessing, breaking,
and distributing, as well as taking and eating?
Besides all these,
even the Calvinian Protestants of Great Britain could never
yet accord among themselves about the manner of taking it,
whether sitting, standing, or kneeling; whether it should be given to the sick,
and those that are ready to die, or not.
Which controversies, though they may be esteemed of small moment,
yet have greatly contributed, with other things,
to be the occasion not only of much contention, but also of bloodshed and devastation,
so that in this last respect the Prelatic Calvinists have
termed the Presbyterians schismatical and pertinacious,
and they them again superstitious, idolatrous, and Papistical.
Who then, that will open their eyes,
but may see that the devil hath stirred up this contention and zeal,
to busy men about things of small moment, that greater matters may be neglected,
while he keeps them in such ado about this ceremony;
while they lay aside others of the like nature, as positively commanded,
and as punctually practised,
and from the observation of which half so many difficulties will not follow?

// lint-disable invalid-characters "§"
§VIII.
How then?
Have we not reason, not finding the nature of this practice to be obligatory upon us,
more than those others which our adversaries have laid aside,
to avoid all this confusion, since those that use it can never agree,
neither concerning the nature, efficacy, nor manner of doing it?
And this proceeds, because they take it not plainly, as it lies in the Scripture,
but have so much mixed in their own inventions.
For would they take it as it lies, it would import no more,
than that Jesus Christ at that time did thereby signify unto them,
that his body and blood was to be offered for them, and desired them,
that whensoever they did eat or drink, they might do it in remembrance of him,
or with a regard to him, whose blood was shed for them.
Now that the primitive Church, gathered immediately after his ascension,
did so understand it, doth appear from their use and practice,
if we admit those places of the Acts, where breaking of bread is spoken of,
to have relation hereto, which as our adversaries do, so we shall willingly agree to.
As first (Acts 2:42), "`And they continued steadfastly in the apostles`' doctrine,
and fellowship, and in breaking of bread,`" etc. This cannot be understood of any other,
than of their ordinary eating; for as nothing else appears from the text,
so the context makes it plain; for they had all things in common:
and therefore it is said (v. 46),
"`And they continuing daily with one accord in the Temple,
and breaking bread from house to house,
did eat their meat with gladness and singleness of heart.`" Who will not willfully
close their eyes may see here that the breaking being joined with their eating,
shows that nothing else is here expressed, but that having all things in common,
and so continuing together, they also did break their bread and eat their meat together.
In doing whereof I shall not doubt but they remembered the Lord, to follow whom they had,
with so much zeal and resignation, betaken themselves.
This is further manifest from Acts 6. For the apostles,
having the care and distribution of that money which the
believers having sold their possessions gave unto them,
finding themselves overcharged with that burden,
appointed deacons for that business,
that they might give themselves continually to prayer and to the ministry of the Word;
not leaving that to serve tables.
This cannot be meant of any sacramental eating, or religious act of worship;
seeing our adversaries make the distributing of that the proper act of ministers,
not of deacons, and yet there can be no reason alleged, that breaking of bread,
which they are said to have continued in, and to have done from house to house,
was other than those tables that the apostles served; but here gave over,
as finding themselves overcharged with it:
now as the increase of the disciples did incapacitate
the apostles any more to manage this,
so it would seem their further increase and dispersing in divers places
hindered the continuance of that practice of having things in common.
But notwithstanding, so far at least to remember or continue that ancient community,
they did at certain times come together and break bread together.
Hence it is said (Acts 20:7) that Paul coming to Troas,
"`and upon the first day of the week, when the disciples came together to break bread,
Paul preached unto them, ready to depart on the morrow,
and continued his speech until midnight.`" Here is
no mention made of any sacramental eating;
but only that Paul took occasion from their being together to preach unto them.
And it seems it was a supper they intended (not a morning bit of bread and sup of wine),
else it`'s not very probable that Paul would from the morning have preached until midnight.
But the 11th verse puts the matter out of dispute, which is thus,
"`When he therefore was come up again, and had broken bread and eaten,
and talked a long while, even till break of day,
so he departed.`" This shows that the breaking of bread was deferred till that time:
for those words,
"`and when he had broken bread and eaten,`" do show that it
had a relation to the breaking of bread aforementioned,
and that was the time he did it.
Secondly, these words joined together, "`and when he had broken bread and eaten,
and talked,`" show it was no religious act of worship but only an eating for bodily refreshment,
for which the Christians used to meet together some time,
and doing it in God`'s fear and singleness of heart,
doth notwithstanding difference it from the eating or feasting of profane persons,
and this by some is called a "`love-feast,`" or a being together,
not merely to feed their bellies, or for outward ends,
but to take thence occasion to eat and drink
together in the dread and presence of the Lord,
as his people; which custom we shall not condemn;
but let it be observed that in all the Acts there
is no other nor further mention of this matter.
But if that ceremony had been some solemn sacrifice, as some will have it,
or such a special sacrament as others plead it to be, it is strange that that history,
that in many lesser things gives a particular account of the Christians`' behaviour,
should have been so silent in the matter.
Only we find that they used sometimes to meet together to break bread, and eat.
Now, as the primitive Christians began by degrees to depart
from that primitive purity and simplicity,
so also to accumulate superstitious traditions,
and vitiate the innocent practices of their predecessors,
by the intermixing either of Jewish or heathenish rites; so also in the use of this,
very early abuses began to creep in among Christians,
so that it was needful for the apostle Paul to reform them, and reprove them therefore,
as he doth at large (1 Cor. 11), from verse 17 to the end,
which place we shall particularly examine,
because our adversaries lay the chief stress of their matter upon it,
and we shall see whether it will infer any more, than we have above granted.
First,
because they were apt to use that practice in a superstitious
mind beyond the true use of it,
as to make of it some mystical supper of the Lord,
he tells them (v. 20) that their "`coming together into one place,
is not to eat the Lord`'s supper,`" he saith not, this is not the right manner to eat; but,
because the Supper of the Lord is spiritual, and a mystery.
Secondly, he blames them, in that they come together for the worse,
and not for the better, the reason he gives of this is (v. 21), "`For in eating,
every one hath taken before his own supper; and one is hungry,
and another is drunken.`" Here it is plain, that the apostle condemns them for that,
because this custom of supping in general was used
among Christians to increase their love,
and as a memorial of Christ`'s supping with the disciples,
that they should have so vitiated it, to eat it apart, and to come full,
who had abundance; and hungry, who had little at home.
Whereby the very use and end of this practice is lost and perverted,
and therefore he blames them, that they do not either eat this in common at home,
or reserve their eating, till they come all together to the public assembly:
this appears plainly by the following (v. 22):
"`Have ye not houses to eat and drink in?
Or despise ye the church of God,
and shame them that have not?`" Where he blames them for their irregular practice herein,
in that they despised to eat orderly, or reserve their eating to the public assembly,
and so shaming such as not having houses nor fullness
at home came to partake of the common table,
who, being hungry,
thereby were ashamed when they observed others come thither full and drunken.
Those that without prejudice will look to the place will
see this must have been the case among the Corinthians;
for supposing the use of this to have been then, as now used either by Papists,
Lutherans, or Calvinists, it is hard making sense of the apostle`'s words,
or indeed to conceive what was the abuse the Corinthians committed in this thing.
Having thus observed what the apostle said above,
because this custom of eating and drinking together some time had its
rise from Christ`'s act with the apostles the night he was betrayed,
therefore the apostle proceeds (v. 23) to give them an account of that.
"`For I have received of the Lord that which also I delivered unto you,
that the Lord Jesus, the same night in which he was betrayed,
took bread,`" etc. Those that understand the difference
betwixt a narration of a thing and a command,
cannot but see, if they will, that there is no command in this place,
but only an account of matter of fact; he saith not, I received of the Lord, that,
as he took bread, so I should command it to you to do so also,
there is nothing like this in the place; yea on the contrary (v. 25),
where he repeats Christ`'s imperative words to his apostles,
he placeth them so as they import no command: "`this do ye, as oft as ye drink it,
in remembrance of me.`" And then he adds,
"`For as often as ye eat this bread and drink this cup,
ye do show the Lord`'s death till he come.`" But these words,
"`as often,`" import no more a command than to say, "`as often as thou goest to Rome,
see the Capitol,`" will infer a command to me, to go thither.

Obj.
But whereas they urge the last words,
"`ye show forth the Lord`'s death till he come,`" insinuating,
that this imports a necessary continuance of that ceremony,
until Christ come at the end of the world to judgment;

Answ.
I answer, they take two of the chief parts of the controversy here for granted,
without proof.
First, that "`as often`" imports a command, the contrary whereof is shown,
neither will they ever be able to prove it.
Secondly, that this coming is understood of Christ`'s last outward coming,
and not of his inward and spiritual: that remains to be proven,
whereas the apostle might well understand it of his inward coming and appearance,
which perhaps some of those carnal Corinthians, that used to come drunken together,
had not yet known; and others, being weak among them,
and inclinable to dote upon outwards, this might have been indulged to them for a season,
and even used by those who knew Christ`'s appearance in Spirit (as other things were,
of which we shall speak hereafter), especially by the apostle,
who became weak to the weak, and all to all, that he might save some.
Now those weak and carnal Corinthians might be permitted the use of this,
to show forth or remember Christ`'s death, till he came to arise in them;
for though such need those outward things, to put them in mind of Christ`'s death;
yet such as are dead with Christ, and not only dead with Christ, but buried,
and also arisen with him, need not such signs to remember him,
and to such therefore the apostle saith (Col. 3:1), "`If ye then be risen with Christ,
seek those things which are above, where Christ sitteth on the right hand of God`":
but bread and wine are not these things that are above, but are things of the earth.
But that this whole matter was a mere act of indulgence and condescension
of the apostle Paul to the weak and carnal Corinthians,
appears yet more by the Syriac^
footnote:[And likewise the other Oriental versions, as the Arabic and Ethiopic,
have it the same way.]
copy, which (v. 17), in his entering upon this matter, hath it thus: "`In that,
concerning which I am about to command you (or instruct you), I commend you not,
because ye have not gone forward,
but are descended unto that which is less (or of less consequence).`" Clearly importing,
that the apostle was grieved that such was their condition,
that he was forced to give them instructions concerning those outward things,
and doting upon which they show they were not gone forward in the life of Christianity,
but rather sticking in beggarly elements.
And therefore (v. 20) the same version hath it thus, "`when then ye meet together,
ye do not do it, as it is just ye should do in the day of the Lord,
ye eat and drink.`" Therefore showing to them,
that to meet together to eat and drink outward bread and wine,
was not the labor and work of that day of the Lord;
but since our adversaries are so zealous for this ceremony,
because used by the church of Corinth (though, with how little ground is already shown),
how come they to pass over far more positive commands of the apostles,
as matters of no moment?
As first (Acts 15:29), where the apostles peremptorily command the Gentiles, as that,
which was the mind of the Holy Ghost, "`To abstain from things strangled,
and from blood.`" And James 5:14, where it is expressly commanded,
"`that the sick be anointed with oil in the Name of the Lord.`"

Obj.
If they say, these were only temporary things, but not to continue.

Answ.
What have they more to show for this, there being no express repeal of them?

Obj.
If they say, the repeal is implied, because the apostle saith,
We ought not to be judged in meats and drinks.

Answ.
I admit the answer,
but how can it be evited from militating the same way against the other practice?
Surely not at all: nor can there be anything urged for the one more than for the other,
but custom and tradition.

Obj.
As for that of James, they say, there followed a miracle upon it, to wit,
the recovery of the sick, but this being ceased, so should the ceremony.

Answ.
Though this might many ways be answered, to wit,
that prayer then might as well be forborne,
to which also the saving of the sick is there ascribed, yet I shall accept of it,
because I judge indeed that ceremony is ceased, only methinks, since our adversaries,
and that rightly, think a ceremony ought to cease, where the virtue fails,
they ought by the same rule to forbear the laying on of hands,
in imitation of the apostles, since the gift of the Holy Ghost doth not follow upon it.

// lint-disable invalid-characters "§"
§IX. But since we find that several testimonies of Scripture do sufficiently
show that such external rites are no necessary part of the New Covenant dispensation,
therefore not needful now to continue,
however they were for a season practised of old, I shall instance some few of them,
whereby from the nature of the thing, as well as those testimonies, it may appear,
that the ceremony of bread and wine is ceased, as well as those other things,
confessed by our adversaries to be so.
The first is Rom. 14:17, "`For the kingdom of God is not meat and drink,
but righteousness and peace,
and joy in the Holy Ghost.`" Here the apostle evidently shows that the kingdom of God,
or Gospel of Christ, stands not in meats and drinks, and suchlike things,
but in righteousness, as by the context doth appear,
where he is speaking of the guilt and hazard of judging
one another about meats and drinks.
So then, if the kingdom of God stand not in them, nor the Gospel, nor work of Christ,
then the eating of outward bread and wine can be no necessary part of the Gospel worship,
nor any perpetual ordinance of it.
Another is yet more plain,
of the same apostle (Col. 2:16). The apostle throughout
this whole second chapter doth clearly plead for us,
and against the formality and superstition of our opposers:
for in the beginning he holds forth the great privileges which Christians have by Christ,
who are come indeed to the life of Christianity, and therefore he desires them (v. 6),
"`As they have received Christ, so to walk in him; and to beware,
lest they be spoiled through philosophy and vain deceit,
after the rudiments or elements of the world,
because that in Christ whom they have received, is all fullness.
And that they are circumcised with the circumcision made without hands,
which he calls the circumcision of Christ,
and being buried with him by baptism are also arisen with him through the faith
of the operation of God.`" Here also they did partake of the true baptism of Christ,
and being such as are arisen with him,
let us see whether he thinks it needful they should make use of such meat and drink,
as bread and wine, to put them in remembrance of Christ`'s death,
or whether they ought to be judged, that they did it not (v. 16),
"`Let no man therefore judge you in meat or in drink.`"
Is not bread and wine meat and drink?
But why?
"`Which are a shadow of things to come: but the body is of Christ.`" Then,
since our adversaries confess that their bread and wine is a sign or shadow, therefore,
according to the apostle`'s doctrine, we ought not to be judged in the observation of it.
But is it not fit for those that are dead with Christ to be subject to such ordinances?
See what he saith (v. 20), "`Wherefore,
if ye be dead with Christ from the rudiments of the world, why,
as though living in the world, are ye subject to ordinances?
(Touch not, taste not, handle not:
which all are to perish with the using) after the commandments and doctrines of men`":
what can be more plain?
If this serve not to take away the absolute necessity of the use of bread and wine,
what can it serve to take away?
Sure I am, the reason here given is applicable to them,
which all do perish with the using, since bread and wine perish with the using,
as much as other things.
But further,
if the use of water and bread and wine were that
wherein the very seals of the New Covenant stood,
and did pertain to the chief sacraments of the Gospel
and evangelical ordinances (so called),
then would not the Gospel differ from the Law, or be preferable to it?
Whereas the apostle shows the difference (Heb. 9:10),
in that such kind of observations of the Jews were as a sign of the Gospel,
for that this "`stood only in meats and drinks, and divers washings.`" And now,
if the Gospel worship and service stand in the same, where is the difference?

Obj.
If it be said, These under the Gospel have a spiritual signification.

Answ.
So had those under the Law; God was the author of those,
as well as Christ is pretended to be the author of these.
But doth not this contending for the use of water, bread and wine,
as necessary parts of Gospel worship, destroy the nature of it,
as if the Gospel were a dispensation of shadows, and not of the Substance?
whereas the apostle, in that of the Colossians above mentioned,
argues against the use of these things,
as needful to those that are dead and arisen with Christ, because they are but shadows;
and since, through the whole Epistle to the Hebrews he argues with the Jews,
to wean them from their^
footnote:[Later editors insert "`old`" here.]
worship, for this reason, because it was typical and figurative.
Is it agreeable to right reason to bring them to another of the same nature?
What ground from Scripture or reason can our adversaries bring us,
to evince that one shadow or figure should yet they make
the figure of circumcision to point to water baptism,
and the Paschal lamb, to bread and wine.
But was it ever known, that one figure was the antitype of the other,
especially seeing Protestants make not these their antitypes
to have any more virtue or efficacy than the type had?
For since, as they say, and that truly, that their sacraments confer not Grace,
but that it is conferred according to the faith of the receiver, it will not be denied,
but the faithful among the Jews received also Grace in the use of their figurative worship.
And though Papists boast that their sacraments confer grace ex opere operato,
yet experience abundantly proveth the contrary.

// lint-disable invalid-characters "§"
§X. But supposing the use of water baptism and
bread and wine to have been in the primitive Church,
as was also that of "`abstaining from things strangled,
and from blood,`" the use of legal purification (Acts 21:23-25),
and anointing of the sick with oil, for the reasons and grounds before mentioned.
Yet it remains for our adversaries to show us how
they come by power or authority to administer them;
it cannot be from the letter of the Scripture,
else they behooved also to do those other things, which the letter declares also they did,
and which in the letter have as much foundation.
Then their power must be derived from the apostles, either mediately or immediately;
but we have shown before, in the tenth Proposition, that they have no mediate power,
because of the interruption made by the apostasy.
And for an immediate power or command by the Spirit of God, to administer these things,
none of our adversaries pretend to it.
We know that in this, as in other things,
they make a noise of the constant consent of the church, and of Christians in all ages;
but as tradition is not a sufficient ground for faith, so, in this matter especially,
it ought to have but small weight,
for that in this point of ceremonies and superstitious observations,
the apostasy began very early,
as may appear in the epistles of Paul to the Galatians and Colossians;
we have no ground to imitate them in those things,
whose entrance the apostle so much withstood, so heavily regretted,
and so sharply reproved.
But if we look to antiquity,
we find that in such kind of observances and traditions
they were very uncertain and changeable,
so that neither Protestants nor Papists do observe this ceremony, as they did,
both in that they gave it to young boys and to little children,
and for aught can be learned,
the use of this and infant baptism are of alike age,
though the one be laid aside both by Papists and Protestants, and the other, to wit,
baptism of infants, be stuck to:
and we have so much the less reason to lay weight upon antiquity, for that,
if we consider their profession of religion,
especially as to worship and the ceremonial part of it, we shall not find any church now,
// lint-disable invalid-characters "é"
whether Popish or Protestant, who differ not widely from them in many things, as Daillé,
in his treatise concerning the Use of the Fathers, well observeth and demonstrateth.
And why they should obtrude this upon us, because of the ancients`' practice,
which they themselves follow not, or why we may not reject this,
as well as they do other things no less zealously practised by the ancients,
no sufficient reason can be assigned.

I shall not nevertheless doubt, but many,
whose understandings have been clouded with these ceremonies,
have notwithstanding by the mercy of God had some secret sense of the mystery,
which they could not clearly understand, because it was sealed from them,
by their sticking to such outward things, and that, through that secret sense,
diving in their comprehensions, they ran themselves into these carnal apprehensions,
as imagining the substance of the bread was changed,
or that if the substance was not changed, yet the body was there,
etc. And indeed I am inclinable very favorably to judge of Calvin in this particular,
in that he deals so ingenuously,
to confess he neither comprehends it nor can express it in words,
but yet by a feeling experience can say, "`The Lord is spiritually present.`" Now,
as I doubt not but Calvin sometimes had a sense of his presence,
without the use of this ceremony,
so as the understanding given him of God made him justly reject
the false notions of transubstantiation and consubstantiation,
though he knew not what to establish instead of them,
if he had fully waited in the Light that makes all things manifest^
footnote:[Eph. 5:13.]
and had not labored in his own comprehension to settle upon that external ceremony,
by affixing the spiritual presence as chiefly or principally,
though not only (as he well knew by experience) there,
or especially to relate to it,
he might have further reached unto the knowledge of this mystery,
than many that went before him.

// lint-disable invalid-characters "§"
§XI. Lastly, if any now at this day, from a true tenderness of spirit,
and with real conscience towards God, did practice this ceremony in the same way, method,
and manner as did the primitive Christians, recorded in Scripture (which yet none,
that I know, now do) I should not doubt to affirm, but they might be indulged in it,
and the Lord might regard them, and for a season appear to them,
in the use of these things,
as many of us have known him to do to us in the time of our ignorance,
providing always they did not seek to obtrude them upon others, nor judge such,
as found themselves delivered, or that they do not pertinaciously adhere to them.
For we certainly know that the day is dawned,
in which God hath arisen and hath dismissed all those ceremonies and rites,
and is only to be worshipped in Spirit, and that he appears to them who wait upon him,
and that to seek God in these things is, with Mary at the sepulchre,
to seek the living among the dead, for we know that he is risen and revealed in Spirit,
leading his children out of these rudiments, that they may walk with him in his Light:
to whom be glory forever.
Amen.
