== THE FOURTEENTH PROPOSITION

[.chapter-subtitle--blurb]
Concerning the Power of the Civil Magistrate in Matters Purely Religious,
and Pertaining to the Conscience

[.heading-continuation-blurb]
Since God hath assumed to himself the power and dominion of the conscience,
who alone can rightly instruct and govern it,
therefore it is not lawful for any whosoever,
by virtue of any authority or principality they bear in the government of this world,
to force the consciences of others; and therefore all killing, banishing, fining,
imprisoning and other such things which are inflicted upon
men for the alone exercise of their conscience or difference
in worship or opinion proceedeth from the spirit of Cain,
the murderer, and is contrary to the Truth, providing always that no man,
under the pretence of conscience, prejudice his neighbour in his life or estate,
or do anything destructive to, or inconsistent with human society,
in which case the law is for the transgressor,
and justice is to be administered upon all without respect of persons.^
footnote:[Luke 9:55-56, Matt. 7:12-13,29; Tit. 3:10.]

// lint-disable invalid-characters "§"
§I. Liberty of conscience from the power of the civil
magistrate hath been of late years so largely and learnedly handled,
that I shall need to be but brief in it; yet it is to be lamented,
that few have walked answerably to this principle, each pleading it for themselves,
but scarce allowing it to others,
as hereafter I shall have occasion more at length to observe.

It will be fit in the first place, for clearing of mistakes,
to say something of the state of the controversy,
that what follows may be the more clearly understood.

By "`conscience`" then,
as in the explanation of the Fifth and Sixth Propositions I have observed,
is to be understood that persuasion of the mind,
which arises from the understanding`'s being possessed
with the belief of the truth or falsity of any thing,
which, though it may be false or evil upon the matter, yet,
if a man should go against his persuasion, or conscience, he would commit a sin,
because what a man doth contrary to his faith, though his faith be wrong,
is no ways acceptable to God; hence the apostle saith,
"`whatsoever is not of faith is sin`";
and "`he that doubteth is damned if he eat,`"^
footnote:[Rom. 14:23.]
though the thing might have been lawful to another;
and that this doubting to eat some kind of meats
(since all the creatures of God are good,
and for the use of man, if received with thanksgiving) might be a superstition,
or at least a weakness, which were better removed.
Hence _Ames De Cas. Cons._
saith, "`The conscience, although erring, doth evermore bind, so as that he sinneth,
who doth contrary to his conscience, because he doth contrary to the will of God,
although not materially and truly, yet formally and interpretatively.`"

So the question is, First,
Whether the civil magistrate hath power to force men in
things religious to do contrary to their conscience,
and if they will not to punish them in their goods, liberties, or lives?
this we hold in the negative.
But secondly,
as we would have the magistrate to avoid this extreme of encroaching upon men`'s consciences,
so on the other hand we are far from joining with,
or strengthening such libertines,
as would stretch the liberty of their consciences to the prejudice of their neighbours,
or to the ruin of human society.
We understand therefore by matters of conscience,
such as immediately relate betwixt God and man,
or men and men that are under the same persuasion,
as to meet together and worship God in that way which
they judge is most acceptable unto him,
and not to encroach upon or seek to force their neighbours otherwise
than by reason or such other means as Christ and his apostles used,
viz. preaching and instructing such as will hear and receive it, but not at all for men,
under the notion of conscience,
to do anything contrary to the moral and perpetual
statutes generally acknowledged by all Christians:
in which case the magistrate may very lawfully use his authority, as on those who,
under a pretence of conscience, make it a principle to kill and destroy all the wicked,
_id est,_ all that differ from them, that they, to wit, the saints, may rule,
and that therefore seek to make all things common and would
force their neighbours to share their estates with them,
// lint-disable invalid-characters "ü"
and many such wild notions, as is reported of the Anabaptists of Münster,
which evidently appears to proceed from pride and covetousness,
and not from purity or conscience,
and therefore I have sufficiently guarded against that in the latter part of the proposition.
But the liberty we lay claim to is such as the primitive
Church justly sought under the heathen emperors,
to wit, for men of sobriety, honesty,
and a peaceable conversation to enjoy the liberty and exercise
of their conscience towards God and among themselves,
and to admit among them such as, by their persuasion and influence,
come to be convinced of the same Truth with them,
without being therefore molested by the civil magistrate.
Thirdly,
though we would not have men hurt in their temporals nor robbed of their privileges
as men and members of the commonwealth because of their inward persuasion,
yet we are far from judging that in the Church of God there should not be censures
exercised against such as fall into error as well as such as commit open evils;
and therefore we believe it may be very lawful for a Christian church,
if she find any of her members fall into any error,
after due admonitions and instructions, according to Gospel order,
if she find them pertinacious,
to cut them off from her fellowship by the _sword of the Spirit_
and denude them of these privileges which they had as fellow-members,
but not to cut them off from the world by the temporal sword,
or rob them of their common privileges as men,
seeing they enjoy not these as Christians or under such a fellowship, but as men,
and members of the creation.
Hence Chrysostom saith well __(de Anath.),__
"`We must condemn and reprove the evil doctrines that proceed from heretics;
but spare the men and pray for their salvation.`"

[.small-break]
'''

// lint-disable invalid-characters "§"
§II. But that no man,
by virtue of any power or principality he hath in the government of this world,
hath power over the consciences of men, is apparent,
because the conscience of man is the seat and throne of God in him,
of which God is the alone proper and infallible Judge, who, by his Power and Spirit,
can alone rectify the mistakes of conscience,
and therefore hath reserved to himself the power of punishing the errors thereof,
as he seeth meet.
Now for the magistrate to assume this,
is to take upon him to meddle with things not within the compass of his jurisdiction,
for if this were within the compass of his jurisdiction,
he should be the proper judge in these things, and also it were needful to him,
as an essential qualification of his being a magistrate, to be capable to judge in them.
But that the magistrate, as a magistrate, is neither proper judge in these cases,
nor yet that the capacity so to be is requisite in him, as a magistrate,
our adversaries cannot deny, or else they must say,
that all the heathen magistrates were either no lawful magistrates,
as wanting something essential to magistracy,
and this were contrary to the express doctrine of the apostle (Rom. 13), or else,
which is more absurd,
that those heathen magistrates were proper judges in matters of conscience among Christians.
As for that evasion,
that the magistrates ought to punish according to the church censure and determination,
which is indeed no less, than to make the magistrate the church`'s hangman,
we shall have occasion to speak of it hereafter.
But if the chief members of the church, though ordained to inform, instruct, and reprove,
are not to have dominion over the faith nor consciences of the faithful,
as the apostle expressly affirms (2 Cor. 1:24),
then far less ought they to usurp this dominion,
or stir up the magistrate to persecute and murder those who cannot yield to them therein.

Secondly,
this pretended power of the magistrate is both contrary
unto and inconsistent with the nature of the Gospel,
which is a thing altogether extrinsic from the rule and government of political states,
as Christ expressly signified, saying his Kingdom was not of this world,
and if the propagating of the Gospel had had any necessary relation thereunto,
then Christ had not said so; but he abundantly hath shown by his example,
whom we are chiefly to imitate in matters of that nature,
that it is by persuasion and the Power of God, not by whips, imprisonments, banishments,
and murderings that the Gospel is to be propagated,
and that those that are the propagators of it are often to suffer by the wicked,
but never to cause the wicked to suffer.
When he sends forth his disciples,
he tells them he sends them forth as "`lambs among wolves,`"^
footnote:[Matt. 10:16.]
to be willing to be devoured, not to devour; he tells them of their being whipped,
imprisoned, and killed for their conscience, but never that they shall either whip,
imprison, or kill; and indeed, if Christians must be as _lambs,_
it is not the nature of lambs to destroy or devour any.

It serves nothing to allege that in Christ`'s and
his apostles`' times the magistrates were heathens,
and therefore Christ and his apostles, not being magistrates,
nor yet any of the believers, could not exercise the power;
because it cannot be denied but Christ, being the Son of God,
had a true right to all kingdoms and was righteous heir of the earth.^
footnote:[Matt. 28:18.]
Next, as to his power, it cannot be denied but he could, if he had seen meet,
have called for legions of angels to defend him,
and have forced the princes and potentates of the
earth to be subject unto him (Matt. 26:53),
so that it was only because it was contrary to the nature of Christ`'s Gospel
and ministry to use any force or violence in the gathering of souls to him.
This he abundantly expressed in his reproof to the two sons of Zebedee,
who would have been calling for fire from heaven
to burn those that refused to receive Christ.
It is not to be doubted,
but this was as great a crime as now to be in an
error concerning the faith and doctrine of Christ.
That there was not power wanting to have punished
those refusers of Christ cannot be doubted;
for they that could do other miracles might have done this also;
and moreover they wanted not the precedent of a holy man under the law, as did Elias;
yet we see what Christ saith to them: "`Ye know not what spirit ye are of`" (Luke 9:55),
"`for the Son of Man is not come to destroy men`'s lives,
but to save them.`" Here Christ shows that such kind of zeal was no ways approved of him,
and such as think to make way for Christ or his Gospel by
this means do not understand what spirit they are of.
But if it was not lawful to call for fire from heaven
to destroy such as refused to receive Christ,
it is far less lawful to kindle fire upon earth to destroy
those that believe in Christ because they will not believe,
nor can believe, as the magistrates do, for conscience`' sake:
and if it was not lawful for the apostles,
who had so large a measure of the Spirit and were so little liable to mistake,
to force others to their judgment,
it can be far less lawful now for men that experience declareth,
and many of themselves confess, are fallible and often mistaken,
to kill and destroy all such as cannot (because otherwise persuaded
in their minds) judge and believe in matters of conscience,
just as they do.
And, if it was not according to the wisdom of Christ, who was and is King of kings,
by outward force to constrain others to believe him or receive him,
as being a thing inconsistent with the nature of his ministry and spiritual government;
do not they grossly offend him that will needs be wiser than he and think to
force men against their persuasion to conform to their doctrine and worship?
The word of the Lord saith, "`not by power and by might,
but by my Spirit saith the Lord`" (Zech. 4:6). But these say,
not by the Spirit of the Lord, but by might and carnal power.
The apostle saith plainly, "`we wrestle not with flesh and blood`";
and "`the weapons of our warfare are not carnal, but spiritual`";^
footnote:[2 Cor. 10:4.]^
footnote:[Later editors change "`spiritual`'`" to "`mighty through God,`' etc.`"]
but these men will needs wrestle with flesh and blood
when they cannot prevail with the Spirit and the understanding,
and not having spiritual weapons go about with carnal
weapons to establish Christ`'s kingdom,
which they can never do; and therefore, when the matter is well sifted,
it is found to be more out of love to self, and from a principle of pride in man,
to have all others to bow to him, than from the love of God.
Christ indeed takes another method, for he saith, "`he will make his people^
footnote:[Later editors change "`He shall make his people`" to "`His people shall be.`"]
a willing people in the day of his power,`"^
footnote:[Ps. 110:3]
but these men labor against men`'s wills and consciences, not by Christ`'s power,
but by the outward sword, to make men the people of Christ, which they can never do,
as shall hereafter be shown.

But thirdly, Christ fully and plainly declareth to us his sense in this matter,
in the parable of the tares (Matt. 13),
of which we have himself the interpreter (vv. 38-41),
where he expounds them to be the "`children of the wicked one,`"
and yet he will not have the servants to meddle with them,
lest they pull up the wheat therewith.
Now it cannot be denied, but heretics are here included,
but these servants saw the tares; and had a certain discerning of them,
yet Christ would not they should meddle, lest they should hurt the wheat,
thereby intimating, that that capacity in man, to be mistaken,
ought to be a bridle upon him, to make him wary in such matters; and therefore,
to prevent this hurt, he gives a positive prohibition, "`But he said,
'`Nay,`'`" (v. 29). So that they that will notwithstanding be pulling up that,
which they judge is tares,
do openly declare that they make no bones to break the commands of Christ.
Miserable is that evasion, which some of our adversaries use here,
in alleging these tares are meant of _hypocrites,_ and not of _heretics!_
But how to evince that, seeing heretics, as well as hypocrites,
are children of the wicked one, they have not anything but their own bare affirmation,
which is therefore justly rejected.

_Obj._
If they say, because hypocrites cannot be discerned, but so may not heretics.

_Answ._
This is both false, and a begging of the question.
For those that have a spiritual discerning can discern both hypocrites and heretics;
and those that want it cannot certainly discern either:
seeing the question will arise, whether that is a heresy,
which the magistrate saith is so?
And seeing it is both possible, and confessed by all, to have often fallen out,
that some magistrates have judged that heresy, which was not;
punishing men accordingly for Truth, instead of error:
there can no argument be drawn from the obviousness or evidence of heresy,
unless we should conclude heresy could never be mistaken for Truth, nor Truth for heresy,
whereof experience shows daily the contrary, even among Christians.
But neither is this shift applicable to this place,
for the servants did discern the tares, and yet were liable to hurt the wheat,
if they had offered to pull them up.

[.small-break]
'''

// lint-disable invalid-characters "§"
§III.
_Obj._ But they object against this liberty of conscience, Duet. 13:5,
where false prophets are appointed to be put to death,
and accordingly they give example thereof.

_Answ._
The case no way holds parallel; those particular commands to the Jews,
and practices following upon them, are not a rule for Christians, else we might,
by the same rule, say it were lawful for us to borrow from our neighbours their goods,
and so carry them away, because the Jews did so, by God`'s command;
or that it is lawful for Christians to invade their neighbours`' kingdoms,
and cut them all off, without mercy, because the Jews did so to the Canaanites,
by the command of God.

_Obj._
If they urge that these commands ought to stand, except they be repealed in the Gospel.

_Answ._
I say, these precepts and practices of Christ and his apostles mentioned,
are a sufficient repeal; for if we should plead, that every command, given to the Jews,
is binding upon us, except there be a particular repeal,
then would it follow that because it was lawful for the Jews, if any man killed one,
for the nearest kindred presently to kill the murderer, without any order of law,
it were lawful for us to do so also.
And doth not this command of Duet. 13:9, openly order him,
who is enticed by another to forsake the Lord, though it were his brother, his son,
his daughter, or his wife, presently to kill him, or her?
"`Thou shalt surely kill him, thy hand shall be first upon him,
to put him to death.`" If this command were to be followed,
there needed neither inquisition, nor magistrate, to do the business; and yet,
there is no reason why they should shuffle by this part, and not the other;
yea to argue this way from the practice among the Jews, were to overturn the very Gospel,
and to set up again the carnal ordinances among the Jews,
to pull down the spiritual ones of the Gospel.
Indeed we can far better argue from the analogy betwixt
the figurative and carnal state of the Jews,
and the real and spiritual one, under the Gospel.
That, as Moses delivered the Jews out of outward Egypt, by an outward force,
and established them in an outward kingdom, by destroying their outward enemies for them;
so Christ, not by overcoming outwardly, and killing others,
but by suffering and being killed, doth deliver his chosen ones, the inward Jews,
out of mystical Egypt, destroying their spiritual enemies before them,
and establishing among them his spiritual Kingdom, which is not of this world.
And as such as departed from the fellowship of outward
Israel were to be cut off by the outward sword,
so those that depart from the inward Israel,
are to be cut off by the sword of the Spirit; for it answers very well,
that as the Jews were to cut off their enemies outwardly,
to establish their kingdom and outward worship, so they were to uphold it the same way.
But, as the Kingdom and Gospel of Christ was not to be
established nor propagated by cutting off,
or destroying the Gentiles, but by persuading them,
so neither is it to be upheld otherwise.

_Obj._
But secondly, they urge Rom. 13,
where the magistrate is said not to bear the sword in vain,
because he is the minister of God, to execute wrath upon such as do evil.
But heresy, say they, is evil.
Ergo.

_Answ._
But so is hypocrisy also, yet they confess he ought not to punish that.
Therefore this must be understood of moral evils,
relative of affairs betwixt man and man, not of matters of judgment or worship,
or else what great absurdities would follow,
considering that Paul wrote here to the Church of Rome,
who was under the government of Nero, an impious heathen and persecutor of the Church?
Now if a power to punish, in point of heresy, be here included,
it will necessarily follow that Nero had this power, yea and that he had it of God;
for because the power was of God, therefore the apostle urges their obedience.
But can there be anything more absurd, than to say,
that Nero had power to judge in such cases?
Surely if Christian magistrates be not to punish for hypocrisy,
because they cannot outwardly discern it, far less could Nero punish anybody for heresy,
which he was incapable to discern.
And, if Nero had not power to judge or punish in point of heresy,
then nothing can be urged from this place:
since all that`'s said here is spoken as applicable to Nero
with a particular relation to whom it was written.
And, if Nero had such a power, surely he was to exercise it,
according to his judgment and conscience, and in doing thereof he was not to be blamed;
which is enough to justify him in his persecuting of the apostles,
and murdering the Christians.

_Obj._
Thirdly they object that saying of the apostle to the Galatians 5:12,
"`I would they were even cut off, which trouble you.`"

_Answ._
But how this imports any more than a cutting off from the Church, is not,
nor can be shown.
Beza, upon the place, saith, "`We cannot understand that otherwise,
than of excommunication: such as was that of the incestuous Corinthian.
And indeed, it is madness to suppose it otherwise;
for Paul would not have these cut off otherwise than he did Hymenaeus and Philetus,
who were blasphemers; which was by giving them over to Satan,
not by cutting off their heads.`"

The same way may be answered that other argument drawn from Rev. 2:20,
where the Church of Thyatira is reproved for suffering the woman Jezebel.
Which can be no otherways understood, than that they did not excommunicate her,
or cut her off by a Church censure: for as to corporal punishment,
it is known that at that time the Christians had not power to punish heretics so,
if they had a mind to it.

_Obj._
Fourthly,
they allege that heresies are numbered among the
works of the flesh (Gal. 5:20). Ergo,
etc.

_Answ._
That magistrates have power to punish all the works of the flesh, is denied,
and not yet proved.
Every evil is a work of the flesh,
but every evil comes not under the magistrate`'s cognizance.
Is not hypocrisy a work of the flesh,
which our adversaries confess the magistrates ought not to punish?
yea is not hatred and envy, there mentioned, as the works of the flesh?
and yet the magistrate cannot punish them, as they are in themselves,
until they exert themselves in other acts, which come under his power.
But so long as heresy doth not exert itself in any act destructive to human society,
or suchlike things,
but is kept within the sphere of those duties of doctrine
or worship which stand betwixt a man and God,
they no ways come under the magistrate`'s power.

[.small-break]
'''

// lint-disable invalid-characters "§"
§IV. But secondly,
this forcing of men`'s consciences is contrary to sound reason,
and the very law of nature.
For man`'s understanding cannot be forced by all the
bodily sufferings another man can inflict upon him,
especially in matters spiritual and supernatural:
it is arguments and evident demonstrations of reason,
together with the power of God reaching the heart,
that can change a man`'s mind from one opinion to another, and not knocks and blows,
and suchlike things, which may well destroy the body but never can inform the soul,
which is a free agent, and must either accept or reject matters of opinion,
as they are borne in upon it by something proportional to its own nature.
To seek to force minds in any other manner, is to deal with men as if they were brutes,
void of understanding, and at last is but to lose one`'s labor, and, as the proverb is,
"`to seek to wash the Black-Moor white.`" By that course indeed men may be made hypocrites,
but can never be made Christians;
and surely the products of such compulsion (even where the end is obtained, to wit,
an outward assent, or conformity,
whether in doctrine or worship) can be no ways acceptable to God,
who desireth not any sacrifice except that which cometh thoroughly from the heart,
and will have no constrained ones:
so that men so constrained are so far from being members of the Church,
that they are made ten times more the servants of Satan than before,
in that to their error is added hypocrisy, the worst of evils in matters of religion,
and that which above all things the Lord`'s soul most abhors.

_Obj._
But if it be said,
their error notwithstanding is thereby suppressed and the scandal removed.

_Answ._
I answer, besides that this is a method no ways allowed by Christ, as is above proved,
surely the Church can be no ways bettered by the accession of hypocrites,
but greatly corrupted and endangered, for open heresies men may be aware of,
and shun such as profess them, when they are separated from the Church by her censures;
but secret hypocrites may putrefy the body, and leaven it, ere men be aware.
And if the dissenters prove resolute,
and suffer boldly for the opinions they esteem right,
experience showeth that such sufferings often tend to the commendation of the sufferers,
but never of the persecutors: for such suffering ordinarily breeds compassion,
and begets a curiosity in others,
to enquire the more diligently into the things for
which they see men suffer so great losses so boldly,
and is also able to beget an opinion that it is for some good they do so suffer,
it being no ways probable, that men will venture all merely to acquire fame,
which may as well be urged to detract from the reputation of all the martyrs,
unless some better arguments be brought against it than a halter or a faggot.
But supposing this principle,
that the magistrate hath power to force the consciences of his subjects,
and to punish them if they will not comply:
very great inconveniences and absurdities will follow,
and even such as are inconsistent with the nature of the Christian religion.

For first it will naturally follow that the magistrate ought to do it,
and sinneth by omission of his duty if he do it not.
Will it not then hence be inferred that Christ was defective to his Church, who,
having power to force men, and to call for legions of angels so to do,
did notwithstanding not exert that power, but left his Church to the mercy of the wicked,
without so necessary a bulwark?

Secondly,
seeing every magistrate is to exercise his power
according to the best understanding he hath,
being obliged so to do for the promoting of what
he in conscience is persuaded to be Truth,
will not this justify all the heathen emperors in their persecutions against Christians?
Will not this justify the Spanish inquisition,
which yet is odious not only to Protestants, but to many moderate Papists?
How can Protestants in reason condemn the Papists for persecuting them,
seeing they do but exercise a lawful power, according to their conscience,
and best understanding, and do no more to them,
than the sufferers profess they would do to them, if they were in the like capacity?
Which takes away all ground of commiseration from the sufferers,
whereas that was the ground that gained, of old, reputation to the Christians, that they,
being innocent, suffered, who neither had, nor by principle could, hurt any.
But there is little reason to pity one,
that is but dealt by according as he would deal with others.
For to say, they have not reason to persecute us, because they are in the wrong,
and we in the right, is but miserably to beg the question.
Doth not this doctrine strengthen the hands of the persecutors everywhere,
and that rationally, from a principle of self-preservation?
For who can blame me for destroying him that I know
waits but for an occasion to destroy me,
if he could?
Yea this makes all suffering for religion, which of old was the glory of Christians,
to be but of pure necessity;
whereby they are not led as lambs to the slaughter as was the Captain of their Salvation,
but rather as wolves caught in the snare,
who only bite not again because they are not able, but, could they get force,
would be as ready to lead those the same way, that lead them.
Where is here the faith and patience of the saints?
For indeed it is but a small glory to make a virtue of necessity,
and suffer because I cannot help it.
Every thief and murderer is a martyr at that rate;
experience hath abundantly proved this in these last centuries.
For however each party talk of passively obeying the magistrate in such cases,
and that the power resides in him, yet it is apparent,
that from this principle it naturally follows that any party, supposing themselves right,
should, so soon as they are able, endeavour, at any rate, to get uppermost,
that they might bring under those of another opinion,
and force the magistrate to uphold their way, to the ruin of all others.

What engine the Pope of Rome used to make, of his pretended power in this thing,
upon any pretence of dislike to any prince or state, even for very small heresies,
in their own account, to depose princes, and set up their subjects against them,
and give their dominions to other princes to serve his interest, they cannot be ignorant,
who have read the life of Hildebrand;
and how Protestants have vindicated the liberty of their consciences,
after this same manner, is apparent.
They suffered much in France, to the great increase and advantage of their party,
but how soon they found themselves considerable,
and had gotten some princes upon their side, they began to let the king know,
that they must either have the liberty of their consciences,
or else they would purchase it, not by suffering, but by fighting.
And the experience of other Protestant states shows that if Henry the fourth,
to please the Papists, had not quitted his religion, to get the crown the more peaceably,
and so the Protestants had prevailed with the sword,
they would as well have taught the Papists with the faggot, and led them to the stake;
so that this principle of persecution, on all hands,
is the ground of all those miseries and contentions:
for so long as any party is persuaded that it is both lawful for them, and their duty,
if in power, to destroy those that differ from them,
it naturally follows they ought to use all means possible to get that power,
whereby they may secure themselves in the ruin of their adversaries.
And that neither Papists nor Protestants judge it^
footnote:[Later editors change "`neither Papists nor
Protestants judge it`" to "`Papists judge it not.`"]
unlawful to compel the magistrate, if they be strong enough to do it, to effect this.
Experience shows it to be a known Popish principle,
that the Pope may depose an heretic prince,
and absolve the people from the oath of fidelity; and the Pope, as is above said,
hath done so to divers princes;
and this doctrine is defended by Bellarmine against Barclay.
The French refused Henry the fourth, till he quitted his religion.
And as for Protestants, many of them scruple not to affirm,
that wicked kings and magistrates may be deposed and killed;
yea our Scotch Presbyters are as positive in it as any Jesuits,
who would not admit this present Charles the second, though otherwise a Protestant,
prince, unless he would swear to renounce episcopacy, a matter of no great difference,
though contrary to his conscience.
Now how little proportion these things bear with the primitive
Christians and the religion propagated by Christ and his apostles,
needs no great demonstration; and it is observable,
that notwithstanding many other superstitions crept into the church very early,
yet this of persecution was so inconsistent with the nature of the Gospel,
and liberty of conscience, as we have asserted it,
such an innate and natural part of the Christian religion,
that almost all the Christian writers for the first
three hundred years earnestly contended for it,
condemning the contrary opinion.

[.small-break]
'''

// lint-disable invalid-characters "§"
§V. Thus Athanasius, "`It is the property of piety not to force, but to persuade,
in imitation of our Lord, who forced nobody,
but left it to the will of every one to follow him, etc. But the devil,
because he hath nothing of Truth,
uses knocks and axes to break up the doors of such as receive him.
But our Saviour is meek, teaching the Truth;
"`Whosoever will come after me,`' and '`whosoever will be my disciple,`' etc.,
but constraining none, coming to us, and knocking rather, and saying, '`My sister,
my spouse, open to me,`' etc. and entereth when he is opened to, and retires if they delay,
and will not open unto him, because it is not with swords, nor darts, nor soldiers,
nor armour, that Truth is to be declared, but with persuasion and counsel.`"^
footnote:[Athan. in _epist. ad solit. vit ag. ibid._]
And it is observable, that it was the impious Arians,
who first of all brought in this doctrine to persecute others, among Christians,
whose successors both Papists and Protestants are in this matter,
whom Athanasius thus reproveth further.
"`Where,`" saith he, "`have they learned to persecute?
Certainly they cannot say, they have learned it from the saints;
but this hath been given them, and taught them of the devil.
The Lord commanded indeed sometimes to flee, and the saints sometimes fled,
but to persecute is the invention and argument of the devil,
which he seeks against all.`"^
footnote:[Athan. _Apol. I de fuga sua, tom. 1._]
And after, he saith,
"`In so far as the Arians banish those that will not subscribe their decrees,
they show that they are contrary to Christians, and friends of the devil.`"

"`But now, O lamentable!`" saith Hilary, "`it is the suffrages of the earth,
that recommend the religion of God, and Christ is found naked of his virtue,
while ambition must give credit to his Name.
The Church reproves and fights by banishment and prisons,
and forceth herself to be believed, which once was believed,
because of the imprisonments and banishments herself suffered.
She, that once was consecrated by the terror of her persecutors,
depends now upon the dignity of those, that are in her communion.
She, that once was propagated by her banished priests, now banisheth the priests.
And she boasts now, that she is loved of the world, who could not have been Christ`'s,
if she had not been hated of the world.`"^
footnote:[Hil+++.+++, contra Aux.]

"`The Church,`" saith Jerome, "`was founded by shedding of blood, and by suffering,
and not in doing of hurt.
The Church increased by persecutions, and was crowned by martyrdom.`"^
footnote:[Jerome, _epist. 62 ad The._]

Ambrose, speaking of Auxentius, saith thus, "`whom he +++[+++viz., Auxentius]
could not deceive by discourse, he thinks ought to be killed by the sword,
making bloody laws with his mouth, writing them with his hands,
and imagining that an edict can command faith.`"^
footnote:[Ambrose, _epist. 32. tom. 3._]

And the same Ambrose saith, that "`going into France,
he would not communicate with those bishops,
that required that heretics should be put to death.^
footnote:[Ambrose, _epist. 27._]

The Emperor Marcian, who assembled the Council of Chalcedon, protests,
that he "`would not force, nor constrain anyone to subscribe the council of Chalcedon,
against his will.`"^
footnote:[Marcian, _epist. ad_ Archimand, _etc._ Mon. Eg. _in acta concil._
Chalced. _tom. 2. conc. gen._]

Hosius, Bishop of Cordua,
testifies that "`the emperor Constantine would not constrain any to be orthodox.`"^
footnote:[Hosius, _epist. ad_ Constit. _apud_ Ath _in epist. ad solit.
vit. tom. 1._]

Hilary saith further, that "`God teacheth, rather than exacteth, the knowledge of himself,
and authorizing his commandments by the miracles of his heavenly works,
he wills not that any should confess him with a forced will,
etc. He is the God of the whole universe, he needs not a forced obedience,
nor requires a constrained confession.`"^
footnote:[Hilary, _l.1. ad Const._]

"`Christ,`" saith Ambrose, "`sent his apostles to sow faith, not to constrain, but to teach;
not to exercise coercive power, but to extol the doctrine of humility.`"^
footnote:[Ambrose, _comm. in_ Luc. _l.7._]

Hence Cyprian, comparing the Old Covenant with the New, saith,
"`then were they put to death with the outward sword,
but now the proud and contumacious are cut off with the spiritual sword,
by being cast out of the Church`": and this answers very well that objection,
before observed, taken from the practice of the Jews under the law.^
footnote:[Cyprian, _epist. 62._]

"`See,`" saith Tertullian to the heathens,
"`if it be not to contribute to the renown of irreligion,
to seek to take away the liberty of religion, and to hinder men their choice of God,
that I may not be admitted to adore, whom I will, but must be constrained to serve him,
whom I will not.
There is none, nay not a man,
that desires to be adored by any against their will.`"^
footnote:[Tertullian, _Apolog. cap. 24._]
And again, "`It is a thing that easily appears to be unjust,
to constrain and force men to sacrifice against their wills; seeing,
to do the service of God, there is required a willing heart.`"^
footnote:[_Id+++.+++, Apolog. c. 28._]
And again, "`It is a human right, and natural power,
that every one worship what he esteems;
and one man`'s religion doth not profit nor hurt another.
Neither is it any piece of religion, to enforce religion,
which must be undertaken by consent, and not by violence,
seeing that the sacrifices themselves are not required,
but from a willing mind.`"^
footnote:[_Idem, ad Scapul. cap. 2._]

Now, how either Papists or Protestants
(that boast of antiquity) can get by these plain testimonies,
let any rational man judge.
And indeed I much question, if in any one point, owned by them and denied by us,
they can find all the old Fathers and writers so exactly unanimous.
Which shows how contrary all of them judged this to be to the nature of Christianity,
and that in the point of persecution lay no small part of the apostasy, which,
from little to more, came to that, that the Pope, upon every small discontent,
would excommunicate princes, absolve their subjects from obeying them,
and turn them in and out, at his pleasure.
Now, if Protestants do justly abhor these things among Papists,
is it not sad that they should do the like themselves?
A thing that at their first appearance, when they were in their primitive innocency,
they did not think on, as appears by that saying of Luther: "`Neither Pope, nor bishop,
nor any other man, hath power to oblige a Christian to one syllable,
except it be by his own consent.`"^
footnote:[Luther, _lib. de Captivit. Babylonica._]
And again, "`I call boldly to Christians,
that neither man nor angel can impose any law upon them, but so far as they will;
for we are free of all.`" And when he appeared at the diet of Spiers,
before the emperor, in a particular conference he had, before the Archbishop of Triers,
and Joachim elector of Brandenburgh,
when there seemed no possibility of agreeing with his opposers,
they asking him what remedy seemed to him most fit?
He answered, "`the counsel that Gamaliel proposed to the Jews,`" to wit,
that "`if this design was of God, it would stand, if not; it would vanish,`" which,
he said, "`ought to content the Pope`":^
footnote:[[.book-title]#History of Council of Trent.#]
he did not say, because he was in the right, he ought to be spared.
For this counsel supposeth that those that are tolerated may be wrong;
and yet how soon did the same Luther, ere he was well secure himself,
press the Elector of Saxony to banish poor Carlstadt, because he could not,
in all things, submit to his judgment;
and certainly it is not without ground reported that it
smote Luther to the heart (so that he needed to be comforted),
when he was informed, that Carlstadt, in his letter to his congregation,
styled himself "`a man banished for conscience,
by the procurement of Martin Luther.`" And since both the
Lutherans and Calvinists not admitting one another to worship,
in those respective dominions,
showeth how little better they are than either Papists or Arians in this particular.
And yet Calvin saith that "`the conscience is free from the power of all men.`"^
footnote:[Calvin. _Inst. c. 19 sect. 14._]
If so, why then did he cause Castellio to be banished, because he could not,
for conscience sake, believe as he did, that God had ordained men to be damned?
And Servetus to be burned, for denying the divinity of Christ,
if Calvin`'s report of him be to be credited, which opinion,
though indeed it was to be abominated, yet no less was Calvin`'s practice,
in causing him to be burned,
and afterwards defending that it was lawful to burn heretics,
by which he encouraged the Papists to lead his followers
the more confidently to the stake,
as having, for their warrant, the doctrine of their own sect-master,
which they omitted not frequently to twit them with,
and indeed it was to them unanswerable.
Hence, upon this occasion,
the judicious author of the [.book-title]#History of the Council of Trent# (in his fifth
book where giving an account of several Protestants that were burned for
their religion) well and wisely observeth it,
as "`a matter of astonishment,
that those of the new Reformation did offer to punish in the case of religion`":
and afterwards, taking notice that Calvin justifies the punishing of heretics, he adds,
"`But since the name of heresy may be more or less restricted, yea or diversely taken,
this doctrine may be likewise taken in divers senses, and may at one time hurt those,
whom at another time it may have benefited.`"

So that this doctrine of persecution cannot be maintained by Protestants,
without strengthening the hands of Popish inquisitors, and indeed, in the end,
lands in direct Popery.
Seeing,
if I may not profess and preach that religion which
I am persuaded in my own conscience is true,
it is to no purpose to search the Scriptures,
or to seek to choose my own faith by convictions thence derived,
since whatever I there observe, or am persuaded of,
I must either subject to the judgment of the magistrate and church of that place I am in,
or else resolve to remove, or die.
Yea doth not this heretical and anti-Christian doctrine both of Papists
and Protestants at last resolve into that cursed policy of Muhammad,
who prohibited all reason or discourse about religion,
as occasioning factions and divisions?
And indeed, those, that press persecution, and deny liberty of conscience,
do thereby show themselves more the disciples of Muhammad than of Christ,
and that they are no ways followers of the apostle`'s doctrine,
who desired the Thessalonians (1 Thess. 5:21) to "`prove all things,
and hold fast that which is good,`" and also saith, "`unto such as are otherwise minded,
God shall reveal it`" (Phil. 3:15),
not that by beatings and banishments it must be knocked into them.

[.small-break]
'''

// lint-disable invalid-characters "§"
§VI. Now the ground of persecution, as hath been above shown,
is an _unwillingness to suffer;_
for no man that will persecute another for his conscience would suffer for his own,
if he could avoid it, seeing his principle obliges him, if he had power,
by force to establish that, which he judges is the Truth, and so to force others to it.
Therefore I judge it meet, for the information of the nations,
briefly to add something in this place concerning the _nature of true Christian sufferings,_
whereunto a very faithful testimony hath been borne by God`'s witnesses,
which he hath raised up in this age,
beyond what hath been generally known or practised for these many generations,
yea since the apostasy took place.
Yet `'tis not my design here in any wise to derogate
from the sufferings of the Protestant martyrs,
whom I believe to have walked in faithfulness towards God,
according to the dispensation of Light in that day appearing,
and of which many were utter enemies to persecution, as by their testimonies against it,
might be made appear.

But the true, faithful, and Christian suffering is,
for men to profess what they are persuaded is right,
and so practise and perform their worship towards God,
as being their true right so to do,
and neither to do more in that because of outward encouragement from men,
nor any whit less, because of the fear of their laws and acts against it.
Thus for a Christian man to vindicate his just liberty,
with so much boldness and yet innocency, will, in due time, though through blood,
purchase peace, as this age has, in some measure, experienced,
and many are witnesses of it, which yet shall be more apparent to the world,
as Truth takes place in the earth.
But they greatly sin against this excellent rule, that, in time of persecution,
do not profess their own way, so much as they would, if it were other ways; and yet,
when they can get the magistrate upon their side,
not only stretch their own liberty to the utmost, but seek to establish the same,
by denying it to others.
But of this excellent patience and sufferings, the witnesses of God,
in scorn called Quakers, have given a manifest proof; for,
so soon as God revealed his Truth among them, without regard to all opposition,
or what they might meet with, they went up and down, as they were moved of the Lord,
preaching and propagating the Truth in marketplaces, highways, streets, public temples,
though daily beaten, whipped, bruised, haled, and imprisoned therefore.
And, when there was anywhere a church or assembly gathered,
they taught them to keep their meetings openly, and not to shut the door,
nor do it by stealth, that all might know it, and, who would, might enter: and,
as hereby all just occasion of fear of plotting against the government was fully removed,
so this their courage and faithfulness, in not giving over their meeting together,
(but more especially the presence and glory of God, manifested in the meeting,
being terrible to the consciences of the persecutors)
did so weary out the malice of their adversaries,
that oftentimes they were forced to leave their work undone.
For, when they came to break up a meeting,
they were forced to take every individual out by force,
they not being free to give up their liberty, by dissolving, at their command: and,
when they were haled out, unless they were kept forth by violence,
they presently returned peaceably to their place.
Yea when sometimes the magistrates have pulled down their meetinghouses,
they have met the next day, openly upon the rubbish,
and so by innocency kept their possession and ground, being properly their own,
and their right to meet and worship God not forfeited to any.
So that, when armed men have come to dissolve them, it was impossible for them to do it,
unless they had killed every one, for they stood so close together,
that no force could move anyone to stir, until violently pulled down: so that,
when the malice of their opposers stirred them to
take shovels and throw the rubbish upon them,
there they stood unmoved, being willing, if the Lord should so permit,
to have been there buried alive, witnessing for him.

As this patient, but yet courageous,
way of suffering made the persecutors`' work very heavy and wearisome unto them,
so the courage and patience of the sufferers using no resistance,
nor bringing any weapons to defend themselves,
nor seeking any ways revenge upon such occasions,
did secretly smite the hearts of the persecutors,
and made their chariot wheels go on heavily.
Thus after much and many kind of sufferings thus patiently borne,
which to rehearse would make a volume of itself,
which may in due time be published to the nations (for we have
them upon record) a kind of negative liberty has been obtained,
so that, at present, for the most part,
we meet together without disturbance from the magistrate.
But, on the contrary, most Protestants,
when they have not the allowance and toleration of the magistrate, meet only in secret,
and hide their testimony; and, if they be discovered,
if there be any probability of making their escape, by force,
though it were by cutting off those that seek them out, they will do it,
whereby they lose the glory of their sufferings by
not appearing as the innocent followers of Christ,
nor having a testimony of their harmlessness in the hearts of their pursuers; their fury,
by such resistance, is the more kindled against them.
As to this last part of resisting such as persecute them,
they can lay claim to no precept from Christ nor
any example of him or his apostles approved.

But as to the first part for fleeing,
and meeting secretly and not openly testifying for the Truth,
they usually object that saying of Christ (Matt. 10:23),
"`When they persecute you in this city,
flee ye into another.`" And (John 20:19) that the disciples
met secretly "`for fear of the Jews.`" And (Acts 9:25) that
Paul was let out of Damascus "`in a basket down by the wall.`"

To all which I answer, first, as to that saying of Christ,
it is a question if it had any further relation than to that particular message,
with which he sent them to the Jews,
yea the latter end of the words seem expressly to hold forth so much:
"`for ye shall not have gone over the cities of Judah,
till the Son of Man be come.`" Now a particular practice or command,
for a particular time, will not serve for a precedent to any, at this day,
to shun the Cross of Christ.
But, supposing this precept to reach further, it must be so understood,
to be made use of only according as the Spirit giveth liberty,
else no man that could flee might suffer persecution.
How then did not the apostles John and Peter flee,
when they were the first time persecuted at Jerusalem?
But, on the contrary, went the next day, after they were discharged by the Council,
and preached boldly to the people.
But indeed many are but too capable to stretch such sayings as these,
for self-preservation, and therefore have great ground to fear, when they interpret them,
that they shun to witness for Christ, for fear of hurt to themselves,
lest they mistake them.
As for that private meeting of the disciples,
we have only an account of the matter of fact,
but that suffices not to make of it a precedent for us,
and men`'s aptness to imitate them in that (which, for aught we know,
might have been an act of weakness) and not in other things of the contrary nature,
shows that it is not a true zeal to be like those disciples,
but indeed a desire to preserve themselves, which moves them to do so.
Lastly, as to that of Paul`'s being conveyed out of Damascus, the case was singular,
and is not to be doubted, but it was done by a special allowance from God,
who having designed him to be a principal minister of his Gospel, saw meet,
in his wisdom, to disappoint the wicked counsel of the Jews.
But our adversaries have no such pretext for fleeing,
whose fleeing proceeds from self-preservation, not from immediate revelation.
And that Paul made not this the method of his procedure, appears,
in that at another time, notwithstanding the persuasion of his friends,
and certain prophecies of his sufferings to come,
he would not be dissuaded to going up to Jerusalem, which,
according to the forementioned rule he should have done.

But lastly, to conclude this matter, Glory to God and our Lord Jesus Christ,
that now these twenty-five years,
since we were known to be a distinct and separate people,
hath given us faithfully to suffer for his Name, without shrinking or fleeing the Cross;
and what liberty we now enjoy, it is by his mercy,
and not by any outward working or procuring of our own,
but `'tis he has wrought upon the hearts of our opposers;
nor was it any outward interest hath procured it unto us,
but the testimony of our harmlessness in the hearts of our superiors:
for God hath preserved us hitherto in the patient sufferings of Jesus,
that we have not given away our cause by persecuting any, which few, if any, Christians,
that I know, can say.
Now against our unparalleled, yet innocent and Christian cause,
our malicious enemies have nothing to say, but that, if we had power,
we would do so likewise.
This is a piece of mere unreasonable malice,
and a privilege they take to judge of things to come,
which they have not by immediate revelation;
and surely it is the greatest height of harsh judgment,
to say men would do contrary to their professed principle, if they could, who have,
from their practice, hitherto given no ground for it,
and wherein they only judge others by themselves:
such conjectures can not militate against us, so long as we are kept innocent.
And if ever we prove guilty of persecution,
by forcing other men by corporal punishment to our way,
then let us be judged the greatest of hypocrites, and let not any spare to persecute us.
Amen, saith my soul.
