== THE FIFTEENTH PROPOSITION

Concerning Salutations and Recreations, etc.

Seeing the chief end of all religion is to redeem men from
the spirit and vain conversation of this world,
and to lead into inward communion with God, before whom if we fear always,
we are accounted happy, therefore all the vain customs and habits thereof,
both in word and deed,
are to be rejected and forsaken by those who come to this fear;^
footnote:[Eph. 5:11; 1 Pet. 1:14; John 5:44; Jer. 10:3; Acts 10:26;
Matt. 15:13; Col. 2:8.]
such as taking off the hat to a man, the bowings and cringings of the body,
and such other salutations of that kind,
with all the foolish and superstitious formalities attending them,
all which man has invented in his degenerate state to feed
his pride in the vain pomp and glory of this world,
as also the unprofitable plays, frivolous recreations,
sportings and gamings which are invented to pass away the precious time,
and divert the mind from the witness of God in the heart,
and from the living sense of his fear,
and from that evangelical spirit wherewith Christians ought to be leavened,
and which leads into sobriety, gravity, and godly fear, in which as we abide,
the blessing of the Lord is felt to attend us in those actions,
which we are necessarily engaged,
in order to the taking care for the sustenance of the outward man.

// lint-disable invalid-characters "§"
§I. Having hitherto treated of the principles of religion,
both relating to doctrine and worship, I am now to speak of some practices,
which have been the product of this principle,
in those witnesses whom God hath raised up in this day, to testify for his Truth.
It will not a little commend them (I suppose) in the judgment of sober and judicious men,
that, taking them generally (even by the confession of their adversaries),
they are found to be free of those abominations which abound among other professors,
such as are swearing, drunkenness, whoredom, riotousness, etc.,
and that generally the very coming among this people, doth naturally work such a change,
so that many vicious and profane persons have been known, by coming to this Truth,
to become sober and virtuous; and many light, vain, and wanton ones,
to become grave and serious, as our adversaries dare not deny,^
footnote:[After this manner the Papists used to disapprove the sobriety of the Waldenses,
of whom Reincrus, a Popish author, so writeth.
"`But this sect of the Leonists hath a great show of truth;
for that they live righteously, before men, and believe all things well of God,
and all the articles which are contained in the creed;
only they blaspheme and hate the church of Rome.`"]
yet, that they may not want something to detract us for,
cease not to accuse us for those things, which, when found among themselves,
they highly commend; thus our gravity they call sullenness; our seriousness, melancholy;
our silence, sottishness.
Such as have been vicious and profane among them,
but by coming to us have left off those evils,
lest they should commend the truth of our profession, they say,
that whereas they were profane before, they are now become worse,
in being hypocritical and spiritually proud.
If any before dissolute and profane among them, by coming to the Truth with us,
become frugal and diligent, then they will charge them with covetousness.
And if any eminent among them for seriousness, piety, and discoveries of God,
come unto us, then they will say,
they were always subject to melancholy and to enthusiasm, though before, when among them,
it was esteemed neither melancholy nor enthusiasm in an evil sense,
but Christian gravity and Divine revelation.
Our boldness and Christian suffering, they call obstinacy and pertinacity,
though half as much, if among themselves, they would account Christian courage,
and nobility.
And though thus by their envy they strive to read all, relating to us, backwards,
counting these things vices in us, which in themselves they would extol as virtues,
yet hath the strength of Truth extorted this confession often from them,
that we are generally a pure and clean people as to the outward conversation.

But this, they say, is but in policy to commend our heresy.

But such policy it is, say I, as Christ and his apostles made use of,
and all good Christians ought to do;
yea so far hath Truth prevailed by the purity of its followers,
that if one that is called a Quaker, do but that, which is common among them,
as to laugh and be wanton, speak at large, and keep not his word punctually,
or be overtaken with hastiness or anger, they presently say,
"`O! this is against your profession!`" As if indeed
so to do were very consistent with theirs,
wherein, though they speak the Truth, yet they give away their cause.
But if they can find any, under our name,
in any of those evils common among themselves (as who can imagine,
but among so many thousands there will be some chaff,
since of twelve apostles one was found to be a devil), O! how will they insult,
and make more noise of the escape of one Quaker, than of an hundred among themselves!

// lint-disable invalid-characters "§"
§II. But there are some singular things,
which most of all our adversaries plead for the lawfulness of, and allow themselves in,
as no ways inconsistent with the Christian religion,
which we have found to be no ways lawful unto us,
and have been commanded of the Lord to lay them aside,
though the doing thereof hath occasioned no small sufferings and buffetings,
and hath procured us much hatred and malice from the world.
And because the nature of these things is such,
that they do upon the very sight distinguish us, & make us known,
so that we cannot hide ourselves from any without proving unfaithful to our testimony:
our trials and exercises have herethrough proved the more numerous and difficult,
as will after appear.
These I have laboured briefly to comprehend in this Proposition,
but they may more largely be exhibited in these six following propositions:

1) That it is not lawful to give to men such flattering titles as,
"`Your Holiness,`" "`Your Majesty,`" "`Your Eminency,`" "`Your Excellency,`"
"`Your Grace,`" "`Your Lordship,`" "`Your Honor,`" etc.,
nor use those flattering words commonly called "`compliments.`"

2) That it is not lawful for Christians to kneel or prostrate themselves to any man,
or to bow the body, or to uncover the head to them.

3) That it is not lawful for a Christian to use superfluities in apparel,
as are of no use save for ornament and vanity.

4) That it is not lawful to use games, sports, plays, nor, among other things,
comedies among Christians, under the notion of recreations,
which do not agree with Christian silence, gravity, and sobriety: for laughing, sporting,
gaming, mocking, jesting, talking,^
footnote:[Later editors insert "`vain`" before "`talking.`"]
etc., is not Christian liberty, nor harmless mirth.

5) That it is not lawful for Christians to swear at all under the Gospel,
not only not vainly, and in their common discourse,
which was also forbidden under the Mosaical law,
but even not in judgment before the magistrate.

6) That it is not lawful for Christians to resist evil, or to war or fight in any case.

Before I enter upon a particular disquisition of these things,
I shall first premise some general considerations, to prevent all mistakes,
and next add some general considerations, which equally respect all of them.
I would not have any judge, that hereby we intend to destroy the mutual relation,
that either is betwixt prince and people, master and servants, parents and children,
nay not at all.
We shall evidence that our principle in these things hath no such tendency,
and that these natural relations are rather better established than any ways hurt by it.
Next, let not any judge that from our opinion in these
things any necessity of levelling will follow,
or that all men must have things in common.
Our principle leaves every man to enjoy that peaceably,
which either his own industry or parents have purchased to him,
only he is thereby instructed to use it aright,
both for his own good and that of his brethren, and all to the glory of God:
In which also his acts are to be voluntary and no ways constrained.
And further, we say not hereby that no man may use the creation more or less than another.
For we know that, as it hath pleased God to dispense it diversely, giving to some more,
and some less, so they may use it accordingly.
The several conditions under which men are diversely stated,
together with their educations answering thereunto, do sufficiently show this:
the servant is not the same way educated as the master, nor the tenant as the landlord,
nor the rich as the poor; nor the prince as the peasant.
Now though it be not lawful for any,
however great abundance they may have or whatever their education may be,
to use that which is merely superfluous:
yet seeing their education has accustomed them thereunto,
and their capacity enables them so to do without being profuse or extravagant,
they may use things better in their kind than such whose education hath neither
accustomed them to such things nor their capacity will reach to compass them.
For it is beyond question that whatever thing the creation affords is for the use of man,
and the moderate use of them is lawful,
yet per accidens they may be unlawful to some and not to others.
As for instance,
who by reason of his estate and education hath been used to eat flesh and drink wine,
and to be clothed with the finest wool, if his estate bear it,
and he use it neither in superfluity nor immoderately, he may do it, and perhaps,
if he should apply himself to feed or be clothed as are the peasants,
it might prejudice the health of his body and nothing advance his soul.
But if a man whose estate and education had
accustomed to both coarser food and raiment,
should stretch himself beyond what he had or were used to,
to the manifest prejudice of his family and children,
no doubt it would be unlawful to him,
even so to eat or be clothed as another (in whom it is lawful,
for that that other may as much mortified,
and have denied himself as much in coming down to that, which this aspires to,
as he in willing to be like him aspires beyond what
he either is able or hath accustomed to do.
The safe place then is for such as have fulness to watch over themselves,
that they use it moderately and rescind all superfluities,
being willing so far as they can to help the need of those
to whom Providence hath allotted a smaller allowance.
Let the brother of high degree rejoice in that he is abased,
and such as God calls in a low degree to be content with their condition,
not envying those brethren who have greater abundance,
knowing they have received abundance as to the inward man,
which is chiefly to be regarded.
And therefore beware of such a temptation as to use
their calling as an engine to be richer,
knowing they have this advantage beyond the rich and noble that are called,
that the Truth doth not any ways abase them, nay not in the esteem of the world,
as it doth the other,
but that they are rather exalted thereby in that as to the inward and spiritual fellowship
of the saints they become the brethren and companions of the greatest and richest,
and in this respect, "`let him of low degree rejoice that he is exalted`" (James 1:9).

These things premised, I would seriously propose unto all such as mind in reality,
to be Christians indeed, and that in nature and not in name only,
whether it were not desirable,
and would not greatly contribute to the commendation of Christianity
and to the increase of the life and virtue of Christ,
if all superfluous titles of honor, profuseness and prodigality in meat and apparel,
excess of^
footnote:[Later editors delete "`excess of.`"]
gaming, sporting and playing were laid aside and forborne?
And whether such as lay them aside, in so doing,
walk not more like the disciples of Christ and his apostles,
and are therein nearer their example than such as use them?
Whether the laying them aside would hinder any from being good Christians,
or if Christians might not be better without them than with them?
Certainly the sober and serious among all sorts will say yea.
Then surely such as lay them aside, as reckoning them unsuitable for Christians,
are not to be blamed but rather commended for so doing:
because that both in principle & practice they effectually
advance that which others acknowledge were desirable,
but can never make effectual so long as they allow the use of them as lawful.
And God hath made it manifest in this age that by discovering the evil of such things,
and leading his witnesses out of them and to testify against them,
he hath produced effectually, in many,
that mortification and abstraction from the love and cares of this world,
who daily are conversing in the world (but inwardly redeemed
out of it) both in wedlock and in their lawful employments,
which was judged could only be obtained by such as were shut up in cloisters and monasteries.
Thus much in general.

// lint-disable invalid-characters "§"
§III.
As to the first, we affirm positively;
that it is not lawful for Christians either to give or receive these titles of honor,
as "`Your Holiness,`" "`Your Majesty,`" "`Your Excellency,`" "`Your Eminency,`" etc.

First,
because these titles are no part of that obedience which is due to magistrates or superiors,
neither doth the giving them add to nor diminish from that subjection we owe to them,
which consists in obeying their just and lawful commands, not in titles and designations.

Secondly, we find not,
that in the Scripture any such titles are used either under the Law or the Gospel: but,
that in the speaking to kings, princes, or nobles, they used only a simple compellation,
as "`O King,`" and that without any further designation,
save perhaps the name of the person, as, "`O King Agrippa,`" etc. Thirdly,
it lays a necessity upon Christians most frequently to lie;
because the persons obtaining these titles, either by election or hereditarily,
may frequently be found to have nothing really in them, deserving them,
or answering to them: as some, to whom it is said,
"`Your Excellency,`" having nothing of excellency in them:
and who is called "`Your Grace,`" appears to be an enemy to Grace: and he who is called,
"`Your Honor,`" is known to be base and ignoble.
I wonder what law of man, or what patent ought to oblige me to make a lie,
in calling good, evil; and evil, good?
I wonder what law of man can secure me, in so doing,
from the just judgment of God, that will make me count "`for every idle word`"; and to lie,
is something more!
Surely Christians should be ashamed that such laws, manifestly crossing the Law of God,
should be found among them.

Obj.
If it be said, We ought in charity to suppose that they have these virtues,
because the King has bestowed those titles upon them,
or that they are descended of such as deserved them:

Answ.
I answer, Charity destroys not knowledge:
I am not obliged by charity either to believe or speak a lie.
Now it is apparent, and cannot be denied by any,
but that those virtues are not in many of the persons expressed by the titles they bear,
neither will they allow to speak so to such in whom these virtues are,
unless they be so dignified by outward princes.
So that such as are truly virtuous must not be styled by their virtues,
because not privileged by the princes of this world,
and such as have them not must be so called,
because they have obtained a patent so to be;
and all this is done by those who pretend to be his followers,
that commanded his disciples not to "`call any man Master,`"^
footnote:[Later editors render this "`not to be called of men Master.`"]
and told them such could not believe "`as received honor one from another,
and sought not the honor which cometh from God only.`" This is so plain
to such as will indeed be Christians that it needs no consequence.

Fourthly,
as to those titles of "`Holiness,`" "`Eminency`" and "`Excellency,`"
used among the Papists to the Pope and cardinals,
etc., and "`Grace,`" "`Lordship,`" and "`Worship,`" used to the clergy among the Protestants,
it is a most blasphemous usurpation.
For if they use "`Holiness`" and "`Grace,`" because these
things ought to be in a pope or in a bishop,
how come they to usurp that peculiarly to themselves?
Ought not holiness and grace to be in every Christian?
And so every Christian should say, "`Your Holiness,`" and "`Your Grace`" one to another.
Next, how can they in reason claim any more titles than were practised
and received by the apostles and primitive Christians,
whose successors they pretend they are,
and as whose successors (and no otherwise) themselves, I judge,
will confess any honor they seek is due to them?
Now if they neither sought, received, nor admitted such honor nor titles,
how came these by them?
If they say they did, let them prove it if they can;
we find no such thing in the Scripture.
The Christians speak to the apostles without any such denominations, neither saying,
"`If it please Your Grace,`" "`Your Holiness,`" "`Your Lordship,`" nor "`Your Worship`";
they are neither called "`My Lord Peter,`" nor "`My Lord Paul`";
nor yet "`Master Peter`" nor "`Master Paul,`" nor "`Doctor Peter`" nor "`Doctor Paul`";
but singly "`Peter`" and "`Paul,`" and that not only
in the Scripture but for some hundreds of years after.
So that this appears to be a manifest fruit of the apostasy:
for if these titles arise either from the office or worth of the persons,
it will not be denied but the apostles deserved them
better than any now that call for them.
But the case is plain, the apostles had the holiness, the excellency, the grace,
and because they were holy, excellent and gracious,
they neither used nor admitted of such titles; but these, having neither holiness,
excellency, nor grace, will needs be so called,
to satisfy their ambitious and ostentive^
footnote:[ostentive +++=+++ ostentatious]
minds, which is a manifest token of their hypocrisy.

Fifthly, as to that title of "`Majesty,`" usually ascribed to princes,
we do not find it given to any such in the holy Scripture.
But that it is specially and peculiarly ascribed unto God, as 1 Chron. 29:11;
Job 37:22; Ps. 21:5; 29:4; 45:3; 93:1; 96:6; and Isa. 2:10; 24:14; and 26:10;
Heb. 1:3; 2 Pet. 1:16, and many more places.
Hence saith Jude (v. 25), "`To the only wise God our Saviour, be glory and majesty,`" etc.,
not to men.
We find in Scripture the proud King Nebuchadnezzar
assuming this title to himself (Dan. 4:30),
who at that time received a sufficient reproof, by a sudden judgment,
which came upon him.
Therefore in all the compellations used to princes in the Old Testament,
it is not to be found, nor yet in the New.
Paul was very civil to Agrippa, yet he gives him no such title:
neither was this title used among Christians in the primitive times.
Hence the Ecclesiastical History of the Reformation of France,^
footnote:[Eccles. Hist. Lib. 4, p. 445.]
relating the speech of the Lord Rochefort at the assembly of the Estate of France,
held under Charles the Ninth in the year 1560, saith,
"`that this harangue was well remarked,
in that he used not the word '`Majesty,`' invented by flatterers
of late years,`" and yet this author minded not how his master
Calvin used this flattering title to Francis the First,
King of France, and not only so,
but calls him "`most Christian King,`" in the Epistle to his Institutions,
though by his daily persecuting of the Reformers,
it was apparent he was far from being such, even in Calvin`'s own esteem.
Surely the complying with such vain titles, imposed and introduced by Antichrist,
greatly tended to stain the Reformation and to render it defective in many things.

Lastly, all these titles and styles of honor are to be rejected by Christians;
because they are to seek the honor that comes from above,
and not the honor that is from below.
But these honors are not that honor that comes from above, but are from below.
For we know well enough what industry and what pains men are at to get these things,
and what part it is that seeks after them, to wit, the proud, insolent, haughty,
aspiring mind.
For judge, is it the meek and innocent Spirit of Christ, that covets that honor?
Is it that Spirit, that must be of no reputation in this world,
that has its conversation in heaven,
that comes to have fellowship with the sons of God?^
footnote:[Phil. 3:20.]
Is it that Spirit, I say, that loves that honor, that seeks after that honor,
that pleads for the upholding of that honor,
that frets and rages and fumes when it is denied that honor?
Or is it not rather the lordly insulting spirit of Lucifer, the prince of this world,
he that of old affected and sought after this honor,
and loved not to abide in the submissive low place?
And so all his children are possessed with the same ambitious proud mind,
seeking and coveting titles of honor, which indeed belong not to them.
For let us examine,^
footnote:[Jerome, in his Epistle to Celant,
admonisheth her that "`she was to be preferred to none for her nobility,
for the Christian religion admits not of respect of persons,
neither are men to be esteemed because of their outward condition,
but according to the disposition of the mind to be esteemed either noble or base;
he that obeyeth not sin is free,
who is strong in virtue is noble.`" Let the Epistle of James be read.]
who are they, that are honorable indeed?^
footnote:[1 Sam. 2:30.]Is it not the righteous man?
Is it not the holy man?
Is it not the humble-hearted man?
the meek-spirited man?
And are not such those that ought to be honored among Christians?
Now, of these, may there not be poor men?
labourers?
silly fishermen?
And if so, how comes it that the titles of honor are not bestowed upon such?
But who are they that generally receive and look for this honor?
Are they not the rich ones?
such as have abundance of the earth?
as be like the rich glutton?
such as are proud and ambitious?
such as are oppressors of the poor?
such as swell with lust and vanity?
and all "`superfluity of naughtiness`"? who are the
very abomination and plague of the nations?
are not these they that are accounted the honorable,
that require and receive the titles of honor, proud Hamans?
Now whether is this the honor that comes from God or the honor from below?
Doth God honor such as daily dishonor him and disobey him?
And if this be not the honor that comes from God, but the honor of this world,
which the children of this world give and receive one from another,
how can the children of God, such as are Christians indeed,
give or receive that honor among themselves, without coming under the reproof of Christ,
who saith, that such as do, cannot believe?
But further,
if we respect the cause that most frequently procures to men these titles of honor,
there is not one of a thousand that shall be found to be,
because of any Christian virtue.
But rather for things to be discommended among Christians.
As by the favor of Princes procured by flattering, and often by worse means,
yea the most frequent, and accounted among men most honorable, is fighting,
or some great martial exploit, which can add nothing to a Christian`'s worth: since,
sure it is, it were desirable there were no fightings among Christians at all,
and insofar as there are, it show they are not right Christians.
And James tells us that all fighting proceeds from the lusts,
so that it were fitter for Christians by the sword
of God`'s Spirit to fight against their lusts,
than by the prevalency of their lusts to destroy one another.
Whatever honor any might have attained of old, under the Law, this way,
we find under the Gospel Christians commended for suffering, not for fighting,
neither did any of Christ`'s disciples, save one, offer outward violence by the sword,
in cutting off Malchus`'s ear, for which he received no title of honor,
but a just reproof.
Finally, if we look either to the nature of this honor, the cause of it,
the way it is conveyed, the terms in which it is delivered,
it cannot be used by such as mind to be Christians in good earnest.

// lint-disable invalid-characters "§"
§IV. Now besides these general titles of honor,
what gross abuses are crept in among such as are called Christians,
in the use of compliments, wherein, not servants to masters or others,
with respect to any such kind of relations,^
footnote:[Later editors insert "`but others who have no such relation.`"]
do say and write to one another, at every turn,
"`Your humble servant,`" "`Your most obedient servant,`" etc. Such wicked customs have,
to the great prejudice of souls, accustomed Christians to lie,
and to use lying is now come to be accounted civility.
O horrid apostasy!
For it is notoriously known,
that the use of these compliments imports not any design of service,
neither are any such fools as to think so, for, if we should put them to it, that say so,
they would not doubt to think we abused them;
and would let us know they gave us words in course, and no more.
It is strange that such as pretend to Scripture as
their rule should not be ashamed to use such things;
since Elihu, that had not the Scriptures, would, by the Light within him,
which these men think insufficient, say (Job 32:21-22):
"`Let me not accept any man`'s person, neither let me give flattering titles unto man.
For I know not to give flattering titles,
in so doing my Maker would soon take me away.`" A certain ancient devout man,
in the primitive time, subscribed himself, to a bishop, "`Your humble servant,`" wherein,
I doubt not but he was more real than our usual complimenters;
and yet he was sharply reproved for it.^
footnote:[This history is reported by Casaubon in his book of manners and customs, p. 169.
"`In this last age he is esteemed an uncivil man who will not,
either to his inferior or equal, subscribe himself servant.
But Sulpicius Severus was heretofore sharply reproved by Paulinus Bishop of Nola,
because in his epistle he had subscribed himself his '`servant,`' saying,
'`Beware thou subscribe not thyself his servant, who is thy brother,
for flattery is sinful, not a testimony of humility to give those honors
to men which are only due to the One Lord, Master and God.`'"`]

But they usually object, to defend themselves, that Luke saith,
"`Most Excellent Theophilus,`" and Paul, "`Most Noble Festus.`"

I answer, since Luke wrote that by the dictates of the infallible Spirit of God,
I think it will not be doubted but Theophilus did deserve it,
as being really endued with that virtue, in which case we shall not condemn those,
that do it by the same rule.
But it is not proved that Luke gave Theophilus this
title as that which was inherent to him,
either by his father,
or by any patent Theophilus had obtained from any of the princes of the earth,
or that he would have given it him, in case he had not been truly excellent;
and without this be proved, which never can,
there can nothing hence be deduced against us.
The like may be said of that of Paul to Festus, whom he would not have called such,
if he had not been truly noble; as indeed he was,
in that he suffered him to be heard in his own cause,
and would not give way to the fury of the Jews against him;
it was not because of any outward title bestowed upon Festus, that he so called him,
else he would have given the same appellation to his predecessor Felix,
who had the same office, but being a covetous man, we find he gives him no such style.

// lint-disable invalid-characters "§"
§V. It will not be unfit in this place to say something
concerning the using of the singular number to one person;
of this there is no controversy in the Latin, for when we speak to one,
we always use the pronoun tu,
and he that would do otherwise would break the rules of grammar.
For what boy, learning his rudiments,
is ignorant that it is incongruous to say "`vos amas,`" "`vos legis,`" that is,
"`you lovest,`" "`you readest,`" speaking to one?
But the pride of man, that hath corrupted many things,
refuses also to use this simplicity of speaking in the vulgar languages.
For being puff`'d up with a vain opinion of themselves,
as if the singular number were not sufficient to them,
they will have others to speak to them in the plural.
Hence Luther, in his plays, reproves and mocks this manner of speaking, saying,
"`Magister,
vos es iratus.`" Which corruption Erasmus sufficiently refutes in his Colloquies.
Concerning which likewise James Howel, in his epistle to the nobility of England,
before the French and English Dictionary, takes notice,
"`that both in France and in other nations,
the word '`thou`' was used in speaking to one, but, by success of time,
when the Roman commonwealth grew into an empire,
the courtiers began to magnify the emperor (as being
furnished with power to confer dignities and offices),
using the word '`you,`' yea and deifying him with more remarkable titles;
concerning which matter we read in the epistles of
Symmachus to the Emperors Theodosius and Valentinianus,
where he useth these forms of speaking: Vestra Aeternitas, '`Your Eternity`';
Vestrum Numen, '`Your Godhead`'; Vestra Serenitas, '`Your Serenity`'; Vestra Clementia,
'`Your Clemency.`'
So that the word '`you`' in the plural number,
together with the other titles and compellations of honor,
seem to have taken their rise from monarchical government; which afterwards, by degrees,
came to be derived to private persons.`"

The same is witnessed by John Maresius, of the French Academy,
in the preface of his Clovis.
"`Let none wonder`" (saith he) "`that the word '`thou`'
is used in this work to princes and princesses:
for we use the same to God: and of old the same was used to Alexanders, Caesars,
queens and empresses.
The use of the word '`you,`' when one person is spoken to,
was only introduced by these base flatteries of men of latter ages,
to whom it seemed good to use the plural number to one person,
that he may imagine himself alone to be equal to many others in dignity and worth,
from whence at last it came to persons of lower quality.`"

To the same purpose speaketh also M. Godeau,
in his preface to the New Testament translation:
"`I had rather`" (saith he) "`faithfully keep to the express words of Paul,
than exactly follow the polished style of our tongue.
Therefore I always use that form of calling God in the singular number,
not in the plural; and therefore I say rather '`thou`' than '`you.`'
I confess indeed,
that the civility and custom of this world requires him to be honored after that manner;
but it is likewise on the contrary true,
that the original tongue of the New Testament hath
nothing common with such manners and civility,
so that not one of these many old versions we have, doth observe it.
Let not men believe, that we give not respect enough to God,
in that we call him by the word '`thou,`' which is nevertheless far otherwise,
for I seem to myself (may be by the effect of custom) more to honor his Divine Majesty,
in calling him after this manner,
than if I should call him after the manners
of men who are so delicate in their forms of speech.`"

See how clearly and evidently these men witness that this form of speaking,
and these profane titles, derive their origin from the base flattery of these last ages,
and from the delicate haughtiness of worldly men, who have invented these novelties,
that thereby they might honor one another under,
I know not what pretence of civility and respect.
From whence many of the present Christians, so accounted, are become so perverse,
in commending most wicked men, and wicked customs,
that the simplicity of the Gospel is wholly lost,
so that the giving of men and things their own names is not only worn out of custom,
but the doing thereof is accounted absurd and rude, by such kind of delicate parasites,
who desire to ascribe to this flattery and abuse the name of civility.
Moreover, that this way of speaking proceeds from a high and proud mind, hence appears,
because that men usually use the singular number to beggars, and to their servants,
yea and in their prayers to God.
Thus the superior will speak to his inferior,
who yet will not bear that the inferior so speak to him,
as judging it a kind of reproach unto him.
So hath the pride of men placed God and the beggar in the same category.
I think I need not use arguments to prove to such as know congruous language,
that we ought to use the singular number, speaking to one;
which is the common dialect of the whole Scripture,
as also the most interpreters do translate it.
Seeing therefore it is manifest to us,
that this form of speaking to men in the plural number, doth proceed from pride,
as well as that it is, in itself, a lie,
we found a necessity upon us to testify against this corruption,
by using the singular equally unto all.
And although no reason can be given, why we should be persecuted upon this account,
especially by Christians who profess to follow the rule of Scripture,
whose dialect this is,
yet it would perhaps seem incredible if I should
relate how much we have suffered for this thing,
and how these proud ones fume, fret, and gnash their teeth,
frequently beating and striking us,
when we have spoken to them thus in the singular number:
whereby we are the more confirmed in our judgment,
as seeing that this testimony of Truth, which God hath given us to bear in all things,
doth so vex the serpentine nature in the children of darkness.

// lint-disable invalid-characters "§"
§VI. Secondly, Next unto this of titles,
the other part of honor used among Christians is the kneeling, bowing,
and uncovering of the head to one another.
I know nothing our adversaries have to plead for them in this matter,
save some few instances of the Old Testament, and the custom of the country.

The first are, such as Abraham`'s bowing himself to the children of Heth,
and Lot to the two angels, etc.

But the practice of these patriarchs, related as matter of fact,
are not to be a rule to Christians now;
neither are we to imitate them in every practice
which has not a particular reproof added to it,
for we find not Abraham reproved for taking Hagar, etc.;
and indeed to say all things were lawful for us which they practised
would produce great inconveniences obvious enough to all.
And as to the customs of the nations, it`'s a very ill argument for a Christian`'s practice.
We should have a better rule to walk by, than the custom of the Gentiles;
the apostles desire us not to be "`conformed to this world,`" etc.^
footnote:[Rom. 12:2.]
We see how little they have to say for themselves in this matter.
Let it be observed, then,
whether our reasons for laying aside these things be not
considerable and weighty enough to uphold us in so doing.

First, We say that God, who is the creator of man,
and he to whom he oweth the dedication both of soul and body,
is over all to be worshipped and adored, and that not only by the Spirit,
but also with the prostration of body.
Now kneeling, bowing,
and uncovering of the head is the alone outward signification of our adoration
towards God & therefore it is not lawful to give it unto man.
He that kneeleth or prostrates himself to man, what doth he more to God?
He that boweth and uncovereth his head to the creature,
what hath he reserved to the Creator?
Now the apostle shows us that the uncovering of the head is that
which God requires of us in our worshipping of him (1 Cor. 11).
But if we make our address to men in the same manner,
where lieth the difference?
Not in the outward signification, but merely in the intention;
which opens a door for the Popish veneration of images,
which hereby is necessarily excluded.

Secondly, men,
being alike by creation (though their being stated under
their several relations requires from them mutual services,
according to those respective relations), owe not worship one to another,
but all equally are to return it to God:
because it is to him and his Name alone that every knee must bow,
and before whose throne the four and twenty elders prostrate themselves.
Therefore, for men to take this one from another is to rob God of his glory:
since all the duties of relations may be performed
one to another without these kinds of bowings,
which therefore are no essential part of our duty to man, but to God: all men,
by an inward instinct,
in all nations have been led to prostrate and bow themselves to God.
And it is plain, that this bowing to men took place from a slavish fear possessing some,
which led them to set up others as gods,
when also an ambitious proud spirit got up in those others,
to usurp the place of God over their brethren.

Thirdly, We see that Peter refused it from Cornelius, saying, he was a man.
Are then the popes more, or more excellent, than Peter,
who suffer men daily to fall down at their feet, and kiss them?
This reproof of Peter to Cornelius doth abundantly show
that such manners were not to be admitted among Christians.
Yea, we see that the angel twice refused this kind of bowing from John (Rev. 19:10,
and 22:9) for this reason, "`because I am thy fellow servant, and of thy brethren`";
abundantly intimating that it is not lawful for fellow servants thus to prostrate
themselves one to another (and in this respect all men are fellow servants.)

Obj.
If it be said, John intended here a religious worship, and not a civil:

Answ.
I answer; that is to say, not to prove:
neither can we suppose John at that time of the day so ill-instructed
as not to know it was unlawful to worship angels;
only it should seem,
because of those great and mysterious things revealed to him by that angel,
he was willing to signify some more than ordinary testimony of respect,
for which he was reproved.
These things being thus considered,
it is remitted to the judgment of such as are desirous to be found Christians indeed,
whether we be worthy of blame for waiving it to men.
Let those, then, that will blame us,
consider whether they might not as well accuse Mordecai of incivility,
who was no less singular than we in this matter.
And forasmuch as they accuse us herein of rudeness and pride,
though the testimony of our consciences, in the sight of God,
be a sufficient guard against such calumnies, yet there are of us,
known to be men of such education,
as forbear not these things for want of that they call good breeding,
and we should be very void of reason to purchase that pride at so dear
a rate as many have done the exercise of their conscience in this matter;
many of us having been sorely beaten & buffeted, yea & several months imprisoned,
for no other reason,
but because we could not so satisfy the proud unreasonable humors of proud men,
as to uncover our heads and bow our bodies.
Nor doth our innocent practice in standing still, though upright,
not putting off our hats any more than our shoes,
the one being the covering of our heads, as well as the other of our feet,
show so much rudeness as their beating and knocking us, etc.,
because we cannot bow to them, contrary to our consciences.
Which certainly shows less meekness and humility upon their part,
than it doth of rudeness or pride upon ours.
Now suppose it were our weakness, and we really under a mistake in this thing,
since it is not alleged to be the breach of any Christian precept are we not to be indulged,
as the apostle commanded should be done to such as scrupled to eat flesh?
And do not persecuting us and reviling us upon this account show them to be more
like unto proud Haman than the disciples or followers of the meek,
self-denying Jesus?
And this I can say boldly, in the sight of God, from my own experience,
and that of many thousands more, that however small or foolish this may seem,
yet we behooved to choose death rather than do it, and that for conscience sake: and that,
in its being so contrary to our natural spirits,
there are many of us to whom the forsaking of these
bowings and ceremonies was as death itself.
Which we could never have left if we could have enjoyed
our peace with God in the use of them,
though it be far from us to judge all those to whom God hath not shown the evil of them,
under the like hazard, yet nevertheless, we doubt not,
but to such as would prove faithful witnesses to Christ`'s Divine Light
in their consciences God will also show the evil of these things.

// lint-disable invalid-characters "§"
§VII.
The third thing to be treated of is the vanity and superfluity of apparel,
in which first two things are to be considered, the condition of the person,
and the country, he lives in.
We shall not say, that all persons are to be clothed alike,
because it will perhaps neither suit their bodies, nor their estates.
And if a man be clothed soberly and without superfluity, though they may be finer,
than that which his servant is clothed with, we shall not blame him for it:
the abstaining from superfluities,
which his condition and education have accustomed him to, may be, in him,
a greater act of mortification than the abstaining from finer clothes in the servant,
who never was accustomed to them.
As to the country, what it naturally produces may be no vanity to the inhabitants to use,
or what is commonly imparted to them by way of exchange,
seeing it is without doubt that the creation is for the use of man.
So where silk abounds, it may be worn, as well as wool; and were we in those countries,
or near unto them, where gold or silver were as common as iron or brass,
the one might be used as well as the other.
The iniquity lies then here, First, when, from a lust of vanity,
and a desire to adorn themselves, men and women,
not content with what their condition can bear, or their country easily affords,
do stretch to have things, that from their rarity, and the price that`'s put upon them,
seem to be precious, and so feed their lust the more,
and this all sober men of all sorts will readily grant to be evil.

Secondly, when men are not content to make a true use of the creation,
whether the things be fine or coarse,
and do not satisfy themselves with what need & conveniency calls for,
but add thereunto things merely superfluous, such as is the use of ribbands and lace,
and much more of that kind of stuff, as painting the face, plaiting the hair,
which are the fruits of the fallen, lustful and corrupt nature,
and not of the new creation, as all will acknowledge.
And though sober men, among all sorts,
will say that it were better these things were not,
yet will they not reckon them unlawful,
and therefore do admit the use of them among their church members.
But we do account them altogether unlawful, and unsuitable to Christians,
and that for these reasons:

First, the use of clothes came originally from the fall; if man had not fallen,
it appears he would not have needed them.
But this miserable state made them necessary, in two respects:
1) to cover his nakedness, and 2) to keep him from the cold,
which is both the proper and principal use of them.
Now, for man to delight himself in that which is the fruit of his iniquity,
and is the consequence of sin, can be no ways lawful for him;
so to extend things beyond their real use, or to superadd things wholly superfluous,
is a manifest abuse of the creation, and therefore not lawful to Christians.

Secondly, those that will needs so adorn themselves in the use of their clothes,
as to beset them with things having no real use or necessity,
but merely for ornament`'s sake,
do openly declare that the end of it is either to please their lust (for which end these
things are chiefly invented and contrived) or otherwise to gratify a vain,
proud and ostentatious mind; and it is obvious these are their general ends in so doing.
Yea, we see how easily men are puff`'d up with their garments,
and how proud and vain they are, when adorned to their mind.
Now, how far these things are below a true Christian, and how unsuitable,
it needs not great probation.
Hereby, those that love to be gaudy and superfluous in their clothes,
show they concern themselves little with mortification and self-denial,
and that they mind to beautify their bodies more than their souls,
which proves they mind little upon mortality,
and so certainly are more nominal than real Christians.

Thirdly, the Scripture severely reproves such practices,
both commending and commanding the contrary,
as Isa. 3. How severely doth the prophet reprove
the daughters of Israel for their tinkling ornaments,
their cauls, and their round tiars, their chains and bracelets, etc.,
and yet is it not strange to see Christians allow themselves in these things,
from whom a more strict and exemplary conversation is required?
Christ desires us not to be anxious about our clothing (Matt. 6:25),
and to show the vanity of such as glory in the splendor of their clothing, tells them,
that even Solomon in all his glory was not to be compared to the lily of the field,
which today is, and tomorrow is cast into the oven.
But surely they make small reckoning of Christ`'s words and doctrine,
that are so curious in their clothing, and so industrious to deck themselves,
and so earnest to justify it, and so mad when they are reproved for it.
The apostle Paul is very positive in this respect (1 Tim. 2:8-10):
"`I will therefore in like manner also,
that women adorn themselves in modest apparel, with shamefacedness and sobriety,
not with broidered hair, or gold, or pearls, or costly array: But (which becometh women,
professing godliness) with good works.`" To the same purpose saith Peter (1 Pet. 3:3-4):
"`Whose adorning, let it not be that outward adorning, of plaiting the hair,
and wearing of gold, or of putting on of apparel.
But let it be the hidden man of the heart, in that which is not corruptible,
even the ornament of a meek and quiet spirit,`" etc. Here,
both the apostles do very positively and expressly assert two things: First,
that the adorning of Christian women (of whom it is particularly spoken, I judge,
because this sex is most naturally inclined to that vanity,
and that it seems that Christian men in those days,
deserved not in this respect so much to be reproved) ought not to be outward,
nor to consist in the apparel.
Secondly, that they ought not to use the plaiting of the hair, or ornaments, etc.,
which was at that time the custom of the nations.
But is it not strange, that such as make the Scripture their rule,
and pretend they are guided by it,
should not only be so frequently and ordinarily in the use of these things,
which the Scripture so plainly condemns, but also should allow themselves in so doing?
For the apostles not only commend the forbearance of these things,
as an attainment commendable in Christians, but condemn the use of them as unlawful,
and yet may it not seem more strange, that in contradiction to the apostles`' doctrine,
as if they had resolved to slight their testimony, they should condemn those that,
out of conscience, apply themselves seriously to follow it, as if, in so doing,
they were singular, proud, or superstitious?
This certainly betokens a sad apostasy in those that will be accounted Christians,
that they are so offended with those who love to follow Christ and his apostles,
in denying of, and departing from, the lying vanities of this perishing world,
and so doth much evidence their affinity with such as hate to be reproved,
and neither will enter themselves nor suffer those that would.

// lint-disable invalid-characters "§"
§VIII.
Fourthly, let us consider the use of games, sports,
comedies and other such things,
commonly and indifferently used by all the several sorts
of Christians under the notion of divertisement and recreation,
and see whether these things can consist with the seriousness, gravity,
and godly fear which the Gospel calls for:
Let us but view and look over the notions of them that call themselves Christians,
whether Popish or Protestant, and see if generally there be any difference,
save in mere name and profession, from the heathen; doth not the same folly,
the same vanity, the same abuse of precious and irrevocable time abound?
The same gaming, sporting, playing, and from thence quarrelling, fighting, swearing,
ranting, revelling?
Now how can these things be remedied so long as the preachers and professors
and those who are the leaders of the people do allow these things and
account them not inconsistent with the profession of Christianity?
And it is strange to see that these things are tolerated everywhere,
the Inquisition lays no hold on them, neither at Rome nor in Spain,
where in their masquerades all manner of obscenity, folly,
yea and atheism is generally practised in the face of the world,
to the great scandal of the Christian name:
but if any man reprove them in these things and forsake their superstitions
and come seriously to serve God and worship him in the Spirit,
he is made a prey, and presently made liable to cruel sufferings.
Doth this bear any proportion to Christianity?
Do these things look anything like the churches of the primitive Christians?
Surely not at all.
I shall first cite some few Scripture testimonies,
being very positive precepts to Christians,
and then see whether such as obey them can admit of these forementioned things.
The apostle commands us, that "`whether we eat or drink, or whatever we do,
we do it all to the glory of God.`" But I judge none
will be so impudent as to affirm that,
in the use of these sports and games, God is glorified.
If any should so say, they would declare they neither knew God nor his glory:
and experience abundantly proves that in the practice of these things,
men mind nothing less than the glory of God,
and nothing more than the satisfaction of their own carnal lusts, wills and appetites.
The apostle desires us (1 Cor. 7:29,31): "`Because the time is short,
that they that buy should be, as though they possessed not.
And they that use this world,
as not abusing it,`" etc. But how can they be found in the obedience of this precept,
that plead for the use of these games and sports?
who, it seems, think the time so long,
that they cannot find occasion enough to employ it,
neither in taking care for their souls, nor yet in the necessary care for their bodies,
but invent these games and sports to pass it away,
as if they wanted other work to serve God, or be useful to the creation in.
The apostle Peter desires us "`to pass the time of our sojourning here in fear`"
(1 Pet. 1:17). But will any say that such as use dancing and comedies,
carding, and dicing, do so much as mind this precept in the use of these things?
where there is nothing to be seen, but lightness and vanity, wantonness, and obscenity,
contrived to hinder men from fear, or being serious,
and therefore no doubt calculated for the service of the devil.
There is no duty more frequently commanded, nor more incumbent upon Christians,
than the fear of the Lord, to stand in awe before him, to walk as in his presence,
but if such as use these games and sports will speak from their consciences, they can,
I doubt not, experimentally declare, that this fear is forgotten in their gaming;
and if God by his Light secretly touch them, or mind them of the vanity of their way,
they strive to shut it out,
and use their gaming as an engine to put away from them that troublesome guest,
and thus make merry over the Just One, whom they have slain and crucified in themselves.
But further, if Christ`'s reasoning be to be heeded,
who saith (Matt. 12:35-36) that "`the good man out of
the good treasure of the heart bringeth forth good things;
and an evil man out of the evil treasure bringeth forth evil things`";
and that of "`every idle word we shall give an account in the day of judgment,`"
it may be easily gathered from what treasure these inventions come,
and it may be easily proved, that it is from the evil, and not the good.
How many idle words do they necessarily produce?
Yea what are comedies but a studied complex of idle and lying words?
Let men that believe their souls are immortal,
and that there will be a day of judgment in which these words of Christ will be accomplished,
answer me, how all these will make account in that great and terrible day,
of all these idle words, that are necessarily made use of, about dancing, gaming,
carding, and comedies acting?
And yet, how is it, that by Christians not condemning these things, but allowing of them,
many that are accounted Christians take up their whole time in them,
yea make it their trade and employment,
such as the dancing-masters and comedians, etc.,
whose hellish conversations do sufficiently declare what master they serve,
and to what end these things contribute; and it cannot be denied,
as being obviously manifest by experience, that such as are masters of these trades,
and are most delighted in them (if they be not open atheists and profligates) are such,
at best, as make religion, or the care of their souls, their least business.
Now, if these things were discountenanced by Christians,
or inconsistent with their profession, it would remove these things;
for these wretches would be necessitated then to
betake themselves to some more honest livelihood,
if they were not fed and upholden by these.
And as hereby a great scandal and stumbling-block
would be removed from off the Christian name,
so also would that, in part, be taken out of the way,
which provokes the Lord to withhold his blessing,
and by occasion of which things the minds of many remain chained in darkness,
and drowned in lust, sensuality, and worldly pleasures, without any sense of God`'s fear,
or their own souls`' salvation.
Many of those called Fathers of the Church, and other serious persons,
have signified their regret for these things, and their desires they might be remedied,
of whom many citations might be alleged, which for brevity`'s sake I have omitted.

// lint-disable invalid-characters "§"
§IX. Obj.
But they object, that men`'s spirits could not subsist,
if they were always intent upon serious and spiritual matters,
and that therefore there is need of some divertisement to recreate the mind a little,
whereby it, being refreshed, is able, with greater vigor to apply itself to these things.

Answ.
I answer, though all this were granted, it would no ways militate against us,
neither plead the use of these things, which we would have wholly laid aside.
For that men should be always in the same intentiveness of mind we do not plead,
knowing how impossible it is, so long as we are clothed with this tabernacle of clay.
But this will not allow us at any time so to recede
from the memory of God and of our souls`' chief concern,
as not still to retain a certain sense of his fear;
which cannot be so much as rationally supposed to
be in the use of these things which we condemn.
Now the necessary occasions, which all are involved into,
in order to the care and sustentation of the outward man,
are a relaxation of the mind from the more serious duties;
and those are performed in the blessing,
as the mind is so leavened with the love of God and the sense of his presence,
that even in doing these things,
the soul carrieth with it that divine influence and spiritual habit, whereby,
though these acts, as of eating, drinking, sleeping, working, be, upon the matter,
one with what the wicked do, yet they are done in another spirit, and in doing of them,
we please the Lord, serve him, and answer our end in the creation, and so feel,
and are sensible of his blessing.
Whereas the wicked and profane, being not come to this place, are, in whatsoever they do,
cursed; and their "`ploughing, as well as praying, is sin`"! Now,
if any will plead that for relaxation of mind,
there may be a liberty allowed beyond these things which
are of absolute need to the sustenance of the outward man;
I shall not much contend against it,
provided these things be not such as are wholly superfluous,
or in their proper nature and tendency lead the mind into lust, vanity, and wantonness,
as being chiefly contrived and framed for that end,
or generally experienced to produce these effects,
or being the common engines of such as are so minded to feed one another therein,
and to propagate their wickedness, to the impoisoning of others;
seeing there are other innocent divertisements,
which may sufficiently serve for relaxation to the mind,
such as for friends to visit one another, to hear or read history,
to speak soberly of the present or past transactions, to follow after gardening,
to use geometrical and mathematical experiments, and such other things of this nature;
in all which things we are not so to forget God (in whom we both live and are moved,
Acts 17:28) as not to have always some secret reserve to him,
and sense of his fear and presence,
which also frequently exerts itself in the midst of these things,
by some short aspiration and breathings,
and that this may neither seem strange nor troublesome,
I shall clear it by one manifest instance, answerable to the experience of all men:
it will not be denied but that men ought to be more in the love of God,
than of any other thing; for we ought to love God above all things.
Now it is plain that men that are taken with love, whether it be of a woman,
or of any other thing, if it hath taken a deep place in the heart, and possess the mind,
it will be hard for the man, so in love,
to drive out of his mind the person or thing so loved, yea in his eating,
drinking, and sleeping his mind will always have a tendency that way, and,
in business or recreations, however intent he be in it,
there will but a very short time be permitted to pass,
but the mind will let some ejaculation forth towards its beloved.
And, albeit such a one must be conversant in those things that
the care of this body and suchlike things call for,
yet will he avoid, as death itself,
to do those things that may offend the party so beloved,
or cross his design in obtaining the thing so earnestly desired;
though there may be some small use in them, the great design which is chiefly in his eye,
will so balance him,
that he will easily look over & dispense with such petty necessities,
rather than endanger the loss of the greater by them.
Now that men ought to be thus in love with God and the life to come, none will deny,
and the thing is apparent from these Scriptures: Matt. 6:20,
"`But lay up for yourselves treasures in heaven`"; Col. 3:2,
"`Set your affection on things above,`" etc. And that
this hath been the experience and attainment of some,
the Scripture also declares (Ps. 63:1; 84:2; 2 Cor. 5:14).

And again, that these games, sports, plays, dancing, comedies, etc.,
do naturally tend to draw men from God`'s fear, to make them forget heaven, death,
and judgment, to foster lust, vanity, and wantonness,
and therefore are most loved as well as used by such kind of persons,
experience abundantly shows;
and the most serious and conscientious among all will scarcely deny, which if it be so,
the application is easy.

// lint-disable invalid-characters "§"
§X. Fifthly, the use of swearing is to be considered,
which is so frequently practised almost among all Christians,
not only profane oaths among the profane in their common discourses,
whereby the most holy name of god is, in a horrible manner, daily blasphemed,
but also solemn oaths with those that have some show of piety,
whereof the most part do defend swearing before the magistrate,
with so great zeal that not only they are ready themselves to do it upon every occasion,
but also stir up the magistrates to persecute those, who,
out of obedience to Christ their Lord and Master, judge it unlawful to swear:
upon which account not a few have suffered imprisonment, and the spoiling of their goods.

But considering these clear words of our Saviour (Matt.
5:33-34), "`Again, ye have heard that it hath been said by them of old time,
Thou shalt not forswear thyself, but shalt perform unto the Lord thine oaths.
But I say unto you, swear not at all,
neither by heaven,`" etc. "`But let your communication be yea, yea; nay, nay:
for whatsoever is more than these,
cometh of evil.`" As also the words of the apostle James (5:12), "`But above all things,
my brethren, swear not, neither by heaven, neither by the earth,
neither by any other oath: but let your yea be yea, and your nay, nay:
lest ye fall into condemnation.`" I say, considering these clear words,
it is admirable how anyone that professeth the Name
of Christ can pronounce any oath with a quiet conscience;
far less to persecute other Christians, that dare not swear,
because of their Master Christ his authority.
For did anyone purpose seriously, and in the most rigid manner, to forbid anything,
comprehended under any general, can they use a more full and general prohibition,
and that without any exception?
I think not.
For Christ, first, proposeth it to us negatively, "`Swear not at all, neither by heaven,
nor by the earth, nor by Jerusalem, nor by thy head,`" etc. And again,
"`Swear not by heaven, nor by earth, nor by any other oath.`" Secondly,
he presseth it affirmatively, "`But let your communication be yea, yea, and nay, nay:
for whatsoever is more than these, cometh of evil.`" And saith James,
"`Lest ye fall into condemnation.`"

Which words both all and every one of them do make such a full prohibition,
and so free of all exception,
that it is strange how men that boast the Scripture is the
rule of their faith and life can counterfeit any exception.
Certainly reason ought to teach everyone that it
is not lawful to make void a general prohibition,
coming from God, by such opposition,
unless the exception be as clearly and evidently expressed as the prohibition;
neither is it enough to endeavor to confirm it by consequences and probabilities,
which are obscure and uncertain, and not sufficient to bring quiet to the conscience.
For if they say that there is therefore an exception and limitation in the words because
there are found exceptions in the other general prohibition of this fifth chapter,
as in the forbidding of divorcement, where Christ saith, "`It hath been said,
whosoever shall put away his wife, let him give her a writing of divorcement.
But I say unto you, That whosoever shall put away his wife,
saving for the cause of fornication, causeth her to commit adultery`"; if, I say,
they say this, they not only labour in vain but also fight against themselves,
because they can produce no exception of this general command of not swearing,
expressed by God to any under the New Covenant, after Christ gave this prohibition,
so clear as that which is made in the prohibition itself: moreover,
if Christ would have excepted oaths made before magistrates,
certainly he had then expressed, adding, "`except in judgment,
before the magistrate,`" or the like; as he did in that of divorcement, by these words,
"`saving for the cause of fornication`": which being so,
it is not lawful for us to except or distinguish,
or (which is all one) make void this general prohibition of Christ;
it would be far less agreeable to Christian holiness to
bring upon our heads the crimes of so many oaths which,
by reason of this corruption and exception, are so frequent among Christians.

Neither is it to be omitted, that without doubt,
the most learned doctors of each sect know,
that these forementioned words were understood by the ancient
Fathers of the first three hundred years after Christ,
to be a prohibition of all sorts of oaths: it is not then without reason,
that we wonder that the Popish doctors and priests bind themselves by an oath to interpret
the holy Scriptures according to the universal exposition of the holy Fathers;
who notwithstanding understood those controverted texts
quite contrary to what these modern doctors do:
and from thence also doth clearly appear the vanity and
foolish certainty (so to speak) of Popish traditions;
for if by the writings of the Fathers, so called,
the faith of the church of those ages may be demonstrated,
it is clear they have departed from the faith of the church
of the first three ages in the point of swearing.
Moreover,
because not only Papists but also Lutherans and Calvinists and some others
do restrict the words of Christ and James 1 think it needful to make manifest
the vain foundation upon which their presumption in this matter is built.

// lint-disable invalid-characters "§"
§XI. Obj.
First,
they object that Christ only forbids these oaths that are made by creatures,
and things created; and they prove it thence, because he numbers some of these things.

Secondly, All rash and vain oaths in familiar discourses; because he saith,
"`Let your communication be yea, yea, and nay, nay.

Answ.
1+++.+++ To which I answer, First, that the Law did forbid all oaths made by the creatures,
as also all vain and rash oaths in our common discourses,
commanding that men should only swear by the Name of God, and that neither falsely,
nor rashly, for that is to take his Name in vain.

Answ.
2+++.+++ Secondly,
it is most evident that Christ forbids somewhat that was permitted under the Law, to wit,
to swear by the Name of God,
because it was not lawful for any man to swear but by God himself, and because he saith,
"`neither by heaven,
because it is the throne of God,`" therefore he excludes all other oaths,
even those which are made by God; for he saith (23:22),
"`he that shall swear by heaven sweareth by the throne of God and by him
that sitteth thereon,`" which is also to be understood of the rest.

Answ.
3+++.+++ Lastly, that he might put the matter beyond all controversy,
he adds "`neither by any other oath.`" Therefore, seeing to swear before the magistrate,
by God, is an oath, it is here without doubt forbidden.

Obj.
Secondly, they object that by these words oaths by God`'s Name cannot be forbidden,
because the heavenly Father hath commanded them, for the Father and the Son are one,
which could not be, if the Son did forbid that which the Father commanded.

Answ.
I answer, they are indeed one, and cannot contradict one another;
nevertheless the Father gave many things to the Jews, for a time,
because of their infirmity under the old Covenant,
which had only a shadow of good things to come, not the very Substance of things,
until Christ should come, who was the Substance,
and by whose coming all these things vanished, to wit, sabbaths, circumcision,
the paschal lamb, men used then sacrifices, who lived in controversy with God,
& one with another, which all are abrogated in the coming of the Son,
who is the Substance, Eternal Word, and essential oath and Amen,
in whom "`the promises of God are Yea and Amen`":
who came that men might be redeemed out of strife, and might make an end of controversy.

Obj.
Thirdly, they object, But all oaths are not ceremonies,
nor any part of the ceremonial Law.

Answ.
I answer, Except it be shown to be an eternal, immutable, and moral precept,
it withstands not;
neither are they of so old an origin as tithes and
the offering of the first fruits of the ground,
which by Abel and Cain were offered, long before the ceremonial law, or the use of oaths,
which, whatever may be alleged against it, were no doubt ceremonies,
and therefore no doubt unlawful now to be practised.

Obj.
Fourthly,
they object that to swear by the Name of God is a moral precept of continual duration;
because it is marked with his essential and moral worship (Duet. 6:13, and 10:20),
"`Thou shalt fear the Lord thy God, and serve him alone: thou shalt cleave to him,
and swear by his Name.`"

Answ.
I answer, this proves not that it is a moral and eternal precept;
for Moses adds that to all the precepts and ceremonies in several places:
as Duet. 10:12-13, saying, "`And now, Israel,
what doth the Lord thy God require of thee, but to fear the Lord thy God,
to walk in all his ways, and to love him,
and to serve the Lord thy God with all thy heart, and with all thy soul.
To keep the commandments of the Lord, and his statutes,
which I command thee this day?`" And (14:23),
the fear of the Lord is mentioned together with the tithes.
And so also Lev. 19:2-3,12,
the Sabbaths and regard to parents are mentioned with swearing.

Obj.
Fifthly, they object that solemn oaths, which God commanded,
cannot be here forbidden by Christ, for he saith that they come from evil:
But these did not come from evil, for God never commanded anything that was evil,
or came from evil.

Answ.
I answer, there are things which are good because commanded, and evil because forbidden:
other things are command, because good, and forbidden, because evil.
As circumcision and oaths, which were good, when and because they were commanded,
and in no other respect; and again, when and because prohibited under the Gospel,
they are evil.

And in all these Jewish constitutions, however ceremonial, there was something of good,
to wit, in their season, as prefiguring some good: as by circumcision, the purifications,
and other things, the holiness of God was typified,
and that the Israelites ought to be holy, as their God was holy.
In the like manner oaths under shadows and
ceremonies signified the verity of God,
his faithfulness and certainty,
and therefore that we ought in all things to speak and witness the Truth.
But the Witness of Truth was before all oaths, and remains when all oaths are abolished;
and this is the morality of all oaths, and so long as men abide therein,
there is no necessity of, nor place for oaths, as Polybius witnessed, who said,
"`The use of oaths in judgment was rare among the ancients,
but by the growing of perfidiousness,
so grew also the use of oaths.`" To which agreeth Grotius, saying,
"`An oath is only to be used as a medicine, in case of necessity;
a solemn oath is not used but to supply defect.
The lightness of men and their inconstancy begot diffidence,
for which swearing was sought out as a remedy.`" Basil the
Great saith that "`swearing is the effect of sin.`" And Ambrose,
that "`Oaths are only a condescendency for defect.`" Chrysostom
saith that "`an oath entered when evil grew,
when men exercised their frauds, when all foundations were overturned:
that oaths took their beginning from the want of Truth.`" These and the
like are witnessed by many others with the forementioned authors.
But what need of testimonies where the evidence of things speaks itself?
For who will force another to swear,
of whom he is certainly persuaded that he abhors to lie in his words?
And again, as Chrysostom and others say, "`For what end wilt thou force him to swear,
whom thou believest not that he will speak the truth?`"

// lint-disable invalid-characters "§"
§XII.
That then, which was not from the beginning,
which was of no use in the beginning,
which had not its beginning first from the will of God, but from the work of the devil,
occasioned from evil, to wit, from unfaithfulness, lying, deceit;
and which was at first only invented by man as a mutual remedy of this evil,
in which they called upon the names of their idols; yea that, which (as Jerome,
Chrysostom, and others testify) was given to the Israelites by God, as unto children,
that they might abstain from the idolatrous oaths of the heathen (Jer. 12:16),
whatsoever is so, is far from being a moral and eternal precept; and lastly,
whatsoever by its profanation and abuse is polluted with sin,
such as are abundantly the oaths of these times, by so often swearing, and forswearing,
far differs from any necessary and perpetual duty of a Christian:

But oaths are so: Therefore, etc.

Obj.
Sixthly, they object that God swore, therefore to swear is good.

Answ.
I answer with Athanasius, "`Seeing it is certain,
it is proper in swearing to swear by another, thence it appears, that God,
to speak properly, did never swear, but only improperly:
whence speaking to men he is said to swear; because these things, which he speaks,
because of the certainty and immutability of his will, are to be esteemed for oaths.
Compare Ps. 110:4, where it is said, '`The Lord did swear,
and it did not repent him,`' etc. '`And I swore`' (saith he) '`by myself`':
and this is not an oath, for he did not swear by another,
which is the property of an oath, but by himself.
Therefore God swears not according to the manner of men,
neither can we be induced from thence to swear, but let us so do and say,
and show ourselves such by speaking and acting,
that we need not with our hearers an oath,
and let our words of themselves have the testimony of Truth:
for so we shall plainly imitate God.`"^
footnote:[Athan. in pass. & cruc, Domin.]

Obj.
Seventhly, they object: Christ did swear, and we ought to imitate him.

Answ.
I answer, that Christ did not swear; and albeit he had sworn, being yet under the Law,
this would no ways oblige us under the Gospel, as neither circumcision,
or the celebration of the paschal lamb.
Concerning which Jerome saith, "`All things agree not to us, who are servants,
that agreed unto our Lord,`" etc. "`The Lord swore, as Lord,
whom no man did forbid to swear; but unto us, that are servants,
it is not lawful to swear, because we are forbidden by the law of our Lord.
Yet, lest we should not suffer scandal by his example, he hath not sworn,
since he commanded us not to swear.`"^
footnote:[Jer+++.+++, lib. Ep. part. 3. tract. 1. Ep. 2.]

Obj.
Eighthly, they object, that Paul swore, and that often (Rom. 1:9, Phil. 1:8),
saying, "`For God is my witness.`" 2 Cor. 11:10,
"`As the truth of Christ is in me.`" 2 Cor. 1:23,
"`I call God for a record upon my soul.`" "`I speak the truth in Christ,
I lie not`" (Rom. 9:1). "`Behold, before God I lie not`" (Gal. 1:20),
and so requires oaths of others.
"`I obtest^
footnote:[obtest +++=+++ to charge, earnestly entreat.]
you,`" saith he, "`before God and our Lord Jesus Christ.`" 1 Thess. 5:27,
"`I charge you by the Lord that this epistle be read to all
the brethren.`" But Paul would not have done so,
if all manner of oaths had been forbidden by Christ, whose apostle he was.

Answ.
To all which I answer, First, that the using of such forms of speaking are neither oaths,
nor so esteemed by our adversaries: for when, upon occasion,
in matters of great moment we have said, "`We speak the Truth in the fear of God,
and before him, who is our Witness,
and the searcher of our hearts,`" adding such kind of serious attestations,
which we never refused in matters of consequence,
nevertheless an oath hath moreover been required of us,
with the ceremony of putting our hands upon the book, the kissing of it,
the lifting up of the hand or fingers, together with this common form of imprecation,
"`So help me God`"; or, "`So truly let the Lord God Almighty help me.`" Secondly,
this contradicts the opinion of our adversaries,
because that Paul was neither before a magistrate, that was requiring an oath of him,
nor did he himself administer the office of a magistrate,
as offering an oath to any other.
Thirdly, the question is not, what Paul or Peter did,
but what their and our Master taught to be done;
and if Paul did swear (which we believe not),
he had sinned against the command of Christ, even according to their opinion,
because he swore not before a magistrate, but in an epistle to his brethren.

Obj.
Ninthly, they object Isa. 65:16, where speaking of the evangelical times, he saith,
"`That he who blesseth himself in the earth shall bless himself in the God of Truth,
and he that sweareth in the earth, shall swear by the God of Truth;
because the former troubles are forgotten, and because they are hid from mine eyes.
For behold,
I create new heavens and a new earth.`" Therefore in these
times we ought to swear by the name of the Lord.

Answ.
I answer,
It is ordinary for the prophets to express the greatest
duties of evangelical times in Mosaical terms,
as appears, among others, from Jer. 31:38-40; Ezek. 36:25 and chap.
40; and Isa. 45:23: "`I have sworn by myself,
that unto me every knee shall bow,
every tongue shall swear.`" Where the righteousness of the New Jerusalem,
the purity of the Gospel with its spiritual worship,
and the profession of the Name of Christ,
are expressed under forms of speaking used to old Jerusalem,
under the washings of the Law, under the names of ceremonies, the temple, services,
sacrifices, oaths, etc. Yea that which the prophet speaks here of swearing,
the apostle Paul interprets it expressly of confession, saying (Rom. 14:11):
"`For it is written, As I live, saith the Lord, every knee shall bow to me,
and every tongue shall confess to God.`" Which being rightly considered,
none can be ignorant, but these words, which the prophet writes under the Law,
when the ceremonial oaths were in use, to wit,
"`Every tongue shall swear,`" were by the apostle being under the Gospel,
when those oaths became abolished, expressed by "`Every tongue shall confess.`"

Obj.
Tenthly, they object, But the apostle Paul approves oaths used among men,
when he writes (Heb. 6:16): "`For men verily swear by the greater,
and an oath for confirmation is to them an end of
all strife.`" But there are as many contests,
fallacies, and diffidences at this time, as there ever were:
therefore the necessity of oaths doth yet remain.

Answ.
I answer, the apostle tells indeed in this place, what men at that time did,
who lived in controversies and incredulity, not what they ought to have done,
nor what the saints did, who were redeemed from strife and incredulity,
and had come to Christ, the Truth and Amen of God.
Moreover, he only alludes to a certain custom usual among men,
that he might express the firmity of the divine promise,
that he might excite in the saints so much the more confidence in God, promising to them,
not that he might instigate them to swear against the Law of God,
or confirm them in that: no not at all,
for neither doth 1 Cor. 9:24 teach Christians the vain races, whereby men oftentimes,
even to the destruction of their bodies, are wearied to obtain a corruptible prize.
So neither doth Christ, who is the Prince of Peace, teach his disciples to fight,
albeit he takes notice (Luke 14:31), what it behoveth such kings to do,
who are accustomed to fight, as prudent warriors therein.
Secondly, as to what pertains to contests, perfidies, and diffidences among men,
which our adversaries affirm to have grown to such a height
that swearing is at present as necessary as ever;
that we deny not at all, for we see, and daily experience teacheth us,
that all manner of deceit and malice doth increase among worldly men and false Christians,
but not among true Christians: but, because men cannot trust one another,
and therefore require oaths one of another,
it will not therefore follow that true Christians ought to do so,
whom Christ has brought to true faithfulness and honesty,
as well towards God as one towards another,
and therefore has delivered them from contests, perfidies, and consequently from oaths.

Obj.
Eleventhly, they object, We grant that among true Christians, there is not need of oaths,
but by what means shall we infallibly know them?
It will follow then, that oaths are at present needful,
and that it is lawful for Christians to swear, to wit, that such may be satisfied,
who will not acknowledge this and the other man to be a Christian.

Answ.
I answer, It is no ways lawful for a Christian to swear,
whom Christ has called to his essential Truth, which was before all oaths,
forbidding him to swear, and, on the contrary,
commanding him to speak the Truth in all things, to the honor of Christ, who called him;
that it may appear that the words of his disciples may be as truly believed,
as the oaths of all the worldly men.
Neither is it lawful for them to be unfaithful in this, that they may please others,
for that they may avoid their hurt:
for thus the primitive Christians for some ages remained faithful,
who being required to swear, did unanimously answer, "`I am a Christian, I swear not.`"
What shall I say of the heathens, some of whom arrived to that degree?
For Diodorus Siculus, relates (lib. 16),
that "`the giving of the right hand was, among the Persians,
a sign of speaking the Truth`"; and the Scythians, as Qu. Curtius relates, said,
in their conferences with Alexander the Great,
"`Think not that the Scythians confirm their friendship by swearing,
// lint-disable invalid-characters "Æ"
they swear by keeping their promises.`" StobÆus, in his third sermon,
tells that Solomon said, "`A good man ought to be in that estimation,
that he need not an oath,
because it is to be reputed a lessening of his honor if he be forced to swear.`" Pythagoras,
in his oration, among other things, hath this maxim, as that,
which concerns the administration of the commonwealth:
"`Let no man call God to witness by an oath, no not in judgment;
but let every man so accustom himself to speak,
that he may become worthy to be trusted even without
an oath.`" Basil the Great commends Clinias an heathen,
"`that he had rather pay three talents, which are about three thousand pounds,
// lint-disable invalid-characters "Æ"
than swear.`" Socrates, as StobÆus relates (Serm.
14), had this sentence, "`the duty of good men requires,
that they show to the world that their manners and actions are more firm than oaths`";
the same was the judgment of Isocrates.
Plato also stood against oaths in his judgments (De Leg.
12). Quintilianus takes notice, "`that it was of old a kind of infamy,
if any was desired to swear; but to require an oath of a noble man,
was like an examining him by the hangman.`" Marcus Aurelius Antoninus,
the Emperor of Rome, saith, in his description of a good man, "`Such is his integrity,
that he needs not an oath.`" So also some Jews did witness,
as Grotius relates out of Maimonides,
"`It is best for a man to abstain from all oaths.`" The Essenes, as Philo Judaeus relates,
"`did esteem their words more firm than oaths;
and oaths were esteemed among them as needless things.`" And Philo himself,
speaking of the third commandment, explains his mind thus, viz.,
"`It were better altogether not to swear, but to be accustomed always to speak the Truth,
that naked words might have the strength of an oath.`" And elsewhere he saith,
"`It is more agreeable to natural reason, altogether to abstain from swearing; persuading,
that whatsoever a good man saith may be equivalent with an oath.`"

Who then needs further to doubt,
but that since Christ would have his disciples attain the highest pitch of perfection,
he abrogated oaths, as a rudiment of infirmity, and in place thereof,
established the use of Truth?
Who can now any more think,
that the holy martyrs and ancient Fathers of the first three hundred years,
and many others since that time have so opposed themselves to oaths,
that they might only rebuke vain and rash oaths by the creatures, or heathen idols,
which were also prohibited under the Mosaical law;
and not also swearing by the True God in truth and righteousness,
which was there commanded?
as Polycarpus, Justin Martyr (Apolog. 2), and many martyrs, as Eusebius relates.
Tertullian, in his Apolog+++.+++, cap. 32, ad Scap+++.+++, cap. 1, of Idolatry (c. 11).
Clement of Alexandria, Strom+++.+++, lib. 7. Origen, in Matt., Tract. 25.
Cyprian, lib. 3. Athanasius, in pass. & cruc+++.+++, Domini Christi.
Hilary, in Matt. 5:34. Basil the Great, in Ps. 14. Gregory of Nyssa, in Cant. Orat. 13.
Gregory of Nazianzus, in dialog. contra juramenta.
// lint-disable invalid-characters "Æ"
Epiphanius, adversus hÆres+++.+++, lib. 1. Ambrose, de Virg+++.+++, lib. 3;
Idem, in Matt. 5. Chrysostom, in Genes. homil. 15;
Idem, homil+++.+++, in Act Apost. cap. 3. Jerome, Epistol+++.+++, lib.
part 3, Ep. 2. Idem, in Zach+++.+++, lib. 2, cap. 8. Idem,
in Matt., lib. 1, cap. 5. Augustine, de serm. Dom. serm. 28.
Cyril, in Jer. 4. Theodoretus, in Duet. 6. Isidore of Pelusium,
Ep. lib. 1, Epist. 155. Chromatius, in Matt. 5. John of Damascus, lib. 3, cap. 16.
Cassiodorus, in Ps. 94. Isidore of Seville, cap. 31.
Antiochus, in Pandect. script. hom. 62. Bede, in Jac. 5. Haymo,
in Apoc. Ambrosius Ansbertius, in Apoc. Theophylact, in Matt. 5.
Paschasius Radbertus, in Matt. 5. Otho Brunsfelsius,
in Matt. 5. Druthmarus, in Matt. 5. Euthymius Eugubinus, Bibliotheca vet. patr.
in Matt. 5. Oecumenius, in Jac+++.+++, c. 5., v. 12. Anselm, in Matt. 5. Waldenses,
Wycliffe, Erasmus, in Matt. 5., and in Jac. 5.
Who can read these places and doubt longer of their sense in this matter?
And who, believing that they were against all oaths,
can bring so great an indignity to the Name of Christ,
as to seek to subject again his followers to so great an indignity?
Is it not rather time that all good men labour to
remove this abuse and infamy from Christians.

Obj.
Lastly, they object, This will bring in fraud and confusion,
for impostors will counterfeit probity,
and under the benefit of this dispensation will be without fear of punishment.

Answ.
I answer, There are two things only, which oblige a man to speak the Truth: First,
Either the fear of God in his heart and love of Truth,
for where this is there is no need of oaths to speak the Truth.
Or Secondly, the fear of punishment from the judge.
Therefore let there be the same or rather greater punishment appointed to those,
who pretend so great truth in words, and so great simplicity in heart,
that they cannot lie, and so great reverence towards the Law of Christ,
that for conscience sake they deny to swear in any wise, if they fail,
and so there shall be the same good order, yea greater security against deceivers,
as if oaths were continued; and also, by that more severe punishment,
to which these false dissemblers shall be liable.
Hence wicked men shall be more terrified, and good men delivered from all oppression,
both in their liberty and goods: for which cause, for their tender consciences,
God hath often a regard to magistrates and their state,
as a thing most acceptable to him.
But if any can further doubt of this thing, to wit,
if without confusion it can be practised in the commonwealth,
let him consider the state of the United Netherlands,
and he shall see the good effect of it, for there,
because of the great number of merchants, more than in any other place,
there is most frequent occasion for this thing,
and though the number of those that are of this mind be considerable,
to whom the States these hundred years have condescended, and yet daily condescend,
yet nevertheless there has nothing of prejudice followed thereupon to the commonwealth,
government, or good order, but rather great advantage to trade,
and so to the commonwealth.

// lint-disable invalid-characters "§"
§XlII.
Sixthly, The last thing to be considered is revenge and war,
an evil as opposite and contrary to the Spirit and doctrine of Christ as Light to darkness.
For as is manifest by what is said,
through contempt of Christ`'s law the whole world is filled with various oaths, cursings,
blasphemous profanations, and horrid perjuries;
so likewise through contempt of the same law the world is filled with violence,
oppression, murders, ravishing of women and virgins, spoilings, depredations, burnings,
vastations, and all manner of lasciviousness and cruelty;
so that it is strange that men made after the Image of God should have so much
degenerated that they rather bear the image and nature of roaring lions,
tearing tigers, devouring wolves,
and raging boars than of rational creatures endued with reason:
and is it not yet much more admirable that this horrid monster
should find place and be fomented among those men that profess
themselves disciples of our peaceable Lord & Master,
Jesus Christ,
who by excellency is called the Prince of Peace and
hath expressly prohibited his children all violence,
and on the contrary commanded them that according
to his example they should follow patience,
charity, forbearance, and other virtues worthy of a Christian.

Hear then what this great Prophet saith,
whom every soul is commanded to hear under the pain
of being cut off (Matt. 5:38 to the end of the chapter).
For thus he saith: "`Ye have heard that it hath been said, an eye for an eye,
and a tooth for a tooth.
But I say unto you, That ye resist not evil:
but whosoever shall smite thee on thy right cheek, turn to him the other also.
And if any man will sue thee at the law, and take away thy coat,
let him have thy cloak also.
And whosoever shall compel thee to go a mile, go with him twain.
Give to him that asketh thee; and from him that would borrow of thee turn not thou away.
Ye have heard that it hath been said, Thou shalt love thy neighbor and hate thine enemy:
But I say unto you, Love your enemies, bless them that curse you,
do good to them that hate you,
and pray for them which despitefully use you and persecute you.
That ye may be the children of your Father which is in heaven:
for he maketh his sun to rise on the evil, and on the good, and sendeth rain on the just,
and on the unjust.
For if ye love them which love you, what reward have ye?
Do not even the publicans the same?
And if ye salute your brethren only, what do you more than others?
Do not even the publicans so?
Be ye therefore perfect, even as your Father which is in heaven is perfect.`"

These words with a respect to revenge, as the former in the case of swearing,
do forbid some things which were formerly lawful to the Jews,
considering their condition and dispensation,
and command unto such as will be the disciples of Christ, a more perfect, eminent,
and full signification of charity, as also patience and suffering,
than was required of them in that time, state, and dispensation by the Law of Moses.
This is not only the judgment of most, if not all, the ancient Fathers, so called,
of the first three hundred years after Christ, but also of many others,
and in general of all those who have rightly understood
and propagated the law of Christ concerning swearing,
as appears from Justin Martyr in Dialog. cum Tryph. ejusdemque Apolog. 2. Item, ad Zenam.
Tertull+++.+++, de Corona Militis. It+++.+++ Apolog. cap. 21 & 37. It+++.+++ lib.
de Idolol. c. 17-19. It+++.+++ ad Scapulam. cap. 1. It+++.+++ adversus Jud+++.+++, cap.
7 and 9. It+++.+++ adv. Gnost. 13. It+++.+++ adv. Marc. c. 4. It+++.+++ lib.
de patientia. c. 6.10. Orig. cont. Celsum, lib. 3,5,8. It+++.+++ in Josuam, hom. 12 cap. 9.
It+++.+++, in Matt. cap. 26. Tract. 36. Cyprian, Epist. 56.
It+++.+++, ad Cornel. Lactan. de just. lib. 5. c. 18: lib. 6, c. 20.
Ambr+++.+++, in Luc. 22. Chrysostom, in Matt. 5, hom. 18. It+++.+++, in Matt. 26, hom. 85.
It+++.+++, lib. 2. de sacerdotio. It+++.+++, 1 Cor. 13. Chromatius, in Matt. 5. Jerome, ad.
Ocean. It+++.+++, lib. Epist. p. 3. Tom. 1. Ep. 2. Athan+++.+++, de Inc.
Verb. Dei. Cyril Alex+++.+++, lib. 11. in Johan. cap. 25-26.
Yea Augustine, although he vary much in this matter,
notwithstanding in these places he did condemn fighting: Epist.
158-160. It+++.+++, ad. Judices, Epist. 263. It+++.+++, ad. Darium, & lib. 21.
It+++.+++, ad. Faustum+++.+++, cap. 76, lib. 22, de Civit.
ad. Marc. cap. 6, as Sylburgius relates.
Euthym+++.+++, in Matt. 26. and among others of this last^
footnote:[1678 London edition omits "`last.`"]
age Erasmus in Luc. cap. 3 and 22. Ludov. Vives, in Introd.
ad. Sap. J. Ferus, lib. 4. Comment in Matt. 7. & Luc. 22.

From hence it appears that there is so great a connection
betwixt these two precepts of Christ,
that, as they were uttered and commanded by him at one and the same time,
so the same way they were received by men of all ages,
not only in the first promulgation, by the little number of the disciples,
but also after the Christians increased in the first three hundred years,
even so also in the apostasy the one was not left and rejected without the other,
and now again in the restitution and renewed preaching of the eternal Gospel,
they are acknowledged as eternal and unchangeable laws,
properly belonging to the evangelical state and perfection thereof,
from which if any withdraw, he falls short of the perfection of a Christian man.

And truly the words are so clear in themselves, that in my judgment,
they need no illustration to explain their sense:
for it is more easy to reconcile the greatest contradictions as these
laws of our Lord Jesus Christ with the wicked practices of wars,
for they are plainly inconsistent.
Whoever can reconcile this, "`Resist not evil,`" with "`Resist violence by force`"; again,
"`Give also thy other cheek,`" with "`strike again`";
also "`Love thine enemies,`" with "`spoil them, make a prey of them,
pursue them with fire and sword,`" or, "`pray for those that persecute you,
and those that calumniate you,`" with "`persecute them by fines, imprisonments,
and death itself, and not only such, as do not persecute you,
but who heartily seek and desire your eternal and temporal welfare`"; whoever, I say,
can find a means to reconcile these things may be supposed
also to have found a way to reconcile God with the devil,
Christ with Antichrist, Light with darkness, and good with evil.
But if this be impossible, as indeed it is impossible,
so will also the other be impossible,
and men do but deceive themselves and others while they boldly
adventure to establish such absurd and impossible things.

// lint-disable invalid-characters "§"
§XIV.
Nevertheless because some, perhaps through inadvertency,
and by the force of custom and tradition, do transgress this command of Christ,
I shall briefly show how much war doth contradict this precept,
and how much they are inconsistent with one another,
and consequently that war is no ways lawful to such as will be the disciples of Christ.
For

First, Christ commands that we should "`love our enemies`";^
footnote:[Matt. 5:43.]
but war, on the contrary, teacheth us to hate and destroy them.

Secondly the apostle saith that "`we war not after the flesh,`"
and that "`we fight not with flesh and blood.`"^
footnote:[Eph. 6:12.]
But outward war is according to the flesh, and against flesh and blood,
for the shedding of the one and destroying of the other.

Thirdly, the apostle saith that "`the weapons of our warfare are not carnal,
but spiritual.`"^
footnote:[2 Cor. 10:4. Later editors replace "`spiritual`" with "`mighty through God.`"]
But the weapons of outward warfare are carnal,
such as cannon, muskets, spears, swords, etc.,
of which there is no mention in the armour described by Paul.

Fourthly, because James testifies, that wars and strifes come from the lusts,
which war in the members of carnal men:^
footnote:[James 4:1.]
But Christians, that is, those, that are truly saints, "`have crucified the flesh,
with its affections and lusts.`"^
footnote:[Gal. 5:24.]
Therefore they cannot indulge them by waging war.

Fifthly, because the prophets Isaiah and Micah have expressly prophesied,
that in the mountain of the house of the Lord, Christ shall judge the nations,
and then "`they shall beat their swords into ploughshares,`" etc.,^
footnote:[Isa. 2:4; Micah 4:3.]
and the ancient Fathers of the first three hundred years after Christ did affirm
these prophecies to be fulfilled in the Christians of their times,
who were most averse from war, concerning which Justin Martyr, Tertullian,
and others may be seen: which need not seem strange to any,
since Philo Judaeus abundantly testifies of the Essenes,
that "`there was none found among them,
that would make instruments of war.`" But how much more did Jesus come,
that he might keep his followers from fighting,
and might bring them to patience and charity.

Sixthly,
because the prophet foretold that there should "`none hurt
nor kill in all the Holy Mountain`" of the Lord:^
footnote:[Isa. 65:25.]
But outward war is appointed for killing and destroying.

Seventhly,
because Christ said that "`his Kingdom is not of this world,`"
and therefore that "`his servants shall not fight:`"^
footnote:[John 18:36.]
Therefore those that fight are not his disciples nor servants.

Eighthly, because he reproved Peter for the use of the sword, saying,
"`Put up again thy sword into his place: for all they that take the sword,
shall perish with the sword.`"^
footnote:[Matt. 26:52.]
Concerning which Tertullian speaks well (lib.
de idol.), "`How shall he fight in peace without a sword, which the Lord did take away?
For although soldiers came to John and received a form of observation,
if also the centurion believed afterwards,
he disarmed every soldier in disarming of Peter.`" Idem+++.+++, de Coron.
Mil. asketh, "`shall it be lawful to use the sword,
the Lord saying that he that useth the sword shall perish by the sword?`"

Ninthly, because the apostle admonisheth Christians, that they defend not themselves,
neither revenge by rendering evil for evil, but give place unto wrath,
because vengeance is the Lord`'s: "`Be not overcome of evil, but overcome evil with good.
If thine enemy hunger, feed him: if he thirst, give him drink`":^
footnote:[Rom. 12:20-21.]
But war throughout teacheth and enjoineth the quite contrary.

Tenthly, because Christ calls his children to bear his cross,^
footnote:[Mark 8:34.]
not to crucify or kill others: to patience not to revenge: to Truth and simplicity,
not to fraudulent stratagems of war, or to play the sycophant,
which John himself forbids: to flee the glory of this world;
not to acquire it by warlike endeavours:
Therefore war is altogether contrary unto the Law and Spirit of Christ.

// lint-disable invalid-characters "§"
§XV. Obj.
But they object that it is lawful to war,
because Abraham did war before the giving of the Law,
and the Israelites after the giving of the Law.

Answ.
I answer as before, 1. that Abraham offered sacrifices at that time,
and circumcised the males: which nevertheless are not lawful for us under the Gospel.

2+++.+++ That neither defensive nor offensive war was lawful to the Israelites,
of their own will, or by their own counsel or conduct,
but they were obliged at all times, if they would be successful,
first to inquire the oracle of God.

3+++.+++ That their wars against the wicked nations were a figure of
the inward war of the true Christians against their spiritual enemies,
in which we overcome the devil, the world, and the flesh.

4+++.+++ Something is expressly forbidden by Christ (Matt. 5:34),
which was granted to the Jews in their time, because of their hardness; and,
on the contrary, we are commanded that singular patience and exercise of love,
which Moses commanded not to his disciples.
From whence Tertullian saith well against Marc+++.+++,
"`Christ truly teacheth a new patience,
even forbidding the revenge of an injury, which was permitted by the Creator.`"
And (lib. de patien.)
"`The law finds more than it lost, by Christ`'s saying, Love your enemies.`"
And in the time of Clem. Alex. Christians were so far from wars,
that he testified that they had no marks or signs of violence among them, saying,
"`Neither are the faces of idols to be painted,
to which so much as to regard is forbidden: neither sword nor bow to them,
that follow peace, nor cups to them who are moderate and temperate,`"
as Sylvius Disc. de Rev. Belg.

Obj.
Secondly, they object that defence is of natural right,
and that religion destroys not nature.

Answ.
I answer, Be it so, but to obey God, and commend ourselves to him in faith and patience,
is not to destroy nature, but to exalt and perfect it; to wit,
to elevate it from the natural to the supernatural life,
by Christ living therein and comforting it,
that it may do all things and be rendered more than conqueror.

Obj.
Thirdly,
they object that John did not abrogate or condemn war when the soldiers came unto him.

Answ.
I answer, What then?
The question is not concerning John`'s doctrine, but Christ`'s, whose disciples we are,
not John`'s: for Christ and not John is that Prophet whom we ought all to hear;
and albeit that Christ said that "`a greater than John the Baptist was not among men
born of women,`" yet he adds that "`the least in the Kingdom of God is greater than he.`"^
footnote:[Luke 7:28.]
But what was John`'s answer, that we may see if it can justify the soldiers of this time?
For if it be narrowly minded,
it will appear that what he proposeth to soldiers doth manifestly forbid them that employment,
for he commands them "`not to do violence to any man, not to defraud any man,`"^
footnote:[Later editors replace "`not to defraud any man`" with "`nor to accuse any falsely.`"]
but that they "`be content with their wages.`"^
footnote:[Luke 3:14.]
Consider then what he dischargeth to soldiers, viz,
not to use violence or deceit against any, which being removed,
let any tell how soldiers can war?
For is not craft, violence, and injustice, three properties of war,
and the natural consequences of battles?

Obj.
Fourthly, they object that Cornelius,
and that centurion of whom there is mention made,^
footnote:[Matt. 8:5.]
were soldiers, and there is no mention that they laid down their military employments.

Answ.
I answer, Neither read we that they continued in them.
But it is most probable that,
if they continued in the doctrine of Christ (and
we read not any where of their falling from the faith),
that they did not continue in them;
especially if we consider that two or three ages
afterwards Christians altogether rejected war,
or at least a long while after that time, if the emperor Marc.
Aurel.
Anton.
be to be credited, who writes thus: "`I prayed to my country gods.
But when I was neglected by them, and observed myself pressed by the enemy,
considering the fewness of my forces, I called to one,
and entreated those who with us are called Christians,
and I found a great number of them: and I forced them with threats:
which ought not to have been; because afterwards I knew their strength and force;
therefore they betook themselves neither to the use of darts, nor trumpets,
for they use not to do so, for the cause and name of their God,
which they bear in their consciences.`" And this was
done about an hundred and sixty years after Christ.
To this add those words, which in Justin Martyr the Christians answer,
RESTORE-GREEK, that is, "`We fight not with our enemies`";
and moreover the answer of Martin to Julian the Apostate, related by Sulpicius Severus:
"`I am a soldier of Christ,
therefore I cannot fight,`" which was three hundred years after Christ.
It is not therefore probable, that they continued in warlike employments.
// lint-disable invalid-characters "é"
How then is Vincent of Lérins and the Papists consistent with their maxim, "`That,
which always, everywhere,
and by all was received,`" etc.? And what becomes of the priests with their oath,
that they neither ought, nor will,
interpret the Scripture but according to the universal consent of the Fathers, so called?
For it is as easy to obscure the sun at mid-day,
as to deny that the primitive Christians renounced all revenge and war.

And albeit this thing be so much known to all,
yet it is as well known that almost all the modern sects
live in the neglect & contempt of this law of Christ,
and likewise oppress others,
who in this agree not with them for conscience sake towards God,
even as we have suffered much in our country,
because we neither could ourselves bear arms, nor send others in our place,
nor give our money for the buying of drums, standards, and other military attire:
and lastly, because we could not hold our doors, windows, and shops close,
for conscience sake,
upon such days as fasts and prayers were appointed for to desire a blessing upon,
and success for, the arms of that Kingdom or Commonwealth (under which we live),
neither give thanks for the victories acquired by the effusion of much blood.
By which forcing of the conscience,
they would have constrained our brethren living in divers kingdoms, at war together,
to have implored our God for contrary and contradictory things,
and consequently impossible;
for it is impossible that two parties fighting together should both obtain the victory.
And because we cannot concur with them in this confusion,
therefore we are subject to persecution.
Yea and others, who with us do witness that the use of arms is unlawful to Christians,
do look asquint upon us:
but which of us two do most faithfully observe this testimony against arms?
either they who at certain times at the magistrate`'s
order do close up their shops and houses,
and meet in their assembly,
praying for the prosperity of their arms or giving thanks for some victory or other,
whereby they make themselves like to those that approve wars and fighting?
Or we, which cannot do these things, for the same cause of conscience,
lest we should destroy, by our works, what we establish in words,
we shall leave to the judgment of all prudent men?

Obj.
Fifthly, they object that Christ (Luke 22:36), speaking to his disciples,
commands them that he that then had not a sword, should sell his coat and buy a sword:
Therefore, say they, arms are lawful.

Answ.
I answer, some indeed understand this of the outward sword,
nevertheless regarding only that occasion,
otherwise judging that Christians are prohibited wars under the Gospel:
among which is Ambrose, who upon this place speaks thus:
"`O Lord! why commandest thou me to buy a sword, who forbiddest me to smite with it?
Why commandest thou me to have it, whom thou prohibitest to draw it?
Unless perhaps a defence be prepared, not a necessary revenge,
and that I may seem to have been able to revenge, but that I would not.
For the law forbids me to smite again: and therefore perhaps he said to Peter,
offering two swords, '`It is enough,`' as if it had been lawful, until the Gospel time,
that, in the Law, there might be a learning of equity,
but in the Gospel a perfection of goodness.`" Others
judge Christ to have spoken here mystically,
and not according to the letter, as Origen upon Matt. 19. saying,
"`If any looking to the letter, and not understanding the will of the words,
shall sell his bodily garment, and buy a sword,
taking the words of Christ contrary to his will, he shall perish.
But concerning which sword he speaks is not proper here to mention.`"
And truly when we consider the answer of the disciples,
"`Master, behold, here are two swords,`" understanding it of outward swords;
and again Christ`'s answer, "`It is enough,`" it seems that Christ would not that the rest,
who had not swords (for they had only two swords), should sell their coats,
and buy an outward sword.
Who can think that, matters standing thus, he should have said two was enough?
But however it is sufficient that the use of arms is unlawful under the Gospel.

Obj.
Sixthly, they object that the Scriptures and old Fathers, so called,
did only prohibit private revenge, not the use of arms for the defence of our country,
body, wives, children, and goods, when the magistrate commands it,
seeing the magistrates ought to be obeyed:
Therefore albeit it be not lawful for private men to do it of themselves,
nevertheless they are bound to do it by the command of the magistrate.

Answ.
I answer, If the magistrate be truly a Christian, or desires to be so,
he ought himself in the first place to obey the command of his Master, saying,
"`Love your enemies,`" etc., and then he could not command us to kill them:
but if he be not a true Christian, then ought we to obey our Lord and King Jesus Christ,
to whom he ought also to obey:
for in the Kingdom of Christ all ought to submit to his laws,
from the highest to the lowest, that is, from the king to the beggar,
and from Caesar to the clown.
But (alas!) where shall we find such an obedience?
O deplorable fall! concerning which Ludov. Viv. writes well
(lib. de con. vit. Christ. sub. Turc.), by relation of Fredericus Sylvius, Disc.
de Revol. Belg+++.+++, p. 85:
"`The Prince entered into the Church, not as a true and plain Christian:
which had indeed been most happy and desirable, but he brought in with him his nobility,
his honors, his ARMS, his ensigns, his triumphs, his haughtiness, his pride,
his superciliousness; that is,
he came into the house of Christ accompanied with the devil,
and which could no ways be done, he would have joined two houses and two cities together,
God`'s and the Devil`'s, which could not more be done, than Rome and Constantinople,
which are distant by so long a tract both of sea and land.
('`What communion, saith Paul,
is there betwixt Christ and Belial?`') Their zeal cooled by degrees,
their faith decreased, their whole piety degenerated,
instead whereof we make now use of shadows and images, and, as he saith,
I would we could but retain these!`" Thus far Vives.
But lastly, as to what relates to this thing,
since nothing seems more contrary to man`'s nature, and seeing, of all things,
the defence of oneself seems most tolerable, as it is most hard to men,
so it is the most perfect part of the Christian religion,
as that wherein the denial of self and entire confidence in God doth most appear,
and therefore Christ and his apostles left us hereof a most perfect example.
As to what relates to the present magistrates of the Christian world,
albeit we deny them not altogether the name of Christians,
because of the public profession they make of Christ`'s name, yet we may boldly affirm,
that they are far from the perfection of the Christian religion;
because in the state in which they are (as in many places before I have largely observed),
they have not come to the pure dispensation of the Gospel, and therefore,
while they are in that condition, we shall not say that war,
undertaken upon a just occasion, is altogether unlawful to them.
For even as circumcision and the other ceremonies
were for a season permitted to the Jews,
not because they were either necessary, or of themselves,
or lawful at that time after the resurrection of Christ,
but because that Spirit was not yet raised up in them,
whereby they could be delivered from such rudiments;
so the present confessors of the Christian name, who are yet in the mixture,
and not in the patient suffering spirit,
are not yet fitted for this form of Christianity,
and therefore cannot be undefending themselves, until they attain that perfection:
but for such, whom Christ has brought hither,
it is not lawful to defend themselves by arms,
but they ought over all to trust to the Lord.

// lint-disable invalid-characters "§"
§XVI.
But lastly, to conclude, If to give and receive flattering titles,
which are not used because of the virtues inherent in the persons,
but are for the most part bestowed by wicked men upon such as themselves; if to bow,
scrape and cringe to one another; if at every time to call one another humble servant,
and that most frequently without any design of real service,
if this be the honor that comes from God, and not the honor that is from below,
then indeed our adversaries may be said to be believers,
and we condemned as proud and stubborn in denying all these things.
But if with Mordecai to refuse to bow to proud Haman,^
footnote:[Est. 3:5.]
and with Elihu not to give flattering titles to men,
lest we should be reproved of our Maker;^
footnote:[Job 32:21-22.]
and if according to Peter`'s example and the angel`'s advice, to bow only to God,
and not to our fellow servants; and if to call no man Lord, nor Master,
except under particular relations, according to Christ`'s command, I say,
if these things be not to be reproved, then are we not blameworthy in so doing.

If to be vain and gaudy in apparel, if to paint the face, and plait the hair;
if to be clothed with gold and silver and precious stones,
and if to be filled with ribbands and lace, be to be clothed in modest apparel;
and if these be the ornaments of Christians, and if that be to be humble, meek,
and mortified, then are our adversaries good Christians indeed, and we proud, singular,
and conceited, in contenting ourselves with what need and conveniency calls for,
and condemning what is more as superfluous: but not otherwise.

If to use games, sports, plays; if to card, dice, and dance; if to sing, fiddle,
and pipe; if to use stage-plays and comedies, and to lie, counterfeit, and dissemble,
be to fear always; and if that be to do all things to the glory of God;
and if that be to pass our sojourning here in fear; and if that be to use this world,
as if we did not use it;
and if that be not to fashion ourselves according to our former lusts;
to be not conformable to the spirit and vain conversation of this world;
then are our adversaries, notwithstanding they use these things, and plead for them,
very good, sober, mortified, and self-denied Christians,
and we justly to be blamed for judging them, but not otherwise.

If the profanation of the Holy Name of God,
if to exact oaths one from another upon every light occasion;
if to call God to witness in things of such a nature in which no earthly
king would think himself lawfully and honorably to be a witness,
be the duties of a Christian man; I shall confess,
that our adversaries are excellent good Christians, & we wanting in our duty:
but if the contrary be true,
of necessity our obedience to God in this thing must be acceptable.

If to revenge ourselves, or to render injury, evil for evil, wound for wound,
to take eye for eye, tooth for tooth; if to fight for outward and perishing things,
to go a warring one against another, whom we never saw,
nor with whom we never had any contest, nor anything to do,
being moreover altogether ignorant of the cause of the war,
but only that the magistrates of the nations foment quarrels one against another,
the causes whereof are for the most part unknown to the soldiers that fight,
as well as upon whose side the right or wrong is; and yet to be so furious,
and rage one against another, to destroy and spoil all,
that this or the other worship may be received or abolished; If to do this,
and much more of this kind, be to fulfill the law of Christ,
then are our adversaries indeed true Christians, and we miserable heretics,
that suffer ourselves to be spoiled, taken, imprisoned, banished, beaten,
and evilly entreated, without any resistance, placing our trust only in god,
that he may defend us, and lead us by this way of the Cross unto his Kingdom.
But if it be otherways,
we shall certainly receive the reward which the Lord
hath promised to those that cleave to him,
and, in denying themselves, confide in him.

And, to sum up all, If to use all these things, and many more that might be instanced,
be to walk in the strait way that leads to Life, be to take up the Cross of Christ;
be to die with him to the lusts and perishing vanities of this world;
and to arise with him in newness of Life; and sit down with him in the heavenly places;
Then our adversaries may be accounted such,
and they need not fear they are in the broad way that leads to destruction;
and we are greatly mistaken that have laid aside all these things for Christ`'s sake,
to the crucifying of our own lusts, and to the procuring to ourselves shame, reproach,
hatred, and ill-will from the men of this world:
not as if by so doing we judged to merit heaven but as knowing they are contrary to
the will of him who redeems his children from the love of this world and its lusts,
and leads them in the ways of Truth and holiness in which they take delight to walk.
