== THE CONCLUSION

If in God`'s fear, candid reader,
thou appli`'st thyself to consider this system of religion here delivered,
with its consistency and harmony, as well in itself as with the Scriptures of Truth;
I doubt not but thou wilt say with me and many more,
that this is the spiritual day of Christ`'s appearance,
wherein he is again revealing the ancient paths of Truth and righteousness.
For thou mayest observe here the Christian religion, in all its parts,
truly established and vindicated, as it is a living, inward, spiritual, pure,
and substantial thing, and not a mere form, show, shadow, notion, and opinion,
as too many have hitherto held it,
whose fruits declare they wanted that which they bear the name of;
and yet many of those are so in love with their empty forms and shadows,
that they cease not to calumniate us for commending and calling them to the Substance,
as if we therefore denied or neglected the true form and outward part of Christianity,
which indeed is (as God the searcher of hearts knows) a very great slander.

Thus, because we have desired people earnestly to feel after God near and in themselves,
telling them that their notions of God, as he is beyond the clouds,
will little avail them if they do not feel him near:
hence they have sought maliciously to infer that
we deny any God except that which is within us.
Because we tell people that it is the Light and the Law within,
and not the letter without, that can truly tell them their condition,
and lead them out of all evil:
hence they say we vilify the Scriptures and set up our own imaginations above them.
Because we tell them that it is not their talking or believing of Christ`'s outward life,
sufferings, death, and resurrection, no more than the Jews crying,
"`the Temple of the Lord, the temple of the Lord,`" that will serve their turn,
or justify them in the sight of God, but that they must know Christ in them,
whom they have crucified, to be raised, and to justify them,
and redeem them from their iniquities: hence they say, we deny the life, death,
and sufferings of Christ, justification by his blood, and remission of sins through him.
Because we tell them, while they are talking and determining about the resurrection,
that they have more need to know the Just One, whom they have slain,
raised in themselves,
and to be sure they are partakers of the first resurrection, and that if this be,
they will be the more capable to judge of the second:
hence they say that we deny the resurrection of the body.
Because, when we hear them talk foolishly of heaven and hell, and the last judgment,
we exhort them to come out of that hellish condition they are in,
and come down to the judgment of Christ in their own hearts,
and believe in the Light and follow it,
that so they may come to sit in the heavenly places that are in Christ Jesus,
hence they maliciously say that we deny any heaven or hell but that which is within us,
and that we deny any general judgment:
which slanders the Lord knows are foully cast upon us whom God hath raised for this end,
and gathered us, that by us he might confound the wisdom of the wise,
and bring to nought the understanding of the prudent, and might,
in and by his own Spirit and Power in a despised
people (that no flesh might glory in his presence),
pull down that dead, dark, corrupt image, and mere shadow and shell of Christianity,
wherewith Antichrist hath deceived the nations,
for which end he hath called us to be a first-fruits of those that serve him,
and worship him no more in the oldness of the letter, but in the newness of the Spirit.

And though we be few in number, in respect of others, and weak as to outward strength,
which we also altogether reject; and foolish,
if compared with the wise ones of this world, yet as God hath prospered us,
notwithstanding much opposition, so will he yet do; that neither the art, wisdom,
nor violence of men or devils shall be able to quench that little spark that hath appeared,
but it shall grow to the consuming of whatsoever shall stand up to oppose it.
The mouth of the Lord hath spoken it,
yea he that hath risen in a small remnant shall arise and
go on by the same arm of power in his spiritual manifestation,
until he hath conquered all his enemies,
until all the kingdoms of the earth become the Kingdom of Christ Jesus.

Unto him that hath begun this work, not among the rich or great ones,
but among the poor and small, and hath revealed it not to the wise and learned,
but unto the poor, unto babes and sucklings,
even to him the Only-Wise and Omnipotent God be honor, glory, thanksgiving, and renown,
from henceforth and forever.
_Amen._
Halelujah.
